### ISSUE TITLE
Add flag for Makefile dependency rules generation

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1214]
Add flag that will make cython output a rule suitable for make describing the dependencies of the main source file.

like this:

```
$ cython -M foo.pxd

foo.c: bar.pxd
```

Migrated from http://trac.cython.org/ticket/655

**Comment by gerion0** [comment]
This would be useful for meson, too. For example, the pxd file is _not_ tracked in [this](https://github.com/mesonbuild/meson/blob/master/test%20cases/python3/3%20cython/libdir/meson.build#L1) test case.

**Comment by scoder** [comment]
Since the `cython` tool does not deal with dependencies (it's a one-shot command), a better place to implement this seems to be the `cythonize` frontend.

**Comment by dcbaker** [comment]
cython still needs to deal with C headers though, correct?

**Comment by scoder** [comment]
Cython's dependency collection in `Cython.Build.Dependencies` does not look at transitive header files but only those that are mentioned directly via `cdef extern from` clauses. It wouldn't be able to decide which of them will be included in a platform/configuration specific way by the C preprocessor anyway.

It transitively collects .pxd, and .pxi files, as well as include files from `cdef extern from` sections (.h, .c, whatever people use there).

I'm pretty sure it also currently does not look into verbatim C code sections (docstrings of `cdef extern from`), so if they include anything, it won't be noticed. That's probably ok – if users want to include something here, they can just name it as the input file of that section. And if they include different files in a platform dependent way, then a) Cython can't decide it anyway and b) we are probably dealing with system provided header files which don't normally change.

**Comment by dcbaker** [comment]
I guess for cython the header files don't matter as long as they shouldn't trigger cython to re-compiler/transpile (at least from Meson's point of view) as the C/C++ compiler will generate its own depfile that would cover the inclusion of C language headers, so for Meson I guess that just means pxd files?

**Comment by scoder** [comment]
The feature was only added to the `cythonize` command for now, in #4563.

Whether it should be added to the `cython` command as well is less obvious since it does not currently deal with dependencies at all. Only `cythonize` has this intention.

**Comment by scoder** [comment]
Backported to 0.29.27 in https://github.com/cython/cython/pull/4576
