### ISSUE TITLE
Dissallow assignment of vtab functions

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1228]
```
cdef class A:
    cpdef int test (self):
        pass
    def __init__(self, bint bad) :
        if bad:
            self.test = NULL # messes all instance of A
```

Migrated from http://trac.cython.org/ticket/669

**Comment by da-woods** [comment]
Currently get `Cannot assign type 'void *' to 'int (A, int __pyx_skip_dispatch)'`, which could possibly be clearer, but avoids users doing too much damage.
