### ISSUE TITLE
Native support for PEP 393 (new unicode object structure)

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1276]
Py3.3 is expected to implement PEP 393, the flexible Unicode string representation.

http://www.python.org/dev/peps/pep-0393/

http://wiki.python.org/moin/SummerOfCode/2011/PEP393

Cython should adapt its optimisations for the unicode type accordingly, especially the for-loop.

Migrated from http://trac.cython.org/ticket/721

**Comment by jdemeyer** [comment]
See also #1655
