### ISSUE TITLE
pyximport of .py files should use language_level=3 in Python 3

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1288]
When running under Python 3, any .py file that pyximport is triggered for can be expected to be in Python 3 syntax. Currently, pyximporting simply fails because of syntax errors because it does not configure the language level at all. Therefore, pyximport's import hook should automatically switch to -3 mode under Python 3 when compiling a .py file.

Note that the same is not true for .pyx files, which may or may not in Py3 syntax. So there should additionally be a way to configure the language level explicitly when installing the pyximport import hooks.

Migrated from http://trac.cython.org/ticket/733

**Comment by hermidalc** [comment]
Unless I'm doing something wrong, as of 0.29.7 this is still not implemented at least when using pyximport.  If you do not specify the ```language_level``` manually it gives you the ```FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release!``` even though it should know it's using Python 3.x.

**Comment by scoder** [comment]
@hermidalc are you sure you are referring to `.py` files? The automatic setting does not apply to `.pyx` files.
https://github.com/cython/cython/blob/19656b2d12bd2da5637819a6f0843651eea10014/pyximport/pyximport.py#L346-L347

**Comment by hermidalc** [comment]
> @hermidalc are you sure you are referring to `.py` files? The automatic setting does not apply to `.pyx` files.
> 
> https://github.com/cython/cython/blob/19656b2d12bd2da5637819a6f0843651eea10014/pyximport/pyximport.py#L346-L347

Ok, sorry didn't know that.
