### ISSUE TITLE
extension types lack a dict to assign arbitrary attributes

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1301]
It should be possible to do this:

```
cdef class MyType(object):
    cdef dict __dict__

m = MyType()
m.xyz = 5
```

Currently, extension types do not support the assignment of arbitrary attributes at all.

http://thread.gmane.org/gmane.comp.python.cython.devel/9638

Migrated from http://trac.cython.org/ticket/745

**Comment by scoder** [comment]
Supported since Cython 0.25.
