### ISSUE TITLE
Test failures and compiler warnings with the clang compiler

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1325]
A while ago I reported a few issues on the cython-users mailing list:
https://groups.google.com/d/topic/cython-users/tWpJJS40KJI/discussion

I believe all the issues that were discussed are still present and are all related to the clang compiler:
1. OpenMP tests should be skipped with the clang compiler
2.  Replace self-assignment hack to avoid unused parameter warnings with CYTHON_UNUSED
3. __Pyx_Method_ClassMethod sometimes included unnecessarily
4. Make runtests.py display the commands it is executing

Please see the comments by Stefan Behnel in the mailing list thread.

Attached find complete Cython build and test logs for 5fcc3e2e051e04fea2cf6d07cd0de94c1e11dca8 for Mac OS X Lion with Xcode 4.3.
The test failures are still there, the compiler warnings changed a bit in the meantime, especially I think there are quite a few new unused function warnings.

Given that clang is getting more and more common (default compiler on the Mac) and finds issues gcc doesn't, would it be possible to include clang on the Cython build / test server (this was mentioned as a possibility by Stefan in the mailing list thread)?
If not I would be of course happy to re-run any builds / tests to diagnose these issues.

Thank you for developing Cython!

At 2012-04-22T22:03:20Z **deil** added attachment [cython-build.log](https://gist.github.com/541ee754a359bbcd805aeefadadd86c4)

At 2012-04-22T22:03:52Z **deil** added attachment [cython-tests.log](https://gist.github.com/71acbeff8f353504632b8180871ba0a1)

Migrated from http://trac.cython.org/ticket/770

**Comment by scoder** [comment]
This is essentially done. Not worth keeping it open.
