### ISSUE TITLE
outermost iterable in genexpr is evaluated too late

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1351]
This test works differently in Python than in Cython:

```
>>> def seff():
...     print("TEST")
...     return range(10)
... 
>>> g = (i for i in seff())
TEST
>>> list(g)
[1, 2, 3, 4, 5, 6, 7, 8, 9](0,)
>>> g = (i for i in (v for v in seff()))
TEST
```

Cython evaluates the outermost iterable of a generator expression inside of the generator body, CPython evaluates is outside, i.e. _before_ creating the generator.

This is a follow-up ticket to http://trac.cython.org/ticket/600.

Migrated from http://trac.cython.org/ticket/823

**Comment by scoder** [comment]
Duplicate of #1159.
