### ISSUE TITLE
Fix cython's deep C-stacks upon deallocation

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1354]
Once you know about python's `trashcan` that is used in its dealloc methods and that cython does not make use of it, it's not hard to cause a crash in deallocation of a cython class:

```
cython("""
cdef class A(object):
    cdef object ref
    def __init__(self,ref):
        self.ref = ref

""")
```

A long linked list of these will quickly exhaust the C-stack (set a ulimit on the stack if you have a lot of memory):

```
print "allocating a"
a=A(None)
for i in range(10**6):
    a=A(a)

print "deleting a"
del a
print "done deleting a"
```

Once you interleave with a python container type (tuple, for instance), the trashcan starts to kick in. The following runs without problem.

```
b=A(None)
print "allocating b"
for i in range(10**6):
    b=A((b,))

print "deleting b"
del b
print "done deleting b"
```

This issue came up as a side issue on http://trac.sagemath.org/sage_trac/ticket/13896. The trashcan is a rather complicated thing to get working right. In particular, cython must take precautions to ensure that once deallocation is started on an object, it isn't put into the trashcan in deallocs of base types.

This is also sage http://trac.sagemath.org/sage_trac/ticket/13901

Migrated from http://trac.cython.org/ticket/797

**Comment by jdemeyer** [comment]
This is another instance: https://trac.sagemath.org/ticket/27267

**Comment by jdemeyer** [comment]
> In particular, cython must take precautions to ensure that once deallocation is started on an object, it isn't put into the trashcan in deallocs of base types.

Good point. I'll look into it.

**Comment by jdemeyer** [comment]
What about something like
```C
void foo_tp_dealloc(PyObject* op)
{
    /* Only enable the trashcan when this is the actual tp_dealloc of the type,
       not when we're being called recursively by the tp_dealloc of a subclass */
    int do_trashcan = (Py_TYPE(op)->tp_dealloc == foo_tp_dealloc);
    if (!do_trashcan) goto skip_trashcan_begin;
    Py_TRASHCAN_SAFE_BEGIN(op);
    skip_trashcan_begin:
    /* Usual deallocator goes here */
    if (!do_trashcan) goto skip_trashcan_end;
    Py_TRASHCAN_SAFE_END(op);
    skip_trashcan_end:
}
```

It won't win prices for beautiful code, but I'll try to get this working.

**Comment by jdemeyer** [comment]
A fix for the trashcan in CPython: https://github.com/python/cpython/pull/11841

**Comment by jdemeyer** [comment]
The `goto` trick I posted above doesn't work in C++ :-(

How bad would it be to drop support for Python < 2.7.4? I ask because the trashcan macros have been changed between 2.7.3 and 2.7.4
