### ISSUE TITLE
const fails when used as the argument to a template of a template

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1355]
This works:

```
from libcpp.vector cimport vector

cdef extern from "Test.hpp":
    cdef vector[char](const) f()
```

As does this:

```
from libcpp.vector cimport vector

cdef extern from "Test.hpp":
    cdef vector[f()
```

But this causes a Cython parse error on Cython 0.18:

```
from libcpp.vector cimport vector

cdef extern from "Test.hpp":
    cdef vector[vector[const char](vector[char]])] f()
```

Migrated from http://trac.cython.org/ticket/798

**Comment by scoder** [comment]
The obvious work-around is a `ctypedef`, but it seems worth fixing.

The parser calls `p_buffer_or_template()` to parse the `[…]` part, which then calls `p_positional_and_keyword_args()` to parse what's inside of the brackets. I guess that simply doesn't allow template type declarations. It could, though. That would probably also help with template type parsing in function signatures.

Also needs a test, probably in one of the tests/run/cpp_*.pyx modules.

**Comment by shwina** [comment]
Taking a look
