### ISSUE TITLE
Py3 mode renames "str" type to "unicode" in auto-embedded signature

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1370]
Consider this:

```
$ cat mylib.pyx
#cython: embedsignature=True
def listdir(str path):
    '''Print out *path*'''

    print(path)

$ cython --version
Cython version 0.19

$ cython mylib.pyx; grep 'Print out' mylib.c | head -1
static char __pyx_doc_5mylib_listdir[= "listdir(str path)\nPrint out *path*";

$ cython -3 mylib.pyx; grep 'Print out' mylib.c | head -1
static char __pyx_doc_5mylib_listdir[](]) = "listdir(unicode path)\nPrint out *path*";
```

In other words, when running with `-3`, the `str` type in the function signature becomes `unicode`.

I guess the idea is that when compiled for Python 2, the extension will expect a unicode object. However, when compiled under Python 3 (which is probably the more likely case), the signature is just confusing as there is no unicode type.

Moreover, the guess that under Python 2.x the function expects an unicode object is not necessarily correct. In my case, the function truly expects str in both Python 2.x and 3.x. Therefore, I think it would be just not rename any types when generating the docstring signature.

Migrated from http://trac.cython.org/ticket/812

**Comment by dgrunwald** [comment]
This bug also affects the `inspect.signature()` result:
```
# cython: binding=True
def f(path: str, a: int = 0, b: bool = True) -> typing.List[str]:
    pass
```

```
>>> testmodule.f.__annotations__
{'path': 'unicode', 'a': 'int', 'b': 'bool', 'return': typing.List[str]}
```

**Comment by scoder** [comment]
This will be easy to fix when we drop Py2 support.

**Comment by scoder** [comment]
Actually, why not change it already in Cy3.0…

PR welcome to always output `str` instead. See the `AutoDocTransform`.

**Comment by McSinyx** [comment]
How does this relate to #2796 if I may ask?

**Comment by scoder** [comment]
Postponing this to 3.1 again, since it's much cleaner to change it then.

**Comment by fahhem** [comment]
This seems to cause errors with py3 typing code that uses `str` as a type.

Original source code (some YAML handling code):
```py
AnyValue = Union[float, str, int, Dict]
```

Error at runtime:
```
Traceback (most recent call last):
...snip...
    AnyValue = Union[float, str, int, Dict]
NameError: name 'unicode' is not defined
```

The code runs under CPython3, but fails due to this rewriting. I'd be happy to send a PR up, though I can't find where the str->unicode translation is happening. I looked at [AutoDocTransforms](https://github.com/cython/cython/blob/master/Cython/Compiler/AutoDocTransforms.py) though I don't see how that does the translation, nor how I would use it to avoid the translation.
