### ISSUE TITLE
cycache fingerprint does not look at compiler directives and Cython version

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1397]
The compiler directives used for Cythonizing should be part of the fingerprint for cycache.

Migrated from http://trac.cython.org/ticket/842

**Comment by saraedum** [comment]
cc @saraedum

**Comment by jdemeyer** [comment]
Does the version of Cython affect the fingerprint? It clearly should.

**Comment by robertwb** [comment]
Yes, it does.
