### ISSUE TITLE
Allow cdef class inheritance from builtin exception types

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1416]
In all supported CPython versions (Py2.6+), exceptions are implemented as builtin types. It would be nice to allow users to inherit from them in cdef classes, i.e. to directly support

```
cdef class MyException(Exception):
    cdef int error_info
```

Migrated from http://trac.cython.org/ticket/862

**Comment by buchuki** [comment]
In the meantime, is there any way to support this indirectly?

**Comment by robertwb** [comment]
That would work (but I don't see how to simultaneously support Python 2 and 3). Generally there's little need to do this though. You could always write a cdef class that is wrapped by a non-cdef extension subclass too.

**Comment by robertwb** [comment]
I take that back, it looks like we special case builtins to work in Python 2 already.

**Comment by robertwb** [comment]
And fully fixed at b1d7b0de9e4cdc1eb866661e34f3da8892993fba.

**Comment by jdemeyer** [comment]
Any reason that this was only done for `Exception` and not other classes like `ValueError`?
