### ISSUE TITLE
binding directive undocumented

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1420]
The `@cython.binding(True)` directive does not appear to have any documentation. I recently discovered (via googling for old forum posts) that I needed to use it for compatibility with some introspection code that examines `f.func_code.co_varnames`. Assuming this is a supported feature, it should be documented (and if it's not it might need an explicit disclaimer somewhere).

Migrated from http://trac.cython.org/ticket/866

**Comment by scoder** [comment]
See http://docs.cython.org/en/latest/src/reference/compilation.html#compiler-directives
