### ISSUE TITLE
cimported ctuples don’t compile their declaration

### ISSUE THREAD

**Issue by robertwb** [cython/cython#1427]
When a module imports a declaration containing a ctuple from a pxd, the C declaration for the ctuple will be missing:

a.pyx:

```
cimport b
b.get_a_ctuple()
```

b.pxd:

```
cdef (int, int) get_a_ctuple()
```

The `__pyx_ctuple_int__and_int` struct and typedef will then be missing, while if `get_a_ctuple` had been declared in a’s module (even in a pxd) it would have been fine.

Migrated from http://trac.cython.org/ticket/873

**Comment by Baekalfen** [comment]
Might be the same as #2745

**Comment by ajfriend** [comment]
+1

I'd love to see this issue resolved!

**Comment by scoder** [comment]
PR welcome.

**Comment by isotherm** [comment]
Tests for additional failure cases are included in the PR, specifically:

* cimported typedef declaration including a ctuple
* cimported function with optional arguments including a ctuple
* cimported class method with ctuple argument

**Comment by Baekalfen** [comment]
Is it ready for me to pull down and test on my code?

**Comment by isotherm** [comment]
Sure, please try it and report back. It works for my use case locally, and the tests pass.

**Comment by Baekalfen** [comment]
It seems that the generated `.c` files contain multiple declarations of `__pyx_ctuple_int__and_int`:

Here is a snippet from the generated `tile.c` file (from `tile.py` and `tile.pxd`:
```
/* "pyboy/core/lcd.pxd":30
 *     cdef void load_state(self, file)
 * 
 *     cdef (int, int) getwindowpos(self)             # <<<<<<<<<<<<<<
 *     cdef (int, int) getviewport(self)
 * 
 */
struct __pyx_ctuple_int__and_int {
  int f0;
  int f1;
};
struct __pyx_ctuple_int__and_int;
typedef struct __pyx_ctuple_int__and_int __pyx_ctuple_int__and_int;

/* "base_window.pxd":17
 * 
 * cdef class BaseWindow:
 *     cdef (int, int) _scaledresolution             # <<<<<<<<<<<<<<
 *     cdef unsigned int _scale
 *     cdef bint enable_title
 */
struct __pyx_ctuple_int__and_int {
  int f0;
  int f1;
};
```

This causes the compiler to fail:
```
pyboy/botsupport/tile.c:1070:8: error: redefinition of '__pyx_ctuple_int__and_int'
struct __pyx_ctuple_int__and_int {
       ^
pyboy/botsupport/tile.c:1056:8: note: previous definition is here
struct __pyx_ctuple_int__and_int {
       ^
pyboy/botsupport/tile.c:1097:8: error: redefinition of '__pyx_ctuple_int__and_int'
struct __pyx_ctuple_int__and_int {
       ^
pyboy/botsupport/tile.c:1056:8: note: previous definition is here
struct __pyx_ctuple_int__and_int {
       ^
2 errors generated.
```

If you want to experiment, you can find my code here and checkout the `no_dummies` branch : https://github.com/Baekalfen/PyBoy

**Comment by isotherm** [comment]
Thanks for the report! I pushed a new commit, which adds a test for that case, and it also appears to work on your code. Please confirm that it works for you.

**Comment by Baekalfen** [comment]
Thanks for the patch! I think that fixes the issue at hand, but there is another commit between yours and `bfcaf163e3dcf472ef2af5dec6ac3fffd0d34e66` which makes my code fail (calculating the checksum of a Game Boy cartridge) in runtime. I will hopefully have time to bisect that tomorrow.

I'm not sure if you want to make a PR and merge before I isolate that? It's likely unrelated to your code.

**Comment by isotherm** [comment]
Great, thanks! I made a small modification to the patch to be more internally consistent. I do have PR https://github.com/cython/cython/pull/3255 open, but I am awaiting feedback from @scoder or others if this is the correct approach.

**Comment by Baekalfen** [comment]
I've isolated the commit to `6d9daa08142e8a61d1f098fa0039b642537e614c`, so I would safely say that your code is not causing the issue. This is an isolated optimization of the `&` operator.

**Comment by isotherm** [comment]
PR now located at https://github.com/cython/cython/pull/3271.
