### ISSUE TITLE
Feature request: scoped typedefs in C++

### ISSUE THREAD

**Issue by molpopgen** [cython/cython#1446]
Cython does not currently support typedefs that are members of C++ classes.  This idiom is widely used, though, and would be nice to have.

**Comment by robertwb** [comment]
Implemented at https://github.com/cython/cython/commit/17e2f2c511575b8726519af726b5f7558dc5afc3 and https://github.com/cython/cython/commit/3f884a1cc9f9a706af5999327598e946ba7b081a
