### ISSUE TITLE
Fused types function arguments with default value results in error

### ISSUE THREAD

**Issue by yenchenlin** [cython/cython#1452]
I found that If I want to put fused type arguments in extension class methods, I cannot have default value arguments in the same function.

For example, following code snippet will result in error:
```python
from cython cimport floating
cdef class Printer:

    def print_num(self, x):
        a = 1
        b = 2
        self._print_num(x, a, b)

    def _print_num(self,floating x, a=1, b=2):
        print x
```

See this [example ipython script](https://github.com/yenchenlin/fused-types-extension-example/blob/master/fused_types_extension.ipynb).

**Comment by scoder** [comment]
Fixed in latest master.
