### ISSUE TITLE
Issue with pyximport

### ISSUE THREAD

**Issue by arita37** [cython/cython#1454]
I have created 2 files in my package directory module1.py module1.pyx

After running this code,

import pyximport; 
pyximport.install(build_dir= 'D:/Python01/cython/')

import module1 as cy
cy.fun_cython(5)
I could not find the pyd or the c file after compilation. On windows, where this files are located ? How can I check if compilation has errors ?

Thanks

**Comment by robertwb** [comment]
Questions such as this are better posted to the mailing list. An issue will be filed if there is actually a bug.
