### ISSUE TITLE
Cython coverage tool blames that function definition lines are not covered

### ISSUE THREAD

**Issue by asvetlov** [cython/cython#1461]
I'm trying to enable a coverage for cython modules for [multidict](https://github.com/aio-libs/multidict) library. `Cython.Coverage` plugin works but the [coverage output](https://codecov.io/gh/aio-libs/multidict/src/cf1458ba151cffd74972cf00471ed09b9d6ee0dc/multidict/_multidict.pyx) looks incorrect.

The tool blames that method definitions are not executed lines but it's definitely wrong because method bodies are executed and test covered.

What I do wrong?

**Comment by scoder** [comment]
Did you try latest master?

**Comment by asvetlov** [comment]
I've tried cython 0.24.1
On master I have another error:
```
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/home/andrew/.virtualenvs/multidict/lib/python3.5/site-packages/pytest_cov/plugin.py", line 212, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/home/andrew/.virtualenvs/multidict/lib/python3.5/site-packages/pytest_cov/engine.py", line 150, in finish
INTERNALERROR>     self.cov.combine()
INTERNALERROR>   File "/home/andrew/.virtualenvs/multidict/lib/python3.5/site-packages/coverage/control.py", line 784, in combine
INTERNALERROR>     self.get_data()
INTERNALERROR>   File "/home/andrew/.virtualenvs/multidict/lib/python3.5/site-packages/coverage/control.py", line 810, in get_data
INTERNALERROR>     self.collector.save_data(self.data)
INTERNALERROR>   File "/home/andrew/.virtualenvs/multidict/lib/python3.5/site-packages/coverage/collector.py", line 349, in save_data
INTERNALERROR>     covdata.add_arcs(abs_file_dict(self.data))
INTERNALERROR>   File "/home/andrew/.virtualenvs/multidict/lib/python3.5/site-packages/coverage/data.py", line 365, in add_arcs
INTERNALERROR>     raise CoverageException("Can't add arcs to existing line data")
INTERNALERROR> coverage.misc.CoverageException: Can't add arcs to existing line data
```

**Comment by asvetlov** [comment]
Aha, `coverage combine` doesn't work somehow.
Anyway, even without combining I have the same behavior (method definitions are not covered) on cython master too.

**Comment by asvetlov** [comment]
Steps to reproduce:
1. Clone https://github.com/aio-libs/multidict
2. Switch to `cython_coverage` branch
3. Run `pip install -r requirements-ci.txt`
4. Run `make cov-dev`, open prompted  html file.
Method definition lines from `multidict/_multidict.pyx` are not covered. 
5. For demonstrating issue with coverage files combining run `make cov-dev-full`.

**Comment by scoder** [comment]
Without having looked at the code, my guess is that we simply don't generate trace calls for function/method/class declarations. The whole tracing support works by explicitly calling the tracer before the C code that is generated for each line of user code that gets executed, and declarations aren't really considered user code. The trace call would need to get added to the instantiation of class objects and functions. AFAIR, we already trace the user code in the module init function, so this should generally be possible, although some C things might happen in an unexpected order in Cython.

**Comment by rmk135** [comment]
Facing the same issue... Method definitions (def/cpdef/cdef) in cdef classes are not covered, when they should be.

Also found person facing the same issue on SO - http://stackoverflow.com/questions/34935796/how-to-use-coverage-analysis-with-cython

**Comment by anthrotype** [comment]
Same issue here. The methods' body shows up as green, but the signature is always red.
Please let me know if I can help further debug this issue.
Thanks

**Comment by scoder** [comment]
As written above, we don't generate tracing calls for the function signature line. Or, rather, if we do, then they are only executed at import time, not at call time. Probably easy to implement, but needs a test that makes sure it really behaves exactly like CPython.

**Comment by kysely** [comment]
I also spent few hours on figuring this out. In the end, I found [a _cython-users_ Google Groups message](https://groups.google.com/d/msg/cython-users/e80vdI9G_3w/NTQTF009BAAJ) which recommends **enabling `binding` directive**.

This seems to completely remove the function signature statements from the coverage and I can reach 100% coverage again.

Could anyone comment on this workaround? Is it safe to use?
(I should also add I only compile with `binding` directive for test and coverage, not the production)

**Comment by scoder** [comment]
The `binding` directive is generally a good idea, mainly because it improves the Python compatibility of Cython compiled functions. However, I would not recommend using it only for testing, since disabling it for production changes the behaviour there.

**Comment by jbrockmendel** [comment]
@scoder I don't fully grok coverage.py or Cython.Coverage, am trying to get a handle on them to make a PR.

Would patching `Plugin._parse_lines` to consider these lines not-executable be a viable solution to this problem?  Or would it be liable to cause more problems?

**Comment by mdekstrand** [comment]
> Would patching Plugin._parse_lines to consider these lines not-executable be a viable solution to this problem? Or would it be liable to cause more problems?

I don't know anything about the coverage.py or Cython.Coverage code, but in principle this sounds like the correct solution if the details are worked out.

The following report is an example of how I am seeing this problem manifest: https://codecov.io/gh/lenskit/lkpy/src/7d705b4b9a051bca66f6cdc1873d3ab4cecdb52b/lenskit/algorithms/_funksvd.pyx

`cdef` local variables with initializers are marked as hit. A `cdef` field declaration of a memory view is also being marked as hit.

**Comment by scoder** [comment]
> consider these lines not-executable

No, that sound wrong. They are executable, CPython counts them, too. Could someone find out if CPython counts them only at import time or also at call time?

If the latter, then the fix is to also generate a line trace event for the function call.

**Comment by anthrotype** [comment]
setting binding=True as @kysely suggested above didn't change anything for me

> Could someone find out if CPython counts them only at import time or also at call time?

How do we find out?

**Comment by anthrotype** [comment]
btw, i'm also seeing switch statements being flagged in red as not covered, but the body of the switch branches is green
https://codecov.io/gh/fonttools/openstep-plist/src/master/src/openstep_plist/_parser.pyx#L119...177

**Comment by anthrotype** [comment]
I just did that. I created two python modules `a.py` and `b.py`. The former contains `import b`, and the latter defines a function `def f(): print('hello world')`.
When I run `coverage run a.py`, I can see that the signature of function `f` in the module `b.py` is green, whereas the body is read (as it was ony imported, not called).
If I add a `# pragma: no cover` next to `import b` inside `a.py` module, and then I add a new line where I call the function from b, `b.f()`, after I re-run `coverage run a.py` I can see the `import b` line is now grey (excluded), and in the module `b.py` I can see that both the function signature and its body are now green.

**Comment by anthrotype** [comment]
> I'd suggest looking at the CPython sources and finding out if a "call" trace event also triggers a "line" trace event. That would be the definite indicator.

right. That sounds more difficult, I'm not sure where to look..

**Comment by scoder** [comment]
Thanks for investigating @anthrotype. I've created a PR for adding the necessary line trace.

**Comment by anthrotype** [comment]
@scoder thank you for fixing this! 👍

**Comment by scoder** [comment]
Well, I _hope_ it's fixed. At least, it generates line trace events during the import now, and it doesn't look like Python generates line events for the definition line at call time, so I think it's as it should be now.

**Comment by scoder** [comment]
One problem I found: if the module includes other source files, then the tracing of the module init function reports (incorrect) lines for the main module file, not for the include file. That's because the trace frame and its 'code' object is created for the module init function only at the start, and thus refers to the module. When the execution switches to the include file, the code object is not updated (and I'm not sure that it would be a good idea to do that). That generally applies to all usages of ``include``. It's simply not anticipated in CPython to have a code mix from multiple files in one function.

Don't know what would be a good way to deal with this. Reporting wrong lines probably isn't ideal anyway.
