### ISSUE TITLE
Cython used with async - Decorators can only be followed by functions or classes

### ISSUE THREAD

**Issue by JendaPlhak** [cython/cython#1462]
I'm trying to compile Python 3 code using Cython (version 0.25a0). The code heavily depends on asyncio and works normally when run with latest Python. Compilation however gives me following error:

```
Error compiling Cython file:
------------------------------------------------------------
...

    @helpers.json_handler(logger = logger)
    async def get_index(req, req_body):
   ^
------------------------------------------------------------

skystore/mem_node.py:40:4: Decorators can only be followed by functions or classes
```

Does it mean, that async and await keywords are not supported? I thought otherwise because according to changelog it was implemented last year.

**Comment by robertwb** [comment]
I think this combination simply hasn't been implemented yet. It'd require a bit of plumbing, but hopefully it wouldn't be that hard.

**Comment by JendaPlhak** [comment]
I would be happy to help my self, but I never really touched Cython internals so I don't know whether I can be of any use :-/

**Comment by scoder** [comment]
Works for me. I guess `async def` wasn't actually implemented at the time.

**Comment by buckle2000** [comment]
This is not fully fixed! The following code won't compile.
```
def pass_through(func):
    return func


async def another():
    @pass_through
    async def test_pass_through():
        pass
```

**Comment by scoder** [comment]
Ah, yeah, thanks for noticing. Turns out, decorators work for the first `async def` spotted, and that enables `async` as keyword. Afterwards, `async` is a keyword and is then no longer recognised in the parser code paths that accept decorators. :)

**Comment by scoder** [comment]
Actually, I think Cython 3.0 is a good time to generally make `async` a keyword for good.
