### ISSUE TITLE
Book feature on cython.org

### ISSUE THREAD

**Issue by packtpartner** [cython/cython#1467]
Hi, 

As I was going through the website, I noticed a few books featured under External Resources on http://cython.org/#documentation

Packt is proud to publish a new book on Cython this year
[Learning Cython Programming - Second Edition](https://www.packtpub.com/application-development/learning-cython-programming-second-edition)

We would appreciate if you could help us feature this book as well as I think it will really help the Cython community.

Let me know what you think.

Many thanks.

**Comment by robertwb** [comment]
You should know what I think from private correspondence earlier this year. We're not going to be linking to this work from cython.org.
