### ISSUE TITLE
docs error: cythonize(include_path=x) does not set C include path

### ISSUE THREAD

**Issue by epruesse** [cython/cython#1480]
The documentation in [compilation.rst](../blob/master/docs/src/reference/compilation.rst#configuring-the-c-build) claims that

```
cythonize(extensions, include_path=[numpy.get_include()])
```

adds the numpy include path to the include file search path used by the compiler. This has been quoted many times and the documented feature is used by many packages, although with zero effect: `include_path` only adds to the search path used by Cython to find `pyx` and `pxd` files.

Some alternative ways to address this:
1. Change docs to match code by removing the misleading section.
2. Change code to match docs by adding the feature. 
3. Change docs and code to use `cython(include_dirs=[])` as a way for globally specifying C include paths. 
4. Change it all to have `cython_include_dirs` and `c_include_dirs` (or path).

3 has the benefit that code using `include_path` will continue to function as before (no effect on C include path), while making the feature people have obviously been expecting available. The term `include_dir` would then consistently (albeit not obviously) refer to the C includes and the term `include_path` to the Cython includes.

**Comment by jdemeyer** [comment]
Whatever you do, make sure not to break existing packages using `include_path` or `include_dirs`.

**Comment by native-api** [comment]
I'd say it's not a doc bug but a Cython bug. `cythonize` produces an `Extension` object which has `include_dirs` as one of attributes. It should set this attribute.

**Comment by epruesse** [comment]
Here's a patch as a suggestion. 
I could make it pick the possible `Extension` options from the `**options` of `cythonize()` easily enough using the `distutils_settings` list, but I'm not certain that the` cythonize()` parameter namespace would benefit. In particular, `include_path` (referring to Cython includes only) and `include_dir` (referring to C/C++ compiler include directives) are so similar that confusion would be guaranteed.

**Comment by native-api** [comment]
I was under impression that NumPy's C include path is being passed to `cythonize` because Cython actually needs the header files for code generation. Well, if you're sure it doesn't...

**Comment by jdemeyer** [comment]
> Cython actually needs the header files for code generation

Cython doesn't need any `.h` files. It just generates `#incude "foo.h"` statements and it's the C compiler who will actually read the header files.

Cython does look for headers in `include_dirs`, but only to add them as dependenies. It's not an error (not should it be) if the headers are not found.

**Comment by makmanalp** [comment]
Having just hit this and spent a while trying to figure out how to work around it, I'd like to voice my support for solution #2 (I can't see the harm, but I don't know much about this, so ...), but also just as an interim measure doing #1 or some variant to fix the docs, which is explicitly claiming something with numpy that doesn't work. I know I'm not the only one to be mislead by this, just by how very often this issue shows up:

https://www.google.com/search?q=numpy%2Farrayobject.h%27+file+not+found&oq=numpy%2Farrayobject.h%27+file+not+found&aqs=chrome..69i57j69i58.427j0j7&sourceid=chrome&ie=UTF-8

For posterity, my interim solution was to pass in my own Extension() to cythonize, which does kinda take away from the benefit of having cythonize in the first place IMHO.

```python
from setuptools import setup, Extension
from Cython.Build import cythonize
import numpy as np

setup(
    name='xyz',
    ext_modules=cythonize(
        Extension(
            "xyz",
            sources=[a/b.pyx"],
            include_dirs=[np.get_include()]
        )
    ),
    install_requires=["numpy"]
)
```

**Comment by carstenblt** [comment]
Sorry for the lack of productive criticism, but having a non-working documentation, apparently for several years, is not a great idea for a project.

**Comment by scoder** [comment]
My guess is that we named the parameter `include_path` rather than `include_dirs` at the time to distinguish it from the `include_dirs` parameter of `Extension` objects. Or, alternatively, without thinking much. Hard to say now... ;)

I'd be happy to merge #1480 if someone takes the time to fix the documented option names and rebase it.

**Comment by epruesse** [comment]
@scoder: I'll try to find the time this week to have another look at it. It's been a while...

**Comment by machinaut** [comment]
Is there a recommended workaround for this (given fix is still not merged)?

**Comment by scoder** [comment]
I would suggest to fix up the PR to make it mergeable.
