### ISSUE TITLE
exposing c++ typename to cython

### ISSUE THREAD

**Issue by jimsrc** [cython/cython#1481]
I have a cython module where I'm trying to expose a typename variable of a c++ templated class.

Here are related links [link1] and [link2] from before 2013, so I wonder if it is now implemented, and they say it's not implemented.
I have scanned the whole web, and I'm surprised to see almost no info about this. Try googling "cython expose c++ typename": there's nothing except stuff about templates.

### *just a thought:
In my .pyx file, after I define the cppclass, I use it in other functions with a specified template typename. So in principle, since cython translates .pyx to .cpp, I'm thinking that this templated-class-typename is well defined.
What I mean, is that this typename variable is defined at compile time, and not a runtime; therefore, this typename-exposing-feature is cython-feasible right?

[link1]:http://grokbase.com/t/gg/cython-users/136v44ees2/wrap-c-template-function-with-multiple-template-parameter-and-typdef-for-specific-instantiations-of-the-typdef
[link2]:https://groups.google.com/forum/#!topic/cython-users/qQpMo3hGQqI

**Comment by robertwb** [comment]
I'm not following what you're asking for. Could you expose a code snippet of what you're trying todo?

**Comment by molpopgen** [comment]
I believe this is the class member typedefs issue.

**Comment by robertwb** [comment]
That is fixed at head and should be in the next release.

**Comment by jimsrc** [comment]
Hello again,
I just read the [CHANGES.rst](https://github.com/cython/cython/blob/master/CHANGES.rst) file, and I think it's great that `cppclass` will be able to have `typedef` members now!

However, I was refering to defining types that were inside a template.
Snippets say more than 10000 words, sorry here it goes.
Now I have two questions (but very similar), one for typenames and another for typedefs.

---
# typenames

So I have these c++ definitions (*):
```c++
// defs_1.h
struct StepperBS{
   typedef double Dtype; // define a type
   int k;
   // more members...
}
```

and, for example, I could use `StepperBS` as template in another C++ `.h` file:
```c++
// defs_2.h
template<class Stp>
struct Odeint {
   	int nok;
   	typename Stp::Dtype my_Dtype; // catch a type from `Stp`
}
```

So far, all legal. But if I tried to write an analog of `defs_2.h` in Cython, I tried:

```cython
# defs_2.pxd
cdef extern from "defs_1.h":
    cdef cppclass Odeint[Stp]:
        int nok
        cdef typename Stp.Dtype my_Dtype # trying to catch `Dtype`
```
which did not compile. But then I thought that since Cython translates .pyx to .cpp, this templated-class-type `Dtype` is well defined, so in principle it could/should be implemented in the Cython compiler?

---

# typedefs

(*) a more general version of `defs_1.h` would be:
```c++
# defs_1.h
template <class D>
struct StepperBS{
   typedef D Dtype; // define a type, catching it from `D`
   int k;
```
which also tries to catch a type from `D`. As the `0.25` version will allow `cppclass` to have `typedef` members, the question would be if it will grab the types in this fashion:
```cython
cdef extern from "odeintt.h":
    cdef cppclass Odeint[Stepper]:
        Odeint()
        cdef typename Stepper.Dtype my_Dtype # trying to catch `Dtype`
```
or something like that?

I hope I was clear with these snippets. Thanks!

**Comment by robertwb** [comment]
These snippets make things much clearer, thanks. 

We don't really have the ability to defer attribute lookups until template instantiation time, which is what this would require. If you now the type is going to be some kind of int, you could write, e.g.
```
    cdef cppclass Odeint[Stepper]:
        typedef int my_Dtype
```
and Odeint::my_Dtype will be used in the generated code.
