### ISSUE TITLE
Presence of BUILD file prevents install on case-insensitive filesystem

### ISSUE THREAD

**Issue by minrk** [cython/cython#1482]
A BUILD file was added recently (a62e4935914d0b4e0d438ef7bce89db88ff40c9d) to the top-level package. The presence of this file prevents distutils from creating its `build` directory during installation on a case-insensitive filesystem (e.g. Windows, many HFS+ installs).

**Comment by robertwb** [comment]
https://github.com/bazelbuild/bazel/issues/552
