### ISSUE TITLE
using C types declared in .h

### ISSUE THREAD

**Issue by jimsrc** [cython/cython#1489]
I want to use in my `.pyx` C types that are `typedef` declarated in my .h file:
```c
//decls.h
typedef double Doub
typedef long int LInt
//etc...
```
My easy work around has been to redeclare them in my *.pxd (i.e. copy-paste that block of my `.h` into my `.pxd` replacing `typedef`-->`ctypedef`).
Now I'm using another `.h` with a lot of `typedef` statements, so I would like a more "cythonic" way of declaring.
I've been reading [this](http://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html), but did not help me.
Maybe something like:
```cython
cdef extern from "decls.h":
   Doub # no idea what to put before `Doub`
```

**Comment by robertwb** [comment]
This isn't a bug. User support is handled at cython-users@googlegroups.com.
