### ISSUE TITLE
array resize_smart speed regression (~40x) on Windows starting in cython 0.21.2

### ISSUE THREAD

**Issue by lesteve** [cython/cython#1492]
That was first discovered in https://github.com/scikit-learn/scikit-learn/issues/7645. 

I put together a stand-alone reproducing example:

```cython
from cpython cimport array

cdef int n_iter = int(1e6)

def transform():
    cdef array.array indices
    indices = array.array("i")

    for i in range(n_iter):
        array.resize_smart(indices, i + 1)
```

Timing it with 0.21.1 gives
* 45ms with cython 0.21.1
* 2.25s with cython 0.21.2

Notebooks with the code and timings can be found [here](https://gist.github.com/lesteve/6f6956a0f8587c550339a54a1f912d14).

Note that there is a speed regression on my Ubuntu machine as well which is a lot milder though (362 ms -> 456 ms for n_iter=1e7)

Suggestions on how to improve the scikit-learn [code](https://github.com/scikit-learn/scikit-learn/blob/c336a4390ef93e65f4e6641b954524d9e412947f/sklearn/feature_extraction/_hashing.pyx) are more than welcome!

**Comment by robertwb** [comment]
@larsmans looks like this was due to https://github.com/cython/cython/commit/65d3b977d785bca3219c3dbaf055c4aacadf0a7f

**Comment by lesteve** [comment]
Thanks for the quick fix! I quickly double-checked and it seems to fix the speed regression on Windows.

Any chance that this fix finds its way into a cython release?
