### ISSUE TITLE
PyException_Check and the Python Cassandra Driver

### ISSUE THREAD

**Issue by abrugh** [cython/cython#1496]
Hi,

I think there's something wrong with Cython 0.25.0

#### How things should and do work:
* Make a new virtualenv
* pip install cython=0.24.1
* pip install cassandra-driver==3.7.0 (i tried 3.2.0 and 3.0.0 too)
* start python
* import cassandra.cluster

#### Where things break
* Make a new virtualenv
* pip install cython==0.25.0
* pip install cassandra-driver==3.7.0
* There will be an error about PyException_Check being implicitly declared but the install completes
* start python
* import cassandra.cluster
* You will set another error about PyException_Check

I honestly know nothing about Cython other than its a black box for making Python faster. But the fact that the only variable between the two scenarios above is the Cython version leads me to believe it's an issue with Cython and not the Cassandra driver.

Sorry of this doesn't meet criteria for a bug report. I'm happy to supply more info.

**Comment by jhgg** [comment]
Am having this exact same issue as of recent.

**Comment by jhgg** [comment]
It looks like this symbol has somehow appeared:

```
$ nm -g /home/deploy/virtualenvs/discord/local/lib/python2.7/site-packages/cassandra/cluster.so | grep PyException
                 U PyException_Check
```

This doesn't exist in the .so generated by cython 0.24.1

**Comment by ngoldbaum** [comment]
I've uploaded cluster.c here: https://gist.github.com/ngoldbaum/ff58cd6d51002ca6dc574e34ff5016cd

The problematic call to the nonexistent PyException_Check is being generated by code in the cython file that looks like this:

```
for exc in [f for f in results if isinstance(f, Exception)]:
    ...
```

**Comment by ngoldbaum** [comment]
In fact the following test code after being cythonized produces a call to PyException_Check:

```
results = ['foo', 'bar']

for exc in [f for f in results if isinstance(f, Exception)]:
    pass
```

```
$ cython test.pyx
$ ag PyException_Check test.c
998:    __pyx_t_6 = PyException_Check(__pyx_t_2);
```

**Comment by ngoldbaum** [comment]
Under cython 0.24.1 the same line looks like:

```
__pyx_t_6 = PyObject_IsInstance(__pyx_t_2, __pyx_builtin_Exception); if (unlikely(__pyx_t_6 == -1)) __PYX_ERR(0, 3, __pyx_L1_error)
```

**Comment by jhgg** [comment]
Fairly certain the bug is here: https://github.com/cython/cython/blob/d8c5467133aa16c3eccb19427c41a62a51115837/Cython/Compiler/PyrexTypes.py#L1218

It is generating the incorrect exception check.

**Comment by ngoldbaum** [comment]
I think this was caused by https://github.com/cython/cython/commit/b1d7b0de9e4cdc1eb866661e34f3da8892993fba, ping @robertwb

**Comment by 1st1** [comment]
Exactly the same problem in http://github.com/magicpython/uvloop: https://travis-ci.org/MagicStack/uvloop/builds/170654704
