### ISSUE TITLE
Missing directive_defaults from Cython.Compiler.Options?

### ISSUE THREAD

**Issue by tamasgal** [cython/cython#1497]
I am using directive_defaults in my packages and I suddenly get an import error. I could not find anything in the changelogs, in fact, Cython uses this import line too in its setup.py. Does anyone have a clue what's going on here? I tried the latest release (0.25) in a fresh virtualenv with Python 2.7.12 and 3.5.2.

```
In [2]: from Cython.Compiler.Options import directive_defaults
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-43ee860b87f9> in <module>()
----> 1 from Cython.Compiler.Options import directive_defaults

ImportError: cannot import name directive_defaults
```

**Comment by cython-notifications** [comment]
Sorry, this should have been in the release notes. Now you must call
Cython.Compiler.Options.get_directive_defaults()

**Comment by tamasgal** [comment]
Many thanks!

**Comment by FNAFDecompiler** [comment]
Hey, how do I get the directive_defaults attribute into Cython.Compiler.Options using Command Prompt for Windows?
