### ISSUE TITLE
cythonize python3 bug with extension list

### ISSUE THREAD

**Issue by thomas-bottesch** [cython/cython#1505]
Hi,

I am currently experiencing a python3 cythonize bug. The same code works under python 2.7.
I think I was able to pinpoint the cause which I explain below.

```
>>> print(cython.__version__)
0.25.1
```

Here is what I am trying to compile with python3.4:

```
extensions = [
    Extension("first_ext", ["first_ext.pyx", "somefile.c"],
        include_dirs = [...],
        libraries = [...],
        library_dirs = [...]),
    Extension("second_ext", ["second_ext.pyx", "somefile2.c"],
        include_dirs = [...],
        libraries = [...],
        library_dirs = [...]),
]
setup(
    name = "My hello app",
    ext_modules = cythonize(extensions),
)
```

Here is the error I am getting:

```
Traceback (most recent call last):
  File "setup.py", line 137, in <module>
    , extra_link_args=['-fopenmp'])
  File "./.virtualenvs/envpy34/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 886, in cythonize
    to_compile.sort()
TypeError: unorderable types: dict() < dict()
```

The `to_compile` list contains tuples with some data like this:

[(0, 'path/first_ext.pyx', 'path/first_ext.c', None, False, <Cython.Compiler.Main.CompilationOptions object at 0x7fd18d3eae10>, True, **{'meta_data_dict_first_ext'}**),
(0, 'path/second_ext.pyx', 'path/second_ext.c', None, False, <Cython.Compiler.Main.CompilationOptions object at 0x7fd18d3eae10>, True, **{'meta_data_dict_second_ext}**)]

Notice the bold metadata dicts (the last entry of each tuple in `to_compile`).

The reason why it fails is that python2.7 is able to sort tuples which have dicts, python3 is not able to do it out of the box.

Here a relevant link to a [stackoverflow discussion](http://stackoverflow.com/questions/22333388/dicts-are-not-orderable-in-python-3)

As a workaround instead of cythonizing a list of Extensions it is possible to cythonize one Extension at a time. This has some disadvantages though like multiple times compiling the same files.

**Comment by robertwb** [comment]
It should never get to the dicts unless everything preceding it in the tuple is the same. Do you perhaps have duplicate entries in your Extension list? (If this is indeed it, we should provide a better error.)

**Comment by the-neworder** [comment]
I can confirm that it has something to do with having multiple times the same extension I saw this error when I had this case:

```
extensions = [
    Extension("first_ext", ["first_ext.pyx", "signals.pyx", "somecfile1.c"],
        include_dirs = [...],
        libraries = [...],
        library_dirs = [...]),
    Extension("second_ext", ["second_ext.pyx", "signals.pyx", "somecfile2.c"],
        include_dirs = [...],
        libraries = [...],
        library_dirs = [...]),
]
setup(
    name = "My hello app",
    ext_modules = cythonize(extensions),
)
```

Signals.pyx looks like this:

```
from libc.stdint cimport uint32_t
from cpython.exc cimport PyErr_CheckSignals

cdef public void check_signals(uint32_t* stop) with gil:
  PyErr_CheckSignals()
```

**somefile1.c** and **somefile2.c** expect that the function **check_signals** is defined somewhere and since it uses the python context it needs to be defined in a pyx file. How can check_signals be used by both .c files if it is not defined in a pyx file? Is this not the way it should be done?

**Comment by robertwb** [comment]
See http://cython.readthedocs.io/en/latest/src/userguide/sharing_declarations.html

**Comment by lobachevzky** [comment]
@robertwb , I have read that page several times and I am still confused I have some source code that needs to be shared between two separate extensions but which needs to be built with different libraries in each extension. Specifically, `sim.pyx` gets used by two separate extensions `sim.egl` and `sim.glfw` but it needs to be build using EGL in the former and using GLFW in the latter. Thanks for your help.

**Comment by phdye** [comment]
Perhaps share, or rather include, the code as pxi files rather than pyx
