### ISSUE TITLE
distutils deprecated

### ISSUE THREAD

**Issue by tygerlord** [cython/cython#1509]
v 0.25.1 
/usr/local/opt/python-3.5.2/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.

Well ok, but what the way we do now? Documentation still refer to use build_ext.

**Comment by robertwb** [comment]
Hmm... I wonder why this warning only prints on Python 3... This is only supposed to trigger for direct imports of old_build_ext.

**Comment by Trevor-P** [comment]
I'm having this issue as well, starting from the Cython helloworld example.  

http://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html

I'm using mingw on windows 10 64 bit as my C compiler, and the error seems to occur when compiling with both Python 2.7 and Python 3.5   

the script does create a ".c" file in the local directory, so at least part of the code is working

**Comment by filmor** [comment]
The respective code (`old_build_ext.py` from line 20 onwards) is wrong in multiple ways:

1. In Python 3 a lot of the `import` mechanics is implemented in `importlib`, so for each import there are 4 additional frames introduced
2. On Windows, the paths will use the native path separator, so checks for `"Cython/Distutils/build_ext.py"` etc. will fail

**Comment by robertwb** [comment]
Thanks. I've relaxed this a bit: https://github.com/cython/cython/commit/f5b89afa9d8ad1217640a40445fb88082cb40e3d

I'll be pushing out a new release.
