### ISSUE TITLE
OSX 10.11.6 "Command Not Found" Error after Install

### ISSUE THREAD

**Issue by weems** [cython/cython#1511]
# Installed and Attempted to Run
> $ pip install rainbowstream
Collecting `rainbowstream
Requirement already satisfied: python-dateutil in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from rainbowstream)
Requirement already satisfied: twitter in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from rainbowstream)
Requirement already satisfied: requests==2.5.3 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from rainbowstream)
Requirement already satisfied: pyfiglet in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from rainbowstream)
Requirement already satisfied: arrow in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from rainbowstream)
Requirement already satisfied: Pillow in /Library/Python/2.7/site-packages (from rainbowstream)
Requirement already satisfied: PySocks in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from rainbowstream)
Requirement already satisfied: pocket in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from rainbowstream)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from python-dateutil->rainbowstream)
Installing collected packages: rainbowstream
Successfully installed rainbowstream-1.3.6
$ rainbowstream
zsh: command not found: rainbowstream

**Comment by robertwb** [comment]
Looks like this was filed against the wrong project.
