### ISSUE TITLE
cythonized modules in zipapp (.pyz) cant be imported

### ISSUE THREAD

**Issue by tygerlord** [cython/cython#1515]
I've a module cythonized in mydir.
Running **`python3 mydir/__main__.py`** works fine, but if I create a .pyz
with zipapp but after that **python3 mydir.pyz** fail with message
ImportError.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "machine.pyz/__main__.py", line 5, in <module>
ImportError: No module named 'ads.main'

```

**Comment by robertwb** [comment]
Can you use any [extension modules](https://docs.python.org/3.6/extending/extending.html) with zipapp?

**Comment by tygerlord** [comment]
Well I'm not an expert with zipapp, but for me it's just an archive executable, so i really don't expect to get in trouble with that. I'll try to investigate more if I have some time.

**Comment by codewarrior0** [comment]
zipapp merely leverages Python's built-in `zipimport` facility; from the [zipimport docs](https://docs.python.org/3.6/library/zipimport.html) we find:

> ZIP import of dynamic modules (.pyd, .so) is disallowed.

**Comment by tygerlord** [comment]
OK, Its my eyes!
Thanks.

**Comment by alexfromapex** [comment]
Any flag to turn off the restriction? This is a big snag for running Python code in Spark

**Comment by robertwb** [comment]
This is not a restriction with Cython, but with zipimport, and any fix would have to be on that side.

**Comment by alexfromapex** [comment]
Sorry should've checked what repo I was commenting on, it sounds like this is part of PEP 273 so would probably need to submit a new PEP anyways
