### ISSUE TITLE
Complex Arithmetic Bug: Exponentiation

### ISSUE THREAD

**Issue by aerusso** [cython/cython#1538]
The following cython file should emit -1/32 twice (up to a zero imaginary component). My machine produces a nan+nanj for the second.

`print((-0.5)**5,(-0.5+0j)**5)`

This is present in the [Debian packaging of Cython3 0.25.2](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846268). I have not tested mainline cython3.

**Comment by robertwb** [comment]
Thanks for finding this.
