### ISSUE TITLE
 warning C4293: '<<' : shift count negative or too big, undefined behavior

### ISSUE THREAD

**Issue by Lexcon** [cython/cython#1562]
I get the warning mentioned in the title of this issue.

I have the latest version of Cython 0.52.2 and Python   (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]

Not sure how to add debugging or reproducing information, I'm trying to compile a more complex file.

The offending line in my generated .c file is:

if ((8 * sizeof(unsigned long) < 53) || (2 * PyLong_SHIFT < 53) || (a < (double) (1L<<53))) {

so it seems to try to shift 53 positions in a Long value

**Comment by Rezangyal** [comment]
Same problem, win8.1, python 2.7, 32 bit, c++ output.

I think the source of the problem is the "utility/optimize.c", line 815, line 580 and line 670

Solution: replace 1L with 1LL
