### ISSUE TITLE
libcpp map vs vector why map requires indexing first zero

### ISSUE THREAD

**Issue by hartsantler** [cython/cython#1563]
if i have a pointer to `map`, how come i have to index it with zero, while with `vector` cython is smart enough to automatically hide that from the user?

```python
cdef public shared_ptr[map[int, string]] make_map(int n):
	cdef map[int, string]* m
	cdef int nx = 2
	m = new map[int,string]()
	for i in range(n+nx):
		m[0][i] = string('map ok')
		print m[i]
	return shared_ptr[map[int, string]](m)

cdef public shared_ptr[vector[int]] make_shared_vec(int n):
	cdef vector[int]* vec
	vec = new vector[int]()
	for i in range(n):
		vec.push_back(i)
	return shared_ptr[vector[int]](vec)

```

**Comment by robertwb** [comment]
Cython aliases . as -> for pointers, but getindex already has meaning for
pointers.

**Comment by hartsantler** [comment]
what i found really confusing with cython syntax rules is that if you have a pointer to an std::vector, you can print the first item in it using `myvec[0]`.  But that only works for the first item, trying to access the second item that way will compile but crash at runtime.
It also a bit of a surprise that `myvec[0] = "foobar"` compiles and splits apart `foobar` by characters.
I think its rare the cases where a user is going to want to manually do pointer math and indexing, its too bad cython is stuck with this syntax.

**Comment by robertwb** [comment]
On Fri, Dec 23, 2016 at 10:25 AM, Brett S. Hartshorn <
notifications@github.com> wrote:

> what i found really confusing with cython syntax rules is that if you have
> a pointer to an std::vector, you can print the first item in it using
> myvec[0].
>
No, this prints the entire vector. vecptr[0] gives the dereferenced vector
if vecptr is a pinter to a vector, intptr[0] gives the dreferenced integer
if intptr is a pointer to an int, etc.

> But that only works for the first item, trying to access the second item
> that way will compile but crash at runtime.
>
Similarly for intptr[1]. (Well, it can succeed, and be garbage, or might be
a segfault...the behavior of dangling pointers depends on the precise
memory layout.)

> It also a bit of a surprise that myvec[0] = "foobar" compiles and splits
> apart foobar by characters.
>
There are pros and cons of strings being iterables (especially as the
element type is the same as the container type), with the debate going way
back e.g.
https://mail.python.org/pipermail/python-3000/2006-April/thread.html#759
This is not new to Cython.

> I think its rare the cases where a user is going to want to manually do
> pointer math and indexing, its too bad cython is stuck with this syntax.
>
Yeah, pointers to indexable things are a pain, even in C/C++.

The unary * operator from C doesn't work well, as it already has other
meanings in Python (though you can use cython.operator.dereference).
