### ISSUE TITLE
encodes absolute source path in output

### ISSUE THREAD

**Issue by jelmer** [cython/cython#1565]
cython encodes the path of the source cython path of the module it compiles in
its output.

It would be useful if it was possible to generate output that can be compiled 
into bit-for-bit reproducible binaries.

E.g.
static const char __pyx_k_home_jelmer_src_bzr_unstable_bz[] = "/home/jelmer/src/bzr/unstable/bzrlib/_annotator_pyx.pyx";

This seems to be used as argument for PyCode_New() calls. Would it be reasonable to use relative paths  or possibly have a flag to use relative paths?

**Comment by robertwb** [comment]
I agree that relative paths would be good, perhaps relative to the package root? I'd like systems like ipython to still be able to locate the original code though.

**Comment by jelmer** [comment]
I can't think of a good way to include a relative path that will be valid across e.g. package installation, so this might indeed require a flag.
