### ISSUE TITLE
feature request: --verbose option to %%cython magic

### ISSUE THREAD

**Issue by kurtbrose** [cython/cython#1569]
When using %%cython or %%cython_pyximport from ipython, if the compilation fails you just get this:

`CompileError: command 'gcc' failed with exit status 1`

Would be nice to have `--verbose` option to the magic function which would simply pipe through gcc stdout / stderr, possibly also set distutils log level to DEBUG (`distutils.log.set_verbosity(distutils.log.DEBUG)`) to give at least a fighting chance to debug the errors.

**Comment by scoder** [comment]
Yes, would be nice to have. Pull request welcome.

**Comment by scoder** [comment]
Included in [0.27.1b1](https://github.com/cython/cython/archive/0.27.1b1.tar.gz). Please give it a try.
