### ISSUE TITLE
is it necessary to link the libc math library? (-lm)

### ISSUE THREAD

**Issue by anthrotype** [cython/cython#1585]
In the latest Cython documentation, it says:

> The libc math library is special in that it is not linked by default on some Unix-like systems, such as Linux. In addition to cimporting the declarations, you must configure your build system to link against the shared library m.

http://cython.readthedocs.io/en/latest/src/tutorial/external.html#dynamic-linking

Now, I tried to compile this sample snippet which cimports from libc.math, on a Ubuntu 16.04 machine:

```cython
from libc.math cimport sin

cpdef double sin2(double x):
    return sin(x*x)
```

I did not link the `m` library in the distutils/setuptools `Extension.libraries`, so the resulting .so file looks like this:

```sh
$ ldd demo.so 
	linux-vdso.so.1 =>  (0x00007fff299a8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f38f9e59000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f38f9a90000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559ffa7c0000)
```

Despite what the cython docs say, even without explicitly linking the math library, this seems to be working fine when I run it from Python:

```python
In [1]: from demo import sin2

In [2]: sin2(0.2)
Out[2]: 0.03998933418663417
```

I'm thinking this works because python itself is linked with libm:

```sh
$ ldd /home/cosimolupo/.pyenv/versions/cython-test/bin/python
	linux-vdso.so.1 =>  (0x00007ffe683dc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f22c487a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f22c4676000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f22c4472000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f22c4169000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f22c3da0000)
	/lib64/ld-linux-x86-64.so.2 (0x00005614020d7000)
```

The question is then, does the recommendation to link 'm' library when compiling extension modules on Unix still hold?

The reason I ask is because I'm wrapping a C library which does require linking with the C math library, but my extension module does not use math directly.

Should I add 'm' to the Extension libraries? Should I only do it if self.compiler.compiler_type == "unix"?

Thanks

**Comment by anthrotype** [comment]
I forgot to mention, I'm building the wrapped C library from source and statically linking it with my python extension module wrapper, so I am trying to replicate the compiler/linker flags in the original library's Makefile via distutils/setuptools.

**Comment by robertwb** [comment]
It's not linked by default on "some Unix-like systems." You can omit it and be fine most of the time, but it won't be as portable.

**Comment by anthrotype** [comment]
I understand that, and in fact it is not linked by default even here on this particular "Unix-like system" whch I'm using, i.e. Ubuntu 16.06.
At least the ldd tool on the complied *.so says it's not linked with libm, unless I tell distutils to tell gcc to do so.

Still, I don't understand how come, being _not_ linked, it still works when I import the compiled extension module from Python.

Sorry if I'm dumb, I'm no expert C programmer.

**Comment by robertwb** [comment]
Exactly what gets found when not explicitly linked depends on the platform and the toolchain and the environment (often in surprising ways). I think this note was added due to issues on some platforms that explicitly linking against the math library resolved, but I don't have any examples off-hand. It may be overly cautious, but is always safe, to declare explicit dependencies on those things that you actually depend on.

**Comment by anthrotype** [comment]
Thanks for the clarification.
