### ISSUE TITLE
numpy_test failures with 1.8.2

### ISSUE THREAD

**Issue by yarikoptic** [cython/cython#1589]
Originally reported in Debian:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848753  and I have just reconfirmed it with 0.25.2 release with numpy 1.8.2-2  on Debian sid, failures of such a weird kind (not sure if precision issue or what)

```
AssertionError: Failed doctest test for numpy_test.__test__.numpy_test
  File "/build/cython-0.25.2/build/work-dir/5/run/cpp/numpy_test/numpy_test.so", line unknown line number, in numpy_test

----------------------------------------------------------------------
File "/build/cython-0.25.2/build/work-dir/5/run/cpp/numpy_test/numpy_test.so", line ?, in numpy_test.__test__.numpy_test
Failed example:
    test_point_record()
Expected:
    array([(0.0, 0.0), (1.0, -1.0), (2.0, -2.0)],
          dtype=[('x', '!f8'), ('y', '!f8')])
Got:
    array([( 0.,  0.), ( 1., -1.), ( 2., -2.)],
          dtype=[('x', '!f8'), ('y', '!f8')])


----------------------------------------------------------------------
Ran 547 tests in 196.859s

FAILED (failures=4)
```
Full buildlog is at  http://neuro.debian.net/_files/_buildlogs/cython/0.25.2/cython_0.25.2-1_amd64.build

any clues?

**Comment by robertwb** [comment]
I think this is sensitive to some internal formatting library. Our test should not be sensitive to this: 

https://github.com/cython/cython/commit/dd0b10c7e31ea136632bfcfd46c925adcf4c4af6
https://github.com/cython/cython/commit/dd9eb10bc5657beed1f66221511c16ec6f4e517d

**Comment by oleksandr-pavlyk** [comment]
Note that commits reference above apply to Cython versions 0.26.alpha and newer. If you are using 0.25.2, these commits are not there yet.
