### ISSUE TITLE
Problems building Cython with icc

### ISSUE THREAD

**Issue by dbalague** [cython/cython#1591]
I am having trouble compiling Cython 0.25.2 using icc. (version 17.0.1)

The problems occur when trying to compile the following files with the corresponding compiler options:

`icc -shared -ipo build/temp.linux-x86_64-3.5/usr/local/python/modules/Cython-0.25.2/Cython/Compiler/Parsing.o -o build/lib.linux-x86_64-3.5/Cython/Compiler/Parsing.cpython-35m-x86_64-linux-gnu.so`

`icc -shared -ipo build/temp.linux-x86_64-3.5/usr/local/python/modules/Cython-0.25.2/Cython/Compiler/Code.o -o build/lib.linux-x86_64-3.5/Cython/Compiler/Code.cpython-35m-x86_64-linux-gnu.so`

`icc -shared -ipo build/temp.linux-x86_64-3.5/usr/local/python/modules/Cython-0.25.2/Cython/Tempita/_tempita.o -o build/lib.linux-x86_64-3.5/Cython/Tempita/_tempita.cpython-35m-x86_64-linux-gnu.so`

All three led to this error:
```
": internal error: 010101_(5000 + 54)

icc: error #10014: problem during multi-file optimization compilation (code 4)
error: command 'icc' failed with exit status 4
```
I worked around it by compiling the three files manually with `icc -shared -O0` instead, and I could finish building and installing Cython with no further problems.

Also, I could run
```
cd Demos
python setup.py build_ext --inplace
```

And the examples:

```
python run_primes.py
python run_spam.py
python run_numeric_demo.py
```
worked with no problems.

**Comment by robertwb** [comment]
Have you verified that this is not an ICC bug?

**Comment by smcantab** [comment]
I ran into the same problem with cython 0.27.2 and icc version 17.0.1 (gcc version 4.8.5 compatibility). I do not have this problem if I use cython 0.26.1

**Comment by dbalague** [comment]
I guess I did not specify the GCC compatibility version. It was exactly the same as yours:
icc version 17.0.1 (gcc version 4.8.5 compatibility)

**Comment by schnaitterm** [comment]
I think this issue is related to the -ipo flag.  I just tried to build 27.3 with the -ip flag and got the same error, but after removing that flag it looks like it's working

**Comment by scoder** [comment]
Sounds like an out-of-memory issue to me, or an iCC bug, as Robert suggested. In any case, Cython does not configure any C compiler flags itself. They come from user settings and/or the original CPython build setup. If changing the compiler flags makes the crash go away, then that's what users have to do on their side.
