### ISSUE TITLE
unique_ptr and allocator combination cause "Unhandled exception at (ntdll.dll) Python.exe: A heap has been corrupted

### ISSUE THREAD

**Issue by paxRomana99** [cython/cython#1592]
The following code causes a heap corrupted error once the array size grows to a certain point.
```python
import numpy as np
cimport numpy as np
from libcpp.memory cimport unique_ptr, allocator

def testArray1(int dim1):
    cdef allocator[double] dbl_al
    cdef unique_ptr[double] myptr

    myptr.reset(dbl_al.allocate(dim1))

def testArray2(int dim1, int dim2):
    cdef allocator[double *] ptr_al
    cdef np.ndarray arr
    cdef double[:,:] carr
    cdef unique_ptr[double *] myptr

    myptr.reset(ptr_al.allocate(dim1))
    arr = np.ndarray((dim1,dim2),dtype=np.float64,order='C')
    carr = arr

    myptr.get()[0] = &carr[0,0]
    myptr.get()[1] = &carr[1,0]
    myptr.get()[2] = &carr[2,0]
```
Calling `testArray1(511)` or `testArray2(511,1000)` works fine. Calling `testArray1(512)` or `testArray2(512,1000)` causes a crash with the heap corrupted notification. This was observed for Cython 24.1, Python 3.5.1, VS2015, Windows 7 SP1.

**Comment by paxRomana99** [comment]
Looks like it might be a window issue. It has been tested on Linux for Python 2.7 with Cython 25.2 and Python 3.5 with Cython 24.1 and neither encountered the issue.

**Comment by samuelbarrett1234** [comment]
FWIW this issue still exists - I have reproduced this on Windows 10 with Python version 3.10.9, Cython version 3.0.11, NumPy version 2.1.2.

**Comment by da-woods** [comment]
This doesn't look valid to me.

You're allocating using using `std::allocator::allocate` and deallocating using `std::default_delete` (in the `unique_ptr` destructor). Generally you should be matching the allocation and deallocation. Therefore, if you're allocating with `std::allocator::allocate` you should be deallocating with `std::allocator::deallocate`.

Now it's possible that really careful reading of the C++ standard confirms that it's actually fine (providing that microsoft has stuck to the standard of course).

Practically I'm fairly sure you're allocating with the array new, and deleting with the non-array delete.
