### ISSUE TITLE
could cython wrap c++ template class? (not template type)

### ISSUE THREAD

**Issue by hqsh** [cython/cython#1595]
i know cython can use "fused" to wrap c++ template types.
but how to wrap template class?
for example, the ".h" file is as below. C1 and C2 are classes, not types.

    template<class C1, class C2>
    void queryInterface(C1& c, C2 iid) {
		pointer_type p;
        if (!c.queryInterface(iid, (void**)&p))
			reset(p);
	}

how to wrap it in ".pxd" file?
if i just use "fused", the error "C1 is not a type identifier" occurred.
thx!

**Comment by hqsh** [comment]
how to wrap it in ".pxd" file?
thx!

**Comment by robertwb** [comment]
See http://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html#templates . If you have further questions, user support is provided at cython-users@googlegroups.com; the issue tracker is used for tracking issues (bugs and feature requests).
