### ISSUE TITLE
Declaration of C function with **in leads to error

### ISSUE THREAD

**Issue by esahione** [cython/cython#1600]
I'm creating APR Cython bindings and I just came across this parsing error. The original function is this:
```
APR_DECLARE(apr_status_t) apr_file_pipe_create(apr_file_t **in, 
                                               apr_file_t **out,
                                               apr_pool_t *pool);
```
And if I declare it as:
`
    apr_status_t apr_file_pipe_create(apr_file_t **in, apr_file_t **out, apr_pool_t *pool)
`

I get a compilation error on the PXD file that says: "Expected ')', found 'in'". If I rename the function argument 'in' to 'file_in' everything works. I'm not familiar enough with Cython's code base to fix it.

**Comment by robertwb** [comment]
in is a reserved keyword in Python (hence Cython).

**Comment by esahione** [comment]
Thanks! I didn't know 'in' was a reserved keyword on declarations as well.

**Comment by robertwb** [comment]
Yes, just like you couldn't name a variable "for" or "const" in C.
