### ISSUE TITLE
Inconsistent behavior between dictionary methods of access (d[k] vs d.__getitem__(k))

### ISSUE THREAD

**Issue by goodmami** [cython/cython#1602]
A dictionary with single-character `unicode` keys queried with a `Py_UNICODE` key will raise a KeyError with bracket access (e.g. `d[k]`), but succeeds with `d.get(k)`, `d.__getitem__(k)`, `k in d`, `d.__contains__(k)`, etc). Here is an example:

```cython
d = {u'a': 1, u'b': 2}
cdef Py_UNICODE c = u'a'
print(c, c in d, d.get(c), d.__getitem__(c))  # succeeds
print(d[c])  # KeyError
```

I get that maybe `Py_UNICODE` isn't compatible with `unicode`, so the hashes would be different, thus leading to the KeyError, but I wouldn't expect it to work with some methods of dictionary access and not others. This can lead to some hard-to-find bugs.

**Comment by scoder** [comment]
Both `Py_UNICODE` and the more portable `Py_UCS4` are treated as C integers here. I agree that they should not be.

**Comment by scoder** [comment]
The old behaviour can be restored in a backwards-compatible way by explicitly casting to a C integer.
