### ISSUE TITLE
Exception being ignored in __dealloc__ (and in C++ class destructor)

### ISSUE THREAD

**Issue by tadeu** [cython/cython#1613]
Hi, I have a code that is like the following simplified test case:

```cython
cdef class RaiseOnDealloc:
    def __cinit__(self):
        print('Entered RaiseOnDealloc.__cinit__')

    def __dealloc__(self):
        print('Entered RaiseOnDealloc.__dealloc__')
        raise RuntimeError('Something bad')
        print('After raising')

def test_raise_on_dealloc():
    print('Entered test_raise_on_dealloc')
    cdef RaiseOnDealloc r = RaiseOnDealloc()
    print('Body of test_raise_on_dealloc')
```

the output of calling `test_raise_on_dealloc()` is this:

```
Entered test_raise_on_dealloc
Entered RaiseOnDealloc.__cinit__
Body of test_raise_on_dealloc
Entered RaiseOnDealloc.__dealloc__
Exception ignored in: 'RaiseOnDealloc.__dealloc__'
RuntimeError: Something bad
```

The `RuntimeError` is not being propagated by `test_raise_on_dealloc`. Is there a way for it to not be ignored? Unfortunately `__dealloc__` is only valid as a` def` function, and it doesn’t accept `except +`.

Even if I move the class to C++ and declare it with `cdef cppclass`, it’s still not possible to propagate exceptions from its destructor, since there seems to be no way to declare destructors on `cdef cppclass` declarations.

**Comment by leofang** [comment]
I just hit this bug too and was surprised this is still not fixed after 3+ years...🤦🏻‍♂️

**Comment by da-woods** [comment]
As a general rule you shouldn't be raising exceptions from destructors (either from C++ or Python). The basic problem is that destructors are often called while handling other exceptions and you can't have two exceptions at once.

It isn't completely clear [from the documentation](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_dealloc) what the rules are for exceptions in `tp_dealloc`. `tp_finalize` (which we don't yet support) definitely requires the exception state to be restored on exit.

So I'm not really convinced this is a bug. Swallowing the exception is definitely a sensible implementation choice (and probably the most sensible one)

**Comment by leofang** [comment]
Thanks, @da-woods, you're absolutely right. Destructors shouldn't raise. I had a long day when I searched and googled for this issue. 

In addition to improving the doc, do you think there's anything smart that Cython can do? For example, can it tell if a function called in `__dealloc__` could raise, and warn/error out at compile time?

**Comment by robertwb** [comment]
Pretty much ever Python function call in _could_ raise an exception, so I'm not sure how useful such a warning would be.

**Comment by leofang** [comment]
Yes, that's a fair point. We wouldn't know such information beforehand. But how about C/C++ functions wrapped by Cython? We will know, wouldn't we?

**Comment by da-woods** [comment]
@leofang It's probably possible for the simplest case, but once you add a `try except` block it suddenly becomes harder to tell if they're handled or not (remember the tuple of types that `except` catches need not be a constant).

I think a runtime message (like we have now) is probably the most sensible option.

**Comment by leofang** [comment]
Sounds like there's some Cython internal that I should learn more to understand 😅 But thanks for the insight @da-woods!

**Comment by leofang** [comment]
@da-woods I just hit exactly the same problem again, but this time the exception happens at interpreter shutdown -- the clean-up function (from another module) becomes unavailable, so it raises in `__dealloc__`. Any advice for working around it?

If not a cdef class but just a plain Python class, there is a known workaround that we learned from other projects:
```python
def __del__(self, is_shutting_down=a_shutting_down_callable_from_elsewhere):
    if is_shutting_down():
        return
    # do cleanup
```
But this trick does not work for `__dealloc__`...

**Comment by da-woods** [comment]
Is there really anything to work around? Ultimately your options are:

* Do nothing - it only prints an error message
* Swallow the exception (e.g. put contents of `__dealloc__` in a try-catch block)
* Skip the destruction on shutting down (what your proposal does)
* Actually fix the error that's causing the exception to be raised

All of the first three options seem equally unsatisfactory to me. But ultimately it is only an warning message - it doesn't break your program.

**Comment by leofang** [comment]
Thanks for quick reply!

> But ultimately it is only an warning message - it doesn't break your program.

Yeah, while it is true (and one that I can't agree with more), we do receive several bug reports due to such innocent bugs...
