### ISSUE TITLE
PyPy3: CYTHON_USE_ASYNC_SLOTS should be defined

### ISSUE THREAD

**Issue by arigo** [cython/cython#1627]
The ``#ifdef PYPY_VERSION`` leaves ``CYTHON_USE_ASYNC_SLOTS`` always undefined, even on PyPy3.  This miscompiles extensions that try to define types with e.g. an ``am_await`` slot.  For example, uvloop complains with:

```
uvloop/loop.c: At top level:
uvloop/loop.c:121550:8: error: unknown type name '__Pyx_PyAsyncMethodsStruct'
 static __Pyx_PyAsyncMethodsStruct __pyx_tp_as_async_BaseFuture = {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

Defining ``CYTHON_USE_ASYNC_SLOTS`` to be ``1`` on PyPy3 gets rid of this particular error (there are others).

**Comment by federikowsky** [comment]
in which file can i find the row that needs to be changed ?

**Comment by scoder** [comment]
This was fixed in 1546cd7b15cacafdbb5142f3bc2776d80240e4f7

**Comment by federikowsky** [comment]
I've pypy3.9 and still got issue
`In file included from uvloop/loop.c:767:
      uvloop/includes/compat.h:74:12: error: implicit declaration of function 'PyContext_CopyCurrent' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          return PyContext_CopyCurrent();`
I opened compat.h and it seems to have problems with including "Python.h".

**Comment by da-woods** [comment]
@federikowsky that doesn't look related to this issue. Please create a new issue (but do make sure it's related to Cython - at a quick look I'm not convinced it is)
