### ISSUE TITLE
Memory leak when using Typed Memory View and np array of	objects (since 2013)

### ISSUE THREAD

**Issue by ckald** [cython/cython#1638]
Hello,

I encountered a problem with my compiled code: the memory is leaking with each call to the cpdef function. Memory profiling shows lots of memoryview objects remaining.

Googling quickly found a couple of similar bug reports, some of them pretty old. The main one, I think, is this one: https://www.mail-archive.com/cython-devel@python.org/msg03817.html

I checked the attached test there — the latest Cython 0.25.2 is leaking as well. 

Please advise how to avoid this — my Cython functions are executed thousands to millions of times and 200 MB program grows to >10 GB because of the leak. 

[leaktest.tar.gz](https://github.com/cython/cython/files/854911/leaktest.tar.gz)

**Comment by ckald** [comment]
Is anybody looking at these issues at all?

**Comment by stefanmh** [comment]
Bump. I'm experiencing this issue, as well.

Repro:

```py
# Compile: cythonize -bi y.pyx

# Run: python -c 'import y; y.main()'

from cpython cimport array
import array
import time
import psutil


cdef f():
	cdef array.array a = array.array('d', [0.0] * 10000)
	cdef double[:] ca = a # Commenting this out prevents the leak

def mem():
	print str(round(psutil.Process().memory_info().rss/1024./1024., 2)) + ' MB'

def main():
	mem()
	for i in xrange(10000):
		f()
	mem()
	time.sleep(1.0)
	mem()
```

Output:

```
$ python -c 'import y; y.main()'
10.9 MB
774.6 MB
774.6 MB
```

Does anyone know of a workaround?

**Comment by stefanmh** [comment]
After applying the patch:

```
$ python -c 'import y; y.main()'
12.96 MB
13.23 MB
13.23 MB
```

**Comment by scoder** [comment]
Is this an issue only in Python 2.x or did anyone encounter it also in Python 3?

**Comment by stefanmh** [comment]
Only in Python2, by the looks of it:

```
$ python3 -c 'import y; y.main()'
11.64 MB
12.13 MB
12.13 MB
```
