### ISSUE TITLE
set update can't take multiple arguments

### ISSUE THREAD

**Issue by japerk** [cython/cython#1645]
If you try to compile code like `s.update(a, b, c)`, cython will complain that update takes 2 arguments, not 4, but it has no problem with `s.update(*[a, b, c])`

**Comment by japerk** [comment]
version 0.25.2

**Comment by cheezman34** [comment]
More precisely, when a set is initialized in local scope like:
`def func(a, b):
	s = {1,2,3}
	s.update(a, b)`
you get an exception, but if the set is not initialized locally, like:
`def func(s, a, b):
	s.update(a, b)`

You don't get the exception.  Presumably cython is optimizing in the first case, and calls an update function that only takes a single parameter, while in the second case it falls back standard python code.  Or something like that.  Python 2.7, btw.
