### ISSUE TITLE
ctypedef struct <name> is not seen

### ISSUE THREAD

**Issue by wl2776** [cython/cython#1657]
The following .pxd file gives error `'circleData' is not a type identifier`

    cdef extern from "globals.h":
        ctypedef struct circleData:
            int x
            int y
            int radius

    cdef extern from "O_Recognition.h":
        cdef struct _internal_data:
            int        DetectedNum
            circleData object_data[2]
            double     NEO[2]
        ctypedef _internal_data INTERNAL_DATA

Full code is here: https://github.com/wl2776/cython_error

Distribution: Anaconda

          platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 2.1.7
         python version : 2.7.13.final.0
       requests version : 2.13.0

Cython version 0.25.2

**Comment by wl2776** [comment]
Removing `cdef extern from` clauses still produces the same error.

**Comment by scoder** [comment]
Thanks for the report, this is a bug in Cython.
The failing bit of code is this:
```
cdef class object_recognition:
    cdef readonly ci.INTERNAL_DATA object_data;
```
This code declares a struct that contains an inner struct member as a Python read-only property, which makes Cython generate a wrapper for it. While generating that property, it apparently fails to make the declaration of the inner struct available to the property code, which then cannot look it up and reports this error on internally generated Cython code.

**Comment by wl2776** [comment]
Adding one more declaration of `circleData` to `cdef extern from "O_Recognition.h":` block removes the compile error.
