### ISSUE TITLE
Is the maximum number of buffer dimensions written in stone?

### ISSUE THREAD

**Issue by JSKenyon** [cython/cython#1686]
This is less of a bug report and more of a query about an undocumented limit on the number of buffer dimensions. 

The problem I am dealing with relies on the use of very large, multi-dimensional (ndim>8) numpy arrays. Until recently, I was only using arrays with ndim=7, and everything worked perfectly. However, upon adding an eighth dimension I received a "More dimensions than the maximum number of buffer dimensions were used." error upon compilation.

Is this a fundamental limit or can it be changed? I have resorted to using the numpy buffer interface with ndim=8, but there is a performance loss. Would a future version of cython allow for a larger/customisable number of buffer dimensions?

**Comment by scoder** [comment]
It is a global setting for the complete module, which means that it applies to all memory views. There is an option for it:
https://github.com/cython/cython/blob/3526e08741c05dd122ffe827d9d8b5864a3436f5/Cython/Compiler/Options.py#L114

**Comment by JSKenyon** [comment]
Ok, so it is possible to edit Options.py to allow for additional dimensions. This feels somewhat like a hack - is there no way that this parameter can be exposed? The code on which I am working is intended to be installed and compiled locally. This might be difficult if it requires changing the internals of Cython.

**Comment by codewarrior0** [comment]
You don't need to edit Options.py - just import it and do `Options.buffer_max_dims = 100`?

**Comment by JSKenyon** [comment]
@codewarrior0 Thanks! I will give that a try.

**Comment by JSKenyon** [comment]
@codewarrior0 @scoder Thank you so much for your help! @codewarrior0, your solution worked perfectly. Thanks for clearing up my misunderstanding.
