### ISSUE TITLE
Documentation contradicts itself about "nogil"

### ISSUE THREAD

**Issue by mhsmith** [cython/cython#1688]
http://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html

> Code in the body of the statement must not manipulate Python objects in any way, and must not call anything that manipulates Python objects without first re-acquiring the GIL. **Cython currently does not check this.**

Then further down:

> Furthermore, any operation that involves Python objects (including calling Python functions) must explicitly acquire the GIL first, e.g. by using a with gil block or by calling a function that has been defined with gil. **These restrictions are checked by Cython** and you will get a compile error if it finds any Python interaction inside of a nogil code section.

**Comment by scoder** [comment]
Thanks. Corrected in 5a1c495896a4742e76cf9eb1e5d90ba659485595
