### ISSUE TITLE
coverity scan complaining about Cython-generated C code

### ISSUE THREAD

**Issue by ThomasWaldmann** [cython/cython#1690]
I recently added borgbackup to https://scan.coverity.com/ and after analyzing the uploaded Python and C code, it complained quite a lot about the generated C code from Cython.

Just wanted to ask whether you want to have a look at that, I could file issues about the most frequent issues. Stuff like uninitialized vars, break statements missing. I didn't verify the stuff, maybe some of it are false positives (but even then, maybe one could try to avoid them somehow, so that Cython-using projects don't get lots of them).

Maybe an even better idea would be if you added Cython as a project to coverity scan, so you could have it analyzed (and also have code generated by it analyzed).

**Comment by cython-notifications** [comment]
Can you give some specific examples? I've found that generated code often
has false positives that are hard to avoid (e.g. control flow that you can
rule out from the input, but is hard to deduce from the output due to
emulating control flow of one language in another). We also use
fall-through intentionally (though it'd be good to annotate this). That
being said, it's good go avoid what we can.

**Comment by ThomasWaldmann** [comment]
```
2622      __Pyx_DECREF(__pyx_t_4); __pyx_t_4 = 0;
2623      __Pyx_DECREF(__pyx_t_5); __pyx_t_5 = 0;
2624      goto __pyx_L15;
2625    }

    CID 1431985 (#1 of 1): Structurally dead code (UNREACHABLE)unreachable: This code cannot be reached: {  PyThreadState *__pyx_ts....

2626    /*exception exit:*/{
2627      __Pyx_PyThreadState_declare
2628      __pyx_L14_error:;
2629      __pyx_t_3 = 0; __pyx_t_2 = 0; __pyx_t_1 = 0; __pyx_t_13 = 0; __pyx_t_14 = 0; __pyx_t_15 = 0;
2630      __Pyx_PyThreadState_assign
2631      __Pyx_XDECREF(__pyx_t_7); __pyx_t_7 = 0;
2632      __Pyx_XDECREF(__pyx_t_8); __pyx_t_8 = 0;
2633      __Pyx_XDECREF(__pyx_t_4); __pyx_t_4 = 0;
```

**Comment by ThomasWaldmann** [comment]
```
1412      kw_args = PyDict_Size(__pyx_kwds);
1413      switch (pos_args) {

    CID 1431949: Missing break in switch (MISSING_BREAK) [select issue]

1414        case  0:
1415        if (likely((values[0] = PyDict_GetItem(__pyx_kwds, __pyx_n_s_path)) != 0)) kw_args--;
1416        else goto __pyx_L5_argtuple_error;

    CID 1431972 (#1 of 1): Missing break in switch (MISSING_BREAK)unterminated_case:
    The case for value 1L is not terminated by a 'break' statement.

1417        case  1:
1418        if (likely((values[1] = PyDict_GetItem(__pyx_kwds, __pyx_n_s_bsd_flags)) != 0)) kw_args--;
1419        else {
1420          __Pyx_RaiseArgtupleInvalid("set_flags", 0, 2, 3, 1); __PYX_ERR(0, 74, __pyx_L3_error)
1421        }

    fallthrough: The above case falls through to this one.

1422        case  2:
1423        if (kw_args > 0) {
1424          PyObject* value = PyDict_GetItem(__pyx_kwds, __pyx_n_s_fd);
1425          if (value) { values[2] = value; kw_args--; }
1426        }
1427      }
```

**Comment by ThomasWaldmann** [comment]
```
 903  /* "borg/crc32.pyx":13
 904 * 
 905 * 
 906 * cdef Py_buffer ro_buffer(object data) except *:             # <<<<<<<<<<<<<<
 907 *     cdef Py_buffer view
 908 *     PyObject_GetBuffer(data, &view, PyBUF_SIMPLE)
 909 */
 910
 911  /* function exit code */
 912  __pyx_L1_error:;
 913  __Pyx_AddTraceback("borg.crc32.ro_buffer", __pyx_clineno, __pyx_lineno, __pyx_filename);
 914  __pyx_L0:;
 915  __Pyx_RefNannyFinishContext();

    CID 1431984 (#1 of 1): Uninitialized scalar variable (UNINIT)5. uninit_use:
    Using uninitialized value __pyx_r. Field __pyx_r.buf is uninitialized.
 
 916  return __pyx_r;
 917}
```
This one is less frequent, but gets classified as "high impact".

**Comment by scoder** [comment]
Thanks for bringing this up, Thomas.

We try to avoid dead code during generation where possible, but sometimes it's just (too) difficult to avoid. It's definitely harmless, but probably worth taking a look in this case.

The "missing" break is intentional. The switch statement is essentially used as a jump-ahead goto here. It appears in pretty much every function with a Python signature.

The missing initialisation of "`__pyx_r`" is usually a false positive but could also refer to a real bug in your own code here. My guess is, however, that coverty is unable to understand the exception handling path here, which should ignore the partially uninitialised struct in the calling code.

**Comment by robertwb** [comment]
The missing initialization of `__pyx_r` ones should be somewhat silenced by 19caad02f792a731f70956dcdc62635ebaa24039.

**Comment by ThomasWaldmann** [comment]
@robertwb yeah, coverity now has ~90 less complaints ("fixed") with cython 0.26.

this one seems new though:

```
 /* function exit code */
1853  __pyx_r = 0;
1854  goto __pyx_L0;
1855  __pyx_L1_error:;
    25. Condition _py_xdecref_tmp != NULL, taking false branch.
1856  __Pyx_XDECREF(__pyx_t_1);
    26. Condition _py_xdecref_tmp != NULL, taking false branch.
1857  __Pyx_XDECREF(__pyx_t_6);
    27. Condition _py_xdecref_tmp != NULL, taking false branch.
1858  __Pyx_XDECREF(__pyx_t_8);
    28. Condition _py_xdecref_tmp != NULL, taking false branch.
1859  __Pyx_XDECREF(__pyx_t_9);
1860  __Pyx_AddTraceback("borg.hashindex.IndexBase.__cinit__", __pyx_clineno, __pyx_lineno, __pyx_filename);
1861  __pyx_r = -1;
1862  __pyx_L0:;
    29. Condition _py_xdecref_tmp != NULL, taking false branch.
1863  __Pyx_XDECREF(__pyx_v_fd);
1864  __Pyx_RefNannyFinishContext();

    CID 1451944 (#1-2 of 2): Resource leak (RESOURCE_LEAK)30. leaked_storage: Variable __pyx_t_13 going out of scope leaks the storage it points to.

1865  return __pyx_r;
1866}
```

**Comment by robertwb** [comment]
Full (ideally minimal) code snippet to reproduce?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.1.0rc1/src/borg/hashindex.pyx#L87 it's this code.

**Comment by enkore** [comment]
That warning is bogus.

```
__pyx_t_13 = hashindex_read(__pyx_v_fd, __pyx_t_2); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 92, __pyx_L11_error)
__pyx_v_self->index = __pyx_t_13;
```

**Comment by scoder** [comment]
Thanks for checking. It's most likely the exception handling code that coverty fails to understand here. It can't be blamed, though, a test of `PyErr_Occurred()` is entirely unrelated to the returned value.

**Comment by scoder** [comment]
That being said, since the return type is a pointer, wouldn't `except NULL` be a suitable declaration for `hashindex_read()` here?
And, couldn't Cython itself help in finding such cases by proposing possible improvements? If the return value has a pointer type, it could generate a marker in its annotation HTML that says: "this could be made more efficient by declaring a dedicated exception value".

**Comment by enkore** [comment]
Yeah, I forgot about except NULL there.

**Comment by robertwb** [comment]
In general `NULL` could be a valid value, but `except NULL` does seem to be the right thing for this particular case.

**Comment by ThomasWaldmann** [comment]
@dalcinl no (I only used c. a few times in total yet - but would be cool too have less "false positives" there).

**Comment by dalcinl** [comment]
See #1960.

**Comment by scoder** [comment]
I think we've solved most/all of these cases by now. I'd rather have a new ticket for anything new (or still open) than leaving this ticket open forever.
