### ISSUE TITLE
hasattr accepts non-string keys, unlike regular Python

### ISSUE THREAD

**Issue by mhsmith** [cython/cython#1702]
<pre>
class O(object):
    pass

o = O()

print delattr(o, None)               # TypeError in Python and Cython
print setattr(o, None, 42)           # TypeError in Python and Cython
print hasattr(o, None)               # TypeError in Python, returns False in Cython
print __builtins__.hasattr(o, None)  # TypeError in Python and Cython
</pre>

**Comment by robertwb** [comment]
Interesting. We're just calling PyObject_HasAttr. I guess https://docs.python.org/3/c-api/object.html lies.

**Comment by codewarrior0** [comment]
Curious! [`PyObject_GetAttr`](https://github.com/python/cpython/blob/2.7/Objects/object.c#L1172-L1203) does the string check, but [`PyObject_HasAttr`](https://github.com/python/cpython/blob/2.7/Objects/object.c#L1206-L1215) clears the error and just returns NULL, so [`builtin_hasattr`](https://github.com/python/cpython/blob/2.7/Python/bltinmodule.c#L883-L917) ends up doing a *second* string check to raise the TypeError.

**Comment by robertwb** [comment]
Preparing a patch now.
