### ISSUE TITLE
__Pyx_PyNumber_IntOrLong can raise TypeError or ValueError, depending on CYTHON_USE_TYPE_SLOTS

### ISSUE THREAD

**Issue by mattip** [cython/cython#1703]
the helper function [__Pyx_PyNumber_IntOrLong](https://github.com/cython/cython/blob/master/Cython/Utility/TypeConversion.c#L268) explicitly raises a ``TypeError``, i.e. on lines 306, 313. However, if ``CYTHON_USE_TYPE_SLOTS`` is not used, it calls directly to ``PyNumber_Int`` in line 298. The error will not be recast by the code on line 314. 

If ``PyNumber_Int`` fails, it raises a ``ValueError``, not a ``TypeError``, so downstream users must catch both errors on platforms like PyPy where ``CYTHON_USE_TYPE_SLOTS`` is not defined.

**Comment by mattip** [comment]
This patch fixes the issue for PyPy at the cost of always running ``PyErr_Clear``

``` diff 
--- a/Cython/Utility/Coroutine.c
+++ b/Cython/Utility/Coroutine.c
@@ -310,10 +310,10 @@ static CYTHON_INLINE PyObject* __Pyx_PyNumber_IntOrLong(PyObject* x) {
       return NULL;
     }
   }
-  else if (!PyErr_Occurred()) {
-    PyErr_SetString(PyExc_TypeError,
+  PyErr_Clear();
+  if (!res)
+  PyErr_SetString(PyExc_TypeError,
                     "an integer is required");
-  }
   return res;
 }
```

**Comment by scoder** [comment]
Agreed that this matches Python behaviour. If PyPy really *always* raises a `ValueError` here, it's a bug on their side. In any case, both can occur.
