### ISSUE TITLE
Multi-dimensional ndarray not optimized

### ISSUE THREAD

**Issue by leftys** [cython/cython#1705]
Access to multi-dimensional ndarrays is not optimized and uses `__Pyx_GetItemInt` function.

> cdef np.ndarray[np.int32_t, ndim=2] a = np.zeros([5, 5], dtype = np.int32)
> a[1][1]

**Comment by robertwb** [comment]
Cython only optimizes indexing when the number of indices matches the number of dimensions, i.e. `a[1,1]` (just like one would want to do for efficiency in plain Python).

http://cython.readthedocs.io/en/latest/src/tutorial/numpy.html#efficient-indexing

**Comment by scoder** [comment]
Also note that there is nothing (well, almost nothing) really special about ndarrays in Cython, and such an optimisation would not apply to indexing into arbitrary other objects. Optimising this very specific use case seems wrong in that light.

**Comment by leftys** [comment]
My problem was using `[i][j]` instead of `[i, j]`, thanks!
