### ISSUE TITLE
error: [WinError 2] O sistema não pode encontrar o arquivo especificado

### ISSUE THREAD

**Issue by taisreis** [cython/cython#1707]
I'm follows the basic tutorial http://docs.cython.org/en/latest/src/tutorial/cython_tutorial.html and I get the following error: 

`running build_ext
building 'helloworld' extension
error: [WinError 2] O sistema não pode encontrar o arquivo especificado`

It creates the .c file but dosen't create the .pyd file.

Codes: https://gist.github.com/taisreis/552e190aba1772bbae79987e01f1efe3

Python: 3.5
Cython: 0.25.2
Compiler: Microsoft Visual C++ 2010
SO: Windows 8

**Comment by scoder** [comment]
The error message seems to be "file not found". Is that the complete output that you get? Could you try to find out which file it's referring to?

**Comment by taisreis** [comment]
This only output that I have and I don't know wich file is missing. The files on the tutorial it's only the helloworld.pyx and the setup.py that are in the same directory. It's possible that it hasen't found the compiller Microsoft Visual C++ 2010 already that it creates the .c file and don't create the .pyd file?

**Comment by taisreis** [comment]
Hello guys
I uninstalled the Cython and I installed with conda in my env and it works. I think that the installation with pip should have some error.
