### ISSUE TITLE
32-bit float is not range-checked

### ISSUE THREAD

**Issue by mhsmith** [cython/cython#1709]
When converting a Python int to any C integral type, Cython checks the data type's limits and may raise `OverflowError`. But it doesn't do the same when converting to a 32-bit float, because it simply has:

`#define __pyx_PyFloat_AsFloat(x) ((float) __pyx_PyFloat_AsDouble(x))`

**Comment by robertwb** [comment]
There are no data type limits for 32-bit floats, only limited precision, and when casting to a float it's explicit that precision is lost. Positive and negative infinity are used as approximations for values that are outside the range that can be finitely represented, and that's correct for this context as well. 

(FWIW, unless you're memory-bound, there's little reason these days to use 32-bit floats and lots of reasons not to.)

**Comment by mhsmith** [comment]
I see your point, but accidental conversion to infinity could really ruin someone's day. If C won't implicitly convert a double to a float, is it really correct for Cython to do so?

**Comment by scoder** [comment]
It does it because you asked for it. This conversion is only used in code that explicitly asks for a float instead of a double.

**Comment by robertwb** [comment]
It could also ruin someone's day for 1e-100 to get truncated to 0. Or for a*b to be infinity despite a and b being finite. 

Note that this is what NumPy does as well

```
>>> np.array([1e-100, 1e100], dtype=np.float32)
array([  0.,  inf], dtype=float32)
```

**Comment by mhsmith** [comment]
OK, fair enough.
