### ISSUE TITLE
pyximport does not work

### ISSUE THREAD

**Issue by panosss** [cython/cython#1723]
I have file helloworld.pyx, with this content:
`print ("Hello World")`

A file helloworld.py, with this content:
`import pyximport; pyximport.install()
import helloworld`

I run it but doesn't work.

On the other hand, with the first way mentioned in the [tutorial](http://docs.cython.org/en/latest/src/tutorial/cython_tutorial.html) (python setup.py build etc etc...) worked fine.

But with pyximport it doesn't.
What am I doing wrong?

I have python 3.4.4, Visual Studio 10, Win 7.

**Comment by panosss** [comment]
I renamed  helloworld.py to  helloworld_main.py and it works!
This means that the 2 files (the .py and the .pyx) must have different names!

**Comment by robertwb** [comment]
Yes, `X.py`, `X.pyc`, `X.pyx`, `X.dll`, and `X.so` all define the module `X`. The import mechanism will pick at most one of them when `X` is imported; distinct modules must have distinct (fully qualified) names.
