### ISSUE TITLE
Error: Expected an idenifier

### ISSUE THREAD

**Issue by panosss** [cython/cython#1730]
I 'm trying to use cython this way:
`cython --embed -o betws.c betws.py`
'betws.py' is my python file.

But I get this error (Expected an idenifier) on line 730:
`query.exec(SQL)`

The whole code at this point is:
`self.db.transaction()`
`        for values in all_values:`
`            SQL = "INSERT INTO games (" + fields + ") VALUES ('" + "','".join(str(e) for e in values) + "')"`
`            query.exec(SQL)`
`        self.db.commit()`

SQL is a string. How can I fix this?

**Comment by panosss** [comment]
I changed 'query.exec(SQL)' to 'query_.exec(SQL)' and seems ok!

**Comment by scoder** [comment]
Yes, ``exec`` is a language keyword in Python 2.x (but no longer in Python 3.x).
