### ISSUE TITLE
cpdef override of a cdef method can produce incorrect vtables

### ISSUE THREAD

**Issue by saraedum** [cython/cython#1732]
There seems to be a problem in the way that cython checks for declarations of `cpdef` overrides of `cdef` methods. It seems that this is related to the feature introduced in https://github.com/cython/cython/pull/545.

Consider the following `base.pxd`, `base.pyx`, and `bug.pyx`:
```python
cdef class A:
    cdef a(self)

cdef class B(A):
    pass
    #cpdef a(self)

cdef class C(B):
    cdef c(self)
```

```python
cdef class A:
    cdef a(self):
        return "A.a()"

cdef class B(A):
    cpdef a(self):
        return "B.a()"

cdef class C(B):
    cdef c(self):
        return "C.c()"
```

```python
from base cimport C

def call():
    return C().c()
```

Calling `bug.call()` prints `B.a()`. Enabling the `#cpdef a(self)` fixes the problem, and it prints `C.c()` as expected.

The problem here is that without the `cpdef`, the vtable used by `bug.pyx` is missing the entry for `B.a`.

To solve this problem, one would probably just have to add a check to Cython so it requires `cpdef` overrides of `cdef` methods to be declared in their `.pxd` files.

**Comment by robertwb** [comment]
Thanks for the report and concise repro.

**Comment by roed314** [comment]
Thanks for the quick fix!
