### ISSUE TITLE
Support __len__ for memoryview slices

### ISSUE THREAD

**Issue by symbolique** [cython/cython#1733]
Currently we are forced to use `arr.shape[0]` rather than `len(arr)` in code such as:
```cython
cdef int f(double[::1] arr) nogil:
    return len(arr)
```
Supporting `__len__` would make it more convenient to convert existing Python code and would make the code more compact.

**Comment by scoder** [comment]
`len()` generally works here, but it's a Python thing, i.e. it requires the GIL. It could probably be 'optimised' into something that does not require the GIL, though.

**Comment by scoder** [comment]
One more thing to keep in mind: memory view arguments are allowed to be `None`, which means that `len(arr)` might need to raise a `TypeError`. That also requires the GIL. The transformation into `arr.shape[0]` could at least be done if the `arr` argument is declared as `not None`, but that further restricts the applicability.

**Comment by scoder** [comment]
Please give #1810 a try to see if it works for you.
