### ISSUE TITLE
Internal compiler error on latest dev version of cython

### ISSUE THREAD

**Issue by ngoldbaum** [cython/cython#1737]
I ran into this trying to compile [yt](http://yt-project.org) using the latest version of cython to work around an issue in the latest release. Unfortunately that's not possible right now due to what I think is a regression in the cython compiler.

Reproducible with the following test script:

```bash
wget https://raw.githubusercontent.com/yt-project/yt/master/yt/frontends/artio/_artio_caller.pyx
cython _artio_caller.pyx
```

Cython 0.25.2 compiles this with no problems. Cython's current master branch (specifically 0ef812567) raises the following compiler error:

```
Error compiling Cython file:
------------------------------------------------------------
...

cdef extern from *:
    object PyErr_Format(exc, const char *format, ...)

@cname("__Pyx_carray_from_py_float64__t")
cdef int __Pyx_carray_from_py_float64__t(object o, float64_t *v, Py_ssize_t length) except -1:
                                                  ^
------------------------------------------------------------

carray.from_py:77:51: 'float64_t' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    void PyTuple_SET_ITEM(object  p, Py_ssize_t pos, object o)
    void PyList_SET_ITEM(object  p, Py_ssize_t pos, object o)


@cname("__Pyx_carray_to_py_float64__t")
cdef inline list __Pyx_carray_to_py_float64__t(float64_t *v, Py_ssize_t length):
                                              ^
------------------------------------------------------------

carray.to_py:112:47: 'float64_t' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        PyList_SET_ITEM(l, i, value)
    return l


@cname("__Pyx_carray_to_tuple_float64__t")
cdef inline tuple __Pyx_carray_to_tuple_float64__t(float64_t *v, Py_ssize_t length):
                                                  ^
------------------------------------------------------------

carray.to_py:124:51: 'float64_t' is not a type identifier
```

**Comment by ngoldbaum** [comment]
Bisected tells me this commit is the culprit:

```
437fcbe8fc81a10c89d46152f3240dde9c679c32 is the first bad commit
commit 437fcbe8fc81a10c89d46152f3240dde9c679c32
Author: Robert Bradshaw <robertwb@gmail.com>
Date:   Mon May 15 15:52:47 2017 -0700

    Basic pickling suport.

:040000 040000 be9c31d654ab738fbdcffb5946481ccdc7fbfb7f ef6d35bb41edb25d6603829fc21563e80b840692 M	Cython
:040000 040000 0ca49e51413da84c629074c891371f3823d46042 b219b42a86bf022d62aa4431588e716b763b8e17 M	tests
```

ping @robertwb

**Comment by ngoldbaum** [comment]
I can work around this issue by setting `auto_pickle=False` in my cython compiler directives.

**Comment by robertwb** [comment]
Thanks for helping us get ready for the release :). 

The repro fails due to missing `.pxd` files (and I suspect the root cause was due to a failure to cimport). Can you boil this down to a smaller example?

**Comment by ngoldbaum** [comment]
argh, sorry for the complicated example in the initial report, I should have realized that you need yt installed to compile that file.

Here's a minimal example that fails to compile for me:

```
cimport numpy as np

cdef class foo:
    cdef np.float64_t bar[3]
```

**Comment by robertwb** [comment]
Thanks! Scratching my head at what pickling would have to do with this, I found an even simpler repro

```
cdef np.float64_t bar[3]
print bar
```
similarly 
```
from numpy cimport float64_t as my_float
cdef my_float bar[3]
print bar
```

The issue is that we're using the declared name (rather than its name in the scope) when generating Cython code. (Surprised this hasn't come up before, maybe people have worked around it?) 

We'll likely have to do something similar to https://github.com/cython/cython/blob/master/Cython/Compiler/PyrexTypes.py#L3335 , hopefully more principled.
