### ISSUE TITLE
cimported modules used to be implicitly imported

### ISSUE THREAD

**Issue by ngoldbaum** [cython/cython#1738]
See for example the following test pyx file:

```
# test.pyx

cimport numpy as np

print(np.pi)
```

Compiling this file with cython 0.25.2 produces no error. Compiling it with the current master branch of cython (specifically 0ef812567) produces the following error:

```
Error compiling Cython file:
------------------------------------------------------------
...
cimport numpy as np

print(np.pi)
       ^
------------------------------------------------------------

test.pyx:3:8: cimported module has no attribute 'pi'
```

I guess this is an improvement in correctness, however I bet there's a lot of code out there that was unintentionally depending on the old behavior (there are a few in yt I've found so far).

**Comment by robertwb** [comment]
Cimported modules were never implicitly imported; this change simply turns what would have been a runtime error into a compile-time error. 

We could consider changing the behavior such that cimporting caused importing, but not all pxd files correspond to actual modules (and even if they do, one may not want to actually import them) and it's unclear what the behavior should be in that case.

**Comment by ngoldbaum** [comment]
Ah, good to know. I guess we're catching real bugs in yt then. Thanks for the info!

**Comment by m-dz** [comment]
Hi, I'm seeing the same issue with hdbscan module (issue opened here: https://github.com/scikit-learn-contrib/hdbscan/issues/153), but they seem to have both cimports and imports in place, strange.

Have tested with:

```
# test.pyx

cimport numpy as np
import numpy as np

print(np.pi)
```

and

```
# setup.py

try:
    from setuptools import setup
    from setuptools import Extension
except ImportError:
    from distutils.core import setup
    from distutils.extension import Extension

from Cython.Build import cythonize
import numpy

setup(
    name = "My test app",
    ext_modules = cythonize('test.pyx'),  # accepts a glob pattern
    include_dirs=[numpy.get_include()]
)
```

and can confirm that the errors occur when the `import numpy as np` is missing.
