### ISSUE TITLE
cython generates wrong C code when a char array is reused

### ISSUE THREAD

**Issue by leixure** [cython/cython#1742]
```python
def foo():
    cdef char cstr[256]
    c_get_name(cstr)
    name = cstr
    c_get_address(cstr)
    address = cstr
    return name == address
```

`foo` always returns `True` no matter what is copied to `cstr` by `c_get_name` and `c_get_address`.

Check the generated C code and see `cstr` is just assigned to other `char *` variables instead of calling `PyString_FromString` immediately like pyrex.

Cython calls `PyString_FromString` at a later time for both the `char *` variables, since they just point to the same variable `cstr`, `name == address` is always `True`.

This issue is seen in 0.25.2

**Comment by robertwb** [comment]
This is due to type inference. Here `name` and `address` are inferred to be of type `char*`. If you want them to be objects, write `name = <object>cstr` or `name = str(cstr)` or `cdef object name = cstr` or simply disable inference with a compiler directive.
