### ISSUE TITLE
Decorators to methods in cdef classes may be applied twice

### ISSUE THREAD

**Issue by JelleZijlstra** [cython/cython#1751]
In Cython 0.25, but not 0.24, decorators applied to untyped functions in cdef classes are somehow applied twice. 

I found the following small repro (still needs several files, sorry):

```python
# cythonbug/cythonized.pxd
cdef class Cls:
    pass

# cythonbug/cythonized.py
from .decorator import dec

class Cls:
    @dec()
    def fn(self):
        pass

# cythonbug/decorator.py
def dec():
    def decorator(fn):
        print("called on", fn)
        return fn
    return decorator

# cythonbug/__main__.py
from . import cythonized

```
Without Cython compilation, this prints "called on" once when executed, as expected. However, if I compile cythonized.py to a .so using Cython, I get:
```
$ python3 -m cythonbug
called on <cyfunction Cls.fn at 0x7f3309d7d8e8>
called on <instancemethod fn at 0x7f3309cf9318>
```

In the generated C code I also see two successive calls to `__pyx_t_1`.

**Comment by JelleZijlstra** [comment]
Perhaps #1724 will fix this.

**Comment by jdemeyer** [comment]
> Perhaps #1724 will fix this.

I would guess so, it seems to be the same bug.

**Comment by robertwb** [comment]
Closing as a duplicate.
