### ISSUE TITLE
Illegal C code created with double complex

### ISSUE THREAD

**Issue by michakraus** [cython/cython#1756]
I am using `double complex` numbers in my code in various places, e.g., as array types, with a custom type defined by
```
ctypedef double complex dcomplex
```
This results in faulty C code:
```
/* Declarations.proto */
#if CYTHON_CCOMPLEX
  #ifdef __cplusplus
    typedef ::std::complex< npy_float64 > __pyx_t_npy_float64_complex;
  #else
    typedef npy_float64 _Complex __pyx_t_npy_float64_complex;
  #endif
#else
    typedef struct { npy_float64 real, imag; } __pyx_t_npy_float64_complex;
#endif
static CYTHON_INLINE __pyx_t_npy_float64_complex __pyx_t_npy_float64_complex_from_parts(npy_float64, npy_float
```
The ` typedef npy_float64 _Complex` is invalid as `_Complex` is only allowed to be used with basic types like `float` and `double`. If I manually change `npy_float64` to `double` everything works fine.

Interestingly, the code generated for `float complex` is correct:
```
/* Declarations.proto */
#if CYTHON_CCOMPLEX
  #ifdef __cplusplus
    typedef ::std::complex< float > __pyx_t_float_complex;
  #else
    typedef float _Complex __pyx_t_float_complex;
  #endif
#else
    typedef struct { float real, imag; } __pyx_t_float_complex;
#endif
static CYTHON_INLINE __pyx_t_float_complex __pyx_t_float_complex_from_parts(float, float);
```
This is observed with Cython 0.25.2 on macOS with both gcc 6.3.0 and Apple LLVM's clang 8.1.0.

**Comment by robertwb** [comment]
I'm not sure how the `npy_float64` would get there with the `ctypedef double complex dcomplex` declaration. Could you try to whittle this down to a reproducible snippet?

**Comment by michakraus** [comment]
I spent considerable time trying to understand this behaviour, but it is utmost puzzling. I can identify the code where the `__pyx_t_npy_float64_complex`type is used, but if I isolate it, I do not observe this problem.
The classes, which use this type, are rather complex. They glue together PETSc, FFTW and LAPACK, which all use different representations for complex numbers. The lines where the problem appears, however, just computes entries of a complex array, which are products and sums of real and complex numbers. This looks, for example like this
```
for j in range(self.grid.nv):
    diag[j] = eigen * 0.5 * ( 2. * self.grid.hv * v[j] ) * fac
```
Here, diag and eigen are dcomplex, everything else is double.

I just observed a very interesting effect. The array `v` is defined by
```
cdef double[:] v = self.grid.v
```
If I disable this line and replace `v`in the above code by `self.grid.v`, i.e., 
```
for j in range(self.grid.nv):
    diag[j] = eigen * 0.5 * ( 2. * self.grid.hv * self.grid.v[j] ) * fac
```
the problem magically disappears. In the `grid` class, `v` is defined by
```
cdef readonly np.ndarray v
```
Obviously, this is some old code where the `np.ndarray` should be replace with `double[:]`. But again, isolating this does not show the problem.

**Comment by da-woods** [comment]
I think this should end up fixed by https://github.com/cython/cython/pull/5021 - it just forces the use of the Cython complex implementation for an extern typedef. There's clearly a bit more going on here with Numpy types being auto-deduced which I'm not sure I understand though

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/d26591ad2f86d3666d60fbaade8424ae64f80a5c hopefully
