### ISSUE TITLE
python36.dll not found

### ISSUE THREAD

**Issue by EinderJam** [cython/cython#1766]
I'm reading Cython's FAQ,and i just saw "How can I make a standalone binary from a Python program using cython?"
So i tried to compile a simple .py script with "cython.exe --embed myscript.py",which gives me a myscript.c file.Then i compile it with VS2017(i didn't forget to give path to python36.dll and python36.lib in compiler options)
Then i move my generated .exe file to a VM with a fresh install of windows(that's to say,without any python install),and at runtime,i get a "python36.dll missing,etc...".Did i miss something ? Is there a way to make my program really standalone,and executable on any system without downloading something ?

                                                                                                              Regards,EinderJam

**Comment by robertwb** [comment]
You need to statically link to not have the dynamic dependency. For more help, try asking on the users list.
