### ISSUE TITLE
'NoneType' object is not callable when setting a tracing function

### ISSUE THREAD

**Issue by traff** [cython/cython#1769]
This bug breaks debugging of Cython with PyCharm and pdb. Below is a small project to reproduce the problem. 

Consider this fork of a Cython tutorial at Europython 2017: https://github.com/traff/optimization-rimini-2017 

1) Go to prj folder.
2) Execute python setup.py develop
3) Run unit tests in  ../tests/test_prj.py

The process will terminate with the following exception:
 

```
File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 140, in parseArgs
    self.createTests()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 147, in createTests
    self.module)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/traff/PycharmProjects/optimization-rimini-2017_2/prj/tests/test_prj.py", line 2, in <module>
    from prj import _pyappend
  File "/Users/traff/PycharmProjects/optimization-rimini-2017_2/prj/prj/__init__.py", line 8, in <module>
    from ._mod import _append
  File "prj/_mod.pyx", line 3, in init prj._mod (prj/_mod.c:1342)
  File "prj/_mod.pyx", line 3, in PyMODINIT_FUNC PyInit__mod(void)
TypeError: 'NoneType' object is not callable
```

Note that when sys.setprofile(fun) is executed along with settrace there is no exception.

**Comment by traff** [comment]
Correction: the error disappears not when sys.setprofile(fun) is called, but when the tracing function fun returns not None, but itself.
(I made the wrong conclusion because made 2 changes simultaneously).

**Comment by traff** [comment]
I found the problem: in CPython a call event tracing sets the result returned by the tracing function to the filed frame->f_trace. And a line event tracing checks whether frame.f_trace is null or not and if not, then calls it.
Cython checks tstate->c_tracefun in both cases which seems to be a bug, that leads to the call on the Py_None object.

**Comment by scoder** [comment]
Does 71c1ad42e869f100787d40e7d0b76ae8c26e869f also solve this?

**Comment by scoder** [comment]
I'll assume that this is fixed. Please re-open if it does not work for you.

**Comment by scoder** [comment]
Should be fixed since 0.27, yes. Seems worth a new ticket. Please try 0.29 and provide all information you can gather, especially the Python version, a reproducer snippet and the exact error that you get. Also note that debugging Cython code is different from tracing it and is not necessarily supported by PyCharm, I don't know. It's compiled native code, after all, which is not directly introspectable. Probably worth asking on their side first, to see what their experience is and what support they promise.

Here are two (multi-file) tests that are known to work:
https://github.com/cython/cython/blob/master/tests/run/line_profile_test.srctree
https://github.com/cython/cython/blob/master/tests/run/line_trace.pyx

**Comment by PDiracDelta** [comment]
@scoder damn, I tried to create a minimal working example... but I can't seem to reproduce the issue, even when the new project uses the same conda environment! Do you think it could be an issue with how PyCharm handles debugging, or is that independent? I've been having other issues with that lately...

**Comment by scoder** [comment]
No idea. The last change in the profiling code was for 0.28, so 0.28.5 should have all there is. Unless you can cut down the crashing code somehow, it's unlikely that anyone else can do something about it. You could still try to get it to run under gdb to get more infos about the crash.

**Comment by pseudotensor** [comment]
repro (from https://stackoverflow.com/questions/32163436/python-decorator-for-printing-every-line-executed-by-a-function):

```
import sys

class debug_context():
    """ Debug context to trace any function calls inside the context """

    def __init__(self, name):
        self.name = name

    def trace_calls(self, frame, event, arg):
        # We want to only trace our call to the decorated function
        if event != 'call':
            return
        elif frame.f_code.co_name != self.name:
            return
        # return the trace function to use when you go into that
        # function call
        return self.trace_lines

    def trace_lines(self, frame, event, arg):
        # If you want to print local variables each line
        # keep the check for the event 'line'
        # If you want to print local variables only on return
        # check only for the 'return' event
        if event not in ['line', 'return']:
            return
        co = frame.f_code
        func_name = co.co_name
        line_no = frame.f_lineno
        filename = co.co_filename
        local_vars = frame.f_locals
        print ('  {0} {1} {2} locals: {3}'.format(func_name,
                                                  event,
                                                  line_no,
                                                  local_vars))

    def __enter__(self):
        print('Entering Debug Decorated func')
        # Set the trace function to the trace_calls function
        # So all events are now traced
        sys.settrace(self.trace_calls)

    def __exit__(self, *args, **kwargs):
        # Stop tracing all events
        sys.settrace = None


def debug_decorator(func):
    """ Debug decorator to call the function within the debug context """
    def decorated_func(*args, **kwargs):
        with debug_context(func.__name__):
            return_value = func(*args, **kwargs)
        return return_value
    return decorated_func

@debug_decorator
def testing() :
    a = 10
    b = 20
    c = a + b

testing()
```

With python:

```
 python testtracelines.py 
Entering Debug Decorated func
  testing line 57 locals: {}
  testing line 58 locals: {'a': 10}
  testing line 59 locals: {'a': 10, 'b': 20}
  testing return 59 locals: {'a': 10, 'b': 20, 'c': 30}
```

With pytest:

```
E
==============================================================================
ERROR: tracelines.py::testing
------------------------------------------------------------------------------
Entering Debug Decorated func

Traceback (most recent call last):
  File "/home/jon/h2oai.fullcondatest/tracelines.py", line 50, in decorated_func
    with debug_context(func.__name__):
  File "/home/jon/h2oai.fullcondatest/tracelines.py", line 40, in __enter__
    sys.settrace(self.trace_calls)
TypeError: 'NoneType' object is not callable

------------------------------------------------------------------------------
Ran 1 tests in 0.01s

FAILED (errors=1)
```

If ever one uses pytest, seems can't use this technique, which basically makes it impossible to use since pytest or nosetest are universally used for testing ones code.

**Comment by da-woods** [comment]
@pseudotensor It works for me on the current 0.29.x and master branches.

You don't get any useful information from attempting to trace Cython functions of course (and you most likely never will), but it doesn't crash.

**Comment by pseudotensor** [comment]
```
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cython
>>> cython.__version__
'0.29.21'
>>> 
```

**Comment by da-woods** [comment]
So to clarify:

* if I run `python3 testtracelines.py`I get the same result as you
* If I run `cythonize -if testtracelines.py` then `python3 -c "import testtracelines"` I just get `Entering Debug Decorated func` and nothing else
* If I run `pytest` I get 0 tests run in 0.01s (which suggests I'm using pytest wrong to be honest)

It isn't obvious to me from your description that you're using Cython at all here, so I think you possibly have found the wrong place
