### ISSUE TITLE
cythonmagic jupyterlab compatibility

### ISSUE THREAD

**Issue by akhmerov** [cython/cython#1775]
Due to `jQuery` not being defined in jupyterlab, the `%%cython` magic is unable to show interactive html when invoked inside jupyterlab. See also [jupyterlab#2634](https://github.com/jupyterlab/jupyterlab/issues/2634).

**Comment by scoder** [comment]
I'd be happy to see a pull request by someone who understands (a bit) how jupyterlab wants these things to work. The code isn't complex, it's not using jQuery, and it's right here:

https://github.com/cython/cython/blob/ac4cbf0265735979ea17cedf051652f8603b7034/Cython/Compiler/Annotate.py#L82

**Comment by tdamsma** [comment]
While investigating this I stumbled upon this issue: https://github.com/jupyterlab/jupyterlab/issues/2710:

> Bokeh is inlining a <script> tag in its HTML output. We disallow arbitrary script execution in outputs in JLab because it's a huge security risk and the JLab extension system makes it easier to build Javascript viewers for things in a safer fashion.

I think the same is going on for the cython extension. The `toggleDiv` function is defined in the annotate code, and therefore only loaded after a cell is annotated. The function should instead be loaded when the extension is loaded, so I think it should be moved to https://github.com/cython/cython/blob/master/Cython/Build/IpythonMagic.py

**Comment by scoder** [comment]
Thanks for digging that out. It shouldn't be moved there because it actually belongs to `Annotate.py`, but reusing it from `IPythonMagic.py` sounds good. Pull request welcome.

**Comment by akhmerov** [comment]
IIRC I opened the issue before jupyterlab disabled arbitrary js execution. I believe right now the only way to render html output with javascript is to either write a jupyterlab extension or to use an existing one if it exists.

**Comment by tdamsma** [comment]
Ok, think I figured this out. The following works in a jupyterlab notebook:

``` python

from IPython.core.magic import Magics, magics_class, line_magic
from IPython.display import display, HTML
toggleDiv = """
this.nextElementSibling.style.display != 'block' ? 
this.nextElementSibling.style.display = 'block' : 
this.nextElementSibling.style.display = 'none'
"""

HTML(f"""
    <button onClick="{toggleDiv}">Click</button>
    <div style='display=none'>ok</div>""")
```
The workaround is inlining the toggleDiv in the html, and not using the scripttag. Come to think of it, isn't this just as much of a security issue as allowing js scripts?

**Comment by afshin** [comment]
I agree, this appears to be a bug. I've created this issue: https://github.com/jupyterlab/jupyterlab/issues/4091

Thanks!

**Comment by tdamsma** [comment]
@scoder, could you review the PR, or do you want to wait for the JupyterLab discussion on if this should actually be allowed in the first place?

**Comment by scoder** [comment]
Thanks for the PR. It doesn't really hurt to do it that way, and if it helps for now, then why not. I'll also close the ticket. Please reopen if jupyterlab/jupyterlab#4091 comes to a decision.
