### ISSUE TITLE
List comprehension in functions annotations

### ISSUE THREAD

**Issue by dalcinl** [cython/cython#1782]
@scoder While working in signature embedding, I discovered that the following code leads to a compiler crash. However, set/dict comprehensions seems to be just fine. 

```python
def foo(a: [i for i in range(3)]): pass
```

**Comment by scoder** [comment]
Yeah, list comprehensions are still a bit more special than the others due to the scoping difference in Py2/3...
However, given that annotations are actually reserved for statically analysable type hints, this shouldn't occur anywhere in practice.

**Comment by dalcinl** [comment]
Issue no longer present in master.
