### ISSUE TITLE
assignment of read-only variable ‘q’ when using const long

### ISSUE THREAD

**Issue by ameli** [cython/cython#1798]
There is an issue with `const long` in function parameters that leads to compilation error. Suppose we want to use `const long a` in the argument of a `cdef`, and `a` is being divided somewhere in that function. Something like

```
cdef int DivideTest(const long a,int b):
	cdef int c = a / b
	return c
```
Then this C code is generated for division of `long`:

```
/* None */
static CYTHON_INLINE long const  __Pyx_div_long__const__(long const  a, long const  b) {
    long const  q = a / b;
    long const  r = a - q*b;
    q -= ((r != 0) & ((r ^ b) < 0));
    return q;
}
```
But since `q` is` const`, it raises this error when compiling:

```
test.c: In function ‘__Pyx_div_long__const__’:
test.c:1126:5: error: assignment of read-only variable ‘q’
     q -= ((r != 0) & ((r ^ b) < 0));
     ^
error: command 'gcc' failed with exit status 1
```
It seems the type `const long` from the argument is directly translated into the intermediate variable `q`, where, `q` should be only `long`.

Similarly, suppose this time we use the mod operator `%`:

```
cdef int ModTest(const long a,int b):
	cdef int c = a % b
	return c
```

Then the c code generates this function for division of `long`:

```
/* None */
static CYTHON_INLINE long const  __Pyx_mod_long__const__(long const  a, long const  b) {
    long const  r = a % b;
    r += ((r != 0) & ((r ^ b) < 0)) * b;
    return r;
}
```

But since `r` is `const long`, again the compilation gives:

```
test.c: In function ‘__Pyx_mod_long__const__’:
test.c:1117:5: error: assignment of read-only variable ‘r’
     r += ((r != 0) & ((r ^ b) < 0)) * b;
     ^
error: command 'gcc' failed with exit status 1

```
Which the type of `r` should be only `long`.  (This issue might not affect much since `const` for non-pointer arguments could be simply avoided and becomes redundant on new compilers, however it is usually a good coding practice.)

**Comment by robertwb** [comment]
Fixed the issue above, but FYI, I'd avoid constness in Cython unless it's needed to interoperate with external code.
