### ISSUE TITLE
Cython for building single python library from python module

### ISSUE THREAD

**Issue by dimv36** [cython/cython#1805]
Hello,

I have a project structure like this:

```
mainmodule/
    __init__.py
   module.py
   submodule1/
      __init__.py
      submodulefile1.py
...
```

Can I make one single library, which contains all code of my `mainmodule` by Cython?
Thank you!

**Comment by scoder** [comment]
See here:
https://github.com/cython/cython/tree/master/Demos/freeze

Note that this is a question, not a bug or feature request. It is better suited for the cython-users mailing list.
