### ISSUE TITLE
General cross-platform code to create a Numpy dtype for a given Cython struct?

### ISSUE THREAD

**Issue by tovrstra** [cython/cython#1809]
Say I have the following C struct (in `dlist.h`):

```
typedef struct {
  double dx, dy, dz;  // relative vector coordinates.
  long i, j;          // involved atoms. vector points from i to j.
  double gx, gy, gz;  // derivative of energy towards relative vector coordinates.
} dlist_row_type;
```

My corresponding Cython struct is:

```
cdef extern from "dlist.h":
    ctypedef struct dlist_row_type:
        double dx, dy, dz
        long i, j
        double gx, gy, gz
```

I'm currently creating a compatible Numpy dtype as follows:

```
cdef dlist.dlist_row_type _dlist_row_tmp
delta_dtype = np.asarray(<dlist.dlist_row_type[:1]>(&_dlist_row_tmp)).dtype
```

This is a reasonable cross-platform solution but it involves a temporary variable. Is there a way to get thisdtype without a temporary variable? Thanks!

**Comment by scoder** [comment]
I wouldn't know any, but this is clearly a question rather than a ticket. You should rather ask it on the cython-users or numpy mailing lists.
