### ISSUE TITLE
Fail to find cstdio

### ISSUE THREAD

**Issue by xiaottang2** [cython/cython#1811]
I am trying to build a package `pphash` as an interface between the [pHash](https://www.phash.org/) library and python using cython.

Here are my `phash.pxd` and `pphash.pyx`:

```
# phash.pxd
cdef extern from '/usr/local/include/pHash.h':
    int ph_dct_imagehash(const char* file, unsigned long long &hash)
```

```
# pphash.pyx
cimport phash
```

When I build it using `python setup.py build_ext -i`, it cannot find the `cstdio`, which is included in a dependent header file `CImg.h` by `pphash.c`.

Here is the log:

```
python setup.py build_ext -i
Compiling pphash.pyx because it changed.
[1/1] Cythonizing pphash.pyx
running build_ext
building 'pphash' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/jason/py3/include/python3.5m -c pphash.c -o build/temp.linux-x86_64-3.5/pphash.o
In file included from pphash.c:493:0:
/usr/include/CImg.h:73:18: fatal error: cstdio: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

Is there anything I can do to fix it?

**Comment by scoder** [comment]
Closing, as this is not a problem in Cython. Please use the cython-users mailing list for questions.

(Hint: this might be a C++ header file but you are compiling in C mode.)
