### ISSUE TITLE
Feature Request: Support PEP484

### ISSUE THREAD

**Issue by rp-** [cython/cython#1815]
I have a few .pyx files and wanted to add type hints so I have better support for auto completion in my IDE,
but it seems cython doesn't create `__annotations__` dicts, but at least doesn't have problems parsing them.

I saw that there is some support for PEP 3107, but from the code it looks like only while parsing pure python files?

**Comment by scoder** [comment]
Did you enable the `binding=True` directive?

**Comment by rp-** [comment]
I did now and __annotations__ are there :+1: 
Sorry didn't know this directive would also add this.

Thanks!
