### ISSUE TITLE
__getstate__ not called when inhering from Exception

### ISSUE THREAD

**Issue by Nikratio** [cython/cython#1817]
Consider the following class:

```
cdef class FUSEError(Exception):
    cdef int errno_
    def __cinit__(self, errno):
        self.errno_ = errno
    def __getstate__(self):
        return (self.errno_,)
    def __setstate__(self, state):
        (self.errno_,) = state
    @property
    def errno(self):
        return self.errno_
    @errno.setter
    def errno(self, val):
        self.errno_ = val
```

I would expect that the class can be pickled/copied just fine. However:

```
$ python3 run.py 
10
$ cat run.py 
#!/usr/bin/env python3
import mylib
from copy import copy
inst = mylib.FUSEError(10)
inst.errno = 42
inst_copy = copy(inst)
print(inst_copy.errno)
```

Note that in the copy, the errno attribute has been reset to its *initial* value. Where does that even come from?

Moreover, even if I forbid pickling by defining:

```
    def __getstate__(self):
        raise PicklingError("FUSEError instances can't be pickled")
```
The copy() function still works just fine, and produces the same result.

[testcase.zip](https://github.com/cython/cython/files/1217228/testcase.zip)

**Comment by robertwb** [comment]
Pure Python has exactly the same behavior. This is due to `Exception` defining its own `__reduce__` method which does not use the state getters and setters.
