### ISSUE TITLE
Error cimporting cpython.array with PyPy

### ISSUE THREAD

**Issue by ghackebeil** [cython/cython#1818]
If a Cython project (named "junk" in this case) has the line `from cpython cimport array` in the pyx or pxd file, it compiles fine with PyPy 5.8, but dies as soon as the the compiled project is imported:

```python
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import junk
  File "pypy5.8/site-packages/Cython/Includes/cpython/array.pxd", line 58, in init junk
    ctypedef class array.array [object arrayobject]
ValueError: array.array has the wrong size, try recompiling. Expected 24, got 64
```
I'm testing on a Mac with PyPy 5.8.0 installed via Homebrew. I tested this with Cython 0.26 and Cython master as of 90fa8d7c50f4465ba3bca58534d2583551e9a043.

**Comment by scoder** [comment]
My guess is that PyPy simply does not export the same C object layout as CPython here. You should ask on their side if there is anything they can do about it or not.

**Comment by rth** [comment]
> My guess is that PyPy simply does not export the same C object layout as CPython here. 

As far as I understand, the complication seems to be more on the Cython rather than CPython side (cf https://github.com/scikit-learn/scikit-learn/pull/11010#issuecomment-383881016), and won't likely be fixed in PyPy (https://bitbucket.org/pypy/pypy/issues/2807/arrayarray-fails-to-import-in-cython#comment-44922862)

**Comment by jabdoa2** [comment]
@scoder Any chance that this can be resolved at some point? Seems to be common problem around multiple projects when using pypy.

We also got this problem when running our code with kivy. See https://github.com/kivy/kivy/issues/5380

**Comment by scoder** [comment]
The declarations in `cpython/array.pxd` expose the internals of the array implementation in CPython. The only advice I can give you here is: if you need your code to support PyPy, then don't use C level access to the `array.array` data type. That's essentially just saying: if you need portability, don't write non-portable code.

You could try to get away with using the `array` type through a memoryview, but I can't say how well supported (and efficient) that is in PyPy.
