### ISSUE TITLE
Cython compiler accepts wrong extension

### ISSUE THREAD

**Issue by pmfeldman** [cython/cython#1822]
I've noticed that the Cython compiler allows one to compile a file having the wrong extension--.py instead of .pyx--with the former situation producing spurious tracebacks.  Renaming the file eliminates the tracebacks.  I recommend that the Cython compiler either provide the same behavior regardless of the file
extension, or refuse to accept a file having the wrong extension.  If compilation of a file with the .py extension is not necessarily a mistake, the Cython docs should be updated to explain what this does.

**Comment by robertwb** [comment]
Cython compiles .py files that are valid Python files (e.g. without extensions like the "cdef" keywords, though if there's a corresponding .pxd file that'll be applied). See http://cython.readthedocs.io/en/latest/src/tutorial/pure.html

Regardless, we shouldn't be crashing with tracebacks. Can you give us an example?

**Comment by pmfeldman** [comment]
My bad.  It is clearly documented.  I did have Cython extensions in the
file, but had the wrong extension (.py instead of .pyx).  Thanks!
