### ISSUE TITLE
__Pyx_PyNumber_IntOrLong("5") does not raise on PyPy

### ISSUE THREAD

**Issue by mattip** [cython/cython#1835]
There are two code paths in ``__Pyx_PyNumber_IntOrLong``, one with ``CYTHON_USE_TYPE_SLOTS`` used on CPython and the other one used on PyPy. The PyPy one calls ``PyNumber_Int(obj)`` which is equivalent to ``int(obj)`` and will succeed when obj is "5", but the one using slots will raise.

Which tests exercise this code path, what could a possible fix look like?

Note that the tests should be run with ``--no-refnanny`` on PyPy to avoid accessing fresh PyTuples with NULL values still not assigned

**Comment by scoder** [comment]
Thanks for your continuous input, Matti. I appreciate it.

Good call about the refnanny, I've disable it not. We had originally disabled it in the tests, but I enabled it at some point because it seemed to work. It does not help much since the distinct code paths for PyPy that it checks are rare, and I can see that it's outright dangerous in some cases.

I'm a bit unsure regarding your actual question, because the function is definitely used for converting non-int/long object values to numbers. I'll have to take a look. It's part of the normal object to C number conversion.

**Comment by mattip** [comment]
Thanks. FWIW, I am looking into enabling ``CYTHON_USE_TYPE_SLOTS`` for the upcoming PyPy 5.9 release in a few weeks, that might remove much of the incompatibilities and simplify the code paths. I just implemented a always-return-false ``PyType_IS_GC`` on PyPy's HEAD, so tomorrow's nightly might just be ``CYTHON_USE_TYPE_SLOTS`` compatible enough to enable for ``PYPY_VERSION_NUM  >= 0x05090000``

**Comment by scoder** [comment]
> I am looking into enabling `CYTHON_USE_TYPE_SLOTS`

Cool, that would be great to have. (Note that we'd still keep up the alternative implementations, in case users want to disable the low-level slot dependency.)

I looked into the usage of the conversion function, and it's really intended to convert objects that support the number protocol and not anything else. It's used as a fallback for casting when the input object is not an int/long, or when the input value is very large (i.e. > long long). That actually makes it less important than it looks. I think the best place to work around this diversion in behaviour is the last fallback at the bottom of the `CIntFromPy` utility function in `TypeConversion.c`. We could explicitly exclude strings there if slots are not used. That's not time critical code anymore. In fact, I wonder if the conversion function is still relevant at all, given that it's only used in so few places...

Regarding tests, I've extended the `int_float_builtins_as_casts_T400` test to include that code path.

**Comment by mattip** [comment]
this patch fixes the new tests on PyPy, would you like it as a pull request?
```
diff --git a/Cython/Utility/TypeConversion.c b/Cython/Utility/TypeConversion.c
index f81f8c9..10fa7b7 100644
--- a/Cython/Utility/TypeConversion.c
+++ b/Cython/Utility/TypeConversion.c
@@ -338,7 +338,9 @@ static CYTHON_INLINE PyObject* __Pyx_PyNumber_IntOrLong(PyObject* x) {
   }
   #endif
 #else
-  res = PyNumber_Int(x);
+  if (!PyBytes_CheckExact(x) && !PyUnicode_CheckExact(x)) {
+      res = PyNumber_Int(x);
+  }
 #endif
   if (likely(res)) {
 #if PY_MAJOR_VERSION < 3

```

**Comment by scoder** [comment]
I applied that change in f0bc37688464646a85ea1ba49ad944c2b4096937
