### ISSUE TITLE
Compatibility with variable annotations (PEP 526)

### ISSUE THREAD

**Issue by mjos** [cython/cython#1850]
Hi,

when trying to compile the following code:

`n: int = 10`

which uses PEP 526 style variable annotation (introduced in Python 3.6.0 beta 1) we get the following result from cython 0.26.1:

```
Error compiling Cython file:
------------------------------------------------------------
...
n: int = 10
^
------------------------------------------------------------

test.pyx:1:1: Syntax error in simple statement list
```

Is this a known limitation of cython that will be resolved in near future? Our code base uses a lot of variable annotations (helps documenting the code and refactoring) and this issue prevents us from using cython without code changes.

**Comment by TeamSpen210** [comment]
To allow Cython's various syntax changes, it has it's own parser which will need to be updated to handle those. Issue #1672 is also related.

**Comment by scoder** [comment]
Not currently supported, but should be trivial to implement in the parser (and ignore it there for now).

**Comment by scoder** [comment]
@mjos: could you provide a set of tests for this feature? That would simplify the implementation. Just write a .py file to put into /tests/run/ that uses different variations of variable annotations, both at the module level and inside of functions.

**Comment by mjos** [comment]
@scoder Sure, we will prepare something. Thanks.

**Comment by mjos** [comment]
@scoder I have created variable_annotations.py with a buch of examples gathered quickly from the PEP 526. Is it ok like this (see the attachment)?

[variable_annotations.zip](https://github.com/cython/cython/files/1267369/variable_annotations.zip)

**Comment by scoder** [comment]
Implemented in latest master. Could you please give it a try?

**Comment by mjos** [comment]
Sorry for my late reply. Works like a charm! Thanks a lot.

**Comment by lxkain** [comment]
I'm really excited about the prospect of using standard python conventions for optional static typing for cython's purposes. This is a great first step towards it! I am wondering, could we also make this work for the case of

```cdef double f_c(double x):
    return x**2-x```

-->

```cdef f_c(x: float) -> float:
    return x**2-x```

**Comment by lxkain** [comment]
Although, I am not sure how to use python's optional typing to specify the type of `i` in the following code snippet:
```
cdef int i  
for i in range(N):
  ...
```
