### ISSUE TITLE
How to declare multiple public extension class variables at the same time?

### ISSUE THREAD

**Issue by abrahamneben** [cython/cython#1853]
I am looking for a way to define multiple public member variables of an extension class at the same time. I need to main python compatibility. Does this syntax work?

    @cython.cclass
    class Store:
        cython.declare(id=cython.int, num_employees=cython.int, visibility="public")

**Comment by scoder** [comment]
No, there is no way to declare multiple names with one `declare()` call.
Note that this is a support question more than a bug. As such, it is best suited for the cython-users mailing list.
If it's meant as a feature request, that's fine for the issue tracker, but it's unclear from your description why this feature is needed. Why can't you write more than one line?

**Comment by scoder** [comment]
BTW, note that your example is ambiguous. It would prevent users from declaring variables named `visibility`.
