### ISSUE TITLE
Add cpdef support for constants

### ISSUE THREAD

**Issue by brmmm3** [cython/cython#1856]
Code and runtime could be reduced if constants could have a C and a Python definition.
Current situation:
If I want to speedup something like "if FOO == 3" then I normally write "cdef int FOO = <Value>".
But it is very likely that this constant is used in other code fragments like "myList.append(FOO)".
Then the FOO has to be converted first into a Python object which is appended.
A "cpdef int FOO = <Value>" would fix this.

**Comment by scoder** [comment]
Duplicates #656.

**Comment by scoder** [comment]
Duplicates #656.
