### ISSUE TITLE
Confusing documentation on extension type initialization

### ISSUE THREAD

**Issue by mhsmith** [cython/cython#1859]
http://cython.readthedocs.io/en/latest/src/reference/extension_types.html

> By the time __cinit__() is called...
> * Memory has been allocated for the object.
> * All C-level attributes have been initialized to 0 or null.
> * Python have been initialized to None, but you can not rely on that for each occasion.

First, I assume "Python" means "Python object attributes".

Second, if I can't rely on it, then why is it even documented?

**Comment by scoder** [comment]
Thanks, I hope this makes it clearer.
