### ISSUE TITLE
segmentation fault (core dumped) when doing file IO

### ISSUE THREAD

**Issue by zhuzhongshu** [cython/cython#1862]
Hello,
I have trouble in using cython for file reading and preprocessing. The cython generated cpp file can be complied with my main cpp file, but when I run the program, it will throw ` segmentation fault (core dumped)` error.
Here is my test.pyx file:
```
cdef public file_reader():
    result=[]
    with open("haha.txt") as f:
        for line in f:
            result.append(line)
    return len(result)
```
and I want to call `file_reader` in the main.cpp file:
```
#include <iostream>
#include "test.h"

using namespace std;

int main(){
   cout<<file_reader()<<endl;
   return 0;
}
```
My cython version is 0.2.61 and the c++ compiler is clang4.0.1.

Thanks!

**Comment by scoder** [comment]
Please read the documentation:
http://docs.cython.org/en/latest/src/userguide/external_C_code.html#public-declarations
Also see the [embedding example](https://github.com/cython/cython/tree/master/Demos/embed) and the `--embed` compiler option.
