### ISSUE TITLE
"Assignment to reference" bug reintroduced in Cython 0.26.x

### ISSUE THREAD

**Issue by dalleyg** [cython/cython#1863]
A bug was introduced in Cython 0.18 that caused code like this to fail

    cdef void foo(double& out):
        out = 123

with an "Assignment to reference" error.  See https://groups.google.com/d/msg/cython-users/j58Sp3QMrD4/y9vJy9YBi_kJ  The bug was fixed and code like that worked through Cython 0.25.2.  I just tried Cython 0.26.1 and the bug has reappeared.

As before, the workaround is to upgrade the reference parameter to a full pointer then dereference it:

    cdef void foo(double& out):
        (&out)[0] = 123

**Comment by scoder** [comment]
Seems to be allowed in C++, but when I remove the error catcher in `ExprNodes.py`, it doesn't do what you would think. It simply reassigns the variable. I'll ask @robertwb what the intention of this error was.

**Comment by shaggyrogers** [comment]
This issue is still present as of version 0.27.3. Cheers for the workaround @dalleyg.

**Comment by spencer-hann** [comment]
still present in 0.29.13

**Comment by Sasstraliss** [comment]
still present in 0.29.14

**Comment by ewquon** [comment]
still present in 0.29.2

The upgrade/dereference workaround works for cython, but the resulting source code does not compile.

**Comment by scoder** [comment]
It may not be obvious to everyone, but the issue will remain present as long as no-one does something about it.

Since I don't have time to look into this, further investigations and/or a PR that resolves this are welcome.

**Comment by lixin-wei** [comment]
I've met this issue, too. Please fix this issue.

**Comment by da-woods** [comment]
> Seems to be allowed in C++, but when I remove the error catcher in `ExprNodes.py`, it doesn't do what you would think. It simply reassigns the variable.

I think it does actually do what's intended (which is to modify the variable that the reference refers to)

https://github.com/cython/cython/pull/3987

**Comment by datdinhquok** [comment]
I'm converting Python types to C types and changing values of passed-by-ref params is a must, oh god, why is it not allowed in Cython?

**Comment by da-woods** [comment]
@datdinhquok 

> changing values of passed-by-ref params is a must coz Python is passbyref always

But actually Python doesn't do pass-by-reference like C++ assignment to reference. For example

```
def f(x):
   x = False
a = True
print(a)  # True
f(a)
print(a)  # True
```

Based on Python behaviour we shouldn't support assignment to reference. Thanks for pointing that out.
