### ISSUE TITLE
keyword args appear as positional in method signature for cdef class

### ISSUE THREAD

**Issue by johnyf** [cython/cython#1864]
Using the compiler directive [`binding`](http://cython.readthedocs.io/en/latest/src/reference/compilation.html#compiler-directives) and a `cdef class`, `inspect.signature` and `inspect.getfullargspec` both return an incorrect signature for methods: keyword arguments are presented as if they are positional.

**Comment by scoder** [comment]
Could you show an example?

**Comment by johnyf** [comment]
Contents of the file `foo.pyx`:

```cython
# cython: binding=True


cdef class Foo(object):

    def wrong_kw_1(self, a, b=False):
        pass

    cpdef wrong_kw_2(self, a, b=False):
        pass


def correct_kw(self, u, v=True):
    pass

cpdef wrong_kw_3(self, u, v=True):
    pass
```

Run as follows:

```python
import inspect
import pyximport
pyximport.install()

import foo


a = foo.Foo()

# wrong signature for `def` method
>>> inspect.signature(a.wrong_kw_1)
<Signature (a, b)>

# wrong signature for `cpdef` method too
>>> inspect.signature(a.wrong_kw_2)
<Signature (a, b)>

# correct signature for `def` function in module's namespace
>>> inspect.signature(foo.correct_kw)
<Signature (self, u, v=True)>

# wrong signature for `cpdef` function in module's namespace
>>> inspect.signature(hehe.correct_kw_too)
<Signature (self, u, v)>
```

The situation is a little worse than the OP reports: introspection yields wrong signatures for `cpdef` functions too, besides for methods.

```
python == 3.5.2rc1+
cython == 0.26.1
ipython == 6.1.0
```

**Comment by cython-notifications** [comment]
Looks like we're not correctly populating the defaults for these methods.

On Sat, Sep 9, 2017 at 5:24 AM, Ioannis Filippidis <notifications@github.com

**Comment by scoder** [comment]
Yes, they must be missing from the `DefNodeWrapper`. Defaults of methods and `cpdef` functions are currently not tested, neither in `py34_signature.pyx` nor in `cyfunction_defaults.pyx`. Probably easy to fix. Pull request welcome.

**Comment by GliderGeek** [comment]
any news on this issue?

i would like to use the [`websocket-client`](https://pypi.org/project/websocket_client/) package in a cython compiled module, but they are using `getfullargspec`.

anythig i can do to help?

**Comment by scoder** [comment]
Probably related to (or the same as) #2983.

**Comment by mattip** [comment]
> Looks like we're not correctly populating the defaults for these methods.

should be "Looks like we're not correctly populating the `__defaults__` for these methods, which should be done by emitting `PyFunction_SetDefaults` somewhere, I think after emitting [`PyCode_New`](https://github.com/cython/cython/blob/0.29.15/Cython/Compiler/ExprNodes.py#L9532) ? If that makes sense I can try to make a PR

**Comment by WillAyd** [comment]
Is this perhaps an issue with the `LambdaNode` class not having a `code_object` assigned at any point before code generation?

**Comment by da-woods** [comment]
This is now fixed on the current master (I suspect in https://github.com/cython/cython/commit/ee7ae0b9ce0dea51cf17adf119afe439917ee4c0). I think the lambda issue is a different one.
