### ISSUE TITLE
libcpp deque has a random-access iterator.

### ISSUE THREAD

**Issue by Alexhuszagh** [cython/cython#1867]
In `libbcpp.vector`, you define:

```cython
cdef extern from "<vector>" namespace "std" nogil:
    cdef cppclass vector[T,ALLOCATOR=*]:
        ctypedef T value_type
        ctypedef ALLOCATOR allocator_type

        # these should really be allocator_type.size_type and
        # allocator_type.difference_type to be true to the C++ definition
        # but cython doesn't support defered access on template arguments
        ctypedef size_t size_type
        ctypedef ptrdiff_t difference_type

        cppclass iterator:
            T& operator*()
            iterator operator++()
            iterator operator--()
            iterator operator+(size_type)
            iterator operator-(size_type)
            difference_type operator-(iterator)
            bint operator==(iterator)
            bint operator!=(iterator)
            bint operator<(iterator)
            bint operator>(iterator)
            bint operator<=(iterator)
            bint operator>=(iterator)
        cppclass reverse_iterator:
            T& operator*()
            iterator operator++()
            iterator operator--()
            iterator operator+(size_type)
            iterator operator-(size_type)
            bint operator==(reverse_iterator)
            bint operator!=(reverse_iterator)
            bint operator<(reverse_iterator)
            bint operator>(reverse_iterator)
            bint operator<=(reverse_iterator)
            bint operator>=(reverse_iterator)
        cppclass const_iterator(iterator):
            pass
        cppclass const_reverse_iterator(reverse_iterator):
            pass
```

This defines the **most** of the operations for a random-access iterator for a C++ iterator.

However, `libcpp.deque`, which also has a random-access iterator, does not have the same supported methods: in fact, it is treated like a bidirectional iterator.

```cython
cdef extern from "<deque>" namespace "std" nogil:
    cdef cppclass deque[T,ALLOCATOR=*]:
        cppclass iterator:
            T& operator*()
            iterator operator++()
            iterator operator--()
            bint operator==(iterator)
            bint operator!=(iterator)
        cppclass reverse_iterator:
            T& operator*()
            iterator operator++()
            iterator operator--()
            bint operator==(reverse_iterator)
            bint operator!=(reverse_iterator)
        cppclass const_iterator(iterator):
            pass
```

Simply, deque's iterator should support the same methods as vector's iterator does (and ideally, it should also have methods for `size_type operator-(iterator)`. Any standard-compliant implementation of deque such as [Clang's](https://github.com/llvm-mirror/libcxx/blob/master/include/deque) should confirm this.

**Comment by scoder** [comment]
Pull request welcome.

**Comment by Alexhuszagh** [comment]
I'll be submitting a PR very soon then @scoder . Before I do, is there any reason that `const_reverse_iterator` is commented out for deque? The Github issue tracker does not highlight any bugs reference that issue, but I'd rather not possibly revert any fixes. Next, is there any particular reason why `reverse_iterator` has the method `iterator operator++()`, and not `reverse_iterator operator++()`? And finally, may I implement `size_type operator-(iterator)` for both deque and vector iterators?

Thank you.

**Comment by scoder** [comment]
I'll happily leave these questions to @robertwb.

**Comment by robertwb** [comment]
On Mon, Sep 11, 2017 at 1:10 PM, Alexander Huszagh <notifications@github.com
> wrote:

> I'll be submitting a PR very soon then @scoder <https://github.com/scoder>
> . Before I do, is there any reason that const_reverse_iterator is
> commented out for deque?
>
Const iterators are commented out because Cython has no notion of a const
method overriding a non-const method for const objects.

> The Github issue tracker does not highlight any bugs reference that issue,
> but I'd rather not possibly revert any fixes. Next, is there any particular
> reason why reverse_iterator has the method iterator operator++(), and not reverse_iterator
> operator++()?
>
Probably an oversight (and an indication that no one's used it).

> And finally, may I implement size_type operator-(iterator) for both deque
> and vector iterators?
>
> Yes, please.
