### ISSUE TITLE
Memoryview.is_c_contig() and is_f_contig() used in the same block causes `is_f_contig` to be omitted

### ISSUE THREAD

**Issue by dhermes** [cython/cython#1872]
I made a [repro][1] you can check out. The issue manifests at runtime as:

```
undefined symbol: __pyx_memviewslice_is_f_contig2
```

[1]: https://github.com/dhermes/cython-memoryview-issue

**Comment by scoder** [comment]
Thank you for the reproducing example.

**Comment by dhermes** [comment]
Thanks for the fix!
