### ISSUE TITLE
Latest cython release breaks NumPy

### ISSUE THREAD

**Issue by charris** [cython/cython#1882]
```
    numpy/random/mtrand/mtrand.c: In function ‘__pyx_pymod_exec_mtrand’:

    build/src.linux-x86_64-3.6/numpy/core/include/numpy/__multiarray_api.h:1537:144: warning: return makes integer from pointer 
```
In python 3 the return value is NULL

**Comment by stonebig** [comment]
I have a strange behavior also here, that looks very mysterious, and implies a cythonized package. I have it only on Python-3.6, with param compiled package of april 2017 per cgohlke.

 https://github.com/ioam/holoviews/issues/1920#issuecomment-331735592 
 
````
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import version
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import version
ModuleNotFoundError: No module named 'version'
>>> import holoviews as hv
>>> import version
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import version
  File "param\version.py", line 83, in init param.version (param\version.c:7238)
    import os, subprocess
SystemError: Parent module 'version' not loaded, cannot perform relative import
>>> 
````

**Comment by scoder** [comment]
@stonebig: this seems unrelated.
@charris: could you provide the relevant C code lines in which this occurs?

**Comment by charris** [comment]
In the cythonized file it is
```
  /* "mtrand.pyx":143
 * 
 * # Initialize numpy
 * import_array()             # <<<<<<<<<<<<<<
 * 
 * cimport cython
 */
  import_array();
```

The compiler warning message is
```
gcc: numpy/random/mtrand/mtrand.c
numpy/random/mtrand/mtrand.c: In function ‘__pyx_pymod_exec_mtrand’:
numpy/random/mtrand/mtrand.c:43560:3: warning: return makes integer from pointer without a cast [-Wint-conversion]
   import_array();
   ^~~~~~~~~~~~
```
And the underlying C code that causes the problem is
```
#if PY_VERSION_HEX >= 0x03000000
#define NUMPY_IMPORT_ARRAY_RETVAL NULL
#else
#define NUMPY_IMPORT_ARRAY_RETVAL
#endif

#define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
```

As you can see, for Python 3 the return value is the pointer `NULL`. The file from which that comes is generated, so you won't find it except in the build directory. This all works fine with Cython 0.26.

**Comment by charris** [comment]
The `__pyx_pymod_exec_mtrand` function seems to be new in 0.27.

**Comment by scoder** [comment]
But isn't that a bug in NumPy? It should be raising a proper exception here, via Cython code, instead of raising the exception from C and then returning with an explicit return value (that Cython cannot see or control) from the Cython generated module init function. Basically, it's executing a return from global module code here.

Could you change the import macro into an inline function written in Cython code? That should fix it.

**Comment by charris** [comment]
Not really, `import_array` is a macro used by everyone writing C extensions for numpy, Cython is irrelevant in the larger picture. I think the question is, why is Cython interpreting it as a function rather than a macro generating a code block? Currently it is defined in `mtrand.pxd` as `void import_array()`, which I understand is the correct way to indicate a macro to Cython. If there is a better way I'd be happy to learn it.

**Comment by charris** [comment]
Are you suggesting that we write a cdef python function in `mtrand.pyx` and then call it in the module body?

**Comment by scoder** [comment]
> Currently it is defined in mtrand.pxd as void import_array()

That's what I meant. You can replace that declaration by an inline function right there. Returning from the middle of a module init function, without giving Cython a chance to clean up its local state, is totally a bad idea and bound to leak references etc. Just spell it
```cython
cdef extern from "...":
    cdef int _import_array()  # assuming this doesn't set an exception on error but returns -1

cdef inline import_array():
    PyErr_Print()
    if _import_array() < 0:
        raise ImportError("...")
    return None
```

**Comment by charris** [comment]
Note that the header file does not exist at the time Cython is run. Is that a problem?

**Comment by scoder** [comment]
Inline functions in .pxd files are copied by Cython at translation time. They end up as inline C functions in the generated .c files. Cython does not look at the header files, it just generates a C #include for them. As long as the header file exists when the C compiler is invoked on the generated .c files that cimported from the .pxd file, everything should be fine.

**Comment by charris** [comment]
OK, I've fixed it in NumPy. There may be downstream projects that don't use the Cython pxd files that will have problems, not to mention the treatment of macros that generate code blocks that aren't functions.

**Comment by scoder** [comment]
I just found these: https://github.com/cython/cython/blob/0.27/Cython/Includes/numpy/__init__.pxd#L1007
Most existing Cython code that interacts directly with NumPy's C-API probably uses those instead of the `numpy.pxd` in NumPy.

**Comment by scoder** [comment]
Ah, I guess that's where you copied your version from. In Py3, you probably don't need the `PyErr_Print()` thanks to exception chaining, but it helps in Py2. I wonder if we should add it there, too...

**Comment by scoder** [comment]
Anyway, I'll close this since it's externally resolved.
