### ISSUE TITLE
Segfaults on Python exit with py 3.5 using petsc4py

### ISSUE THREAD

**Issue by wence-** [cython/cython#1890]
Cython 0.27 results in segfaults in `PyImport_Cleanup` when exiting Python when it is used to compile petsc4py (https://bitbucket.org/petsc/petsc4py) on Python 3.5.3.  In particular, when clearing the dict of modules:

```
#0  _Py_ForgetReference (op=op@entry=0x7ffff5f85160 <__pyx_moduledef>) at Objects/object.c:1766
#1  0x00000000004a2f6a in _Py_Dealloc (op=0x7ffff5f85160 <__pyx_moduledef>) at Objects/object.c:1794
#2  0x00000000004921a9 in free_keys_object (keys=keys@entry=0xcc7db0) at Objects/dictobject.c:351
#3  0x00000000004976c1 in PyDict_Clear (op=op@entry=0x7ffff7f68448) at Objects/dictobject.c:1388
#4  0x00000000005601ee in PyImport_Cleanup () at Python/import.c:415
#5  0x000000000041ff62 in Py_Finalize () at Python/pylifecycle.c:576
#6  0x0000000000435249 in Py_Main (argc=argc@entry=3, argv=argv@entry=0x904020) at Modules/main.c:788
#7  0x000000000041c799 in main (argc=3, argv=0x7fffffffd938) at ./Programs/python.c:65
```

And `op->_ob_prev` is NULL, which presumably should not happen.

git bisect blames 9f2471dba3.

Any idea as to where to start looking properly?

**Comment by wence-** [comment]
Looks like this is indeed a petsc4py problem (which was indeed playing tricks during import), so no bug here, thanks.

**Comment by scoder** [comment]
I've disabled PEP-489 support by default for 0.27.1. It's too risky for now.
