### ISSUE TITLE
PyInit_modname() functions no longer fully initialize modules on 0.27

### ISSUE THREAD

**Issue by scopatz** [cython/cython#1891]
After migrating from 0.26.1 to 0.27 on Python 3.6.2, calling the `PyInit_modname()` from C is no longer sufficient to fully initialize the module.  This like the string table are left uninitialized, which causes many segfaults, even for static data.  For example, an "def f(): import json" function in Cython will fail because the  `__pyx_string_tab` is never initializes the string constant for `json`, which implies that `__Pyx_InitGlobals` is never called.

I believe that this is because of the new slot-based multiphase init.  

Is there a new method for loading modules from C/C++ that I am missing? Or is this a bug?

**Comment by scoder** [comment]
That's correct. The details are in PEP 489. I also sort-of updated the example in the docs, although it's still not recommended to do that at all.

The question is, why are you explicitly calling the module init function in the first place? Is that some kind of embedding scenario?

**Comment by scopatz** [comment]
Hi @scoder - yeah this is an embedding scenario.  I actually have a few python modules compiled into the same shared object.

For what it is worth, I found a work around for this in [the Python docs here](https://docs.python.org/3/extending/extending.html#the-module-s-method-table-and-initialization-function).  It basically amounts to,

```C++
PyImport_AppendInittab("modname", PyInit_modname);
Py_Initialize();
PyImport_ImportModule("modname");
```

This is a little annoying because the flow in Python 2 is still, 

```C++
Py_Initialize();
initmodname();
```

I guess that is life... Maybe this should be captured in the docs somewhere?

**Comment by scoder** [comment]
I added a doc example here:
https://github.com/cython/cython/commit/5c3b6e995d845e0a9511ff51521876cc13c1bdb1

**Comment by scopatz** [comment]
Thanks @scoder!
