### ISSUE TITLE
Incorrect module name resolution

### ISSUE THREAD

**Issue by mjos** [cython/cython#1892]
Hi,

when trying to import module from global namespace from a local module that happens to have the same unqualified name, the local module is imported instead of the one from global namespace (cython 0.27).

Example:

Project structure:
```
main.py
module/__init__.pyx
module/builtins.pyx
```

content of main.py:
```
import module.builtins
```

content of module/builtins.pyx:
```
from builtins import open
```

Running: ```python main.py``` results in:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import module.builtins
  File "module/builtins.pyx", line 1, in init module.builtins
    from builtins import open
ImportError: cannot import name open
```

**Comment by scoder** [comment]
Use `from __future__ import absolute_import`, or switch to `language_level=3`.

**Comment by mjos** [comment]
Thanks!
