### ISSUE TITLE
Type Inference System, Program Analysis Project

### ISSUE THREAD

**Issue by usama54321** [cython/cython#1893]
Hi,

I am a Computer Science student, and am taking a Program Analysis Course this semester. As part of the course, I am going to work on a project, under the guidance of an instructor. My project idea has been to work on optimizing the type inference/system of a dynamically typed compiled system. After going through a few projects online, I came upon cython, and it seems to fit my project description exactly. 

I have been going through the documentation, and have read about the auto inference system working on the basic C types except Integers. What I have in mind so far is to work on improving the type analysis system, so it can also infer the return types of functions, as requested [here](https://github.com/cython/cython/issues/1073), and maybe build up further from there.

I would be really thankful if you could give me some overview about the type analysis system in place already, and where to start reading up on the internals of the library.

Thanks
Usama

**Comment by scoder** [comment]
Cool, excellent idea :)

You've probably already found the current type inference driver in
https://github.com/cython/cython/blob/master/Cython/Compiler/TypeInference.py
It builds upon the `infer_type()` methods of each of the expression nodes in the syntax tree, see `ExprNodes.py`. Currently, type inference is done only inside of functions. Not at the global module level, and not across functions. And it is mostly limited by safety considerations. We cannot infer some unsafe C type where the code suggests Python semantics (unlimited integers, arbitrary subtypes of Python classes, etc.).

To get started, you can look through the hacker guide:
https://github.com/cython/cython/wiki/HackerGuide#getting-started
It's probably not entirely up to date, but it should give you an entry point.

For project communication, please subscribe to the [cython-devel](https://mail.python.org/mailman/listinfo/cython-devel) mailing list. A bug tracker is not a good place to discuss general organisational things etc.

**Comment by scoder** [comment]
Closing since this didn't lead anywhere.
