### ISSUE TITLE
Cython.Coverage: error with pyx-file coverage with lower-case filenames and wrong line numbers in .coverage

### ISSUE THREAD

**Issue by MaxBo** [cython/cython#1898]
On windows, 
with cython0.27
and 
Coverage.py, version 4.3.4 with C extension

I try to report the coverage of a pyx-file with the Cython.Coverage plugin for coverage.py
`coverage run --source=src -m py.test --pyargs cythonarrays` the .coverage-file including line-numbers that were hit for the .pyx files.
However, `coverage report` issues 

> src\cythonarrays\array_shapes.pyx   TypeError: 'NoneType' object is not iterable
> src\cythonarrays\tests\example_cython.pyx   TypeError: 'NoneType' object is not iterable

Unfortunately, the coverage module catches the exception and did not show where the error occured.
So i had to patch coverage.summary.py to get the tracebak, which showed me, that set(self._code), becuase self._code was None in line 286 in 

```
class CythonModuleReporter(FileReporter):
    def lines(self):
        return set(self._code)
```

Further debugging led me to the point, that the "None" of self._code came from

```
class Plugin(CoveragePlugin):
    def _parse_lines(self, c_file, sourcefile):
        if sourcefile not in self._c_files_map:
            return (None,) * 2  # e.g. shared library file
```

and sourcefile was not in self._c_files_map, because sourcefile started with C:\Dev\cythonarrays\..., while the key in the self._c_files_map-dictionary was written with lowercase c:\dev\cythonarrays...
So abspath returns the path with lowercase because it finds the files in PATH. I installed the package ediable with pip install -e cythonarrays and this lead to entries in easyinstall.pth with lowercase path.

To patch the problem, i converted all filepaths to lowercase

```
class Plugin(CoveragePlugin):

    def file_reporter(self, filename)
        filename = os.path.abspath(filename).lower()

    def _parse_lines(self, c_file, sourcefile):
        (...)
        for filename, code in code_lines.items():
            abs_path = _find_dep_file_path(c_file, filename).lower()
```
This adds the *.pyx-files to the report.

However, this might be not the best solution, which works always on windows and linux...
Maybe you have another idea how to fix this.

The other problem are the line numbers reported by `coverage run` and stored in the .coverage result file, for the .pyx-file, which do not match the actual line numbers in the pyx-file.
In the .coverage -file, for my example_cython.pyx-file there are 26 line numbers between 1 and 983 collected.
`!coverage.py: This is a private format, don't read it directly!{"lines":{"C:\\Dev\\cythonarrays\\code\\cythonarrays\\src\\cythonarrays\\tests\\example_cython.pxd":[],"C:\\Dev\\cythonarrays\\code\\cythonarrays\\src\\cythonarrays\\tests\\example_cython.pyx":[1,246,10,288,207,983,537,155,284,285,286,31,32,289,290,291,36,37,287,243,244,245,54,55,314,315]},"file_tracers":{"C:\\Dev\\cythonarrays\\code\\cythonarrays\\src\\cythonarrays\\tests\\example_cython.pyx":"Cython.Coverage.Plugin","C:\\Dev\\cythonarrays\\code\\cythonarrays\\src\\cythonarrays\\tests\\example_cython.pxd":"Cython.Coverage.Plugin","C:\\Dev\\cythonarrays\\code\\cythonarrays\\src\\cythonarrays\\array_shapes.pyx":"Cython.Coverage.Plugin"}}`

 The  example_cython.pyx file has only 86 lines. 

The C-File i generated contains comments for the traced lines in the actual .pyx-file like:

>  /* "cythonarrays/tests/example_cython.pyx":31
 
to C-imported files like:
 

> /* "../../../../Anaconda/envs/cythonarrays/lib/site-packages/Cython/Includes/numpy/__init__.pxd":220

and to View.MemoryView and to a "Tree fragment"

> /* "View.MemoryView":120
>  /* "(tree fragment)":1

So the strange numbers the Cython.Coverage plugin collected in the c-file are mostly line numbers refering to the "View.MemoryView" 

```
  /* "View.MemoryView":983
 *         return self.from_object
 * 
 *     __pyx_getbuffer = capsule(<void *> &__pyx_memoryview_getbuffer, "getbuffer(obj, view, flags)")             # <<<<<<<<<<<<<<
 * 
 * 
 */
```

or to the "tree fragment"

 ```
 /* "(tree fragment)":1
 * def __reduce_cython__(self):             # <<<<<<<<<<<<<<
 *     cdef bint use_setstate
 *     state = (self.INF_d, self.INF_f, self.NAN_d, self.NAN_f, self.NINF_d, self.NINF_f, self._invalid_g, self._jobs_j, self._km_ij, self._not_initialized_ij, self._param_g, self._persons_gi, self._trips_ij, self._valid_g, self._zonenumbers_i, self.destinations, self.groups, self.n_threads, self.origins)
 */
```
What could be the reason that these line numbers are collected instead of the numbers of the lines in the actual .pyx-file, that were hit?

**Comment by MaxBo** [comment]
I found an alternative to .lower(), that helped to get the right line_numbers:

Instead of converting the filepath to lowercase, the following function returnes the filepath as the file system returnes it (on Windows - on linux it remains as it is):

```
import glob
def get_actual_filename(name):
    if not sys.platform.startswith('win'):
        return name
    dirs = name.split('\\')
    # disk letter
    test_name = [dirs[0].upper()]
    for d in dirs[1:]:
        test_name += ["%s[%s]" % (d[:-1], d[-1])]
    res = glob.glob('\\'.join(test_name))
    if not res:
        #File not found
        return None
    return res[0]
```
(thanks to [this link](https://stackoverflow.com/questions/3692261/in-python-how-can-i-get-the-correctly-cased-path-for-a-file)

Then the filename then can be converted with 
```
class Plugin(CoveragePlugin):

    def file_reporter(self, filename)
        filename = get_actual_filename(os.path.abspath(filename))

    def _parse_lines(self, c_file, sourcefile):
        (...)
        for filename, code in code_lines.items():
            abs_path = get_actual_filename(_find_dep_file_path(c_file, filename))
```

**Comment by scoder** [comment]
`os.path.normcase()` seems to do what you want:
https://docs.python.org/3/library/os.path.html#os.path.normcase

**Comment by scoder** [comment]
Could you provide a pull request, including a test?

**Comment by MaxBo** [comment]
Writing a good test is difficult, because it depends on the file system of the test server.
Where would you put the test?

I tried os.path.normcase(), but this does not work.
```
os.path._getfullpathname(r'c:\dev\cythonarrays\code\cythonarrays\src\cythonarrays\tests\example_cython.pyx')
'c:\\dev\\cythonarrays\\code\\cythonarrays\\src\\cythonarrays\\tests\\example_cython.pyx'
```
the following returns the right upper and lowercases:
```
os.path._getfinalpathname(r'c:\dev\cythonarrays\code\cythonarrays\src\cythonarrays\tests\example_cython.pyx')
'\\\\?\\C:\\Dev\\cythonarrays\\code\\cythonarrays\\src\\cythonarrays\\tests\\example_cython.pyx'
```
but has backslashes and question marks in front of the filepath.
Therefore i used this get_actual_filename - function i found on stackoverflow

**Comment by scoder** [comment]
Regarding tests, look at the `coverage*.srctree` files in `tests/run/`. They are basically a bunch of several text files in one, using a separator. You can run them with `python3 runtests.py -vv coverage` (the last parameter being a test filename regex).
I understand that it's not easy, but you could e.g. rename the source file with different case only on Windows, and then run the analysis on it. That should keep it trivially working on other systems. Travis will tell your if your pull request still works in Linux.

**Comment by scoder** [comment]
`normcase()` makes it all lower case on Windows, which seems ok for comparisons ... ?

**Comment by MaxBo** [comment]
yes, but then the files are not correctly found any more by coverage.py, because coverage uses the filepath with upper and lowercases as it finds it on the disc. Then we would have to patch the code of coverage too, which i would like to avoid.

**Comment by MaxBo** [comment]
thanks for the hint to `coverage*.srctree` I will try to create a reasonable test in the next days.

**Comment by MaxBo** [comment]
I found a better replacement for the _actual_filename function:
from coverage.files import canonical_filename
this ensures, that the same filenames are generated as in the coverage-package.

I tried to run the existing tests in windows, but i failed.
I can run most of the .srctree-tests in windows (2 failures in the pxdbecause of missing support of symlinks in windows:

```
End-to-end pxd_signature_excvalue ... ok
runTest (__main__.EndToEndTest)
End-to-end pxd_syntax ... ok

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (c) and running inlinepxd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Dev\cython\runtests.py", line 1079, in run
    ext_so_path = self.runCompileTest()
  File "C:\Dev\cython\runtests.py", line 768, in runCompileTest
    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
  File "C:\Dev\cython\runtests.py", line 1015, in compile
    so_path = self.run_distutils(test_directory, module, workdir, incdir)
  File "C:\Dev\cython\runtests.py", line 897, in run_distutils
    self.copy_files(test_directory, workdir, related_files)
  File "C:\Dev\cython\runtests.py", line 800, in copy_files
    copy(file_path, join(target_directory, filename))
OSError: symbolic link privilege not held

======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (cpp) and running inlinepxd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Dev\cython\runtests.py", line 1079, in run
    ext_so_path = self.runCompileTest()
  File "C:\Dev\cython\runtests.py", line 768, in runCompileTest
    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)
  File "C:\Dev\cython\runtests.py", line 1015, in compile
    so_path = self.run_distutils(test_directory, module, workdir, incdir)
  File "C:\Dev\cython\runtests.py", line 897, in run_distutils
    self.copy_files(test_directory, workdir, related_files)
  File "C:\Dev\cython\runtests.py", line 800, in copy_files
    copy(file_path, join(target_directory, filename))
OSError: symbolic link privilege not held

----------------------------------------------------------------------
Ran 38 tests in 48.928s

FAILED (errors=2)
Following tests excluded because of missing dependencies on your system:
   compile.posix_pxds
ALL DONE

```

The coverage*.srctrees failed directly, because the quotation marks made problems, so i changed them from
`PYTHON -c 'import shutil; shutil.copy("pkg/coverage_test_pyx.pyx", "pkg/coverage_test_pyx.pxi")'`
to
`PYTHON -c "import shutil; shutil.copy('pkg/coverage_test_pyx.pyx', 'pkg/coverage_test_pyx.pxi')"`

i hope this does not break something in linux.

The coverage-tests however fail, because no data is found:


```
(cythontest) C:\Dev\cython>python runtests.py -vv coverage
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]

Running tests against Cython 0.27 7e39d9e77fbbd33b787af1ab84c15a468f7fe9c5
Backends: c,cpp

runTest (__main__.EndToEndTest)
End-to-end coverage_api ... C:\Anaconda\envs\cythontest\python.exe coverage_test.py

Coverage.py warning: No data was collected.
Traceback (most recent call last):
  File "coverage_test.py", line 66, in <module>
    run_coverage(coverage_test_py)
  File "coverage_test.py", line 44, in run_coverage
    cov.report(file=out)
  File "C:\Anaconda\envs\cythontest\lib\site-packages\coverage\control.py", line 977, in report
    return reporter.report(morfs, outfile=file)
  File "C:\Anaconda\envs\cythontest\lib\site-packages\coverage\summary.py", line 158, in report
    raise CoverageException("No data to report.")
coverage.misc.CoverageException: No data to report.

FAIL
runTest (__main__.EndToEndTest)
End-to-end coverage_cmd ... C:\Anaconda\envs\cythontest\python.exe collect_coverage.py
Name    Stmts   Miss  Cover   Missing
-------------------------------------
No data to report.


Traceback (most recent call last):
  File "collect_coverage.py", line 95, in <module>
    run_report()
  File "collect_coverage.py", line 28, in run_report
    module_path, stdout)
AssertionError: 'coverage_test_py.py' not found in coverage report:

Name    Stmts   Miss  Cover   Missing
-------------------------------------
No data to report.


FAIL
runTest (__main__.EndToEndTest)
End-to-end coverage_nogil ... C:\Anaconda\envs\cythontest\python.exe coverage_test.py

Coverage.py warning: No data was collected.
Traceback (most recent call last):
  File "coverage_test.py", line 46, in <module>
    run_coverage(coverage_test_nogil)
  File "coverage_test.py", line 29, in run_coverage
    cov.report(file=out)
  File "C:\Anaconda\envs\cythontest\lib\site-packages\coverage\control.py", line 977, in report
    return reporter.report(morfs, outfile=file)
  File "C:\Anaconda\envs\cythontest\lib\site-packages\coverage\summary.py", line 158, in report
    raise CoverageException("No data to report.")
coverage.misc.CoverageException: No data to report.

FAIL

======================================================================
FAIL: runTest (__main__.EndToEndTest)
End-to-end coverage_api
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1506, in runTest
    self.assertEqual(0, res, "non-zero exit status")
AssertionError: 0 != 1 : non-zero exit status

======================================================================
FAIL: runTest (__main__.EndToEndTest)
End-to-end coverage_cmd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1506, in runTest
    self.assertEqual(0, res, "non-zero exit status")
AssertionError: 0 != 1 : non-zero exit status

======================================================================
FAIL: runTest (__main__.EndToEndTest)
End-to-end coverage_nogil
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1506, in runTest
    self.assertEqual(0, res, "non-zero exit status")
AssertionError: 0 != 1 : non-zero exit status

----------------------------------------------------------------------
Ran 3 tests in 9.563s

FAILED (failures=3)
ALL DONE
```

So before i can write a new test, i would have to fix the existing for windows. It would be great, if someone who has more insight how the coverage works, would have a look on it.

**Comment by scoder** [comment]
The quotation fix is fine. But the DLL renaming seems backwards. It should better try to find the file. If it doesn't, then coverage reporting is probably not working on Windows currently. I can't say, I don't have access to a Windows system and we are not currently running the external integration tests on Appveyor - guess we should. Any help with fixing the implementation is appreciated. It's probably just the regex in line 110 of Coverage.py that fails to match the different DLL naming scheme.

**Comment by scoder** [comment]
I pushed a regex fix to master. It should now also find Windows DLLs. Please rebase your PR to see if that helps.

**Comment by MaxBo** [comment]
Thanks for the regex. The expression seems ok.
But it does not help.
I still got the error message, that `C:\Dev\cython\TEST_TMP\run\coverage_api\pkg\coverage_test_py.cp36-win_amd64.py` is not found:

Therefore i added the regex to the coverage_api.srctree
```

def source_file_for(module):
    module_name = module.__name__
    path, ext = os.path.splitext(module.__file__)
    if ext == '.so':
        # Linux/Unix/Mac extension module
        platform_suffix = re.search(r'[.](?:cpython|pypy)-[0-9]+[-_a-z0-9]*$', path, re.I)
        if platform_suffix:
            path = path[:platform_suffix.start()]
    elif ext == '.pyd':
        # Windows extension module
        platform_suffix = re.search(r'[.]cp[0-9]+-win[_a-z0-9]*$', path, re.I)
        if platform_suffix:
            path = path[:platform_suffix.start()]
    source_filepath = path + '.' + module_name.rsplit('_', 1)[-1]
    return source_filepath
```
now the tests pass on windows.

**Comment by scoder** [comment]
Nice. Thanks! I'll try it on appveyor as well.

**Comment by scoder** [comment]
Ah, you still had the source line issues. Reopening.

**Comment by scoder** [comment]
Basically, any Cython internals should be ignored, i.e. excluded. External packages, include files, etc. should be mapped to their correct files (which hopefully works already...?).

**Comment by MaxBo** [comment]
Thanks for merging! 
The source line issue was solved with this patch, too. The probem was, that some source line numbers were before mapped to the wrong file, but now it works.
So the issue can be closed

**Comment by jakirkham** [comment]
Hi, I just ran into a similar error (at least from the outset) as the one described in this issue. Though am seeing it on all platforms (macOS, Linux, and Windows) and Python 2/3. For more details please see issue ( https://github.com/jakirkham/cyminmax/issues/13 ). Should I open a new issue or would you prefer to reopen this issue and track it here? This assuming that I'm not missing some Cython option that would fix the issue.

**Comment by scoder** [comment]
A pull request would probably be more helpful. :)
Seriously, most of the work here is usually to come up with a suitable regression test that reproduces the problem. Clearly, our current (passing) tests are not sufficient to cover whatever concrete problem you are facing there. The coverage tests live in the `tests/run/coverage_*.srctree` files, which join multiple files that the test runner in `runtests.py` then splits up again to run the whole thing.

**Comment by jakirkham** [comment]
If I knew what to fix, I could try.... ATM I don't however.

Right. So the issue appears at commit ( https://github.com/jakirkham/cyminmax/commit/675f86170ac89891a3fd56f169fa9003eb50102c ). At this stage, there is not really any Cython code. Just a stub module. Either this is a good test case or simple enough that any error I made could hopefully be easily identified.

Have been working on adding code since and have seen errors along the lines of `stringsource   NoSource: No source for code: ...` as well. Not sure if this is useful information or a red herring. Does seem to be some kind of issue though.

**Comment by scoder** [comment]
Then it's best to open a new ticket for now.

**Comment by jakirkham** [comment]
Ok. Added in issue ( https://github.com/cython/cython/issues/1985 ). Thanks.
