### ISSUE TITLE
Erase returns void in cython unordered_map.pxd

### ISSUE THREAD

**Issue by MichaelWS** [cython/cython#1901]
https://github.com/cython/cython/blob/master/Cython/Includes/libcpp/unordered_map.pxd

Erase returns void in the pxd.  In C++, it returns an iterator in these cases.  Can I issue a pull request to make it
iterator erase(iterator)

**Comment by scoder** [comment]
See https://github.com/cython/cython/pull/1490

**Comment by scoder** [comment]
Duplicate of #1484.

**Comment by MichaelWS** [comment]
sorry removing.  Thank you
