### ISSUE TITLE
NameError for cimported pxd but no compile error

### ISSUE THREAD

**Issue by rpmcnally** [cython/cython#1909]
I've been trying to debug a Cython module that uses a few large pxd files to interface with some external C libraries.  I guess one of them has an error in it somewhere but I'm having a hard time tracking it down and Cython seems to generate odd code as a result.  I've made the smallest example that exhibits the behavior in hopes that there is something I can do to have problems like this flagged (or at least a warning).

mydefs.pxd
```
cdef enum things:
    thing1, thing2, cat
```

mymodule.pyx
```
cimport mydefs
  if mydefs.thing3:
    print "HOORAY
 else:
    print "BOOOO"
```

In this minimal example, I'm obviously accessing something from `mydefs` that doesn't exist, but it compiles fine and the runtime error isn't particularly helpful:
```
  File "myprog.pyx", line 3, in init myprog (myprog.c:803)
    if mydefs.thing3:
NameError: name 'mydefs' is not defined
```

Is there something I can to have Cython check for errors like this?  Why isn't that checked for by default?

**Comment by cython-notifications** [comment]
You should be getting an error "cimported module has no attribute
'thing3'". Are you importing this package as well as cimporting it? What
version of Cython are you using?

**Comment by rpmcnally** [comment]
I apologize, I should have tried the latest version before posting this.  I had been using 0.24; when I attempt to compile the same code with 0.27.1, I do receive the error you mentioned.  I'll have to check with my admins to see if we can get that installed.  Sorry for wasting your time but thank you for the quick response.
