### ISSUE TITLE
Using "except +" adds include "ios"

### ISSUE THREAD

**Issue by tamboril** [cython/cython#1910]
After just adding some `except +` to my `cdefs`, the generated code now has:

    #include "ios"

...which is not available on my platform (CentOS 7)

**Comment by tamboril** [comment]
Never mind.  It's not available with "C" compiler, but is with C++ compiler.
Not sure how to catch C++ exceptions that are thrown by the implementations of my C API.

**Comment by robertwb** [comment]
Correct, one cannot catch C++ exceptions unless using C++ mode to compile your extension. (Even if you got past the missing include, it'd barf at the try { ... } catch { ... } syntax.)
