### ISSUE TITLE
[Windows] Unable to use raw string literal in `cdef extern from` statement

### ISSUE THREAD

**Issue by tusharpm** [cython/cython#1912]
The path separator for Windows (`\`) needs escaping in the string notation, which we worked around using raw string literals `r"<dir>\<file>"`.

A small example is at https://gist.github.com/tusharpm/ac0eef89796ca9c67ca92fe6c6071f6b.

In `mypxd.pxd`, there are two variants of `cdef extern from`:
1. (commented) works - using the escape sequence (`\\`).
2. (not commented) uses the `r"<file_path>"` notation which results in [an error (attached Output.txt)](https://github.com/cython/cython/files/1357081/Output.txt).

**Comment by scoder** [comment]
According to the code in
https://github.com/cython/cython/blob/0.27.x/Cython/Compiler/Parsing.py#L3069
and
https://github.com/cython/cython/blob/0.27.x/Cython/Compiler/Parsing.py#L870
this should actually be supported, although it's probably untested. Coming up with a cross-platform test for this doesn't seem easy...
Could you try to debug that code to see where it goes wrong for you? It should enable `is_raw` in your case and override `kind` with `'u'`, and that should be it.

**Comment by tusharpm** [comment]
In my code, I didn't specify the `language_level=3` directive.
Attaching the debugger showed `is_python3_source` was `False`, and it went to `_append_escape_sequence` (from line 941) even when `is_raw` was set.

The problem I faced is resolved, so I'll close the issue.
Thanks!
