### ISSUE TITLE
Incorrect constant folding for list comprehension with always-false condition

### ISSUE THREAD

**Issue by asottile** [cython/cython#1920]
Originally found [here](https://stackoverflow.com/questions/46633859/list-comprehension-result-differs-between-cython-and-cpython/46634766#46634766)

### Reproduction:

```python
# test.py
assert not [l for l in [1] if False], "FAIL"
```

```
$ python test.py  # succeeds
$ cython -3 --embed test.py && gcc -I/usr/include/python3.5m -O3 -o test test.c -lpython3.5m -lm -lutil -ldl && ./test
Traceback (most recent call last):
  File "test.py", line 1, in init test
    assert not [l for l in [1] if False], "FAIL"
AssertionError: FAIL
```

I've traced the problematic code to https://github.com/cython/cython/blob/14b085980903fa5a172a118929aecbae2d1975c4/Cython/Compiler/Optimize.py#L4197-L4218

Notably: line 4204 is `False` so the condition gets dropped

I think to properly prune this, the `IfStatNode` shouldn't be treated as an `if` statement (which this code seems to do) and specialized code in `visit_ComprehensionNode` should handle this.  Though I'm not familiar with the codebase at all :)

**Comment by BrenBarn** [comment]
Your output shows a `not` in the assert but your example file has no `not`.

**Comment by asottile** [comment]
@BrenBarn indeed, I retyped it in the issue instead of copy pasting, fixed the description.

**Comment by scoder** [comment]
Interesting, thanks for the report. It works when I say `return not [...]`, but not `assert not [...]` or `if not [...]`.
