### ISSUE TITLE
Coercing custom types

### ISSUE THREAD

**Issue by phil0stine** [cython/cython#1925]
Probably trivial, but I cannot find a way to coerce custom `cppdef` object to automatically convert to a Python object. 
The [builtin list](http://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html#standard-library) shows a number of types that can be automatically converted, but when I tried to copy the builtin cppclass definition of `pair` to my own `pxd` file, the builtin `pair` converted to Python, but my custom version did not.

**Comment by robertwb** [comment]
Custom type coercion is not supported in Cython.

**Comment by phil0stine** [comment]
Ok out of curiosity that means that the cython core distribution has these built-in types explicitly defined? Is it a part of the source I can read? 
In any case I will proceed with converting the types via wrapping my c++ classes unless there is a better approach.

**Comment by robertwb** [comment]
Yes: https://github.com/cython/cython/blob/master/Cython/Compiler/PyrexTypes.py#L3398
