### ISSUE TITLE
Support New TSS (Thread Specific Storage) API of Python 3.7

### ISSUE THREAD

**Issue by sonots** [cython/cython#1932]
TLS (Thread Local Storage) API will be deprecated as https://github.com/python/cpython/blob/731e18901484c75b60167a06a0ba0719a6d4827d/Include/pythread.h#L81-L92 and TSS (Thread Specific Storage) API is newly added as https://github.com/python/cpython/blob/731e18901484c75b60167a06a0ba0719a6d4827d/Include/pythread.h#L98-L142.
see also https://www.python.org/dev/peps/pep-0539/

pythread.pxd does not support it yet https://github.com/cython/cython/blob/31752522d88f03642fb9c17474135cb16d2fe474/Cython/Includes/cpython/pythread.pxd.

**Comment by scoder** [comment]
Pull request welcome.
This probably also means that we should update the TLS usage inside of Cython itself, specifically in the `FastGil` code in `ModuleSetupCode.c`.

**Comment by sonots** [comment]
Is there a way to use preprocessors like `#if PY_VERSION_HEX >= 0x03070000` in pythread.pxd?

**Comment by scoder** [comment]
You don't have to. Just declare them there. Users will have to take care that they are only used when available.

That being said, it's probably possible to backport the API to older CPython versions by defining `Py_tss_t` as a simple struct containing an `int` as native key, and then using that as key value in the old TLS C-API. There is already lots of compatibility code in `ModuleSetupCode.c`, so it shouldn't hurt much to add it there.

**Comment by sonots** [comment]
fixed via https://github.com/cython/cython/pull/1939
