### ISSUE TITLE
__lt__, __gt__ and others rich comparisons behave differently as for example __iadd__

### ISSUE THREAD

**Issue by realead** [cython/cython#1935]
The following looks inconsistent:

A small reproducer with cython 0.27.1:

```
cdef class MutableFloat:
    cdef double x
    def __cinit__(self, x):
        self.x=x
    def __iadd__(self, MutableFloat other):
        self.x=self.x+other.x
        return self
    def __lt__(self,  MutableFloat other):
        return self.x<other.x
    def __gt__(self, MutableFloat other):
        return self.x>other.x
    def __repr__(self):
        return str(self.x)
```

and now: 
```
  a,b=MutableFloat(1.0), MutableFloat(2.0)
  a+=b #a=3.0, works
  a<b  #error x unknown
  a>b #error x unknown
```

when  we look at the cythonized functions:
```
static PyObject *__pyx_pf_7mutable_12MutableFloat_2__iadd__(struct __pyx_obj_7mutable_MutableFloat *__pyx_v_self, struct __pyx_obj_7mutable_MutableFloat *__pyx_v_other); /* proto */
static PyObject *__pyx_pf_7mutable_12MutableFloat_4__lt__(PyObject *__pyx_v_self, struct __pyx_obj_7mutable_MutableFloat *__pyx_v_other); /* proto */
static PyObject *__pyx_pf_7mutable_12MutableFloat_6__gt__(PyObject *__pyx_v_self, struct __pyx_obj_7mutable_MutableFloat *__pyx_v_other); /* proto */
```

for `__iadd__`  (and any other functions) `self` is `xxx_MutableFloat` but for rich comparisons `PyObject *`. Maybe this is how it should be, but I didn't find anything  about this  potential problem in the documentation. Anyway if this is "functioning as designed", the need to declare `def __gt__(MutableFloat self, MutableFloat other):` looks strange to me.

**Comment by scoder** [comment]
Typing the arguments of these special methods will give you a TypeError on reversed comparisons. Try 1 < a and a < 1, for example. The semantics are documented in the standard Python docs. We should reference those, I think. A pull request to improve the Cython docs would be appreciated.

**Comment by scoder** [comment]
I take that back...

**Comment by scoder** [comment]
You are right. Python [specifies](https://docs.python.org/3/reference/datamodel.html#basic-customization) their signature as `self, other`.
