### ISSUE TITLE
Internals of exceptions on ThreadState `_ts` struct have moved

### ISSUE THREAD

**Issue by tacaswell** [cython/cython#1955]
https://github.com/python/cpython/commit/ae3087c6382011c47db82fea4d05f8bbf514265d / https://bugs.python.org/issue25612 /  https://github.com/python/cpython/pull/1773 re-arranged how exception information is stored and moved `exc_type`, `exc_value`, and `exc_tracback` into a `_err_stackitem` struct pointed to by `exc_info`.

**Comment by warsaw** [comment]
Maybe I'm doing something wrong but I'm still unable to build lxml from git head of python3.7, cython, and lxml.  The generated etree.c file still references `exc_type`.

Here are the steps I've used to reproduce the problem:

* macOS 10.12.6, Xcode Version 9.1 (9B55)
* clone the CPython repo, configure, make, make altinstall (i.e. to /usr/local)
* `python3.7 -mvenv /tmp/py37`
* `source /tmp/py37/bin/activate`
* clone the Cython repo, cd into that
* `pip install -e .` from inside the virtualenv
```
(py37) % type cython
cython is /tmp/py37/bin/cython
(py37) % cython --version
Cython version 0.28a0
```
* clone the [lxml repo](http://lxml.de/index.html#download) and cd into that
* `make inplace`

This yields tons of warnings and one error.  But it's definitely using the pip installed Cython:

```
(py37) % find . -name \*.c
(py37) % make inplace
python setup.py  build_ext -i  --with-cython --warnings --with-coverage
Building lxml version 4.1.0.
Building with Cython 0.28a0.
...
```

```
src/lxml/etree.c:259432:24: error: no member named 'exc_type' in 'struct _ts'
    if (!__pyx_tstate->exc_type) {
         ~~~~~~~~~~~~  ^
356 warnings and 1 error generated.
Compile failed: command 'gcc' failed with exit status 1
```

```c
    if (!__pyx_tstate->exc_type) {
        Py_INCREF(PyExc_StopIteration);
        __Pyx_ErrRestore(PyExc_StopIteration, exc, NULL);
        return;
    }
```

So what am I doing wrong, or is this a bug in lxml, or is Cython still not quite fixed yet?

**Comment by scoder** [comment]
You are right, there was a left-over. Thanks for insisting.

**Comment by warsaw** [comment]
Cool thanks.  I'll keep an eye on that and try git head again once that lands.

**Comment by warsaw** [comment]
Oh, nm.  I see that's a commit on master.  I was able to build lxml with this change... thanks for fixing this!  Now for the inevitable follow up question, do you have an ETA for a 0.28 release? :)

**Comment by tacaswell** [comment]
Sorry I missed one :disappointed:

**Comment by scoder** [comment]
I sneaked it into 0.27.3, just released.

**Comment by warsaw** [comment]
Awesome, thanks!  I'll give that a try on Monday.

**Comment by warsaw** [comment]
FYI, 0.27.3 works great.  Thanks!

**Comment by markshannon** [comment]
I suspect that this hasn't been fixed. See https://github.com/cython/cython/pull/1956#issuecomment-401597288

**Comment by scoder** [comment]
The syntax fix was correct. The question is rather whether the original implementation was semantically correct. Could well be that there are more/other things to do here now. 

Besides, to verify that the expected Cython version was used to generated a specific C file, look at the version marker in the first line of the file. `head -1 somefile.c` is a useful remote debugging helper here, for those who have to deal with users who complain about failures even after installing the latest Cython.
