### ISSUE TITLE
parallel.parallel(num_threads=None) leads to a generated code which cannot be compiled

### ISSUE THREAD

**Issue by realead** [cython/cython#1957]
In the[ online documentation ](http://cython.readthedocs.io/en/latest/src/userguide/parallelism.html#cython.parallel.parallel) the signature is given as  `cython.parallel.parallel(num_threads=None)`

Please consider the following example (python3.6.2, cython 0.27.1, gcc 5.4):

```
#parallel_error.pyx
from cython import parallel
def do_without_gil():
    cdef:
      unsigned int thread_id
      int i
    with nogil, parallel.parallel(num_threads=None): #that seems to be the problem
        for i in parallel.prange(300, schedule="static", chunksize=10):
            thread_id = parallel.threadid()
            with gil:
                print i,": ",thread_id

#setup.py
from distutils.core import setup
from Cython.Build import cythonize
from distutils.extension import Extension

setup(name="par_error",
      ext_modules=cythonize(Extension('parallel_error', ['parallel_error.pyx'], extra_compile_args=['-fopenmp'], extra_link_args=['-fopenmp'])))
```

and now: 

```
python setup.py build_ext --inplace
Compiling parallel_error.pyx because it changed.
[1/1] Cythonizing parallel_error.pyx
running build_ext
building 'parallel_error' extension
gcc -pthread -B /home/XXX/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/XXX/include/python3.6m -c parallel_error.c -o build/temp.linux-x86_64-3.6/parallel_error.o -fopenmp
parallel_error.c: In function ‘__pyx_pf_14parallel_error_do_without_gil’:
parallel_error.c:1025:307: error: expected integer expression before end of line
error: command 'gcc' failed with exit status 1
```

The problem seems to be the resulting #pragma:

`#pragma omp parallel  private(__pyx_t_1, __pyx_t_2, __pyx_t_3, __pyx_t_4) firstprivate(__pyx_t_5, __pyx_t_6, __pyx_t_7) private(__pyx_filename, __pyx_lineno, __pyx_clineno) shared(__pyx_parallel_why, __pyx_parallel_exc_type, __pyx_parallel_exc_value, __pyx_parallel_exc_tb) num_threads(Py_None)`

`num_threads(Py_None)` seems to be the problem here.

That is probably not a big deal, as  I don't have to use `None` as parameter and can just use `parallel.parallel()`.

**Comment by scoder** [comment]
Thanks for the report.
