### ISSUE TITLE
Pip install fails with error unrecognized command line option ‘-fstack-protector-strong’

### ISSUE THREAD

**Issue by benmishkanian** [cython/cython#1967]
When doing a Pip install of cython, it failed while running gcc with error `unrecognized command line option ‘-fstack-protector-strong’`. Googling this suggests that gcc >= v4.9 is necessary to use this flag. Is this really a hard requirement? Is there any way to make this work with gcc v4.7?

One thing that is confusing me is that I tried installing cython v0.18, which was released before the release of gcc v4.9 and it still had this same error. So is it actually some unrelated issue?

**Comment by scoder** [comment]
Cython does not enforce any specific CFLAGS. Maybe they come in through your Python setup, or via environment variables?

**Comment by benmishkanian** [comment]
Thanks for the quick response. It seems that CFLAGS is not defined on this system:
```Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print os.environ['CFLAGS']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bmishkania/bin/localPython/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'CFLAGS'
```

I even tried setting CFLAGS="" when doing the pip install and it had the same error. Do you have an idea of where these flags may be coming from?

**Comment by scoder** [comment]
Probably from the C compiler flags that were used to build your CPython installation.
In any case, this is not a Cython issue, so I'll close this ticket. For support questions, please contact the cython-users mailing list instead of opening tickets on the bug tracker.
