### ISSUE TITLE
exp does not support complex numbers?

### ISSUE THREAD

**Issue by xoviat** [cython/cython#1976]
It's a small nitpick, but exp should support them.

**Comment by scoder** [comment]
which `exp`?

**Comment by xoviat** [comment]
See https://github.com/scipy/scipy/pull/8114/commits/63ccf5e6d64284565a3708d67c3de5aa113feba0. I had to calculate the result explicitly using the sin/cos formula because it complained about converting to a double.

**Comment by xoviat** [comment]
Looks like `from libc.math cimport exp`.

**Comment by scoder** [comment]
Well, yes, `libc` defines `exp()` on C doubles. That's how it is. C++ has support for complex trigonometry, though: https://github.com/cython/cython/blob/master/Cython/Includes/libcpp/complex.pxd
