### ISSUE TITLE
--no-cython-compile not working with latest release ( 0.27.3)

### ISSUE THREAD

**Issue by twiggy** [cython/cython#1983]
0.27.3 came out over the weekend on Nov 4th 2017.

Some of our build started breaking with 

setup.py: platform.system() => 'Linux'
    setup.py: platform.architecture() => ('64bit', 'ELF')
    setup.py: platform.linux_distribution() => ('Ubuntu', '14.04', 'trusty')
    setup.py: platform.libc_ver() => ('glibc', '2.4')
    setup.py: Not using bundled FreeTDS
    setup.py: include_dirs = ['/usr/local/include']
    setup.py: library_dirs = ['/usr/local/lib']
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --no-cython-compile not recognized

pymssql is dependent on cython in some build scenarios. 

Did 0.27.3 change an option for using --no-cython-compile in some scenarios. perhaps this is some pip/setuptools version issue as well. 

I think pymssql isn't pegged to 0.27.2 and so some change effects its build.

**Comment by twiggy** [comment]
having a requirements file with this 

git+https://github.com/wayfair/pymssql.git@v2.1.3.0.0.1#egg=pymssql

might help reproduce. I'm in a virtual env with python 2.7.13 if that helps as well.

**Comment by scoder** [comment]
I'm not aware of any changes. Do you actually need to pass that option? As long as you are using a standard CPython release series, the binary wheels should work just fine, and pip will be happy to use them.

**Comment by twiggy** [comment]
I'm going to close out for now. I suspect this is an issue with pip and cython requirements. i wanted the no cython compile option took quite a few minutes off the build. i basically have to install cython prior to running a pip install -r requirements.txt command. it also appear to be passing install options to the wrong line. For now i just pegged my previous install to 0.27.2 and put 0.27.2 in the requirements file and all is right. all some sort of dependency tree issue i'm guessing.

**Comment by scoder** [comment]
Also make sure you update `pip` before installing the requirements. Older `pip` versions don't install wheels by default, or may just not find them by their naming scheme.
