### ISSUE TITLE
Cython coverage fails on trivial module

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#1985]
Measuring and reporting the coverage of the Cython module does not appear to be working correctly in the case of this package ( https://github.com/jakirkham/cyminmax/commit/675f86170ac89891a3fd56f169fa9003eb50102c ). In particular, an error is seen when reporting the coverage and trying to submit it. This occurs on both Python 2 and Python 3. Details from the report and submission failures are included below. Links to relevant CI logs are included in the details. While the errors may initially appear to be unrelated, both issues share the same cause on local inspection. On the surface, the problem seems to share a similar cause to issue ( https://github.com/cython/cython/issues/1898 ). However this is not limited to Windows and upgrading `cython` to `0.27.1+` does not seem to affect the issue.

<details>
<summary>Coverage Report Error:</summary>

```python
$ coverage report -m
src/cyminmax.pyx   TypeError: 'NoneType' object is not iterable
Name       Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------
setup.py      54      0     11      0   100%
```

xref: https://travis-ci.org/jakirkham/cyminmax/jobs/298596443#L883-L887

</details>

<br>

<details>
<summary>Coveralls Submission Error:</summary>

```python
$ coveralls
...
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/dplenv/bin/coveralls", line 6, in <module>
    sys.exit(coveralls.wear())
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coveralls/__init__.py", line 94, in wear
    source_files=coverage.coveralls(args.base_dir, ignore_errors=args.ignore_errors, merge_file=args.merge_file),
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coveralls/control.py", line 9, in coveralls
    return reporter.report(base_dir, ignore_errors=ignore_errors, merge_file=merge_file)
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coveralls/report.py", line 20, in report
    analysis = self.coverage._analyze(fr)
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coverage/control.py", line 891, in _analyze
    return Analysis(self.data, it)
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/coverage/results.py", line 19, in __init__
    self.statements = self.file_reporter.lines()
  File "/home/travis/miniconda/envs/dplenv/lib/python3.5/site-packages/Cython/Coverage.py", line 276, in lines
    return set(self._code)
TypeError: 'NoneType' object is not iterable
```

xref: https://travis-ci.org/jakirkham/cyminmax/jobs/298596443#L1003-L1018

</details>

**Comment by scoder** [comment]
I didn't try to reproduce it with your code, but I committed a change that might fix it. Could you try latest master?

**Comment by jakirkham** [comment]
Sure. Thanks for giving it a try. Installed from [`master`]( https://github.com/cython/cython/commit/630f0124414c591315840e5ffa9c8b0df90a235b ) and ran the following using commit ( https://github.com/jakirkham/cyminmax/commit/2553a8e7f43501beb7e343f5fec7ac3712edc4f3 ) of my library.

```
$ coverage run --source . setup.py test
$ coverage report
```

The first line built it from source with all the recommended options I could find enabled. That passed. The second line failed with exit code `1` and emitted the following message.

```
Plugin 'Cython.Coverage.Plugin' did not provide a file reporter for '/Users/kirkhamj/Developer/PyCharmCE/cyminmax/src/cyminmax.pyx'.
```

Also saw some weird warnings when compiling the code. They are shown below. These are weird in the sense that I don't have a `TestClass` object at all and don't have any variables matching the names listed. That said, I doubt this is relevant to the coverage problem. Just seemed worth noting.

```
warning: TestClass:20:10: 'cpdef_method' redeclared 
warning: TestClass:31:10: 'cpdef_cname_method' redeclared 
```

**Comment by jakirkham** [comment]
Going back to the released version, would add that the `.coverage` file contains contents that look something like this (below).

FWICT it seems to be measuring coverage of the Cython files. So it seems the reporting step maybe needs some help finding those files. Seems strange as the filename with full path is included in `.coverage`.

Would add that it also picks up a file called `stringsource`. Not entirely sure where it thinks it finds this as I don't see it anywhere.

<details>
<summary><code>.coverage</code> file:</summary>
<code white-space="pre-wrap">
!coverage.py: This is a private format, don't read it directly!{"arcs":{"/Users/kirkhamj/Developer/PyCharmCE/cyminmax/setup.py":[[-4,4],[4,5],[5,6],[6,8],[8,9],[9,10],[10,11],[11,13],[13,15],[15,18],[-18,18],[18,19],[19,-18],[18,27],[-27,27],[27,28],[28,30],[30,35],[35,-27],[27,40],[40,42],[42,43],[43,47],[47,48],[48,52],[52,56],[56,59],[59,60],[60,61],[61,62],[62,64],[64,70],[70,71],[71,72],[72,76],[76,77],[77,78],[78,84],[84,85],[85,87],[87,88],[88,89],[-88,88],[88,-88],[89,92],[92,93],[93,94],[94,95],[95,96],[96,97],[97,98],[98,101],[101,102],[102,103],[103,104],[104,105],[105,106],[106,107],[107,108],[108,109],[109,114],[114,115],[115,116],[116,117],[117,118],[118,119],[119,120],[120,121],[121,122],[122,125],[125,126],[126,127],[127,125],[125,130],[130,131],[131,132],[132,133],[133,134],[134,135],[135,136],[136,137],[137,138],[138,139],[139,140],[140,141],[141,142],[142,143],[143,144],[144,145],[145,146],[146,147],[147,149],[149,150],[150,151],[151,152],[152,153],[153,154],[154,155],[155,156],[156,157],[157,158],[158,160],[-19,20],[20,22],[22,23],[23,24],[24,-19],[-30,31],[31,32],[32,33],[33,-30],[-35,36],[36,37],[37,-35],[160,-4]],"/Users/kirkhamj/Developer/PyCharmCE/cyminmax/src/cyminmax.pyx":[[-1,3],[3,1],[1,9],[9,1],[1,207],[207,284],[284,285],[285,286],[286,289],[289,290],[290,314],[314,315],[315,537],[537,983],[983,1],[1,-1],[-9,23],[23,25],[25,31],[31,32],[32,34],[34,35],[35,62],[62,-9],[35,38],[38,64],[64,-9],[35,40],[40,64],[35,42],[42,64],[35,44],[44,64],[35,48],[48,64],[35,50],[50,64],[35,52],[52,64],[35,54],[54,64],[35,58],[58,64],[35,60],[60,64]],"/Users/kirkhamj/Developer/PyCharmCE/cyminmax/stringsource":[[-279,280],[280,-279],[-651,652],[652,-651],[-645,646],[-343,344],[344,345],[345,346],[346,347],[347,348],[348,353],[353,354],[354,355],[355,356],[356,361],[361,362],[362,366],[-296,298],[298,304],[304,307],[307,-296],[366,368],[368,-343],[646,647],[647,648],[648,-645],[-370,371],[371,372],[372,376],[376,377],[377,378],[378,379],[379,380],[380,382],[382,381],[381,383],[383,-370],[380,383]],"/Users/kirkhamj/Developer/PyCharmCE/cyminmax/src/cyminmax.pxd":[[-26,27],[27,28],[28,33],[33,38],[38,40],[40,57],[57,65],[65,66],[66,-26],[57,58],[58,60],[60,61],[61,65],[60,62],[62,63],[63,65],[40,41],[41,42],[42,44],[44,45],[45,46],[46,47],[47,55],[55,57],[44,50],[50,51],[51,52],[52,53],[53,55],[52,55],[62,65],[55,41],[50,52],[45,47],[47,48],[48,55]]},"file_tracers":{"/Users/kirkhamj/Developer/PyCharmCE/cyminmax/src/cyminmax.pyx":"Cython.Coverage.Plugin","/Users/kirkhamj/Developer/PyCharmCE/cyminmax/src/cyminmax.pxd":"Cython.Coverage.Plugin"}}
</code>
</details>

**Comment by jakirkham** [comment]
Alright I think I'm starting to see what is going on. It looks like [`_find_dep_file_path`]( https://github.com/cython/cython/blob/0.27.3/Cython/Coverage.py#L33 ) is munging the paths improperly somehow. Namely it is taking paths that look like this `<dir>/src/cyminmax.pyx` and turning them into `<dir>/cyminmax.pyx` instead. This happens [inside `_parse_lines`]( https://github.com/cython/cython/blob/0.27.3/Cython/Coverage.py#L223 ). The result is paths that would have been the same [mismatch here]( https://github.com/cython/cython/blob/0.27.3/Cython/Coverage.py#L226 ) kicking out a `None` for all the files seen.

**Comment by scoder** [comment]
Not entirely impossible that #1900 changed the behaviour here. Suggests that we lack a test for setups like yours. See the `tests/run/coverage_*.srctree` test "archives" for an example (they are a bunch of concatenated files). Pull request welcome.

**Comment by jakirkham** [comment]
So this issue has evolved. Now reporting with Coverage yields an outright failure. ( https://github.com/cython/cython/issues/2718 ) Not sure if we should keep this open or close and migrate to that issue. Mention this specifically because some other people still see problems like this one ( e.g. https://github.com/cython/cython/issues/2265 ).

**Comment by s-sajid-ali** [comment]
Is there at least one working repo with Cython coverage ? 

I have a single function in a [repo](https://github.com/s-sajid-ali/cython_test_coverage) to test cython coverage.  

I've followed all the directives mentioned in the [cython docs](https://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html).

I have in my repo : 
- enabled line tracing in the .pyx file - [1](https://github.com/s-sajid-ali/cython_test_coverage/blob/master/cython_test_coverage/basic_cython.pyx)
- passed the relevant macro to distutils - [2](https://github.com/s-sajid-ali/cython_test_coverage/blob/master/setup.py)
- included cython.coverage in .coveragerc - [3](https://github.com/s-sajid-ali/cython_test_coverage/blob/master/.coveragerc)
- included a cython directive for the html report in .travis.yml - [4](https://github.com/s-sajid-ali/cython_test_coverage/blob/master/.travis.yml)

Yet, I don't see any coverage report for the cython source file on codecov. What am I missing ?

**Comment by scoder** [comment]
> `coverage run --append --source . cython_test_coverage/basic_cython.pyx`

Well, if I understand correctly what the command does then this obviously can't work. `.pyx` files are not executable Python files.

> `python ~/packages/cython/Cython/Coverage.py run --append --source . cython_test_coverage/basic_cython.pyx`

`Cython/Coverage.py` is not an executable script. Running it does nothing.

> Is there at least one working repo with Cython coverage ?

See the `coverage_*.srctree` test cases here:
https://github.com/cython/cython/tree/master/tests/run

> passed the relevant macro to distutils

No, you didn't. The `setup.py` file does not get compiled, so adding compiler directives to it does not help. (And in fact, you don't want the directives to apply to `setup.py` anyway, you want to apply them to the compiled file.)

@s-sajid-ali, please don't hijack arbitrary tickets. If you have problems getting coverage reporting to work for you at all, please ask for help on the mailing list.

**Comment by s-sajid-ali** [comment]
Apologies for posting at the wrong location, I was working on getting a basic coverage before doing the same for a larger repo and this was mentioned on that (thread)[https://github.com/pyFFTW/pyFFTW/issues/235]. If it was off topic or inappropriate please feel free to delete or mark it as off topic. Thanks for pointing out the cython test.
