### ISSUE TITLE
npy_isnan requires GIL

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#1989]
Was rather surprised to see that Cython requires the GIL to use things like `npy_isnan`. Given the function/macro is pure C, not really sure what good the GIL would do. Also would have figured the [`nogil` in `cdef extern`]( https://github.com/cython/cython/blob/0.27.3/Cython/Includes/numpy/math.pxd#L20 ) would have ensured that all functions in that block did not require the GIL. Regardless it appears to be needed. Here is a test file demonstrating the problem below and the compilation error.

<details>
<summary>Test file</summary>

```cython
#filename: test.pyx

cimport numpy
cimport numpy.math

cdef bint test(double a) nogil:
    return numpy.math.npy_isnan(a)
```

</details>

<br>

Using version

<details>
<summary>Compilation error</summary>

```
$ cython --version
Cython version 0.27.3

$ cython test.pyx

Error compiling Cython file:
------------------------------------------------------------
...
cimport numpy
cimport numpy.math

cdef bint test(double a) nogil:
    return numpy.math.npy_isnan(a)
                    ^
------------------------------------------------------------

test.pyx:5:21: cimported module has no attribute 'npy_isnan'

Error compiling Cython file:
------------------------------------------------------------
...
cimport numpy
cimport numpy.math

cdef bint test(double a) nogil:
    return numpy.math.npy_isnan(a)
                              ^
------------------------------------------------------------

test.pyx:5:31: Calling gil-requiring function not allowed without gil
```

</details>

**Comment by scoder** [comment]
The name of that function in the Cython declaration is `isnan()`. As the error says, `npy_isnan()` is not defined.

**Comment by jmschrei** [comment]
Howdy

`isnan()` does not work on Windows machines that compile with MSVC. I've been struggling with getting a fast `isnan` working cross-platform that doesn't require the GIL. Do you have any suggestions?
