### ISSUE TITLE
bug in ipython: fibonacci of ten millions is negative

### ISSUE THREAD

**Issue by spagoc** [cython/cython#1990]
I have a bug for a simple fibonacci calculation using ipython: the fibonacci number of 10 millions is a negative number:
![cython-bug](https://user-images.githubusercontent.com/1367579/32650681-fc87c012-c5fe-11e7-9ca9-15fca962fd55.png)

**Comment by spagoc** [comment]
Sorry I forgot C has limit in integer precision

**Comment by scoder** [comment]
Not really "precision", C integer types have a limited value space (which is even platform specific) and wrap around.
