### ISSUE TITLE
@cython.infer_types(True) is not accepted in pure python mode

### ISSUE THREAD

**Issue by lxkain** [cython/cython#2008]
I have a function declaration like this:

```
@cython.boundscheck(False)
@cython.wraparound(False)
@cython.cdivision(True)
@cython.locals(seq="double[:]")
@cython.infer_types(True)
def isotonic_regression_inplace(seq):
  pass
```

I want to have this code working in pure python mode, but the infer_types is not recognized.

**Comment by scoder** [comment]
Ah, yes. Thanks for the report. There is a typo in `Shadow.py`. I'll fix it for 0.28.

**Comment by lxkain** [comment]
Thank you for this very important tool!

**Comment by lxkain** [comment]
Thanks for the tip about `Shadow.py`, I was able to fix this for now.
