### ISSUE TITLE
How to tell cythonize() to name the generated extension module source file by another name?

### ISSUE THREAD

**Issue by AraHaan** [cython/cython#2017]
lets say for example someone got an python script named ``test.py``. How can they tell cythonize that instead of generating it as ``test.c`` to name the generated c file as ``testmodule.c``?

**Comment by scoder** [comment]
Should be possible by passing an `Extension` instance into `cythonize()`.

**Comment by AraHaan** [comment]
🤔

**Comment by scoder** [comment]
Please read the  documentation:
http://docs.cython.org/en/latest/src/reference/compilation.html#configuring-the-c-build

And please do not use the bug tracker for support questions.
