### ISSUE TITLE
Python 3.6 new `inspect.isasyncgenfunction` and `inspect.isasyncgen`

### ISSUE THREAD

**Issue by danigosa** [cython/cython#2026]
Are they supported? They are always returning False when compiled, as plain Python they work as expected, the function compiled is _printed_ as _cyfunction_ `<cyfunction PgSATable.select_rows at 0x7fe182688100>` . Neither the result if I call the function and check the future is giving True when asynchronous generators.

**Comment by scoder** [comment]
That result is correct. Cython compiled coroutines do not have the same type as Python coroutines. Avoid type checks, or use ABCs for them.

**Comment by scoder** [comment]
BTW, that doesn't mean that CPython couldn't change its behaviour here, but that's not Cython's decision.
