### ISSUE TITLE
Supporting Python 2.7 and 3.6 both from a single Cython based package

### ISSUE THREAD

**Issue by magrawal08** [cython/cython#2028]
Hi,

Is there any way to have a Cython module compatible with both Python 2 and 3? I am aware that the generated .c file can be linked to either python27.dll or python3.dll. But what I am looking is that a way to allow the compiled .pyd to be able to load in both python 2 and 3. Any help is much appreciated.

I also noticed this comment "We are also working to make the compiler run in both Python 2.x and 3.x." on the following page. I am wondering if it is related to my needs somehow.

http://cython.readthedocs.io/en/latest/src/userguide/pyrex_differences.html

Regards,
Mayank

**Comment by robertwb** [comment]
This is not possible. You probably want to build and ship both separately (e.g. see how wheels are done).
