### ISSUE TITLE
libc.math make declarations nogil?

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#2029]
More pandas use cases.

pandas/_libs/src/headers has a bunch of stuff that cython already provides and I'm pushing to use the cython versions.  In this case, it was replacing

```
 cdef extern from "../src/headers/math.h":
     double sqrt(double x) nogil
```
 
with `from libc.math cimport sqrt`.

But upon making that replacement, the affected functions were profiled as 5-15% slower.  See https://github.com/pandas-dev/pandas/pull/18420#issuecomment-346978217 and the comment below it.

_Assuming_ that there aren't any downsides I'm missing, I think cython can get the same bump by declaring those functions as nogil [here](https://github.com/cython/cython/blob/master/Cython/Includes/libc/math.pxd#L64).  (Presumably other functions in `libc.math` would also be affected, but I haven't profiled them).

Is there a reason I'm missing not to declare these as nogil?  If not, I'm happy to submit a PR.

**Comment by robertwb** [comment]
On Wed, Nov 29, 2017 at 9:19 AM, jbrockmendel <notifications@github.com> wrote:
>
> More pandas use cases.
>
> pandas/_libs/src/headers has a bunch of stuff that cython already provides and I'm pushing to use the cython versions. In this case, it was replacing
>
>  cdef extern from "../src/headers/math.h":
>      double sqrt(double x) nogil
>
> with from libc.math cimport sqrt.
>
> But upon making that replacement, the affected functions were profiled as 5-15% slower. See pandas-dev/pandas#18420 (comment) and the comment below it.

This doesn't make any sense (looking at
https://github.com/jbrockmendel/pandas/blob/64d54822dfb5440279f36b37e66808cf741feba4/pandas/_libs/src/headers/math.h
which just gets its sqrt from the same place). Is there anything of
note in the diff of the generated .c file before and after the change?

> Assuming that there aren't any downsides I'm missing, I think cython can get the same bump by declaring those functions as nogil here. (Presumably other functions in libc.math would also be affected, but I haven't profiled them).
>
> Is there a reason I'm missing not to declare these as nogil? If not, I'm happy to submit a PR.

This entire block is declared as nogil
https://github.com/cython/cython/blob/master/Cython/Includes/libc/math.pxd#L1

**Comment by jbrockmendel** [comment]
> This entire block is declared as nogil

Huh, dumb mistake on my part.  Thanks.

>  Is there anything of note in the diff of the generated .c file before and after the change?

I'll do a build with just that one change to check for sure, but based on before/after builds I have lying around, I see 8 occurrences of `sqrt` (and one of `sqrtf`) both before and after, no clear difference.

Probably ought to re-run those benchmarks with large N before putting too much more time into this.
