### ISSUE TITLE
cython threadlocal cause syntax error?

### ISSUE THREAD

**Issue by braindevices** [cython/cython#2036]
I just use exactly advise from [this](https://github.com/cython/cython/wiki/enhancements-prange)  to explicitly declare thread local variables. However it cause an error:
```
  cdef threadlocal(int) old_ell = -1
                         ^
------------------------------------------------------------

: Syntax error in C variable declaration
```

**Comment by scoder** [comment]
Thanks. I added a note to the page that it's not actually documentation. It mostly serves historical purposes.
The actual documentation is here:
http://docs.cython.org/en/latest/src/userguide/parallelism.html
