### ISSUE TITLE
cython.final not allowed on class

### ISSUE THREAD

**Issue by pitrou** [cython/cython#2040]
The doc says:
> `@cython.final` terminates the inheritance chain by preventing a type from being used as a base class, or a method from being overridden in subtypes. This enables certain optimisations such as inlined method calls.

but I get the following error:
```
@cython.cclass
@cython.final
class WorkerState(object):
^
------------------------------------------------------------

distributed/schedulerstate.py:57:0: The final compiler directive is not allowed in class scope
```

**Comment by pitrou** [comment]
And then when I want to add `@cython.final` to a method I get:
```

    @cython.final
    @cython.ccall
    @cython.returns(cython.Py_ssize_t)
    def get_nbytes(self):
   ^
------------------------------------------------------------

distributed/schedulerstate.py:471:4: Only final types can have final Python (def/cpdef) methods
```

**Comment by scoder** [comment]
Thanks, yes, that should be allowed. Can't test right now, but do you get the same error when you apply the decorators in reversed order?

**Comment by pitrou** [comment]
>  do you get the same error when you apply the decorators in reversed order?

Yes.

**Comment by scoder** [comment]
Note that I only enabled the case where `@cclass` is below `@final`, i.e. you first have to convert the Python class to a cclass, and then mark that as final.
