### ISSUE TITLE
set iteration not optimized

### ISSUE THREAD

**Issue by pitrou** [cython/cython#2048]
Set iteration could use `_PySet_NextEntry`, but instead it uses the generic iteration API (and instantiates an iterator object).

**Comment by pitrou** [comment]
There's already a similar optimization for dict iteration. Unfortunately, it uses a lot of AST-mongering that I do not feel competent to replicate (see `_transform_dict_iteration` in `Cython/Compiler/Optimize.py` and also `DictIterationNextNode` in `Cython/Compiler/Nodes.py`).

**Comment by scoder** [comment]
There is probably still some space for fine tuning, but the implementation is there now.
