### ISSUE TITLE
Make a knob to emit pure python code

### ISSUE THREAD

**Issue by KOLANICH** [cython/cython#2055]
It's a bit a strange issue, but sometimes the things are broken, the module is either simply not compiled, or it is compiled, but crashes the interpreter. In some cases I do not care about performance much, but I want the things just work. It's better to have a tool working slowly than non-working at all.

So it'd be nice to have a knob to make it generate just python code instead of compilation the c++ one.

**Comment by scoder** [comment]
Could you clarify? You want to generate Python code from a Cython .pyx code file, right?

Note that this can only work with code that does not use any actual C or C++ functionality, i.e. this would be a fairly limited feature.

It's also not clear to me what the concrete use case is. Do you consider this a pure debugging feature, or does it go beyond that? A more concrete motivation would help to understand this request better.

**Comment by KOLANICH** [comment]
Thank you, the main motivation was toolchain-related issues: there is a zoo of toolchains with own stdlibs, it's hard to make code built by all of them.

But a deeper look found that in the case I have encountered the problem was in the C++ code used by the developer, not the cython-generated one. Since there was no such an issue for all these years, I guess that this is not a problem and cython-generated code usually compiles well. I don't close this issue, because the idea may have another uses like debugging, but feel free to do this, if you find that another uses are not enough important.
