### ISSUE TITLE
Offering assisstance

### ISSUE THREAD

**Issue by arekbulski** [cython/cython#2074]
I am the current developer of Construct library. I took it over in 2016 and since then, the project has flourished to a point where its pretty much done and perfect. I am looking a for a new project to participate in or even take over if needed. 

I would ask that you point me to what I can do for the project. You can also consider giving me write access to repository.

**Comment by robertwb** [comment]
We'd welcome additional contributions. Please feel free to look over the issues, submit and review pull requests, answer questions on the mailing lists, etc. We do have "good first issue" and "help wanted" tags, though these certainly aren't applied to every applicable bug.
