### ISSUE TITLE
Implement @total_ordering for cdef classes

### ISSUE THREAD

**Issue by scoder** [cython/cython#2090]
We now support the normal Python comparison methods like `__eq__()` etc., but it would simplify their usage to auto-generate the obvious mappings when the `@functools.total_ordering` decorator is used. At the C level, this could probably be done without a performance penalty.

See https://docs.python.org/3/library/functools.html#functools.total_ordering

Since this only applies to cdef classes, it seems better to use a safe and dedicated separate decorator `@cython.total_ordering` than to rely on the generic Python decorator.

Approach:
- Support the new decorator as a new directive in `Options.py`, similar to `@no_gc_clear`.
- In `generate_richcmp_function()` (in `ModuleNode.py`), add default implementations of the missing comparison functions to the C switch statement if the directive is set.
- Add a new test file `tests/run/exttype_total_ordering.pyx`, implement different cdef class configurations in it, and test their comparisons with Python doctests. You can also implement normal Python classes in these doctests for direct comparison of Python's own behaviour.
- Run the tests with `python[2|3] runtests.py -vv --debug exttype_total_ordering`. The generated code can be found in the `TEST_TMP/run/c/` directory.

**Comment by jdemeyer** [comment]
> than to rely on the generic Python decorator

...which is implemented very stupidly anyway, so +1 to improving it in Cython.

If you do this, then I would drop the automatic adding of `__ne__` by default, but add it if `@cython.total_ordering` is given.

**Comment by jdemeyer** [comment]
Ah I see! The automatic `__ne__` seems to be new in Python 3. Python 2 doesn't do that.

**Comment by scoder** [comment]
> Python 2 doesn't do that.

Good to know, but I don't think it hurts anyone if we keep the Py3 behaviour, rather than implementing an explicit difference which pretty much no-one would notice, just for a legacy Python version.

**Comment by jdemeyer** [comment]
> Good to know, but I don't think it hurts anyone if we keep the Py3 behaviour, rather than implementing an explicit difference which pretty much no-one would notice, just for a legacy Python version.

Sure.

**Comment by holdenk** [comment]
Cool, I'd be happy to take this on as a starter issue if that would be cool with folks?

**Comment by scoder** [comment]
Sure! I updated the description with some pointers. Please ask back whenever something is unclear.

**Comment by TeamSpen210** [comment]
Why is it necessary to have a Cython-specific version of the decorator? Aside from tracebacks the behaviour would be identical. The only reason I can think of would be to maintain monkeypatching capabilities for the module, which would be rather fragile anyway (since you need to ensure import orders)... I could see in future optimisations being implemented for other decorators, and the `cython` namespace getting excessively cluttered.

**Comment by scoder** [comment]
I didn't say it's necessary, just that it's safer. It's simply easier to detect a Cython specific decorator than an otherwise imported one, but that's it.

In any case, here, the bulk of the work is to get the dispatch and the fallbacks right and to prove it via tests (which can partly also be copied from CPython). Renaming the decorator can still be done later.

**Comment by scoder** [comment]
Implemented in #3626. Documentation is missing. Should go here: https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#rich-comparison-operators
