### ISSUE TITLE
iscoroutine returns False for native coroutines in python 3.5+

### ISSUE THREAD

**Issue by ramonz** [cython/cython#2092]
Test code:

test_run.py
```python
from test import test

if __name__ == '__main__':
    test()
```

test.py
```python
# coding: utf-8
import asyncio
import inspect
import logging

logging.basicConfig(level=logging.DEBUG)


async def async_func():
    await asyncio.sleep(1)


def test():
    logging.info(f' inspect.iscoroutinefunction='
                 f'{inspect.iscoroutinefunction(async_func)}')

    logging.info(f' asyncio.coroutines.iscoroutinefunction='
                 f'{asyncio.coroutines.iscoroutinefunction(async_func)}')
```

run:
```
$ /usr/local/lib/python3.6.3/bin/python3 ./test_run.py
INFO:root: inspect.iscoroutinefunction=True
INFO:root: asyncio.coroutines.iscoroutinefunction=True
$ /usr/local/lib/python3.6.3/bin/cython -3 -X always_allow_keywords=True -D ./test.py
$ /usr/local/bin/gcc -shared -pthread -pipe -fPIC -fwrapv -Wall -fno-strict-aliasing -O2 -I/usr/local/lib/python3.6.3/include/python3.6m -o ./test.so ./test.c
$ /usr/local/lib/python3.6.3/bin/python3 ./test_run.py                                                                                                        
INFO:root: inspect.iscoroutinefunction=False
INFO:root: asyncio.coroutines.iscoroutinefunction=False
$ rm ./test.so 
$ /usr/local/lib/python3.6.3/bin/python3 ./test_run.py 
INFO:root: inspect.iscoroutinefunction=True
INFO:root: asyncio.coroutines.iscoroutinefunction=True
```

What I am doing wrong? Thanks

```
$ /usr/local/lib/python3.6.3/bin/cython --version                                                                                                             
Cython version 0.28a0
```

**Comment by scoder** [comment]
That's correct, yes. Cython compiled coroutines do not have byte code, and they are not Python generators. They implement the same protocol, but they are technically not the same thing (in the same way that a list iterator is not a dict iterator, even though both are iterators).

The `inspect` module should definitely return `False`. Whether the `asyncio` module should also return `False` is debatable. It could be argued that that's a bug in `asyncio`, but deciding that would require a deep look into the internals of `asyncio` to figure out the exact semantics that is intended there. Please reopen if you have reason to believe that Cython should do something about this, rather than fixing it in asyncio.

**Comment by danigosa** [comment]
I found a filthy workaround just in case anyone falls into desperation:

Following the `cyfunctions` above, `create_token` is NOT a coroutine, while `init_connection` is an `async` function, **this workaround works in both so it's ok if you can schedule the functions whether are coros or not**, no way to easily fix this with `asyncio.iscoroutinefunction` or at least easier than that:

```
In [59]: async def test():
    ...:     await create_token({})
    ...:
In [61]: asyncio.get_event_loop().run_until_complete(test())
TypeError: object str can't be used in 'await' expression

In [73]: async def test():
    ...:     return await init_connection()
Out[74]: <asyncpg.pool.Pool at 0x7f78e04752c8>
```

Here comes the magic:

```
In [69]: async def test():
    ...:     return await asyncio.coroutine(create_token)({})
In [70]: asyncio.get_event_loop().run_until_complete(test())
Out[70]: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1MjU1NTk0NTB9.v8wRZGIke6RYizIpJhl4oaypKyvuVARKaiq0KdpJg6XJ0qTB0o76BuTLera6kSQ_5qXnAb7_9DQSadwdRqgPmw'

In [71]: async def test():
    ...:     return await asyncio.coroutine(init_connection)()
In [72]: asyncio.get_event_loop().run_until_complete(test())
Out[72]: <asyncpg.pool.Pool at 0x7f78df48af48>
```

With that the workaround:

```python
def nasty_iscoroutinefunction(func):
      is_coro = asyncio. iscoroutinefunction(func)
      if func.__class__.__name__ == 'cython_function_or_method':
            # It's cythonized, danger!
            is_coro = True  # We'll make it possible
            func = asyncio.coroutine(func)
      return is_coro
```

This works!

**Comment by graingert** [comment]
`inspect.iscoroutinefunction()` uses `inspect._signature_is_functionlike` so that duck-type functions like Cython functions and AsyncMock can support it

this was backported to 3.10 and is released in 3.11b4

**Comment by graingert** [comment]
> @graingert looking at the implementation, it still requires us to set `f.__code__.co_flags` to have a certain value.
> 
> We've apparently been reluctant to do this because of the possibility that CPython might try to use the flags to process the code object [#2273 (comment)](https://github.com/cython/cython/issues/2273#issuecomment-414032693)

_Originally posted by @da-woods in https://github.com/cython/cython/issues/3849#issuecomment-1187595194_

**Comment by scoder** [comment]
Thanks @graingert.

Note that the fact that `unittest.mock.AyncMock` uses a fake code object and sets a flag on it does not mean that the same thing will work for us at the C level with a real code object using the `CO_COROUTINE` flag. However, this should at least work safely in CPython <= 3.10, probably up to 3.11, and from those versions on, the `inspect` change in https://github.com/python/cpython/pull/94050 would take over (from the PoV of a user) if we ever need to remove the flag again. So I'd deem it ok to generally enable the flag for coroutines in Cython 3.0. Until further notice. :)

**Comment by scoder** [comment]
Given that there was a lot more activity in ticket https://github.com/cython/cython/issues/2273, I'll reopen that one instead.
