### ISSUE TITLE
ValueError continuous memory view and 0-size numpy array

### ISSUE THREAD

**Issue by paugier** [cython/cython#2093]
A ValueError is raised if one gives a numpy array with shape `(2, 0, 1)` to such Cython functions with a 3d memoryview as argument:

```cython
cimport numpy as np
import numpy as np
np.import_array()

cpdef myfunc3d(np.float64_t[:, :, ::1] arr):
    if arr.size > 0:
        print(arr[0, 0, 0])
    else:
        print('size == 0')
```

The code to get the error:

```python
import numpy as np
arr = np.ones((2, 0, 1))
print(arr.flags)
myfunc3d(arr)
```
which gives:
```
C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-81a397764d36> in <module>()
      1 arr = np.ones((2, 0, 1))
      2 print(arr.flags)
----> 3 myfunc3d(arr)

_cython_magic_5dfab2d7f2a0e837d79c56566c9147b4.pyx in _cython_magic_5dfab2d7f2a0e837d79c56566c9147b4.myfunc3d()

ValueError: Buffer and memoryview are not contiguous in the same dimension.
In [ ]:
```
Strangely, no error is raised for a shape `(1, 0, 1)`!

**Comment by ashwinvis** [comment]
Strangely enough, by changing the function definition as shown below does not raise any error.

```python
from cython cimport view

def myfunc3d(np.float_t[:,:,::view.contiguous] arr):
```
Possible explanation from [Cython docs](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html?highlight=view#specifying-more-general-memory-layouts)

> The difference between the contiguous flag and the ::1 specifier is that the former specifies contiguity for only one dimension, whereas the latter specifies contiguity for all following (Fortran) or preceding (C) dimensions:

However this is not a solution, the issue still persists, IMHO.

**Comment by ashwinvis** [comment]
To add to the previous comment, although no error is raised the output `size == 0` is unexpected!
```python
>>> import numpy as np; arr = np.ascontiguousarray(np.ones((2, 0, 1))); print(arr.flags); myfunc3d(arr)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
size == 0

>>> arr.size

0
```

**Comment by c-f-h** [comment]
I ran into this too. Here's another minimal example to reproduce this:

```
cdef void foo(double[:, :, ::1] X):
    pass

import numpy as np
X = np.zeros((4,4,4))

# this works
foo(np.ascontiguousarray(X[:, 2:3, :]))

# this fails with 'ValueError: Buffer and memoryview are not contiguous in the
# same dimension.'
foo(np.ascontiguousarray(X[:, 2:2, :]))
```

The problem is that `__Pyx_ValidateAndInit_memviewslice` does not correctly realize that a 0-size array is **always** C-contiguous.

This crops up in the wild, too. A search for the error message reveals many instances where people inadvertently passed 0-size arrays to cython-implemented functions and got confusing error messages. E.g.: https://stackoverflow.com/questions/46470492/buffer-and-memoryview-are-not-contiguous-in-the-same-dimension-in-python

**Comment by c-f-h** [comment]
For reference, here is the corresponding check for contiguouity in numpy:

https://github.com/numpy/numpy/blob/3873ec46816f3fe0f705394242f83a764d4ce90e/numpy/core/src/multiarray/flagsobject.c#L123

Note that it is contingent on the NPY_RELAXED_STRIDES_CHECKING compile-time environment variable, however this seems to be always on by default.

The Cython function `__Pyx_ValidateAndInit_memviewslice` does not have the same check for 0-length dimensions.

**Comment by scoder** [comment]
Yes, that's a bug. It should behave like NumPy.
PR welcome. Tests can go into `tests/memoryview/memslice.pyx`, there are several contiguity tests already.
