### ISSUE TITLE
Enable profiling support via CLI.

### ISSUE THREAD

**Issue by ioctl0** [cython/cython#2100]
It would be really nice to turn profiling support on on the cython command line. I'd like to build unprofiled binaries for production, but quickly turn on profiling for development builds. Going through many cython files and editing them is sup-optimal.

**Comment by robertwb** [comment]
Profiling is a directive that can be set via the command line:
http://cython.readthedocs.io/en/latest/src/reference/compilation.html#how-to-set-directives

**Comment by ioctl0** [comment]
Ah, oops. The documentation of profiling doesn't make this clear IMO -- http://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html
