### ISSUE TITLE
Question about typing lowering performance

### ISSUE THREAD

**Issue by arekbulski** [cython/cython#2103]
This is a general question, so I dont mind general answers. Say I have a function that restrics its return type to dict, but the code calling this function doesnt care if its a dict or not. In other words, the typing is superfluous. Is it possible that this typing be LOWERING performance, or can typing only increases it? I would like to know if I should be adding type annotations carefully or whenever possible.

**Comment by robertwb** [comment]
Yes, you should add type annotations judiciously, where they actually help
performance and/or readability/robustness of the code. There are cases that
can hurt performance as well: assigning to a typed variable (including as a
function argument) incurs a type check that's wasteful if we can't take
advantage of knowing the type.

**Comment by arekbulski** [comment]
Understood.

Does this happen to include a situation where function return is typed, but the variable to which it gets assigned to is not typed? I would think that would be No.

**Comment by scoder** [comment]
Am 15. Februar 2018 05:35:39 MEZ schrieb Arkadiusz Bulski <notifications@github.com>:
>Understood.
>
>Does this happen to include a situation where function return is typed,
>but the variable to which it gets assigned to is not typed? I would
>think that would be No.

Cython has some type inference in place, so the variable might inherit the return type, depending on its further usage.

The most wasteful typing case is probably when a variable is typed (or inferred) as a C number but only (or mostly) used as a Python object. In that case, Cython has to create a new Python object on each use, which is costly.

Thus, what Robert wrote: typing is an optimisation. Use it when you can prove that you have to.

Stefan

**Comment by arekbulski** [comment]
The assignment in question is actually inserting output of a typed-return function as a value into a dictionary-derived container. I dont think inference could work in this case.

Would it be possible, or beneficial, to have a variable of io.BytesIO type? I can measure the speed gain/loss with a benchmark suite that I have, but how would I type it?

**Comment by arekbulski** [comment]
In this example `io` is BytesIO. Does this also cause the boxing penalty, when calling `io.read`?
```cython
cdef bytes read_bytes(io, int count):
    if not count >= 0: raise StreamError
    bytes data = io.read(count)
    if not len(data) == count: raise StreamError
    return data
```

**Comment by arekbulski** [comment]
Second, better example. Is `i` inferred to be a C integer? If not, would adding a type to it cause boxing when assigning `i` to dict value? `this` is an AttrDict, it maps attribute access to key access. I know for a fact that adding `cdef list obj` type causes speedup.
```cython
def parse_array_15(io, this):
    count = 3
    obj = ListContainer()
    for i in range(count):
        this._index = i
        obj.append(decompiled_16._parse(io, this, None))
    return obj
```

**Comment by TeamSpen210** [comment]
You can only use types that the Cython compiler knows about - mainly builtins, and a few particular modules such as `array `. For file objects, really all you can do is call their methods - there isn't any C API for them overall. Parts are actually written in Python anyway.

**Comment by arekbulski** [comment]
If using C integer when passing it to python functions causes "boxing", then how can I define a variable as "python integer" as opposed to "C integer"? From what I gather, "cdef int x" is C integer.

**Comment by scoder** [comment]
Note that, in general, a bug tracker is not a good place to provide support for user questions. Please switch over to the mailing list.
