### ISSUE TITLE
Documentation links to broken external project site

### ISSUE THREAD

**Issue by gnbl** [cython/cython#2111]
https://cython.readthedocs.io/en/latest/src/quickstart/install.html from https://github.com/cython/cython/blob/master/docs/src/quickstart/install.rst points to a pythonxy domain which now seems to host a spam site or has been hacked.
The 'official' site might be https://python-xy.github.io/ or https://github.com/python-xy but it seems rather inactive.

**Comment by scoder** [comment]
Thanks!
