### ISSUE TITLE
Documentation is wrong about where include statement is allowed

### ISSUE THREAD

**Issue by mhsmith** [cython/cython#2127]
[The documentation](http://cython.readthedocs.io/en/latest/src/userguide/language_basics.html) strongly implies that the include statement can be used anywhere:

> The contents of the included file should begin at an indentation level of zero, and will be treated as though they were indented to the level of the include statement that is including the file.

But this is not the case:

```
Error compiling Cython file:
------------------------------------------------------------
...
def f():
    include "test2.py"
   ^
------------------------------------------------------------

test.pyx:2:4: include statement not allowed here
```

Previous reports on mailing list: [here](http://cython-users.narkive.com/LwSHQgu5/include-statement-only-at-module-level-contrary-to-documentation) and [here](https://groups.google.com/forum/#!topic/cython-users/FWgvQB_zjFY).

Ideally this restriction would be removed, but until then, the documentation should be corrected.

**Comment by scoder** [comment]
"indented" does not imply "inside of a function". I've clarified the paragraph.
