### ISSUE TITLE
cython/pyext PythonObject scons builder output object suffix is .os

### ISSUE THREAD

**Issue by yanghao** [cython/cython#2139]
Hello,
I have a wired problem that PythonObject as defined in Tools/site_scons/site_tools/pyext.py in scons give a  suffix of "os", instead of "o". Is there any reason for this?

OS: Ubuntu 17.10
Python: 3.6.3
Cython: latest master branch

output log from scons build:
```
Running : ./tools/scons -Q config=configs/picorv32.py
['hello.c']
<BuilderWrapper 'PythonObject'>
['hello.os']
  CONFIG build/configs/picorv32/main/config/config.h
    HDLC build/configs/picorv32/main/picorv32.vvp
  CONFIG build/configs/picorv32/pyext/config/config.h
  CYTHON build/configs/picorv32/pyext/hardware/iverilog/hello.c
 **PYEXTCC build/configs/picorv32/pyext/hardware/iverilog/hello.os**
 PYEXTLK build/configs/picorv32/pyext/picorv32.so
```

Best Regards,
Yanghao

**Comment by yanghao** [comment]
Looks like this is due to scons problem. Raised pull request there: https://github.com/SCons/scons/pull/3105

**Comment by bdbaddog** [comment]
Unlikely this is a SCons issue, but rather an issue with how SCons is being used in the build system.
