### ISSUE TITLE
PEP 461 format of bytes string returns basestring (python 3.5.1+)

### ISSUE THREAD

**Issue by djvernon68** [cython/cython#2153]
Issue:
PEP 461 style bytes formatting (b'%b' % variable) returns basestring. So the following code results in a cythonize error:

```cython
cpdef bytes cy_foo():
    cdef:
        bytes bytes_1, bytes_2

    bytes_1 = b'bytes 1'
    bytes_2 = b'bytes 2'

    return b'%(bytes_1)b %(bytes_2)b' % {
                    b'bytes_1': bytes_1,
                    b'bytes_2': bytes_2} 
```

Result:
`Cannot convert 'basestring' object to bytes implicitly. This is not portable.`

This same basic code in python 3.5.1+ returns a bytes object.

**Comment by scoder** [comment]
Cython is not smart enough here to detect that the formatting is guaranteed to return a bytes object in this case because it only works in Py3 (and raises an exception in Py2 due to an unknown format conversion type 'b').

As a work-around, you can use a cast, i.e.
`return <bytes> (b'...' % {...})`
