### ISSUE TITLE
Segment fault when handling exception

### ISSUE THREAD

**Issue by nqbao** [cython/cython#2163]
When I run the following code, it will always raise a segment fault. Can you help me to explain what is wrong here?

**test.pyx**
```
cdef int test () except -1:
    return -1

cdef public void run ():
    try:
        print 'Try block'
        test ()
    except:
        print 'Catch block'
    finally:
        print 'Finally block'

    print 'Done'

def crash():
    run()
```

Then run it with

```
cythonize -i test.pyx
python -c "import test; test.crash()"
```

Result

```
Try block
Catch block
[1]    80115 segmentation fault  python -c "import test; test.crash()"
```

I am using Cython 0.28 and Anconda (2.7). But i have the same problem on Ubuntu as well

```
cython -V
Cython version 0.28
python -V
Python 2.7.13 :: Anaconda custom (x86_64)
```

**Comment by nqbao** [comment]
Interestingly, if i comment out the `except` block, i will get it runs without segment fault

```
cdef int test () except -1:
    return -1

cdef public void run ():
    try:
        print 'Try block'
        test ()
    #except:
    #    traceback.print_exc()
    #    print 'Catch block'
    finally:
        print 'Finally block'

    print 'Done'

def crash():
    run()
```

```
Try block
Finally block
Exception  in 'test.run' ignored
```

**Comment by scoder** [comment]
Please read the documentation on [exception handling](http://docs.cython.org/en/latest/src/userguide/language_basics.html#error-return-values), and use the mailing list instead of the bug tracker for support questions.

**Comment by nqbao** [comment]
Thanks, i will post it to the mailing list. I thought it could be a bug of Cython so I posted it here.
