### ISSUE TITLE
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

### ISSUE THREAD

**Issue by nooperpudd** [cython/cython#2176]
clang: warning: libstdc++ is deprecated; 
move to libc++ with a minimum deployment target of OS X 10.9

**Comment by scoder** [comment]
What did you do to see this warning?
I don't see where Cython would reference this library directly, so maybe there's something wrong with your local C++ compiler setup?

**Comment by nooperpudd** [comment]
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by nooperpudd** [comment]
https://github.com/websockets/utf-8-validate/commit/a87dd40953077ad02f7621e91c3c7d342276879e

**Comment by scoder** [comment]
Closing as it's not a problem in Cython. Probably needs to be fixed in distutils or setuptools.

**Comment by maliho0803** [comment]
did you solve this problem? if so, how did you do?
