### ISSUE TITLE
Autodoc doesn't work when uploading docs to Readthedocs.io

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [cython/cython#2180]
The changes I made worked fine on my computer, but it seems that readthedoc.io couldn't handle autodoc.

See at https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html, there is no list of arguments for `pyximport`.

Is it something that can be fixed with a PR? If yes, is there a config file to modify? If no, can a person with enough permissions take care of it? Thanks.

**Comment by jdemeyer** [comment]
You need to give some context, what are you trying to do? See also http://sscce.org/

**Comment by gabrieldemarmiesse** [comment]
My bad, I though scoder would take care of it, he's familiar with the issue since he merged the PR. I should explain myself in more details.

I made this PR: #2179 not so long ago. The goal was to display in the docs the arguments of `pyximport.install()`. For this I used `autodocs` to fetch the docstring from the function. It worked well on my computer when I was building the documentation. 
The PR was merged, the modifications were taken into account in the code, but the website cython.readthedocs.io doesn't display the formated docstring as expected. 

I don't know if I can fix it with another PR or if it has to be done by someone who have the rights on the configuration of the docs in readthedocs.io.

**Comment by gabrieldemarmiesse** [comment]
Ping. Does someone know if there is any way to fix this issue?

**Comment by gabrieldemarmiesse** [comment]
Here is what I see if I git clone Cython and that I run `make html`:
![from_git_clone](https://user-images.githubusercontent.com/12891691/40271879-4e2c242c-5ba4-11e8-8679-5270aedf81a2.png)

Here is what you can see at https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#arguments
.

![from_cython readthedocs io](https://user-images.githubusercontent.com/12891691/40271889-6a75b33c-5ba4-11e8-84b0-394dbb928281.png)

Does anyone has an idea of why this occurs? If not I'll make a PR and copy paste the docstrings in the `.rst` file until we find a solution.

**Comment by scoder** [comment]
@robertwb
Looks like there is a way to configure autodoc support in readthedocs:
https://read-the-docs.readthedocs.io/en/latest/faq.html#my-project-isn-t-building-with-autodoc

**Comment by gabrieldemarmiesse** [comment]
Allowing us to use autodoc would allow us to use it for `pyximport.install()`, `cythonize()` and the compiler options `Cython.Compiler.Options`.

**Comment by gabrieldemarmiesse** [comment]
Ping. 

It would allow me to write cool PRs for the docs.

**Comment by scoder** [comment]
Fixed in 0030408ac7219ea21352d9ab0b71cfcbab90de4c.
