### ISSUE TITLE
Uppercase "IF" treated as "if" statement

### ISSUE THREAD

**Issue by Baekalfen** [cython/cython#2191]
I wasn't able to find any documentation on this, so I assume this is a bug.

It is not possible assigning a value to a variable called "IF", as it gets treated like the keyword "if". This code will fail with a `Expected an identifier or literal` error on line 2:

    a = 1
    IF = 2
    b = 3

In the same way, this is valid code, as `IF` gets parsed as an if-statement:

    def hello():
        IF 1:
            print("Hello")

**Comment by scoder** [comment]
http://docs.cython.org/en/latest/src/reference/language_basics.html#conditional-compilation
