### ISSUE TITLE
Externally defined type no longer works after upgrading to 28.1

### ISSUE THREAD

**Issue by rpep** [cython/cython#2200]
Hi there,
We have in our finite-difference magnetics code [Fidimag](https://github.com/computationalmodelling/fidimag) a wrapper for the C time-integration library SUNDIALS. We've recently had a user contact us who wasn't able to install our software, and we've tracked it down to a change between versions 27 and 28 of Cython, but we've not been able to identify how to fix it after looking through the changelogs.

The short version is - SUNDIALS defines the typename 'realtype' which is just typedef'd to double. We previously had the following in the pxd file:

```
cdef extern from "sundials/sundials_types.h":
    ctypedef double realtype
```

and in the pyx files, we defined functions like:

```
cdef inline somefunction(np.ndarray[realtype, ndim=1, mode='c'] array):
    """
    Some code here
    """
```

Does anyone have any suggestions?

**Comment by rpep** [comment]
We've managed to fix the issue, but I'm still not sure whether this is a deliberate change in Cython or a bug. We've always done the naming convention:

'source.pyx' containing the code
'source.pxd' containing the information from header files and type declarations.

Without importing the pxd file within the pyx file, things just worked. I tried doing in the pyx file:
```
from source cimport *
```
But this did not work. What did work was renaming `source.pxd` to `sourcedecl.pxd` and then doing 
```
from sourcedecl import *
```

Is this an intentional feature or a bug?

Thanks,
Ryan

**Comment by scoder** [comment]
You didn't say what kind of problem/error you faced, but:

> 'source.pyx' containing the code
> 'source.pxd' containing the information from header files and type declarations.

That's not how it should be. A `.pxd` file with the same name (and path) as a `.pyx` file is meant to contain declarations *of the code* in the `.pyx` file, and they both share the same namespace. The `.pxd` file allows sharing declarations of the `.pyx` module for reuse in other modules. If you `cimport` anything from such a namespace, you create a dependency on the `.pyx` module, which is probably not what you want.

If you want to provide a namespace for external declarations, use a different file name.

**Comment by rpep** [comment]
Right, got it. I think we had a fundamental misunderstanding about what those files were for.

The error was just that 'realtype' wasn't defined in the pyx file, so that it stopped working isn't surprising if we had the wrong assumptions.

Thanks a lot for the quick response and tip!
