### ISSUE TITLE
Cython performance on calling external C function

### ISSUE THREAD

**Issue by nhannguyen95** [cython/cython#2202]
I recently read [this wiki post](https://github.com/cython/cython/wiki/tutorials-simplecdef), the author pointed out that calling external C function likely gives a bad running time:

```
## first version
..
## second version
..

## third version: call an external C function
cdef extern from "recip_square3.h":
    double recip_square3 (double i)

## calling this function with n = 100000 takes 1.44s on his machine,
## while other versions take 0.41s in average
def approx_pi3(int n):
    cdef int k
    cdef double val = 0.

    for k in range(1, n+1):
        val += recip_square3( k )

    return (6 * val)**0.5

## fourth version
..
## fifth version
..
```

He explained that the function **recip_square3** can't be inlined, and that "you have the C function call overhead".

However when I tested on my machine, it seems that this issue was resolved on the newer Cython versions (that I'm using), all pyx implementation versions gave equal time (0.5s on my machine). So I'm asking for a confirmation if this is true and if it is: from which Cython version this issue was resolved.

**His Cython version: 0.19.1
My Cython version: 0.26.1**

Thank you in advance.

**Comment by scoder** [comment]
No idea how this could qualify as a ticket. Please ask on the cython-users mailing list.
