### ISSUE TITLE
Add declaration for PyEval_InitThreads

### ISSUE THREAD

**Issue by lkollar** [cython/cython#2205]
As pointed out in the [Cython documentation][1] if a C callback function which manipulates Python objects is called from non-Python threads, the `PyEval_InitThreads` function has be called before the callback is invoked otherwise the interpreter will crash. As Cython does not have a declaration for this function users have to manually create one.

Would it make sense to add a declaration for this function to the existing declarations for CPython?

I am happy to submit a PR if this makes sense.

[1]: http://docs.cython.org/en/latest/src/userguide/external_C_code.html#acquiring-the-gil

**Comment by scoder** [comment]
Sure, anything that's missing should be added, but the easiest is probably to set the C macro `__PYX_FORCE_INIT_THREADS=1`.

**Comment by scoder** [comment]
That being said, a less hidden way would probably be nice, e.g. a new directive.

**Comment by Kamekameha** [comment]
It may worth noting, as mentioned in the posted [google-groups link](https://groups.google.com/d/msg/cython-users/AqyQDREh4uI/1F7yhWRgvtcJ) along with the [documentation link](http://docs.cython.org/en/latest/src/userguide/external_C_code.html#acquiring-the-gil), that just cimporting the `cython.parallel` Cython module should suffice to ensure that `PyEval_InitThreads` is called, doing so would add the [`InitThreads`](https://github.com/cython/cython/blob/93c7400a5027ee57ea710d6a0a26e3e339de5182/Cython/Utility/ModuleSetupCode.c#L826) utility code to the module initialization function, specifically, to `__Pyx_InitGlobals`.

Therefore, you don't exactly need to use anything from the `cython.parallel` module to initialize the GIL, and that's independent of whether `__PYX_FORCE_INIT_THREADS` is defined or not, unlike the case with using the `threading` library which only initializes the GIL when [creating a new thread](https://github.com/python/cpython/blob/71ca738f4cd2696d056d0cdb83bebd576f98ccc2/Modules/_threadmodule.c#L1064).
