### ISSUE TITLE
Division discrepancies between cython and python

### ISSUE THREAD

**Issue by hmaarrfk** [cython/cython#2212]
`test.py`
```
a = 3
b = 2
c = a/b
d = 3/2
e = 3//2
f = a//b
```

In python, `d->1.5` and is a `float`, but with the cythonized version of the file, `d->1` and is an `int` because it seems to simplify the result at the compilation stage.

Since this is pure python code, shouldn't it follow python conventions?

Thanks,

Mark

**Comment by robertwb** [comment]
Cython still follows Python 2 semantics (unless `from __future__ import division` appears at the top or the `language_level` [directive](http://cython.readthedocs.io/en/latest/src/reference/compilation.html#compiler-directives) is set to 3.

**Comment by hmaarrfk** [comment]
Thank you @robertwb 
That seemed to do the trick!!!
Python growing pains are real. Thanks for your help
