### ISSUE TITLE
Link down in FAQ: "Is Cython faster than CPython?"

### ISSUE THREAD

**Issue by sandan** [cython/cython#2213]
Trying to view https://sage.math.washington.edu:8091/hudson/view/bench/ gives: sage.math.washington.edu’s server IP address could not be found. When clicking on "See the latest results".

**Comment by gabrieldemarmiesse** [comment]
Thanks for reporting it. I couldn't find the pages. So I removed the links altogether.

**Comment by scoder** [comment]
Yes, the benchmark runner does not exist any more.
