### ISSUE TITLE
documentation: Using C++ in Cython 

### ISSUE THREAD

**Issue by mgbukov** [cython/cython#2214]
Hi,

in the Documentation, on the [page for wrapping up C++](http://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html), in the header file

```
namespace shapes {
    class Rectangle {
    public:
        int x0, y0, x1, y1;
        Rectangle();
        Rectangle(int x0, int y0, int x1, int y1);
        ~Rectangle();
        int getArea();
        void getSize(int* width, int* height);
        void move(int dx, int dy);
    };
}
```
it would be helpful to add to the constructor `Rectangle();` the empty scope, i.e. write `Rectangle() {};`. Probably the same goes for the destructor.

This is not required to run the specific example showed online, but becomes **essential when writing a template class**. In the case of a template class, using `Rectangle();` cython is able to compile the library but it raises the following error when the class is imported in python:

```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from env_object import Pyobject
ImportError: dlopen(/Users/mbukov/Dropbox/RL_exp/quantum_RL/Q_struct_int_index/env_source/cpp_interface_example/env_object.cpython-36m-darwin.so, 2): Symbol not found: __ZN18environment_objectIiEC1Ev
  Referenced from: /Users/mbukov/Dropbox/RL_exp/quantum_RL/Q_struct_int_index/env_source/cpp_interface_example/env_object.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/mbukov/Dropbox/RL_exp/quantum_RL/Q_struct_int_index/env_source/cpp_interface_example/env_object.cpython-36m-darwin.so
```

On the other hand, using ``Rectangle() {};` works fine.

**Comment by robertwb** [comment]
When making this a template class, the entire contents of the .cpp file must be put into the .h file, including the definition (vs. just the declaration) of the constructor and the destructor. But this isn't generally the recommended thing to do for non-template classes, which can consist of declarations only.
