### ISSUE TITLE
add compile option to hide binary size warnings

### ISSUE THREAD

**Issue by rgommers** [cython/cython#2221]
Hi, I propose to add an option (by default not enabled) to hide the binary size warnings that are in general useful but can easily give false alarms. Examples:

- https://github.com/numpy/numpy/pull/432
- https://github.com/numpy/numpy/pull/5343
- https://morepypy.blogspot.ca/2018/04/how-to-ignore-annoying-cython-warnings.html

The second link is an example of NumPy devs considering not merging a clear improvement because of this warning, and the third one of PyPy devs publishing a complete package just to install a warning filter to work around the false alarm. 

When package authors know that it's going to be a user-visible false alarm (and it's quite an alarming/confusing one for users), then giving them an option to do a release with the check disabled seems quite valuable.

**Comment by rgommers** [comment]
Also for reference some history: http://thread.gmane.org/gmane.comp.python.cython.devel/14352/focus=14354. Cc'ing @njsmith

**Comment by robertwb** [comment]
These warnings are definitely quite valuable, but we decided it makes sense
to hide them, or at least warn at a lower level, if the size goes up for
extern classes taht don't have a base class.

**Comment by robertwb** [comment]
Looks like we're already downgrading from a hard error to a warning in this case. 

To clarify, the ask is for a compiler option that can be passed to packages to suppress this warning? Given that each package would have to know to compile in this way, is that better than having the package suppress this warning with the usual mechanisms?

**Comment by rgommers** [comment]
> To clarify, the ask is for a compiler option that can be passed to packages to suppress this warning? 

Indeed

>  is that better than having the package suppress this warning with the usual mechanisms?

There are some advantages:
- a warning filter needs to be specific, so we need a number of them. e.g. in numpy we had filters for `dtype` and `ufunc` but not `ndarray`. So in my second example it then required yet another filter.
- filters are global and can be reset. To make test suites reproducible it makes sense to start with `warnings.resetwarnings()` and then add your own filters (this is what numpy's test runner does, which many projects use).
- The Python warnings mechanism has issues (up to Python 3.6 IIRC) with filters that were reset and then re-added, those didn't work.

In general, I'd just much prefer to have a single silence flag that can be passed to Cython, because this issue keeps popping up and wastes a lot of time. And I've personally never encountered a single case where it was useful, so I'd rather investigate the first time that does happen rather than every time it's a false alarm.

**Comment by rgommers** [comment]
> These warnings are definitely quite valuable, but we decided it makes sense to hide them, or at least warn at a lower level, if the size goes up for extern classes that don't have a base class.

Simply hiding instead of warning would be even better than a compiler option.

**Comment by amueller** [comment]
Is there any news on this? And when is this warning helpful? We're getting it at random places in scikit-learn and it's throwing off our warning filters.

**Comment by mattip** [comment]
Maybe the warning should be `dtype python object size is 96 bytes but PyArray_Descr is 88 bytes`. The complaint is that the C struct size `PyArray_Descr` in the headers is smaller than the actual allocated object by `PyArrayDescr_New`, indicating that headers used when the cython extension modules were compiled are out of date wrt the actual module, and that fields have been added.

It seems there is no way to tell cython "this library is careful to be backward compatible, any fields added are never needed by cython code". Perhaps that could be an attribute of `PyExtensionType`, and something that could added to the `ctypedef class numpy.dtype [object PyArray_Descr]` line?

**Comment by robertwb** [comment]
I like the idea of adding it to the ctypedef class declaration.

**Comment by mattip** [comment]
Where would one start to add a `no_size_warn` attribute to `PyExtensionType`? It is not clear how the [`ctypedef class` definition](http://docs.cython.org/en/latest/src/userguide/extension_types.html#external-extension-types) gets mapped to the attributes that appear in [`PyExtensionType`](https://github.com/cython/cython/blob/master/Cython/Compiler/PyrexTypes.py#L1328) .

**Comment by robertwb** [comment]
We could augment the annotation to be somethign like

`[object object_struct_name, type type_object_name, check_size=False ]`

Perhaps alternatively we could make this a min_size option, which
would allow the class to grow, but also make it possible to detect if
you're using a really old version that might be missing fields you
need expect, and of course setting this to 0 would disable any
checking whatsoever. (I wonder if we could automatically infer minsize
by looking at offset(...) for every field we access. There's still the
contract that the class grow in a backwards compatible way of course.)

**Comment by scoder** [comment]
What about `check_size=min` to generate a `>=` check?

**Comment by rgommers** [comment]
gh-2622 wasn't meant to close this, can this issue be reopened?

@mattip, @robertwb @scoder thanks for working on this!

**Comment by mattip** [comment]
Closed by #2627
