### ISSUE TITLE
Dead Link (URL) in EmbeddingCython

### ISSUE THREAD

**Issue by praisethemoon** [cython/cython#2223]
Good day,

The wiki page EmbeddingCython [https://github.com/cython/cython/wiki/EmbeddingCython](https://github.com/cython/cython/wiki/EmbeddingCython) refers to a dead link [http://thread.gmane.org/gmane.comp.python.cython.devel/669](http://thread.gmane.org/gmane.comp.python.cython.devel/669). 

Best regards.

**Comment by gabrieldemarmiesse** [comment]
Thank you for reporting it. The dead links were removed.
