### ISSUE TITLE
language_level not respected in include'ed Cython modules

### ISSUE THREAD

**Issue by UncleSam314** [cython/cython#2229]
Cython [documentation](https://github.com/cython/cython/blob/0.27.x/docs/src/reference/compilation.rst#compiler-directives) says:

language_level (2/3)
Globally set the Python language level to be used for module compilation. Default is compatibility with Python 2. To enable Python 3 source code semantics, set this to 3 at the start of a module or pass the "-3" command line option to the compiler. Note that cimported and included source files inherit this setting from the module being compiled, unless they explicitly set their own language level.

However, if we include cython module(s) in another one then compiler directives in the include'ed module(s) are ignored. In the following example, include'ing hello_dep.pyx causes language_level=2 directive in hello_dep.pyx to be ignored.

```
**hello.pyx**

#cython: language_level=3
include "hello_dep.pyx"

**hello_dep.pyx**

#cython: language_level=2
print "abc"

$ cythonize hello.pyx -b -i
Error compiling Cython file:
------------------------------------------------------------
...
#cython: language_level=2

print "abc"     ^
------------------------------------------------------------
hello_dep.pyx:3:6: Syntax error in simple statement list

```

**Comment by scoder** [comment]
I updated the documentation. Too-level directives in (literally) included files are never looked at, they are just arbitrary comments.
