### ISSUE TITLE
Optimize 'for _ in range(my_c_integer):' 

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [cython/cython#2231]
Hello,
This type of loop:
```python
cdef int i
cdef int a = 100
for i  in range(a):
    #do something
```
Is optimised into a C loop. But this type of loop:
```python
cdef int a = 100
for _ in range(a) :
    #do something 
```
Isn't optimised. 

Maybe it could be considered as a future feature of Cython?

**Comment by scoder** [comment]
Cython does not currently track assigned values, i.e. it does not consider that `a` has the known value `100` here. Thus, it assumes that the loop variable might overflow when converted to a C integer loop, and refuses to do it. Explicitly typing the loop variable opts out of the safety here and triggers the optimisation.

It seems easy to look up the assigned value here, but I doubt that it has any advantage in practice. If you intend the loop to run from 0 to 99, why not just write `for i in range(100)` ?

**Comment by gabrieldemarmiesse** [comment]
Thanks, it's a lot more clear now.
