### ISSUE TITLE
Cannot use Collections Abstract Base Classes in .pxd files

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [cython/cython#2232]
Summary: attempting to change [this line](https://github.com/grpc/grpc/blob/7df24412237760f9dbae6b1bd7b8f89c95c9c913/src/python/grpcio/grpc/_cython/_cygrpc/channel.pxd.pxi#L20) from `cdef list references` to `cdef collections.MutableSequence references` isn't going well - neither `import`ing nor `cimport`ing the standard library's `collections` module is working, and I also see `'MutableSequence' is not a type identifier`. ([Of course it is.](https://docs.python.org/2/library/collections.html#collections-abstract-base-classes))

Being able to specify fields according to their types rather than their implementing classes is a nice-to-have rather than something that's required for my immediate work, but it's a good practice. See "Effective Java", Second Edition, Item 52: "Refer to objects by their interfaces" if you're not already familiar with it.

**Comment by robertwb** [comment]
Cython has no notion of interface (though it'd be nice to add one). 

The reason typing a member as `list` is supported is to take advantage of the implementation of `list` for optimized index access, etc. If you want/need to accept a general MutableSequence (or similar) then type it as object and use Python's duck typing. (I could see the motivation for allowing this just to get the documentation and/or type checking on assignment, but removing the error for non-cimported types would be a regression for when one wants to rely on the concrete implementation.)
