### ISSUE TITLE
Accessing typedefs in C++ template classes

### ISSUE THREAD

**Issue by videlec** [cython/cython#2233]
It seems not possible to typedef instantiated template like
```
ctypedef MyCppClass[T] MyCppClass_T
```
For example cythonizing
```
# distutils: language=c++

cdef extern from "header.h":
    cdef cppclass A[T]:
        ctypedef T Element

ctypedef A[int] Aint
cdef Aint.Element a = 3
```
I obtain
```
Error compiling Cython file:
------------------------------------------------------------
...
        ctypedef T Element

ctypedef A[int] Aint


cdef Aint.Element a = 3
    ^
------------------------------------------------------------
test.pyx:10:5: 'Aint' is not a cimported module
```

**Comment by Nic30** [comment]
+1

**Comment by eyjohn** [comment]
Getting the same behaviour iterating over std containers:

```cython
ctypedef unordered_map[string, string] Dictionary
cdef const Dictionary* ndict
cdef Dictionary.const_iterator ndict_it
```

With the error:
```
simplehttp/util.pxi:40:9: 'Dictionary' is not a cimported module
```
(the middle line works fine though)

A workaround seems to be to explicitly redeclare the type fully:
```cython
ctypedef unordered_map[string, string] Dictionary
cdef const Dictionary* ndict
cdef unordered_map[string, string].const_iterator ndict_it
```

**Comment by VadimPushtaev** [comment]
+1

```
ctypedef unordered_map[string, vector[string]] string_to_strings
cdef string_to_strings.iterator it = self._m.begin()
```

**Comment by da-woods** [comment]
The argument against it is that this wouldn't be valid C++ code. If you did 

```
std::vector<int> x();
x::iterator it = x.begin();
```

You get `error: ‘x’ is not a class, namespace, or enumeration`

That doesn't _necessarily_ mean we shouldn't do it in Cython, but it makes it a bit non-obvious what C++ code to generate, especially when pointers/references/const is involved.

**Comment by VadimPushtaev** [comment]
@da-woods, this is not what I'm trying to do. `string_to_strings` is not a variable name, this is a type name.

The c++ code would be:


```
#include <unordered_map>

typedef std::unordered_map<int, int> string_to_strings;

int main() {
    string_to_strings::iterator it;
}
```

**Comment by da-woods** [comment]
Sorry you're quite right - what you're trying to do should work ideally. I'll delete my earlier comment since it's just wrong

**Comment by VadimPushtaev** [comment]
Not really sure whether this is a proper way, but looks like it can be fixed pretty easily: https://github.com/cython/cython/pull/4039
