### ISSUE TITLE
Change call signature of CyFunction to FASTCALL signature

### ISSUE THREAD

**Issue by scoder** [cython/cython#2263]
The new FASTCALL calling convention in CPython 3.6 and later avoids creating argument tuples and passes them as `PyObject*` C array instead. Keyword arguments can also be passed as a key-value C array.

It is described here:
https://mail.python.org/pipermail/python-dev/2016-August/145793.html

For Python function signatures that do not require tuple/dict arguments (i.e. that do not use `*args` or `**kwargs`), Cython should
- switch the call signature of its `CyFunction` function type to the FASTCALL signature
- provide a converter that unpacks the argument tuple (and keywords) from the normal `tp_call` slot (can be done in the def-wrapper function)
- use FASTCALL internally when calling a `CyFunction`, thus avoiding the argument packing
- export the FASTCALL signature directly in CPython 3.8+ (where [PEP 575](https://www.python.org/dev/peps/pep-0575/) will hopefully get accepted)

**Comment by jdemeyer** [comment]
Working on this...

**Comment by jdemeyer** [comment]
I'm wondering what to do with Python versions that *do* support `METH_FASTCALL` but not vectorcall (PEP 590), in particular Python 3.7. There are basically 3 options:
A. Use `METH_FASTCALL` anyway even if vectorcall is not supported. This may lead to a regression when keyword arguments are passed.
B. Enable `METH_FASTCALL` only for Python 3.8. This is essentially reverting #3021 for Python 3.7.
C. On 3.7, use `METH_FASTCALL` for PyCFunction but not for CyFunction. This is the best solution for performance, but will make the `METH_FASTCALL` handling code even messier than it already is.
