### ISSUE TITLE
Converting Python code with openCV module to C using Cython(issue with import CV2)

### ISSUE THREAD

**Issue by swatinair123** [cython/cython#2272]
Hi i am facing issues When i import cv2 in my python code and convert the python code to C using Cython and then using the .c and .h file in Visual studio and using it in the main.cpp .It says no module named cv2 occurs when i execute the Main.cpp . I am able to create the openCVTestcode.c and openCVTestcode.h file and i have added to the Visual studio project and calling it from main.cpp. it works fine while importing numpy and it prints the result also. The issue is when i use openCv and Tensorflow. i get no module named cv2 error. Should we add openCV path or so in Visual studio project? But this was not needed for Numpy.

When i use cimport cv2 instead of import cv2 in openCVTestcode.pyx it says cimported module has no attribute 'imread'. Please help in this regard i have a openCVTestcode.pyx file and i am compiling using python -m cython openCVTestcode.pyx. From this i get the .c and .h files which i am adding to a visual studio project and calling the function in the .h files from the main.cpp
Code for Main.cpp
int main(void) {
Py_Initialize();  //Needed!
PyInit_openCVTestcode();     //Needed! called PyInit_hello() for Python3
openCVtest();
Py_Finalize();    //Needed!
return 0;
}

Below is openCVTestcode.pyx

import cv2
cdef public void openCVtest():
    image = cv2.imread("Test.png")
    cv2.imshow("test",image)
    cv2.waitKey(0)

**Comment by robertwb** [comment]
Discussion happening at cython-users@googlegroups.com.
