### ISSUE TITLE
Expose contextvars CPython implementation

### ISSUE THREAD

**Issue by pfreixes** [cython/cython#2281]
Hi,

I'm planning on use contextvars [1] within a Cython code and I would like to have access to the CPython implementation instead of accessing through the generic Python module.

Does it make sense?

In such case, I could try to work on a PR that would define the methods as a new include file behind the generic `Include/cpython` directory. 

[1] https://docs.python.org/dev/library/contextvars.html#module-contextvars

**Comment by scoder** [comment]
Yes, I think covering the C-API in a .pxd file would be a good first step. Eventually, Cython should learn how to use context variables internally and make them available as efficient context managers.

**Comment by scoder** [comment]
I added convenience getter functions in ff16389c0da5acc2be1b49fd074b0919cb252b88.
