### ISSUE TITLE
Type `long` maps to different numpy types in windows and linux

### ISSUE THREAD

**Issue by david-cortes** [cython/cython#2283]
When creating cython extensions in windows platforms, if I build a function taking as input a numpy array with type integer, the same `numpy.int32` and `numpy.int64` map to different C types in windows and linux. Particularly, in windows, the C type `long` matches to `numpy.int32`, whereas in linux it matches to `numpy.int64` - e.g. this function:
```
def fc(np.ndarray[long, ndim=2] a):
    return None
```

Would only accept an array with type `np.int32` in windows, and would only accept an array with type `np.int64` in linux (both 64-bit OSes). The type `double`, however, matches to `np.float64` under both.

I'm not sure if this is related to the numpy build (I'm using the builds from clean anaconda installations), but it would be nice if it could match to the same types in different OSes, so as to make code more easily compatible across platforms.

The bug happens with Python 3.6.

**Comment by robertwb** [comment]
This is because long has a different size on these platforms. You can comport np.npy_int64 and friends to use a fixed size.
