### ISSUE TITLE
integer division

### ISSUE THREAD

**Issue by GliderGeek** [cython/cython#2300]
Not sure if this is a bug, but i didn't find a good description yet. So for documentation purposes i'm posting this here.

## Description
In python2 an integer division yields an integer, in python3 this is changed and the division return a float.  
When compiling python3 code, the binary yields an integer as a result, instead of the expected float. This thus results in a difference between the 'normal' code and the compiled code, leading to strange results.

## Minimal example
example.pyx
```python
>>> 1/2
0.5
```
example.so
```python
>>> 1/2
0
```

## Actions
I don't know if there is already a method for dealing with this issue? (maybe compile flags in `setup.py`, 
to indicate the use of python3)

**Comment by gabrieldemarmiesse** [comment]
Please see #2299 . Thanks!

**Comment by gabrieldemarmiesse** [comment]
Can you please close this issue? Thank you

**Comment by GliderGeek** [comment]
Thanks for the quick reply.

**Comment by gabrieldemarmiesse** [comment]
You're welcome, thanks for reporting this unexpected behavior.
