### ISSUE TITLE
app works perfectly with just python but when one compiles it with cython it doesn't work and gives recursionerrors.

### ISSUE THREAD

**Issue by hippylover** [cython/cython#2303]
Latest version of cython. My app works fine when i run it with python but when i make it into a module and import the module from a simple launcher script suddenly it doesn't seem to see any data from the internet and it also gives me these: RecursionError: maximum recursion depth exceeded while calling a Python object.

Nuitka has the same problem but doesn't give me these recursionerrors. It's a proprietary app and i don't want to give away the sourcecode but if you have any ideas they will be greatly appreciated.

I have no idea if it's relevant but when compiling the program(making object code) with gcc i also get this error/warning/note(the only one):

`prog.c: In function ‘__pyx_pf_4prog_13Ui_MainWindow_setupUi.isra.75’:
prog.c:41229:18: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
 static PyObject *__pyx_pf_4prog_13Ui_MainWindow_setupUi(CYTHON_UNUSED PyObject *__pyx_self, PyObject *__pyx_v_self, PyObject *__pyx_v_MainWindow) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

Also not sure if relevant but i have a bunch of classes(threads) that calls the next class when one is finished making a loop. Maybe this is a nono even if it works fine in python?

I'm using pyside2, requests, delorean and humanize.

**Comment by hippylover** [comment]
Any ideas?

**Comment by hippylover** [comment]
Just tried it with pyqt5 now. It works perfectly. Perhaps this is a pyside2 bug. If you have the chance and will to help those guys out(it's opensource too!) then i suppose we can put this behind us.

**Comment by robertwb** [comment]
My guess is that you were already very close to the recursion limit, and minor implementation detail differences put you over (or not). You can play with [getrecursionlimit](https://docs.python.org/3/library/sys.html#sys.getrecursionlimit) to test/work around this.

**Comment by hippylover** [comment]
That is not the bug. This is either a bug in pyside2 or cython depending on how you look at it. I and others have tested the exact same code in both pyside2 and pyqt5 and only pyside2 exhibits the bug.
