### ISSUE TITLE
Cython 0.28.2 Coroutines return None for coro.cr_frame

### ISSUE THREAD

**Issue by fried** [cython/cython#2306]
This causes the asyncio/coroutines.py: _format_coroutine(coro) to throw an exception when it tries to access the co_filename from coro.cr_frame.  

AttributeError: 'NoneType' object has no attribute 'co_filename'

Now any code that tries to repr a task that contains a Cython Coroutine throws very unexpected exceptions.

**Comment by fried** [comment]
Looking at the change log it looks like this was a feature.

**Comment by fried** [comment]
bpo-33672 looks like they are fixing this in cpython

**Comment by 1st1** [comment]
Ideally we should fix this in Cython too: `__code__` attribute shouldn't ever point to `None`, it should be either set or not.

**Comment by scoder** [comment]
I created a PR in #2806. Comments and testing (and especially test extensions) welcome.
