### ISSUE TITLE
How to `pip install -e`? 

### ISSUE THREAD

**Issue by fduxiao** [cython/cython#2307]
I use cython just to accelerate my code(all written in pure python), so I don't want them to be built when installing them to my developing environment (with `pip install -e`) since it will be inconvenient to debug.  Also the `cythonization` process inside setup.py should not be run. (Compiled version in my situation is tested with CI, so there is no concerns about that.)

How should I specify options for not compiling to C and not building?

**Comment by robertwb** [comment]
Sounds like a question for the users lists, not a bug.
