### ISSUE TITLE
cimport from a raw directory (to emulate the namespace package functionality in CPython 3.3+)

### ISSUE THREAD

**Issue by newt0311** [cython/cython#2310]
Hello,

I'd like to use namespace package like functionality when using cimport. I think most of the pieces are there already. It seems like just changing "check_package_dir" in Utils.py to not check for __init__ files would be sufficient?

Also I noticed that the pyx search (find_pyx_file in Main.py) doesn't keep the sys_path argument. Is there a reason for that?

I wasn't sure what the impact of these changes would be so I wanted your thoughts before submitting a PR.

Thanks.
-- PG

**Comment by robertwb** [comment]
I think we need the `__init__` files to discover the package root and resolve absolute to relative imports. We also don't want to diverge from Python here. Sounds like a good topic for the dev list.
