### ISSUE TITLE
__cinit__ clarification

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#2311]
Context: trying to make `_BaseOffset` [here](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/offsets.pyx#L296) into a `cdef class`, troubleshooting pickle errors of the form:

```
TypeError: object.__new__(YearBegin) is not safe, use pandas._libs.tslibs.offsets._BaseOffset.__new__()
```
 
The [docs](https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html) say that `__cinit__` is a synonym for `__new__`:

```
Older Cython files may use __new__() rather than __cinit__(). The two are synonyms. 
```

But as far as I can tell the actual signature (and name) is more like that of `__init__`.  Am I missing something, or are these contradictory?

**Comment by robertwb** [comment]
Cython used to have a `__new__` which was renamed to `__cinit__` because Python introduced it's own `__new__` (with, as you point out, a different meaning and signature).
