### ISSUE TITLE
Please provide Python 3.7 wheels

### ISSUE THREAD

**Issue by hroncok** [cython/cython#2416]
Please, provide wheels for Python 3.70rc1 on PyPI. This would allow consumers of Cython to test their code faster with 3.7. Thank you.

**Comment by gabrieldemarmiesse** [comment]
Hello! I know it's suboptimal, but the documentation mentions:

>For one-time builds, e.g. for CI/testing, on platforms that are not covered by one of the wheel packages provided on PyPI, it is substantially faster than a full source build to install an uncompiled (slower) version of Cython with

>pip install Cython --install-option="--no-cython-compile"

Maybe that would help you wait until Cython has wheels for Python 3.7.

**Comment by hroncok** [comment]
Thanks. I'm aware of that one, but is it sometimes hard to propagate this option down (to tox, etc.).

**Comment by gabrieldemarmiesse** [comment]
I understand, it's not something I can solve then since I'm not one of the maintainers. I Hope your issue is going to be solved soon.

**Comment by scoder** [comment]
Built and uploaded Linux wheels.
