### ISSUE TITLE
Please clarify in documentation, that the resulting C-string is null terminated

### ISSUE THREAD

**Issue by realead** [cython/cython#2421]
The documentation states (http://cython.readthedocs.io/en/latest/src/tutorial/strings.html#passing-byte-strings) that to cast a python bytes/bytearray-object one has simple to use:

`cdef char* other_c_string = py_string`

What is not directly obvious, whether this resulting C-string is null-terminated.

Please consider to clarify in documentation, that the resulting C-string is `\0` terminated.

Python-3 documenation states it explicitly here https://docs.python.org/3/c-api/bytes.html#c.PyBytes_AsString and here https://docs.python.org/3/c-api/bytearray.html#c.PyByteArray_AsString 

Python-2 documentation lacks this assurance, but judging from the code e.g. https://github.com/python/cpython/blob/2.7/Objects/bytearrayobject.c#L288 this is also the case.

**Comment by gabrieldemarmiesse** [comment]
Thanks for the feedback!
