### ISSUE TITLE
cython-tool might produce an error for cython.pyx, the same way cythonize does

### ISSUE THREAD

**Issue by realead** [cython/cython#2422]
When building a file called `cython.pyx` via 

`cythonize cython.pyx` 

I get an error message saying: "ValueError: cython is a special module, cannot be used as a module name" which is a Good Thing.

However, using `cython cython.pyx`  doesn't produce any errors but a cython.c file - one which at least at Linux cannot be compiled.

Given that `cython` - tool is advertized in documentation (http://cython.readthedocs.io/en/latest/src/reference/compilation.html#compiling-from-the-command-line) and that it is not unusual for somebody new to Cython to call her/his pyx-file "cython.pyx", please consider to produce the same error message also with `cython`-tool.

**Comment by scoder** [comment]
PR welcome
