### ISSUE TITLE
ValueError with numpy 1.16

### ISSUE THREAD

**Issue by skoudoro** [cython/cython#2444]
Hi, 

Our PRE release bots, which using Numpy 1.16,  failed many times with this error: 
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`  (see https://github.com/nipy/dipy/issues/1579)

Here a small example to reproduce our problem: 

`simple_mp.pyx` file:
````
import numpy as np
import cython

def masking_test():
	simple_wm = np.array([[0, 0, 0, 0, 0, 0],
                          [0, 0, 1, 0, 0, 0],
                          [0, 1, 1, 1, 0, 0],
                          [0, 1, 1, 1, 0, 0],
                          [0, 0, 0, 0, 0, 0]])
	mask = np.zeros(simple_wm.shape)

	simple_wm[mask==0] = 1
````
Test in a Python terminal after compiling: 
````
>>> import simple_mp as m
>>> m.masking_test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "simple_mp.pyx", line 13, in simple_mp.masking_test
    simple_wm[mask==0] = 1
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
````

Python 3.6
cython 0.29a0
numpy 1.16.0.dev0+2804c03

How can I resolve this problem? Thanks

**Comment by gabrieldemarmiesse** [comment]
Your problem comes from numpy and is unrelated to cython. Please see https://stackoverflow.com/questions/10062954/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous

**Comment by skoudoro** [comment]
Thanks for your answer @gabrieldemarmiesse.

> Your problem comes from Numpy and is unrelated to Cython

I think it is... This short example should have the same behavior in a `*.py` or `*.pyx` file which is not the case. This Error only appears when cython compiled this code, it works correctly otherwise.

**Comment by gabrieldemarmiesse** [comment]
My apologies. You are totally right. I managed to reproduce the error with python 3.6, cython master and numpy 1.14.5. I'm going to investigate and see if an earlier version of cython or numpy does the trick.

**Comment by gabrieldemarmiesse** [comment]
If we unpack the line, we see that this assignment fails:

```python
boolean_mask = mask == 0
```

From the generated code, it seems that Cython assumes that when comparing a python object for equality to an integer, the result must be a boolean.

```
__pyx_t_9 = __Pyx_PyInt_BoolEqObjC(__pyx_v_mask, __pyx_int_0, 0, 0); if (unlikely(__pyx_t_9 == ((int)-1))) __PYX_ERR(0, 11, __pyx_L1_error)
  __pyx_t_1 = __Pyx_PyBool_FromLong(__pyx_t_9); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 11, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_v_boolean_mask = __pyx_t_1;
  __pyx_t_1 = 0;
```

**Comment by gabrieldemarmiesse** [comment]
On my side it worked with Cython 0.28.3 and numpy 1.14.5. I would assume that there is a commit after the release of Cython 0.28.3 which broke something.

Can you try with Cython 0.28.3 and tell me if it works for you?

**Comment by skoudoro** [comment]
Yes, it works with Cython 0.28.3

**Comment by gabrieldemarmiesse** [comment]
After some search, I managed to narrow down the commit which was breaking it (I just discovered git bisect and it is awesome).

d556575c6ca2ce45d4d38d0db299459b7482e8d2 is the first bad commit
commit d556575c6ca2ce45d4d38d0db299459b7482e8d2
Author: Stefan Behnel <stefan_ml@behnel.de>
Date:   Thu Mar 29 19:24:52 2018 +0200

    The optimised int/float comparison was accidentally not activated when the result of a comparison was already known to be of type bint (instead of a Python object), nor for the "!=" operator.
    These seem to be fairly common cases.

:040000 040000 a4b2f009fe2810e87f7153de74ce9818485f79e3 d2b709db6284a2744f69ea3c02ae5538c249b182 M      Cython
:040000 040000 2825c405aba1641560c4f652cd9f78b483d0986e dc7fc43cd24887e9a04494d5c25842b31f4994ec M      tests

**Comment by skoudoro** [comment]
Wow ! this is an old commit, I am surprised that it appears only now in our bots... Maybe it was hidden because of others errors in our project.

Anyway, Thank you for looking at that! (I never used git bisect, I will look at it now...)

**Comment by gabrieldemarmiesse** [comment]
You're welcome!

**Comment by scoder** [comment]
It used to be in a pull request that was only recently merged, that's why it's failing now. Thanks for the investigations, and for the early report.
