### ISSUE TITLE
Error while cythonizing print("string",end="") type of statement in python 3.6.5

### ISSUE THREAD

**Issue by OneTruthPrevails** [cython/cython#2463]
Expected ')', found '='

**Comment by gabrieldemarmiesse** [comment]
I think it's an issue of Python 2/3. By default, cython uses python 2 semantics. 

I agree that it is counter-intuitive. There is an easy fix. See #2299.

**Comment by scoder** [comment]
Not a bug, but there will be a transition to Py3 syntax by default.
