### ISSUE TITLE
pre-processor support for sizeof(type)

### ISSUE THREAD

**Issue by SnowWalkerJ** [cython/cython#2473]
As far as i recall, you can write 
```C
#define SIZE_OF_INT sizeof(int)
```
in C.

However, when I write 
```cython
DEF USE_LONG = 1
IF USE_LONG == 1:
    ctypedef long Int
ELSE:
    ctypedef int Int
DEF SIZE_INT = sizeof(Int)
```
in Cython, the compiler gives the error: `Invalid compile-time expression` for the last line above. But the result of `sizeof(int)` can be known at compile-time.

**Comment by robertwb** [comment]
This can't be done, because the generated `c` file may be compiled on platforms with different integer sizes. (There are two compile phases, `pyx` -> `c` and `c` -> `so`/`dll` and this error refers to the former whereas `sizeof(int)` is only known at the latter.)
