### ISSUE TITLE
Issue with Stackless Python 2.7.14

### ISSUE THREAD

**Issue by kdschlosser** [cython/cython#2476]
Windows 7 x64 sp1
Stackless Python 2.7.14 x32
Cython 0.28.3

I am not sure if it is possibly something I am doing wrong. There is a project I am working on and it compiles using Python 2.7.14 without problem. When I compile it using Stackless Python 2.7.14 I get a Python app crash as soon as it starts cythonizing.

Here is the data from the app crash window

    Problem Event Name:	APPCRASH
    Application Name:	python.exe
    Application Version:	0.0.0.0
    Application Timestamp:	59ccecdf
    Fault Module Name:	python27.dll
    Fault Module Version:	2.7.14150.1013
    Fault Module Timestamp:	59ccecce
    Exception Code:	c0000005
    Exception Offset:	00069c2a
    OS Version:	6.1.7601.2.1.0.256.1
    Locale ID:	1033
    Additional Information 1:	0a9e
    Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
    Additional Information 3:	0a9e
    Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

I am building python_openzwave (updated version that will build on Windows) and I am more then happy to provide the code and requirements to build it if it is needed to do some testing. I think that because it builds properly without Stackless that there is some kind of a compatibility issue with Stackless. The project I am working on has been around since 1996 and unfortunately Stackless Python is not something that can be removed and the version of python can not be upgraded at the present time.

I searched the internet to see if anyone has had an issue with the 2 working together and I could not find any issues. I couldn't find anything on someone running the 2 together either. Pretty much a dead end.

Any help is appreciated.
Thanks again.
Kevin

**Comment by scoder** [comment]
I never tried Cython with Stackless, and I'm no Windows user, so I can't comment on this. But if you could run it in a debugger to get a stack trace of the crash, that might be helpful.

**Comment by kdschlosser** [comment]
I have never had the need to run python code through a debugger. I know of the pdb module for python but I have never used this before. I know I also have the ability to debug the crash with Visual Studio but when I do it really doesn't show a whole lot because of not having pdb files associated to anything python related.

I could be going about this wrong. if you could give me a direction to head in so i can get the correct information over to ya.

it appears to me from what debugging information i did get was that the fault happens just after StringIOTree.pyd files gets loaded. Now whether the error is in this file. or possibly the one that loads after it i do not know.

I do want to also mention that Stackless python does have an addition include directory and I have tried both having it added and not and the error persists.

**Comment by kdschlosser** [comment]
what is very strange is the fact that it will not compile on Stackless but it does compile on the save version of  a non Stackless python. and if i take the compiled version and move it to the Stackless installation it does not run. and I get the exact same error.  I thought I should mention that as well.

**Comment by scoder** [comment]
I added test jobs for stackless to travis. Seems to [fail completely](https://api.travis-ci.org/v3/job/405554719/log.txt) for 2.7, based on some issue in the test runner, but seems to [work quite](https://api.travis-ci.org/v3/job/405554720/log.txt) well in Stackless Py3.6, with only one failure in the embedding test (which has a rather involved build setup, so the failure is not very surprising).

**Comment by scoder** [comment]
`pdb` won't help here, since the crash is at the native level, not in Python code. Visual Studio would be the right place to look. I never used it, though.

**Comment by kdschlosser** [comment]
OK well that is great that you did some test runs. and have also encountered the problem.

What i find strange is if i compile using Python 2.7 it compiles without error and the compiled ll loads without error. Then if i load the compiled dll in Stackless 2.7 i get the same error that i get when i compile the code using Stackless.

Could the problem lie with Stackless and not Cython?
I am in the same boat as far as Visual Studio knowledge.  

You may need to alter the include paths so it includes the additional h files that are in stackless. there are additional subfolders under the normal python includes folder. I am not sure if you accounted for this. I do not know the file structure of Stackless 3+ and if this same thing needs to be accounted for.

Would you happen to be able to provide me with the error output for the travis builds for 2.7 I think i may ask some questions over in the stackless repo.

**Comment by kdschlosser** [comment]
as you can see I am talking to the folks that make stackless. If there some kind of a minimal example that causes this crash that i can give them. they want to run it with a debugging version they have compiled. The only thing I have is the project I am working on which has a more complicated build environment that needs to e set up first.

**Comment by kdschlosser** [comment]
OK so i am not sure exactly what was causing the issue but i ran a build of openzwave using msbuild instead of visual studio. and when Cython ran no exception everything seems to be good. I do not know what caused the issue because I am using the same msbuild that VS is using. I am passing the solution right to msbuild. VS has to be adding some argument that is causing an issue don't know what it is.

**Comment by kdschlosser** [comment]
Ok. so the results are in. This problem actually still did exist even tho I did manage to get Cython to compile  my code it was still throwing a strange exception "SystemError no exception set" upon importing the file. the folks over at stackless have spent quite a bit of time locating and repairing the issue. I wanted to note it here so that if someone else runs across this problem it has been documented. It appears as this problem might also affect stackless python 3 versions as well. 

a more detailed description of the cause and solution can be found here
https://github.com/stackless-dev/stackless/issues/166
as well as in the referenced issue several posts back.

I want to thank @scoder for adding stackless to the travis tests. it provided information that may have aided in a quick repair of the problem.

**Comment by akruis** [comment]
Hi, I'm a maintainer of Stackless Python. As reported by @kdschlosser the problem with Stackless Python 2.7.x has been identified an fixed (stackless-dev/stackless#166, [Stackless commit 187184ba](https://github.com/stackless-dev/stackless/commit/187184ba0c4f7250387efb365a651358bca3ebfa)) at least to a certain degree. It is now possible to build and run Cython generated extension modules using Stackless Python 2.7.x.

Unfortunately this is not sufficient, at least from my point of view. Stackless Python is designed as a ABI compatible replacement for regular C-Python. This works, as long as an extension module uses the documented C-API only. But Cython uses the undocumented PyFrameObject which differs between regular C-Python and Stackless-Python. Not a problem, if you compile everything on Stackless, but if you install a binary wheel (i.e. pip install bencoder), that has been created with Cython the module will crash.

I'll open a separate issue to discuss this problem.
