### ISSUE TITLE
\n is interpreted in verbatim code

### ISSUE THREAD

**Issue by realead** [cython/cython#2484]
In Cython 0.28.3

The following example:

```
cdef extern from *:
    """
    #include <stdio.h>
    void print_endln(){
       printf("\n");
    }
    """
    void print_endln()
    
def print_endln_wrapper():
    print_endln()

```

results in the following code (which cannot be compiled):

```
    #include <stdio.h>
    void print_endln(){
       printf("
");
    }
```

Please note, that "\n" becomes a linebreak.

It is not what I would expect from verbatim, but if it is "functioning as designed" please mention this in documentation.

NB: Something similar happens to other escape characters, for example \t, in this case however the produced c-file can be compiled (Which doesn't mean it makes it easier to find the reason for unexpected behavior).

**Comment by scoder** [comment]
It's how strings work in Python. If you don't want escapes to be evaluated, use a raw string (`r"""..."""`).

Doc PR welcome.

**Comment by realead** [comment]
Thanks for clearing that!

Maybe it should be recommended to use `r"""..."""` per default in the [documentation](http://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#including-verbatim-c-code)?

I guess often the user is not even aware that there are some escapes in the verbatim-code because it will be just copied&pasted from somewhere and using `"""..."""` might break the code in more or less subtle ways.
