### ISSUE TITLE
Late import in thread hangs

### ISSUE THREAD

**Issue by gerrieroos** [cython/cython#2486]
Given two files:

foo.py:
`print 'foo'`

t.py:
```import threading
def run():
        print 1
        import foo
        print 2
f = threading.Thread(target=run)
f.start()
f.join()
```

Compiling/freezing them:
cython -D t.py ; /usr/home/jail/usr/local/bin/cython_freeze -o main.c t ; gcc -s -pthread -Os -o t main.c t.c \`python2.7-config --cflags --ldflags\`

Executing 't':
1

The 'import foo' never completes. This also affects importing other modules such as 'os', 'subprocess', etc.

**Comment by gerrieroos** [comment]
It looks like the import lock is being held by the main thread. Adding 'imp.release_lock()' somewhere before f.join() is a workaround.

**Comment by scoder** [comment]
That's a relict of the pre-PEP-489 time. It's not going to be fixed in Py2 any more. Better support in Cython is pending, see #1715.
