### ISSUE TITLE
Is it possible to raise compile time error in pyx?

### ISSUE THREAD

**Issue by braindevices** [cython/cython#2491]
I would like to do some small preprocessor like job in pyx. So that I can check the environment during cythonize（） or compilation. Then it can set some constant or if environment does not match that pyx's pre-request it can raise an error during cythonize() or compilation.

**Comment by jdemeyer** [comment]
You can do it in C:
```
cdef extern from *:
    r"""
    #if SOMETHING_WRONG
    #error "Something is wrong!"
    #endif
    """
```

**Comment by scoder** [comment]
I agree with Jeroen. I'm not sure if that's what you meant, but using the compile time environment for decisions like this is the wrong thing most of the time. It's better to move adaptations to C compile time. Please reopen the ticket if I misunderstood your request.
