### ISSUE TITLE
No .c line in traceback during module init

### ISSUE THREAD

**Issue by jdemeyer** [cython/cython#2492]
Since the introduction of the disabling of `.c` lines in tracebacks, such line numbers are unconditionally not shown during the module init code:
```
      __Pyx_AddTraceback("init sage.structure.coerce_maps", 0, __pyx_lineno, __pyx_filename);
```
Since I find these `.c` line numbers really handy for debugging, I consider it a serious regression.

**Comment by jdemeyer** [comment]
I guess the reason for that disabling should be fixed anyway by #2199.

**Comment by jdemeyer** [comment]
I should also add that C lines are particularly useful during module init, because the init logic is quite complicated and the Cython traceback is not very useful there.

**Comment by wkerzendorf** [comment]
@jdemeyer we're currently building bleeding-edge cython with flags to make sure that it doesn't segfault. At what point can we use a stable version of cython again? currently we have to do this: https://github.com/tardis-sn/tardis/blob/master/.travis.yml
