### ISSUE TITLE
Should not use __attribute__((optimize(…)))

### ISSUE THREAD

**Issue by jwilk** [cython/cython#2494]
[GCC documentation](https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/Common-Function-Attributes.html#index-optimize-function-attribute) says this about the `optimize` attribute:
>This attribute should be used for debugging purposes only. It is not suitable in production code.

In practice, `__attribute__((optimize("Os")))` seems to re-enable strict aliasing, despite `-fno-strict-aliasing` specified on command-line:
```
i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-5qX40H/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python2.7 -c build/temp.linux-i386-2.7/src/decode.c -o build/temp.linux-i386-2.7/build/temp.linux-i386-2.7/src/decode.o -pthread
build/temp.linux-i386-2.7/src/decode.c: In function 'initdecode':
build/temp.linux-i386-2.7/src/decode.c:51244:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   __Pyx_INCREF(((PyObject *)(&PyString_Type)));
   ^~~~~~~~~~~~
```
<sup>([full build log](https://buildd.debian.org/status/fetch.php?pkg=python-djvulibre&arch=i386&ver=0.8.1-1&stamp=1531050480&raw=1))</sup>

I was going to file a bug against GCC, but then I realized the attribute shouldn't be used in the first place, and there's apparently [plenty of bugs about it in GCC Bugzilla already](https://gcc.gnu.org/ml/gcc-help/2014-12/msg00130.html).

**Comment by scoder** [comment]
Thanks for finding that out. The `cold` attribute seems to have a similar effect, though:
https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/Common-Function-Attributes.html#index-cold-function-attribute

**Comment by charris** [comment]
@scoder Will Cython be changing the use of the attribute?

**Comment by charris** [comment]
I ask because if it is true that `__attribute__((optimize("Os")))`  re-enables strict aliasing, that would be a problem for NumPy.

**Comment by scoder** [comment]
Yes, this will change in 0.29. See 9ddac7152091eac62830fea4f38b4d7f9edb6a86.

**Comment by scoder** [comment]
You can always define the C macro `CYTHON_SMALL_CODE` to nothing to disable this unconditionally.

I'd like to release it rather earlier than later, but there is no clear release timeframe. #2499 is the most important open ticket. Once that's solved, and it'll take a couple of person days to get right, I think I'd look into a release. So, expect a couple of weeks.

I'll also consider a 0.28.5 release in the meantime that would have this fix.

**Comment by mattip** [comment]
Just a FYI that numpy/numpy#11665 adopted defining `CYTHON_SMALL_CODE=` was merged for an upcoming  NumPy 1.15.1, thanks for helping work through this.

**Comment by scoder** [comment]
Seeing that this causes actual trouble to projects, I decided to release 0.28.5 with (almost) only this fix. It's uploading to PyPI now.

**Comment by charris** [comment]
Thanks @scoder .
