### ISSUE TITLE
Why Cython uses gcc -O2 optimizations?

### ISSUE THREAD

**Issue by y-luis** [cython/cython#2502]
Cython, by default, calls `gcc` compiler with `-O2` flag, what is the reason behind that, since `-O0` (which reduces compilation time) is the default in `gcc`?

When I run my project with `-O0`, compilation time is reduced by 50%! So I wonder whether there is a strong reason to use the default.

**Comment by robertwb** [comment]
Cython uses Python's distutils which uses whatever flags were used to compile Python itself.
