### ISSUE TITLE
Could you provide a more general code in "Tutorials>Calling C libraries"

### ISSUE THREAD

**Issue by GoingMyWay** [cython/cython#2521]
The example in [Tutorials>Calling C libraries](http://docs.cython.org/en/latest/src/tutorial/clibraries.html) is awesome, but how can I write cython code so that the `Queue` can store any types in Python, since in `collections.deque`, one can store any type 

```
In [1]: from collections import deque 

In [2]: q = deque()

In [3]: q
Out[3]: deque([])

In [4]: a = set()

In [5]: q.append(a)

In [6]: q.append(1)

In [7]: q
Out[7]: deque([set(), 1])
```

I haved tried to set `int` to `void*` and cast `-1` to `<void*>(-1)`, but it seems that is not the right solution. Can you help me, thank you!

**Comment by gabrieldemarmiesse** [comment]
You should be able to cast the adress of the python object to a `void*`. But then, you are responsible for keeping the Python objects alive and free the memory. See this example: http://docs.cython.org/en/latest/src/userguide/language_basics.html#type-casting

Note that there is a cython mailing list, github issues are more to report bugs.

**Comment by GoingMyWay** [comment]
@gabrieldemarmiesse thank you, could you provide the mailing list?

**Comment by gabrieldemarmiesse** [comment]
Sure, here it is: https://groups.google.com/forum/#!forum/cython-users

**Comment by scoder** [comment]
Doc PR welcome, but I wouldn't count this as a bug.
