### ISSUE TITLE
Using <complex.h> include does not work

### ISSUE THREAD

**Issue by HaidStefan** [cython/cython#2524]
Hello guys,
I am new to Cython and I wanted to wrap a simple c-function to python. In the C File i use: `#include<complex.h>`

When i try to build the wrapper i get following error:
lib/mandelbrot_c.c(10): error C2146: Syntaxfehler: Fehlendes ";" vor Bezeichner "c"
lib/mandelbrot_c.c(10): error C2065: "c": nichtdeklarierter Bezeichner
lib/mandelbrot_c.c(10): error C2065: "z": nichtdeklarierter Bezeichner
...

The problem is that the macro does not work i guess. The code used in the c-file is: 
`double complex c, z;`

The files can be found here:
https://github.com/HaidStefan/python_wrap_c_libraries/tree/dev/cython

Does anyone know a solution for this? Sorry if this question is dumb but i am new to cython and I'm trying to make a benchmark between different wrappers. 

Thanks a lot in advance
Stefan

**Comment by robertwb** [comment]
I would guess the problem is having a struct called `complex`, e.g.

```
cdef extern from "mandelbrot_c.h":
    struct complex:
        pass
```

If you need more help, follow-up on the users list at `cython-users@googlegroups.com`.

**Comment by HaidStefan** [comment]
If anyone is interested:
The complex library from the C99 standard library is not supported from the MSVC compiler, which is used to build cython. 
See: [https://stackoverflow.com/questions/22991409/compiling-c-code-in-visual-studio-2013-with-complex-h-library](https://stackoverflow.com/questions/22991409/compiling-c-code-in-visual-studio-2013-with-complex-h-library)

**Comment by robertwb** [comment]
complex.h is used by Cython iff it is explicitly included (as it is here).
