### ISSUE TITLE
Use __slots__ in pure Python mode?

### ISSUE THREAD

**Issue by jdemeyer** [cython/cython#2526]
This is just an idea that I had while thinking about pure Python mode: in Python, using `__slots__` makes a class quite close to an extension type: attributes are stored as `PyObject *` in the object structure.

So I would propose: in pure Python mode, translate a class with `__slots__` to a `cdef class` and translate the attributes to `cdef public object` attributes.

Maybe this should not be enabled by default. At a minimum, we should use `__slots__` when the class is declared as `cdef class` in the `.pxd` file or by `@cython.cclass`.

**Comment by scoder** [comment]
You can already use
```
@cython.cclass
class ExtType:
    x: cython.int
    y: str
```
I think that's better than caring about `__slots__`.

**Comment by jdemeyer** [comment]
Sure, but you lose compatibility with older Python versions that way. Anyway, it was just an idea, feel free to shoot it down :-)

**Comment by robertwb** [comment]
I agree that it would make a sense to do it for at least for classes
declared to be cdef classes, though if there's a pxd file we would need the
members listed explicitly there for cimporting.

**Comment by scoder** [comment]
I'm closing this as a duplicate of #995.
