### ISSUE TITLE
Cython.Build.cythonize does not respect CC or GCC environment variables

### ISSUE THREAD

**Issue by ostrokach** [cython/cython#2535]
`Cython.Build.cythonize` does not respect the `CC` and / or `GCC` environment variables and defaults to the `gcc` binary. This is especially problematic with `conda-build >= 3.0`, where the `{{ compiler('c') }}` requirement installs compilers of the form `x86_64-conda_cos6-linux-gnu-cc` instead of `cc`, etc.

I created an example Cython package that [fails](https://gitlab.com/ostrokach/cython-bug/-/jobs/87513018) to build using [standard conda-build](https://gitlab.com/ostrokach/cython-bug/blob/master/.ci/conda-fail/build.sh) but [passes](https://gitlab.com/ostrokach/cython-bug/-/jobs/87513021) if I [create symlinks](https://gitlab.com/ostrokach/cython-bug/blob/master/.ci/conda-pass/build.sh) from `gcc` to `${GCC}`.

See also: [StackOverflow - Set default compiler when using Cython and setuptools to compile multiple extensions](https://stackoverflow.com/questions/47770000/set-default-compiler-when-using-cython-and-setuptools-to-compile-multiple-extens)

**Comment by scoder** [comment]
`cythonize` uses distutils, which makes use of `CC`. Are you sure the env vars are set correctly on your side?

**Comment by ostrokach** [comment]
I think the environment variables are set correctly.

The only difference between a passing and a failing script are the lines:
```bash
ln -s ${CC} $(dirname ${CC})/cc
ln -s ${GCC} $(dirname ${GCC})/gcc
```

It seems that distutils is in legacy mode, and its use is [no longer recommended](https://packaging.python.org/guides/tool-recommendations/)?

**Comment by scoder** [comment]
`distutils` is in the stdlib, so it is not necessary to recommend its use. It is always used when building extension modules. And it definitely uses `$CC` on unixy systems.

In fact, there is nothing special about Cython at all here. If you can build other packages with binary modules, then you should be able to build Cython generated modules.

**Comment by ostrokach** [comment]
Maybe Cython may be missing a call to `distutils.sysconfig.customize_compiler(c)`?

```python
import distutils.ccompiler

c = distutils.ccompiler.new_compiler()
print(c.compiler)
# prints ['cc']

distutils.sysconfig.customize_compiler(c)
print(c.compiler)
# prints ['/path/to/my/cc', '-Wsign-compare', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-Wstrict-prototypes']
```

**Comment by scoder** [comment]
Again, Cython is _not_ calling the C compiler. It's done by distutils, which makes use of `$CC`.

**Comment by ostrokach** [comment]
Thank you for your help, and sorry for the noise. 

This issue is not related to Cython.

----

For the benefit of others, for whatever reason, this issue only appears when the `conda-forge` channel is ahead of the `defaults` channel in the `~/.condarc` file...
