### ISSUE TITLE
Change directive default to `language_level=3`

### ISSUE THREAD

**Issue by scoder** [cython/cython#2565]
This is a breaking change that needs preparation. It changes the default semantics of the Cython language from Python 2 to Python 3.

Specifically, it will enable the `__future__` imports `division`, `print_function`, `absolute_import`, and preferably also `generator_stop` (which became active in Python 3.7).

Excluding `unicode_literals` from the default setup seems like a good idea, as long as users want to continue supporting Python 2.x (and if they don't then it makes no difference for Py 3.x anyway). In this case, it is worth considering if f-strings should also be supported for Py2 `str`, although it might not be worth implementing this given the nearing end of life of Py2.

Users will be able to opt out of this by explicitly setting `language_level=2`. We should emit a warning in a prior release when no language level is specified.

**Comment by jdemeyer** [comment]
As I mentioned on the mailing list, I would very much like to exclude `from __future__ import unicode_literals` (which is often considered a bad idea).
