### ISSUE TITLE
Add PyArray_IS_F_CONTIGUOUS

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#2567]
Appears [`PyArray_IS_F_CONTIGUOUS`]( https://docs.scipy.org/doc/numpy/reference/c-api.array.html#c.PyArray_IS_F_CONTIGUOUS ) missing from the `numpy` Cython API. Would be nice to have it.

**Comment by mattip** [comment]
See 222334c0b9 which should provide this and others.

**Comment by jakirkham** [comment]
Hmm...not seeing this function or macro there. Am I missing something?

**Comment by mattip** [comment]
I see it [here]( https://github.com/cython/cython/commit/222334c0b91eae41de2af2692daec6183cdaf243#diff-24bcfc3298e43281fed97318a554550dR162) in that changeset

**Comment by mattip** [comment]
Seems you are right, still missing.

**Comment by jakirkham** [comment]
No worries. Certainly that changeset is an improvement in either case.
