### ISSUE TITLE
Documentation does not describe ctuples?

### ISSUE THREAD

**Issue by CnlPepper** [cython/cython#2574]
I discovered ctuples a while ago by exploring the Cython changelog, but I can't find any reference to them in the documentation. They are a much more elegant/faster way of passing multiple return values between functions, I had been using pointers/references in cdef functions before I discovered them (which is messy) e.g.

ctuple:
    cdef (bint, double, double, int) my_func(double a, double b):
        ...
        return True, d1, d2, i

CLEAN! :)

pointer:
    cdef bint my_func(double a, double b, double *d1, double *d2, int *i)
        ...
        d1[0] = ...
        d2[0] = ...
        i[0] = ...
        return True

YUCK! :(

Could they please be added to the next version of the documentation?

FYI I have an open ticket with pycharm relating to the lack of recognition of ctuples: https://youtrack.jetbrains.com/issue/PY-31491
It would be useful to be able to point the developer to some formal documentation.

**Comment by scoder** [comment]
PR very welcome. Should go to the end of this section:
http://docs.cython.org/en/latest/src/userguide/language_basics.html#c-variable-and-type-definitions
in this file:
https://github.com/cython/cython/blob/master/docs/src/userguide/language_basics.rst

**Comment by gabrieldemarmiesse** [comment]
Who knew that a feature so awesome existed? Seriously, that's super cool. If you need any help @CnlPepper , tag me and I'll give a hand.

**Comment by CnlPepper** [comment]
@gabrieldemarmiesse Thanks for the link to the test file, most useful. I didn't realise ctuples had some of the other tuple functionality.

**Comment by gabrieldemarmiesse** [comment]
@CnlPepper you are welcome!
