### ISSUE TITLE
cython and gcc

### ISSUE THREAD

**Issue by 1587257781** [cython/cython#2586]
I used cython to convert the .py file to a .c file, and then used gcc to convert the .c file to a .so file. The following problem occurred in the second process.
gcc -fPIC -c test.c
In file included from Python.h:68:0,
                 from test.c:4:
pytime.h:122:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
     struct timeval *tv,
            ^~~~~~~
pytime.h:127:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
     struct timeval *tv,
            ^~~~~~~
test.c:1711:30: fatal error: structmember.h: No such file or directory
     #include <structmember.h>
                              ^
compilation terminated.

**Comment by robertwb** [comment]
You should probably be using distutils to orchestrate the second step, as it will set up the flags and paths correctly for your Python. If this still doesn't work, please don't hesitate to ask on the mailing lists.

**Comment by 1587257781** [comment]
@robertwb  Thank you, I will give it a try, then I have any questions in the mail to ask you。

**Comment by 1587257781** [comment]
@robertwb I will try the method you said, what is the problem in the mail to ask you
