### ISSUE TITLE
Cython Invalid types for '>' (float[:, :], float)

### ISSUE THREAD

**Issue by xfanak** [cython/cython#2594]
Hello everyone, I'm trying to use cython to speed up my code, but this error jumps out while compile:

 **Invalid types for '>' (float[:, :], float)**

and here's my code (the relevant part):

```
import numpy as np
cdef float[:,:] myarray
a = np.where(myarray>0.05)
```
Can anybody help me figure this out? Python version 3.6.3, cython version 0.29
Thanks in advance!

**Comment by scoder** [comment]
A memory view is not a NumPy array and does not support NumPy's broadcasting etc. operations.
