### ISSUE TITLE
fopenmp issue on mac

### ISSUE THREAD

**Issue by peiyaoli** [cython/cython#2599]
Hi, I met some issues with Cython fopenmp library here.
Mine OS is macos 10.13.6 。
gcc version 5.

I compiled a module with fopenmp and cython library, no error poped up. However, while I import the module, 
···
ImportError: dlopen(/Users/XXX/Documents/Projects/parallel-mse/entropy.cpython-36m-darwin.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /Users/XXX/Documents/Projects/parallel-mse/entropy.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/XXX/Documents/Projects/parallel-mse/entropy.cpython-36m-darwin.so
···

Here is my `gcc -v`

Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@5/5.5.0_2/libexec/gcc/x86_64-apple-darwin17.3.0/5.5.0/lto-wrapper
Target: x86_64-apple-darwin17.3.0
Configured with: ../configure --build=x86_64-apple-darwin17.3.0 --prefix=/usr/local/Cellar/gcc@5/5.5.0_2 --libdir=/usr/local/Cellar/gcc@5/5.5.0_2/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --enable-plugin --disable-werror --with-pkgversion='Homebrew GCC 5.5.0_2' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-nls --enable-multilib
Thread model: posix
gcc version 5.5.0 (Homebrew GCC 5.5.0_2)

I googled lots of threads but none could solve this. Could anyone have a lot at it?
Thanks

**Comment by lorentzenchr** [comment]
@da-woods Without a minimal reproducing example and 5 years old, I think this can be closed.
