### ISSUE TITLE
Reconsider inspect.iscoroutine() etc.

### ISSUE THREAD

**Issue by scoder** [cython/cython#2609]
Currently, the type testing functions in the `inspect` module reject the corresponding Cython functions.

On the one hand, this makes sense because Cython functions have no byte code, for example, and are therefore not 100% compatible, depending on what users intend to find out when they do the type test.

On the other hand, this is unfortunate, because many use cases do not require byte code but rely only on certain other features that Cython already emulates.

Let's discuss if it should stay that way.

Relevant links:
- http://docs.cython.org/en/latest/src/userguide/limitations.html#inspect-support
- python-trio/trio/issues/550

**Comment by whplh** [comment]
Hey there. 
The python community gave the new guideline in [PEP 575](https://www.python.org/dev/peps/pep-0575/#cfunction) as the new standard for what a function should be and what kind of functions should exist.
Unfortunately they kicked the cython function from the inspect module without providing the inspect.isbasefunction as mentioned in the document. 
So maybe someone knows what is actually needed to comply with the new standard? 
"Just" rename "cyfunction" to "cfunction"? =) 
But then there are also bound methods...

**Comment by da-woods** [comment]
This may now be fixed, at least on Python 3.11+

**Comment by scoder** [comment]
This was meant (although not used much) as a discussion ticket, and the decision was more or less taken on CPython side now. We should just go as far as possible with the compatibility.

It's not completely implemented, not for older Python versions than 3.10/3.11 at least, but let's consider the decision done and close the ticket.
