### ISSUE TITLE
detecting compiler from setup.py 

### ISSUE THREAD

**Issue by jordi-vaquero** [cython/cython#2611]
Hello Everyone, 
I am working on a project that connects my own C++ code with my own c++ code to python/cython code. The code works fine but on compilation time there are some flags that needs to be added based on which compiler you use. clang needs **compile_args.append('-stdlib=libc++')** but gcc doesn't. 
Mac uses clang by default but gcc can be installed so asking for a darwing architecture is not helping. 

My question is how can I say which compiler version is using to compile the cythonized files, in order to make the different statesments my self. 

Thanks for your help

Jordi

**Comment by scoder** [comment]
Not a Cython problem (and this is a bug tracker) but a general distutils question. The mailing list is a good place to discuss questions like this.
Somewhat related to #2531, though.
