### ISSUE TITLE
Cython produces invalid C in some cases

### ISSUE THREAD

**Issue by Nikratio** [cython/cython#2613]
In some cases, Cython produces invalid C code:

```
$ cat mylib.pyx 
cdef object py_retval

async def test():
    global py_retval
    py_retval = {'foo': 42}

$ cython --version
Cython version 0.28.5

$ cython -3 -Wextra --force -3 --directive embedsignature=True mylib.pyx --fast-fail

$ python3 ./setup.py build_ext --inplace
running build_ext
building 'mylib' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-MLq5fN/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c mylib.c -o build/temp.linux-x86_64-3.5/mylib.o -Wall -Wextra
mylib.c: In function ‘__Pyx_modinit_global_init_code’:
mylib.c:1422:3: error: ‘__pyx_cur_scope’ undeclared (first use in this function)
   __pyx_cur_scope->__pyx_v_5mylib_py_retval = Py_None; Py_INCREF(Py_None);
   ^~~~~~~~~~~~~~~
mylib.c:1422:3: note: each undeclared identifier is reported only once for each function it appears in
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

[testcase.zip](https://github.com/cython/cython/files/2391748/testcase.zip)

**Comment by Nikratio** [comment]
Also reproduced with current git master (Cython version 0.29a0)

**Comment by scoder** [comment]
Looks like an analysis problem. The variable `py_type` is mostly just used as a global in plain cdef functions, but also in an async coroutine function in `fuse_api.pxi`. My guess is that this is the place where the type analysis erroneously decides that it is part of a closure, although it is clearly also declared as a global in that function.

**Comment by scoder** [comment]
Probably trivial to fix, once we find the place where that happens.

**Comment by Nikratio** [comment]
`fuse_api.pxi`? That's weird, I replaced the original huge testcase with a tiny one just a few minutes after filing the issue. Could you try to refresh? This should show you something much more tractable :-).
