### ISSUE TITLE
Stopped generating C files.

### ISSUE THREAD

**Issue by thetestgame** [cython/cython#2617]
I was working with Cython on Windows 10 and it worked for about 20 compiles before it just stopped generating files all together. It executes successfully but does not generate any files. This was the repo I was using to test https://github.com/AnythingTechPro/cython-cmake-example.

**Comment by scoder** [comment]
That cmake setup looks pretty complicated. Are you sure there's nothing wrong with that?

**Comment by thetestgame** [comment]
It shouldn't be the cmake. it worked perfectly for about 20 compiles until I hit a syntax error with my Cython code. Since the syntax both the cmake and the regular cythonize methods do not work. I've tried recloning that repositories, I've tried over repositories, tried wiping and reinstalling Cython. Nothing seems to work. The output though still seems as though Cython is doing something just its not outputting any files.

**Comment by thetestgame** [comment]
I've been able to identify the issue as an environment problem. I'm closing this issue.
