### ISSUE TITLE
Cython embedsignature gives useless information for memoryviews in Sphinx

### ISSUE THREAD

**Issue by matt-chan** [cython/cython#2634]
Hi,
The embedsignature option in Cython gives call signature information for Sphinx to document, but it is not useful when describing memoryviews. 

This is the source:
```
def foo(double[::1] n):
    ....
```
And this is the call signature printed in Sphinx

> foo(__Pyx_memviewslice n)

So it loses the type information, along with the dimension and stride. Is it possible to add this in? Or is this something that should be addressed from the Sphinx-autodoc side? 

Thanks!

**Comment by scoder** [comment]
Definitely a bug, thanks for the report. The code for this is in the `EmbedSignature` tree transformation in `AutoDocTransform.py`, probably easy to fix. Want to give it a try?

**Comment by matt-chan** [comment]
I think this fixes it. No idea if it breaks something else though. I just stepped through it with a debugger and found where the string gets generated...
