### ISSUE TITLE
Bug in absolute import handling in python 2.7

### ISSUE THREAD

**Issue by ibell** [cython/cython#2638]
I think this is the same issue: https://grokbase.com/t/gg/cython-users/1417hszq2d/pxd-import-problem-when-modules-added-to-package

I have code in a .pyx file in my package PDSim (https://github.com/ibell/pdsim) that reads:
```
from PDSim.flow cimport flow_models
```
which yields the error (though somehow not terminal):
```
PDSim/scroll/_scroll.pyx: cannot find cimported module 'PDSim.flow'
```
in which the folder flow in my package has the contents:
```
>> ls -l
-rw-rw-r-- 1 ian ian  2216 Dec 19  2017 fanno.pyx
-rw-rw-r-- 1 ian ian  1933 Dec 19  2017 flow_models.pxd
-rw-rw-r-- 1 ian ian 24767 Sep 30 18:32 flow_models.pyx
-rw-rw-r-- 1 ian ian  2407 Dec 19  2017 flow.pxd
-rw-rw-r-- 1 ian ian 13527 Dec 19  2017 flow.pyx
-rw-rw-r-- 1 ian ian     0 Dec 19  2017 __init__.py
```

Why does it not find this module?

**Comment by ibell** [comment]
I can "fix" the issue with the replacement of
```
from PDSim.flow cimport flow_models
```
by
```
cimport PDSim.flow.flow_models as flow_models
```
which is pretty verbose, and smells like a bug.  The parallel python import is
```
from PDSim.flow import flow_models
```
which works fine.

**Comment by scoder** [comment]
This case might need special-casing in the path search. I guess it tries to look for a cimportable `PDSim.flow` package, which would succeed if there was a `PDSim/flow/__init__.pxd` file, but ignores the `__init__.py` file as something non-cimportable. Instead, it should look for it, and continue the name list search only for `name.pxd` files.

**Comment by bweigel** [comment]
From what we could figure out the problem stems from the `cimported_files`-method in `Dependencies.py`, when `pxd_file` is `None`:

```python
    def cimported_files(self, filename):
        ...
            pxd_file = self.find_pxd(module, filename)
            if pxd_file is not None:
                pxd_list.append(pxd_file)
            elif not self.quiet:
                print("%s: cannot find cimported module '%s'" % (filename, module))
```

This seems to be ultimately due to `search_include_directories`-function in `Utils.py`, which doesn't cover all the cases of package/module-discovery, which are:

1. `pkg/a.pxd` where `b` is definied in the `a.pxd`
1. `pkg/a/__init__.pxd` where `b` is definied in the `__init__.pxd`
2. `pkg/a/b.pxd` and `pkg/a/__init__.[pxd|py|pyx]`

**Comment by bweigel** [comment]
The `self.cimports(filename)` call returns an "incomplete" list of possible dependencies to include.
i.e. in case of `from pkg.a cimport b` it would only return `pkg.a`, which would miss the aforementioned case 3 (package structure of `pkg/a/b.pxd` together with `pkg/a/__init__.[pxd|py|pyx]`)
