### ISSUE TITLE
Absolute cimporting errors

### ISSUE THREAD

**Issue by ibell** [cython/cython#2639]
I really don't want to have to specify full paths for cimports if I can avoid it.....

Within a package, this is valid in python with normal import, but not in Cython with cimport (in python 2.7 with language level='3'):
```
cimport .common_scroll_geo as comm
```
and you must do
```
cimport PDSim.common_scroll_geo as comm
```
and the error received is quite obtuse:
```
Error compiling Cython file:
------------------------------------------------------------
...
import numpy as np
import cython

import matplotlib.pyplot as plt

cimport .common_scroll_geo as comm
       ^
------------------------------------------------------------

PDSim/scroll/symm_scroll_geo.pyx:8:8: Expected an identifier
```

**Comment by scoder** [comment]
That's not actually valid Python. Python requires `from . import common_scroll_geo as comm` instead.
