### ISSUE TITLE
cdiv and cmod incorrect?

### ISSUE THREAD

**Issue by dubiousjim** [cython/cython#2643]
I was looking at the definitions of `cdiv` and `cmod` in Shadow.py. These seem to give incorrect results for some operands. For example, in C99:

```
4 / -4 == -1    4 % -4 == 0
4 / -2 == -2    4 % -2 == 0
4 / -1 == -4    4 % -1 == 0
```

But these functions would return:

```
cdiv(4, -4) == 0    cmod(4, -4) == 4
cdiv(4, -2) == -1    cmod(4, -2) == 2
cdiv(4, -1) == -3    cmod(4, -1) == 1
```

That's based on just running those definitions in the Python interpreter. Perhaps Cython handles them specially, and doesn't in fact give the incorrect results above. Still, why not include correct Python code? The following would work:

```
def cdiv(a, b):
    if a < 0:
        a = -a
        b = -b
    if b < 0:
        return (a + b + 1) // b
    return a // b

def cmod(a, b):
    r = a % b
    if (a*b) < 0 and r: r -= b
    return r
```

Sorry if this is just me misunderstanding some magic behind the scenes stuff.

**Comment by robertwb** [comment]
Thanks for looking at this! Please feel free to send a PR, or if you don't have the time I can fix them.

**Comment by mb-a** [comment]
You might want to make sure that your new functions work properly with the test found here:
https://github.com/cython/cython/blob/master/tests/run/cdivision_CEP_516.pyx#L27-L28

**Comment by scoder** [comment]
I'm targeting this to 3.0 for now, but would consider backporting it since it's really a bug fix for something that's currently broken.
