### ISSUE TITLE
Enable TLS on cython.org

### ISSUE THREAD

**Issue by bentley** [cython/cython#2654]
Visiting https://cython.org/ leads to a certificate error, as GitHub serves a certificate only valid for GitHub subdomains.

As of May 1, GitHub supports TLS for custom domains by hosting sites on a CDN. This means [updating the DNS records for cython.org](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain) should be enough to enable TLS via Let’s Encrypt.

**Comment by robertwb** [comment]
Thanks for the pointer. I've updated the DNS records; hopefully they should propagate (and a certificate be issued) soon. I'll keep this open once I verify.

**Comment by robertwb** [comment]
All works great.
