### ISSUE TITLE
Setting `language_level=3` breaks `cimport` with one or more nested directory

### ISSUE THREAD

**Issue by fish2000** [cython/cython#2661]
Basically, setting `language_level=3` breaks `cimport` statements with one or more nested directory. 

If you have `mypackage/mycymod.pyx` that does a `cimport` of `mypackage/ext/stuff/mywrappers.pxd`, like by doing `from ext.stuff.mywrappers cimport MyThing`, this works fine with `language_level=2` but breaks with `language_level=3`, where all of a sudden the Cython compiler reports that it cannot find any of the .pxd files e.g. `mypackage/ext/stuff/mywrappers.pxd`.

It works, if you drop `mywrappers.pxd` down one level – but that’s a hack workaround.

I have created [a GitHub repository](https://github.com/fish2000/language_level) containing a pretty minimalist example demonstrating this bug, with the `language_level=2` setting in `master` and `language_level=3` in another branch, inventively titled `language_level_3`. Here’s how one may readily check the bug:

```bash
$ cd /tmp
$ git clone https://github.com/fish2000/language_level.git
$ cd language_level/
$ ls -sF
$ ./rebuild # this runs `python setup.py build_ext --inplace`
$ git status # this will show updated code generated by cython
$ git reset --hard
$ git checkout language_level_3 # branch changes `language_level=3`
$ git pull
$ ls -sF
$ more setup.py # you can see the updated `language_level`
$ ./rebuild # This command will die with Cython compile errors!
$ git reset --hard
$ cd ..
$ rm -rf language_level
```

I first noticed this problem in my own project, [Halogen](https://github.com/fish2000/halogen), which uses Cython; I am stuck on `language_level=2` at the moment because of this.

**Comment by fish2000** [comment]
It may behoove whoever investigates this to consider #2638 as well – it looks to be possibly somehow related.

**Comment by fish2000** [comment]
[Here, also, is a gist](https://gist.github.com/fish2000/0fbccb196c573d1acef819b753092326) with examples of the error messages in question.

**Comment by jdemeyer** [comment]
I think that this is just because of turning on `absolute_import`. You may need to replace `cimport ext.FOO` by `cimport .ext.FOO`

**Comment by scoder** [comment]
Agreed, this seems normal Python behaviour.
