### ISSUE TITLE
Many NumPy functions marked as needing GIL that do not

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#2663]
Recently reached for [`PyArray_GetPtr`]( https://docs.scipy.org/doc/numpy-1.15.0/reference/c-api.array.html#c.PyArray_GetPtr ), to get quick C level access into a location in a NumPy array. Went to release the GIL as this function does not create any Python objects, but was surprised to find that [Cython requires the GIL for it]( https://github.com/cython/cython/blob/5dfefdadf6c20bf631ea3b6e567eede2f1ddd3d0/Cython/Includes/numpy/__init__.pxd#L718 ). Started to make a PR, but quickly discovered there are many such functions like [`PyArray_NDIM`]( https://docs.scipy.org/doc/numpy-1.15.0/reference/c-api.array.html#c.PyArray_NDIM ), [`PyArray_STRIDES`]( https://docs.scipy.org/doc/numpy-1.15.0/reference/c-api.array.html#c.PyArray_STRIDES ), [`PyArray_DATA`]( https://docs.scipy.org/doc/numpy-1.15.0/reference/c-api.array.html#c.PyArray_DATA ), etc. that are also marked as requiring the GIL even though they are providing convenient access to `struct` members. Given the scope and the discussion in issue ( https://github.com/numpy/numpy/issues/11803 ), figured we should discuss the right way forward.

**Comment by scoder** [comment]
AFAICT, these functions/macros are not documented as not requiring the GIL. I'd rather not take that decision on our side. If the NumPy devs agree that they want to support GIL-free access to them in the future, then we can adapt to that in Cython. One more reason to let NumPy ship its own declarations for Cython code.

**Comment by jakirkham** [comment]
My understanding is the array structure and data access macros/functions are all safe to use without the GIL. Skimming [the associated code]( https://github.com/numpy/numpy/blob/v1.15.2/numpy/core/include/numpy/ndarraytypes.h#L1468 ) seems to confirm this. Though I must admit I don't see any documentation to confirm this belief.

Certainly understand the value in being safe. Also agree this is a pretty reasonable argument for moving the API over to NumPy.

**Comment by scoder** [comment]
I'll move the responsibility for this over to the NumPy project, based on https://github.com/numpy/numpy/issues/11803.
