### ISSUE TITLE
Typed memoryview slicing syntax broken

### ISSUE THREAD

**Issue by Time0o** [cython/cython#2664]
I am unable to compile the following example taken straight from the [Typed Memoryviews](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.htmll) tutorial section with Cython 0.29 or 0.28.5:

```Python
def process_3d_buffer(int[1:102:2,:] view not None):
    pass
```

Importing a `.pyx` file containing only the above using `pyximport.install()` results in the following:

```
Error compiling Cython file:
------------------------------------------------------------
...
def process_3d_buffer(int[1:102:2,:] view not None):
                          ^
------------------------------------------------------------

foo.pyx:1:27: Start must not be given.

Error compiling Cython file:
------------------------------------------------------------
...
def process_3d_buffer(int[1:102:2,:] view not None):
                     ^
------------------------------------------------------------

text.pyx:1:22: Only Python type arguments can have 'not None'
```

I would find it very odd if samples shown in the tutorial were not covered by unit tests.
Am I overlooking something here?

**Comment by scoder** [comment]
Thanks for bringing this up. It's wrongly presented in the docs. Slicing is not part of the declaration, it's only available as a normal expression. Meaning, you can do
```cython
cdef int[:] view1d = obj
view1d = view1d[::2]  # select only every second row
```
But you cannot select specific subsets as part of the declaration. I'll change the docs.
