### ISSUE TITLE
Could Cython's setup.py get more compiler flags from distutils.sysconfig?

### ISSUE THREAD

**Issue by gmc444-b** [cython/cython#2673]
I'm at one of those shops that is running Python on Solaris. We build our Python interpreters as 64-bit applications. When building Cython on our Solaris servers, it does not pick up the native C compiler flags from the Python sysconfig. The build defaults to the 32-bit memory model and fails.

Could Cython's setup.py be enhanced to get these compiler flags from distutils.sysconfig?

**Comment by robertwb** [comment]
Cython only manages the .pyx -> .c conversion, from then on it's distutils (or setuptools) that actually invokes the C compiler, which is where this needs to be fixed.

**Comment by gmc444-b** [comment]
Perhaps I wasn't clear. I'm not trying to build code with Cython, I'm trying to build Cython itself from the source distribution. I'm asking for a modification to [this code](https://github.com/cython/cython/blob/master/setup.py#L111) in Cython's setup.py to get Python's compiler flags from sysconfig.
