### ISSUE TITLE
Links are hard to see on cython.org

### ISSUE THREAD

**Issue by gwerbin** [cython/cython#2677]
It's very hard to tell links apart from regular text on the Cython homepage. [Example screenshot on Imgur](https://imgur.com/a/nit9qDn).

This is undesirable from a general UX perspective and can be an issue for accessibility. Is there any reason they can't be a slightly brighter shade, and/or underlined?

They also don't change on-hover or if they've already been followed. Is there any reason not to set this?

I'd make the PR myself but I don't see the stylesheet in this repo.

**Comment by robertwb** [comment]
The site is a separate repo: https://github.com/cython/cython.github.io
Pull requests welcome.
