### ISSUE TITLE
cython array in pure python mode

### ISSUE THREAD

**Issue by h5rdly** [cython/cython#2678]
Cheers for this awesome project.

I read the [Pure Mode](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html) tutorial, but couldn't find this specific item - how can i `from cpython cimport array` in pure python mode, inside a `,py` file that has `import cython`?

Thanks,
Eli

**Comment by scoder** [comment]
Could you explain your use case? The C interface and the Python interface to the `array.array` type are not really interchangeable, so writing Python code that uses the C interface when compiled is probably not easy. You might be able to get away with memory views, though.

**Comment by h5rdly** [comment]
Hi,

My case is unpacking same-type data coming from a socket - I'm recieving bytestreams of ints, floats etc.
 I'm trying to do better than struct.unpack(), and thought cython arrays might be the way to go, but the infrastructure is such that other people are around the code as well, so I prefer use pure mode if possible. 

Are you talking about using cython memoryviews with python arrays?

**Comment by scoder** [comment]
Yes, that's what I meant. In Py3, they should work with `array.array` without further setup, also from Python code. And indexing/slicing should also work nicely for both environments, with the same syntax.

**Comment by h5rdly** [comment]
What if we have 2.7 at work? Anything to be done?

**Comment by h5rdly** [comment]
Guess I wait until we upgrade to 3.7. Still sound odd that you can declare all regular c types in pure python mode with `@cython.loclas`, but can't declare c arrays, would be super beneficial

**Comment by h5rdly** [comment]
How about ctypes arrays?  Can they be used with cython memoryview?

**Comment by scoder** [comment]
The PEP 3118 buffer interface was originally only added for Py3 and then backported to Py2, but never applied to the standard data types there, let alone the standard library. The support in Py3 was still improved over the first couple of releases. I'd be surprised if ctypes had any support for it at all, even in Py3.

**Comment by scoder** [comment]
I'll close this as a question that was answered. Not something to do on Cython side.
