### ISSUE TITLE
unable to use cython anaconda on windows 10

### ISSUE THREAD

**Issue by tempegarit** [cython/cython#2711]
windows 10
anaconda Version 5.3
Python 3.7.0
MSC v.1912 64 bit (AMD64)

I had this function on jupyter lab.

    def fib(n):
        if n<2:
            return n
        return fib(n-1)+fib(n-2)

i call it with code below and it ran well.

    fib(20)

Then i tried to use cython. First i load cython.

    %load_ext Cython

And here was where i used cython.

    %%cython
    def fib_cython(n):
        if n<2:
            return n
        return fib_cython(n-1)+fib_cython(n-2)

After i ran the code above,  this error cames up

    DistutilsPlatformError: Unable to find vcvarsall.bat

I've tried following instruction on this link

https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_Cython_On_Anaconda_On_Windows?lang=en#action=addcomment

It didn't work for me.

Is there anyone know how to solve this problem?

**Comment by josephcslater** [comment]
I have the same issue. I followed the instructions for [Cython working on Windows](https://github.com/cython/cython/wiki/CythonExtensionsOnWindows) but didn't get past `setenv` isn't a Windows shell command.

**Comment by robertwb** [comment]
Several people on the users list use Windows; you'll have better luck getting this question answered there.
