### ISSUE TITLE
Should PyUnicode_FromObject return unicode?

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#2714]
Curious as to whether [`PyUnicode_FromObject`]( https://github.com/cython/cython/blob/084a25f55d0b4cf8b4c3cd496ec57bb3e2f57f71/Cython/Includes/cpython/unicode.pxd#L122 ) should have a return type of `unicode` or not?

**Comment by scoder** [comment]
It can call into the codecs using the user definable default encoding and I think I wasn't sure at the time whether all decoders are guaranteed to return a unicode string in Py2 (and Py3?). It's probably safe, but then, this is C. "Probably" leaves a chance for hard crashes, so I left it open.

Worth further investigation.

**Comment by scoder** [comment]
Answered too quickly. I now see that `PyUnicode_Decode()`, which is the weakest fallback that may get called at the very end, only calls `PyUnicode_Check()` on the final result, not `PyUnicode_CheckExact()`. So the return value is actually not guaranteed to be an exact `unicode` object, which is what the `unicode` type implies in Cython.

So, answer is "no, it should not".
