### ISSUE TITLE
Can't return wanting type of data

### ISSUE THREAD

**Issue by leeweizhe1993** [cython/cython#2717]
Hello, I want to build a function that can return the most common permutation of six "R" letters plus six "B" letters, the list may looks like this:
![image](https://user-images.githubusercontent.com/32242263/48481944-3b9a6c00-e84a-11e8-926e-e35f39552e90.png)
I want to write a loop of this function to simulate the most common distribution of these strings. I did write a for loop with python and it did work, but after I import cython to accelerate this function, something goes wrong, here is the error:
![image](https://user-images.githubusercontent.com/32242263/48482092-ad72b580-e84a-11e8-81c1-2a9ccea2fa5f.png)
What kind of data should I return to accelerate my simulation, please?

**Comment by robertwb** [comment]
This is more a user support issue that should be asked in the mailing list.
