### ISSUE TITLE
Error when building against cpython 3.8-dev

### ISSUE THREAD

**Issue by jnwatson** [cython/cython#2721]
There's no urgency since 3.8 isn't going to be released for a while.

```/home/nic/src/cython/Cython/Plex/Scanners.c: In function ‘__pyx_tp_dealloc_6Cython_4Plex_8Scanners_Scanner’:
/home/nic/src/cython/Cython/Plex/Scanners.c:6643:104: warning: implicit declaration of function ‘_PyGC_FINALIZED’; did you mean ‘_Py_IS_ALIGNED’? [-Wimplicit-function-declaration]
   if (unlikely(PyType_HasFeature(Py_TYPE(o), Py_TPFLAGS_HAVE_FINALIZE) && Py_TYPE(o)->tp_finalize) && !_PyGC_FINALIZED(o)) {
 ```

The missing symbol (actually a manifest constant) is _PyGC_FINALIZED.

The Python devs have been reorganizing the API to separate the officlal API from the internal one. That manifest constant definition is now protected by ```#if defined(Py_BUILD_CORE) || defined(Py_BUILD_CORE_BUILTIN)``` in objimpl.h

**Comment by vstinner** [comment]
I just fixed it with commit https://github.com/python/cpython/commit/3e21ad1a254cc33e8d4920ad7f026254ec728bee of https://github.com/python/cpython/pull/10626.

**Comment by scoder** [comment]
Thanks @vstinner!
And thanks for the heads-up @jnwatson!
