### ISSUE TITLE
Include PyUnicode_FromStringAndSize in cpython.unicode

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#2726]
Would be nice to have the Python C API call [`PyUnicode_FromStringAndSize`]( https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_FromStringAndSize ) in [`cpython.unicode`]( https://github.com/cython/cython/blob/master/Cython/Includes/cpython/unicode.pxd ).

**Comment by TeamSpen210** [comment]
It's not really necessary. Simply do `buffer[:len].decode()`, which will do the same thing, via an inline function and then one line of `PyUnicode_Decode`. This way you can still pass an encoding and errors. `PyUnicode_FromStringAndSize` does a UTF8 decode anyway.

**Comment by scoder** [comment]
I agree, but still, any missing C-API function is a bug. PR welcome.
