### ISSUE TITLE
Change in 0.29.1 causes C4804 in MSVC

### ISSUE THREAD

**Issue by wesm** [cython/cython#2731]
We've experienced test failures caused by this change https://github.com/cython/cython/commit/55861ed7698382af7799013466cfbb2bae08b97d and this code

```c
#if CYTHON_USE_PYLONG_INTERNALS
  #include "longintrepr.h"
  #undef SHIFT
  #undef BASE
  #undef MASK
  #ifdef SIZEOF_VOID_P
    enum { __pyx_check_sizeof_voidp = 1/(SIZEOF_VOID_P == sizeof(void*)) };
  #endif
#endif
```

See https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/20527085/job/f0u8990fn0qb6u0d#L1354

```
lib.cpp(201): error C2220: warning treated as error - no 'object' file generated
lib.cpp(201): warning C4804: '/': unsafe use of type 'bool' in operation
ninja: build stopped: subcommand failed.
error: command 'C:\\Program Files (x86)\\CMake\\bin\\cmake.exe' failed with exit status 1
```

We'll suppress the warning for now

**Comment by scoder** [comment]
Thanks for the report. Interesting enough, this didn't show up in our MSVC builds. I added an explicit type cast that should resolve this.
