### ISSUE TITLE
Casting int to cpdef enum

### ISSUE THREAD

**Issue by Xfel** [cython/cython#2732]
Simplified code:
```
cpdef enum MyEnum:
    MY_VAL=2

def my_fn():
    return <MyEnum>2
```

I'd expect my_fn() to return MyEnum.MY_VAL, but just returns the int value.

**Comment by jakirkham** [comment]
Encountered the same thing.

FWIW this works:

```cython
cpdef enum MyEnum:
    MY_VAL = 2

def my_fn():
    return MyEnum(2)
```

That said, would not have expected needing the explicit construction of `MyEnum`.

**Comment by jakirkham** [comment]
Guessing there would need to be some alternative handling [here]( https://github.com/cython/cython/blob/796fd06da1fa1d5481ce43a6b6c901bc87f0ce9a/Cython/Compiler/PyrexTypes.py#L495 ) to handle `cpdef enum` types conversion. Noting this in part as that code path seems to be used to generate the `int` coercion C code seen with this example.

**Comment by jakirkham** [comment]
Maybe this could be done by checking if it is an instance of [`__Pyx_EnumBase`]( https://github.com/cython/cython/blob/efdf996dced075682d86b7e53a12b56b5ebfea38/Cython/Utility/CpdefEnums.pyx#L22 ).

What do you think @scoder? 🙂

**Comment by jakirkham** [comment]
It is worth noting that using the construction workaround in comment ( https://github.com/cython/cython/issues/2732#issuecomment-1176893773 ) comes with fairly significant overhead.

```cython
cpdef enum MyEnum:
    MY_VAL = 2

def my_fn1():
    return MyEnum.MY_VAL

def my_fn2():
    return MyEnum(MyEnum.MY_VAL)
```

```python
In [3]: %timeit my_fn1()
27.6 ns ± 0.394 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [4]: %timeit my_fn2()
398 ns ± 5.33 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

**Comment by jakirkham** [comment]
A more performant approach might be mapping preexisting `MyEnum` Python objects to `MyEnum` C values like so.

```cython
cpdef enum MyEnum:
    ZERO = 0
    ONE = 1


cdef inline _convert_MyEnum_c_to_py(MyEnum c_enum):
    if c_enum == MyEnum.ZERO:
        return (<object>MyEnum).ZERO
    elif c_enum == MyEnum.ONE:
        return (<object>MyEnum).ONE
    else:
        raise ValueError(f"Unknown `MyEnum` value: {c_enum}")

 
def my_fn1():
    cdef MyEnum c_enum = MyEnum.ONE
    cdef object py_enum = <object>c_enum
    return py_enum


def my_fn2():
    cdef MyEnum c_enum = MyEnum.ONE
    cdef object py_enum = _convert_MyEnum_c_to_py(c_enum)
    return py_enum
```

```python
In [3]: %timeit my_fn1()
28.1 ns ± 1.42 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [4]: %timeit my_fn2()
79.9 ns ± 0.537 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

This still adds some overhead due to the global lookup for `MyEnum`, but it is unclear how this would be avoided given the nature of the check.

**Comment by da-woods** [comment]
> Guessing there would need to be some alternative handling [here](https://github.com/cython/cython/blob/796fd06da1fa1d5481ce43a6b6c901bc87f0ce9a/Cython/Compiler/PyrexTypes.py#L495) to handle `cpdef enum` types conversion. Noting this in part as that code path seems to be used to generate the `int` coercion C code seen with this example.

Doesn't look to go through there when I set a breakpoint there. (Although I suspect you're broadly right about where to look)

**Comment by da-woods** [comment]
> A more performant approach might be mapping preexisting MyEnum Python objects to MyEnum C values like so.

It looks to me like `__Pyx_EnumBase` tries to do this already so I'm slightly surprised there's so much benefit. Possibly "ordered_dict" is the wrong structure?

**Comment by scoder** [comment]
I agree that this behaviour should be changed. Returning the corresponding Enum object is the expected result. In the case of an invalid enum integer value, I'd also expect an exception, probably a `ValueError` as shown in https://github.com/cython/cython/issues/2732#issuecomment-1178383584. Cython can probably do something more efficient internally than the generic attribute lookup in `(<object>MyEnum).ZERO`.

**Comment by jakirkham** [comment]
> > Guessing there would need to be some alternative handling [here](https://github.com/cython/cython/blob/796fd06da1fa1d5481ce43a6b6c901bc87f0ce9a/Cython/Compiler/PyrexTypes.py#L495) to handle `cpdef enum` types conversion. Noting this in part as that code path seems to be used to generate the `int` coercion C code seen with this example.
> 
> Doesn't look to go through there when I set a breakpoint there. (Although I suspect you're broadly right about where to look)

Interesting came to that conclusion by looking at the generated C code and comparing. In particular was seeing references to that conversion code when doing `<object>c_enum`

That said, using the debugger seems like the more reliable way to go

> > A more performant approach might be mapping preexisting MyEnum Python objects to MyEnum C values like so.
> 
> It looks to me like `__Pyx_EnumBase` tries to do this already so I'm slightly surprised there's so much benefit. Possibly "ordered_dict" is the wrong structure?

Yeah was noticing that. Think the tricky thing is we want to lookup by `int` in this case, but the keys are `str`s for each value. Wasn't seeing a mapping that went from `int`s to `IntEnum` values, but may be overlooking something

**Comment by da-woods** [comment]
> > it looks to me like `__Pyx_EnumBase` tries to do this already so I'm slightly surprised there's so much benefit. Possibly "ordered_dict" is the wrong structure?
> 
> Yeah was noticing that. Think the tricky thing is we want to lookup by `int` in this case, but the keys are `str`s for each value. Wasn't seeing a mapping that went from `int`s to `IntEnum` values, but may be overlooking something

So having looked in more detail, it uses Python's `IntEnum` on most modern versions (not the class that's listed in the utility code). If you look at that's constructor it actually have it's own int -> enum map, but presumably you're just losing time on boxing/unboxing the enum.

**Comment by jakirkham** [comment]
> I agree that this behaviour should be changed. Returning the corresponding Enum object is the expected result. In the case of an invalid enum integer value, I'd also expect an exception, probably a `ValueError` as shown in [#2732 (comment)](https://github.com/cython/cython/issues/2732#issuecomment-1178383584). Cython can probably do something more efficient internally than the generic attribute lookup in `(<object>MyEnum).ZERO`.

Thanks Stefan 🙏

Do you have a sense of where it would make sense to add conversion code like this?

Agree there is likely a better way to handle accessing the right `IntEnum` value. Do you have thoughts on what would be the best way to approach this?

Also guessing we can do some templating to simplify the branch logic (if that is the right way to go).

**Comment by da-woods** [comment]
> Do you have a sense of where it would make sense to add conversion code like this?

(Not Stefan but) I have a 50% written change with the conversion code in as a `cdef __Pyx_Enum_{{name}}_to_py(int c_val)` in `CpdefEnum.pyx` (and called from the `PyrexTypes.CEnumType.create_to_py_utility_code` function).

> Agree there is likely a better way to handle accessing the right IntEnum value. Do you have thoughts on what would be the best way to approach this?

I'm not sure there's a better way to approach this - Cython doesn't look to have much special knowledge of the Python enum

> Also guessing we can do some templating to simplify the branch logic (if that is the right way to go).

yes
