### ISSUE TITLE
Typing collections' contents

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#2742]
It would be really useful to be able to type collections' contents. That way readability would improve as users could know what is inside a collection. Also Cython could optimize code related to working with items taken or added to the collections. It's possible the collections themselves could even be implemented at the C level in these cases aiding performance further. Syntax might look as follows.

```cython
cdef dict[char, int] typecode_sizes
```

Though these are all just thoughts at this point. Happy to discuss.

**Comment by scoder** [comment]
Duplicate of #1979.

**Comment by jakirkham** [comment]
Thanks @scoder. Sorry for the duplicate. Missed that one when I searched.
