### ISSUE TITLE
API for accessing parsed code?  ast-like?

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#2743]
pandas has hacked together a handful of lint-like scripts for cython code, but it would be much less kludgy if we could access something resembling an ast.  Is exposing something like that feasible?

The other use case I have in mind is generating a dependency graph.  Module X depends on modules A and B, ...  I can hack this together by regexing the pyx files, but `cythonize` must produce something like this internally, so using that must be more reliable.

**Comment by scoder** [comment]
This is a duplicate of #1628.
