### ISSUE TITLE
Optimized abs should be nogil-safe

### ISSUE THREAD

**Issue by QuLogic** [cython/cython#2746]
From the following:
```cython
cdef double foo(double x):
    return abs(x)

cdef int bar(int x):
    return abs(x)
```
the resulting C/C++ code calls `fabs`/`abs` thanks to #1255. If you add `nogil` on these functions, then Cython will complain with:
```
    return abs(x)
             ^
------------------------------------------------------------
test_abs.pyx:2:14: Calling gil-requiring function not allowed without gil
```
Because of #1837, I'm not sure about `bar`, but at least `foo` should not require the GIL.

**Comment by scoder** [comment]
True. It's probably as easy as adding nogil to the declaration of the C functions in `Builtin.py`. PR welcome.
