### ISSUE TITLE
'final' subclasses produce suboptimal self casts

### ISSUE THREAD

**Issue by QuLogic** [cython/cython#2747]
Starting from:
```cython
# subclass.pyx
cdef class A:
    cdef int foo(self):
        return -1

    cdef int bar(self, int x):
        return -1

cdef class Sub(A):
    cdef int foo(self):
        return self.bar(0)

    cdef int bar(self, int x):
        return x + 1
```
compiles fine with `cythonize -b subclass.pyx`. If you add `@cython.final` onto `Sub`, then it produces a non-fatal warning:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -m64 -fPIC -fPIC -Iconda/envs/cp36/include/python3.6m -c subclass.c -o build/temp.linux-x86_64-3.6/subclass.o
subclass.c: In function ‘__pyx_f_8subclass_3Sub_foo’:
subclass.c:1667:41: warning: passing argument 1 of ‘__pyx_f_8subclass_3Sub_bar’ from incompatible pointer type [-Wincompatible-pointer-types]
   __pyx_r = __pyx_f_8subclass_3Sub_bar(((struct __pyx_obj_8subclass_A *)__pyx_v_self), 0);
                                        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
subclass.c:1205:85: note: expected ‘struct __pyx_obj_8subclass_Sub *’ but argument is of type ‘struct __pyx_obj_8subclass_A *’
 static int __pyx_f_8subclass_3Sub_bar(CYTHON_UNUSED struct __pyx_obj_8subclass_Sub *__pyx_v_self, int __pyx_v_x); /* proto*/
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```
But if you _also_ add `# distutils: language = c++` to the file to compile as C++, then it fails to compile:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -m64 -fPIC -fPIC -Iconda/envs/cp36/include/python3.6m -c subclass.cpp -o build/temp.linux-x86_64-3.6/subclass.o
subclass.cpp: In function ‘int __pyx_f_8subclass_3Sub_foo(__pyx_obj_8subclass_Sub*)’:
subclass.cpp:1682:41: error: cannot convert ‘__pyx_obj_8subclass_A*’ to ‘__pyx_obj_8subclass_Sub*’
   __pyx_r = __pyx_f_8subclass_3Sub_bar(((struct __pyx_obj_8subclass_A *)__pyx_v_self), 0);
                                        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
subclass.cpp:1220:85: note:   initializing argument 1 of ‘int __pyx_f_8subclass_3Sub_bar(__pyx_obj_8subclass_Sub*, int)’
 static int __pyx_f_8subclass_3Sub_bar(CYTHON_UNUSED struct __pyx_obj_8subclass_Sub *__pyx_v_self, int __pyx_v_x); /* proto*/
                                                                                     ^
error: command 'gcc' failed with exit status 1
```

**Comment by QuLogic** [comment]
Note that in the C case (which produces just a warning), it seems to work correctly. That is, if we add:
```cython
def do_foo():
    cdef A a 

    a = Sub()
    return a.foo()
```
and call it, it returns 1 whether there's the `cython.final` decorator or not.

**Comment by robertwb** [comment]
Thanks for the report. Indeed, the code is correct, but the C compiler does not understand the subtype relationship among these pointers (hence the warning and error).

**Comment by jjerphan** [comment]
Such compilation warnings are also observed when building scikit-learn (see [this trace](https://gist.github.com/jjerphan/8cfbb5349f5680856460ff80152ab69d#file-full-trace-log-L492-L696)) on class hierarchy whose final classes aren't necessarily decorated with `@final`.

Still, we do not have any problems at runtime.

**Comment by scoder** [comment]
We might be able to mitigate this by generating a more suitable cast, at least in some cases.

**Comment by QuLogic** [comment]
Yes, I don't understand the title change. It's not suboptimal, it's outright not able to compile (in C++ mode).

**Comment by thesamesam** [comment]
And it won't be able to in C in April either.

**Comment by scoder** [comment]
What's failing here is that we cast the `self` argument to the inherited type of the original `self` argument defining the method, not the `self` of the final C function of the concrete subtype that we actually call.

https://github.com/cython/cython/blob/f2d564a06b775bd1cedfc36f5fc8996865ad3675/Cython/Compiler/ExprNodes.py#L6333

It feels like we should actually know the type of the concrete C function implementation, but it seems that we lose it when inheriting the original type. For calling `final` methods, we separately remember the `final_func_cname` of the C function and then call that. However, I think we should instead create a real entry for them to remember name and type, and then use that directly when analysing the method attribute in `AttributeNode`. `final` methods might not be more special than that, after all.

**Comment by hroncok** [comment]
I was wondering if as an immediate workaround for the failures we see in Fedora with GCC 14, we could add:

```
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
...
#pragma GCC diagnostic pop
```

**Comment by hroncok** [comment]
- Gentoo: https://github.com/gentoo/gentoo/pull/35549
 - Fedora: https://src.fedoraproject.org/rpms/Cython/pull-request/57

Should we temporarily add this to Cython upstream?

**Comment by mgorny** [comment]
For the record, my patch is pretty poor. It would certainly be better to limit the scope (i.e. `push`/`pop`) to the call itself.

**Comment by scoder** [comment]
If this is the best we currently have, then we can add the pragma for the time being. It works around a real user problem. But we should limit it to the absolute minimum of code, so that users still benefit from the C compiler diagnostics for their own code.

**Comment by scoder** [comment]
See https://github.com/cython/cython/pull/6039

**Comment by thesamesam** [comment]
@scoder Would it be possible to cut a point release soon with the workaround? GCC 14 is fast approaching and it'd be great to not have to keep telling other folks about this gotcha. Many thanks.
