### ISSUE TITLE
Cython 0.29 broke support for C++ enum classes

### ISSUE THREAD

**Issue by orivej** [cython/cython#2749]
Before https://github.com/cython/cython/commit/be4ca1d685e8d703f2285183147f8587da56fe6d (a fix for #2186), on this input:
```Cython
cpdef enum E "E":
    A
```
Cython was generating this:
```C
/* CIntToPy */
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__E(enum E value) {
    const enum E neg_one = (enum E) -1, const_zero = (enum E) 0;
```

Since https://github.com/cython/cython/commit/6079a5b0b0936feb2ec339a1f31d7d708ae6d3a3 it is generating this:
```C
/* CIntToPy */
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__E(enum E value) {
    const enum E neg_one = (enum E) ((enum E) 0 - (enum E) 1), const_zero = (enum E) 0;
```

This works for C enums, but fails to compile for C++ enum classes (https://godbolt.org/z/NY8PJT):
```C++
enum class E { X };
const enum E neg_one_class_28 = (enum E) -1;
const enum E neg_one_class_29 = (enum E) ((enum E) 0 - (enum E) 1);
```
```
<source>:3:54: error: invalid operands to binary expression ('enum E' and 'enum E')
const enum E neg_one_class_29 = (enum E) ((enum E) 0 - (enum E) 1);
                                          ~~~~~~~~~~ ^ ~~~~~~~~~~
```

**Comment by orivej** [comment]
Here is a complete example.
`e.hpp`:
```C++
enum class E { A, B };
```
`e.pyx`:
```Cython
cdef extern from "e.hpp" namespace "E":
    cpdef enum E "E":
        A
        B
```

**Comment by scoder** [comment]
Ok, this is really getting cumbersome … :)
What other options do we have that C and/or C++ compilers would accept without complaining all too loudly? Maybe `(enum E) (0 - 1)`, without the second cast ?

**Comment by orivej** [comment]
I think that `(enum E) (0 - 1)` would be the same as `(enum E) -1`, as was before #2186. I can not reproduce the warning mentioned in that issue, even though I have tried various version of gcc and clang with `-Wall`, with `enum` and `enum class`: https://godbolt.org/z/buBUI9

**Comment by orivej** [comment]
Apparently it is a GCC bug that `(enum E) -1` generates a warning with `-Wconversion`, since it is [documented](https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Warning-Options.html) that it should "not warn for explicit casts like abs `((int) x)` and `ui = (unsigned) -1`". Moreover, the current workaround does not help gcc 5.5 and earlier, as demonstrated in https://godbolt.org/z/DlXIfA.

I propose to explicitly silence this warning with:
```C
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#endif

const enum E a = (enum E) -1;

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif
```

**Comment by kblomqvist** [comment]
I thought that enum class is not supported yet. See, https://github.com/cython/cython/issues/1603.

**Comment by cf-natali** [comment]
Sorry to revive this old issue, but it seems that the problem is still present.
There are still occurrences of the problematic code 

https://github.com/cython/cython/blob/master/Cython/Utility/TypeConversion.c#L658
```
/////////////// CIntToPy ///////////////

static CYTHON_INLINE PyObject* {{TO_PY_FUNCTION}}({{TYPE}} value) {
    const {{TYPE}} neg_one = ({{TYPE}}) (({{TYPE}}) 0 - ({{TYPE}}) 1), const_zero = ({{TYPE}}) 0;
```

https://github.com/cython/cython/blob/master/Cython/Utility/TypeConversion.c#L879
```
/////////////// CIntFromPy ///////////////
//@requires: CIntFromPyVerify

{{py: from Cython.Utility import pylong_join }}

static CYTHON_INLINE {{TYPE}} {{FROM_PY_FUNCTION}}(PyObject *x) {
```

**Comment by da-woods** [comment]
@cf-natali In Cython 3 we [do now support enum classes properly](https://github.com/cython/cython/pull/3640). Obviously that doesn't help Cython 0.29 users but going forward the thing to do is probably to use an enum class instead.

**Comment by cf-natali** [comment]
Thanks @da-woods .
Indeed, we're looking forward to Cython 3 however for now it's quite annoying for us since Cython 0.29 is used e.g. in the latest Ubuntu LTS - I assume this will affect quite a few people.

**Comment by cf-natali** [comment]
https://github.com/cython/cython/pull/3803 fixes this (tested locally).
