### ISSUE TITLE
Implement PEP-560: core support for generic types

### ISSUE THREAD

**Issue by vvegorova** [cython/cython#2753]
Seems that `Generic.__class_getitem__` can't be called automatically after cythonization.

Code sample `example.py`:

```python
from typing import Generic, TypeVar

T = TypeVar("T")
print(Generic[T])
```
Cythonization:
```cythonize -a -i example.py```

The cythonized code fails with `TypeError`:
```
>>> import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "example.py", line 5, in init example
    print(Generic[T])
TypeError: 'type' object is not subscriptable
```

Cython 0.29.1
Python 3.7.1

**Comment by scoder** [comment]
PEP-560 is not currently implemented. Probably easy to do, but needs to be done.
https://www.python.org/dev/peps/pep-0560/

**Comment by scoder** [comment]
This should be relatively easy.
- copy over the tests from CPython
- copy over parts of the implementation from CPython
- adapt and optimise.

**Comment by scoder** [comment]
PR welcome.

**Comment by msg555** [comment]
For whatever it's worth I'm still running into apparently this issue with Cython 0.29.16/Python 3.7.7 running the same test as the OP.

**Comment by scoder** [comment]
See https://github.com/cython/cython/issues/2753#issuecomment-450492882 above. PR welcome.

**Comment by msg555** [comment]
My feeling is that https://github.com/cython/cython/pull/3518 should address. Seems like just dropping back to PyObject_GetItem is sufficient when we're not dealing with a mapping or sequence object. Would definitely still need to write some tests

**Comment by nikhilmishra000** [comment]
it seems like #3518 did not entirely fix this issue -- there will be an error if you try to inherit from the subscripted class.

For example, with the following in `example.py`, and building the same way as above:
```
from typing import Generic, TypeVar

T = TypeVar("T")

print(Generic[T])

class MyClass(Generic[T]):
  pass
```

will give:
```>>> import example
typing.Generic[~T]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "example.py", line 7, in init example
    class MyGeneric(Generic[T]):
TypeError: __init__() takes 3 positional arguments but 4 were given
```

**Comment by msg555** [comment]
Yes, we skipped MRO support for this MR. That still needs to happen and is also part of PEP 560.

**Comment by scoder** [comment]
@nikhilmishra000 I created #3537 from your comment. PR welcome.

**Comment by gst** [comment]
I am having the OP problem as well.. is there any workaround / solution ?

**Comment by scoder** [comment]
@gst, sure, use Cython 3.0, where the fix was implemented.

**Comment by gst** [comment]
@scoder I get the same error with cython 3.0(a6) .. :\

**Comment by gst** [comment]
to be noted that with python3.6 and cython 0.29.21 I do NOT have the problem..

**Comment by da-woods** [comment]
Python 3.6 didn't use `__class_getitem__` so that's an unsurprising result. It was introduced to simplify the implementation of `Typing`.

I believe this won't be fixed in Cython 0.29.x - we're considering it a new feature, not a bug fix, and new features aren't being added to 0.29.x any more.

No idea why this isn't working in the current Cython 3.0 version. It is in there and it is tested so everything (except inheritance) should work.

**Comment by gst** [comment]
> No idea why this isn't working in the current Cython 3.0 version. 

should I open a new issue with my env. details  ?

**Comment by da-woods** [comment]
@gst Certainly "example.py" from the original post of this issue works for me on the latest master. You might be better off asking on the Cython-users mailing list (with enough detail to reproduce your setup) since I don't think this is really a Cython bug

**Comment by gst** [comment]
with latest master : 

```python
TypeError: __init__() takes 3 positional arguments but 4 were given
```

with the following example:

```
rom typing import Generic, TypeVar

T = TypeVar('T')


class FitnessCalculator(Generic[T]):
    pass
```

**Comment by da-woods** [comment]
Inheritance from generic types definitely doesn't work right now - https://github.com/cython/cython/issues/3537. I don't have a good workaround.

**Comment by da-woods** [comment]
> Inheritance from generic types definitely doesn't work right now - #3537. I don't have a good workaround.

OK - the workaround is to explicitly spell out all the steps that should be done automatically

```
from typing import Generic, TypeVar

T = TypeVar('T')

gt = Generic[T]

class FitnessCalculator(*gt.__mro_entries__((gt,))):
    __orig_bases__ = (gt,)
    pass
```

**Comment by gst** [comment]
I confirm the workaround works.. it's not very nice but it works.
