### ISSUE TITLE
Document @cython.compile

### ISSUE THREAD

**Issue by h5rdly** [cython/cython#2770]
Hi,

I was wondering whethter there is a way, or it is possible to add a way, to do something like:
```python
from cython import cythonize, other, cython, magics

@cythonize  # Decorator of interest
@other 
@cython
@magics
def slow_function_at_work():
      # omg so slow

# slow function is fast at this point
```
I dug a bit inside some cython files, and saw there's a `pyx_to_dll` function, and a `cython_inline` function. 

Is it perhaps possible to - 
- Make `pyx_to_dll` read `StringIO` objects (probably not since I saw that path is formed into a command string)
- Somehow work with `cython_inline(inspect.getsource(slow_function))`
- Use some other method

So that one can @cythonize his functions in pure mode?

I think this is the epitome of pure mode - the ability to decorate and move along, and let cython hook in the sped up code.

Thanks,
Eli

**Comment by h5rdly** [comment]
Sweet, thanks!

It looks like `RuntimeCompiledFunction` in fact uses `cython_inline`.  
Are you aware of - 
https://github.com/AlanCristhian/statically

This package also seems to use a similar technique, but has more meat to it - 
https://github.com/AlanCristhian/statically/blob/master/statically.py

**Comment by scoder** [comment]
> Does @cython.compile take into account the other magics, eg locals, returns, cfunc, nogil etc?

I would hope so, but since it's undocumented, you'd better try it out. If it does not, then that's probably just an easy to fix bug.

**Comment by h5rdly** [comment]
Sorry if it's silly, but how can I see in runtime what @compile generated?
