### ISSUE TITLE
Where is the `pgen` executable for compiling the grammar?

### ISSUE THREAD

**Issue by FRidh** [cython/cython#2782]
While improving the cross-compilation situation of Python packages in Nixpkgs, I attempted to fix the Cython package. It needs a `pgen` executable:
```
Unable to find pgen, not compiling formal grammar.
```
Where can I find this executable?

CPython comes with a `pgen` header and `lib2to3` module, but no executable as far as I know.

**Comment by scoder** [comment]
https://github.com/python/cpython/tree/master/Parser

You can build it with `make Parser/pgen`.

Note that Cython's `Grammar` file is not currently used, and also somewhat outdated.

**Comment by FRidh** [comment]
Thanks for the quick reply. 

> Note that Cython's `Grammar` file is not currently used, and also somewhat outdated.

Are you implying that it may not be usable? How would one then continue, without the grammar?

**Comment by robertwb** [comment]
The "grammar" of Cython is implicit in its lexer/parser. This is an (unfinished) attempt to standardize that, but is not used yet.

**Comment by scoder** [comment]
Also see https://bugs.python.org/issue35808

**Comment by RaitoBezarius** [comment]
@scoder As pgen is retired, do you think the code in `setup.py` that relies on it could be removed too?
