### ISSUE TITLE
`test_embed` failure with Python 3.7.2 and cython 0.29.2

### ISSUE THREAD

**Issue by FRidh** [cython/cython#2785]
In Nixpkgs we run the test suite after building and installing. It failed with:
```
======================================================================
FAIL: test_embed (__main__.EmbedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runtests.py", line 1803, in test_embed
    "make PYTHON='%s' CYTHON='%s' LIBDIR1='%s' test > make.output" % (sys.executable, cython, libdir)))
AssertionError: 0 != 512
```

**Comment by FRidh** [comment]
On the following page the reference to the log can be found:
https://hydra.nixos.org/build/86735910

**Comment by FRidh** [comment]
I don't see any other reference to `test_embed` in the log.

**Comment by scoder** [comment]
Ah, right, the names of the specific files are different. This is the error:
```
/nix/store/3xwc1ip20b0p68sxqbjjll0va4pv5hbv-binutils-2.30/bin/ld: cannot find -lncurses
collect2: error: ld returned 1 exit status
make: *** [Makefile:19: embedded] Error 1
```
My guess is that CPython was somehow built with `ncurses` and remembered that in its distutils build flags, but during the Cython build, the library is not available. Not an actual Cython problem, rather a dependency problem with the specific CPython installation.

**Comment by FRidh** [comment]
Ahh, thanks for showing that. We recently wiped some info from `sysconfigdata` in not a very clean way, so it may be related to that. Might have to do that. Thanks again!
