### ISSUE TITLE
Problem with variable scope in nested iteration

### ISSUE THREAD

**Issue by eguaio** [cython/cython#2787]
Probably related with issue #1159, but I'm not sure.
In python, the following code:
```
def showMe(*arg):
    print [list(a) for a in arg]

dats = [[1, 2], [3, 4]]
showMe( *( (str(a) for a in d) for d in dats))
```
Shows:
`[['1', '2'], ['3', '4']]`
But compiled with Cython, it shows:
`[['3', '4'], ['3', '4']]`

That is, the scope of the variables in the iterators is changed. 
This different behavior gave me a lot of problems, since I mostly test the software with python and compile it with Cython for shipping.
Fixing the problem would be great, but I understand this could be related with optimizations that Cython does when compiling, so it is not easy to solve. Rather than that,  I would like to know where to find documentation about all the different behaviors between CPython and Cython, so I can avoid using that language constructs.

And thank you for the great job you're doing!

**Comment by scoder** [comment]
Yes, that's exactly #1159. CPython evaluates the iterable directly when creating the generator (i.e. outside of the generator itself), Cython does it when starting it, i.e. inside. That's one of the biggest bugs that Cython currently has. Doesn't show very often, but it can.

Regarding a list of current differences, I think the issue tracker serves that need best:
https://github.com/cython/cython/labels/Python%20Semantics

**Comment by scoder** [comment]
I added a link here: http://docs.cython.org/en/latest/src/userguide/limitations.html
