### ISSUE TITLE
numpy.ufunc size check insists on exact size match

### ISSUE THREAD

**Issue by TimoRoth** [cython/cython#2799]
numpy.ufunc does not carry the "check_size ignore" flag, which in turn results in runtime failures if the size of the struct grows:
https://github.com/cython/cython/blob/master/Cython/Includes/numpy/__init__.pxd#L918

With numpy 1.16, after long years of that struct being untouched, it now gained 3 new fields and grew in size.

Judging by
https://github.com/numpy/numpy/blob/master/numpy/__init__.py#L177
It is clearly expected to just result in a warning. In reality, the module fails to load.

Am I missing something here, or is there simply the "check_size ignore" part missing for that class?

**Comment by seberg** [comment]
Both the `pxd` in cython and in NumPy have this flag (now), so I think we can close this issue.

**Comment by scoder** [comment]
@seberg right, thanks for noticing.
