### ISSUE TITLE
Remove support for Python 2 and Python 3 < 3.7 in Cython 3.1

### ISSUE THREAD

**Issue by astrojuanlu** [cython/cython#2800]
As you might have heard, [Python 2 is EOL in about 11 months](https://pythonclock.org/). I wonder what is the roadmap of Cython regarding Python 2 support, because [most core scientific Python projects have already explicited theirs](https://python3statement.org/).

In particular, I guess dropping Python 2 support would help fixing [some cygdb bugs](https://github.com/cython/cython/issues?utf8=%E2%9C%93&q=is%3Aopen+cygdb) which in my opinion make using Cython a bit more painful than it should.

**Comment by robertwb** [comment]
We don't have a specific roadmap, but given that we're a low-level
dependency we do have a history of supporting Python versions long after
EOL. We are working on changing the default language level to be 3 with the
next release.

This is a good question for the list.

(It would be good to fix the cygdb bugs regardless, only fixing them on
Python 3 would be reasonable.)

**Comment by scoder** [comment]
As discussed on the cython-users mailing list, Cython 3.0 will still provide support for Python 2.7, both for running the compiler in it and for building and using the generated extension modules.

This is meant to ease the upgrade path for users who want to port to Cython 3.0 but cannot yet drop support for Python 2.7 on their side.

Support for Python 2.7 and Python < 3.4 (or < 3.5, TBD) will be removed in Cython 3.1. Both Cython 3.0 and 3.1 are expected to be released in the course of 2019.

**Comment by scoder** [comment]
Given that Py3.4 is now out of maintenance, and that the test suite takes excessively long to run in Py3.4, I strongly favour removing also the support for Py3.4 in Cython 3.1, which will then only target Py3.5 and later.

**Comment by robertwb** [comment]
+1

**Comment by wkschwartz** [comment]
+1 for nnouncing these plans/policies in developer documentation (perhaps a project roadmap). It would make it easier for new folk to contribute to the project. I suspect downstream projects would also appreciate knowing Cython's version support plans.

**Comment by auvipy** [comment]
I want to volunteer on this issue

**Comment by scoder** [comment]
I don't think it's something for right now. There will be more changes along the way for Cython 3.0, and Py2 support will only be removed afterwards. Better keep the risk of collisions low then.

**Comment by auvipy** [comment]
sure maybe after cython 3.0 release?

**Comment by scoder** [comment]
Update: we missed 2019, and will hardly make 2020 for the Cython 3.0/1 releases.

Since Python 3.5 is also officially out of maintenance now, I think it's best to remove all support for Python < 3.6 and only support the then maintained 3.[6789] in the Cython 3.1 release. [That means we can](https://docs.python.org/3/whatsnew/3.6.html) start using f-string formatting in our code base, rely on ordered dicts and on UTF-8 as Windows filesystem encoding, will no longer need backwards compatibility shims for async code and `typing`, … Oh, golden times… :)

**Comment by h-vetinari** [comment]
Python 3.6 has now [reached](https://www.python.org/dev/peps/pep-0494/#id14) EOL as well.

**Comment by 0dminnimda** [comment]
> `typing`, … Oh, golden times… :)

No need to say that we all want to have `typing` in cython sooo much!

**Comment by EwoutH** [comment]
This issue is now almost 4 years old, Python 2.7, 3.4 and 3.5 have been [end-of-life](https://endoflife.date/python) for a long time:

- Python 2.7: Security support ended 2 years and 10 months ago (01 Jan 2020)
- Python 3.4: Security support ended 3 years and 8 months ago (18 Mar 2019)
- Python 3.5: Security support ended 2 years ago (13 Sep 2020)

The last time the Python version requirement [was raised](https://github.com/cython/cython/commit/8c490265b8c2b23e8680068c9d18210e5f82c8e7) was 4 years ago, in november 2018. At that moment, Python 2.6 and 3.3 support was removed.

So would it be time to consider dropping Python 2.7, 3.4 and 3.5 already before the 3.0 release? I have no idea how far away it is, but the list of features missing out on is growing, the testing and CI matrices for minor version support keep growing and the percentage of users still using those versions is getting smaller.

Of course the 0.29.x release series can keep support. I think the intersection of users still using Python 2.7, 3.4 or 3.5 _and_ benefiting from the latest improvements of Cython 3.0 is quite small.

**Comment by h-vetinari** [comment]
@scoder just commented in #5130:
> We will remove Python 2.7 support in Cython 3.1. That's the main feature of that future release.

That plan hasn't changed for a long time, and it doesn't look like it will. Still, I understand the sentiment (of @EwoutH), not least because that plan was made when Cython 3 was still scheduled for 2019 - three years later, I think reality has overtaken the utility of keeping Python 2.7 support in Cython 3; with every passing month it is more and more just dead weight for an (almost) empty set of users.

At the same time, there are only 1-2 remaining blockers (with PRs +/- ready to be merged) for 3.0, so if an end is in sight, then of course it's better just to push it over the finish line as-is.

Sidenote: with adding CI for 3.12 alpha, Cython will support 10(!) separate python versions released over a span of ~15 years - a monumental feat. 🤯

**Comment by da-woods** [comment]
My view is:
* I think the plan of "release Cython 3 with Python " support, then drop it shortly afterwards" still makes sense now. Even if it was probably made with the expectation of Cython 3 being a little earlier.
* I don't hugely care about supporting Python 3.4/3.5 personally - I'm not quite sure who's using those. But I don't think they're causing us too much pain at the moment.

**Comment by auvipy** [comment]
on cython 3.0 there should be 2.7 + 3.6/3.7+ only. python 3.4 and 3.5 do not have much user. even if, they can use older versions.

**Comment by scoder** [comment]
Whatever the Python devs say about their support intentions, here are the PyPI download starts, averaged over the last month:
```
2.6 :         12.8 / day
2.7 :      36806.6 / day
2.8 :          1.0 / day
3.1 :          8.5 / day
3.2 :         15.5 / day
3.3 :          5.4 / day
3.4 :        133.7 / day
3.5 :       7317.9 / day
3.6 :      48094.7 / day
3.7 :     327190.8 / day
3.8 :     199755.2 / day
3.9 :      94715.5 / day
3.10:     131179.3 / day
3.11:       7568.3 / day
3.12:         53.6 / day
null:      13590.5 / day
```
Both 2.7 and 3.6 still seem rather relevant. Even 3.5 does not seem entirely negligible to me, even though it's probably small enough to let users stick with Cython < 3.0.

I think it's reasonable to keep support for Python 2.7 and 3.6+ in Cython 3.0.

**Comment by hugovk** [comment]
Here's how it's changed:

![cython](https://user-images.githubusercontent.com/1324225/202157603-0319d5da-b35b-4d7a-905e-b70362b4fea1.png)

For comparison, it's not that unusual when compared to other packages that have already dropped 2.7: 

* https://hugovk.github.io/pypi-tools/charts

The top downloaded package urllib3 had 4.91% downloads for Python 2.7 last month, and [are dropping 2.7 now](https://urllib3.readthedocs.io/en/stable/v2-roadmap.html#optimized-for-python-3-6) (the alpha just came out).

**Comment by EwoutH** [comment]
> Both 2.7 and 3.6 still seem rather relevant – dropping everything <= Py3.6 would cut off 11% of the daily downloads.

I would strongly argue to keep 3.6 in, even if it's end-of-life. It's a way more modern version than 2.7. So I would suggest keeping this discussion about dropping 3.5 and lower, which means dropping 2.7, 3.4 and 3.5. Moving to Python 3 allows to drop a large amount of redundant code, and 3.4 and 3.5 are not used that much. Also, Python 3.6 is the lowest version [cibuildwheel](https://github.com/pypa/cibuildwheel) supports.

That brings me to the following point again:

> Of course the 0.29.x release series can keep support. I think the intersection of users still using Python 2.7, 3.4 or 3.5 and benefiting from the latest improvements of Cython 3.0 is quite small.

I strongly believe that _intersection_ of users on very old Python versions like 2.7 expecting and using new cython features is very small. There is a very good case to be made for keeping legency support and bugfixes for such a important project as cython, but that's where the 0.29.x maintenance branch is for.

The second question is how close is the 3.0 release? If it's withing a few months, keeping 2.7 in for a tad longer doesn't have that much costs, but if it's more than 6 months away I would say let's drop it now to allow reduced testing, CI and maintenance efforts to speed up development.

**Comment by h-vetinari** [comment]
> @hugovk: For comparison, it's not that unusual when compared to other packages that have already dropped 2.7:

This is the key point IMO - even numpy, which dropped python 2.7 almost three years ago, still has ~3% downloads for 2.7. Those old machines are still running, but it's really unlikely that this is anything more than keeping the lights on - i.e. almost certainly no active development. 

Anyway, I'm keeping my fingers crossed for 3.0 soon (and have tried to help with reviewing the blocker PRs, to my limited ability at least), then the whole discussion becomes moot. 🙃

**Comment by scoder** [comment]
Looking back through the ticket communication, I noticed that we basically already [decided to remove Py3.5 support](https://github.com/cython/cython/issues/2800#issuecomment-703072864), also for Cython 3.0, and to make 2.7/3.6 the minimum versions. That was in 2020 and still feels ok to me now.

**Comment by scoder** [comment]
> I strongly believe that _intersection_ of users on very old Python versions like 2.7 expecting and using new cython features is very small.

I rather think that allowing users to still keep up support for Python 2.7, while writing their code for a modern Python 3.x, is a feature. Remember, Cython is a code development tool, not an end-user library. The constraints and needs that our users have can be very different from that of a library user, let alone that of an application developer.

To put an end to this discussion: we will keep Python 2.7 support in Cython 3.0, and remove it in Cython 3.1, as was always planned. As it stands, both will support Python 3.6, unless times change significantly before their releases.

I wouldn't actively remove Python 3.5 support for Cython 3.0 right now, unless we notice that it starts considerably getting in the way. We can still do that for Cython 3.1, while cleaning up the code base. As it stands, it works and does not get in the way, except for modern wheel building (which can be easily worked around by *adding* another, separate wheel building workflow that we can completely switch to in the future).

BTW, once Cython 3.1 is out, the Cython 3.0 branch will be the legacy stable branch in the same way that 0.29.x is now. It will be non-trivial to pick changes over any way, given that we'll often have to add some kind of Py2.7 support for them. So we can as well just clean up the master branch a little more after the, say, second 3.0.x branch release or so.

**Comment by scoder** [comment]
As @h-vetinari proposed in #5533, should we move directly to Py3.8+ with Cython 3.1? Sounds reasonable to me.

**Comment by auvipy** [comment]
> As @h-vetinari proposed in #5533, should we move directly to Py3.8+ with Cython 3.1? Sounds reasonable to me.

yeah thats sounds most reasonable the this time.

**Comment by scoder** [comment]
We still have support for Py3.7 included as it stands. We'll see if it gets in the way before the release. Apart from that, most of the legacy special cases have been removed in #5801, so this can be closed.

**Comment by scoder** [comment]
According to https://hugovk.github.io/pypi-tools/charts, Py3.7 still has a notable package download share, so it feels too early to drop support for it "just because we can".

**Comment by h-vetinari** [comment]
> According to https://hugovk.github.io/pypi-tools/charts, Py3.7 still has a notable package download share

The vast majority of these are existing deployments that will be recreated/rerun, but never be meaningfully changed, much less actively developed. Of course you're free to extend support as long as you want, but I think the actual number of Cython 3.1 users that are on Python 3.7 is close 0.

PS. https://mayeut.github.io/manylinux-timeline/ has some nice charts as well - in particular, there's a percentage of downloads for old python versions that ~never goes away (still ~10% of downloads on <3.7).

**Comment by scoder** [comment]
These are the latest download stats for Cython:
```
Downloads by Python version:
  null:      46512.0 / day (  4.2%)
  3.13:        176.4 / day (  4.2%)
  3.12:      10263.4 / day (  5.1%)
  3.11:     116934.0 / day ( 15.6%)
  3.10:     213042.1 / day ( 34.6%)
  3.9 :     142549.5 / day ( 47.4%)
  3.8 :     192228.1 / day ( 64.6%)
  3.7 :     334090.3 / day ( 94.5%)
  3.6 :      29232.3 / day ( 97.2%)
  3.5 :       3439.7 / day ( 97.5%)
  3.4 :         95.4 / day ( 97.5%)
  3.3 :         41.6 / day ( 97.5%)
  3.2 :          1.5 / day ( 97.5%)
  3.1 :          6.7 / day ( 97.5%)
  2.8 :          1.0 / day ( 97.5%)
  2.7 :      28092.6 / day (100.0%)
  2.6 :          4.9 / day (100.0%)

Downloads by system:
  null   :      54368.7 / day (  4.9%)
  other  :       5339.8 / day (  5.3%)
  Darwin :      23400.0 / day (  7.4%)
  Windows:      42169.4 / day ( 11.2%)
  Linux  :     991386.4 / day (100.0%)
Total downloads: 33,499,929.8
```

According to these, Py3.7 is substantially more important than Py3.8. I do buy the argument that most of the Py3.7 systems won't change any more, and I would also guess that they still use Cython 0.29.x. However, it seems strange to cut off a platform that is all by itself responsible for 30% of the daily downloads. That's 10x as much as Py3.6.

**Comment by auvipy** [comment]
I don't see any harm keeping python 3.7 for 3.1 release.

**Comment by astrojuanlu** [comment]
Would be good to have a breakdown of downloads by Cython _and_ Python version to better understand upgrade patterns.

**Comment by scoder** [comment]
It doesn't look like pypistats provides this information: https://pypistats.org/api/

Maybe someone with a Google account can grab the information from https://github.com/ofek/pypinfo ?
Should be something like

* `pypinfo -pc 'cython==3.*' pyversion version`
* `pypinfo -pc 'cython==0.29.*' pyversion version`

**Comment by hugovk** [comment]
```console
$ pypinfo -pc 'cython==3.*' pyversion version
Served from cache: False
Data processed: 1.92 GiB
Data billed: 1.92 GiB
Estimated cost: $0.01
```

| python_version | version | percent | download_count |
| -------------- | ------- | ------- | -------------- |
| 3.7            | 3.0.4   |  18.66% |      2,761,736 |
| 3.10           | 3.0.4   |  12.26% |      1,815,374 |
| 3.7            | 3.0.3   |  11.71% |      1,733,718 |
| 3.7            | 3.0.5   |  11.31% |      1,674,025 |
| 3.8            | 3.0.4   |   9.84% |      1,456,610 |
| 3.10           | 3.0.3   |   8.16% |      1,207,434 |
| 3.9            | 3.0.4   |   7.92% |      1,172,679 |
| 3.10           | 3.0.5   |   7.65% |      1,132,959 |
| 3.8            | 3.0.5   |   6.52% |        965,728 |
| 3.8            | 3.0.3   |   5.97% |        883,509 |
| Total          |         |         |     14,803,772 |

```console
$ pypinfo -pc 'cython==0.29.*' pyversion version
Served from cache: False
Data processed: 1.92 GiB
Data billed: 1.92 GiB
Estimated cost: $0.01
```

| python_version | version | percent | download_count |
| -------------- | ------- | ------- | -------------- |
| 3.7            | 0.29.36 |  23.49% |      2,544,440 |
| 3.10           | 0.29.36 |  13.34% |      1,444,466 |
| 3.8            | 0.29.36 |  12.95% |      1,402,314 |
| 3.11           | 0.29.36 |  12.07% |      1,307,858 |
| 3.9            | 0.29.36 |  12.07% |      1,307,292 |
| 3.7            | 0.29.21 |   8.74% |        946,779 |
| 3.7            | 0.29.24 |   6.00% |        649,679 |
| 3.8            | 0.29.21 |   4.43% |        480,357 |
| 3.12           | 0.29.36 |   4.13% |        447,372 |
| 3.6            | 0.29.36 |   2.78% |        300,721 |
| Total          |         |         |     10,831,278 |

**Comment by hugovk** [comment]
And like https://dev.to/hugovk/why-are-there-still-so-many-downloads-for-eol-python-37-30cp Amazon Linux is responsible for the biggest share of 3.7 downloads:

```console
$ pypinfo -pc --limit 20 'cython==3.*' system distro pyversion
Served from cache: False
Data processed: 2.81 GiB
Data billed: 2.81 GiB
Estimated cost: $0.02
```

| system_name | distro_name      | python_version | percent | download_count |
| ----------- | ---------------- | -------------- | ------- | -------------- |
| Linux       | Amazon Linux     | 3.7            |  27.34% |      4,783,214 |
| Linux       | Ubuntu           | 3.10           |  14.73% |      2,577,466 |
| Linux       | Ubuntu           | 3.8            |   9.66% |      1,689,913 |
| Linux       | Ubuntu           | 3.9            |   7.97% |      1,394,693 |
| Linux       | Debian GNU/Linux | 3.8            |   4.60% |        803,999 |
| Linux       | Debian GNU/Linux | 3.7            |   4.34% |        759,565 |
| Linux       | Debian GNU/Linux | 3.9            |   4.02% |        703,642 |
| Linux       | Amazon Linux     | 3.8            |   3.26% |        570,025 |
| Linux       | Debian GNU/Linux | 3.11           |   2.82% |        493,792 |
| Linux       | Ubuntu           | 3.11           |   2.76% |        482,969 |
| Windows     | None             | 3.10           |   2.74% |        479,561 |
| Linux       | Ubuntu           | 3.7            |   2.68% |        468,827 |
| Linux       | Debian GNU/Linux | 3.10           |   2.68% |        468,021 |
| Linux       | Debian GNU/Linux | 3.12           |   2.24% |        392,544 |
| Linux       | Alpine Linux     | 2.7            |   1.83% |        320,958 |
| Windows     | None             | 3.11           |   1.48% |        258,252 |
| Linux       | Amazon Linux     | 3.10           |   1.35% |        236,673 |
| Linux       | Alpine Linux     | 3.10           |   1.35% |        235,761 |
| Linux       | Alpine Linux     | 3.8            |   1.22% |        213,028 |
| Darwin      | macOS            | 3.9            |   0.93% |        162,506 |
| Total       |                  |                |         |     17,495,409 |


```console
$ pypinfo -pc --limit 20 'cython==0.29.*' system distro pyversion
Served from cache: False
Data processed: 2.81 GiB
Data billed: 2.81 GiB
Estimated cost: $0.02
```
| system_name | distro_name      | python_version | percent | download_count |
| ----------- | ---------------- | -------------- | ------- | -------------- |
| Linux       | Amazon Linux     | 3.7            |  31.04% |      3,491,782 |
| Linux       | Ubuntu           | 3.8            |   9.28% |      1,043,790 |
| Linux       | Ubuntu           | 3.10           |   8.09% |        909,750 |
| Linux       | Ubuntu           | 3.9            |   5.21% |        586,552 |
| Linux       | Ubuntu           | 3.7            |   4.93% |        554,398 |
| Linux       | Debian GNU/Linux | 3.8            |   4.67% |        525,616 |
| Linux       | Ubuntu           | 3.11           |   4.26% |        479,607 |
| Linux       | Debian GNU/Linux | 3.9            |   3.94% |        443,551 |
| Linux       | Alpine Linux     | 3.8            |   3.86% |        434,711 |
| Linux       | Debian GNU/Linux | 3.7            |   3.78% |        425,042 |
| Linux       | Alpine Linux     | 3.11           |   2.72% |        306,453 |
| Linux       | Alpine Linux     | 3.7            |   2.60% |        292,323 |
| Linux       | Amazon Linux     | 3.8            |   2.48% |        278,687 |
| Linux       | Debian GNU/Linux | 3.11           |   2.42% |        272,191 |
| Linux       | Alpine Linux     | 3.9            |   2.40% |        270,451 |
| Linux       | Amazon Linux     | 3.10           |   2.15% |        241,925 |
| Linux       | Debian GNU/Linux | 3.10           |   2.04% |        229,607 |
| Linux       | Debian GNU/Linux | 3.12           |   1.64% |        185,032 |
| Linux       | Alpine Linux     | 3.10           |   1.29% |        145,221 |
| Windows     | None             | 3.12           |   1.18% |        132,704 |
| Total       |                  |                |         |     11,249,393 |

**Comment by scoder** [comment]
Thanks, that's really helpful. It means that a substantial number of Cython 3.0.x downloads actually come from Py3.7 systems that [are still supported](https://dev.to/hugovk/why-are-there-still-so-many-downloads-for-eol-python-37-30cp#comment-28nk3) until mid 2025.

That suggests to me that we should *not* drop the support just now. We can probably do that in a later Cython 3.x release through gradual deprecation, say, in 3.2 or 3.3, but now seems too early.

**Comment by scoder** [comment]
Most Linux distributions that provide long term support for Python 3.7 have now reached their EOL. The only notable exception seems to be Amazon Linux 2, which will reach its EOL in a few months. Given that Cython 3.0.x exists and is fully functional, I think we can afford to exclude Py3.7 support from Cython 3.1.
