### ISSUE TITLE
"cdef struct foo: pass" should be valid syntax

### ISSUE THREAD

**Issue by jdemeyer** [cython/cython#2802]
It's a minor annoyance that this is not legal syntax for structs in `cdef extern` blocks which have no interesting attributes:
```
cdef struct foo: pass
```

**Comment by scoder** [comment]
I'm wondering, though: wouldn't a plain `cdef struct foo` (without `pass`) in a `cdef extern` block also be ok? Doesn't that work already?

**Comment by scoder** [comment]
Ah, I should have checked before. It's possible to do this:
```
cdef extern …:
    cdef struct astruct

    ... # use struct name already for other declarations

    cdef struct astruct:
        ...  # declare attributes here
```
and that shouldn't be counted as a redeclaration but only as a forward declaration. So, `pass` is needed then.
