### ISSUE TITLE
__cinit__ with parent class?

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#2809]
I have legacy code that I would like to update to use modern cython idioms, namely `__cinit__`.  `_Timestamp` is a cdef class that subclasses `datetime.datetime`.  The existing `__new__` method calls the parent class's `__new__` (and to make that work, we have to have a non-cdef Timestamp subclass where `__new__` is defined).

As far as I know `datetime.datetime` does not have a `__cinit__`.  What is the recommended way to implement a `__cinit__` method with a parent class?

**Comment by scoder** [comment]
Did you read the documentation?
http://docs.cython.org/en/latest/src/userguide/special_methods.html#initialisation-methods
Are you suggesting that this not covered there? This seems more of a support question than a bug.

**Comment by jbrockmendel** [comment]
I've read the docs many times, but there's always a chance I missed something.

There is a paragraph in the docs:

> If your extension type has a base type, the `__cinit__()` method of the base type is automatically called before your `__cinit__()` method is called [...]

but that seems to assume that the base type is itself a cython class, whereas in the relevant use case the parent class as defined [here](https://github.com/cython/cython/blob/master/Cython/Includes/cpython/datetime.pxd#L15) doesn't have a `__cinit__` method.

If you prefer, I can close this and re-ask on the mailing list.

**Comment by scoder** [comment]
I've extended that docs section a little. Let me know if that clarifies it.
