### ISSUE TITLE
Generator and implicit casting bug 

### ISSUE THREAD

**Issue by gtsystem** [cython/cython#2812]
I created a simple cpp class that hold a reference to a std:string

```cpp
#include <string>

namespace test {
    class Test {
        private:
            const std::string &m_string;

        public:
            Test(const std::string& s): m_string{s} {}
            const std::string get_string() { return m_string; }
    };
}
```

and I'm using it inside a cython generator as follow:
```cython
# distutils: language = c++
# cython: language_level=3str

from libcpp.string cimport string

cdef extern from "cpp_class.h" namespace "test":
    cdef cppclass Test:
        Test(string)
        string get_string()

def iter_test_implicit(bytes bb):
    cdef Test *t = new Test(bb)  # implicit bytes to std::string conversion here
    yield t.get_string()
    yield t.get_string()
    del t
```

If I iterate over `iter_test_implicit` from python I get:

```
b'test'
b''
```

I would expect it to print twice the test string, but the second yielded item returns an empty string. I assume that the referenced string get lost after the generator resume..
If I explicitly do the conversion from python bytes to std::string everything works fine:
```cython
def iter_test_explicit(bytes bb):
    cdef string st = bb    # explicit conversion here
    cdef Test *t = new Test(st)
    yield t.get_string()
    yield t.get_string()
    del t
```

and the output is as expected:
```
b'test'
b'test'
```

Full code [example.zip](https://github.com/cython/cython/files/2786551/example.zip)

**Comment by scoder** [comment]
You are storing the reference to a temporarily created C++ string object in the `Test` class that Cython created for you. That means that Cython owns it, and it deallocates it after use. In this case, it gets allocated on the C stack and cleaned up on the first yield.

By assigning it to an explicit local variable in your second example, it becomes part of the generator closure, which stays alive across yields. This is the right way to handle it.
