### ISSUE TITLE
Cython 0.29.3 : Building of documentation fails because sphinx.ext.pngmath is no longer deprecated, it does not exist

### ISSUE THREAD

**Issue by Corin-EU** [cython/cython#2818]
Python 3.4.3
Sphinx 1.8.3
Cython 0.29.3

cython/docs/conf.py still has on line 44 in the list of extensions: 'sphinx.ext.pngmath'

This has been deprecated for over 2 years, no longer exists for latest Sphinx 1.8.3. and has been replaced by sphinx.ext.imgmath

This causes building of documentation to fail with

     Running Sphinx v1.8.3

     Extension error:
     Could not import extension sphinx.ext.pngmath (exception: No module named 'sphinx.ext.pngmath')

Changing the conf.py entry to 'sphinx.ext.imgmath' cures the problem and the documentation in "man", "html", and "text" can now be built.  

(Former issue with text document building using python 2.7 + cython 0.25.2 + sphinx 1.5.5 previously reported issue  #1665  no longer occurs and so that issue is now closed.)

There are still numerous warnings though.

     -------------Building of Manual Pages ----------------
     PYTHONPATH="/usr/lib/python3.5:/usr/local/lib/python3.5/dist-packages:/usr/src/build/Cython-0.29.3/Cython:/usr/src/build/Cython-0.29.3/docs" \
_ make "man"
   sphinx-build -b man -d build/doctrees -D latex_paper_size=a4  . build/man
     Running Sphinx v1.8.3
     making output directory...
     WARNING: unknown config value 'latex_paper_size' in override, ignoring
     loading intersphinx inventory from https://docs.python.org/3/objects.inv...
     building [mo]: targets for 0 po files that are out of date
     building [man]: all manpages
     updating environment: 53 added, 0 changed, 0 removed
     reading sources... [100%] src/userguide/wrapping_CPlusPlus                                                                                                                                 
     ../CHANGES.rst:1143: WARNING: Inline emphasis start-string without end-string.
     /usr/src/build/Cython-0.29.3/docs/src/quickstart/install.rst:62: WARNING: duplicate citation Sage, other instance in /usr/src/build/Cython-0.29.3/docs/src/quickstart/build.rst
     /usr/src/build/Cython-0.29.3/docs/src/tutorial/related_work.rst:44: WARNING: duplicate citation Pyrex, other instance in /usr/src/build/Cython-0.29.3/docs/src/quickstart/overview.rst
     /usr/src/build/Cython-0.29.3/docs/src/userguide/extension_types.rst:853: WARNING: Unexpected indentation.
     /usr/src/build/Cython-0.29.3/docs/src/userguide/memoryviews.rst:19: WARNING: Unknown target name: "pep 3118".
     /usr/src/build/Cython-0.29.3/docs/src/userguide/memoryviews.rst:227: WARNING: Unknown target name: "new style buffers".
     /usr/src/build/Cython-0.29.3/docs/src/userguide/memoryviews.rst:227: WARNING: Unknown target name: "pep 3118".
     looking for now-outdated files... none found
     pickling environment... done
     checking consistency... /usr/src/build/Cython-0.29.3/docs/CONTRIBUTING.rst: WARNING: document isn't included in any toctree
     /usr/src/build/Cython-0.29.3/docs/examples/README.rst: WARNING: document isn't included in any toctree
     /usr/src/build/Cython-0.29.3/docs/src/reference/directives.rst: WARNING: document isn't included in any toctree
     /usr/src/build/Cython-0.29.3/docs/src/reference/extension_types.rst: WARNING: document isn't included in any toctree
     /usr/src/build/Cython-0.29.3/docs/src/reference/index.rst: WARNING: document isn't included in any toctree
     /usr/src/build/Cython-0.29.3/docs/src/reference/interfacing_with_other_code.rst: WARNING: document isn't included in any toctree
     /usr/src/build/Cython-0.29.3/docs/src/reference/language_basics.rst: WARNING: document isn't included in any toctree
     /usr/src/build/Cython-0.29.3/docs/src/reference/limitations.rst: WARNING: document isn't included in any toctree
     /usr/src/build/Cython-0.29.3/docs/src/reference/special_mention.rst: WARNING: document isn't included in any toctree
     /usr/src/build/Cython-0.29.3/docs/src/quickstart/overview.rst:46: WARNING: Citation [Cython] is not referenced.
     d   writing... cython.1 { src/quickstart/index src/quickstart/overview src/quickstart/install src/quickstart/build src/quickstart/cythonize src/tutorial/index src/tutorial/cython_tutorial src/tutorial/external src/tutorial/clibraries src/tutorial/cdef_classes src/tutorial/pxd_files src/tutorial/caveats src/tutorial/profiling_tutorial src/tutorial/strings src/tutorial/memory_allocation src/tutorial/pure src/tutorial/numpy src/tutorial/array src/tutorial/readings src/tutorial/related_work src/tutorial/appendix src/userguide/index src/userguide/language_basics src/userguide/extension_types src/userguide/special_methods src/userguide/sharing_declarations src/userguide/external_C_code src/userguide/source_files_and_compilation src/userguide/early_binding_for_speed src/userguide/wrapping_CPlusPlus src/userguide/fusedtypes src/userguide/pypy src/userguide/limitations src/userguide/pyrex_differences src/userguide/memoryviews src/userguide/buffer src/userguide/parallelism src/userguide/debugging src/userguide/numpy_tutorial src/userguide/numpy_pythran src/changes } /usr/src/build/Cython-0.29.3/docs/src/userguide/language_basics.rst:245: WARNING: unknown keyword: None
     /usr/src/build/Cython-0.29.3/docs/src/userguide/language_basics.rst:245: WARNING: unknown keyword: False
     /usr/src/build/Cython-0.29.3/docs/src/userguide/language_basics.rst:245: WARNING: unknown keyword: NULL
     /usr/src/build/Cython-0.29.3/docs/src/userguide/special_methods.rst:14: WARNING: unknown keyword: cdef class
 
     build succeeded, 22 warnings.
 
     The manual pages are in build/man.
 
     Build finished. The manual pages are in build/man.

     -------------Building of HTML documentation ----------------
      PYTHONPATH="/usr/lib/python3.5:/usr/local/lib/python3.5/dist-packages:/usr/src/build/Cython-0.29.3/Cython:/usr/src/build/Cython-0.29.3/docs" make "html"
     sphinx-build -b html -d build/doctrees -D latex_paper_size=a4  . build/html
     Running Sphinx v1.8.3
     making output directory...
     WARNING: unknown config value 'latex_paper_size' in override, ignoring
     loading pickled environment... done
     building [mo]: targets for 0 po files that are out of date
     building [html]: targets for 53 source files that are out of date
     updating environment: 0 added, 0 changed, 0 removed
     looking for now-outdated files... none found
     preparing documents... done
     writing output... [100%] src/userguide/wrapping_CPlusPlus                                                                                                                                  
     /usr/src/build/Cython-0.29.3/docs/src/userguide/language_basics.rst:245: WARNING: unknown keyword: None
     /usr/src/build/Cython-0.29.3/docs/src/userguide/language_basics.rst:245: WARNING: unknown keyword: False
     /usr/src/build/Cython-0.29.3/docs/src/userguide/language_basics.rst:245: WARNING: unknown keyword: NULL
     /usr/src/build/Cython-0.29.3/docs/src/userguide/special_methods.rst:14: WARNING: unknown keyword: cdef class
     generating indices...
     writing additional pages... search
     copying images... [100%] src/tutorial/python_division.png                                                                                                                                  
     copying static files... done
     copying extra files... done
     dumping search index in English (code: en) ... done
     dumping object inventory... done
     build succeeded, 5 warnings.
 
     The HTML pages are in build/html.
     Build finished. The HTML pages are in build/html.

     -------------Building of plain text documentation ----------------
     PYTHONPATH="/usr/lib/python3.5:/usr/local/lib/python3.5/dist-packages:/usr/src/build/Cython-0.29.3/Cython:/usr/src/build/Cython-0.29.3/docs" make "text"
     sphinx-build -b text -d build/doctrees -D latex_paper_size=a4  . build/text
     Running Sphinx v1.8.3
     making output directory...
     WARNING: unknown config value 'latex_paper_size' in override, ignoring
     loading pickled environment... done
     building [mo]: targets for 0 po files that are out of date
     building [text]: targets for 53 source files that are out of date
     updating environment: 0 added, 0 changed, 0 removed
     looking for now-outdated files... none found
     preparing documents... done
     writing output... [100%] src/userguide/wrapping_CPlusPlus                                                                                                                                  
     /usr/src/build/Cython-0.29.3/docs/src/userguide/language_basics.rst:245: WARNING: unknown keyword: None
     /usr/src/build/Cython-0.29.3/docs/src/userguide/language_basics.rst:245: WARNING: unknown keyword: False
     /usr/src/build/Cython-0.29.3/docs/src/userguide/language_basics.rst:245: WARNING: unknown keyword: NULL
     /usr/src/build/Cython-0.29.3/docs/src/userguide/special_methods.rst:14: WARNING: unknown keyword: cdef class
     build succeeded, 5 warnings.

     The text files are in build/text.

     Build finished. The text files are in build/text.

**Comment by scoder** [comment]
Thanks. I resolved the `pngmath` issue. PR to fix the warnings is welcome.

**Comment by scoder** [comment]
Closing, since the actual issue is solved.
