### ISSUE TITLE
Parallelism during Cython compilation of third party projects

### ISSUE THREAD

**Issue by mzpqnxow** [cython/cython#2841]
Is there any easy way to parallelize Cython compilation? I have a system with 192CPUs and 1TB RAM but it still takes ~7m to build Pandas (even with ccache)

I opened an issue with Pandas and the devs pointed to Cython, though there wasn’t any certainty that anything could be done to improve the situation within Cython.

Is there any easy way to cause a third party project to Cythonize in parallel? Is this even a Cython issue?

Thanks, I apologize if this isn’t a Cython issue, or is one that just can’t be trivially addresses by Cython devs. I’ve not had much opportunity to work with Cython which I hope explains my lack of direction in trying to chase this down.

I did modify the Pandas setup.py to utilize ‘nthreads’ but I’m looking more for something like ‘make -j’ behavior- it seems ‘nthreads’ only optimizes for one file at a time, whereas I’m looking for multiple files being compiled simultaneously

I’m wondering if the logic in each third party project would need to be rewritten to look more like this: https://github.com/cython/cython/blob/master/Tools/cystdlib.py

**Comment by mzpqnxow** [comment]
Oh and just to be clear- I’m not talking about runtime parallelism, the GIL, etc.. I’m purely talking about the process of Cythonizing code that utilizes Cython, which as I u sweatband it takes place at build/install time of the third party project.

And I understand it’s not for Cython devs to PR to third parties if such functionality exists- I’m happy to do that myself.

**Comment by scoder** [comment]
In Python 3.4(or 3.5?) and later, you can use something like `python setup.py build_ext -j20` to run 20 parallel build jobs for the extension module builds. Then normally building the whole package afterwards should reuse the already compiled extensions.

Other than that, yes, passing `nthreads` to `cythonize()` will also parallelise the code generation of Cython, although that is usually dominated by the C compilation time. Both options together should get you pretty far.

**Comment by mzpqnxow** [comment]
Fair enough, I think for my usage (Python 2.7, deploying via virtualenv/requirements.txt) there's probably not much I can do without forking cython and making the build use a process pool. Thank you for the help, I will close this out now

**Comment by robertwb** [comment]
You shouldn't have to fork Cython, as cythonize(..., nthreads=N) already uses a process pool to compile multiple files in parallel. Different logic is needed to get setuptools to do the C compilation in parallel (for older version of Python).
