### ISSUE TITLE
Optimise append/pop for non-lists

### ISSUE THREAD

**Issue by scoder** [cython/cython#2850]
Found through CPython's [micro benchmark script](https://github.com/python/cpython/blob/master/Tools/scripts/var_access_benchmark.py): 

With all `CYTHON_*` optimisation macros enabled (default):
```
  20.7 ns       list_append_pop
 155.4 ns       deque_append_pop
```
When disabled:
```
  66.4 ns       list_append_pop
  75.1 ns       deque_append_pop
```
For non-lists, this is slow even when compared to CPython 3.8:
```
  61.6 ns       list_append_pop
  53.9 ns       deque_append_pop
```

**Comment by scoder** [comment]
Fixed by avoiding the tuple packing and method calls:
```
  20.0 ns       list_append_pop
  45.5 ns       deque_append_pop
```

**Comment by jdemeyer** [comment]
This is not safe: #2996
