### ISSUE TITLE
Cython fails to build on Travis CI due to pyzmq upgrade

### ISSUE THREAD

**Issue by jdemeyer** [cython/cython#2853]
It seems that today's `pyzmq` upgrade has broken Travis CI. See for example https://travis-ci.org/cython/cython/jobs/495437648 (from the PR updating the documentation).

**Comment by scoder** [comment]
Hmm, this is annoying. Travis seems to have an older zmq version installed.
```
  Bad libzmq version: Detected ZMQ version: 2.2.0, but require ZMQ >= 3.2
      Explicitly allow legacy zmq by specifying `--zmq=/zmq/prefix`
```
I tried pinning pyzmq to <18 (the latest version released today), but that only helped a bit and there are still failing nodes. All travis nodes have the same libzmq version installed, 2.2.0. No idea why some of them would fail and others not.

**Comment by scoder** [comment]
Ok, I think I fixed it by _not_ installing `libzmq` but using the embedded one that `pyzmq` ships with. See 4927e0e949e6b041f521958c3a875343aca30ac6.

**Comment by scoder** [comment]
I take that back. The embedded libzmq needs to be activated via `setup.py` build option (which, in pip, disables all wheel installations), and takes ages to build. Not an option. I'll revert it to see if it's a temporary problem or what else can be done.

**Comment by scoder** [comment]
The problem was that the latest `pyzmq` versions don't provide wheels for Py3.4 anymore. I pinned the version to one that has them.
