### ISSUE TITLE
Cosider adding an option to show the cythonized code in ipython-magic

### ISSUE THREAD

**Issue by realead** [cython/cython#2855]
When prototyping with IPython there is one reason I often switch to compiling the cython extension on the command line: to see the whole cythonized code. While `--anotate` is great to spot issues it is not enough to see what is really going on.

Please consider adding an option to show also the whole cythonized code.

**Comment by scoder** [comment]
Ok, but wouldn't this just flood your notebook with tons of hard to read C gibberish? If there is anything to improve in the `-a` output, I'd rather see that done.

**Comment by realead** [comment]
I must confess, that with my proposed solution I miss code-highlightning from time to time...

When using annotate from the command-line one has a link to the generated c-file, but this link is missing in IPython.

What about adding an new "+"-section at the and of the annotate-output, so one can click on it and see the  whole C-code?
