### ISSUE TITLE
implement PEP-563: annotations as strings

### ISSUE THREAD

**Issue by scoder** [cython/cython#2863]
I think Cython 3.0 would also be a good time to implement [PEP-563](
https://www.python.org/dev/peps/pep-0563/) ("Postponed Evaluation of Annotations"). There already is a Cython code generator in `Cython.CodeWriter` that can be used to generate the expression string. This should be done somewhat late in the compiler pipeline since some optimisations can make use of the annotation information. It might be worth creating a separate transformation before the code generation.

What needs to be done:
- Implement a new transform `class SerialiseAnnotations(VisitorTransform)` in `ParseTreeTransforms.py`.
- Give it visitor methods for all nodes that can have annotations (any `ExprNode`, and anything that has an `annotation` attribute in `Nodes.py`).
- If the node has an annotation, serialise it using the code writer and replace the existing `node.annotation` with a `StringNode' (or `UnicodeNode` ?) that wraps the string value.
- Add the new transform to the pipeline in `Pipeline.py`, rather late, before the final checks.
- Extend the existing annotation related tests in `tests/run/` to cover the annotation string value. Add new tests for expressions that are not covered yet.

**Comment by nihilist-banana** [comment]
Hi, I would like to work on this. Can someone point me to some resources?

**Comment by scoder** [comment]
@nihilist-banana, there is a description of the implementation steps in the ticket, and the [HackerGuide](https://github.com/cython/cython/wiki/HackerGuide) has some general information about how to get started. Does this help already, or otherwise, could you maybe ask on the `cython-devel` mailing list if you need more specific guidance?

**Comment by nihilist-banana** [comment]
Thanks, @scoder. I'll look into this for now.

**Comment by guilhermeleobas** [comment]
Hi @nihilist-banana, are you still working on this? If not, I'd be happy to work on it.

**Comment by scoder** [comment]
Any help is appreciated.

**Comment by guilhermeleobas** [comment]
I will work on this as soon as I have some cycles to spare.

**Comment by da-woods** [comment]
This was done in https://github.com/cython/cython/pull/3284 (so issue can be closed I think)

**Comment by scoder** [comment]
Thanks for the reminder.

**Comment by scoder** [comment]
Just FYI, the Python Steering Council [has just decided](https://mail.python.org/archives/list/python-committers@python.org/thread/CLVXXPQ2T2LQ5MP2Y53VVQFCXYWQJHKZ/) that the final incarnation of PEP 536 becoming the default behaviour will be postponed and not be released as part of Python 3.10.

I don't see any immediate impact on Cython, though. The change in behaviour is still meant to come in CPython, just in 3.11 (as it stands). Let's keep things on our side as they are, at least for now.

**Comment by da-woods** [comment]
If I remember correctly, the first version of the PR had postponed evaluation as a switchable option. It worked, but I think I ditched it because it seemed like a lot of pointless complexity (evaluating annotation in the right scope was fiddly). But the relevant code will still exist somewhere on github and can be dug up if needed.

But not right now...
