### ISSUE TITLE
Cython 0.29.5 + gcc 8.2.1 broken completely

### ISSUE THREAD

**Issue by Time0o** [cython/cython#2865]
I'm trying to compile the hello world example from the [basic tutorial](https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html) using the versions of cython (installad inside an anaconda venv) and gcc (system install, on Arch Linux) mentioned in the title. Starting the interpreter and running `shutil.which('gcc')` gives me `/usr/bin/gcc` as expected. Yet, when running `python setup.py build_ext --inplace` I receive the following error:

```running build_ext
building 'helloworld' extension
gcc -pthread -B /home/timo/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/timo/anaconda3/include/python3.6m -c helloworld.c -o build/temp.linux-x86_64-3.6/helloworld.o
gcc -pthread -shared -B /home/timo/anaconda3/compiler_compat -L/home/timo/anaconda3/lib -Wl,-rpath=/home/timo/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/helloworld.o -o /home/timo/.../helloworld.cpython-36m-x86_64-linux-gnu.so
/home/timo/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.6/helloworld.o: unable to initialize decompress status for section .debug_info
/home/timo/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.6/helloworld.o: unable to initialize decompress status for section .debug_info
/home/timo/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.6/helloworld.o: unable to initialize decompress status for section .debug_info
/home/timo/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.6/helloworld.o: unable to initialize decompress status for section .debug_info
build/temp.linux-x86_64-3.6/helloworld.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```

This looks similar to the following [bug report](https://bugs.archlinux.org/task/61151) which has supposedly been fixed. What's happening here? Can someone reproduce this?

I have binutils 2.31.1-4, libelf/elfutils 0.175-1 installed if that helps

**Comment by Time0o** [comment]
Okay, after further research this seems to be a problem with `libelf 0.175-1` which pops up in other situations as well. One workaround I have found is to exclude debug symbols during compilation. Cython does not seem to provide a straightfoward way to do this (which is a very weird design choice if true) but this seems to work (caveat is that binary ends up in the cwd):

```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext

setup(
    ext_modules = [
        Extension('helloworld',
                  sources=['helloworld.pyx'],
                  extra_compile_args=['-g0'])
    ],
    cmdclass = {'build_ext': build_ext}
)
```

So if anyone else has this problem that's what I would suggest other then downgrading `libelf` or waiting for a fix.

**Comment by scoder** [comment]
> Cython does not seem to provide a straightfoward way to do this (which is a very weird design choice if true)

It's actually the obvious choice, because Cython has nothing to do with the configuration of your C compiler. That is the responsibility of `distutils`. There is a convenience feature, though, that allows you to set `distutils` options for the extension. You could also use that here.
