### ISSUE TITLE
0.29.6 missing on PyPI

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [cython/cython#2867]

**Comment by scoder** [comment]
Well, yes, just like 3.0, 3.1 and all other future releases. ;-)
It'll be on PyPI as soon as the release is prepared.

**Comment by kaeptmblaubaer1000** [comment]
There are no "3.0" or "3.1" tags, while a "0.29.6" tag exists in this repository.

**Comment by scoder** [comment]
Release _preparations_ commonly involve setting a tag, yes. :)

Seriously, though, it's not unheard of that releases can sometimes take a couple of hours, days or even weeks after tagging/branching/whatever before they are made public. That's often called "quality assurance", or sometimes also "real life". If you file a ticket for that, then someone has to look at it and take the time to close it, which is annoying.

**Comment by kaeptmblaubaer1000** [comment]
Ok, I won't create such tickets anymore
