### ISSUE TITLE
DistutilsPlatformError: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by GavinMoreYoung** [cython/cython#2870]
#### Version
python : 3.6.8
cython : 0.29.6
#### code
%load_ext Cython
%%cython -a
import random  
def average_cy1(int n):  
    cdef int i  
    cdef float s = 0  
    for i in range(n):
        s += random.random()
    return s / n
#### error information
DistutilsPlatformError                    Traceback (most recent call last)
<ipython-input-3-ddcd257563cc> in <module>
----> 1 get_ipython().run_cell_magic('cython', '-a', 'import random  \ndef average_cy1(int n):  \n    cdef int i  \n    cdef float s = 0  \n    for i in range(n):\n        s += random.random()\n    return s / n\n')

c:\users\admin\.virtualenvs\python_for_finance_mastering_data_driven_f-hf8uuk7i\lib\site-packages\IPython\core\interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2345                 magic_arg_s = self.var_expand(line, stack_depth)
   2346             with self.builtin_trap:
-> 2347                 result = fn(magic_arg_s, cell)
   2348             return result
   2349 

<c:\users\admin\.virtualenvs\python_for_finance_mastering_data_driven_f-hf8uuk7i\lib\site-packages\decorator.py:decorator-gen-129> in cython(self, line, cell)

c:\users\admin\.virtualenvs\python_for_finance_mastering_data_driven_f-hf8uuk7i\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

c:\users\admin\.virtualenvs\python_for_finance_mastering_data_driven_f-hf8uuk7i\lib\site-packages\Cython\Build\IpythonMagic.py in cython(self, line, cell)
    331 
    332         self._build_extension(extension, lib_dir, pgo_step_name='use' if args.pgo else None,
--> 333                               quiet=args.quiet)
    334 
    335         module = imp.load_dynamic(module_name, module_path)

c:\users\admin\.virtualenvs\python_for_finance_mastering_data_driven_f-hf8uuk7i\lib\site-packages\Cython\Build\IpythonMagic.py in _build_extension(self, extension, lib_dir, temp_dir, pgo_step_name, quiet)
    441             if not quiet:
    442                 old_threshold = distutils.log.set_threshold(distutils.log.DEBUG)
--> 443             build_extension.run()
    444         finally:
    445             if not quiet and old_threshold is not None:

d:\python\Lib\distutils\command\build_ext.py in run(self)
    337 
    338         # Now actually compile and link everything.
--> 339         self.build_extensions()
    340 
    341     def check_extensions_list(self, extensions):

d:\python\Lib\distutils\command\build_ext.py in build_extensions(self)
    446             self._build_extensions_parallel()
    447         else:
--> 448             self._build_extensions_serial()
    449 
    450     def _build_extensions_parallel(self):

d:\python\Lib\distutils\command\build_ext.py in _build_extensions_serial(self)
    471         for ext in self.extensions:
    472             with self._filter_build_errors(ext):
--> 473                 self.build_extension(ext)
    474 
    475     @contextlib.contextmanager

d:\python\Lib\distutils\command\build_ext.py in build_extension(self, ext)
    531                                          debug=self.debug,
    532                                          extra_postargs=extra_args,
--> 533                                          depends=ext.depends)
    534 
    535         # XXX outdated variable, kept here in case third-part code

d:\python\Lib\distutils\_msvccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    343 
    344         if not self.initialized:
--> 345             self.initialize()
    346         compile_info = self._setup_compile(output_dir, macros, include_dirs,
    347                                            sources, depends, extra_postargs)

d:\python\Lib\distutils\_msvccompiler.py in initialize(self, plat_name)
    236         plat_spec = PLAT_TO_VCVARS[plat_name]
    237 
--> 238         vc_env = _get_vc_env(plat_spec)
    239         if not vc_env:
    240             raise DistutilsPlatformError("Unable to find a compatible "

d:\python\Lib\distutils\_msvccompiler.py in _get_vc_env(plat_spec)
    132     vcvarsall, vcruntime = _find_vcvarsall(plat_spec)
    133     if not vcvarsall:
--> 134         raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    135 
    136     try:

DistutilsPlatformError: Unable to find vcvarsall.bat

I do not know how to solve this issue, i need your help.

**Comment by scoder** [comment]
https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

**Comment by flutefreak7** [comment]
Note there is a bug with Python 3.7 right now related to this that the wiki doesn't help with:

https://bugs.python.org/issue35699
