### ISSUE TITLE
Wrong output from power function

### ISSUE THREAD

**Issue by CyanideCN** [cython/cython#2880]
I recently found that the power function erroneously returns 1 when dealing with non-integer power. When I tried to see this bug in detail, I found that the returned values are corrent when the non-integer power is given in decimal form, but when the power is given in fraction, the returned value is always 1.

code to produce:
`test.pyx`:
```
def test_power_1(double num):
    return num ** (1 / 2)

def test_power_2(double num):
    return num ** 0.5
```
The function `test_power_1` returns wrong value but `test_power_2` works.

Python version: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Cython version: 0.29.6

**Comment by scoder** [comment]
Did you set ``language_level=3`` (or ``3str``), or else import ``__future__.division`` ?

**Comment by CyanideCN** [comment]
That works, thanks!
