### ISSUE TITLE
args assigned value like kwarg results in TypeError: takes no keyword arguments

### ISSUE THREAD

**Issue by willjp** [cython/cython#2881]
I'm not certain if this is considered a bug, or if this behaviour is simply not intended.

cython:      `0.29.2`
python:     `2.7.11`
compiler:  `visualstudio-14.0`
compiled arch:          `amd64_86`

``` python

def my_function(a):
    pass

my_function(a=1)
```

results in
``` 
TypeError: my_function() takes no keyword arguments
```

If this behaviour is abnormal, please let me know and I'll try some other python/cython versions and report back success/fail.
Thanks very much for the wonderful tool!

**Comment by scoder** [comment]
It's an optimisation. If you want to accept keywords for single argument functions, use the `always_allow_keywords` directive.
http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives

**Comment by willjp** [comment]
thank you very much!
