### ISSUE TITLE
Equality comparison incorrectly returns true (sometimes)

### ISSUE THREAD

**Issue by lzkelley** [cython/cython#2888]
**Background:**

I have a np.ndarray of uint64, `ids`, shaped (N, 2), which I pass from python to a function in a cython file.  The cython function compares the second element of each row of this array (i.e. `ids[:, 1]`) to all future rows to find repeat entries.  At times, this is returning an incorrect value.

Trimmed down version:

-----------

**Problem:**

```
ctypedef unsigned long long ULNG

def build_tree(np.ndarray[ULNG, ndim=2] ids, np.ndarray[long,   ndim=1] next):
    cdef long num_mergers = ids.shape[0]

    for ii in range(num_mergers):
        outid = ids[last_ind, 1]
        jj = ii + 1
        while (jj < num_mergers):
            for kk in [0, 1]:
                if (ids[jj, kk] == outid):    # [*]
                    next[ii] = jj
```

At a particular row, the equality test (`[*]`) returns true despite the values being different.  I've added a print statement `print(ii, ids[jj, kk], outid, ids[jj, kk] == outid)`, at the offending entry, which gives,

```
193 9223372036551552872 9223372036551553059 True
```

---------------

**Other info**

I'm exploring this in a jupyter notebook (calls a method that calls the cython method, compiled used `pyximport`), and **after ~6 kernel restarts (and re-compiles), it finally worked properly**, I think without any changes to the operating code.

I assumed it was some sort of type error, so inside the cython method, I also printed out the `type()` result for these values and they both return `int` (instead of anything about an `unsigned long long`), but I'm guessing that's because of a python-function vs. cython issue?

**Comment by scoder** [comment]
> I'm exploring this in a jupyter notebook

Note that notebooks are particularly bad at guaranteeing that the code that runs and the data it processes really comes from the code that the cells show. The fact that you are additionally using `pyximport` makes this even worse, IMHO.


I'll close this is probably not reproducible.
