### ISSUE TITLE
Baffling output behavior

### ISSUE THREAD

**Issue by JesseRMeyer** [cython/cython#2895]
Consider the following code for a simple arena memory allocator. I allocate some memory, and I sweep through it to check if any non-0 values exist. What I ended up discovering is something of a mystery. The value in memory at location 0 from the allocation appears to change in between accesses without any modifications taking place. I'm reporting it here in case it reveals an issue with Cython. I did gander over the .c file, and it appears sensible. But the results just simply are not. If I switch to calloc, there is no problem. 

No threads or anything obvious that would otherwise be a smoking gun. 

The memory struct is a simple POD, and I just fill it in immediately.

`

	cdef memory result
	result.max_size = 100000 * 4096
	result.base = <unsigned char *>malloc(result.max_size * sizeof(char)) 
	result.used = 0

	cdef size_t i = 0
	printf("i = %zu \n", i)
	printf("result base at loc 0: %u \n", result.base[0])
	printf("result base at loc i: %u \n", result.base[i])

	cdef:
		unsigned char res = 0
		size_t good_memory_cells = 0

	for i in range(result.max_size):
		res = result.base[i]
		if res == 0:
			good_memory_cells += 1
		else:
			printf("i = %zu \n", i)
			printf("result base at loc 0: %u \n", result.base[0])
			printf("result base at loc i: %u \n", result.base[i])
			printf("result res: %u \n", res)
			printf("non-zero memory!!! %u and %u at index %zu \n", res, result.base[i], i)`

Below, you'll see that the last printf reports that res != result.base[i] which, semantically should be impossible.

> i = 0 
> result base at loc 0: 0 
> result base at loc i: 0 
> i = 0 
> result base at loc 0: 0 
> result base at loc i: 0 
> result res: 25 
> non-zero memory!!! 25 and 0 at index 0 

How can res not possibly equal result.base[i] when i has not changed between accesses?

My file settings are #cython: language_level=3, boundscheck=False, wraparound=False, initializedcheck=False, nonecheck=False, cdivision=True

OSX 10.13.6, Python 3.6.6, Cython 0.29.6 

Here's the transpiled C code:

`   static struct __pyx_t_4test_memory __pyx_f_4test_memory_allocate(void) {
        struct __pyx_t_4test_memory __pyx_v_result;
        size_t __pyx_v_i;
        unsigned char __pyx_v_res;
        size_t __pyx_v_good_memory_cells;
        struct __pyx_t_4test_memory __pyx_r;
        size_t __pyx_t_1;
        size_t __pyx_t_2;
        size_t __pyx_t_3;
        int __pyx_t_4;

      /* "test_comp.pyx":99
     * 	cdef memory result
     * 
     * 	result.max_size = 100000 * 4096 #TODO(Jesse): Figure out a real upper bound. Basically just grab 100k pages.             # <<<<<<<<<<<<<<
     * 	result.base = <unsigned char *>malloc(result.max_size * sizeof(char)) #NOTE(Jesse): Because we only alloc _once_, we are certain the OS will hand us 0'd memory. No need to calloc.
     * 	result.used = 0
     */
      __pyx_v_result.max_size = 0x186A0000;

      /* "test_comp.pyx":100
     * 
     * 	result.max_size = 100000 * 4096 #TODO(Jesse): Figure out a real upper bound. Basically just grab 100k pages.
     * 	result.base = <unsigned char *>malloc(result.max_size * sizeof(char)) #NOTE(Jesse): Because we only alloc _once_, we are certain the OS will hand us 0'd memory. No need to calloc.             # <<<<<<<<<<<<<<
     * 	result.used = 0
     * 
     */
      __pyx_v_result.base = ((unsigned char *)malloc((__pyx_v_result.max_size * (sizeof(char)))));

      /* "test_comp.pyx":101
     * 	result.max_size = 100000 * 4096 #TODO(Jesse): Figure out a real upper bound. Basically just grab 100k pages.
     * 	result.base = <unsigned char *>malloc(result.max_size * sizeof(char)) #NOTE(Jesse): Because we only alloc _once_, we are certain the OS will hand us 0'd memory. No need to calloc.
     * 	result.used = 0             # <<<<<<<<<<<<<<
     * 
     * 	cdef size_t i = 0
     */
      __pyx_v_result.used = 0;

      /* "test_comp.pyx":103
     * 	result.used = 0
     * 
     * 	cdef size_t i = 0             # <<<<<<<<<<<<<<
     * 	printf("i = %zu \n", i)
     * 	printf("result base at loc 0: %u \n", result.base[0])
     */
      __pyx_v_i = 0;

      /* "test_comp.pyx":104
     * 
     * 	cdef size_t i = 0
     * 	printf("i = %zu \n", i)             # <<<<<<<<<<<<<<
     * 	printf("result base at loc 0: %u \n", result.base[0])
     * 	printf("result base at loc i: %u \n", result.base[i])
     */
      (void)(printf(((char const *)"i = %zu \n"), __pyx_v_i));

      /* "test_comp.pyx":105
     * 	cdef size_t i = 0
     * 	printf("i = %zu \n", i)
     * 	printf("result base at loc 0: %u \n", result.base[0])             # <<<<<<<<<<<<<<
     * 	printf("result base at loc i: %u \n", result.base[i])
     * 
     */
      (void)(printf(((char const *)"result base at loc 0: %u \n"), (__pyx_v_result.base[0])));

      /* "test_comp.pyx":106
     * 	printf("i = %zu \n", i)
     * 	printf("result base at loc 0: %u \n", result.base[0])
     * 	printf("result base at loc i: %u \n", result.base[i])             # <<<<<<<<<<<<<<
     * 
     * 	cdef:
     */
      (void)(printf(((char const *)"result base at loc i: %u \n"), (__pyx_v_result.base[__pyx_v_i])));

      /* "test_comp.pyx":109
     * 
     * 	cdef:
     * 		unsigned char res = 0             # <<<<<<<<<<<<<<
     * 		size_t good_memory_cells = 0
     * 
     */
      __pyx_v_res = 0;

      /* "test_comp.pyx":110
     * 	cdef:
     * 		unsigned char res = 0
     * 		size_t good_memory_cells = 0             # <<<<<<<<<<<<<<
     * 
     * 	for i in range(result.max_size):
     */
      __pyx_v_good_memory_cells = 0;

      /* "test_comp.pyx":112
     * 		size_t good_memory_cells = 0
     * 
     * 	for i in range(result.max_size):             # <<<<<<<<<<<<<<
     * 		res = result.base[i]
     * 		if res == 0:
     */
      __pyx_t_1 = __pyx_v_result.max_size;
      __pyx_t_2 = __pyx_t_1;
      for (__pyx_t_3 = 0; __pyx_t_3 < __pyx_t_2; __pyx_t_3+=1) {
        __pyx_v_i = __pyx_t_3;

        /* "test_comp.pyx":113
     * 
     * 	for i in range(result.max_size):
     * 		res = result.base[i]             # <<<<<<<<<<<<<<
     * 		if res == 0:
     * 			good_memory_cells += 1
     */
        __pyx_v_res = (__pyx_v_result.base[__pyx_v_i]);

        /* "test_comp.pyx":114
     * 	for i in range(result.max_size):
     * 		res = result.base[i]
     * 		if res == 0:             # <<<<<<<<<<<<<<
     * 			good_memory_cells += 1
     * 		else:
     */
        __pyx_t_4 = ((__pyx_v_res == 0) != 0);
        if (__pyx_t_4) {

          /* "test_comp.pyx":115
     * 		res = result.base[i]
     * 		if res == 0:
     * 			good_memory_cells += 1             # <<<<<<<<<<<<<<
     * 		else:
     * 			printf("i = %zu \n", i)
     */
          __pyx_v_good_memory_cells = (__pyx_v_good_memory_cells + 1);

          /* "test_comp.pyx":114
     * 	for i in range(result.max_size):
     * 		res = result.base[i]
     * 		if res == 0:             # <<<<<<<<<<<<<<
     * 			good_memory_cells += 1
     * 		else:
     */
          goto __pyx_L5;
        }

        /* "test_comp.pyx":117
     * 			good_memory_cells += 1
     * 		else:
     * 			printf("i = %zu \n", i)             # <<<<<<<<<<<<<<
     * 			printf("result base at loc 0: %u \n", result.base[0])
     * 			printf("result base at loc i: %u \n", result.base[i])
     */
        /*else*/ {
          (void)(printf(((char const *)"i = %zu \n"), __pyx_v_i));

          /* "test_comp.pyx":118
     * 		else:
     * 			printf("i = %zu \n", i)
     * 			printf("result base at loc 0: %u \n", result.base[0])             # <<<<<<<<<<<<<<
     * 			printf("result base at loc i: %u \n", result.base[i])
     * 			printf("result res: %u \n", res)
     */
          (void)(printf(((char const *)"result base at loc 0: %u \n"), (__pyx_v_result.base[0])));

          /* "test_comp.pyx":119
     * 			printf("i = %zu \n", i)
     * 			printf("result base at loc 0: %u \n", result.base[0])
     * 			printf("result base at loc i: %u \n", result.base[i])             # <<<<<<<<<<<<<<
     * 			printf("result res: %u \n", res)
     * 			printf("non-zero memory!!! %u and %u at index %zu \n", res, result.base[i], i)
     */
          (void)(printf(((char const *)"result base at loc i: %u \n"), (__pyx_v_result.base[__pyx_v_i])));

          /* "test_comp.pyx":120
     * 			printf("result base at loc 0: %u \n", result.base[0])
     * 			printf("result base at loc i: %u \n", result.base[i])
     * 			printf("result res: %u \n", res)             # <<<<<<<<<<<<<<
     * 			printf("non-zero memory!!! %u and %u at index %zu \n", res, result.base[i], i)
     * 
     */
          (void)(printf(((char const *)"result res: %u \n"), __pyx_v_res));

          /* "test_comp.pyx":121
     * 			printf("result base at loc i: %u \n", result.base[i])
     * 			printf("result res: %u \n", res)
     * 			printf("non-zero memory!!! %u and %u at index %zu \n", res, result.base[i], i)             # <<<<<<<<<<<<<<
     * 
     * 	if good_memory_cells == result.max_size:
     */
          (void)(printf(((char const *)"non-zero memory!!! %u and %u at index %zu \n"), __pyx_v_res, (__pyx_v_result.base[__pyx_v_i]), __pyx_v_i));
        }
        __pyx_L5:;
      }

      /* "test_comp.pyx":123
     * 			printf("non-zero memory!!! %u and %u at index %zu \n", res, result.base[i], i)
     * 
     * 	if good_memory_cells == result.max_size:             # <<<<<<<<<<<<<<
     * 		printf("safe!")
     * 
     */
      __pyx_t_4 = ((__pyx_v_good_memory_cells == __pyx_v_result.max_size) != 0);
      if (__pyx_t_4) {

        /* "test_comp.pyx":124
     * 
     * 	if good_memory_cells == result.max_size:
     * 		printf("safe!")             # <<<<<<<<<<<<<<
     * 
     * 	return result
     */
        (void)(printf(((char const *)"safe!")));

        /* "test_comp.pyx":123
     * 			printf("non-zero memory!!! %u and %u at index %zu \n", res, result.base[i], i)
     * 
     * 	if good_memory_cells == result.max_size:             # <<<<<<<<<<<<<<
     * 		printf("safe!")
     * 
     */
      }

      /* "test_comp.pyx":126
     * 		printf("safe!")
     * 
     * 	return result             # <<<<<<<<<<<<<<
     * 
     * cdef struct tree_crown_pixels:
     */
      __pyx_r = __pyx_v_result;
      goto __pyx_L0;

      /* "test_comp.pyx":96
     * 	return result
     * 
     * cdef memory memory_allocate() nogil:             # <<<<<<<<<<<<<<
     * 	cdef memory result
     * 
     */

      /* function exit code */
      __pyx_L0:;
      return __pyx_r;
    }
`

**Comment by scoder** [comment]
`malloc()` makes no guarantees about the content of the memory that you get. `calloc()` initalises the memory to zero, `malloc()` does not.

**Comment by JesseRMeyer** [comment]
I understand those guarantees and that does not appear to be the issue. Please read the code carefully and notice that the data at result.base[0] is 0 when it is first accessed after being allocated by malloc, but then changes its value spontaneously afterwards even though no modifications have been made to that address.

**Comment by scoder** [comment]
What is `memory` here?

**Comment by JesseRMeyer** [comment]
It's very straight forward.

    cdef struct memory: 
    	    unsigned char *base
	    size_t max_size
	    size_t used

>  Note that accessing uninitialised memory is undefined behaviour in C

That may just be it, then.  If I checked the assembly, I wonder if the local variable is just being set to whatever happened to be at that location on the stack and never was written. In practice, I write to the address right after the procedure ends, so that write may commit the page and avoid any actual bugs.
