### ISSUE TITLE
Disable __Pyx_RaiseUnboundLocalError insertion

### ISSUE THREAD

**Issue by bashtage** [cython/cython#2898]
I have some code that combines two paths, on that handles dense ndarrays and one that handles sparse arrays, in a single function. I am getting __Pyx_RaiseUnboundLocalError decorations around variable within a loop that cannot be unbound, since the structure is like

```
if cond:
  a = <bind>
else:
  b = <bind>
c = <bind>
for i in range(100):
  common_function(c)
  if cond:
      special_a(a)
  else:
     special_b(b)
```

Can I disable these checks?  Or do I need separate paths where all variables are clearly bound?

**Comment by scoder** [comment]
You can assign to both `a` and `b` before the loop to make sure they are always assigned and never unbound.
