### ISSUE TITLE
Default constructor for extension types

### ISSUE THREAD

**Issue by leftys** [cython/cython#2902]
Hi!

I was very happy to see dataclasses and typed namedtuples in recent Python versions. I think they allow very convenient and Pythonic way to structure data. In particular, I like that I don't have to implement constructors. However, if we want better performance and use Cython, we have no choice than to use extension types (cdef classes) and implement constructors full of `self.varname = varname`. 

Could Cython implement default constructors/init methods for extension types, that would take all class attributes as parameters (in the definition order) and perform the assignment?

**Comment by scoder** [comment]
Is there an advantage of doing this over implementing `@dataclass` for cdef classes? Or are there use cases where `@dataclass` is not the right thing?

**Comment by leftys** [comment]
I don't think so, ability to compile dataclasses would be great, but I suppose it would be much more complicated. If this is planned, are there some open issues I could watch?

**Comment by scoder** [comment]
Superseded by #2903.
