### ISSUE TITLE
BUG: cannot easily override a cython Include

### ISSUE THREAD

**Issue by mattip** [cython/cython#2905]
I am trying to vendor `numpy.pxd` (or `numpy/__init__.pxd`) into numpy. It seems the file in `Includes/numpy/__init__.pxd` is seen before mine when I try `cimport numpy`.

To reproduce: copy the `__init__.pxd` from `Includes/numpy` into `site-packages/numpy`, and add garbage in the original file so using it will crash cython (I used `xxxx = xxxxxxxxx`). Then build a project that calls `cimport numpy` such as pandas. If the copy is found, `cythonize` will succeed. If the original version is found, cythonize will crash.

I am willing to work on a PR, but need some direction as to where to look for the problem.

**Comment by mattip** [comment]
I think the problem is that `Includes` is appended to the search path [here](https://github.com/cython/cython/blob/0.29.6/Cython/Compiler/Main.py#L93), then later on `sys.path` is optionally appended to the search path [here](https://github.com/cython/cython/blob/0.29.6/Cython/Utils.py#L136). IMO if `sys_path` is True the precedence should be 
- user provided `include_directories`
- `sys.path`
- `Includes`

instead of the current situation which gives precedence to `Includes`

**Comment by scoder** [comment]
I agree about the import path order. `sys.path` and `Includes/` should be reversed.

**Comment by scoder** [comment]
PR welcome.
