### ISSUE TITLE
Cython mishandles PEP-3135 __class__ cell in methods

### ISSUE THREAD

**Issue by marginalhours** [cython/cython#2912]
Hello, I am having trouble with some inconsistent behaviour round the value of `__class__` in Cythonized code. This is on Python **3.6.7** with Cython **0.29.1**. 

Briefly, in uncythonized code `__class__` inside a method on a `class` refers to the `class` object, whereas once cythonized, it seems to refer to `<class 'module'>`. This behaviour is a bit unintuitive, and has caused a few issues in a codebase I'm working on, but it's possible I have misunderstood the language semantics! 

I have tried to search for reasons / documentation why this is the case, but I couldn't turn up anything. I apologise if there is something really obvious I'm missing here; let me know if so and I'll close the issue at once. 

Example:

`minimal.py`:
```
class Something:
    def method(self):
        print(__class__)
```

(in an interpreter, uncythonized):
```
from minimal import Something
Something().method()
# prints <class 'minimal.Something'>
```
(after running `cythonize minimal.py -3`):
```
from minimal import Something
Something().method()
# prints <class 'module'>   
```

I believe there is an obvious workaround -- in instance methods, `self.__class__` should still have the correct value. But I was curious if this is intended behaviour, and if so, is there something in the docs about it?

**Comment by scoder** [comment]
I think we handle `super()` separately but not `__class__` (as defined by [PEP-3135](https://www.python.org/dev/peps/pep-3135/)).

PR welcome, it's probably quite easy. See `TransformBuiltinMethods._inject_super()` in `ParseTreeTransforms.py`. The `NameNode` with name `__class__` should be replaced in methods y a `ClassCellNode`. Tests can go into `py3k_super.pyx`, although a new test file like `pep3135_class_cell.py` that also runs uncompiled in Python would also be nice (add a `#tag: pure3.0` comment at the top of the file to prevent it from running in Python 2).
