### ISSUE TITLE
Fix for cimport from PEP420 namespace

### ISSUE THREAD

**Issue by CnlPepper** [cython/cython#2918]
We have a project (https://github.com/cherab) that is split into a number of different sub-packages. Different teams/labs own the different sub-packages. We use namespaces to pull the separate packages together to appear as a single package. We have recently tried to make the package installable from pypi, however we have encountered an issue with cython compilation:

pip install cherab
pip install cherab-openadas

The second package (dependent on the first) fails to compile, saying it can not find the pxd files. On investigating, pip appears to set up a PEP420 namespace where there is no `__init__.py` in the root package. If I manually add an `__init__.py` to the root of the package and try pip again, the cython compilation for cherab-openadas succeeds. Given this, I had a look through the cython source and noticed that during the pxd search, only paths with `__init__.py/pxd` files are scanned. I removed the relevant check in Cython.Utils.search_include_directories() (on 0.29.x branch) and attempted the  re-installation with pip in a clean environment. The compilation and installation was successful.

Given PEP420, is there any explicit need for the `__init__.*` check? Could it be removed? On first look, I can't see any reason it would cause a problem.

**Comment by mattngc** [comment]
Thanks for raising @CnlPepper,  +1 for fixing this.

**Comment by scoder** [comment]
The lookup algorithm in PEP-420 is a bit more complex than just leaving out the `__init__.p*` check. PR welcome that implements the correct algorithm.
https://www.python.org/dev/peps/pep-0420/#specification

**Comment by CnlPepper** [comment]
I feel I might be a bit out of my depth with this one, but I can have a look. Do you want this patched against 0.29.x or master?

**Comment by scoder** [comment]
Definitely `master`.

**Comment by CnlPepper** [comment]
@scoder I'm not 100& sure how to go about adding a test for this feature... I found test/build/package_compilation.srctree which looks like it might be a good place to get inspiration. I've not encountered srctree files before, is there any documentation and how do I run a specific test?

It looks like I just need to patch the Cython.Utils.is_package_dir() function to understand PEP420 namespace folders. Can you think of any reason this might not be a valid approach?

**Comment by scoder** [comment]
That's a good place to start, yes. Our "srctree" test files are literally just a bunch of source files stuffed into one, with the commands at the top that get executed. Use "runtests.py -vv [regex]" to run them. See
https://github.com/cython/cython/wiki/HackerGuide#the-test-suite

**Comment by CnlPepper** [comment]
Fingers crossed I didn't screw anything up, all the relevant tests passed so hopefully I didn't miss anything.

**Comment by CnlPepper** [comment]
@scoder Looks like I need to add a guard to prevent the test being run for old python versions (e.g. 2.7), is there a feature of the test system that will do this?

**Comment by CnlPepper** [comment]
Addressed items raised in code review in pull request #2946.

Hopefully it's all good for a merge.

**Comment by kn45** [comment]
If I run `python setup.py build_ext --inplace` in projects with no \_\_init\_\_.py, the complied submodule .so file would not appear **inplace** but at the root directory.
However, everything goes well **inplace** if I add back the empty \_\_init\_\_.py files to submodule.
I use the latest Cython (0.29.14).

**Comment by CnlPepper** [comment]
This change was only made for 3.0, it was not back ported to 0.29.x as far as I know.

**Comment by mkoeppe** [comment]
2 years later, Cython 3.x is still unreleased. Can we get a backport please?

**Comment by scoder** [comment]
Note that there have been (alpha) releases of Cython 3.0 in the meantime. The latest is 3.0.0a9, which an a10 in the makings.

**Comment by mkoeppe** [comment]
Switching to an alpha release of a dependency is not an option for production

**Comment by KimiNewt** [comment]
I've encountered this issue as well, and because of our build system it is very difficult (not to mention unnecessary) to add `__init__.py`s everywhere. Perhaps @mkoeppe 's change can be done under a flag/directive?
