### ISSUE TITLE
Segmentation fault when call wrapped python function in C

### ISSUE THREAD

**Issue by luoxiaojian** [cython/cython#2921]
I'm trying to call cdef function from C. If the cdef function contains python statements, such as print(), python (def) function, a segmentation fault would be raised.

The pyx file:
# cython: language_level=3

cdef public double PI = 3.1415926

cdef public double get_e():
    print("calling get_e()")
    return 2.718281828

The C file:
#include "Python.h"
#include "transcendentals.h"
#include <math.h>
#include <stdio.h>

int main(int argc, char **argv) {
  Py_Initialize();
  PyInit_transcendentals();
  printf("pi**e: %f\n", pow(PI, get_e()));
  Py_Finalize();
  return 0;
}

The compile commands are:
cython transcendentals.pyx
gcc -I. -I/usr/include/python3.5m -I/usr/include/python3.5m  -Wno-unused-result -Wsign-compare -g -fstack-protector-strong -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -L/usr/lib transcendentals.c main.c -lpython3.5m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions

If I remove the print statement, no segmentation fault will be raised, but value of PI is 0.

I'm trying to locate the problem, and I found in the generated code of get_e
__pyx_t_1 = __Pyx_PyObject_Call(__pyx_builtin_print, __pyx_tuple_, NULL); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 6, __pyx_L1_error)
__pyx_builtin_print is NULL

**Comment by luoxiaojian** [comment]
I tested on python2.7 and problems solved.
Is there some bug when cython work with python3 or I did something wrong?

**Comment by scoder** [comment]
The latter. Calling the module init function (and throwing away the module reference that it returns) is not the right thing to do in Python 3. Leave that to CPython. You can use the inittab mechanism to integrate with a statically linked extension module.
