### ISSUE TITLE
"encodes absolute source path in output change" fix was reverted

### ISSUE THREAD

**Issue by vnitinv** [cython/cython#2933]
Original issue: encodes absolute source path in output #1565

Fix was done via: https://github.com/cython/cython/pull/1576

same day, another commit reverted the changes (must be sync issue)
https://github.com/cython/cython/commit/ba00ebef16f7b86c595498a3807e709e6d9c9228#diff-4548b0f91e1236cc95eb7cbd6a960533L9050

**Comment by scoder** [comment]
Isn't it this?
https://github.com/cython/cython/commit/ba00ebef16f7b86c595498a3807e709e6d9c9228#diff-8edfdd295193e44fbc412ba8cb0396f7R206

Is there an actual problem with the current implementation?

**Comment by vnitinv** [comment]
I tried with 0.29.6. Need to try out 0.29.7. Thanks for update
