### ISSUE TITLE
Cython 0.29.7 mangles cdef public functions on windows, but doesn't do it in Linux

### ISSUE THREAD

**Issue by Jivko1212** [cython/cython#2937]
I am building an extension that I want to be able to call from C++. The signature of the function is:
```cython
cdef public int count_cwrap(int limit) except -1
```

This gets this C signature in Windows:
```C
__PYX_EXTERN_C int __pyx_f_19pythagorean_triples_count_cwrap(int);
```
and this signature in Linux:
```C
__PYX_EXTERN_C int count_cwrap(int);
```
Calling the function from windows works, but it seems like a bug to me, and would prefer the Linux behavior.

Here is the full code to reproduce.
pythagorean_triples.pyx:
```python
# cython: language_level=3
import time
import cython
import numpy as np
 
def count(limit):
    if limit < 3:
       raise ValueError('Invalid limit value')
    arr = np.zeros(10)
    result = cython.declare(cython.int, 0)
    a = cython.declare(cython.int)
    b = cython.declare(cython.int)
    c = cython.declare(cython.int)
    for a in range(1, limit + 1):
        for b in range(a + 1, limit + 1):
            for c in range(b + 1, limit + 1):
                if c * c > a * a + b * b:
                    break

                if c * c == (a * a + b * b):
                    result += 1
    return result

cdef public int count_cwrap(int limit) except -1:
    return count(limit)

if __name__ == '__main__':
    start = time.time()
    result = count(1000)
    duration = time.time() - start
    print(result, duration)`
```

setup_pyx.py for Windows
Note that I need to export the mangled name, otherwise the function is not in the symbol table of the produced pyd file or the lib for linking. 
```python
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize
 
setup(
    ext_modules = cythonize(Extension('pythagorean_triples', sources = ['pythagorean_triples.pyx'], 
	export_symbols=['__pyx_f_19pythagorean_triples_count_cwrap']))
)
```

setup_pyx.py for Linux:
I don't need to export anything here. Everything is much easier and works properly.
```python
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize

setup(
    ext_modules = cythonize(Extension('pythagorean_triples', sources = ['pythagorean_triples.pyx']))
)
```

In Linux, I am building with ```python3 setup_pyx.py build_ext --inplace```
In Windows I am building with ```python setup_pyx.py build_ext --inplace```
I also tried compiling to C in Windows with ```cython pythagorean_triples.pyx``` The result was the same mangled function name.

**Comment by scoder** [comment]
Hmm, could you double-check that you are generating both C files cleanly from the same .pyx file? Specifically, `cythonize()` avoids regenerating the `.c` file if it's already there and newer than the source file. Maybe you still had an old `.c` file lying around that you generated when your `.pyx` file did not have a  `private` yet?

I don't have access to a Windows system myself, but this is the only explanation I have, because the generation of the  `.c` file is not platform- (or anything else-) dependent in any way.

**Comment by Jivko1212** [comment]
I am closing the issue because I found that it was created by an additional .pxd file that I used for a separate compilation using the .py with concomitant magic .pxd file. The .pxd file was not present in Linux.
