### ISSUE TITLE
Request for new release to PyPi(0.29.8)

### ISSUE THREAD

**Issue by gpiks** [cython/cython#2944]
Hi @scoder , I am not sure if you have other changes in the pipeline, but would like to see to be able to use #2930 in our project. 

Thanks!

**Comment by scoder** [comment]
Specifically #2930 is currently scheduled for 3.0, not for a point release. I considered it too risky to change something like this in a point release.

**Comment by gpiks** [comment]
Thats fair. Thanks! 

Out of curiosity, what kind of timeframe do you expect for a 3.0?

**Comment by scoder** [comment]
Whenever it's ready, but definitely this year.
See the blockers in the "Cython 3.0" milestone: https://github.com/cython/cython/milestone/58
Any help with them is appreciated and will speed this up.

**Comment by gpiks** [comment]
I am just starting out with cython and am fairly green in that regard. Do you have any recommendations for issues to pick up? Any of the `good-first-issue`?

**Comment by scoder** [comment]
Yeah, pretty much any of those. Also, #2864 is a fairly big one where we still need to investigate why several of the tests fail. Help in that direction would be appreciated.
I'll close this ticket, though, because it's not something to discuss on the bug tracker.
