### ISSUE TITLE
Properly Handle Duplicate Kwargs

### ISSUE THREAD

**Issue by joshuahaertel** [cython/cython#2963]
```
def print_kwargs(**kwargs):
    print(kwargs)

print_kwargs(**{'a': 'a', 'a': 'b'})
```
This works in python, but not when compiled with Cython. I think it might have something to do with the way kwargs are unpacked.

It's good to point out that **this** is illegal in python, and will raise a SyntaxError(keyword argument repeated):
`print_kwargs(a='a', a='b')`

Also worth pointing out that, Interestingly enough, this works the same in python as in cython:
`print({'a': 'a', 'a': 'b'})`
printing `{'a': 'b'}`

**Comment by will-ca** [comment]
One one hand, I believe I've run into this issue in another function call in my own code that's basically as follows:

```python3
objecttype(**{**parameterdict, 'overwrittenparameter': x})
```

`TypeError: function() got multiple values for keyword argument 'overwrittenparameter'`

But on the other hand, I can't seem to reproduce it using an inline Cython version of the example in the OP:

```python3
>>> cprint_kwargs=cython.inline("def f(**kwargs):\n print(kwargs)\nreturn f")
>>> cprint_kwargs(**{'a': 'a', 'a': 'b'})
{'a': 'b'}
```

**Comment by joshuahaertel** [comment]
I wonder if Python is handling the kwargs before calling the the function? Can you inline a call to the function?

**Comment by will-ca** [comment]
Ah, yeah. The dictionary and keyword arguments would have probably been processed and consolidated completely by CPython before being passed into the Cythonized bits.

Inlining the function call does produce the broken result:

```python3
>>> cython.inline("def f(**kwargs):\n print(kwargs)\nreturn f(**{'a': 'a', 'a': 'b'})")
TypeError: function() got multiple values for keyword argument 'a'
```

**Comment by will-ca** [comment]
Wrapping the dictionary in any kind of code that constructs a new dictionary does make it work however:

```python3
>>> cython.inline("return (lambda **kwargs: kwargs)(**{'a': 'a', 'a': 'b'})")
TypeError: function() got multiple values for keyword argument 'a'
>>> cython.inline("return (lambda **kwargs: kwargs)(**dict({'a': 'a', 'a': 'b'}))")
{'a': 'b'}
```

But I do find this a little strange, as I'd naively expect the original example to just call the dictionary constructor and unpackers?

**Comment by scoder** [comment]
> print_kwargs(**{'a': 'a', 'a': 'b'})

You didn't say what kind of error you got for this, but my quick guess is that Cython detects that this is redundant and replaces it with (essentially)

> print_kwargs(a='a', a='b')

which then is illegal. I'm wondering, though: what is the use case for this?

**Comment by joshuahaertel** [comment]
It was the `TypeError: function() got multiple values for keyword argument 'a'`

I hit it with an external library where one class called super and set a kwarg. The parent class then called super as well, trying to set the same kwarg, if one wasn't set already. Instead of using `setdefault`, it did something like `super(**{'a': 'a', **kwargs})`, but since that works in cpython, there's no need for the author to have thought twice about their implementation.

**Comment by scoder** [comment]
Thanks for the detailed bug report. I deoptimised this case since it wasn't a correct transformation.
