### ISSUE TITLE
Functions should accept keyword definitions for single positional arguments.

### ISSUE THREAD

**Issue by will-ca** [cython/cython#2965]
```python3
import cython
fstring = 'def f(x): return x+2'
lstring = 'lambda x: x+2'
```

In interpreted CPython, functions with only a single positional parameter can still have their one argument passed through a keyword, just as with any regular function: 

```python3
exec(fstring)
f(5)
eval(lstring)(5)
```

`7`

`7`

```python3
f(x=5)
eval(lstring)(x=5)
```

`7`

`7`

This fails, however, with Cython:

```python3
cython.inline(fstring+'\nreturn f')(x=5)
cython.inline('return '+lstring)(x=5)
```

`Traceback (most recent call last):`

`  File "<stdin>", line 1, in <module>`

`TypeError: f() takes no keyword arguments`

`Traceback (most recent call last):`

`  File "<stdin>", line 1, in <module>`

`TypeError: lambda() takes no keyword arguments`

Oddly enough, however, this type of behaviour is avoided if the function has multiple arguments of any kind:

```python3
fstring = 'def f(x, y): return x+y'
lstring = 'lambda x, y=2: x+y'
cython.inline(fstring+'\nreturn f')(x=5, y=2)
cython.inline('return '+lstring)(x=5)
```
`7`

`7`

**Comment by scoder** [comment]
See the `always_allow_keywords` directive [here](http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives), or wait for positional-only arguments in Cython 3.0.
