### ISSUE TITLE
tp_print renamed to tp_vectorcall_offset in cython master

### ISSUE THREAD

**Issue by tacaswell** [cython/cython#2976]
This was changed in:

https://github.com/python/cpython/pull/13185 / https://github.com/python/cpython/commit/aacc77fbd77640a8f03638216fa09372cc21673d to support https://www.python.org/dev/peps/pep-0590/

A brute-force `tp_print` -> `tp_vectorcall_offset` find-and-replace fixes it on cpython master, but is very not back-compatible :smiling_imp: .  Will look into seeing if I can sort out how to gate this correctly.

**Comment by tacaswell** [comment]
https://mail.python.org/pipermail/python-dev/2018-June/153927.html Seems cython is already in the loop on this at the high-level

**Comment by scoder** [comment]
I would be happy about a PR that
- replaces the direct setting of `tp_print` with a C macro `__Pyx_SET_TP_PRINT()`
- renames `tp_print` in the extension type struct comments with the new name, since the old name is a legacy Py2 name anyway.

**Comment by scoder** [comment]
That should be against the `0.29.x` branch, to keep it compatible with Py3.8. (And since that's a point release, I'd keep the `tp_print` name in the comments as they are and change them only in master, just in case…)

**Comment by scoder** [comment]
I'll take care of this change, and will also prepare a new release once it's clear that nothing else will change in CPython 3.8b1.

**Comment by tacaswell** [comment]
Thanks @scoder !  Sorry I did not get to doing something about this fast enough.

**Comment by jdemeyer** [comment]
Sorry for that, I didn't expect that Cython would assign anything to `tp_print` explicitly.

Apart from this, there is no breakage due to PEP 590?

**Comment by scoder** [comment]
I got everything fixed in my local tests, at least. The latest 0.29.10 release should be ok with CPython 3.8 beta 1. Let's see what our users uncover. :)

**Comment by vstinner** [comment]
I opened https://bugs.python.org/issue37250 to maybe fix Python 3.8 before Python 3.8.0 final release.

**Comment by tacaswell** [comment]
@vstinner a few times a week I build cpython + the pydata stack from all of the master branches (and test at least Matplotlib).  When I find issues with down-stream projects should I also report them upstream to cpython?

**Comment by vstinner** [comment]
> @vstinner a few times a week I build cpython + the pydata stack from all of the master branches (and test at least Matplotlib). When I find issues with down-stream projects should I also report them upstream to cpython?

In case of doubt, it's better to report the issue and asks if it's a deliberate backward incompatible or a regression.
