### ISSUE TITLE
ImportError: some/path/some_module.so: undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by nmgeek** [cython/cython#2979]
Something seems to have happened to Python between release 2.7.12 and 2.7.15 which breaks ABI comparability of .so files compiled with Cython.  There are various references to this in Python and Debian bug trackers but I have not found a workaround.  One suggested workaround has you build your own _cytoolz_ package but I could not find _cytoolz_ being used by Cython in my environment.  Maybe that is for cpython and cpython is a different compiler?

I believe the _PyFPE_jbuf_ symbol comes from a compiler option called _fpectl_.

Is it possible to get or build a version of the Cython package which builds .so files without a reference to PyFPE_jbuf and which runs on Ubuntu 16.04 LTS x86_64?

It just seems to me that since we put these into wheels that are named like _foo-cp27-cp27mu-linux_x86_64.whl_ they should run without incident under any 2.7 version of Python.

**Comment by nmgeek** [comment]
Here is the compile command that Cython spews in case that helps:

`x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/utils.o -o build/lib.linux-x86_64-2.7/utils.so`

**Comment by scoder** [comment]
> build your own cytoolz package

You can generalise that to "build the failing package yourself".

Cython has no control over your build flags. Those are up to `distutils` /  `setuptools`, and usually are inherited from the original build of your CPython runtime.

You can ask on the python mailing list to see if others have an idea of how to solve this.
