### ISSUE TITLE
string_to_entry leftover in Symtab

### ISSUE THREAD

**Issue by samaingw** [cython/cython#3007]
In Cython/Compiler/Symtab.py, the base class Scope has a dict attribute named `string_to_entry` initialized to an empty dict in `__init__`.
This attribute has a comment about its use in ModuleScope (no comments about it in Scope).

A global search for this attribute in the whole cython repo (`find [cython_repo]/* | xargs grep -n "string_to_entry"`) gives only the two occurences described above (initialization in Scope, comment in ModuleScope).

I was wondering if it was a leftover of an old version, or the first blocks of a future feature.

**Comment by scoder** [comment]
I removed the attribute. Thanks.
