### ISSUE TITLE
How to specify include_dir with cythonize?

### ISSUE THREAD

**Issue by corydolphin** [cython/cython#3014]
Hello,

I am trying to use Cython to accelerate some slow, math-heavy code in a large existing project. Since the project doesn't use setup.py for dependencies, I would like to use the `cythonize` command line tool to build the cython binaries. This works well, but I am unable to figure out how to specify an include directory, to e.g. include Numpy header files. 

Does anyone have guidance? E.g. to fix this issue:

```bash
$ cythonize -a -i **/*.pyx -3

Compiling math-heavy-routines.pyx because it changed.
[1/1] Cythonizing math-heavy-routines.pyx
running build_ext
math-heavy-routines.c:611:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1```

**Comment by ozars** [comment]
Use `CFLAGS="-Inumpy_dir" cythonize ...` as distutils honors some common environment variables. If you need to link some shared objects you can explicitly provide `LDFLAGS` as well.

**Comment by scoder** [comment]
Note that the bug and feature tracker is not the right place to ask support questions. Use the cython-users mailing list for that.
