### ISSUE TITLE
C compiler warning from calling __Pyx_PyFunction_FastCallDict()

### ISSUE THREAD

**Issue by Kamekameha** [cython/cython#3028]
[Calls](https://github.com/cython/cython/blob/b9f3704b8201e07599652da5b0ca3922fe5d2a12/Cython/Utility/ObjectHandling.c#L1875) to [`__Pyx_PyFunction_FastCallDict()`](https://github.com/cython/cython/blob/b9f3704b8201e07599652da5b0ca3922fe5d2a12/Cython/Utility/ObjectHandling.c#L2021-L2024) apparently assume that it expects a `nargs` of type `Py_ssize_t` but currently the function expects an `int`, causing compilation warnings.

**Comment by scoder** [comment]
Thanks for the report.

**Comment by Kamekameha** [comment]
Following this up I've found the warning is still persistent, as it so happens that [`PyEval_EvalCodeEx()`](https://docs.python.org/3/c-api/veryhigh.html#c.PyEval_EvalCodeEx) also expects an `int` for the `argcount` argument.  I've noticed also that the [surrounding arguments](https://github.com/cython/cython/blob/e1de7e4ab38052a2c570d16236d7220ed6cdd7a1/Cython/Utility/ObjectHandling.c#L2193-L2203) for the call are cast down to `int`, so maybe the fix is as simple as casting down `nargs` as well.
