### ISSUE TITLE
Use of uninitialized local variable compiler warnings from __Pyx_SetItemInt_Fast()

### ISSUE THREAD

**Issue by Kamekameha** [cython/cython#3029]
With #3022, the [variable `r`](https://github.com/cython/cython/blob/b9f3704b8201e07599652da5b0ca3922fe5d2a12/Cython/Utility/ObjectHandling.c#L503) is returned without prior initialization with the return value of [`mp_ass_subscript()`](https://github.com/cython/cython/blob/b9f3704b8201e07599652da5b0ca3922fe5d2a12/Cython/Utility/ObjectHandling.c#L506), both returning a possibly wrong value and causing compiler warnings.

**Comment by seberg** [comment]
Sorry about that, I opened which should fix this gh-3026

**Comment by seberg** [comment]
Just a heads up, the fix has been merged, so it can be closed (I hope ;)).
