### ISSUE TITLE
Cython doesn't work on Python 3.8 beta2

### ISSUE THREAD

**Issue by vstinner** [cython/cython#3034]
Cython is been made compatible with Python 3.8 beta2 in commit 0d88839168013fd69350d31eaee5514cd2f727b9, but this commit is not part of Cython tag 0.29.11. Would it be possible to get a new release, please?

cc @scoder

**Comment by stonebig** [comment]
also, I have apparent issues running
`````
%load_ext Cython
````
in latest jupyterlab/cython cgohlke/python-3.8.0b2

**Comment by scoder** [comment]
Duplicate of #3031.

**Comment by Harmon758** [comment]
[Cython 0.29.12](https://github.com/cython/cython/releases/tag/0.29.12) has been released with that commit/fix now.

**Comment by thedrow** [comment]
Please close this issue for good measure.
