### ISSUE TITLE
Check files before overwriting during compilation

### ISSUE THREAD

**Issue by sehoffmann** [cython/cython#3041]
It would be nice for Cython to check if a file can be safely overridden when generating `.c` or `.cpp` files.

This can easily be done by checking the first line for `"/* Generated by Cython ..."` or a similiar flag.
If that line is missing, the build process should be stopped and a warning should be emitted, forcing the user to either manually check and delete the files or to pass an yet-to-introduce flag which disables this behaviour.

The scenario which led me to open this issue:
1) I'm implementing some performance-critical sections directly in a `.cpp` file
2) Classes used to interact with Python are exposed in identically named `.h` and `.pxd` files.
3) One of the classes required an Extension Class, forcing me to create a `.pyx` file.
4) Me forgetting that `conda-develop -b` builds inplace by default, resulted in the newly generated `.cpp` file overwritting one day's worth of work.

I think this is a relatively easy to implement feature, which could prevent some frustration in the future.

**Comment by jonashaag** [comment]
I just hid this too, had a C++ file `a.cpp` and Cython file `a.pyx` and compiled Cython in C++ mode, overwriting `a.cpp`. Luckily I had a recent backup in Git.

**Comment by da-woods** [comment]
Duplicate https://github.com/cython/cython/issues/4177 - this is in the Cython 3 branch
