### ISSUE TITLE
"size changed, may indicate binary incompatibility"

### ISSUE THREAD

**Issue by pitrou** [cython/cython#3042]
What is that and how do I silence this warning?
```
../../pyarrow-test-3.6/lib/python3.6/site-packages/pyarrow/tests/test_cython.py:102: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
E   ValueError: pyarrow.lib.DictionaryMemo size changed, may indicate binary incompatibility. Expected 184 from C header, got 160 from PyObject
lib.pxd:75: ValueError
```

**Comment by pitrou** [comment]
Note the wheel was built with Cython 0.29.8 and is being tested with Cython 0.29.12.

**Comment by pitrou** [comment]
@scoder What would this be? We are not the only ones to get the issue apparently: https://github.com/apache/arrow/pull/4884#issuecomment-511705985

**Comment by pitrou** [comment]
Also I can't reproduce locally, even with those exact Cython versions.

**Comment by pitrou** [comment]
Update: I managed to reproduce locally... but only with manylinux1, not manylinux2010!

Here is a manylinux1-produced wheel:
```
Python 3.7.3 (default, Apr  3 2019, 19:16:38) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow as pa
>>> pa.lib.DictionaryMemo.__basicsize__
160
```

Here is a manylinux2010-produced wheel:
```
Python 3.7.3 (default, Apr  3 2019, 19:16:38) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow as pa
>>> pa.lib.DictionaryMemo.__basicsize__
184
```

**Comment by mbrobbel** [comment]
> Update: I managed to reproduce locally... but only with manylinux1, not manylinux2010!
> 

We're using the published pyarrow manylinux1 wheel when building a manylinux2010 wheel of our project which explains the value error.

**Comment by pitrou** [comment]
Ok and I finally understand: Cython is flagging a real issue here. We're putting a C++ `DictionaryMemo` structure in our Python `DictionaryMemo` extension type. But the size of the C++ structure depends on the C++ (and libstdc++) compiler ABI, so loading it on a more recent compiler may break. Instead, we should only store a pointer like we do on other extension types.

So, sorry for my initial annoyance and thanks to Cython for flagging this!

**Comment by syedmustafa54** [comment]
How can we create binary @pitrou
