### ISSUE TITLE
how to compile multiple files 

### ISSUE THREAD

**Issue by syedmustafa54** [cython/cython#3043]
I have python code 
`main.py` in `main.py` I need to import different script second.py and other modules like Cuda, pytorch
but when I run 
```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
ext_modules = [Extension("main",["main.py"]),]
setup(
    name = 'My Program Name',
    cmdclass = {'build_ext': build_ext},
    ext_modules = ext_modules
)
```
I am getting `.so` and `.c` file than i am compiling it to binary  by this command 
```
gcc -Os -I /usr/include/python2.7/ -o run  main.c -lpython2.7 -lpthread -lm -lutil -ldl
```
when I run `./run` getting error `no module name second` when i remove `second` from import getting error on different import module like `no module pytorch` when I am running main.py its working perfect without errors 
How can I make Python a binary file.

**Comment by scoder** [comment]
Does this page help?
http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html
Otherwise, please ask on the cython-users mailing list. The bug tracker is not a place for support questions.

**Comment by syedmustafa54** [comment]
what is cython-user mailing list how can i contact them @scoder
