### ISSUE TITLE
Is it possible to create a static library instead of shared library?

### ISSUE THREAD

**Issue by ethanjyx** [cython/cython#3062]
The current way of building with Cython will result in a shared library in the end, i.e. `.so`, is there a reason for us to build into `.so`?

I wonder if it could be built into a `.o` or static library file. The benefit of a static library is that we can combine everything into a single executable, instead for shared library we will have the binary loading the separate shared library file.

**Comment by scoder** [comment]
Yes, that possibility exists. You can link multiple extension modules together and use the "inittab" mechanism to load them into CPython.
https://docs.python.org/3/extending/embedding.html#extending-embedded-python
https://docs.python.org/3.5/c-api/import.html#c.PyImport_AppendInittab

**Comment by jaxlotl** [comment]
Would it be possible to get a little more detail on this solution? I am relatively new to cython myself, but from these links it is unclear how I can convert my cython-generated shared library into a static library, or whether I can build the static library directly from cython. Thank you!

**Comment by Huweicai** [comment]
Does anyone have idea about it? I am facing the same problem now.

**Comment by webknjaz** [comment]
Is this what y'all are looking for? https://cython.readthedocs.io/en/latest/src/tutorial/clibraries.html#static-linking
