### ISSUE TITLE
Add explicit support for defining namespaces?

### ISSUE THREAD

**Issue by Keithcat1** [cython/cython#3068]
Being able to define your own namespaces would make it easier to organize large Cython modules.
It might look something like this.
constants=namespace[
    """Constants and functions required by this module"""
    cdef int value=1
    cdef int another_value=4
    cdef add(x=val, y=another_val):
        return x+y
    ]
print(constants.add(20, constants.val))

This would be like a normal module, except everything defined inside can be used with an attribute lookup and all functions and classes ETC would remember the namespace where they were stored.
This would allow you to define sections that have an obvious purpose and split modules up into different parts.
It would also allow you to put multiple modules into a single Cython file and still allow them to use Cython.

**Comment by robertwb** [comment]
Cython, like Python, uses modules for its namespaces. https://cython.readthedocs.io/en/latest/src/userguide/sharing_declarations.html

**Comment by Keithcat1** [comment]
Hi,
That wouldn't work. What I'm suggesting is to add a syntax which allows you to define a new global namespace which is tied to a variable.
Then anything you define in that namespace will be local to that namespace, the same way modules work.

**Comment by scoder** [comment]
Cython, like Python, uses packages, modules and classes for namespacing. An extension type or struct seems like a reasonable solution to the problem you propose.
