### ISSUE TITLE
An workaround approach to conditional definition

### ISSUE THREAD

**Issue by cmpute** [cython/cython#3076]
I have similar demand for conditional statement inside definition, which is claimed here #573 . Since it's not trivial to implement that, I propose another way to workaround:

```
ctypedef struct ohmygod:
      int common

IF UNAME_SYSNAME == "Windows":
      ctypedef struct ohmygod:
            int greece
ELSE:
      ctypedef struct ohmygod:
            float pelvis
```

That is to allow partial definition in Cython (this feature is like ["partial" keyword in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods)). I have tried this idea, Cython won't report error but simply ignore the second definition. Is this way easier to implement in Cython?

**Comment by scoder** [comment]
> Cython won't report error but simply ignore the second definition

Interesting. It should definitely report an error for this. And I would not want this as a feature, because it makes it hard to understand for users what the actual definition of the struct is. It should be defined in one place, not split across multiple definitions, each of which is incomplete (and wrong) by itself.

**Comment by scoder** [comment]
Also note that the declaration in Cython is usually not the issue. Just declare whatever you feel like, whether the C compiler knows about it or not. The usage then in the code is the only problem, and that can be guarded in any way you like, including "IF"s.

**Comment by cmpute** [comment]
Cool. Thanks for the reply. However, I still want some feature to enable conditional definition :) Hope it can be implemented in the future
