### ISSUE TITLE
python 3.7.4 cython 0.29.12 extension module filename has @PYVERNODOTS@

### ISSUE THREAD

**Issue by kangwonlee** [cython/cython#3078]
## Environment

* Python 3.7.4
* Tested with Cython [`0.29.6`](https://travis-ci.org/kangwonlee/2018pycpp/builds/571585187) and [`0.29.12`](https://travis-ci.org/kangwonlee/2018pycpp/jobs/571554861) (tests from https://github.com/kangwonlee/2018pycpp/issues/42)
* Source code used : [link](http://scipy-lectures.org/advanced/interfacing_with_c/interfacing_with_c.html#id13)

## Symptom

* Filename of the cython 0.28.1 extension module contains string `@PYVERNODOTS@`
* Seems not able to import in this case

Please let me know any suggestion.

**Comment by scoder** [comment]
I have no idea why this would happen, but it's not a Cython issue. The file name is generated by distutils/setuptools. There is something wrong with your Python installation.

**Comment by kangwonlee** [comment]
I did some more search and noticed it seems python 3.7.4 issue. https://stackoverflow.com/questions/57473816/what-does-pyvernodots-in-python-c-extension-modules-mean
