### ISSUE TITLE
Problems with pickling and unpickling extension types

### ISSUE THREAD

**Issue by Keithcat1** [cython/cython#3079]
I was trying to convert my Python object to a Cython object when I realized that the way Cython pickles extension types, using a tuple instead of a dict is incompatible.
There are 2 problems. The first is that I can't load pickled Python objects as Cython extension types that have the same attributes without a lot of fiddling and extra code. Second, if I change the list of cdef attributes of an extension type, old pickled instances can't load anymore.
Would it be possible for Cython to automatically define a `__setstate__` method that returns a dict, then for Cython to also define a `__getstate__` method that takes that dictionary, iterates through it, sets as many values as it can, and leaves the rest untouched?

**Comment by robertwb** [comment]
This sounds dangerous to do in general (especially because uninitialized
attributes won't be attribute errors). Seems better to write a custom
reduce method where you can do whatever you want.

**Comment by scoder** [comment]
I agree that this is not something that Cython should do itself.
