### ISSUE TITLE
After "python setup.py build_ext -i" test fails

### ISSUE THREAD

**Issue by demiurg337** [cython/cython#3083]
Hi
I fixed bug for https://github.com/cython/cython/pull/3070 and wrote test, and seems like all works,
but after I was doing command "python setup.py build_ext -i", test fails
only after deletion of all ".so" files which are result of previous command, test again works.
(I tried it with diferent version of python)

Is this problem from my changes? (or otherwise maybe there is additional bug in code generation?)
(sory for question, but I am really confused)

This question bound to https://github.com/cython/cython/pull/3070

**Comment by scoder** [comment]
See my comment over there.
