### ISSUE TITLE
Cythonized python.net code cannot find system assemblies

### ISSUE THREAD

**Issue by crayxt** [cython/cython#3084]
Cross-post from https://github.com/pythonnet/pythonnet/issues/941

Dup of my SO question https://stackoverflow.com/questions/57493309/cythonized-python-net-code-cannot-find-system-assemblies

When I compile the python code which uses python.net to access .Net assemblies, it can't find those assemblies. Without compilation it works ok.

For demo code, I used https://github.com/pythonnet/pythonnet/blob/master/demo/helloform.py

My setup.py file

```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize

ext_modules = [
    Extension(
        'helloform',
        sources = ['helloform.py'],
        language = 'c++'
      )
]

setup(
  name = 'helloform',
  ext_modules = cythonize(ext_modules),
)
```
Then I build it with python setup.py build_ext --inplace.

I wanted to load compiled module from Python prompt with import helloform but it failed with

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "helloform.py", line 8, in init helloform
ModuleNotFoundError: No module named 'System'
```

**Comment by scoder** [comment]
This is dotnet specific code, using dotnet specific packages. What Python runtime do you use? Please ask over there what the problem might be. It's more likely that they would be able to resolve this than Cython.

**Comment by crayxt** [comment]
Closing this in favor of the issue opened on pythonnet itself https://github.com/pythonnet/pythonnet/issues/941
