### ISSUE TITLE
got segmentation fault using memoryview with c++ vector

### ISSUE THREAD

**Issue by chenjunweii** [cython/cython#3085]
Hi, I have got a segmentation fault error when I use memoryview with c++ vector, but i have no such error when I use memoryview without c++ vector

any solutions ?  thanks 

example code 

```cython

    cdef vector [int32 [:]] v = vector [int32 [:]] ()

    for i in range(5):

        v.push_back(np.ones(10, dtype = np.int32) + i)

    for i in range(5):

        print('out : ', v[i][0])   

```

**Comment by krsnad** [comment]
Hi, I'm facing the same problem in 2021. Is this not the correct way to do it.

**Comment by 0dminnimda** [comment]
@krsnad I don't really understand what is the essence of the OP's example, can you provide a clearer example of when you get segfault and when not?

**Comment by 0dminnimda** [comment]
And also it would be good to know your os, python version and cython version.

**Comment by da-woods** [comment]
You can't use a memoryview as an element of a vector. Cython generates code manually to construct and destruct it. Since there's no way for the vector to generate this code it will crash.

We probably generate an error message though, rather than allowing it to compile and crash.
