### ISSUE TITLE
Single-argument functions cannot be called using keyword

### ISSUE THREAD

**Issue by jdemeyer** [cython/cython#3090]
```
In [1]: %load_ext cython

In [2]: %%cython
   ...: def f(k): return k

In [3]: f(k=1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-2f40ef43e783> in <module>()
----> 1 f(k=1)

TypeError: f() takes no keyword arguments
```

**Comment by jdemeyer** [comment]
The problem is very obvious in retrospect: single-argument functions use `METH_O` which do not accept keywords. The question is what to do with this, given that nobody complained about this so far. I only found this out when trying some edge-cases for #3021.

**Comment by scoder** [comment]
There is a compiler setting to always allow keywords, also for METH_O functions.

**Comment by scoder** [comment]
Hmm, on second thought, I wonder if it's worth changing the default setting, now that we have all that fast-calling integration?

**Comment by scoder** [comment]
I now think that Cython 3.0 is a good time to change the default setting. Let's just do that.

**Comment by robertwb** [comment]
I remember this default was chosen due to non-trivial performance implications. Is the fast calling integration sufficient to overcome this now?

**Comment by scoder** [comment]
You can still see a slight difference in a micro benchmark. The main performance impact is when we create a tuple for passing the single argument. The fast calling conventions usually just pass their arguments on the C stack.
```bash
$ cat metho.pyx
def metho(a):
    pass

$ python3.9 cythonize.py -if3 -X always_allow_keywords=False metho.pyx
$ python3.9 -m timeit -s 'from metho import metho' 'metho(1)'
10000000 loops, best of 5: 27.3 nsec per loop

$ python3.9 cythonize.py -if3 -X always_allow_keywords=True metho.pyx
$ python3.9 -m timeit -s 'from metho import metho' 'metho(1)'
10000000 loops, best of 5: 29.6 nsec per loop
$ python3.9 -m timeit -s 'from metho import metho' 'metho(a=1)'
10000000 loops, best of 5: 38.6 nsec per loop

$ python2.7 cythonize.py -if3 -X always_allow_keywords=False metho.pyx
$ python2.7 -m timeit -s 'from metho import metho' 'metho(1)'
10000000 loops, best of 3: 0.0725 usec per loop

$ python2.7 cythonize.py -if3 -X always_allow_keywords=True metho.pyx
$ python2.7 -m timeit -s 'from metho import metho' 'metho(1)'
10000000 loops, best of 3: 0.0738 usec per loop
$ python2.7 -m timeit -s 'from metho import metho' 'metho(a=1)'
10000000 loops, best of 3: 0.103 usec per loop
```
So, yeah, there is a tiny difference, 1-2ns on my machine in this extreme case. That's 8% in the case of Py3.9, which can avoid the tuple creation in both cases, so the relative weight of the argument checking inside of the function is higher.

Anyway, the option doesn't go away. If you really want a `METH_O` with no keyword argument passing in the caller and no argument checking in the callee, you can use `@always_allow_keywords(False)` in a backwards compatible way.

**Comment by robertwb** [comment]
Thanks for the benchmarks. That's significantly less overhead than what I
recall there being when we added this option. The fast calling conventions
are really nice.
