### ISSUE TITLE
% string formatting with multiple inputs via of tuples doesn't match python3.5 behavior

### ISSUE THREAD

**Issue by dannyjeck** [cython/cython#3092]
I'm new to cython but this seems like incorrect behavior.

Python code put in cytest/test.py:
```
def test_func_no_tuples(a, b):
  print((a.__class__, b.__class__))
  print((a, b))
  s = 'string being formatted=%d' % a
  print(s)


def test_func_with_tuple(a,b):
  print((a.__class__, b.__class__))
  print((a, b))
  s = 'string being formatted=%d-%d' % (a,b)
  print(s)

test_func_no_tuples(50.,50.)

test_func_with_tuple(50.,50.)
```

Before compilation the output of `python3 -c "from cytest import test"` is:
```
python3 -c "from cytest import test"
(<class 'float'>, <class 'float'>)
(50.0, 50.0)
string being formatted=50
(<class 'float'>, <class 'float'>)
(50.0, 50.0)
string being formatted=50-50
```

After a pip install of cython==0.29.13 I compile with:
```
PYTHONLIB=/usr/include/python3.5
CFLAGS="-shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -I${PYTHONLIB}"
cython --no-docstrings -3 cytest/test.py -o cytest/test.c
gcc $CFLAGS -o cytest/test.so cytest/test.c
```

Now the output is:
```
(<class 'float'>, <class 'float'>)
(50.0, 50.0)
string being formatted=50
(<class 'float'>, <class 'float'>)
(50.0, 50.0)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "cytest/test.py", line 16, in init cytest.test
    test_func_with_tuple(50.,50.)
  File "cytest/test.py", line 11, in cytest.test.test_func_with_tuple
    s = 'string being formatted=%d-%d' % (a,b)
ValueError: Unknown format code 'd' for object of type 'float'
```
This is the error I would get if did `1.2.__format__('d')`, but it appears that in the other case cython isn't using that function.

The relevant c code output by cython is:
```
  /* "cytest/test.py":4
 *   print((a.__class__, b.__class__))
 *   print((a, b))
 *   s = 'string being formatted=%d' % a             # <<<<<<<<<<<<<<
 *   print(s)
 * 
 */
  __pyx_t_3 = __Pyx_PyUnicode_FormatSafe(__pyx_kp_u_string_being_formatted_d, __pyx_v_a); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 4, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_3);
  __pyx_v_s = ((PyObject*)__pyx_t_3);
  __pyx_t_3 = 0;

```

```
  /* "cytest/test.py":11
 *   print((a.__class__, b.__class__))
 *   print((a, b))
 *   s = 'string being formatted=%d-%d' % (a,b)             # <<<<<<<<<<<<<<
 *   print(s)
 * 
 */
  __pyx_t_3 = PyTuple_New(4); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 11, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_3);
  __pyx_t_4 = 0;
  __pyx_t_5 = 127;
  __Pyx_INCREF(__pyx_kp_u_string_being_formatted);
  __pyx_t_4 += 23;
  __Pyx_GIVEREF(__pyx_kp_u_string_being_formatted);
  PyTuple_SET_ITEM(__pyx_t_3, 0, __pyx_kp_u_string_being_formatted);
  __pyx_t_2 = __Pyx_PyObject_Format(__pyx_v_a, __pyx_n_u_d); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_t_5 = (__Pyx_PyUnicode_MAX_CHAR_VALUE(__pyx_t_2) > __pyx_t_5) ? __Pyx_PyUnicode_MAX_CHAR_VALUE(__pyx_t_2) : __pyx_t_5;
  __pyx_t_4 += __Pyx_PyUnicode_GET_LENGTH(__pyx_t_2);
  __Pyx_GIVEREF(__pyx_t_2);
  PyTuple_SET_ITEM(__pyx_t_3, 1, __pyx_t_2);
  __pyx_t_2 = 0;
  __Pyx_INCREF(__pyx_kp_u_);
  __pyx_t_4 += 1;
  __Pyx_GIVEREF(__pyx_kp_u_);
  PyTuple_SET_ITEM(__pyx_t_3, 2, __pyx_kp_u_);
  __pyx_t_2 = __Pyx_PyObject_Format(__pyx_v_b, __pyx_n_u_d); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_t_5 = (__Pyx_PyUnicode_MAX_CHAR_VALUE(__pyx_t_2) > __pyx_t_5) ? __Pyx_PyUnicode_MAX_CHAR_VALUE(__pyx_t_2) : __pyx_t_5;
  __pyx_t_4 += __Pyx_PyUnicode_GET_LENGTH(__pyx_t_2);
  __Pyx_GIVEREF(__pyx_t_2);
  PyTuple_SET_ITEM(__pyx_t_3, 3, __pyx_t_2);
  __pyx_t_2 = 0;
  __pyx_t_2 = __Pyx_PyUnicode_Join(__pyx_t_3, 4, __pyx_t_4, __pyx_t_5); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_2);
  __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
  __pyx_v_s = ((PyObject*)__pyx_t_2);
  __pyx_t_2 = 0;
```

It looks like the __Pyx_PyUnicode_FormatSafe function is being used only in the first case and not in the second, which may or may not be relevant. I am using Python 3.5.2. 

If there is any other information needed let me know

**Comment by dannyjeck** [comment]
I should also mention I'm compiling on ubuntu 16.04

**Comment by brendan-matroid** [comment]
Does this apply to brace-formatted strings too?

**Comment by scoder** [comment]
Looks like this is a difference between `%`-formatting and `format()`/f-strings. Cython optimises some cases of the former into f-strings, that's why this occurs.

I think the right fix would be to generate a bit of additional code that checks if the format value is an integer, and if not, passes it through `PyNumber_Int()`. Tests will show if the behaviour is the same in Py2 and Py3, and if both need this adaptation.

**Comment by BoBoThein** [comment]
. Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
bash is already the newest version (5.0.11).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ ls
README.md  brute.py  password.txt
$ python3 brute.py
Traceback (most recent call last):
  File "brute.py", line 2, in <module>
    exec(marshal.loads('c\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00@\x00\x00\x00s\xaf\x01\x00\x00d\x00\x00d\x01\x00l\x00\x00Z\x00\x00d\x00\x00d\x01\x00l\x01\x00Z\x01\x00d\x00\x00d\x01\x00l\x02\x00Z\x02\x00d\x00\x00d\x01\x00l\x03\x00Z\x03\x00d\x00\x00d\x01\x00l\x04\x00Z\x04\x00d\x00\x00d\x01\x00l\x05\x00Z\x05\x00e\x00\x00j\x06\x00d\x02\x00\x83\x01\x00\x01d\x03\x00\x84\x00\x00Z\x07\x00e\x01\x00j\x08\x00d\x04\x00k\x02\x00s|\x00e\x01\x00j\x08\x00d\x05\x00k\x02\x00r\xf4\x00d\x06\x00Z\t\x00d\x07\x00Z\n\x00d\x08\x00Z\x0b\x00d\t\x00Z\x0c\x00d\n\x00Z\r\x00d\x0b\x00Z\x0e\x00d\x0c\x00Z\x0f\x00d\r\x00Z\x10\x00d\x08\x00Z\x11\x00d\x0e\x00Z\x12\x00d\n\x00Z\x13\x00d\x0f\x00Z\x14\x00d\x0c\x00Z\x15\x00e\n\x00e\x0b\x00e\x0c\x00e\r\x00e\x0e\x00e\x0f\x00f\x06\x00Z\x16\x00e\x04\x00j\x17\x00e\x16\x00\x83\x01\x00Z\x18\x00n\x00\x00d\x10\x00\x84\x00\x00Z\x19\x00e\x19\x00\x83\x00\x00\x01e\x1a\x00e\x1b\x00e\x0c\x00d\x11\x00\x17e\x0b\x00\x17d\x12\x00\x17e\x10\x00\x17d\x13\x00\x17\x83\x01\x00\x83\x01\x00Z\x1c\x00e\x1a\x00e\x1b\x00e\x0c\x00d\x11\x00\x17e\x0b\x00\x17d\x14\x00\x17e\x10\x00\x17d\x13\x00\x17\x83\x01\x00\x83\x01\x00Z\x1d\x00d\x15\x00Z\x1e\x00d\x1f\x00g\x01\x00Z\x1f\x00d\x18\x00\x84\x00\x00Z\x07\x00d\x19\x00\x84\x00\x00Z \x00d\x1a\x00\x84\x00\x00Z!\x00d\x1b\x00\x84\x00\x00Z"\x00d\x1c\x00\x84\x00\x00Z#\x00d\x1d\x00\x84\x00\x00Z$\x00e%\x00d\x1e\x00k\x02\x00r\xab\x01e \x00\x83\x00\x00\x01n\x00\x00d\x01\x00S( \x00\x00\x00i\xff\xff\xff\xffNt\x05\x00\x00\x00clearc\x01\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00sG\x00\x00\x00x@\x00|\x00\x00d\x01\x00\x17D]4\x00}\x01\x00t\x00\x00j\x01\x00j\x02\x00|\x01\x00\x83\x01\x00\x01t\x00\x00j\x01\x00j\x03\x00\x83\x00\x00\x01t\x04\x00j\x05\x00d\x02\x00d\x03\x00\x15\x83\x01\x00\x01q\x0b\x00Wd\x00\x00S(\x04\x00\x00\x00Ns\x01\x00\x00\x00\ng\x00\x00\x00\x00\x00\x00$@id\x00\x00\x00(\x06\x00\x00\x00t\x03\x00\x00\x00syst\x06\x00\x00\x00stdoutt\x05\x00\x00\x00writet\x05\x00\x00\x00flusht\x04\x00\x00\x00timet\x05\x00\x00\x00sleep(\x02\x00\x00\x00t\x01\x00\x00\x00st\x01\x00\x00\x00c(\x00\x00\x00\x00(\x00\x00\x00\x00t\x00\x00\x00\x00t\x07\x00\x00\x00runntek\r\x00\x00\x00s\x08\x00\x00\x00\x00\x01\x11\x01\x10\x01\r\x01t\x05\x00\x00\x00linuxt\x06\x00\x00\x00linux2s\x07\x00\x00\x00\x1b[96;1ms\x07\x00\x00\x00\x1b[34;1ms\x07\x00\x00\x00\x1b[33;1ms\x07\x00\x00\x00\x1b[32;1ms\x06\x00\x00\x00\x1b[0;1ms\x07\x00\x00\x00\x1b[31;1ms\x07\x00\x00\x00\x1b[36;1ms\x05\x00\x00\x00\x1b[34ms\x05\x00\x00\x00\x1b[32ms\x05\x00\x00\x00\x1b[31mc\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00C\x00\x00\x00s\x03\x01\x00\x00d\x01\x00GHt\x00\x00t\x01\x00d\x02\x00\x17\x83\x01\x00\x01t\x02\x00j\x03\x00d\x03\x00\x83\x01\x00\x01d\x04\x00GHt\x04\x00d\x05\x00\x17GHt\x04\x00d\x06\x00\x17t\x01\x00\x17d\x07\x00\x17t\x05\x00\x17d\x08\x00\x17GHt\x04\x00d\x06\x00\x17t\x01\x00\x17d\t\x00\x17t\x05\x00\x17d\n\x00\x17GHt\x04\x00d\x0b\x00\x17t\x01\x00\x17d\x0c\x00\x17t\x05\x00\x17d\r\x00\x17GHt\x06\x00d\x0e\x00\x17t\x04\x00\x17d\x0f\x00\x17t\x01\x00\x17d\x10\x00\x17t\x05\x00\x17d\x11\x00\x17GHt\x06\x00d\x0e\x00\x17t\x04\x00\x17d\x12\x00\x17GHt\x06\x00d\x0e\x00\x17t\x04\x00\x17d\x12\x00\x17t\x01\x00\x17d\x13\x00\x17t\x05\x00\x17d\x14\x00\x17GHt\x06\x00d\x0e\x00\x17t\x04\x00\x17d\x12\x00\x17t\x01\x00\x17d\x13\x00\x17t\x05\x00\x17d\x15\x00\x17GHt\x04\x00d\x16\x00\x17GHt\x04\x00d\x04\x00\x17GHd\x00\x00S(\x17\x00\x00\x00Ns\x1a\x00\x00\x00\n    \n    \n    \n    \n     s\x1f\x00\x00\x00      [-_-] HALLO BANGSAT [-_-]i\x01\x00\x00\x00t\x01\x00\x00\x00 s\x0c\x00\x00\x00      \xe2\x96\x84\xe2\x96\x84s\x11\x00\x00\x00     \xe2\x96\x88\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88s\x10\x00\x00\x00       AUTHOR : s\x0f\x00\x00\x00 Riski Darmawans\x10\x00\x00\x00       GITHUB : s\x1b\x00\x00\x00 https://github.com/FR13ND8s$\x00\x00\x00\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x88\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84s\r\x00\x00\x00    WA     : s\r\x00\x00\x00 085835787069s\x0c\x00\x00\x00\xe2\x96\x93\xe2\x96\x93\xe2\x96\x93\xe2\x96\x93s\x1b\x00\x00\x00\xe2\x96\x88\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88s\x0c\x00\x00\x00   FUNGSI : s\x15\x00\x00\x00 Hack Facebook Nargets\x1e\x00\x00\x00\xe2\x96\x88\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88s\x06\x00\x00\x00   >> s\x19\x00\x00\x00 JANGAN RECODE YA BANGSATs\x1a\x00\x00\x00 CAPEK GUA BUATNYA BANGSATs\'\x00\x00\x00\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x80\xe2\x96\x80\xe2\x96\x80\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88(\x07\x00\x00\x00R\n\x00\x00\x00t\x02\x00\x00\x00GLR\x05\x00\x00\x00R\x06\x00\x00\x00t\x02\x00\x00\x00WWt\x01\x00\x00\x00Rt\x01\x00\x00\x00B(\x00\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00R\t\x00\x00\x00t\x05\x00\x00\x00cover#\x00\x00\x00s\x1c\x00\x00\x00\x00\x06\x05\x01\x0e\x01\r\x01\x05\x01\t\x01\x19\x01\x19\x01\x19\x01!\x01\x11\x01!\x01!\x01\t\x01s\x03\x00\x00\x00[?]s\x13\x00\x00\x00 Masukkan ID Targets\x03\x00\x00\x00 : s\x13\x00\x00\x00 KETIK password.txts2\x00\x00\x00https://www.facebook.com/login.php?login_attempt=1sD\x00\x00\x00Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0s8\x00\x00\x00Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.1) Geckc\x01\x00\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00sG\x00\x00\x00x@\x00|\x00\x00d\x01\x00\x17D]4\x00}\x01\x00t\x00\x00j\x01\x00j\x02\x00|\x01\x00\x83\x01\x00\x01t\x00\x00j\x01\x00j\x03\x00\x83\x00\x00\x01t\x04\x00j\x05\x00d\x02\x00d\x03\x00\x15\x83\x01\x00\x01q\x0b\x00Wd\x00\x00S(\x04\x00\x00\x00Ns\x01\x00\x00\x00\ng\x00\x00\x00\x00\x00\x00$@id\x00\x00\x00(\x06\x00\x00\x00R\x01\x00\x00\x00R\x02\x00\x00\x00R\x03\x00\x00\x00R\x04\x00\x00\x00R\x05\x00\x00\x00R\x06\x00\x00\x00(\x02\x00\x00\x00R\x07\x00\x00\x00R\x08\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00R\t\x00\x00\x00R\n\x00\x00\x00I\x00\x00\x00s\x08\x00\x00\x00\x00\x01\x11\x01\x10\x01\r\x01c\x00\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00s\xc5\x00\x00\x00t\x00\x00j\x01\x00\x83\x00\x00a\x02\x00t\x03\x00j\x04\x00\x83\x00\x00}\x00\x00t\x02\x00j\x05\x00t\x06\x00\x83\x01\x00\x01t\x02\x00j\x07\x00t\x08\x00\x83\x01\x00\x01t\x02\x00j\t\x00|\x00\x00\x83\x01\x00\x01t\x02\x00j\n\x00t\x08\x00\x83\x01\x00\x01t\x02\x00j\x0b\x00t\x08\x00\x83\x01\x00\x01t\x02\x00j\x0c\x00t\x00\x00j\r\x00j\x0e\x00\x83\x00\x00d\x01\x00d\x02\x00\x83\x01\x01\x01t\x0f\x00\x83\x00\x00\x01t\x10\x00\x83\x00\x00\x01t\x11\x00\x83\x00\x00\x01d\x03\x00GHt\x12\x00t\x13\x00d\x04\x00\x17\x83\x01\x00\x01t\x12\x00t\x13\x00d\x05\x00\x17\x83\x01\x00\x01t\x14\x00j\x15\x00d\x02\x00\x83\x01\x00\x01t\x16\x00d\x08\x00\x17GHd\x00\x00S(\t\x00\x00\x00Nt\x08\x00\x00\x00max_timei\x01\x00\x00\x00R\r\x00\x00\x00s\x1e\x00\x00\x00MAAF PASSWORD TIDAK DI TEMUKANs#\x00\x00\x00BUATLAH LAGI password/Wordlist Kamui\x03\x00\x00\x00s\x06\x00\x00\x00[-_-] s\x12\x00\x00\x00[-_-] [-_-] [-_-] (\x17\x00\x00\x00t\t\x00\x00\x00mechanizet\x07\x00\x00\x00Browsert\x02\x00\x00\x00brt\t\x00\x00\x00cookielibt\x0c\x00\x00\x00LWPCookieJart\x11\x00\x00\x00set_handle_robotst\x05\x00\x00\x00Falset\x13\x00\x00\x00set_handle_redirectt\x04\x00\x00\x00Truet\r\x00\x00\x00set_cookiejart\x10\x00\x00\x00set_handle_equivt\x12\x00\x00\x00set_handle_referert\x12\x00\x00\x00set_handle_refresht\x05\x00\x00\x00_httpt\x14\x00\x00\x00HTTPRefreshProcessort\x07\x00\x00\x00welcomet\x04\x00\x00\x00lagit\x06\x00\x00\x00searchR\n\x00\x00\x00R\x10\x00\x00\x00R\x05\x00\x00\x00R\x06\x00\x00\x00R\x0f\x00\x00\x00(\x01\x00\x00\x00t\x02\x00\x00\x00cj(\x00\x00\x00\x00(\x00\x00\x00\x00R\t\x00\x00\x00t\x04\x00\x00\x00mainO\x00\x00\x00s \x00\x00\x00\x00\x02\x0c\x01\x0c\x01\r\x01\r\x01\r\x01\r\x01\r\x01\x1c\x01\x07\x01\x07\x01\x07\x01\x05\x01\x0e\x01\x0e\x01\r\x01c\x01\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00s\xe3\x00\x00\x00t\x00\x00j\x01\x00j\x02\x00t\x03\x00d\x01\x00j\x04\x00|\x00\x00\x83\x01\x00\x17\x83\x01\x00\x01t\x00\x00j\x01\x00j\x05\x00\x83\x00\x00\x01d\x02\x00t\x06\x00j\x07\x00t\x08\x00\x83\x01\x00f\x02\x00g\x01\x00t\t\x00_\n\x00t\t\x00j\x0b\x00t\x0c\x00\x83\x01\x00}\x01\x00t\t\x00j\r\x00d\x03\x00d\x04\x00\x83\x00\x01\x01t\x0e\x00t\t\x00j\x0f\x00d\x05\x00<|\x00\x00t\t\x00j\x0f\x00d\x06\x00<t\t\x00j\x10\x00\x83\x00\x00}\x02\x00|\x02\x00j\x11\x00\x83\x00\x00}\x03\x00|\x03\x00t\x0c\x00k\x03\x00r\xdf\x00d\x07\x00

**Comment by DirectAcces** [comment]
Nice

**Comment by DirectAcces** [comment]
Alternatieve tekst

**Comment by nickwilson330** [comment]
:)

**Comment by blankraza** [comment]
Nice

**Comment by wangjing123-wj** [comment]
毒贩夫妇的地方大数据

**Comment by omsunman** [comment]
😊

**Comment by nanlliu** [comment]
and can I work on this as a beginner?

**Comment by scoder** [comment]
@nanlliu depends. It probably needs a little bit of C knowledge, and a good understanding of how formatting works in Python (or the dedication to learn that).

I'd suggest to start by extending the '%' formatting tests in `tests/run/fstring.pyx`, then look at the generated C code and try to make sense of it. Look at `FormattedValueNode` in `ExprNodes.py` to see how the formatting is done, and the `_build_fstring()` method in `Optimize.py` to see how '%' formatting is mapped to f-strings. There's probably more than one case in which the mapping is incorrect. Find those, and then the next step is to find a good way how to resolve those, either with something in the Python code or with some additional C code.

**Comment by nanlliu** [comment]
ok. I will dedicate myself to learn! I have experience of both python and c++, hopefully learning C is not too bad.

**Comment by scoder** [comment]
@nanlliu any progress? Anything we can help with?

**Comment by nanlliu** [comment]
oh shoot. my bad! I have been working on another issue for another project! actually i haven't started it yet since i had so many things going on. If someone else would like to take it, that's totally fine. Im really sorry. If no, then I would come back and work on this

**Comment by scoder** [comment]
I think I found a nice way of doing this in #3589.
