### ISSUE TITLE
Template function overloading

### ISSUE THREAD

**Issue by nikhil003** [cython/cython#3126]
Hi,

I am trying to wrap some c++ code, where I have a templated function and the function is overloaded with different types of input argument. I was wondering whether it can be handled in cython. When I try to compile my code, I get error

**"Cannot assign type 'vector[Coordinate[float]]' to 'Coordinate[float]'**

It seems like the I am not able to use overloading correctly, though the different data types work without any problem. 

Here is my declaration in .pxd file

```python
cdef extern from "header.h" namespace "Namespace":
    bool convert[T](vector[Coordinate[T]] &c, Json &to_, Json &from_)
    bool convert[T](Coordinate[T] &c, Json &to_, Json &from_)
```

and here is the code in pyx file

```python
cpdef bool _convert_d(_Coordinate_d inp, _cy_json proj_to, _cy_json proj_from):
    """transform input coordinate of double type from source to destination projection
    """
    cdef bool out
    out = convert[double](deref(inp.thisptr), deref(proj_to.thisptr), deref(proj_from.thisptr))

cpdef bool _convert_points_d(double[:, :] inp, _cy_json proj_to, _cy_json proj_from):
    """transform input coordinate of double type from source to destination projection
    """
    cdef bool out
    cdef vector[Coordinate[double]] _list_of_coordinates
    cdef int i, nx
    nx = <int> inp.shape[0]
    for i in range(nx):
        _c = _Coordinate_d(inp[i, 0], inp[i, 1])
        _list_of_coordinates.push_back(deref(_c.thisptr))
    out = convert[double](_list_of_coordinates, deref(proj_to.thisptr), deref(proj_from.thisptr))
```

**Comment by nikhil003** [comment]
It seems that the function can be overloaded if I separately declare function with the desired data type. I will close this issue for now.

**Comment by hinxx** [comment]
@nikhil003 can you elaborate on your last comment, please? I'm hitting similar issue with the code I'm trying to wrap.
