### ISSUE TITLE
Missing Python.h in generated header

### ISSUE THREAD

**Issue by gerion0** [cython/cython#3133]
Consider the following minimal example:

foo.pyx
```Cython
# cython: language_level=3
from cpython.ref cimport PyObject

cdef public struct Foo:
    PyObject* bar
```
Compiling this with:
```
cython --cplus foo.pyx -o foo.cpp
```
results in an `foo.h` header. Embedding this standalone, e.g.:
main.c
```C
#include "foo.h"

int main() {
        return 0;
}
```
does not compile (since `#include "Python.h" is missing):
```
% g++ main.c
In file included from main.c:1:
foo.h:15:3: error: 'PyObject' does not name a type
   15 |   PyObject *bar;
      |   ^~~~~~~~
In file included from main.c:1:
foo.h:43:1: error: 'PyMODINIT_FUNC' does not name a type
   43 | PyMODINIT_FUNC initfoo(void);
      | ^~~~~~~~~~~~~~
```
I saw the option `--capi-reexport-cincludes` that results in some includes. However, `Python.h` is still missing, when using it. Is there an existing way to embed this include in the header? Otherwise it would be nice if you modify the compiler to inlucde `Python.h`.

**Comment by scoder** [comment]
Admittedly, not a big use case given that you probably can't make much use of the header file without importing "Python.h" yourself, but then, since the header file itself depends on it, why not make sure it's there?
