### ISSUE TITLE
Cython compile with C++ is much slower than C

### ISSUE THREAD

**Issue by zhqu1148980644** [cython/cython#3144]
Module compiled from C/C++(code) with `extern` in C++ mode `runs two times slower` than module compiled in C mode. My code roughly does a bunch of looping and multiplication job.

**Comment by scoder** [comment]
Could you give a short, reproducible example that exhibits this? Very often, such performance differences are just due to different compiler flags of the C and C++ compiler.

**Comment by zhqu1148980644** [comment]
@scoder I can't reproduce this right now.(Currently, module compiled by C and C++ performs the same speed after I updated my code.)
