### ISSUE TITLE
Initializing array with values requires GIL?

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#3160]
When trying to compile the following code with Cython, I get the error message below.

```cython
cdef void func() nogil: 
    cdef int[4] a = [0, 1, 2, 3]
```

```cython
/Users/jkirkham/miniconda/envs/cython/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/jkirkham/test.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
cdef void func() nogil: 
    cdef int[4] a = [0, 1, 2, 3]
        ^
------------------------------------------------------------

test.pyx:2:9: Slicing Python object not allowed without gil
```

Dropping the `nogil` makes the error go away. However the C code generated looks something like this and as such doesn't appear to be using the GIL.

```c
static void __pyx_f_4test_func(void) {
  ...

  int __pyx_t_1[4];

  __pyx_t_1[0] = 0;
  __pyx_t_1[1] = 1;
  __pyx_t_1[2] = 2;
  __pyx_t_1[3] = 3;

  ...
}
```

**Comment by jakirkham** [comment]
Also if I write the code like so, it appears I've run into issue ( https://github.com/cython/cython/issues/1662 ).

```cython
cdef void func() nogil: 
    cdef int[4] a
    a[:] = [0, 1, 2, 3]
```

**Comment by atomtrading** [comment]
Same issue I encounter right now.

**Comment by scoder** [comment]
Looks like the GIL check in `SliceIndexNode` is too broad and does not detect the "simple" cases that work without GIL.
PR welcome.

**Comment by atomtrading** [comment]
I had quick look at ExprNode.py but I wouldn't know where to start, Im not familiar at all with the Cython code base.

**Comment by HeeebsInc** [comment]
any fix to this?

**Comment by matusvalo** [comment]
I suppose that the problem is that `SliceIndexNode` has disallowed GIL:

https://github.com/cython/cython/blob/d085015f5afcdfa246f8af61d0f77b9734ac69f6/Cython/Compiler/ExprNodes.py#L5420

`nogil_check()` method should be implemented for `SliceIndexNode` to decide when GIL is allowed and when not - e.g. as here:

https://github.com/cython/cython/blob/d085015f5afcdfa246f8af61d0f77b9734ac69f6/Cython/Compiler/ExprNodes.py#L731-L736
