### ISSUE TITLE
Release 0.29.14

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#3177]
Would be great to have a new release. Am curious what the timeline for 0.29.14 might be.

**Comment by h-vetinari** [comment]
@scoder
Do you have any plans/ideas for this already?

**Comment by scoder** [comment]
Done.

**Comment by scoder** [comment]
I couldn't get a Py3.8 wheel built for MacOS, though. PR welcome that fixes it, both in the local travis config and (especially) here:
https://github.com/MacPython/cython-wheels
https://travis-ci.org/MacPython/cython-wheels/builds/606100226
