### ISSUE TITLE
metaclasses added to a class using the six.add_metaclass decorator

### ISSUE THREAD

**Issue by kdschlosser** [cython/cython#3207]
This may be a bug or it could be simply a question I am not sure. I do know that using the six.add_metaclass decorator appears to not work.

This is what I am attempting to do.

I have a sizeable library some 200K lines of code. There is quite a bit of "voodoo magic" code using metaclases. this is done to dynamically add parent classes based on specific input at the time a class instance is needed.

The majority of the library is python code there is a separate extension that does get compiled and is used by the library. This extension does not have any metaclasses as it does rely on c++ code.

The portion of the library I am attempting to compile into extension modules is only for the purposes of increased performance. The code in pure python that I am trying to compile.

I know that Cython does support support metaclasses for python classes. So this should not be an issue. What I am seeing is that the cythonizing process only looks for (metaclass=some_meta_class) or \_\_metaclass\_\_ = some_meta_class. The issue I am having is that the library I am writing needs to be able to support python 2.7.x and 3.5+. I do not want to have to maintain 2 sets of code for something as simple as this. That is the reason why there is the six.add_metaclass decorator so 2 sets of code would not have to be in place.

My question is this.. Does Cython know to look for the @six.add_metaclass(some_metaclass) before a class definition?. 

If it does not is this something that could be added?. I know I can write into the build process parsing the files and place the metaclass declaration where it needs to be based on the python version, But seeing as how cython is supposed to support metaclasses It should also support having that decorator in place and make the adjustments needed in the cpp output file.

I do not know what the plans are for Cython when Python 2 becomes EOL. It is going to be a really long while before all programs that are running Python 2.x get upgraded to 3.x so I am hoping that Cython is going to continue to support Python 2.x and this can be added if it is not already.

If it is added then there is an issue with the metaclasses. I am using the \_\_init\_\_ of a metaclass to set in place a class attribute. and this class attribute is not getting defined. 

Any help would be greatly appreciated.

**Comment by TeamSpen210** [comment]
If you're compiling Cython code, there's not as strong a need to use `six`. Just use Python 3 syntax and it'll be translated back to the Python 2 equivalents where required. If you need it to be pure-Python too, you could always apply the decorator in a non-compiled module, or otherwise rearrange your code such that it's not affected by Cython. See #2800 for the EOL plan - soonish. Python 2.7 was released a decade ago, support is going to end eventually.

**Comment by kdschlosser** [comment]
OK so for the time being if I use the python 3 syntax Cython is going to do what it needs to do if compiled for Python 2. That's what I needed to know. after I wrote this I hammered out a simple bit of code that parses the files and removes the decorator. It really was not that hard to do because I had to iterate over the files and folders to change the extension from .py to .pyx and to move the files to a temp folder anyhow. so instead of using shutuil to copy the file I just make a new file using open to write the converted code.

**Comment by scoder** [comment]
You may also consider supporting Python 2.x *only* with compiled extension modules, by writing your code in Python 3 syntax and leaving the rest to Cython.

**Comment by kdschlosser** [comment]
At the moment because I am still developing the library I set the build routine up so that I can compile  the library as all c extension via a command line switch. I do also like being able to provide the option to the user if they want to use the library either way compiled as pyd's or as normal python. I personally like to be able to view the code in a library. it is easier for me to learn how to use it. once I have learned what it can do and wrote whatever it is i needed to interact with it if the option was there then i would switch it out for c extensions if available. I know that the speed difference is quite large. I still have to make the compile process multi threaded so it doesn't take 15 minutes to compile the thing. 

I am still running into an issue with the metaclass tho. and I am not sure what is causing it.

I wrote a test setup program and library with what I am trying to to do and that works without issue. but when I compile my library it does doesn't. The mechanics are the same so it should be working correctly.

There are only a few small differences in the build routine. The test library sub classes Cython.Distutils.extension.Extension so Cython has to be already installed. In the library I am having issue with the setup program installs Cython only for the build process. so I am not able to subclass the Extension class in Cython because it has not been installed yet. and I am not using the build_ext from Cython either.. actually I am not using it in the test either so that shouldn't be the issue. 

The thing is it compiles properly it just doesn't behave properly. That class attribute that gets set in the metaclasses \_\_init\_\_ does not get created and I am not sure why but it does get created in the test.. it's baffling.

**Comment by kdschlosser** [comment]
here is the cpp code that is generated by Cython for that section of the metaclass

```cpp

  /* "singleton.pyx":142
 *         super(InstanceSingleton, cls).__init__(name, bases, dct)
 * 
 *         cls._instances = getattr(cls, '_instances', {})             # <<<<<<<<<<<<<<
 * 
 *         if (
 */

#line 142 "singleton.pyx"
  __pyx_t_2 = __Pyx_PyDict_NewPresized(0); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 142, __pyx_L1_error)

#line 142 "singleton.pyx"
  __Pyx_GOTREF(__pyx_t_2);

#line 142 "singleton.pyx"
  __pyx_t_3 = __Pyx_GetAttr3(__pyx_v_cls, __pyx_n_s_instances, __pyx_t_2); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 142, __pyx_L1_error)

#line 142 "singleton.pyx"
  __Pyx_GOTREF(__pyx_t_3);

#line 142 "singleton.pyx"
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

#line 142 "singleton.pyx"
  if (__Pyx_PyObject_SetAttrStr(__pyx_v_cls, __pyx_n_s_instances, __pyx_t_3) < 0) __PYX_ERR(0, 142, __pyx_L1_error)

#line 142 "singleton.pyx"
  __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
```

I have to use the getattr with a default if it does not exist because of a dynamic class creation.

If i give a better description of how the program is supposed to run then maybe it might shed some light.

This library is a python binding to a cpp library called OpenZWave. OpenZWave is a library that handles communications with ZWave devices and those devices are wireless and use the ZWave protocol.

The way the protocol is written there are "modules" or pre defined sets of instructions these modules define what a device supports. the only way to know what the device supports is by querying the device. this does not take place in OpenZWave until after the device is added to the program.. The library I wrote follows the same layout as the ZWave protocol. so there is a python class that represents each of the modules.. and there are a lot of them.. over 100. I am using the metaclass to build the class that represents the device. part of the process is the dynamically created class sub classes the module classes the device supports.

I am starting to hate that word classes LOL

Now this does not seem to be all that difficult.. Unless... you only want a single instance that represents a device to ever be created.. Plus.. you also want to have an IDE be able to track a data path and also offer all of it's features... so the base class of the dynamic class is the same class that has the metaclass that builds the dynamic class and when the dynamic class gets made it is going to call the \_\_init\_\_ of the meta class again. and that is the reason why there is the getattr with the default because I do not want to erase any of the stored values if it already exists. This is where I believe the issue is with the Cython compilation is because of the getattr.

I am going to put the same kind of thing in place in my test program and see if the behavior gets duplicated.

**Comment by kdschlosser** [comment]
OK so I managed to get past that problem.. Even tho the code I had originally has worked fine without being compiled as a c extension I had to make some adjustments in order to get it to work properly when compiled. 

```cpp
/* "singleton.pyx":142
 *         super(InstanceSingleton, cls).__init__(name, bases, dct)
 * 
 *         cls._instances = getattr(cls, '_instances', {})             # <<<<<<<<<<<<<<
 * 
 *         if (
 */
```

you see the call to super is before the creation of the class attribute.. This is what it did not like. Not sure why. I had to move the the creation of the class attribute to before the call to super.. strange behavior. I even tried adding it to the dict passed to \_\_init\_\_ before the call to super and that did not work either. which it should have I would have thought. That is supposed to be what gets used when the class gets created to set any of the class level attributes/methods/properties.

This is what I tried and it did not work. maybe someone would be willing to explain to me why?
All 3 failures work without being compiled. it is only when it is compiled as a c extension there is an issue.

```python
class InstanceSingleton(type):

    def __init__(cls, name, bases, dct):
        super(InstanceSingleton, cls).__init__(name, bases, dct)
        cls._instances = getattr(cls, '_instances', {})
```

```python
class InstanceSingleton(type):

    def __init__(cls, name, bases, dct):
        dct['_instances'] = dct.get('_instances', {})
        super(InstanceSingleton, cls).__init__(name, bases, dct)
```

```python
class InstanceSingleton(type):

    def __init__(cls, name, bases, dct):
        super(InstanceSingleton, cls).__init__(name, bases, dct)
        if not hasattr(cls, '_instances'):
            cls._instances = {}
```


and this is what works.
```python
class InstanceSingleton(type):

    def __init__(cls, name, bases, dct):
        cls._instances = getattr(cls, '_instances', {})
        super(InstanceSingleton, cls).__init__(name, bases, dct)
```

**Comment by kdschlosser** [comment]
I am now onto the next problem.. I will open another issue for this.
