### ISSUE TITLE
ImportError with Python 3.8 MinGW

### ISSUE THREAD

**Issue by KmolYuan** [cython/cython#3213]
Building libraries with MinGW in Python 3.8 failed:

```bash
> python setup.py install
...
    from .xxx import xxx_func
ImportError: DLL load failed while importing xxx: The specified module could not be found.
```

This is also happened with `build_ext --inplace`.

Neither Cython built by MinGW or MSVC can't solve it.

Here is my CI links:

+ <https://ci.appveyor.com/project/KmolYuan/pyslvs/builds/28410219>
+ <https://ci.appveyor.com/project/KmolYuan/solvespace/builds/28410774>

**Comment by KmolYuan** [comment]
After preliminary test, the libraries without `cimport` still can import.

**Comment by KmolYuan** [comment]
Found the answer: <https://docs.python.org/3.8/library/os.html#os.add_dll_directory>

MinGW will link some dynamic libraries such as `libstdc++-6.dll` and `libgcc_s_seh-1.dll` in `mingw64/bin`. In Python 3.8, `PATH` and the current working directory are not longer used.
MSVC's import path is not interfered.

Check dependencies:

```batch
> dumpbin /dependents my_gnu_extension.cp38-win_amd64.pyd
...
Dump of file my_gnu_extension.cp38-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    python38.dll
    KERNEL32.dll
    msvcrt.dll
    libgcc_s_seh-1.dll
    libstdc++-6.dll
```

```python
import os
os.add_dll_directory('...\\msys64\\mingw64\\bin')  # installed path
import my_gnu_extension
```

More realistic way, we can embed standard libraries by static linking:

```sh
-static-libgcc -static-libstdc++ -Wl,-Bstatic,--whole-archive -lwinpthread -Wl,--no-whole-archive
```

```python
from setuptools import setup
from setuptools.command.build_ext import build_ext

link_args = ['-static-libgcc', '-static-libstdc++', '-Wl,-Bstatic,--whole-archive', '-lwinpthread', '-Wl,--no-whole-archive']

class Build(build_ext):
    def build_extensions(self):
        compiler = self.compiler.compiler_type
        if compiler == 'mingw32':
            e.extra_link_args = link_args
        super(Build, self).build_extensions()

setup(
    ...
    cmdclass={'build_ext': Build},
    ...
)
```

If Cython went to support MinGW, this patch should be included.

**Comment by KmolYuan** [comment]
Here's the todo list:

1. Mention this issue on doc (in the [part of MinGW](https://cython.readthedocs.io/en/latest/src/tutorial/appendix.html#appendix-installing-mingw-on-windows)).
1. Some compile option patch. (with `mingw32` compiler and Python 3.8+ detection)
    + Default to warn the users when cythonize.
    + `cythonize` function try to append the linking options automatically and remind size increasing.
    + **Warning: There's someone could missing standard static libraries `*.a`.**
1. Supports Cython installation.
    + When MinGW compiles with a `--no-cython-compile` Cython, this issue will comes.
    + This will not a matter when 2nd are done.

**Comment by scoder** [comment]
Documentation PR welcome.
For the rest, I don't see it in Cython's responsibility to configure the C compiler in any way. That's up to the user and distutils/setuptools.
