### ISSUE TITLE
FusedFunctionObject half-initialized during GC tracking

### ISSUE THREAD

**Issue by achernomorov** [cython/cython#3215]
There are new CPython behavior about GC tracking of half initialized objects  https://bugs.python.org/issue38392.

FusedFunctionObject is about to be in half-initialized state then base CyFunctionObject "constructor" calls GC_Track. 

So...
------
../Modules/gcmodule.c:2019: visit_validate: Assertion failed: PyObject_GC_Track() object is not valid
Enable tracemalloc to get the memory block allocation traceback

> 
> object address  : 0x7fcc7c1109b0
> object refcount : 1
> object type     : 0x7fcc6a4c1660
> object type name: fused_cython_function
> object repr     : <cyfunction get_nonzero_line at 0x7fcc7c1109b0>
> 
> Fatal Python error: _PyObject_AssertFailed
> Python runtime state: initialized

--------

**Reproduce**
-------
_Env_
python 3.9 ( latest from github) 
./configure --with-pydebug --enable-profiling
Python need to be build with PY_DEBUG - issue38392 is new functionality so it under PY_DEBUG for now.

_Code_

` import scipy.ndimage._ni_label`

**Comment by scoder** [comment]
Thanks for the report and the PR. I ended up rewriting parts of it in c964bfd to get a bit of additional cleanup along the way and avoid unused C function warnings.

**Comment by scoder** [comment]
Backported to 0.29.17 in b3c2e0d6791378a7361a1cc731ff93728b6a3d16.
