### ISSUE TITLE
pyrex_differences.html unclear about pyrex for loop syntax

### ISSUE THREAD

**Issue by dmoney** [cython/cython#3225]
In [pyrex_differences.html](https://cython.readthedocs.io/en/latest/src/userguide/pyrex_differences.html#list-set-dict-comprehensions), it says:

>  You can use the `for … from` syntax, too, but it is generally preferred to use the usual `for … in range(...)` syntax with a C run variable (e.g. `cdef int i`).

This was unclear to me, and I initially couldn't find any Python syntax that used "for ... from".  After I found [this page from Pyrex's docs](https://www.cosc.canterbury.ac.nz/greg.ewing/python/Pyrex/version/Doc/Manual/basics.html#mozTocId899067), I think it's referring to this kind of Pyrex loop:

    for 0 <= i < n: 
        ...

Should this be changed to something like the following?

> You can use Pyrex's `for 0 <= i < n` syntax too

I'm happy to submit the PR if so.

**Comment by da-woods** [comment]
There definitely is a `for ... from ...` loop. See test cases: https://github.com/cython/cython/blob/master/tests/run/forfrom.pyx, https://github.com/cython/cython/blob/master/tests/run/for_from_float_T254.pyx, https://github.com/cython/cython/blob/master/tests/run/addloop.pyx.

I don't know the full history, but I wonder if the `varname from` was made optional at some point. I guess the documentation could be made clearer to cover both varieties of "old-style" loops, but my opinion is the important bit is more the recommendation of what you should use (which is clear). My opinion is pretty unimportant of course :)

**Comment by scoder** [comment]
That page is for people who knew Pyrex before (probably not many any more) and want to understand what to look out for when migrating their code to Cython.

If you don't understand what that page is talking about, then that's a good thing. No need to look it up. The main point regarding this syntax is "don't use it".

**Comment by scoder** [comment]
Also, scrolling down a bit on that page will give you more examples of the `for … from …` syntax.
(We call it that in order to distinguish it from Python's normal `for … in …` loop, which you should be using instead.)

I generally consider all PRs, but I'll close this ticket since I think there's no real issue here.
