### ISSUE TITLE
 cython autoconverts uint8_t[32] using PyObject_FromCString(), stopping at NUL bytes

### ISSUE THREAD

**Issue by thefallentree** [cython/cython#3234]
So I have 
```
cdef struct A:
    uint8_t[32] buf
```
and when I access it ,  ```x = A.buf```  , default auto conversion is calling with ```PyObject_FromCString((const char*) A.buf)``` which rely on strlen() over an binary field,  obviously doesn't work,  the only way to get correct conversion is to use 
```
 x = <bytes> A.buf[:32] 
```

which force cython to use PyObject_FromCStringWithSize() , which works.  I'm using the latest 0.29.14 cython

**Comment by thefallentree** [comment]
ping ? anyone having the same issue?

**Comment by robertwb** [comment]
This is working as intended; `char[N]` is often used in C to store a zero-terminated string of up to 32 (including the terminator) characters. (Yes, C is ambiguous as this is also how to store a character array of exactly 32 characters. `uint8_t` is an alias for `char`.)

**Comment by thefallentree** [comment]
fixed length array should probably behave  differently than char * ,  or in other terms, there should be some kinda of warning or strict mode to warn people anytime the NULL-term conversion is used.  (because that could be wrong)

**Comment by robertwb** [comment]
The problem is that fixed length arrays of chars is ambiguous in `C`--it's often used for *both* null-terminated and non-null-terminated data (e.g. to allow it to be allocated as part of a struct). No matter which convention is picked, it's going to be wrong for many people, and changing it now would be backwards incompatible. At least writing `buf[:32]` (or even `buf[:sizeof(buf)]` gives an obvious way to resolve this ambiguity.

**Comment by thefallentree** [comment]
at least one issue with current auto-conversion scheme, the user need to be very careful never pass structs or pointers between cdef functions and python functions, because everytime it cross that boundary, it will be autoconverted and wrong.  The only solution is to excessively crop using buf[:sizeof(buf)] every time. 

Either we could try to refuse to do the wrong thing (force user to clarify), or at least we should give some warning so people don't get bite and have no idea why his array content got cropped seeming randomly.

**Comment by scoder** [comment]
I agree with @robertwb that this is impossible to "get right" for all users. Both ways to do it would be wrong for a large number of users, so keeping it the way it is now seems the best option. Starting to prevent users from doing something simple seems worse than what we have.

Documentation update welcome, if needed.

**Comment by da-woods** [comment]
I was wondering if we should revisit this a bit. I agree that stopping at the null terminator is the right thing to do. However, I don't see any reason why you'd want to go beyond the bounds of a known fixed-size array - that's always the wrong thing to do.

I'd suggest we should stopping at whichever comes first of the null terminator or the end of the array.

The only real downside (that I can see) is that this "fudged" hybrid behaviour would gives users the false impression that their code is correct (then they'd be surprised when they have an array containing a 0), while a crash would at least alert them quickly that it isn't.

**Comment by thefallentree** [comment]
I think that is even worse,  as previous comments said, if cython can't figure out the right thing to do , it should not try to be clever.  we should just change the default to require user clarification instead.  

I'm okay to write more verbose code that will work than being hit some default that never do correct thing 100% time.
