### ISSUE TITLE
Question: Why is PyString_CheckExact used (preventing str subclass returns)?

### ISSUE THREAD

**Issue by dmontagu** [cython/cython#3256]
Trying to debug the issue described in [this comment](https://github.com/samuelcolvin/pydantic/pull/799#issuecomment-560144353), I found that when a return type is annotated as `str`, Cython is preventing me from returning a *subclass* of `str`.

In particular, consider the following function: https://github.com/samuelcolvin/pydantic/blob/151143deb4eaf6a5e2dce4532659e5ee9e2e4713/pydantic/validators.py#L58-L61

```python
def strict_str_validator(v: Any) -> str:
    if isinstance(v, str):
        return v
    raise errors.StrError()
```

The generated C code for the return statement adds a `PyString_CheckExact`, which [doesn't allow returning a subclass of `str`](https://py3c.readthedocs.io/en/latest/reference.html#c.PyStr_CheckExact):
```
+058: def strict_str_validator(v: Any) -> str:
+059:     if isinstance(v, str):
+060:         return v
    __Pyx_XDECREF(__pyx_r);
    if (!(likely(PyString_CheckExact(__pyx_v_v))||((__pyx_v_v) == Py_None)||(PyErr_Format(PyExc_TypeError, "Expected %.16s, got %.200s", "str", Py_TYPE(__pyx_v_v)->tp_name), 0))) __PYX_ERR(0, 60, __pyx_L1_error)
    __Pyx_INCREF(__pyx_v_v);
    __pyx_r = ((PyObject*)__pyx_v_v);
    goto __pyx_L0;
+061:     raise errors.StrError()
```

Is there a reason `PyStr_CheckExact` is used instead of `PyStr_Check`?

Is there a workaround for this that would allow us to return subclasses of `str` without raising a `TypeError`? Our current workaround is to change the return type annotation to `typing.Union[str]` instead of `str`, but it would be great if we didn't have to do this.

**Comment by TeamSpen210** [comment]
Cython generally uses exact checks when doing type checks for builtins. It’s because if it’s known to be the exact subclass, Cython can use all the internal details of the string to optimise code - access the character array directly for example. If you set the [compile directive](http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives) `annotation_typing` to `False` Cython won’t use annotations for type checking.

**Comment by dmontagu** [comment]
Thanks for the info. In general, I would like to keep annotation typing on to preserve any resulting performance improvements; it's just this specific case is causing issues since this function sometimes needs to handle subclasses of `str`.

Based on this, I'm assuming that `Union[str]` is a reasonable (mypy-compatible) annotation to use for this purpose, but please let me know if there is a suggested alternative.

**Comment by TeamSpen210** [comment]
One thing you could do is move the annotations for these specific functions into a stub file.
