### ISSUE TITLE
Performance optimization of &-operator causes miscalculation

### ISSUE THREAD

**Issue by Baekalfen** [cython/cython#3258]
Commit 6d9daa08142e8a61d1f098fa0039b642537e614c causes a wrong result to be calculated in the example below. There seems to be something with the negative number, which makes it act unexpectedly.

This code snippet prints `1`:
```
x = -1
x &= 0xFF
print(x)
```

Before the commit, the code above would print `255`, which is also the case in CPython and PyPy without Cython.

**Comment by scoder** [comment]
Right, looks like there was a test missing for negative numbers. PR welcome.
