### ISSUE TITLE
Problem wrapping C macros in Cython

### ISSUE THREAD

**Issue by Keithcat1** [cython/cython#3264]
I was attempting to wrap this code in Cython but it uses macros that seem to support generic types, and there is no way of declaring a function in a cdef extern block to handle macros that are this generic.
I would love it if there was a keyword like 'macro' that I could use to tell Cython to just generate C code to call the macro, and allow the C compiler to figure out if the correct types are being used or not.

**Comment by da-woods** [comment]
You can use wrap it as:

    return_type MACRO_NAME(...)

i.e. writing `...` to indicate a C variadic function. You do need to specify a return type though, but it may not matter if this isn't exact. Obviously this can't handle the full macro syntax, but it can cope with most "function-like" macros.

**Comment by Keithcat1** [comment]
Wow, I didn't know Cython supported that. Strangely, I read through pretty much the entire documentation, and I never found it. This won't solve all my problems, but I love that it works. I would love if there was a way to declare return types in a similar way.
Thanks a lot!

**Comment by robertwb** [comment]
It's the syntax for declaring a variadic arguments like those used by printf, though this is a clever use. The return type is harder, as we have to know the return type at Cython compile time (e.g. to assign it to a variable or convert it to an object) but don't have any way to infer it.
