### ISSUE TITLE
Optimization: pystr.isprintable() -> Py_UNICODE_ISPRINTABLE(pystr)

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#3277]
I think these should be equivalent, but the generated C I'm seeing doesn't appear to be using Py_UNICODE_ISPRINTABLE.

**Comment by scoder** [comment]
`str.isprintable()` does not exist in Py2, so applying this optimisation would turn a Python runtime exception into a C compile time error.
Can be done in Cython 3.1.
