### ISSUE TITLE
optimization: str(x) -> PyObject_Str(x)

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#3279]
AFAICT they are equivalent.  Found a usage of PyObject_str [here](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/parsing.pyx#L929) and it looks like the optimization isn't made in other places where we just do `str(x)`.

I was happy to see that the usage of [PyUnicode_Join](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/tslibs/parsing.pyx#L1007) was unnecessary.

**Comment by scoder** [comment]
Yes, they are equivalent.

The optimisation for the 1-argument case can follow this example:
https://github.com/cython/cython/blob/5578a9ea829846589b1ace31c747ac207ffc1967/Cython/Compiler/Optimize.py#L2320

Note that this needs to behave "as expected" for the three language levels 2, 3str and 3, but I think that should be ok. IIRC, `str()` gets mapped to `unicode()` (which is already optimised) in LL-3, but not in LL-2/3str, where the new optimisation would apply.

**Comment by scoder** [comment]
Implemented in #3478.
