### ISSUE TITLE
Create a wheel for Alpine Linux

### ISSUE THREAD

**Issue by aviramha** [cython/cython#3286]
My Dockerfile that installs cython takes years to build because of compiling cython each time.
I think many will benefit from having a pre-built wheel for Alpine Linux, and the cost should be minimal.

I wanted to create a PR but couldn't find if there's automation for pushing to PyPi..

**Comment by scoder** [comment]
Could you explain why the current Linux wheels don't work for Alpine Linux?

**Comment by aviramha** [comment]
manylinux doesn't support musl-wheels right now. It seems to be a wider issue than relevant to Cython I assume.
I might create an alpine package to solve my issue :)

Thanks anyway.

**Comment by da-woods** [comment]
@aviramha You don't actually have to compile Cython - it runs fine (but slightly slower) uncompiled, so skip it if that's what's slowing you down.
