### ISSUE TITLE
RuntimeWarning: size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by jiapengwen** [cython/cython#3295]
```
from libcpp.vector cimport vector
from libcpp.string cimport string

ctypedef double input_t
ctypedef double rtn_t

cdef class NodeBase:
    cdef:
        public list bm_child_list
        public dict bm_kwargs
        public string version

        vector[rtn_t] bm_child_tree_last_value

def __init__(self, *args, **kwargs):
        self.bm_context = vector[input_t]()
        self.bm_child_list = [x for x in args]
        self.bm_kwargs = kwargs
        self.version = "v1.0.0"

        size = len(self.bm_child_list)
        # todo
        self.bm_child_tree_last_value = vector[rtn_t](size if size else 1)

cpdef rtn_t tick_update(self, int didx, int tidx, int sidx) except *:
        cdef rtn_t data = 0
        cdef NodeBase child_node
        cdef int i = 0
        if self.bm_child_list:
            # print("has child,size:", len(self.bm_child_list))
            for child_node in self.bm_child_list:
                child_node.tick_update(didx, tidx, sidx)
            data = self.drv_compute_value(didx, tidx, sidx)
            self.bm_child_tree_last_value[0] = data
        else:
            data = self.drv_compute_value(didx, tidx, sidx)
            self.bm_child_tree_last_value[0] = data

        return data

 cpdef rtn_t drv_compute_value(self, int didx, int tidx, int sidx) except *:
        return 1

```
use as follow:
```
 node_base1 = NodeBase()
    print(node_base1.tick_update(1,1,1))
    print(node_base1.tick_update(1,1,1))
    print(node_base1.tick_update(1,1,1))
    print(node_base1.tick_update(1,1,1))
    print(node_base1.tick_update(1,1,1))
```
but it get runtimeWarning， i can't understand
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: core.node_base.NodeBase size changed, may indicate binary incompatibility. Expected 88 from C header, got 120 from PyObject
  return f(*args, **kwds)

python version = 3.6.9
cython version = 0.29.13

please he'l'p me

**Comment by mattip** [comment]
The `bm_child_tree_last_value` field in your struct changes size. That will cause problems.

**Comment by jiapengwen** [comment]
> The `bm_child_tree_last_value` field in your struct changes size. That will cause problems.

if  bm_child_tree_last_value define in list, then will ok?

**Comment by da-woods** [comment]
I don't see why a vector field would be a problem - std::vectors as members of C++ classes are used extensively. I'd suspect that some source file/compiled module file is outdated and it just needs rebuilding properly

**Comment by scoder** [comment]
Agreed. Try to rebuild all Cython modules in your project (and projects that `cimport` from it / that it `cimport`s from) cleanly from scratch and see what that gives.

**Comment by jiapengwen** [comment]
> I don't see why a vector field would be a problem - std::vectors as members of C++ classes are used extensively. I'd suspect that some source file/compiled module file is outdated and it just needs rebuilding properly

rm *.so *.cpp， then rebuild, it run ok
thanks！！！
