### ISSUE TITLE
cast_bytes_py2 was removed from IPython in 7.11.0

### ISSUE THREAD

**Issue by sappjw** [cython/cython#3296]
It looks like the `cast_bytes_py2` utility function was removed from the IPython py3compat utils in version 7.11.0 ([see here](https://github.com/ipython/ipython/commit/a089b78315ef964f8552ffa52db569a8a924bfc2#diff-230d8a7c9440fa2ab8c6a3ebe9a9f279)).  There are some calls to this function in [Cython/Build/IpythonMagic.py](https://github.com/cython/cython/blob/master/Cython/Build/IpythonMagic.py).

**Comment by scoder** [comment]
See #3291.
