### ISSUE TITLE
Passing 2D Numpy Array To C using Memory Views

### ISSUE THREAD

**Issue by kris-singh** [cython/cython#3305]
Passing a 2D numpy array to underlying c function with the following API

``` python
cpdef func([:, :, ::1] a):
   c_func(&a[0, 0])
```

causes the following error Cannot Take the address of a memory view slice 
But,
```python
cpdef func(np.ndarray[double, ndim=2, 'c'] a):
   c_func(&a[0, 0])
```
works. Either there should be proper documentation for this type of behavior in docs saying the new typed memoryview doesn't support this yet or this feature should be implemented.

**Comment by da-woods** [comment]
Not a bug - count the dimensions of the memoryview version.

**Comment by kris-singh** [comment]
I see. I confused [:,  :,  ::1] as thinking of representing a 2d contiguous when it should have been [:, ::1]
