### ISSUE TITLE
Conditional `with nogil` does not compile

### ISSUE THREAD

**Issue by fzeiser** [cython/cython#3313]
I have problems compiling code with the conditional `with nogil()` block. After some trial and error with the code in the [Conditional GIL Acquiring / Releasing](https://cython.readthedocs.io/en/latest/src/userguide/fusedtypes.html#conditional-gil-acquiring-releasing) description, I tried to imitate two cases of the test suite (`tests/run/nogil.pyx` and `tests/run/nogil_conditional.pyx`).

I'm not sure about the guidelines for minimal examples here, but in order to keep the code here simple, I just put the code in a jupyter notebook.

``` py
%load_ext Cython

import Cython
Cython.__version__
# '0.29.14'
```

Following function using just `notgil` compiles:
``` py
%%cython
def test(int x):
    """
    >>> test(5)
    47
    >>> test(11)
    53
    """
    with nogil:
        f(x)
        x = g(x)
    return x


cdef void f(int x) nogil:
        cdef int y
        y = x + 42
        g(y)

cdef int g(int x) nogil:
        cdef int y
        y = x + 42
        return y
```

However, the next test with `nogil()` does not:

``` py
%%cython

def test(int x):
    """
    >>> test(0)
    110
    """
    with nogil(True):
        x = f_nogil(x)
        with gil(True):
            x = f_gil(x)
    return x
```
It returns
```

Error compiling Cython file:
------------------------------------------------------------
...
def test(int x):
    """
    >>> test(0)
    110
    """
    with nogil(True):
             ^
------------------------------------------------------------

/home/fabiobz/.cache/ipython/cython/_cython_magic_85c518a8fd9e570a122eb1e684613c64.pyx:7:14: Expected ':', found '('
 
```

Any ideas on what's going on?

**Comment by da-woods** [comment]
Looking at [changes.rst](https://github.com/cython/cython/blob/master/CHANGES.rst), this is a new feature coming in the Cython 3.0 release. I assume the online documentation is generated from the most recent git master, so is ahead of what's actually been released.

If this feature is important to you then you probably should get the absolute latest version from git. Otherwise you should wait for it to make it into a real release

**Comment by fzeiser** [comment]
Sorry, that should have been obvious! I should have selected "stable" in the menu of readthedocs, not the default "latest" Thanks!
