### ISSUE TITLE
Undefined dependency .gitrev

### ISSUE THREAD

**Issue by skaller** [cython/cython#3330]
Building on OSX. The Makefile contains an undefined dependency of .git on .gitrev.
Removing that, make repo doesn't nothing. However make all seems to work.

```
~>cd cython
~/cython>make repo
make: *** No rule to make target `.gitrev', needed by `.git'.  Stop.
~/cython>less Makefile
~/cython>make repo
make: Nothing to be done for `repo'.
~/cython>make all
python setup.py build_ext --inplace
```

Unfortunately for me, it is building stuff for the wrong version of Python:
```
creating build/lib.macosx-10.12-x86_64-2.7
```

i have zero interest in Python 2.7, I want 3.x. Is it possible to build a 3.x version?

**Comment by McSinyx** [comment]
> i have zero interest in Python 2.7, I want 3.x. Is it possible to build a 3.x version?

After reading the Makefile, I think Python runtime can be specified by the environmental variable `PYTHON`, e.g. `PYTHON=python3 make all`.

**Comment by skaller** [comment]
Actually its not clear how to find Python3 run time at all. I have several Pythons installed. The "official" python.org one is useless, there is no library to link against. They've been making this mistake for decades. The official Apple python2.7 has links in /usr/include and /usr/lib. I found 3.6.5 in my brew version, but I have no idea how to "point" at them. So its doubtful Cython's simple Makefile can work when none of the installers now to build Python correctly, including the originators. Even assuming Cython can work with 3.x.

**Comment by McSinyx** [comment]
> I found 3.6.5 in my brew version

How do you use it normally?  What error did you get when you ran `make` with `PYTHON` set to it?

> Even assuming Cython can work with 3.x.

It can, I'm using it now.

If all you want is to have Cython running (not hacking/contributing to the project), just use the PyPI version, which can be installed via  [pip](https://pip.pypa.io/en/latest/).  For installing from the git repo, `python3 setup.py install --user` would be sufficient--`make` is not needed in your case.

**Comment by skaller** [comment]
I'm not interesting in "using" it in the normal sense. I'm actually building a Felix binding to Python. Felix is a C++ code generator which can currently generate Python 3 modules. So roughly, it can do the same thing as Cython, only with a quite different source language. I can't generate types yet, and there is no binding to the Python API.

So looking for tools that might help, Cython looked by far the best. I haven't tried to set PYTHON yet. Actually I now have a mess, trying to install several different Pythons in the hope I can actually find a run time library. As far as I can tell the official Python.org one doesn't have a run time library in the Framework. Anyhow the problem is, setting PYTHON to what?  When I have at least 3 versions of it, its not clear which one to use.

**Comment by scoder** [comment]
I wonder why you need to build Cython yourself in the first place. Why not just
`/…/your/python3.7 -m pip install Cython` ?

Note that you can also just install Cython as a pure Python package by passing `--no-cython-compile` to `setup.py`. Using the binary package (in which Cython compiled a couple of its performance critical modules itself) just makes it faster, which helps when it's used to compile many modules.

**Comment by skaller** [comment]
The point of this issue is that there is a bug in the Makefile, and a bug in the instructions on building the repository, both of which have trivial fixes: remove the dependency, and change the docs from make repo to just make all.

**Comment by McSinyx** [comment]
> The point of this issue is that there is a bug in the Makefile, and a bug in the instructions on building the repository, both of which have trivial fixes: remove the dependency, and change the docs from make repo to just make all.

I think it'd be more suitable to classify it as unclear documentation.  To quote the README:

> Note that Cython used to ship the full version control repository in its **source distribution**, but no longer does so due to space constraints. To get the full source history, make sure you have git installed, then step into the base directory of the Cython source distribution and type:
>
>     make repo

Note that `make all` actually do the making (sorry for the pun).

> I also hate pip. Last few times I tried to use it, following various people's instructions, it didn't work. 

I'm sorry to hear so.  As an user, `pip` is absolutely heaven for GNU/Linux, but the experience on macOS might differs. Note that you can just execute the setup script directly if you don't want the immediate layer.

> This is particularly important on MacOS because it doesn't come with a package manager, and lots of horrible conflicts and issues arise with installations, and Apple often provides usable binaries but fails to provide the associated developer files (headers, etc).

For this particular reason, when packaging your software, keep an eye on `pip`.  Building wheel with, say, `delocate` may prevent this inconvenience to your users.

Looking at your current use case, I think it'd be best to just `path/to/your/python3 setup.py install --user`.  `make repo` simply turn a `sdist` into a git repo, while probably you tried to run it on a clone of the GitHub one already.

**Comment by skaller** [comment]
Yes, I tried to build on a clone of the Git repo. I'll certainly take advice on packaging stuff for Python users down the track but that's way down the track!
