### ISSUE TITLE
PyDescr_NewWrapper

### ISSUE THREAD

**Issue by skaller** [cython/cython#3335]
In `Includes/cpython/descr.pxd` this line 24
```
    PyDescr_NewWrapper(PyTypeObject* cls, wrapperbase* wrapper, void* wrapped)
```
appears to be a function binding, but there is no specified return type. I don't know if this is an error or not but it is unusual, and is breaking my translator script which expects functions to have a particular lexical structure, including a specified return type. What's the correct return type?

**Comment by scoder** [comment]
Without an explicit type declaration, it's always `object` (as in Python).
I'll add it, though, to make it explicit.

**Comment by skaller** [comment]
Thanks. My script uses mechanical rules, mainly regexps, to parse the pxd files, so running it catches inconsistencies.  I've bound about 75% of the API so far in the sense the output type checks. Inconsistencies generate code that causes my compiler to barf so I can't ignore it.
