### ISSUE TITLE
Compiling a pxd file that uses libc and libcpp libraries together

### ISSUE THREAD

**Issue by atifemreyuksel** [cython/cython#3347]
I have tried to compile a pxd file which uses math functions in libc and map structure in libcpp together. 
Import lines of my code is put below:
```
#cython: boundscheck=False
#cython: wraparound=False
#cython: cdivision=True
#cython: nonecheck=False

# distutils: language = c++

cimport numpy as np
import numpy as np
from libcpp.math cimport pow, round, floor, sqrt, isnan, fmax, fmin, fabs, ceil, exp, fmod, NAN
from libcpp.map cimport map
```

And I tried to compile this file by using the following lines in the setup py:
```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
from Cython.Build import cythonize
import os
import numpy as np

setup(ext_modules=(cythonize([Extension(
                                        name="name", 
                                        sources=["name.pyx")],
                                        include_dirs=[np.get_include()],
                                        language="c++",
                                        extra_compile_args=["-std=c++14"]
                                    )
                              ]
                  )
      )
)
```
How can I compile this file succesfully? Is there anyone who solved this problem before?

Thanks for your help.

**Comment by McSinyx** [comment]
What's the problem?

**Comment by atifemreyuksel** [comment]
The error message includes `name.cpp:3130:111: error: 'isnan' was not declared in this scope` . I think it cannot see the C functions due to using `# distutils: language = c++`. The reason is the std namespace of C++ is used and there is no isnan function in libcpp of cython. 

Is there any way to solve this issue?

**Comment by robertwb** [comment]
It looks like you're running into something similar to https://stackoverflow.com/questions/18128899. Is an `#include <math.h>` not being included in your `name.cpp`? (I assume by `from libcpp.math` you meant `from libc.math`?

**Comment by atifemreyuksel** [comment]
Sorry, when I tried some different cases, I wrote `libcpp.math` wrongly.

I have a name.pxy file which has 
```
from libc.math cimport pow, round, floor, sqrt, isnan, fmax, fmin, fabs, ceil, exp, fmod, NAN
from libcpp.map cimport map
```

@robertwb, what is the **best practice** when you want to use c libraries and cpp libraries together in cython? I can use them together in Jupyter notebook but I cannot handle it when creating a script.

**Comment by da-woods** [comment]
If I understand that StackOverflow link correctly then including `<math.h>` should definitely including plain, unnamespaced `isnan`, but _may_ also include `std::isnan`. While including `<cmath>` should definitely include `std::isnan` but _may_ also include the unnamespaced `isnan`.

Therefore your code should work, and works for me (with the `from libc.math import ...`). I think this should be reported as a bug to the makers of your compiler/standard library.

You could of course write your own wrappings for the math functions in the `std` namespace (just copy and modify https://github.com/cython/cython/blob/master/Cython/Includes/libc/math.pxd).

It's possible there may be something else going wrong though. Is this the first, or the last, error message you get? The first is often most useful.

**Comment by robertwb** [comment]
This should just work. I second da-woods that it looks like an error with your C++ compiler or build environment. Do you get the same error when trying to compile the a tiny cpp file with nothing but

```
#include <math.h>
int main(int argc, int argv) {
  double x = argc;
  return isnan(x);
}
```

What about if you include such a file for your sources instead of the pyx in setup.py? (Try also adding

```
#include "numpy/arrayobject.h"
#include "numpy/ufuncobject.h"
```

and seeing if that gives you the error.)

**Comment by atifemreyuksel** [comment]
Hi again. I solved my problem by using two different source files which pyx file using only libc library and the other using only libcpp library. 

After this, I compile and call these files in my main code like below:
```
import setuptools
import pyximport
pyximport.install(setup_args={'include_dirs': np.get_include()})
from test_cython_c import *

from pyximport import install
old_get_distutils_extension = pyximport.pyximport.get_distutils_extension

def new_get_distutils_extension(modname, pyxfilename, language_level=None):
    extension_mod, setup_args = old_get_distutils_extension(modname, pyxfilename, language_level)
    extension_mod.language='c++'
    return extension_mod,setup_args

pyximport.pyximport.get_distutils_extension = new_get_distutils_extension
pyximport.install(setup_args={'include_dirs': np.get_include()})
from test_cython_cpp import *
```

Thanks to [How to configure pyximport to always make a cpp file?](https://stackoverflow.com/questions/21938065/how-to-configure-pyximport-to-always-make-a-cpp-file)

**Comment by scoder** [comment]
Ah, yeah… We should finally fix `pyximport` to use `cythonize()`, so that it picks up the module directives correctly. Sounds like yet another backwards incompatible thing to do for 3.0. `pyximport` has been essentially unmaintained for years now, which makes it hard to convince someone to put effort into it. But people still use it, so …

@atifemreyuksel, if using two modules is ok for you, that's fine. But it's definitely not necessary. Cython definitely has no problem with this and the C++ compiler should generally be able to deal with this as well. @robertwb gave you advice on what you can try to debug this problem.

**Comment by navytux** [comment]
It looks like if we switch `build_ext` to use `cythonize` internally, it will automaticlly make pyximport to use it: https://github.com/cython/cython/issues/3541.

**Comment by navytux** [comment]
correction: pyximport currently uses `old_build_ext`: https://github.com/cython/cython/blob/3de7a4b8fb7ce045222e13ca02541f6a70e89c2e/pyximport/pyxbuild.py#L13

if we switch it to `new_build_ext`, or to just `from Cython.Distutils import build_ext` and switch that build_ext to new implementation that is based on cythonize (#3541), then it will make this issue automatically done.

**Comment by scoder** [comment]
Closing, not a Cython issue.
