### ISSUE TITLE
Counterintuitive and quite bad overhead for `cpdef` functions with fused types?

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3356]
I'm getting very bad overheads when passing Python objects to `cpdef` functions with `ctypedef fused` arguments from within the Python interpreter.

Some level of overhead is to be expected and probably inevitable, but with arguments typed as fused types, **the extra latency is multiple orders of magnitude greater than the latency I get even when checking the types manually in Python**.

It's sufficient that in any small-to-medium sized function, **the majority of the execution time just gets eaten up by the fused type dispatching**.

### Demonstration code:

**fusedtest.py**
```python3
# distutils: language = c++
import cython

def no_overhead(var):
	# ~55ns
	return 0

def py_overhead(var):
	# ~60ns
	if isinstance(var, float):
		a = var
		return 0
	elif isinstance(var, int):
		b = var
		return 0

def fused_type_overhead(var):
	# ~370ns
	return 0

def fused_type_staticwrapped(var):
	# ~65ns
	if isinstance(var, float):
		a = var
		return fused_type_overhead(a)
	elif isinstance(var, int):
		b = var
		return fused_type_overhead(b)
```

**fusedtest.pxd**
```Cython
# distutils: language = c++
import cython

ctypedef fused fused_type_ohtest:
	double
	int

cpdef bint no_overhead(double var)

@cython.locals(a=cython.double, b=cython.int)
cpdef bint py_overhead(var)

cpdef bint fused_type_overhead(fused_type_ohtest var)

@cython.locals(a=cython.double, b=cython.int)
cpdef bint fused_type_staticwrapped(var)
```

### `timeit` results:

```python3
>>> min(timeit.repeat(stmt='vecdev.no_overhead(a)', setup='a=5.0', globals=globals(), repeat=1000, number=1000))
5.775999989054981e-05

>>> min(timeit.repeat(stmt='vecdev.py_overhead(a)', setup='a=5.0', globals=globals(), repeat=1000, number=1000))
6.097899995438638e-05

>>> min(timeit.repeat(stmt='vecdev.fused_type_overhead(a)', setup='a=5.0', globals=globals(), repeat=1000, number=1000))
0.000368557999991026

>>> min(timeit.repeat(stmt='vecdev.fused_type_staticwrapped(a)', setup='a=5.0', globals=globals(), repeat=1000, number=1000))
6.318700002339028e-05
```

---

I don't know nearly enough C++ or enough about the CPython API to say whether this is a valid and actionable issue on technical grounds, and I do understand that there must be some degree of overhead when inspecting the types of generic Python objects in order to choose a C/C++ specialization.

But as a user, I do think that this behaviour creates at least three separate problems on practical grounds:

1. **Direct performance impact:** As an example, I have a simple utility function in a library that accepts two arrays as arguments and returns a new array from the component-wise sums of the two input arrays. I wished to be able to have it accept multiple types of arrays and numeric types as arguments, so I set its arguments as fused types without yet modifying any parts of its code. Before using fused types, its performance was about on par with Numpy, taking about 1μs to sum two arrays of 1,000 `double`s. Just by using fused types, it instead takes 3μs to do the same. `cProfile.run()` seems to confirm that the extra time is spent in `myfile.py:427(__pyx_fuse_0_0my_func)`. In an Python program relying heavily on this function, **fully two thirds of the execution time would be taken up just by the fused type dispatcher**.

2. **Breaking convention of parity with pure Python:** When using Cython, partly because it just falls back on CPython calls by default, I at least find it easy to assume that compiled functions will perform generally at least approximately as well as their uncompiled Python equivalents. I know that unnecessarily typing other variables does sometimes add overhead as well due to the type checking— but in most cases, as long as the typing is done in a way that makes sense in that it serves the code's intended functionality, it seems safe to assume that your program code will only speed up, or at the very worst, stay about the same. I think the fact that it's relatively easy to gain performance and very hard to lose performance is a big part of why Cython's such a useful tool. **In this case, however, the automatically generated type checking code for fused types is slower than the naïve Python approach (using `isinstance()`) by about a factor of 100x.**

3. **Incentivisation of superfluous code:** Because the naïve Python approach using `isinstance()` introduces about a hundred times less overhead than using fused types, **the optimal approach for getting performance from functions when called from both Cython and Python seems to be to define a `cdef` function using fused types that can be specialized at compile time for in-Cython calls, and then manually write a separate `cpdef` wrapper for it that does its own type checking with `isinstance()` when called from regular Python**, like `fused_type_staticwrapped()` above. In addition to being generally messy, this introduces manually written code that should be superfluous given the automatic specialization and dispatch feature, and makes maintenance a bit painful. Aside from the direct impact, the performance dynamics thus also incentivise writing redundant and messy code.

**Comment by scoder** [comment]
Thanks for the detailed report, but it's a known issue. See #1385.

**Comment by scoder** [comment]
Help welcome, BTW. It's probably not difficult to implement, but no-one has done it so far.
