### ISSUE TITLE
Add SIMD hint to prange for effective compiler vectorization

### ISSUE THREAD

**Issue by fschlimb** [cython/cython#3374]
It's currently not possible to tell the compiler that a given (parallel) loop can be vectorized/SIMD'ized. 
We'd like to have a way to annotate pranges in a way that tells the compiler to vectorize the loop.

Cython uses OpenMP for its prange construct. OpenMP comes with a SIMD directive which does exactly that. When adding the `SIMD` to what cython generates for the following code, icc generates vectorized code which is then almost Vector-length/32 times faster:

```
@boundscheck(False)
@wraparound(False)
@cdivision(True)
@initializedcheck(False)
def black_scholes_par(int nopt,
				  float[::1] price,
				  float[::1] strike,
				  float[::1] t,
				  float rate,
				  float vol,
				  float[::1] call,
				  float[::1] put):
    # using [::1] is essential for autovectorization
	cdef int i
	cdef float P, S, a, b, z, c, Se, y, T
	cdef float d1, d2, w1, w2
	cdef float mr = -rate
	cdef float sig_sig_two = vol * vol * 2

    # In order to release the GIL for a parallel loop, code in the with block cannot
    # manipulate Python objects in any way.
	with nogil, parallel():
		for i in prange(nopt):
			P = price [i]
			S = strike [i]
			T = t [i]

			a = log(P / S)
			b = T * mr
			
			z = T * sig_sig_two
			c = 0.25 * z
			y = 1./sqrt(z)

			w1 = (a - b + c) * y
			w2 = (a - b - c) * y
			
			d1 = 0.5 + 0.5 * erf(w1)
			d2 = 0.5 + 0.5 * erf(w2)

			Se = exp(b) * S
			
			call [i] = P * d1 - Se * d2
			put [i] = call [i] - P + Se
```

I suggest adding a boolean flag `simd=[False|True]` to `prange`.

**Comment by ogrisel** [comment]
Why has this issue been closed @fschlimb?

**Comment by fschlimb** [comment]
@ogrisel As far as I remember the motivating example did not benefit from the "simd" directive. With proper ":" array notation cython generated code that at least the intel compiler vectorized even without. Let me know if you have an example where this would make a difference.
