### ISSUE TITLE
Typing special methods/magic methods in pure Python mode?

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3389]
`def` doesn't seem to be allowed in `.pxd` files, but it's required for special methods of extension types.

I think this means there's no way to type magic methods in pure Python mode without depending on `cython` being available in the module's namespace.

**Comment by will-ca** [comment]
Hm. I suppose you could use annotations for most cases, but probably not for types that don't have a direct Python equivalent (`cython.uint`, `ctypedef` types, etc).

**Comment by da-woods** [comment]
Most magic methods have a pretty strictly defined signature I think which Cython uses. 

You should be able to use annotations consisting of `cython.uint`, or a non-Python type defined in a `pxd` file.

A specific example would probably be useful.

**Comment by will-ca** [comment]
The [docs](https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html) seem to list the return type of most of the magic methods as simply `object`. I don't think the arguments types are statically typed either, since then rich comparison operators wouldn't be able to work with different types?

Mostly, aside from the inconsistency of not being able to define/declare everything together in the `.pxd` file, using `cython.uint` creates a dependency that `cython` is available in the module namespace, and I think using non-Python types defined in `.pxd` files will just result in a `NameError` when running purely in CPython.

E.G., I don't think there's any pure Python mode code that directly mirrors the following Cython code and 1) is still statically typed when compiled and 2) will run fine interpreted in CPython without monkey-patching the global namespace to include the `ctypedef not_in_py`:

```python
ctypedef fused not_in_py:
    int
    sometype

cdef class test_cls:
    def __init__(self, not_in_py arg):
        cdef not_in_py v
        v = arg+7
        print(v)
```

- `cpdef __init__(self, not_in_py arg)` in the `.pxd` file doesn't work, nor do `def` or `cdef`.

- Since the method can't be declared in the `.pxd`, `cython.locals(v=not_in_py)` has to go in the `.py` file instead.

- The Cython-dependent decorator is pretty well addressed with `Cython.Shadow.locals()`, but `not_in_py` won't resolve without monkey-patching it in at the start of the module (which, IIRC, might then cause Cython to complain about the apparent name conflict when compiling unless you take an ugly/obfuscuating route through `globals()`), and now some of the typing happens in the `.py` file while the rest is still in the `.pxd` file, both of which will make the code messier and maintenance harder.

- `def test_func(arg: not_in_py):`  would also raise `NameError("name 'not_in_py' is not defined")` while interpreted, and require creating the same problems in order to fix.

I'm definitely not saying this is a huge issue or an uncircumventible restriction on functionality, but it just seems kind of inconvenient that `.pxd` files are sufficient for basically all static typing use cases *except* for magic methods, especially since I'm not sure that there's an obvious reason why the syntax that's used for typing normal methods and functions can't or shouldn't also be usable with special methods.

I found this thread on `cython-users` from a while ago too where it sounded like this was a planned area of development, just not a priority:
https://groups.google.com/forum/#!topic/cython-users/UmIQ3xrd_x0

**Comment by da-woods** [comment]
Thanks - that makes a more sense. 

Ability to evaluate annotations won't be an issue in future versions of Python (https://www.python.org/dev/peps/pep-0563/) and you can get it from `__future__` now. Annotations can also take strings.

You can also declare fused types in the .py file https://cython.readthedocs.io/en/latest/src/userguide/fusedtypes.html#declaring-fused-types with `cython.fused_type`

With that said, when I try to run your example I get a "This may never happen, please report a bug" assertion error - I this is to do with when the function marks itself as having fused arguments, and should be an easy fix.

---------------------------------

I don't think I have an opinion on whether being able to specify `def` functions in .pxd files makes sense. If it does make sense then in should probably apply to everything and not just special methods

**Comment by will-ca** [comment]
Ah. I hadn't actually compiled that code— my own use case is in pure Python mode where I've tried to keep Cython language features as confined to the `.pxd` file as possible, so I meant the `.pyx` code only to illustrate the kind of thing I wasn't able to cleanly do in that paradigm.

I guess the bit that ultimately feels a bit inconsistent to me, however, is that special methods seem to be about the only major language feature that can't be statically typed just from `.pxd` files, despite having nearly the same syntax and semantics as regular methods and functions when defined in `.pyx` files.

The `Cython.Shadow` functions provide a workaround, but I think putting declarations back in the `.py` file kind of undermines the purpose of having a `.pxd` file? I think there might also be other types that they don't presently provide a way to expose, like `libcpp.vector`.

The impression that I got was that special methods are already be treated differently from other functions and methods in that they're converted fully into C-level features when defined with `def`, and hence that it might make sense to support `def` in `.pxd` files for them specifically. I don't know if that's actually how it works though.

**Comment by scoder** [comment]
> def doesn't seem to be allowed in .pxd files, but it's required for special methods of extension types.

There is no use in defining (special/Python) methods of extension types in `.pxd` files currently.  That's why `def` is disallowed. Remember, `.pxd` files are for (shared) declarations, `.pyx` files are for the implementation. The only implementation that you can have in `.pxd` files are inline functions, since they can be copied into the `.pyx` files that use them.

**Comment by scoder** [comment]
Also, as @da-woods wrote, special methods have a specific C signature already, sometimes including C types. There are (almost) no cases where users should override or specialise those with static type annotations.

Fused types can be considered an exception here, because their dispatch mechanism can still be useful. That doesn't mean they have to be specified in `.pxd` files, though. Just use type annotations. It's generally a good idea to keep implementation specific behaviour local to the implementation, and not leak it out into `.pxd` files. And the (fused) argument types of special methods are purely implementation specific and irrelevant to the outside world.

Also see #1359 and #2120.

Can we close this ticket, or did I miss anything else?
