### ISSUE TITLE
address/pointer in Shadow shouldn't cast (which often fails) when type is already OK

### ISSUE THREAD

**Issue by memeplex** [cython/cython#3390]
For example, taking the address of recarray element fails in uncompiled pure-python cython.  `cython.address(feats[k])`, where `feats` is a recarray, fails with:

```
ValueError: Can't cast from structure to non-structure, except if the structure only has a single field.
```
The problem is in `Shadow.cast`, which is ultimately called by `address`:

```
...
    if hasattr(type, '__call__'):
        return type(*args)
    else:
        return args[0]
...
```

Not bullet-proof, but I believe you would be supporting more scenarios if you simply did't try to cast an argument which is already of the target type. And, in any case, I'm failing to see the point of that cast when you already have the right object, it's not that usual that a type can construct a new instance from an old one, nor it's a necessarily cheap operation.

So what about:

```
if isinstance(args[0], type) or not hasattr(type, '__call__'):
    return args[0]
else:
    return type(*args)
```

**Comment by memeplex** [comment]
Also note that, when compiled, I'm accessing the recarray as a struct-typed recarray, so the code is valid pure-python cython code, it just won't work if run with cpython.

**Comment by scoder** [comment]
Probably superseded by 48dc1f0169f81ed20c6b374941c2498ec94e57d0.

**Comment by scoder** [comment]
Closing. Feel free to reopen if it is still an issue.

**Comment by memeplex** [comment]
Ok, thanks!
