### ISSUE TITLE
Create subclass to cython array

### ISSUE THREAD

**Issue by Mibu287** [cython/cython#3396]
I wrote a simple class which subclass cython.array in **demo.pyx** file.

```
#cython: language_level = 3
#cython: embedsignature = True

from cython.view cimport array as cyarray

cdef class newarray(cyarray):
    pass
```
The code above compiled with no error. However, I could not import the module with error as below:

```
>>> import demo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "demo.pyx", line 1, in init demo
    #cython: language_level = 3
ModuleNotFoundError: No module named 'View'
```

I searched in **demo.c** file emitted by cython and found that the error occurred in one of the module's initialization function:

```
static int __Pyx_modinit_type_init_code(void)
...
 __pyx_t_1 = PyImport_ImportModule("View.MemoryView"); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 1, __pyx_L1_error)
__Pyx_GOTREF(__pyx_t_1);
__pyx_array_type = __Pyx_ImportType(__pyx_t_1, "View.MemoryView", "array", sizeof(struct __pyx_array_obj), __Pyx_ImportType_CheckSize_Warn);
```
Cython tried to import "View.MemoryView" using Python's default import routines. Since there was not any View module in search path ==> import fail.

However, I do not understand why Cython tried to import array type from other module. All information needed to create cython.array was already in the .c file. It only need to call PyModule_AddObject to add cython.array type to new module.

What did I do wrong or is that a bug?

I used Python 3.7.4 on MacOs, Cython 0.29.15.

**Comment by da-woods** [comment]
I don't know if inheriting from these internal types is a good idea or not, but it seems like it _should_ work.

**Comment by Mibu287** [comment]
@da-woods: I don't know if inheriting from internal types is a good idea or not, either. As I'm quite new to Cython, I'm in the process of discovering what I can or can not do with the language.

About your 2nd argument, I don't really understand why a class not implemented as a `cdef class` is not suppose to be inherited from. I thought a class implemented in C and is add to to module's namespace (PyModule_AddObject, PyDict_SetString, ...) can be sub-classed just fine? Could you please elaborate on this? Thanks in advance.

**Comment by da-woods** [comment]
https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#subclassing

> An extension type may inherit from a built-in type or another extension type:
> ...
> A complete definition of the base type must be available to Cython, so if the base type is a built-in type, it must have been previously declared as an extern extension type. 

(I think some of the common builtins may be known to Cython too). But the argument is that if it is considered an implementation detail then neither your nor Cython should have the information to subclass it. Maybe.

**Comment by Mibu287** [comment]
@da-woods: Thanks a lot. I’m gonna close this issue and wait for your PR to be accepted.

**Comment by da-woods** [comment]
Don't close the issues - it's still an issue _until_ the PR is accepted...
