### ISSUE TITLE
Cython files don't compile on Mingw-w64 64-bit

### ISSUE THREAD

**Issue by Keithcat1** [cython/cython#3405]
I can compile Cython generated code on the 32-bit version of Mingw, but on the 64-bit version, I get these errors:
C:\py>gcc -m64 pathfinder.cpp
pathfinder.cpp:215:41: warning: division by zero [-Wdiv-by-zero]
     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*))
 };
                                       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

pathfinder.cpp:215:79: error: division by zero is not a constant expression
     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*))
 };
                                                                               ^

pathfinder.cpp:215:41: error: '(1 / 0)' is not a constant expression
     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*))
 };
                                       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

pathfinder.cpp:215:79: error: enumerator value for '__pyx_check_sizeof_voidp' is
 not an integer constant
     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*))
 };
                                                                               ^

**Comment by KmolYuan** [comment]
Asked question can be solved by <https://github.com/cython/cython/issues/2670#issuecomment-432212671>.

You can simply apply this patch to `%PYTHON_DIR%\include\pyconfig.h`:

```patch
--- pyconfig.h	2016-01-27 10:54:56.000000000 +0300
+++ pyconfig.h	2016-03-28 11:46:48.000000000 +0300
@@ -100,6 +100,12 @@
 
 /* Compiler specific defines */
 
+#ifdef __MINGW32__
+#ifdef _WIN64
+#define MS_WIN64
+#endif
+#endif
+
 /* ------------------------------------------------------------------------*/
 /* Microsoft C defines _MSC_VER */
 #ifdef _MSC_VER
```

**Comment by Keithcat1** [comment]
Thanks, works.
Someone should send a PR to CPython so this issue doesn't pop up again.

**Comment by Elektriman** [comment]
this does not fix the issue.

**Comment by da-woods** [comment]
Trying to compile Python extensions on a different compiler to the one that Python was compiled with is typically a nightmare. See https://wiki.python.org/moin/WindowsCompilers for some of the details. Unless you have specifically built Python with MingW you'll probably find this a bad idea.

**Comment by xKRISTOFx** [comment]
@xKRISTOFx
