### ISSUE TITLE
MemoryView implementation incompatible with Options.cache_builtins = False

### ISSUE THREAD

**Issue by thirtythreeforty** [cython/cython#3406]
Disabling the `cache_builtins` option in setup.py:
```
Options.cache_builtins = False
```
causes code that uses `MemoryView` to fail to compile:
```
Error compiling Cython file:
------------------------------------------------------------
...
    if not is_slice:

        if start < 0:
            start += shape
        if not 0 <= start < shape:
            _err_dim(IndexError, "Index out of bounds (axis %d)", dim)
                    ^
------------------------------------------------------------

View.MemoryView:832:21: Accessing Python global or builtin not allowed without gil
```

(There are several such errors building the file, all stemming from doing a lookup on the exception type without the GIL held.)

To fix this, the GIL should be locked before calling _err_dim.

**Comment by da-woods** [comment]
I've done this a tiny bit differently to how you've suggested, since I think the whole point of `_err_dim` was avoiding writing duplicate `with gil:` code but the basic diagnosis was good.

**Comment by thirtythreeforty** [comment]
Great, thanks for the quick turnaround! Your way will prevent someone from mocking `ValueError`, but on the other hand I can't see anyone wanting to actually _do_ that, so it should work!

**Comment by da-woods** [comment]
> Your way will prevent someone from mocking ValueError, but on the other hand I can't see anyone wanting to actually do that, so it should work

I was just adding a comment to that effect in the PR description when you replied:

>I guess this slightly breaks the contract of the cache_builtins option, that you should be able to monkey-patch builtin stuff (including exceptions). With that said - it's an implementation detail that it's written in Cython. If it was written in C then it'd just use the standard exception definitions in the headers and the user wouldn't be able to change them anyway.

I think the "implementation detail" excuse makes it OK but we'll see if it makes it past review...
