### ISSUE TITLE
[Question] Is there a Cython variable to check if the running platform is 32-bits

### ISSUE THREAD

**Issue by MomIsBestFriend** [cython/cython#3407]
Is there a variable in the Cython API I could use to determine if I'm running of 32-bits? (or 64)

something that would look somewhat like this:

```python
from cython.foo.bar.baz import is_32_bits
```

That would be a ```bint``` (or with other type and value), so it could later be used in ```if/else``` statements.

---

What I am trying to ask is, what is the encouraged way to check if the running platform is 32-bits, inside a ```cython``` file?

**Comment by TeamSpen210** [comment]
You could do the following - check the size of the pointer type:

```python
from libc.stdint cimport intptr_t

if sizeof(intptr_t) == 4:
```

But it seems like a good idea for Cython to provide stuff like this as compile-time constants for `IF/ELIF/ELSE`.

**Comment by MomIsBestFriend** [comment]
@TeamSpen210 Thank you for the quick response :)

---

> You could do the following - check the size of the pointer type:
> 
> ```python
> from libc.stdint cimport intptr_t
> 
> if sizeof(intptr_t) == 4:
> ```

This does in fact better than the current code I have, so thank you for the better alternative.

My main motivation to check the running platform's bits using the Cython library, is to reduce the amount of external libraries that gets imported, and I am already importing Cython in (almost) every file.

> But it seems like a good idea for Cython to provide stuff like this as compile-time constants for `IF/ELIF/ELSE`.

That would be amazing :)

**Comment by scoder** [comment]
> But it seems like a good idea for Cython to provide stuff like this as compile-time constants for IF/ELIF/ELSE.

No. This is best done by the C compiler, not Cython. Otherwise, you'd have to generate separate C files for different architectures, which is fairly annoying. Better just generate the C file once and let the C compiler make something platform specific out of it.

**Comment by scoder** [comment]
> check the size of the pointer type

Or something else, depending on what behavioural information you actually need. Often enough, "is it 32 bits or not" isn't the best you can base your decisions on. Sometimes something more concrete like the size of a specific data type is better.

**Comment by scoder** [comment]
Closing this issue, since I don't think Cython should provide the "one way" for users to do this, which I don't think even exists.

**Comment by MomIsBestFriend** [comment]
Thank you @TeamSpen210 and @scoder you both helped a lot!
