### ISSUE TITLE
Parallelizing Cythonizing step of compilation

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#3412]
It's pretty awesome to be able to compile Cython code in parallel ( https://github.com/cython/cython/commit/1c4f32b93570b41de3c8028711549a32e15b31f1 ). Am wondering, would it be possible to extend this to the Cythonizing step as well?

**Comment by scoder** [comment]
That's what the commit does that you linked to. Am I missing something?

**Comment by jakirkham** [comment]
I could be mistaken, but I think that just parallelizes the compilation of the C/C++ code. Am asking about the generation of C/C++ code from Cython. Or are you saying that should  already be parallelized too?

**Comment by scoder** [comment]
Yes.
