### ISSUE TITLE
GCC crash with C functions in conditional expression.

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3418]
`.py`
```python3
def dynfuncswitch(val, preferleft=True):
	"""Causes gcc crash."""
	return (math.floor if preferleft else math.ceil)(val)
```
`.pxd`
```python3
from libc cimport math
```

The above code is valid Python, and it Cythonizes fine, but it causes a crash in `gcc`. Typing the arguments and return of the function does not change the behaviour.

```
error: assignment of function ‘double __pyx_t_1(double)’
19498 |     __pyx_t_1 = floor
```

**Comment by da-woods** [comment]
I'm relatively sure this is something I've fixed recently as part of a bigger PR.

https://github.com/cython/cython/blob/2a335975f705e0c40df2b593006a3cd0bb1bcf6f/Cython/Compiler/Code.py#L835-L837

If this is the right fix is it worth taking those three lines out and submitting them on their own?
