### ISSUE TITLE
Caching for `cython.inline()` does not differentiate between different compiler configurations.

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3419]
```python3
>>> cython.inline('def f(int a, int b):\n\treturn a/b\nreturn f', language_level=3)(5,2)
2.5
```

```python3
>>> cython.inline('def f(int a, int b):\n\treturn a/b\nreturn f', language_level=2)(5,2)
2
>>> cython.inline('def f(int a, int b):\n\treturn a/b\nreturn f', language_level=3)(5,2)
2
```

**Comment by scoder** [comment]
Interesting. I added the `language_level` to the module hash, but it seems to have no effect.

https://github.com/cython/cython/blob/0b81c765bf9b23138b83311e07aacec74517e778/Cython/Build/Inline.py#L193-L194

**Comment by will-ca** [comment]
I think that hash is being skipped entirely by the fast path at the very start of the function, which only takes into account the code string and (unbound?) argument signature:

https://github.com/cython/cython/blob/0b81c765bf9b23138b83311e07aacec74517e778/Cython/Build/Inline.py#L153-L162
