### ISSUE TITLE
Successful compilation of clearly nonsensical references before assignment?

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3423]
```python3
def bogusassignment():
	testvar = testvar
	return testvar
```
```python3
@cython.locals(testvar=cython.int)
cpdef int bogusassignment()
```

Code like this compiles and runs fine, but I'm not sure if there's any legitimate use cases where it would actually be intentional.

I'm also not totally sure exactly where the values assigned to the uninitialized variable are coming from, and whether there might be adverse security implications in being able to easily accidentally read from an unknown portion of memory:

```python3
def leakyread():
	charp = charp
	l = []
	for i in range(1000):
		b = charp[i]
		l.append(b)
	return b''.join(l)
```
```python3
@cython.locals(charp=cython.p_char, b=bytes, l=list)
cpdef bytes leakyread()
```

(Like, hypothetically, if `charp` above were used as part of a public-facing portion of a web application, and the environment it was running in allowed it to access passwords, keys, internal program state, etc?)

Ramble: This behaviour seems weird to me based on Python semantics, but I assume there must be valid uses cases for it to be explicitly allowed with a warning. I'm not familiar enough with low-level programming to understand all of those use cases, or to have a good gauge on how difficult it is to meaningfully differentiate between valid code and presumably nonsensical assignments like above. So, apologies if this is invalid or redundant.

**Comment by da-woods** [comment]
I don't think Cython enforces whether C variables are initialized. However there is [an optional warning `warn.maybe_uninitialized`](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#warnings). A simpler example (try it with and without the line `# cython: warn.maybe_unitialized = True`):

    def f():
        cdef int a
        return a

`gcc` (and probably other compilers) gives you a warning though so it's not _entirely_ silent. Either way I don't think this is a bug.
