### ISSUE TITLE
(Docs) __init__.pxd?

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3424]
It seems that making an `__init__.pxd` file in a Python/Cython package can allow c-importing the entire sub-namespace of the package in one statement.

If correct, this could probably bear [a mention](https://www.google.com/search?hl=en&q=%22__init__.pxd%22%20site%3Acython.readthedocs.io%2F) in the documentation.

**Comment by scoder** [comment]
Hmm.
1) Isn't this possible with a simple `__init__.py` as well?
2) If not, shouldn't we fix that, instead of requiring `__init__.pxd` files?

**Comment by mattip** [comment]
NumPy needed an `__init__.pxd` to allow [`from numpy.random cimport BitGenerator`](https://github.com/numpy/numpy/blob/master/numpy/random/_philox.pyx#L13) in cython code, where BitGenerator is a c-extension class from cython. In python we do `from numpy.random import BitGenerator`, but could not `cimport` it without the `__init__.pxd`. [This](https://github.com/numpy/numpy/blob/master/numpy/random/__init__.pxd) is the `__init__.pxd`. I tend to think of a  `__init__.pxd` as a cython header file.

**Comment by will-ca** [comment]
I think this is the behaviour that prompted me to make an `__init__.pxd` as well. I can't really check right now, but IIRC just doing `import` generated unoptimized code, while `cimport` on the package required an `__init__.pxd` file.

I think requiring an `__init__.pxd` file makes sense for `cimport`s of packages. A `.py` (and maybe `.pyx`? IDK.) module file can't be `cimport`ed without a `.pxd` file. It'd be congruent for a package, usually defined by a `__init__.py` file, to also require an `__init__.pxd` (which would have all the typing and other C-level information necessary for static compilation).

Note that it is possible to do regular `import`s; they just have to go through CPython and don't get optimized AFAICT. It also works fine to `cimport` the modules inside of a package without an `__init__.pxd` file in the package (e.g. `from cypkg.cysubpkg cimport cymodule`), but doing a `cimport` on the package itself requires `__init__.pxd` IIRC.

**Comment by scoder** [comment]
I think we should change that. It's ok to require an `__init__.pxd` file to import something from a non-empty package namespace (i.e. having actual declarations in the `__init__.pxd` file), but it shouldn't be necessary to have both a `.py` and a `.pxd` file just to make a directory a package that can be (c)imported from. That's just unnecessarily redundant. We should allow cimports from `.pxd` modules that live in ordinary Python packages.

**Comment by will-ca** [comment]
We *can* do `cimport`s from `.pxd` modules that live in ordinary Python packages, I'm pretty sure, so long as we explicitly specify the module.

So, with this structure:

```
pypkg
|—__init__.py
|—pymodule.py
|—pymodule.pxd
```

...We can already do any of:

`from pypkg cimport pymodule`
`cimport pypkg.pymodule`
`cimport pypk.pymodule as whatever`

...But we can't do:

`cimport pypkg`
`cimport pypkg as whatever`

Or anything else that imports the package namespace itself, I believe, unless we have an `__init__.pxd`.

I'm also not sure how the following form would (or should) resolve when we do have an `__init__.pxd`:

`from pypkg cimport somename`

...Since it's not immediately super clear whether Cython should be looking in the package directory for `somename.pxd`, or in `__init__.pxd` under the package directory for a definition/declaration/cimport for `somename`.

**Comment by scoder** [comment]
> immediately super clear whether Cython should be looking in the package directory for `somename.pxd`, or in `__init__.pxd` under the package directory for a definition/declaration/cimport for somename.

For cimports, if there's an `__init__.pxd`, then that's the package namespace, plus submodules and subpackages. If there's no `__init__.pxd` but only an `__init__.py`, then the (cimport) package namespace is empty and we only look for submodules and subpackages. That behaviour seems obvious to me.

It's as ambiguous as `from pkg import somename` in Python, that's all.
