### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by FNAFDecompiler** [cython/cython#3425]
Hey, how do I get the directive_defaults attribute into Cython.Compiler.Options using Command Prompt for Windows?

**Comment by McSinyx** [comment]
What do you mean, shouldn't it be set in `setup.py`?

**Comment by da-woods** [comment]
@McSinyx I assume this is trying to set the option from the `cython` or `cythonize` command?

I think this might be something that https://github.com/cython/cython/pull/3152/files would fix? Maybe?

**Comment by McSinyx** [comment]
Sorry I was unaware of it.

**Comment by FNAFDecompiler** [comment]
Like, I'm trying to activate the command "build_all.bat", but it says the following:
Traceback (most recent call last):
  File "build.py", line 28, in <module>
    directive_defaults = Options.directive_defaults
AttributeError: module 'Cython.Compiler.Options' has no attribute 'directive_defaults'

Could you help me with this?

**Comment by da-woods** [comment]
built_all.bat and build.py are not part of Cython. 

This commit suggests that `directive_defaults` hasn't existed for 4 years: https://github.com/cython/cython/commit/c6dfb487e474d3768a036f0d39d1d6e38de00c73

You should probably contact whoever wrote the library you're trying to use and ask them to update their build scripts.

**Comment by FNAFDecompiler** [comment]
You know, I want to use "get_directive_defaults()" in Command Prompt for Windows. Or could you give me an updated version of "build.py"?

I'm using AnacondaDecompiler, and it requires Cython.Compiler.Options to have the Directive Defaults attribute.

**Comment by McSinyx** [comment]
After a quick search it seems AnacondaDecompiler has been abandoned.  I could be wrong though, and I think your best shot would be trying to contact the project developer(s); or alternatively use an older version of Cython.

**Comment by scoder** [comment]
Not a Cython issue.
