### ISSUE TITLE
Renaming/aliasing imports (or other data) in .pxd files?

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3432]
I see this as a wishlist feature at most, but sometimes I will use syntax in Python like:

```python3
import package.subpackage.module_a, package.subpackage.module_b
subpackage = package.subpackage

do_stuff_with(subpackage.module_a.some_cls())
```

This makes it possible to explicitly import only the specified module(s) from a package, while still having a partial level of qualification on the modules' names in order to avoid cluttering/obfuscating the global namespace, without being too verbose either.

With `.pxd` files, the closest ways of doing this seem to be:

```python3
cimport package.subpackage.module_a, package.subpackage.module_b
```
```python3
do_stuff_with(package.subpackage.module_a.some_cls())
```

...which is more verbose, due to the fully qualified name, or:

```python3
from package.subpackage cimport module_a as subpackage_module_a, module_b as subpackage_module_b
```
```python3
do_stuff_with(subpackage_module_a.some_cls())
```

...Which is messier and less clear.

---

In Python, the rename occurs through an actual dynamic name/variable assignment to the module object, which obviously can't work for static declarations. Maybe the `=` operator could create aliases that denote (possibly textual) equivalence in certain cases?

**Comment by scoder** [comment]
Since `cimport … as …` and `from … cimport …` both exist already and do exactly what one would expect from Python, I'm very much against adding a special case feature that really just does the same thing and requires a lot of care in the implementation to restrict it to "things that should work" and exclude everything else. I would also like to avoid having to explain to users why these "things that should work" are the only things that work and everything else that looks and feels the same to them is being rejected.

**Comment by scoder** [comment]
I also disagree that `cimport … as …` is "messier and less clear". It's exactly what I do when I need this, and I consider it a good thing that it makes it clear at the very top of the file under which name something that gets imported is going to be used in the rest of the module.

**Comment by will-ca** [comment]
Ah, I meant that my specific example of of `from <packagename> cimport <modulename> as <packagename>_<modulename>` is less clear, in that it concatenated the package and module names using an underscore in lieu of a real dot/attribute.

I like to keep at least a couple levels of "dots" in front of imported names, so it's clear whenever it pops up in the rest of the code that the name isn't defined within the current module. But Python only supports the `from ... import ... as ...` format, which directly brings the imported names right into the module namespace, or the `import ...` format, which often leaves more levels of qualification and verbosity (and presumably attribute access overhead) than necessary. Hence, I settled on using full imports followed by assignments.

I appreciate the explicit explanation for keeping things as they are. Thank you.

Really, I guess my gripe is with Python semantics not providing a way to import names with partial qualification.

**Comment by scoder** [comment]
All of `from pkg cimport subpkg`, `import pkg.subpkg as subpkg` and `import pkg.subpkg` work for me and allow for different top-level names with or without "dotted" sub-package name usage. Not sure what you're missing there.

**Comment by will-ca** [comment]
It probably says more about my package structuring and coding style than anything, but I don't like `from pkg import subpkg` because it doesn't let me explicitly specify which modules to make available from `subpkg`, especially if they're not in `__init__.py`.

In any case, I do agree that this isn't actually an issue with Cython (but I was also wondering whether aliasing might be a generally useful feature when I submitted this).
