### ISSUE TITLE
Sphinx autodoc can't see signatures generated with binding=True

### ISSUE THREAD

**Issue by McSinyx** [cython/cython#3438]
Hi,

For example, if I have a pure Python function like this in a python module:
```python
def foo(bar: int) -> str: pass
```
then both `help` and Sphinx autodoc got the signature correctly.

However, if the same thing is compiled by Cython then autodoc fails to see any signature at all (the function is then documented as just `foo`), if `binding=True` (and `embedsignature=False`) is set.  `help` output is quite normal though (`foo(bar: 'int') -> 'str'`), although it would be nicer if the single quotes are not there.

Reversed compiler flags' behavior as documented in GH-3150 has consistent output for both.

**Comment by da-woods** [comment]
I'm pretty sure the single quotes are from https://github.com/cython/cython/pull/3285 / https://www.python.org/dev/peps/pep-0563/. This is the future behaviour of Python so probably not going away.

**Comment by McSinyx** [comment]
Thanks, I figured that earlier, but `foo(bar: int) -> str` would be much more readable.  That being said, the output of `help` is out of scope from Cython perspective.  I'll try to ask on Python IRC and report back about this just in case someone stumble upon this issue about the same thing.

Do you have any idea about the real issue though?  Need I provide more material to reproduce?  Should I cross-post in Sphinx as well (to investigate what autodoc would look for but cannot find)?

**Comment by da-woods** [comment]
I don't know for sure but: the sphinx autodoc website implies that it bases its work off the docstring. `help` is generating the what it displays from `__annotations__` etc, not the docstring. If you check `foo.__doc__` you'll see the signature isn't in there.

I think (but not certain) this is expected behaviour.

**Comment by McSinyx** [comment]
I'm not sure about the inner implementation, at this point I guess he have to ask them, but it works for pure Python module (not compiled via Cython) so they also get the signature from elsewhere (inspect maybe?).

**Comment by da-woods** [comment]
Ah - fair point. Don't know then.

**Comment by McSinyx** [comment]
I'm closing this now as it is fixed by sphinx-doc/sphinx#7355.  BTW the quotes for signature in `help` is filed in [bpo-39990](https://bugs.python.org/issue39990).
