### ISSUE TITLE
`from . cimport modulename` tries to search in parent package from `__init__.pxd`.

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3442]
In `__init__.pxd` in a package, using `from . cimport modulename` attempts to find `modulename.pxd` in the parent directory of the package.

Using `from . import modulename` in basic Python attempts to find `modulename.*` within the package itself, as does using `from . cimport modulename` in all `*.pxd` files *except* for `__init__.pxd` in packages.

Using `from .packagename cimport modulename` in `__init__.pxd` doesn't work around this, because this (correctly) attempts to find `packagename` inside the package itself.

Because of this, I think there should not be much functional code out there that depends on the relative `cimport` being based on the parent directory, meaning that it should be possible to switch it to the package directory, in line with Python behaviour, without breaking compatibility.

---

#### Example structure:
```
cyrel_package/
├── __init__.pxd
├── __init__.py
├── module.pxd
├── module.py
└── subpackage
    ├── __init__.pxd
    ├── __init__.py
    ├── submodule.pxd
    └── submodule.py
```

And in `cyrel_package/subpackage/__init__.pxd`:

```python3
# from . cimport submodule
# Fails, "'cyrel_package/submodule.pxd' not found" — Attempts to import relative to parent package directory instead of current package directory.

# from .subpackage cimport submodule
# Fails, "'cyrel_package/subpackage/subpackage/submodule.pxd' not found" — Attempts to (correctly) import relative to current package directory.

from cyrel_package.subpackage cimport submodule
# Works.
```

It also fails with `from . cimport module` in the topmost `cyrel_package/__init__.pxd`.

**Comment by scoder** [comment]
Thanks for the report. There's probably just a tiny wrong decision taken somewhere, e.g. that `__init__.pxd` is not always considered to be a package in all places or so.

You tried this with the latest master, right? Could you provide a PR that adds this setup to the existing `tests/run/relative_cimport.srctree` test?
