### ISSUE TITLE
diable cython prepended header

### ISSUE THREAD

**Issue by guihao-liang** [cython/cython#3459]
Hi, I'm using cython with setup.py,
```
~ 167  ext_modules=cythonize(
~ 168             [
~ 169                 # Everything but primes.pyx is included here.
~ 170                 Extension(
~ 171                     "*",
~ 172                     ["turicreate/_cython/*.pyx"],
~ 173                     include_dirs=include_dirs,
~ 174                     libraries=["TuriCore"],
~ 175                     library_dirs=library_dirs,
~ 176                     extra_compile_args=["-O3", "-DNDEBUG", "-std=c++11", "-w"],
+ 177                 ),
+ 178             ]
+ 179         ),
```

I explicitly pass the `include_dirs` to control the build, but cython inserts an include path that breaks my build,

```
clang -fno-strict-aliasing -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/guihaoliang/Work/gui-1-36/targets/include -I/Users/guihaoliang/.pyenv/versions/2.7.16/include/python2.7 -c turicreate/_cython/cy_dataframe.cpp -o build/temp.macosx-10.14-x86_64-2.7/turicreate/_cython/cy_dataframe.o -O3 -DNDEBUG -std=c++11 -w
...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error: no
      member named 'isnan' in the global namespace
using ::isnan;
      ~~^
...
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/math.h:165:5: note:
      expanded from macro 'isnan'
    ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
    ^
```

the wrong include path is,
```
-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include
```

the right include path is under xcode toolchiain (by default should be searched first in clang), which has the right math.h.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h
```

I wonder if there's a way that I can disable the prepended header inserted by cython? Thanks!

**Comment by scoder** [comment]
This is not a Cython bug/issue. It's most likely a problem with your local compiler setup.
If you need help with that, you can ask on the cython-users mailing list or even a general Python mailing list, since it's not Cython specific.

**Comment by mattip** [comment]
Cython uses setuptools/distutils, it does not mangle C-level include paths. My guess is this is coming from your environment variables somehow? Do you have any of `CPPFLAGS`, `CFLAGS`, `CXXFLAGS` set? Another place where `distutils` pulls these variables is from the values of `sysconfig.get_config_vars('CC', 'CXX', 'OPT', 'BASECFLAGS','CCSHARED', 'LDSHARED')`, which are fixed when compiling python.

**Comment by guihao-liang** [comment]
Thanks for the help! It's not a problem with Cython. I tried different python version and it works. It seems to be the problem from my python2 installed by pyenv, which might be linked with that xcode sdk, I guess.

**Comment by guihao-liang** [comment]
yes, it pulls from
```
'PY_CFLAGS': '-fno-strict-aliasing -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include  -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/Users/guihaoliang/.pyenv/versions/2.7.16/include  -DPy_BUILD_CORE',
```
much appreciated @mattip !!!
