### ISSUE TITLE
Type Specialization without gil

### ISSUE THREAD

**Issue by xin-jin** [cython/cython#3470]
Hi,

If I have a function, say, 
```
cdef double greater(double, double) nogil
``` 
I can use it like this `f = greater` inside a nogil function and it works perfectly. However, if I make the function take fused types 
```
cdef numeric greater(numeric, numeric) nogil
```
then neither `f = greater` nor `f = greater[double]` works in a nogil function.

I am just wondering if there is a workaround for this (or probably a more correct way to write it)?

**Comment by da-woods** [comment]
`f = greater` sounds like you've just found somewhere that Cython doesn't enforce it's GIL checks properly. You shouldn't be doing this. It'll fail dramatically and unexpectedly if `greater` does any manipulation of Python objects. Why not just make `greater` a `nogil` function?

**Comment by xin-jin** [comment]
> `f = greater` sounds like you've just found somewhere that Cython doesn't enforce it's GIL checks properly. You shouldn't be doing this. It'll fail dramatically and unexpectedly if `greater` does any manipulation of Python objects. Why not just make `greater` a `nogil` function?

Ahh, yes, `greater` is indeed nogil in my actual code. I forgot to add it (now corrected the original post). Is it still going to fail?

**Comment by da-woods** [comment]
> Is it still going to fail?

No - it looked from the question like you were doing this as a way of calling a regular function in a `nogil` block. If it's marked as `nogil` then it's fine.

I know internally fused functions use some generated Cython code which does require the GIL to select which function to call. Therefore, I wouldn't expect `f = greater` to work. I think `f = greater[double]` should work though?

**Comment by xin-jin** [comment]
> > Is it still going to fail?
> 
> No - it looked from the question like you were doing this as a way of calling a regular function in a `nogil` block. If it's marked as `nogil` then it's fine.
> 
> I know internally fused functions use some generated Cython code which does require the GIL to select which function to call. Therefore, I wouldn't expect `f = greater` to work. I think `f = greater[double]` should work though?

`f = greater[double]` doesn't work. It says "Converting to Python object not allowed without gil".

**Comment by da-woods** [comment]
It works if you specify the function pointer type:

```
ctypedef double (*func_ptr)(double, double) nogil

# then later...
cdef func_ptr f = greater[double]
return f(1.0, 2.0)
```

It does seem like it should be able to work out the type like it does without fused types though.

**Comment by xin-jin** [comment]
> It works if you specify the function pointer type:
> 
> ```
> ctypedef double (*func_ptr)(double, double) nogil
> 
> # then later...
> cdef func_ptr f = greater[double]
> return f(1.0, 2.0)
> ```
> 
> It does seem like it should be able to work out the type like it does without fused types though.

It works! Thank you very much.
