### ISSUE TITLE
Incorrect code for bytearray iteration

### ISSUE THREAD

**Issue by scoder** [cython/cython#3473]
The following code infers the loop variable as `unsigned char`, but then uses Python iteration for the loop, without properly converting the items.
```cython
def calculate_crc(bytearray st):
    print(f'Iterating over {st}')

    for ch in st:
        print(f'{ch}')
```

**Comment by piotrmaslanka** [comment]
Tactical link [https://groups.google.com/forum/m/#!topic/cython-users/3ajf9LsV3pU](https://groups.google.com/forum/m/#!topic/cython-users/3ajf9LsV3pU)

**Comment by scoder** [comment]
Removing milestone target since it's annoying but not a regression.

**Comment by da-woods** [comment]
https://github.com/cython/cython/pull/3617 fully optimized loops over bytearrays (for Cython 3).

I think this issue was more about the type of the loop variable in Cython 0.29.x though?

**Comment by Kenrick0** [comment]
Hi! I ran into this bug while running Cython 0.29.22 on the code below and would like to fix it. This is my first change in this project, so please let me know if I've missed anything.
```python
def f(src):
    data = bytearray(src)
    for elem in data:
        print(elem)
```
The relevant code this generates is:
```c
  /* "bytearray_test.py":3
 * def f(src):
 *     data = bytearray(src)
 *     for elem in data:             # <<<<<<<<<<<<<<
 *         print(elem)
 */
  __pyx_t_1 = PyObject_GetIter(__pyx_v_data); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 3, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_2 = Py_TYPE(__pyx_t_1)->tp_iternext; if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 3, __pyx_L1_error)
  for (;;) {
    {
      // Specifically this line is incorrect because __pyx_t_3 is unsigned char, and __pyx_t_2 returns PyObject*
      __pyx_t_3 = __pyx_t_2(__pyx_t_1);
      if (unlikely(!__pyx_t_3)) {
        PyObject* exc_type = PyErr_Occurred();
        if (exc_type) {
          if (likely(__Pyx_PyErr_GivenExceptionMatches(exc_type, PyExc_StopIteration))) PyErr_Clear();
          else __PYX_ERR(0, 3, __pyx_L1_error)
        }
        break;
      }
      __Pyx_GOTREF(__pyx_t_3);
    }
    __pyx_v_elem = __pyx_t_3;
```
I found the unsigned char is being inferred in ExprNodes.py > IndexNode > infer_type(). Changing this type from `PyrexTypes.c_uchar_type` to `py_object_type` fixes this specific problem by making the iteration just use python types. (both `__pyx_t_3` and `__pyx_v_elem` become PyObject*) I confirmed this by compiling and running with this change, however this breaks tests in bytearray_coercion that are checking for unsigned char types.

So my next attempt is to change the __pyx_t_3 (ForInStatNode.item) temporary to be PyObject* and generate the `__Pyx_PyInt_As_unsigned_char` to convert the resulting object to an unsigned char. This works and passes the tests, including the new test I added for bytearray iteration.

This is the same block as above after the change in #4108
```c
  /* "bytearray_test.py":3
 * def f(src):
 *     data = bytearray(src)
 *     for elem in data:             # <<<<<<<<<<<<<<
 *         print(elem)
 *
 */
  __pyx_t_1 = PyObject_GetIter(__pyx_v_data); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 3, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_2 = Py_TYPE(__pyx_t_1)->tp_iternext; if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 3, __pyx_L1_error)
  for (;;) {
    {
      // Now __pyx_t_3 is PyObject* and is converted to unsigned char below
      __pyx_t_3 = __pyx_t_2(__pyx_t_1);
      if (unlikely(!__pyx_t_3)) {
        PyObject* exc_type = PyErr_Occurred();
        if (exc_type) {
          if (likely(__Pyx_PyErr_GivenExceptionMatches(exc_type, PyExc_StopIteration))) PyErr_Clear();
          else __PYX_ERR(0, 3, __pyx_L1_error)
        }
        break;
      }
      __Pyx_GOTREF(__pyx_t_3);
    }
    __pyx_t_4 = __Pyx_PyInt_As_unsigned_char(__pyx_t_3); if (unlikely((__pyx_t_4 == (unsigned char)-1) && PyErr_Occurred())) __PYX_ERR(0, 3, __pyx_L1_error)
    __Pyx_DECREF(__pyx_t_3); __pyx_t_3 = 0;
    __pyx_v_elem = __pyx_t_4;
```

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/c416c7cb2159cc43f9461d96721aeaaa8f9f4714
