### ISSUE TITLE
Passing 2D numpy array to C++ Code with memory view fails

### ISSUE THREAD

**Issue by longuyen97** [cython/cython#3496]
I have the following code:

```
cdef extern from "mul.hpp":
    void multiply_by_10_in_C(double **, unsigned int, unsigned int)

import numpy as np

def multiply_by_10(arr):
    if not arr.flags['C_CONTIGUOUS']:
        arr = np.ascontiguousarray(arr)

    cdef double[:, ::1] arr_memview = arr
    multiply_by_10_in_C(&arr_memview[0, 0], arr.shape[0], arr.shape[1])
```

It is currently failing with following message: `pymul.pyx:11:24: Cannot assign type 'double *' to 'double **'
`. How do I pass a 2D array to C++ code?

**Comment by scoder** [comment]
The error message is correct: you are passing a pointer to an array of doubles into a function that expects a pointer to an array of double pointers. This is not a bug.

If you want further help with this, please ask on the cython-users mailing list.
