### ISSUE TITLE
Extension type does not return TypeError when adding incompatible types 

### ISSUE THREAD

**Issue by maxwellhodges** [cython/cython#3497]
I tried to run the code in Kurt Smith's Cython book:

```
cdef class E:
    """Extension type that supports addition."""
    cdef int data
    def __init__(self, d):
        self.data = d
    def __add__(x, y):
        # Regular __add__ behavior
        if isinstance(x, E):
            if isinstance(y, int):
                return (<E>x).data + y
        # __radd__ behavior
        elif isinstance(y, E):
            if isinstance(x, int):
                return (<E>y).data + x
        else:
            return NotImplemented
```

Addition with integers works fine but adding to a float (or any other incompatible type) just returns None rather than a ValueError.  Same behaviour on Mac and Ubuntu and Cython version is 0.29.16.  I couldn't find anything in the docs that says this would have changed?

**Comment by TeamSpen210** [comment]
It's a problem with that method. If you look carefully, if the `isinstance(..., int)` checks fail execution would continue out of the outer `if` statement, and reach the end of the function which returns `None`. You'll probably want to remove the `else:`, and just always return `NotImplemented` if the function reaches the end.

**Comment by maxwellhodges** [comment]
Hi Spencer, just tested it and you're right - this works:

```
cdef class E:
    """Extension type that supports addition."""
    cdef int data
    def __init__(self, d):
        self.data = d
    def __add__(x, y):
        # Regular __add__ behavior
        if isinstance(x, E):
            if isinstance(y, int):
                return (<E>x).data + y
        # __radd__ behavior
        elif isinstance(y, E):
            if isinstance(x, int):
                return (<E>y).data + x
        
        return NotImplemented
```

Seems to be a small error in the book.  Thanks a lot
