### ISSUE TITLE
Fused dispatch function leaks into specialised user functions

### ISSUE THREAD

**Issue by scoder** [cython/cython#3511]
Any signature type added to the [generated fused dispatch function](https://github.com/cython/cython/blob/983192298f91352b6159dcd839c607d962bd0a4e/Cython/Compiler/FusedNode.py#L643-L645) leaks into the default argument type of the user defined signature of the specialised functions. This probably happens in (or is triggered by behaviour of) `FusedNode.analyse_expressions()`, but we need to find out where and what is actually going wrong here.

**Comment by da-woods** [comment]
Not got to the bottom of this yet but I think you've got it the wrong way round. It isn't that the types from the dispatch function leak into the user function. It's that the defaults from the use function leak into the dispatch function.

Using the example in https://github.com/pandas-dev/pandas/issues/33507#issuecomment-613013030 as a test + `CYTHON_CLINE_IN_TRACEBACK` the error comes from

    if (!(likely(PyDict_CheckExact(__pyx_v__fused_sigindex))||((__pyx_v__fused_sigindex) == Py_None)||(PyErr_Format(PyExc_TypeError, "Expected %.16s, got %.200s", "dict", __Pyx_PyType_Name(Py_TYPE(__pyx_v__fused_sigindex))), 0))) __PYX_ERR(0, 6, __pyx_L1_error)

i.e. an unwanted bool has found its way into the dispatch function.

**Comment by scoder** [comment]
> you've got it the wrong way round

Cool, thanks for digging into this!
