### ISSUE TITLE
Still having problems to complie to dll

### ISSUE THREAD

**Issue by yafengabc** [cython/cython#3512]
> You didn't say what kind of error you got, but I guess it's some kind of "something isn't initialised or available" error. The reason for that would be that you are calling `PyInit_some()` directly, which is not the right way to initialise an embedded module.
> 
> Instead, call `PyImport_AppendInittab("some", &PyInit_some)` before calling `Py_initialize()`.
> 
> We should make that clear in the documentation. Currently, only the [CPython docs](https://docs.python.org/3/extending/embedding.html) mention it.

Not any error messages
I found some problems that I may describe
In fact, no function can run, such as print
i modify the code:
dllmain.c
```C
#include <Python.h>
#include <Windows.h>
#include "some.h"

extern __declspec(dllexport) char*  __stdcall test() {
    return _test();
}

BOOL WINAPI DllMain(HINSTANCE hinstDLL,DWORD fdwReason,LPVOID lpReserved) {
    switch( fdwReason ) {
        case DLL_PROCESS_ATTACH:
            PyImport_AppendInittab("some", &PyInit_some) ;
            Py_Initialize();
            break;
        case DLL_PROCESS_DETACH:
            Py_Finalize();
            break;
    }
    return TRUE;
}
```
some.pyx
```python
cdef public char* _test():
    return "ok return well"
```
and write a c program to call it:
```C
#include "stdio.h"

extern char* __stdcall test(void);
int main(void){
    printf("%s",test());
}
```
the result is:
D:\msys64\home\songwz\cytest\diff_no>loaddll
ok return well

but i change the code:

some.pyx
```python
cdef public char* _test():
    print("hello")
    return "ok return well"
```
He will not return anything
The code below is the same
```python
def hello():
    pass
cdef public char* _test():
    hello()
    return "ok return well"
```
But the code below works：
```python
cdef hello():   #<-----cdef works
    pass
cdef public char* _test():
    hello()
    return "ok return well"
```

_Originally posted by @yafengabc in https://github.com/cython/cython/issues/3509#issuecomment-613237803_

**Comment by scoder** [comment]
Let's keep this in context. I'll reply in the original ticket.
