### ISSUE TITLE
How to access wrapped c pointer on cdef class?

### ISSUE THREAD

**Issue by brettlangdon** [cython/cython#3525]
Greetings, I have been trying to use Cython to wrap a C library and I cannot seem to figure out how to get this specific workflow to work.

Here is an example of what I am trying to do:

```cython
# my_lib.pyx
cdef extern from "my_lib.h":
    ctypedef struct c_widget:
        pass

    c_widget* c_widget_new();

    ctypedef struct c_cart:
        pass

    c_cart* c_cart_new();
    void c_cart_add_widgets(cart* cart, c_widget** widget);


cdef class Cart:
    cdef c_cart* _cart

    def __cinit__(self):
        self._cart = c_cart_new()
        if self._cart is NULL:
            raise MemoryError()

    cdef add(self, widgets):
        cdef c_widget** c_widgets
        # TODO: list of Widgets -> c_widget**
        c_cart_add_widgets(self._cart, c_widgets)


cdef class Widget:
    cdef c_widget* _widget

    def __cinit__(self):
        self._widget = c_widget_new()
        if self._widget is NULL:
            raise MemoryError()
```

Example API that I am going for in Python:

```python
from my_lib import Cart, Widget

cart = Cart()
cart.add([
    Widget(),
    Widget(),
    Widget(),
])
```

The part I am having trouble with is in the `add` method for `Cart`, if I have a list of `Widget` instance, how do I get the underlying `cdef c_widget* _widget` property?

I have tried a number of ways, but anything I do usually yields in me having a `PyObject*` and/or telling me that `Widget` has no attribute `_widget`.

I am guessing I am probably approaching this from the wrong angle. Any direction/advice would be greatly appreciated!

**Comment by brettlangdon** [comment]
I was able to figure this out. Just needed to cast the variable to `Widget`.

```cython
cdef add(self, widgets):
    cdef Widget current_widget
    for widget in widgets:
        current_widget = <Widget>widget
        # I can now access `current_widget._widget`
```

If there is a better/cleaner way to handle this, I would love to know!

I'll close this issue for now since this isn't an active issue for me anymore.

**Comment by TeamSpen210** [comment]
You'll actually want to do `current_widget = <Widget ?>widget`. That ensures it does a type check and raises an exception if someone gave you something else, instead of blindly casting and inevitably crashing.

**Comment by scoder** [comment]
@brettlangdon you can also simply type your `widget` loop variable as `cdef Widget widget`. That will do a type check on assignment and lets Cython know what type the value has.

**Comment by brettlangdon** [comment]
@scoder and @TeamSpen210 thank you both so much, these are both great suggestions!

Is there a way for me to define a function parameter type of "list of Widget" to get the type checking on function call?

(my guess is no because lists can hold anything, can't know until we try to access an item in it?)

**Comment by TeamSpen210** [comment]
Indeed, you couldn't actually check in advance. If Cython inserted a loop to check every item, that would be rather inefficient. Even if it did, any time you did anything that called back into Python code it's potentially possible for that to have modified the list to insert a non-`Widget` object. So you need to check each time you access.
