### ISSUE TITLE
encountered an issue with default argument values in Cython 3.0a

### ISSUE THREAD

**Issue by grlee77** [cython/cython#3527]
I tried out Cython 3.0a with [PyWavelets](https://github.com/PyWavelets/pywt/). I also encountered segfaults due to the missing `import_array()`  that was reported in #3520. 

After fixing that, we came across one additional error when running the test suite. Specifically, when calling the function `pywt.swt` which in turn calls a Cython function of the same name and the following definition ([link to source in the PyWavelets repo](https://github.com/PyWavelets/pywt/blob/6e3641bb33e7f8e010ed29b77791e5f8f975d162/pywt/_extensions/_swt.pyx#L52-L53
)):

```Cython
def swt(cdata_t[::1] data, Wavelet wavelet, size_t level, size_t start_level,
        bool trim_approx=False):
```

results in the following error:
```
>   cpdef swt(cdata_t[::1] data, Wavelet wavelet, size_t level, size_t start_level,
E   TypeError: Expected dict, got bool
```

Simply removing the default value of False for `trim_approx` resolves the issue.

```Cython
def swt(cdata_t[::1] data, Wavelet wavelet, size_t level, size_t start_level,
        bool trim_approx)
```
In this instance, this is an acceptable workaround as the cython-level function is only called by a python wrapper, so there is no issue with API compatibility for us to remove the default in the underlying Cython function. My question is whether this is a bug or some new expected behavior?

**Comment by da-woods** [comment]
https://github.com/cython/cython/issues/3511 - Bug. Should be fixed in current master.

**Comment by grlee77** [comment]
I can confirm that the issue is fixed on master. Thanks!
