### ISSUE TITLE
Cython 3.0: issue calling a Cython function assigned as a class attribute

### ISSUE THREAD

**Issue by grlee77** [cython/cython#3529]
In testing `scikit-image` with current Cython master, we encountered a couple of test failures of the type:

`FAILED skimage/io/tests/test_colormixer.py::TestColorMixerAdd::test_basic - TypeError: add() takes exactly 4 positional arguments (5 given)
`

This seems to be related to the use of a Cython function [defined here](https://github.com/scikit-image/scikit-image/blob/671077842d0332ec25ecda31a5b95daaa64a1996/skimage/io/_plugins/_colormixer.pyx#L19-L21) in a test class which [assigns the function as a class attribute](https://github.com/scikit-image/scikit-image/blob/671077842d0332ec25ecda31a5b95daaa64a1996/skimage/io/tests/test_colormixer.py#L34-L35).

I assume the 5th argument in the error message above is related to an additional `self` argument when called as a bound method? I don't know enough about the low level details of Python classes or Cython to speculate on the reason for this change in behavior. 

Changing the test class to explicitly specify that cm.add is a static method as in:
```Python
class TestColorMixerAdd(ColorMixerTest):
    op = staticmethod(cm.add)
```
fixes the issue.

**Comment by scoder** [comment]
Yes, Cython functions are Python compatible now (previously required the `binding` directive, see #2564) and bind to Python classes as methods. `staticmethod()` is the right (Python) way to deal with this case.

If you do not want this, you can also use the decorator `@cython.binding(False)` or disable binding globally, but that will also remove the ability to introspect function signatures etc.

**Comment by emmanuelle** [comment]
thank you @scoder!
