### ISSUE TITLE
Possible regression between 0.29.15 and 0.29.16

### ISSUE THREAD

**Issue by neok-m4700** [cython/cython#3543]
I would like to open a possible regression between releases `0.29.15` and `0.29.16`.

Please see https://github.com/symengine/symengine.py/issues/318 for the full description (missing a `typedef struct __pyx_ctuple_long ...` in the generated `cpp` source).

I think that the regression was intoduced in https://github.com/cython/cython/pull/3271 (@isotherm ?):
applying https://github.com/cython/cython/pull/3271.patch on the `0.29.15` release results in the same build error as when using `0.29.16`.

**Comment by scoder** [comment]
Resolved by #3551 in 9e26b370f2bf4d9aea29a9d29bcac0955ebb632c.

**Comment by neok-m4700** [comment]
Thanks for the quick fix !
