### ISSUE TITLE
Division by Zero in Method/Function __pyx_memoryview_slice_memviewslice

### ISSUE THREAD

**Issue by simonsan** [cython/cython#3568]
First time reporting something from `scan-build`. I hope that helps and that I am at the right place with this, I suppose this is an upstream issue for our project. I attached the uploaded report with txt ending. 
[report-117322.html.txt](https://github.com/cython/cython/files/4566816/report-117322.html.txt)

![2020-05-02 02_54_08-_home_runner_work_openage_openage_ bin_clang++-9-debug-Oauto-sanitize-none_opena-Screenshot](https://user-images.githubusercontent.com/14062932/80851170-47394880-8c20-11ea-8d68-2b7d124fde76.png)

**Comment by scoder** [comment]
Thanks for the report. I'm sure it's a false positive, but I can understand why it's confusing to a machine.
