### ISSUE TITLE
Segmentation fault in Printing.c with python3

### ISSUE THREAD

**Issue by grigandal625** [cython/cython#3569]
Sorry for my English :)

**OS - 18.04.1-Ubuntu**

I got a segmentation fault in cython/Cython/Utility/Printing.c line 168 (static int __Pyx_PrintOne)

that's how i got it:

In cython, the code is the simplest:

    # program.pyx

    cdef public int test():
        print('hello, world')
        return 0

Then on bash:

    cython program.pyx

got files:

- program.h
- **program.c** (- error here at line 1917)

Wrote the following .c file:
```
/ * --- main.c --- * /

#include "Python.h"
#include "program.h"


int main (int argc, char * argv []) {
    Py_Initialize();
    PyInit_program();
    test();
    Py_Finalize();
    return 0;
}
```

compile to `a.out` with

```
gcc $(python3-config --cflags) program.c main.c $(python3-config --ldflags) -fPIC
```

trying to call `./a.out` - **got error**

---
I also note that everything works for python2.7 libs and linker parameters in gcc comand:

in `main.c` change line `PyInit_program();` to `initprogram();` and run

```
gcc $(python-config --cflags) program.c main.c $(python-config --ldflags) -fPIC
```

`./a.out` prints `hello, world`

Maybe I'm doing something wrong?

**Comment by scoder** [comment]
Calling the module init function is not the right way to initialise an extension module.
I updated the documentation to make that clearer.

https://cython.readthedocs.io/en/latest/src/tutorial/embedding.html
