### ISSUE TITLE
Referencing local variable before assignment is safe inside sizeof

### ISSUE THREAD

**Issue by Celelibi** [cython/cython#3575]
Referencing a variable before it is assigned to anything is usually a bad idea.
It is, however, perfectly valid to do so inside the `sizeof` operator. It's even a common pattern in C when using `malloc` / `calloc`.

This program produce a warning, while it should probably not.
```cython
def main():
    cdef int x
    print(sizeof(x))

main()
```

**Comment by scoder** [comment]
True. Can't say how difficult it is to fix, though. Maybe we could special-case `sizeof()`, and probably also `typeof()`, `varargs()` and maybe others(?) in the control flow analysis somehow, so that they won't consider the variable an actual usage.

**Comment by Celelibi** [comment]
I am not sure what you mean by `varargs()`.

**Comment by scoder** [comment]
> I am not sure what you mean by `varargs()`.

Sorry, I meant `va_start()` and friends in `stdarg.h`. But I just noticed that we're not currently providing those declarations anyway, so it's not something to add in this PR for now.
