### ISSUE TITLE
Cython3 fails: missing compile-time constants / compiler directives

### ISSUE THREAD

**Issue by kif** [cython/cython#3576]
One example is https://github.com/kif/freesas:
```
running build_ext
cythoning freesas/_distance.pyx to freesas/_distance.c
/opt/VirtualEnv/py38/lib/python3.8/site-packages/Cython/Compiler/Main.py:344: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/jerome/workspace/freesas/freesas/_distance.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
    """
    cdef floating sigma = 0.40567 * radius
    return exp(- pos * pos / (2.0 * sigma * sigma)) * 0.3989422804014327 / sigma


IF HAVE_OPENMP:
  ^
------------------------------------------------------------

freesas/_distance.pyx:76:3: Compile-time name 'HAVE_OPENMP' not defined
```

What is/was the rational: setup.py determines if the architecture/compiler are suitable for openmp parallelization and includes one or the other version of the source code. In more recent code (silx, pyFAI), we are doing this detection at runtime, not compile-time, so this issue does not appear.

**Comment by kif** [comment]
Here is the section of the setup.py:
```    def patch_extension(self, ext):
        """
        Patch an extension according to requested Cython and OpenMP usage.

        :param Extension ext: An extension
        """
        # Cytonize
        if not self.use_cython:
            self.patch_with_default_cythonized_files(ext)
        else:
            from Cython.Build import cythonize
            patched_exts = cythonize(
                [ext],
                compiler_directives={'embedsignature': True,
                                     'language_level': 3},
                force=self.force_cython,
                compile_time_env={"HAVE_OPENMP": self.use_openmp}
            )
            ext.sources = patched_exts[0].sources
```

**Comment by kif** [comment]
I notice there is also a warning about the Python3 syntax which is not used. This means the `cythonize` is either not called or not with the proper options.

**Comment by kif** [comment]
Once the compile-time extension has been passed, it is OK:
```
cython -E HAVE_OPENMP=True freesas/_distance.pyx
python setup.py build
```

**Comment by kif** [comment]
I double checked and there are also issues within silx where the compiler directives are not taken into account. 
https://github.com/silx-kit/silx/issues/3027
So there is probably something that changed between cython 0.29 and cython3 when it comes to the integration within setuptools build_ext

**Comment by da-woods** [comment]
https://github.com/cython/cython/pull/3561 looks to be the most recent relevant change to setuptools, so is a likely cause?

**Comment by kif** [comment]
I have re-shuffled our setup.py and apparently it works again ... I suspect the bug was on our side.
