### ISSUE TITLE
Warning C4551: function call missing argument list

### ISSUE THREAD

**Issue by Ekopalypse** [cython/cython#3579]
Using Cython version 3.0a4 with python3.7 on windows7 x64, I received 

plugin.cpp(329104): warning C4551: function call missing argument list

~~~cpp
#if PY_VERSION_HEX < 0x030600A4 && CYTHON_PEP487_INIT_SUBCLASS
    if (likely(result) && likely(PyType_Check(result))) {
        if (unlikely(__Pyx_SetNamesPEP487(result) < 0)) {
            Py_CLEAR(result);
        } else {
            result = __Pyx_InitSubclassPEP487(result, mkw);
        }
    }
#else
    (void) __Pyx_GetBuiltinName;   <-- line 329104
#endif
~~~

Cython version 3.0a1 did not show this warning.

Feel free to close if this isn't relevant.

**Comment by scoder** [comment]
Oh, great. That line is literally only there to _avoid_ a warning, about the function being unused, specifically. Does it help to take the address of the function instead, i.e. `(void) &__Pyx_GetBuiltinName` ?

**Comment by Ekopalypse** [comment]
@scoder, sorry for the naive question but should I do the test to see if the change does what you want it to be done? I certainly open for doing it.
