### ISSUE TITLE
Document new features in Cython 3.0

### ISSUE THREAD

**Issue by scoder** [cython/cython#3583]
It's time to look through the documentation to see if all new features have been documented and/or are findable for users in an appropriate place. This is a great beginners ticket because it allows playing with new Cython features and figuring out how they work.

- look through [CHANGES.rst](https://github.com/cython/cython/blob/master/CHANGES.rst) to see what features are new in the latest 3.0 alpha versions and which seem to be worth mentioning
- look in the documentation where you would expect this to be documented
- if it's already covered, perfect
- otherwise, search the documentation to see if it's mentioned elsewhere, and decide if that's the right place
- if not, write a paragraph or two and/or add a cross-ref from places where you think it's also worth mentioning
- if you add example code (examples are great!) make sure it compiles by adding it as a `.pyx` file under `docs/examples/` to let the test suite pick it up
- preferably, use separate commits/updates for the different features.

**Comment by da-woods** [comment]
From a quick look through, features that stand out to me as currently undocumented include:

* cython-3.0.pxd versioning - probably should be documented. I'll submit a PR with a sentence or two for this.
* limited api - probably shouldn't be documented until its a little more complete.
* pythran - not strictly new to Cython 3, but I can find references to it in the changelog but no documentation at all. @serge-sans-paille ?

**Comment by serge-sans-paille** [comment]
@da-woods : the official doc is scarce, but here it is: https://cython.readthedocs.io/en/latest/src/userguide/numpy_pythran.html

**Comment by mattip** [comment]
By "`cdef` properties" do you mean the inlined `@property` decorator on `ctypedef class`es? That is documented as [C inline properties](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#c-inline-properties).

So unless more refinement is needed, I think the three new features described here are documented (assuming "limited API" is not yet ready for prime time).

**Comment by da-woods** [comment]
> By "`cdef` properties" do you mean the inlined `@property` decorator on `ctypedef class`es? That is documented as [C inline properties](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#c-inline-properties).
> 
> So unless more refinement is needed, I think the three new features described here are documented (assuming "limited API" is not yet ready for prime time).

Yeah - the inlined `@property` decorator is what I meant. I don't think think more refinement is needed, so two out of the three features are documented (and limited API isn't ready yet)
