### ISSUE TITLE
endian.h

### ISSUE THREAD

**Issue by dvarrazzo** [cython/cython#3595]
Hello,

I am using [`endian.h`](http://man7.org/linux/man-pages/man3/endian.3.html) in Cython using the following definition:

```cython
# convert values  between host and big-/little-endian byte order
# http://man7.org/linux/man-pages/man3/endian.3.html

from libc.stdint cimport uint16_t, uint32_t, uint64_t

cdef extern from "<endian.h>" nogil:

    cdef uint16_t htobe16(uint16_t host_16bits)
    cdef uint16_t htole16(uint16_t host_16bits)
    cdef uint16_t be16toh(uint16_t big_endian_16bits)
    cdef uint16_t le16toh(uint16_t little_endian_16bits)

    cdef uint32_t htobe32(uint32_t host_32bits)
    cdef uint32_t htole32(uint32_t host_32bits)
    cdef uint32_t be32toh(uint32_t big_endian_32bits)
    cdef uint32_t le32toh(uint32_t little_endian_32bits)

    cdef uint64_t htobe64(uint64_t host_64bits)
    cdef uint64_t htole64(uint64_t host_64bits)
    cdef uint64_t be64toh(uint64_t big_endian_64bits)
    cdef uint64_t le64toh(uint64_t little_endian_64bits)
```

is there any specific reason to not have it in Cython? Ok if I contribute it in a MR?

Thank you very much.

**Comment by scoder** [comment]
Seems to be Linux specific, that limits its usefulness. If there was such an addition to Cython, I'd rather have something that works cross-platform. So, I'd say no.

Feel free to distribute the `.pxd` via a PyPI package, though. Cython doesn't need to ship them itself, they can just reside somewhere on the PYTHONPATH.

**Comment by dvarrazzo** [comment]
No worries: not being portable seems a good reason. I will keep it in my project's code.
