### ISSUE TITLE
set_array_base: ValueError: Cannot set the NumPy array 'base' dependency more than once

### ISSUE THREAD

**Issue by Xianqi-Zhang** [cython/cython#3601]
Hi
My code:

![Snipaste_2020-05-12_17-29-16](https://user-images.githubusercontent.com/32128662/81667673-22da3900-9476-11ea-8009-a21f8a09366d.jpg)

When i use this in python, like this:
>>> import numpy_cleanup as nc
>>> nc.make_matrix(100, 100)
ValueError: Cannot set the NumPy array 'base' dependency more than once

Do u have any idea? Thank you for your any reply!

**Comment by scoder** [comment]
I'm pretty sure that this exception comes from NumPy and not from Cython. Could you please ask over there? (Also, I'm not sure if it's worth a ticket. I'd ask on their mailing list first.)

**Comment by Xianqi-Zhang** [comment]
https://github.com/numpy/numpy/issues/16211

**Comment by eric-wieser** [comment]
Just to follow up - I think this is an X/Y problem, and the underlying question here is _"How do I create a `memoryview` object from a pointer and a destructor"_. If you can do that, you can pass the `memoryview` to numpy and everything will work fine.
