### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by MatrixHaxxor** [cython/cython#3602]
Hi,
I  need some help with dealing with function callbacks. 

My Scenario:
I have a external library. The only things available for me are the headerfiles and the .lib files for linking. Now I want to make some functions available in python.

So a example from a header file:
--> This is the function and it takes a other function as a argument. In this case: XPLMCameraControl_f  inControlFunc
<img width="439" alt="1" src="https://user-images.githubusercontent.com/26418347/81687282-3fb44380-9459-11ea-8fc7-234c494b8b7a.PNG">

-->XPLMCameraControl_f  inControlFunc is defined like this:
<img width="464" alt="2" src="https://user-images.githubusercontent.com/26418347/81687948-9b7ecc80-9459-11ea-9021-56e8c1308cfa.PNG">

From Python I want to be able to call XPLMControlCamera like the following:
<img width="481" alt="3" src="https://user-images.githubusercontent.com/26418347/81690105-2d3b0980-945b-11ea-8e4e-5fc4d21d82f3.PNG">

What do I have to do in order to get this work?

**Comment by scoder** [comment]
A bug tracker is not a good place to ask general support questions. Please ask on the cython-users mailing list.
