### ISSUE TITLE
__Pyx_PyType_Ready() can garble memory

### ISSUE THREAD

**Issue by pitrou** [cython/cython#3603]
After some debugging, we found out that `__Pyx_PyType_Ready` can garble arbitrary memory.
Indeed, it has the following lines:
```c++
#if PY_VERSION_HEX >= 0x03050000
    t->tp_flags |= Py_TPFLAGS_HEAPTYPE;
#endif
    r = PyType_Ready(t);
#if PY_VERSION_HEX >= 0x03050000
    t->tp_flags &= ~Py_TPFLAGS_HEAPTYPE;
#endif
```

The problem is if `PyType_Ready` indirectly triggers the garbage collector. The static type `t` will be incorrectly considered as a heap type, and therefore as a GC-enabled object. When traversing this object, the GC will lookup the GC header by subtracting 16 bytes from `t`'s beginning, which may point to any other C static variable. Then it will temporarily "decref" the GC header, modifying other data.
(in our case, that other data is a Cython function's `ml_flags`, rendering it unusable, but that might be something else, depending what your Cython module contains)

**Comment by pitrou** [comment]
@scoder

**Comment by pitrou** [comment]
Perhaps a possible solution is for Cython to allocate static types like this:
```c
typedef struct {
    PyGC_Head gc_head;
    PyTypeObject typeobj;
} SafeStaticType;

static SafeStaticType __pyx_safetype_7pyarrow_3lib_KeyValueMetadata = {
    .gc = {
        .gc_refs = -2  /* _PyGC_REFS_UNTRACKED */
    },
    .typeobj = {
        PyVarObject_HEAD_INIT(0, 0)
        /* etc. */
    }
};

static PyTypeObject* __pyx_type_7pyarrow_3lib_KeyValueMetadata = \
    &__pyx_safetype_7pyarrow_3lib_KeyValueMetadata.typeobj;

```

**Comment by pitrou** [comment]
In the meantime, we're probably going to disable the GC on module initialization:
https://github.com/apache/arrow/pull/7160/files

**Comment by scoder** [comment]
Lovely. Thanks for the investigations.
Here is the full code. Note the comment.
https://github.com/cython/cython/blob/94ea7d0931300d23d518d34129c0cd61ffca5f31/Cython/Utility/ExtensionTypes.c#L57-L72

**Comment by pitrou** [comment]
Yeah, I saw the comment. I think the BPO issue would deserve a proper fix, but I'm not involved very much nowadays. Perhaps @jdemeyer feels brave enough? :-)

**Comment by pitrou** [comment]
Perhaps Cython should always use `PyType_FromSpec`, not always in limited API builds?

**Comment by scoder** [comment]
> Perhaps Cython should always use `PyType_FromSpec`

Yes, I was thinking that anyway. The main reason for keeping the current static types is Py2.7 support. That'll be ripped out in Cython 3.1, shortly after the 3.0 release. But we could already start by switching to heap types for Py3.4+ in Cython 3.0. (No, this will not change in 0.29.x any more.)

We could also mitigate the issue by only setting the heaptype flag if there actually are heap types involved, I think. That could also be done in 0.29.x.

**Comment by scoder** [comment]
And regarding always using `PyType_FromSpec()` in Py3, then we run into bugs like https://bugs.python.org/issue38140
So, I guess the answer is no, we can't currently use `PyType_FromSpec()`, at least not for Py<3.9.

**Comment by scoder** [comment]
Anyway, I started splitting the current Limited-API special-casing into separate feature flags in #3611. Let's see where that gets us. We might be able to work around the limitations of `PyType_FromSpec()` when we're not limited to the limited API.

**Comment by scoder** [comment]
… and, obviously, `PyType_FromSpec()` calls `PyType_Ready()` internally, so that's even worse in the end. :-/

Then our best hope for now is to limited the impact of the heaptype flag hack, I'd say.

**Comment by da-woods** [comment]
It's quite likely I'm missing something, but is there a reason not to turn off the GC within `__Pyx_PyTypeReady`? [It might be possible to do in C](https://github.com/python/cpython/blob/7443d42021d433da0497f8ba651daa47e7dc1991/Modules/gcmodule.c#L1482) but even if not then it's only a module import and Python function call.

**Comment by scoder** [comment]
Yeah, I looked at that, too, but that was only changed fairly recently. In older CPython versions, the GC switch is a static C variable in the `gc` module, so it's not trivially to switch it off there. It's still an option, though.

**Comment by scoder** [comment]
#3611 seems to work now (as of a0d4511bfa91bf571daccb5e28c7b2a27a734825) with `-DCYTHON_USE_TYPE_SPECS=1` enabled, i.e. using type specs for all types that currently have specs. Only the types of generators and coroutines are missing, I'll also look into those. If it all turns out good, I think this can become the default setting for Py3+ in Cython 3.0.

@pitrou could you give that branch a try on your side?

**Comment by pitrou** [comment]
Is it `CYTHON_USE_TYPE_FROM_SPEC` or `CYTHON_USE_TYPE_SPECS`? It's not clear from the diff.

**Comment by scoder** [comment]
The latter. I renamed it along the way.

**Comment by scoder** [comment]
I've opted for disabling the GC during these calls to `PyType_Ready()` as a way to fix this specific bug.

Getting type specs to work is too big a change for now, since they really don't provide equal functionality with static types for now (e.g. there's no buffer interface support).

**Comment by scoder** [comment]
Thanks for figuring out the details, @pitrou.

**Comment by pitrou** [comment]
@scoder Do you still want me to try type specs on PyArrow?

**Comment by scoder** [comment]
Not right now, I think. I'd be happy if you could try that once the branch tests ok, though. I'll keep working on it and will see if I hit any blockers.
