### ISSUE TITLE
__del__ beside the __dealloc__

### ISSUE THREAD

**Issue by brightening-eyes** [cython/cython#3612]
python3 uses __del__ for uninitialization of classes, it would be good to have this as well, it can help to uninitialize python variables, while in __dealloc__ we can uninitialize c variables.
this is useful for example when we are using a module that uses ctypes, or is dependent on some python initialization.

**Comment by scoder** [comment]
Right, [PEP 442](https://www.python.org/dev/peps/pep-0442/) allows this. Cython currently implements it the other way round and calls `tp_finalize()` from `tp_dealloc()`, but it would certainly be nice to also support `__del__` directly. PR welcome.

How to do it:
The `tp_finalize` slot in `TypeSlots.py` needs to become a `MethodSlot` backed by `__del__`.
This seems worth a dedicated set of tests, maybe `tests/run/pep442_tp_finalize.pyx`.
