### ISSUE TITLE
M_PI: undeclared identifier, after 0.29.18

### ISSUE THREAD

**Issue by sciunto** [cython/cython#3622]
In scikit image, it appears that after the release of cython 0.29.18, a failure appeared

```skimage\restoration\_unwrap_1d.c(2215): error C2065: 'M_PI': undeclared identifier```

Our incriminated file: https://github.com/scikit-image/scikit-image/blob/master/skimage/restoration/_unwrap_1d.pyx
Our issue: https://github.com/scikit-image/scikit-image/issues/4727
Our CI failure: https://ci.appveyor.com/project/scikit-image/scikit-image/builds/32990701/job/6oxfs51ij6fk6jqi#L840

Do you have any idea on how to fix this? Is it a bug from your or our side?

(Cc @emmanuelle)

**Comment by da-woods** [comment]
I'd guess https://github.com/cython/cython/commit/399a72d75c7413f67cf9b62a5a24e4084d4e4ba7 didn't get merged into 0.29.18?

**Comment by scoder** [comment]
> I'd guess 399a72d didn't get merged into 0.29.18?

Oh, well. Yeah, sorry for that. I'll release a 0.29.19 with that fix then (4ca10b5fc1e5295dc00337b3243023344b5f291a).

**Comment by emmanuelle** [comment]
Thank you so much for the help @scoder and @da-woods :-) :heart:
