### ISSUE TITLE
Module has no attribute '__pyx_capi__'

### ISSUE THREAD

**Issue by xin-jin** [cython/cython#3627]
Hi, I am using Python 3.7 with cython 0.29.14.

I am confused about the error in the title for long time.

Specifically, I have directories like this:
```
my_pkg/
  __init__.py
  a/
    __init__.py
    __init__.pxd
    setup.py
    cython_ext/
      __init__.py
      __init__.pxd
      basics.pyx
      basics.pxd
  b/
    __init__.py
    __init__.pxd
    setup.py
    cython_ext/
      __init__.py
      basics.pyx
```

There is function defined in `a/cython_ext/basics.pyx`:
```
cpdef void f() nogil
```
and is also declared in `a/cython_ext/basics.pxd`.

`a/setup.py` has an Extention entry like this:
```
Extension(
  "basics",
  sources=["cython_ext/basics.pyx"],
  language="c++",
  extra_compile_args=["-std=c++17"],
  include_dirs=[numpy.get_include()],
)
```
I also have `options={"build": {"build_lib": "cython_ext"}}` so that the `.so` file is generated under `cython_ext`.

I then cimport the function `f` in `b/cython_ext/basics.pyx`:
```
from my_pkg.a.cython_ext.basics cimport f
```

However, when importing the module `b.cython_ext/basics`, it always complains
`AttributeError: module 'my_pkg.a.cython_ext.basics' has no attribute '__pyx_capi__'`

Any idea what goes wrong? I used to have `basics.pyx` and `basics.pxd` directly under `a/` rather than an extra `cython_ext` and they used to work. Really confused.

**Comment by xin-jin** [comment]
I spent the whole weekend trying to figure out this issue, and finally got it ...

First, the setup.py has to be changed to
```
Extension(
  "cython_ext.basics",
  sources=["cython_ext/basics.pyx"],
  language="c++",
  extra_compile_args=["-std=c++17"],
  include_dirs=[numpy.get_include()],
)
```

However, doing this alone won't work, and this is what made me fail again and again... After changing setup.py, one also needs to delete all `__pycahe__` and `build` in all relevant folders before running `python setup.py build_ext` (simply adding `--force` without deleting those intermediate files won't work).

**Comment by scoder** [comment]
Ah, yes. This is wrong:
> I also have options={"build": {"build_lib": "cython_ext"}} so that the .so file is generated under cython_ext.

This does not make "cython_ext" a package. If you want the extension to be in a package, you have to name it that way. If you have a specific place in the documentation where you looked and did not find that information, I'd be happy to receive a PR that clarifies it.

**Comment by xin-jin** [comment]
> Ah, yes. This is wrong:
> 
> > I also have options={"build": {"build_lib": "cython_ext"}} so that the .so file is generated under cython_ext.
> 
> This does not make "cython_ext" a package. If you want the extension to be in a package, you have to name it that way. If you have a specific place in the documentation where you looked and did not find that information, I'd be happy to receive a PR that clarifies it.

Thanks! 

It would be nice if you could add a simple example illustrating building extensions in subdirectories in https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html
