### ISSUE TITLE
Coverage plugin is broken on Cython modules in packages with sources in src-layout

### ISSUE THREAD

**Issue by webknjaz** [cython/cython#3636]
_(Ref: https://twitter.com/webKnjaZ/status/1265373614003625987)_

Having a module under src-layout causes `Cython.Coverage.Plugin` to not set itself as a tracer in the DB. And even when it's set, it fails to matchthe module with its sources

I've made a reproducer repo with GitHub Actions Workflow integrated as a demo of this bug:
- https://github.com/webknjaz/cython-coverage-extern-bug-repro-issue3636
- https://github.com/webknjaz/cython-coverage-extern-bug-repro-issue3636/runs/718112079?check_suite_focus=true#step:13:6

When this happens, the following message is printed out during the report stage:
```console
Couldn't parse '..../src/call_mymath/call_mymath.pyx' as Python source: 'invalid syntax' at line 1
```

Reproducer details:
==================
It's based on the example https://github.com/cython/cython/tree/master/Demos/libraries with a slightly modified structure:
```console
|- mymath.c
|- mymath.h
|- setup.py
|- src/
    |- call_mymath/
        |- call_mymath.pyx
        |- __init__.py
    |-flat_ns_call_mymath.pyx
|- test_cython.py
```
`flat_ns_call_mymath.pyx` is the same as `call_mymath.pyx` (the only thing modified inside is relative path to the C-header).

`setup.py` puts both `flat_ns_call_mymath.so` and `call_mymath.so` under `call_mymath` package in `site-packages`. So they are importable as `call_mymath.flat_ns_call_mymath` and `call_mymath.call_mymath`. `call_mymath.flat_ns_call_mymath` shows up in the report and `call_mymath.call_mymath` doesn't because `Cython.Coverage.Plugin` fails to map it with the source and claim the file tracing rights.

STR
===
1. `pip install coverage Cython`
2. `CFLAGS=-DCYTHON_TRACE=1 cythonize --inplace --directive=embedsignature=True --directive=emit_code_comments=True --directive=linetrace=True --directive=profile=True '**/*.pyx'`
3. `pip install .`
4. `coverage run -m test_cython`
5. `coverage report` -- this is where it fails with
    ```console
    Couldn't parse '..../src/call_mymath/call_mymath.pyx' as Python source: 'invalid syntax' at line 1
    ```
    (adding `-i` makes at least `flat_ns_call_mymath` show up correctly)

When looking at `.coverage` using `sqlite3`, `flat_ns_call_mymath.pyx` is mapped to `Cython.Coverage.Plugin` in the `tracer` table while there's no record for `call_mymath.pyx` there.

**Comment by webknjaz** [comment]
So here's the reproducer: https://github.com/webknjaz/cython-coverage-extern-bug-repro-issue3636/runs/718112079?check_suite_focus=true#step:13:6.

@scoder ^

**Comment by webknjaz** [comment]
Turns out that Cythonize generates C-sources that don't include `src/` prefix in path comments.

Just adding those comments there makes it show up in the log:
```console
$ sed -i s#/\\*[[:space:]]'"'call_mymath/#/*\ '"'src/call_mymath/#g src/call_mymath/call_mymath.c
``` 

```diff
--- src/call_mymath/call_mymath.c.orig	2020-05-28 23:15:32.663441119 +0200
+++ src/call_mymath/call_mymath.c	2020-05-28 23:17:46.511099303 +0200
@@ -1243,7 +1243,7 @@
 static PyObject *__pyx_tuple__2;
 /* Late includes */
 
-/* "call_mymath/call_mymath.pyx":4
+/* "src/call_mymath/call_mymath.pyx":4
  *     double sinc(double)
  * 
  * def call_sinc(x):             # <<<<<<<<<<<<<<
@@ -1278,7 +1278,7 @@
   __Pyx_RefNannySetupContext("call_sinc", 0);
   __Pyx_TraceCall("call_sinc", __pyx_f[0], 4, 0, __PYX_ERR(0, 4, __pyx_L1_error));
 
-  /* "call_mymath/call_mymath.pyx":5
+  /* "src/call_mymath/call_mymath.pyx":5
  * 
  * def call_sinc(x):
  *     return sinc(x)             # <<<<<<<<<<<<<<
@@ -1292,7 +1292,7 @@
   __pyx_t_2 = 0;
   goto __pyx_L0;
 
-  /* "call_mymath/call_mymath.pyx":4
+  /* "src/call_mymath/call_mymath.pyx":4
  *     double sinc(double)
  * 
  * def call_sinc(x):             # <<<<<<<<<<<<<<
@@ -1375,7 +1375,7 @@
   __Pyx_RefNannyDeclarations
   __Pyx_RefNannySetupContext("__Pyx_InitCachedConstants", 0);
 
-  /* "call_mymath/call_mymath.pyx":4
+  /* "src/call_mymath/call_mymath.pyx":4
  *     double sinc(double)
  * 
  * def call_sinc(x):             # <<<<<<<<<<<<<<
@@ -1667,7 +1667,7 @@
   #endif
   __Pyx_TraceCall("__Pyx_PyMODINIT_FUNC PyInit_call_mymath(void)", __pyx_f[0], 1, 0, __PYX_ERR(0, 1, __pyx_L1_error));
 
-  /* "call_mymath/call_mymath.pyx":4
+  /* "src/call_mymath/call_mymath.pyx":4
  *     double sinc(double)
  * 
  * def call_sinc(x):             # <<<<<<<<<<<<<<
@@ -1679,7 +1679,7 @@
   if (PyDict_SetItem(__pyx_d, __pyx_n_s_call_sinc, __pyx_t_1) < 0) __PYX_ERR(0, 4, __pyx_L1_error)
   __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
 
-  /* "call_mymath/call_mymath.pyx":1
+  /* "src/call_mymath/call_mymath.pyx":1
  * cdef extern from "../../mymath.h":             # <<<<<<<<<<<<<<
  *     double sinc(double)
  * 
```

But this doesn't explain why `flat_ns_call_mymath.pyx` works. If both don't have `src/` both should work the same way but they don't...

**Comment by webknjaz** [comment]
So when `Cython.Coverage._find_dep_file_path(main_file='/home/wk/src/github/webknjaz/cython-coverage-extern-bug-repro-issue3636/src/call_mymath/call_mymath.c', file_path='call_mymath/call_mymath.pyx', relative_path_search=True)` is called, it returns `/home/wk/src/github/webknjaz/cython-coverage-extern-bug-repro-issue3636/call_mymath/call_mymath.pyx` with `src/` missing because it doesn't do any exit checks.

I'm currently confused by the design decisions: should C-files contain a full path relative to the root of the project or `_find_dep_file_path()` should guess the source correctly?

**Comment by webknjaz** [comment]
I've created a PR on the coverage plugin side that tries to match trailing path fragments with the main file: https://github.com/cython/cython/pull/3648.

Ideally, I'd prefer cythonize to put better paths into comments in C-files but I have no idea about the motivation of the current implementation and it's probably more complicated.

**Comment by cmpute** [comment]
I got a even complexer module structure, I don't know this can be fixed or not..

```
|- setup.py
|- module/
    |- submodule1/
        |- impl.pyx
        |- __init__.py
    |- submodule2/
        |- impl.pyx
        |- __init__.py
    |- submodule3.pyx
|- test/
    |- test_submodule1.py
    |- test_submodule2.py
```

PS: I build my package with scikit-build
