### ISSUE TITLE
fused type variable declared in unrelated function causes incorrect type inference

### ISSUE THREAD

**Issue by anntzer** [cython/cython#3642]
The following example
```cython
cimport cython

cdef unrelated(cython.floating x):
    cdef cython.floating t

cdef handle_float(float* x): pass
cdef handle_double(double* x): pass

def main(cython.floating x):
    if cython.floating is float:
        handle_float(&x)
    elif cython.floating is double:
        handle_double(&x)
```
currently causes cython (both 0.29.19 and 3.0a5) to incorrectly (AFAICT) error out with
```
Error compiling Cython file:
------------------------------------------------------------
...

def main(cython.floating x):
    if cython.floating is float:
        handle_float(&x)
    elif cython.floating is double:
        handle_double(&x)
                     ^
------------------------------------------------------------

test.pyx:13:22: Cannot assign type 'float *' to 'double *'
```
Note that commenting out the `cdef cython.floating t` declaration removes the error, even though `unrelated` is never used by `main`.

**Comment by da-woods** [comment]
I think (but could yet be wrong) that it's https://github.com/cython/cython/blob/0532a0919be640210eeba1144717a6273707e112/Cython/Compiler/Nodes.py#L1035

cythonscope is having the attribute `fused_to_specific` set on it, and that influences all subsequent lookups. Not sure right now how it should be fixed though.
