### ISSUE TITLE
please create a real-time chat for users to discuss amongst themselves.

### ISSUE THREAD

**Issue by davidbuzz** [cython/cython#3653]
i suggest https://gitter.im/cython/cython   but as an outsider i'm not allowed to make it. 
Alternatively a Cython-Users facebook group, or a 'discord' channel would be nice, or all of them.   at least one anyway.     cython-users email list is so 20 years ago, and non-real-time.

**Comment by scoder** [comment]
Haven't used it in a while, but isn't there still a #cython IRC channel on freenode?

**Comment by davidbuzz** [comment]
.. It might as well be in the dark web or on the moon if its not published in the cython docs and/or github, If that's the only choice, then please document it here...  also irc is so 20 years ago.

**Comment by scoder** [comment]
> irc is so 20 years ago.

So is email. I checked, the IRC channel still exists.

**Comment by davidbuzz** [comment]
I thankyou for documenting the IRC channel, but I'd like to point out that gitter.im is far superior,  free, used by tens of thousands of open source projects, and has no downsides,  so I wonder why not use it?

**Comment by meawoppl** [comment]
This died...
![image](https://user-images.githubusercontent.com/579782/155827233-5f46aae4-a7d8-46c2-81ef-607f72058d93.png)

**Comment by graingert** [comment]
twisted uses https://gitter.im/twisted/twisted with a bridge to libera chat #twisted and it works great! I recommend you try it out and see if you want the same support in cython
