### ISSUE TITLE
Please implement ᴘᴇᴘ572 along the new := operator !

### ISSUE THREAD

**Issue by ytrezq** [cython/cython#3656]
This is related to the new `:=` operator which is used by several ᴇᴠᴍ implementations like the one in the Panoramix decompiler fork from Palkeo.

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        res = []
        idx = 0

        while idx < len(trace):
            if idx + number <= len(trace):
                if (r2 := f(trace[idx : idx + number])) is not None:
                      ^
    ------------------------------------------------------------

    helpers.pyx:237:19: Expected ')', found ':'
Which means the syntax above is in reality correct starting with Python3.8…

**Comment by da-woods** [comment]
There's already an issue for this https://github.com/cython/cython/issues/2636
