### ISSUE TITLE
Cython 3.0a5 fails to cythonize on msvc(x64:LLP64 model)

### ISSUE THREAD

**Issue by neonene** [cython/cython#3659]
since cython-447445a3f4c651c2881bc5b50b8d3a1b3fc6b7a6
(Patch title: Speed up Machines.py by compiling it.)

On cythoning with Python3.9b1(win64), Machines.pyd and Transitions.pyd
raise "OverflowError: Python int too large to convert to C long".

To avoid this error and warning, it seems good to replace
'long' in the following 5 files with 'Py_ssize_t'.  And it works fine for me.

   Cython/Plex/Machines.py
   Cython/Plex/Machines.pxd
   Cython/Plex/Scanners.pxd
   Cython/Plex/Transitions.pxd
   Cython/Compiler/Scanning.pxd

But I'm not sure this is correct because a compiler warning below remains
and PyUnicode_FromOrdinal() requires 'int' argument.

Cython/Plex/Machines.py:167 (cython-3ee066283d503d9ed494f90793ee89e6973904f8)
165:            elif code1 != maxint:
166:                while code0 < code1:
167:                    state[unichr(code0)] = new_state  # <<<<<<<<<<<<<<
168:                    code0 += 1

Machines.c
6897:   __pyx_t_4 = PyUnicode_FromOrdinal(__pyx_v_code0);
warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data

**Comment by scoder** [comment]
Thanks for the report. It's rather an incorrect value being passed here than an incorrect type being declared.
