### ISSUE TITLE
(upgrade cython3) ubuntu 18.04 - howto upgrade cython3

### ISSUE THREAD

**Issue by mrkapqa** [cython/cython#3665]
Hello,

i am trying to follow a guide from svp4linux to build mpv with vaporsynth support.

it relies on cython3 >= 0.28., however, ubuntu 18.04 LTS offers only 0.26.

i don't want to upgrade at this moment to 20.04 LTS because Ubuntu is more stable with AMD proprietary driver here and for 20.04 they are not released yet.

Please show me a way to upgrade the cython3 package.

Tried with

sudo pip3 install cython3

but this gave

"ERROR: Could not find a version that satisfies the requirement cython3 (from versions: none)
ERROR: No matching distribution found for cython3"

**Comment by da-woods** [comment]
Hi. User support questions go to the mailing list (https://groups.google.com/forum/#!forum/cython-users), not the bug trackers. I suggest you look at the [installation instructions](http://docs.cython.org/en/latest/src/quickstart/install.html) first.
