### ISSUE TITLE
Could you please remove master branch and problematic words from the code?

### ISSUE THREAD

**Issue by ghost** [cython/cython#3684]
Words such as master, slave, blacklist and whitelist are not suitable due to the deep history associated with racism.
They can be more accurate and precise than they are currently.

Golang team has already removed the use of those words in their code along with few others - https://www.reddit.com/r/golang/comments/gy9ylr/go_has_removed_all_uses_of_blacklistwhitelist_and/
There are other big projects which have done the same.

Here is a tweet from the github CEO - https://twitter.com/Una/status/1271180494944829441

PS - Historical context for main - https://www.nakasendoway.com/the-japanese-family-system/

Please consider alternatives such as canary, develop or edge.

**Comment by scoder** [comment]
I can see how "blacklist" and "whitelist" can be (voluntarily) interpreted in a way that suggests a racist historic context, and wouldn't mind replacing those names in the code.

I do not see why "master" should be interpreted in the context of "master and slave". It stems from the German word "Meister", which means "someone who learned (and mastered) a capability". Naming the "master" branch "master branch" means that it's the branch that aggregates all approved capabilities (or merged feature branches, if you prefer). I do not see a "master-slave" relation in this context, and the word "slave" doesn't seem to be used in the code base.

**Comment by oracleaide** [comment]
Just replace it with Meister.  English is a Germanic language. 
What are we supposed to do with Slavs who were the first slaves? 
In French "Slavic" is written as "slave".  Are we supposed to remove traces of Slavs as well?

**Comment by robertwb** [comment]
Some terms are inherently (or even intentionally) offensive and are certainly worth avoiding. As pointed out, master has many other meanings (e.g. those derived from meister, and also related to the concept of mastering a record from which other copies are made) that clearly apply here. Renaming this branch would do nothing to combat the actual issues of racism beyond virtue signaling, and has pragmatic concerns. 

I am going to close this request.
