### ISSUE TITLE
regression in 0.29.20: type object 'foo' has no attribute '__div__'

### ISSUE THREAD

**Issue by astraw** [cython/cython#3688]
I maintain [cgkit1](https://github.com/strawlab/cgkit1/), and with 0.29.20, the compiled code is not functional.

Steps to reproduce:

```
# download and extract the files for cgkit1 1.2.5 from https://pypi.org/project/cgkit1/#files
cd cgkit1-1.2.5
pip install cython==0.29.20
python setup.py install
python -c "import cgtypes" # cgtypes is installed by cgkit
```

I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "cgtypes.pyx", line 1, in init cgtypes
    # -*- coding: utf-8 -*-
AttributeError: type object 'cgtypes.vec3' has no attribute '__div__'
```

If I repeat with Cython 0.29.19, I do not get this error. This is with Python 3.8.3 and pip installed from conda on Windows.

**Comment by scoder** [comment]
This is probably due to the (disabled) change for #2056. Looks like there was more that should not have been changed (or should have been disabled) in the 0.29.x branch.

**Comment by scoder** [comment]
Could you please check if the latest 0.29.x branch works for you?

**Comment by astraw** [comment]
Yes, I checked ad6e273167a9fc81b6c3a6e4bd1b48b41b55f5dc and this worked for me. Thanks.
