### ISSUE TITLE
Avoid &PyTuple_GET_ITEM()

### ISSUE THREAD

**Issue by vstinner** [cython/cython#3701]
Giving a direct access to an array of `PyObject*` (`PyObject**`) is causing issues with other Python implementations, like PyPy, which don't use PyObject internally.

https://bugs.python.org/issue41078 converts PyTuple_GET_ITEM() macro to a static inline function which prevents to write `&PyTuple_GET_ITEM()`.

Cython uses it at exactly 4 lines (in 3 functions).

`__Pyx_CyFunction_CallAsMethod()` uses::

```
#if CYTHON_METH_FASTCALL
    // Prefer vectorcall if available. This is not the typical case, as
    // CPython would normally use vectorcall directly instead of tp_call.
     __pyx_vectorcallfunc vc = __Pyx_CyFunction_func_vectorcall(cyfunc);
    if (vc) {
        return __Pyx_PyVectorcall_FastCallDict(func, vc, &PyTuple_GET_ITEM(args, 0), PyTuple_GET_SIZE(args), kw);
    }
#endif
```

`__Pyx_PyFunction_FastCallDict()` and `__Pyx__GetModuleGlobalName()` use::

```
            /* function called with no arguments, but all parameters have
               a default value: use default values as arguments .*/
            args = &PyTuple_GET_ITEM(argdefs, 0);
            result =__Pyx_PyFunction_FastCallNoKw(co, args, Py_SIZE(argdefs), globals);
(...)
k = &PyTuple_GET_ITEM(kwtuple, 0);
(...)
        d = &PyTuple_GET_ITEM(argdefs, 0);
```

One option is to use `_PyTuple_ITEMS()` providing by the internal `pycore_tuple.h` header file... but I strongly discourage to use the internal C API. It would make C extensions tightly coupled with CPython versions, break at every single Python release (the internal C API does not provide any kind of backward compatibiltiy warranty), etc.

**Comment by vstinner** [comment]
__Pyx_CyFunction_CallAsMethod() can use PyVectorcall_Call() on Python 3.8 and newer: it takes positional arguments as a tuple and keyword arguments as a dictionary. It uses `_PyTuple_ITEMS()` internally (an internal function returning `PyObject**`).

**Comment by vstinner** [comment]
For `__Pyx_PyFunction_FastCallDict()`, it's more complex. Python 3.8 provides a **private** `_PyFunction_Vectorcall()` function which uses the VECTORCALL calling convention::

```
PyObject *
_PyFunction_Vectorcall(PyObject *func, PyObject* const* stack,
                       size_t nargsf, PyObject *kwnames)
```

It is called `_PyFunction_FastCallDict()` in Python 3.6 and 3.7.

But I discourage to use **private** functions.

**Comment by scoder** [comment]
Thanks for bringing this up, Victor.

> I discourage to use private functions.

At least Py3.[678] won't change any more, so what we have seems fine for those and using the private functions that they provide should also be ok.

For later versions, we'll have to see what to do. We tend to take whatever is available, but provide fallbacks for PyPy & friends whenever we do something CPython specific.

**Comment by vstinner** [comment]
If CPython lacks a C API to call a function with the calling convention used by Cython, we can consider to add a public new function to CPython. I would prefer to not degrade performances if needed.

**Comment by scoder** [comment]
Note sure if it makes a visible difference for real-world code, but a nice property of the current implementation in `__Pyx_CyFunction_CallAsMethod()` is the extremely short inlined fast-path to the indirect vector function call. It's literally just a couple of pointer dereferences.

That makes me question what's so bad about `&PyTuple_GET_ITEM()` when used in CPython. I pushed 5492c4295ecb97d5d9468cc0fa4a870c32307e53 to guard the usage in `__Pyx_CyFunction_CallAsMethod()` behind the usual feature flag (which is disabled in PyPy), even though that doesn't change the situation in CPython after your change.

**Comment by vstinner** [comment]
The plan is to ban ``PyObject**`` in the public C API of CPython: https://bugs.python.org/issue41078

**Comment by vstinner** [comment]
> The plan is to ban PyObject** in the public C API of CPython: https://bugs.python.org/issue41078

Apparently, other people consider that it's not a big deal, and no solution was designed. I close the issue.
