### ISSUE TITLE
Compiler crash: `AttributeError: 'set' object has no attribute 'cf_is_null'`

### ISSUE THREAD

**Issue by ell1e** [cython/cython#3712]
I am getting a compiler crash trying to install a python project:
```
Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/ellie/.local/lib/python3.8/site-packages/Cython/Compiler/Optimize.py", line 2012, in visit_SimpleCallNode
    function = self.get_constant_value_node(function_name)
  File "/home/ellie/.local/lib/python3.8/site-packages/Cython/Compiler/Optimize.py", line 1996, in get_constant_value_node
    if name_node.cf_state.cf_is_null:
AttributeError: 'set' object has no attribute 'cf_is_null'
```
This is the crashing line:
https://github.com/wobblui/wobblui/blob/master/src/wobblui/filedialog.pyx#L365
This is the version of Cython I'm using:
```
$ pip3 show Cython
Name: Cython
Version: 0.29.20
Summary: The Cython compiler for writing C extensions for the Python language.
Home-page: http://cython.org/
Author: Robert Bradshaw, Stefan Behnel, Dag Seljebotn, Greg Ewing, et al.
Author-email: cython-devel@python.org
License: Apache
Location: /home/user/.local/lib/python3.8/site-packages
Requires: 
Required-by:
```

Pretty sure it worked with a previous Cython version many months ago, so possibly a regression...? Not sure

**Comment by da-woods** [comment]
It definitely looks like a bug. Here's a simplified version of your code that reproduces it:

```
def run(done_callback):
    try:
        [] # anything
    finally:
       done_callback(result)
```

As far as I can tell being in the `finally` block is needed for the bug to trigger. If it's in try/except/else/not-in-a-try-block then you don't see it.

`cf_state` looks to be initially made a `set`, then replaced with a `ControlFlowState` object in `FlowControl.check_definitions`. It seems like in this case it isn't be replaced correctly.

Unfortunately this is where I'm outsmarted, so I don't think I can fix it.

**Comment by scoder** [comment]
If it works for older versions, then `git bisect` could help to find how this was introduced.

**Comment by da-woods** [comment]
bbef4d74841b7e979a45d9bbb59c5a1c733a55d7 - which makes sense because it was changing flow-control and finally

**Comment by ell1e** [comment]
I can confirm it works for me now, thanks for the fix!
