### ISSUE TITLE
BUG: code generated by cython uses features not supported by xlc/xlC

### ISSUE THREAD

**Issue by aixtools** [cython/cython#3723]
I am trying to build pandas. It's first step is to cythonize the source code.

The build process ends with:

```
"pandas/_libs/window/aggregations.cpp", line 5436.23: 1540-0063 (S) The text "(" is unexpected.
"pandas/_libs/window/aggregations.cpp", line 5523.23: 1540-0063 (S) The text "(" is unexpected.
"pandas/_libs/window/aggregations.cpp", line 6759.21: 1540-0063 (S) The text "(" is unexpected.
"pandas/_libs/window/aggregations.cpp", line 20023.21: 1540-0063 (S) The text "(" is unexpected.
```

On examining this I see that there are special statements - perhaps unsupported by xlc/xlC (v11).

```
 +5436      __pyx_t_1 = (std::signbit(__pyx_v_val) != 0);

 +5523      __pyx_t_1 = (std::signbit(__pyx_v_val) != 0);

 +6759    __pyx_t_1 = (std::isnan(__pyx_v_val) != 0);

+20023    __pyx_t_1 = (std::isnan(__pyx_v_val) != 0);

```

Just one more complete except - to give a bit more context:
```

+20016    /* "pandas/_libs/window/aggregations.pyx":1634
+20017   *         float64_t temp, q, r
+20018   *
+20019   *     if isnan(val):             # <<<<<<<<<<<<<<
+20020   *         return
+20021   *
+20022   */
+20023    __pyx_t_1 = (std::isnan(__pyx_v_val) != 0);
+20024    if (__pyx_t_1) {
+20025
+20026      /* "pandas/_libs/window/aggregations.pyx":1635
+20027   *
+20028   *     if isnan(val):
+20029   *         return             # <<<<<<<<<<<<<<
+20030   *
+20031   *     nobs[0] = nobs[0] + 1
+20032   */
+20033      goto __pyx_L0;
+20034
+20035      /* "pandas/_libs/window/aggregations.pyx":1634
+20036   *         float64_t temp, q, r
+20037   *
+20038   *     if isnan(val):             # <<<<<<<<<<<<<<
+20039   *         return
+20040   *
+20041   */
+20042    }
```

Is this something I can resolve manually?

How can I test-drive the Python to C conversion?

Thanks!

**Comment by da-woods** [comment]
These are coming being generated because Pandas is using these functions from the C++11 standard library:

https://github.com/pandas-dev/pandas/blob/7e25af85fa6fc91bc606d130a4f81b1af8fd4d91/pandas/_libs/window/aggregations.pyx#L15-L19

Cython is doing exactly what it's being asked to here. You either need to turn on C++11 support on your compiler, or persuade the maintainers of Pandas not to use it.

**Comment by da-woods** [comment]
Or get Pandas to add a compiler specific work-around here https://github.com/pandas-dev/pandas/blob/1546c35dc839b3f6c094ad41d14cda24e9e13a0c/pandas/_libs/src/headers/cmath

**Comment by aixtools** [comment]
Thanks. I also posted on pandas. However, as I mentioned above - xlc/xlC (v11) does not seem to support C++11. (And I see you added a comment while was typing - I'll look at it!  -- THX!!)
