### ISSUE TITLE
PyUnicode_AS_UNICODE is deprecated in Python 3.9

### ISSUE THREAD

**Issue by charris** [cython/cython#3724]
This causes test failures for NumPy and isn't fixed in 3.0.a5. It can be worked around if needed but it would be nice if it was fixed before Python 3.9 came out.

**Comment by da-woods** [comment]
I think this has been fixed since the release of 3.0.a5. It might be worth trying the current master (or waiting for a6).

All the usages I can find in the source look to be conditionally compiled.

**Comment by charris** [comment]
I installed Cython from master this morning, hence the report :)

**Comment by charris** [comment]
The actual problem is `PyUnicode_DATA`
```
#elif PY_VERSION_HEX > 0x03030000 && defined(PyUnicode_KIND)
  #define CYTHON_PEP393_ENABLED 1
  #define __Pyx_PyUnicode_READY(op)       (likely(PyUnicode_IS_READY(op)) ?\
                                              0 : _PyUnicode_Ready((PyObject *)(op)))
  #define __Pyx_PyUnicode_GET_LENGTH(u)   PyUnicode_GET_LENGTH(u)
  #define __Pyx_PyUnicode_READ_CHAR(u, i) PyUnicode_READ_CHAR(u, i)
  #define __Pyx_PyUnicode_MAX_CHAR_VALUE(u)   PyUnicode_MAX_CHAR_VALUE(u)
  #define __Pyx_PyUnicode_KIND(u)         PyUnicode_KIND(u)
  #define __Pyx_PyUnicode_DATA(u)         PyUnicode_DATA(u)
```

**Comment by charris** [comment]
I think you need to use `PyUnicode_KIND` and call the correct version of `PyUnicode_nBYTE_DATA`, where `n` is 1, 2, or 4.

**Comment by charris** [comment]
Oops, looks like the remaining errors actually come from NumPy C code.

**Comment by scoder** [comment]
Yeah, all these deprecations are really annoying and difficult to work around. It's easy to write code that works with and without `Py_UNICODE`, but it's difficult to write correct code while `Py_UNICODE` is still available and used in CPython without running into deprecation warning that make user code fail.

I've just disabled the usage for Py3.9+ in 336363893b6cc02f6c1d0f26102ea2501784f7d7 and now require PEP-393 to be available. Users shouldn't have an interest in disabling the support in Cython.
