### ISSUE TITLE
Is there a way to compile large files?

### ISSUE THREAD

**Issue by Nimdim** [cython/cython#3738]
Hello all!
I have a py file in my project file which size is 1.7mb.
While compiling first a .c file of size 40.4mb is produced.
While processing compilation takes 6.5 gb RAM and then fails when RAM and SWAP are exhausted.
Is there a way to compile such files? For example by automatically breaking them to several .c files parts?

**Comment by da-woods** [comment]
Support questions are better asked on [the cython-users mailing list](https://groups.google.com/forum/#!forum/cython-users).

The answer is probably roughly:
1. buy more RAM.
2. reduce the C optimization level
3. split the py files into multiple submodules.
