### ISSUE TITLE
Conversion function redefinition error when handling C++ types

### ISSUE THREAD

**Issue by KmolYuan** [cython/cython#3741]
I have a extension class which including C++ member (`std::vector<my_struct>`, and `my_struct` has some `std::pair<int, int>` members).
And there also has a `std::pair<int, int>` type definition in the same source.

I'm found that the conversion function (`std::pair<int, int>` to `tuple[int, int]`) is defined twice unless added `@cython.auto_pickle(False)` on my extension class.

```
11510:18: error: redefinition of 'PyObject* __pyx_convert_pair_to_py_int____int(const std::pair<int, int>&)'
 static PyObject *__pyx_convert_pair_to_py_int____int(std::pair<int,int>  const &__pyx_v_p) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10055:18: note: 'PyObject* __pyx_convert_pair_to_py_int____int(const std::pair<int, int>&)' previously defined here
 static PyObject *__pyx_convert_pair_to_py_int____int(std::pair<int,int>  const &__pyx_v_p) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm not clearly know how Cython checks the tool functions of `ctypedef`.
In another case My extension members are sharing a same `ctypedef` with local variables, but this error is not occurred.

**Comment by KmolYuan** [comment]
When I'm using `vector[pair[int, int]]` and `map[int, bint]` in the same file, the error comes again.
Regardless creating type alias or using original form can't solve the problem.

Maybe somewhere Cython treats `bint` as a different type when generating conversion functions.

**Comment by da-woods** [comment]
This looks like substantially the same issue as https://github.com/cython/cython/issues/3716 and https://github.com/cython/cython/issues/3734. The problem is where Cython utility code is itself generating utility code. Each lot of 2nd-level generated utility code is generated without access to the full module scope so can end up sharing names.

I'll try to have a look at it in the near future. Although it looked trick to solve last time I looked

**Comment by KmolYuan** [comment]
My case is little complex, which mixed a lot of functions and cannot extracted a small one.
I'm not actually know what cause the duplicated code in my module.

The repo is here, change this line from `Status &` to `object` can reproduce the error: (build by `setup.py`)
https://github.com/KmolYuan/pyslvs/blob/master/pyslvs/topo_config.pyx#L187

But this error does not bother me at the moment.
