### ISSUE TITLE
How to use str(cython.char *) in pure python mode?

### ISSUE THREAD

**Issue by Chise1** [cython/cython#3742]
I want to use cython.char * type pure python's str ,how to use it ?(pep484)

**Comment by da-woods** [comment]
Support questions can be asked on [the cython-users mailing list](https://groups.google.com/forum/#!topic/cython-users/). The bug tracker is for bugs and feature requests.

**Comment by da-woods** [comment]
https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#c-types

`cython.pointer(cython.char)` or `cython.p_char`
