### ISSUE TITLE
Cannot use importlib to import Cython extensions

### ISSUE THREAD

**Issue by HunterAP23** [cython/cython#3745]
I have a module with functions that I compile without any manual optimizations. The normal version of the code looks like:
```py
def Main_Default(value_max: int, num_loops: int, rlock, runtime: str, compilation: str, call_type: str, subcall: str, case: str):
```

I then tried modifying the function to use C-type declarations like so:
```py
cdef void Main_Default(int value_max, int num_loops, rlock, str runtime, str compilation, str call_type, str subcall, str case):
```
The function doesn't return anything, and all the variables are of the correct type.

In my main program, I'm dynamically importing different modules using `importlib` based on a JSON file's parameters - basically letting a user choose what modules to import rather than importing all the modules. I do this through a snippet like this:

```py
if info["library"] in sys.modules:
    print("{0} module has already been loaded.".format(info["library"]))
else:
    lib = importlib.import_module(info["library"], package=info["package"])
    print("Loaded module '{0}'.".format(info["library"]))
...
funcs[group] = vars(lib)["Main_Default"]
```

Where `info["package"]` is the top-level package of my module, and `info["library"]` is the actual module's full name. The last line is where I assign the `Main_Default` function to a dictionary value where I'll call it later.

All works fine in the first scenario where I'm using Python function declaration, where I'm met with the success message and the module runs fine when it's called.

The issue is that when using C-type function declarations, Importing the module works fine (as I still get the success message), but when trying to assign the `Main_Default` function of the module I get the following error message:
```py
'Main_Default' is not a valid function inside 'my_package.my_module'
```

I printed out the `vars(lib)` for my module just to make sure the function was listed, and the `Main_Default` function is not listed.
I believe this is due to `importlib` using the Python `import1 function, while in this case I'd want to use Cython's `cimport` function.

Any way I can use `importlib` or some similar dynamic method for Cython extensions?

**Comment by HunterAP23** [comment]
I see now through some more research that I should be using `cpdef` instead of `cdef` for my function declaration, but now I'm running into this issue:
```py
cpdef void Main_Default(int value_max, int num_loops, rlock, str runtime, str compilation, str call_type, str subcall, str case):
     ^
------------------------------------------------------------

my_package.my_module.pyx:14:6: closures inside cpdef functions not yet supported
```

**Comment by scoder** [comment]
This is a usage question, not a bug. Thus, the bug tracker is the wrong place to discuss this. Use the cython-users mailing list instead.

I would suggest to use a normal `def` function instead.
