### ISSUE TITLE
Memory leak with memory views and `NPY_RELAXED_STRIDES_CHECKING`

### ISSUE THREAD

**Issue by peterbell10** [cython/cython#3747]
The following code will leak memory for every function call:
```python
a = np.random.rand(10)[:, None]
def memory_leak():
    cdef double [:,::1] arr = a
    return
```

The `a` array has strides `(8, 0)` but is still considered contiguous by numpy because the axis is only length 1. So, changing `a` to `np.ascontiguousarray(a)` has no effect.

I am using python 3.7 and cython 0.29.12.

**Comment by da-woods** [comment]
I think this might be a Numpy bug. Here's an alternative version that just uses the C API buffer interface (through Cython, for convenience) that shows the same issue

```
import numpy as np

from cpython.buffer cimport *

a = np.random.rand(10)[:, None]
b = np.random.rand(10)

def version_1():
    cdef Py_buffer buf
    PyObject_GetBuffer(a, &buf, PyBUF_STRIDED)
    PyBuffer_Release(&buf)


def version_2():
    cdef Py_buffer buf
    PyObject_GetBuffer(b, &buf, PyBUF_STRIDED)  # array "b" instead of "a"
    PyBuffer_Release(&buf)
```

Running `version_1` in a loop shows the same behaviour as the memoryview version (a continuous increase in memory used). Running `version_2` in a loop doesn't show a memory leak.

I'll close this as "third party" but feel free to tell me if I've done something wrong.
