### ISSUE TITLE
Symbol not found: Py_SET_TYPE

### ISSUE THREAD

**Issue by andyfaff** [cython/cython#3748]
In https://github.com/scipy/scipy/issues/12489 I report errors raised whilst trying to run scipy after building with:

macOS 10.15.5
Python 3.8.3
numpy 1.19.0
cython 0.29.20

I get the following stacktrace upon import:

```
>>> import scipy.optimize as sciopt
sciopt.Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/__init__.py", line 387, in <module>
    from .optimize import *
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 33, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/linesearch.py", line 16, in <module>
    from scipy.optimize import minpack2
ImportError: dlopen(/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/minpack2.cpython-38-darwin.so, 2): Symbol not found: _Py_SET_TYPE
  Referenced from: /Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/minpack2.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/minpack2.cpython-38-darwin.so
```

The same import works when I use cython 0.29.18 to build scipy. I'm guessing this may be a cython issue, so reporting here.

**Comment by da-woods** [comment]
As far as I can tell Cython doesn't (and has never) contained the symbol `_Py_SET_TYPE`.

It was added to CPython fairly recently https://github.com/python/cpython/commit/d2ec81a8c99796b51fb8c49b77a7fe369863226f#diff-dab5801649f1809dca3b570bd3a86f05 and looks to appear in the upcoming version 3.9. Therefore I wouldn't expect it to appear in a Python 3.8 module at all.

Is it possible that you're somehow accidently including some Python 3.9 headers installed somewhere in your PC while compiling your module? I'm not sure how the Cython version you have installed should affect this though.

**Comment by andyfaff** [comment]
No 3.9 headers on my Mac. But I am using miniconda env python I wonder if that has anything to do with it.

**Comment by andyfaff** [comment]
I think the issue is due to doing a:

```
python setup.py build
pip install .
```

Instead of a straightforward:
```
pip install .
```

I think the former builds against the installed version of (a newer) numpy, whereas the latter builds against a pinned numpy version. So I think that there are symbols that don't get defined correctly with the former.
