### ISSUE TITLE
[Feature Request] Support clang-cl as compiler 

### ISSUE THREAD

**Issue by kingyue737** [cython/cython#3752]
clang-cl support C99. It would be nice if we can choose clang-cl as compiler in Windows

**Comment by da-woods** [comment]
I think this is really a setuptools/distutils issue - Cython mostly does the pyx -> c step and leaves compiling the C code to those.

There's also a separate core Python issue. The C compiler on Windows needs to be compatible with the one that Python was compiled with - see https://wiki.python.org/moin/WindowsCompilers. I don't know if clang-cl is.

**Comment by da-woods** [comment]
Follow-up to this some years later: it's still a setuptools/distutils issue. It does work in alternative build systems like Meson (I expect skbuild is fine too). So anyone wanting to do this should probably "just" switch build system.

It'd be nice if Cython were able to test clang-cl but unfortunately our tests are very tied to setuptools.
