### ISSUE TITLE
Is there an efficient way to store python object in a list?

### ISSUE THREAD

**Issue by cmpute** [cython/cython#3757]
What I want to achieve is accessing a list of python objects with little overhead. Originally I thought I can use
```cython
cdef class Something:
    cdef int prop
cdef vector[Something] some_list

# accessing
print(some_list[0].prop)
```
But I found that Python object cannot be used as template parameter. Is there any efficient way to achieve similar behavior? Maybe directly using `PyObject*` is an option, but I guess there will be some reference counting problems?

**Comment by scoder** [comment]
Use a Python list.

Note that the bug tracker is the wrong place to ask usage related questions. Use the cython-users mailing list instead.
