### ISSUE TITLE
Help On Compile of setup.py

### ISSUE THREAD

**Issue by Harshil783** [cython/cython#3769]
> Command: `python3 setup.py build_ext --inplace -DMS_WIN64`
 **Error: Does Not Print In Cmd**
 **_Problems Nothing Is Created Not A Main.c file_**
> Setup.py Source Code
`import setuptools
from distutils.core import setup
from Cython.Build import cythonize

setup(
    ext_modules=cythonize("Main.pyx")
)`
File I Am Trying To Compile Are Two File
First File Source Code:
`from ast import literal_eval
import time
print("Welcome To Decimal To Hex Or Binary Converter")
def line():
    for i in range(50):
        print("-",end='')
print("\nPlease Type The 'h' for hex input")
line()
print("\nPlease Type The 'd' for decimal input")
line()
print("\nPlease Type The 'b' for binary input")
line()
temp = input("\nType 'h' or 'd' or 'b':")
line()
time.sleep(1)
print(f"\nSo You type '{temp}'")
time.sleep(1)

for i in temp:
    if i == 'h':
        try:
            time.sleep(1)
            hexa = input("\nPlease Type The Hex Input To Convert Into Deciaml And Binary:")
            time.sleep(1)
            print(f"In The Decimal Form: %s" %(literal_eval(hexa)))
            print(f"In The Binary Form: %s" %(bin(int(hexa,16))))
            time.sleep(5)
        except ValueError:
            print("Only Hex Numbers!")
            print("Hex Numbers Look Like 0x1,0x3, etc.")
            time.sleep(5)
            line()
    elif i == 'd':
        line()
        time.sleep(1)
        print("\nEntering Decimal Mode")
        time.sleep(1)
        line()
        time.sleep(1)
        deci = input("\nPlease Type The Decimal Input To Convert Into Hex And Binary:")
        try:
            time.sleep(1)
            print(f"In The Hexadecimal Form: %s" %(int(deci)))
            print(f"In The Binary Form: %s" %(bin(int(deci,16))))
            time.sleep(5)
        except ValueError:
            print("Only Decimal And Integers Accepted!")
            print("Type Some Simple Numbers like 1,2,3, etc.")
            line()
            time.sleep(5)
    elif i == 'b':
        line()
        time.sleep(1)
        print("\nEntering Binary Form")
        line()
        time.sleep(1)
        bina = input("\nType The Binary Input To Convert In Hexadecimal And Decimal Form:")
        line()
        try:
            time.sleep(1)
            print("\nIn The HexaDecimal Form: %s" %(hex(int(bina,2))))

        except ValueError:
            print("\nOnly Binary Numbers:")
    else:
        print("Please Only Select From 'h' or 'd' or 'b' ")
        time.sleep(5)`
Second File Source Note: **_This is the file used to run first file_**
`import time
from Main_Struct import bina
def bins():
    b_num = list(bina)
    value = 0

    for i in range(len(b_num)):
        digit = b_num.pop()
        if digit == '1':
            value = value + pow(2, i)
    print("The Decimal Form is: %s" %(value))
    time.sleep(5)
bins()`

**Comment by Harshil783** [comment]
**And Second Problem What is python-dev package And How to install in windows?**

**Comment by da-woods** [comment]
The issues tracker is for bug reports and feature requests, not user support.

You might try asking on the cython-users mailing list.
