### ISSUE TITLE
POSIX compliance of Cython

### ISSUE THREAD

**Issue by magnusmusngi** [cython/cython#3770]
I am planning to port a code that uses this Cython library into a POSIX-compliant OS that is neither Linux nor Unix. Given this, I would like to know if this library is POSIX-compliant, and if so, does that mean that I will not have any issues with this library while porting it to the aforementioned OS? Thank you.

**Comment by da-woods** [comment]
I _think_ this is mainly a support question and so should be asked on the Cython users list.

If Python works on your target OS then Cython should work too. If it doesn't then report it as a bug. The generated code should be standard C89 (unless you deliberately use C++ or features from later versions of C) - if the code fails to compile on your OS then report it as a bug. Obviously if a specific Cython library wraps something that doesn't work on your target OS then you're stuck.

Beyond that I'm not sure what "compliance" you're worried about.
