### ISSUE TITLE
C++ Required

### ISSUE THREAD

**Issue by Harshil783** [cython/cython#3771]
Hey! I Have C++ 14.0 Installed In Microsoft Visual Studio Then Why Cython Does Not Recognize Microsoft C++ 14.0 is present

**Comment by scoder** [comment]
1) This has nothing to do with Cython. It's either a distutils issue, or, more likely, a local setup issue.
2) The Cython bug tracker is not the right place to provide general user support. Use the cython-users mailing list for that, or in cases like this, also a general Python mailing list.

**Comment by Harshil783** [comment]
> 1. This has nothing to do with Cython. It's either a distutils issue, or, more likely, a local setup issue.
> 2. The Cython bug tracker is not the right place to provide general user support. Use the cython-users mailing list for that, or in cases like this, also a general Python mailing list.

Hey! Wait I Fixed Issue I Am Getting Error
Like:
||=== Build file: "no target" in "no project" (compiler: unknown) ===|
C:\Users\DELL\Desktop\Python Projects\Personal Projects\Hello_World.c|213|warning: division by zero [-Wdiv-by-zero]|
C:\Users\DELL\Desktop\Python Projects\Personal Projects\Hello_World.c|213|error: enumerator value for '__pyx_check_sizeof_voidp' is not an integer constant|
||=== Build failed: 1 error(s), 1 warning(s) (0 minute(s), 1 second(s)) ===|

**Comment by scoder** [comment]
Yes, that's a safe-guard to detect (and reject) broken setups. You probably installed MinGW or something like that, and it's messing up your local installation even more.

See https://github.com/cython/cython/wiki/CythonExtensionsOnWindows
