### ISSUE TITLE
Generated Code Gives Error

### ISSUE THREAD

**Issue by Harshil783** [cython/cython#3772]
Here is the error
C:\Users\DELL\Desktop\Python Projects\Personal Projects\Hello_World.c|213|error: enumerator value for '__pyx_check_sizeof_voidp' is not an integer constant|

**Comment by da-woods** [comment]
https://github.com/cython/cython/issues/3771#issuecomment-671214549

>     2. The Cython bug tracker is not the right place to provide general user support. Use the cython-users mailing list for that, or in cases like this, also a general Python mailing list.
