### ISSUE TITLE
Support long double functions in libc.math

### ISSUE THREAD

**Issue by RobbenRoll** [cython/cython#3774]
I wanted to use `expl`, i.e. the long double version of `exp`, for an extended precision calculation. In the master branch `expl` got added to `libc/math.pdx` in [this commit](https://github.com/cython/cython/commit/4f9e2e37eb06de526938c428f35a355cdcc466f3) on May 7. However, this change has not been included in a release as of v0.29.21. Was this done intentional? I would be very happy about support for long double C-math functions in future releases since I was hoping to make use of this in a Python package...   

As of v0.29.21 trying to build a .pyx with:
```from libc.math cimport expl```
throws:
```'libc\math\expl.pxd' not found```.

**Comment by RobbenRoll** [comment]
Saw that this has already entered 3.0.0 alpha.

**Comment by da-woods** [comment]
@RobbenRoll Just for the future: there's nothing particularly special about the pxd files that are built into Cython so there's no need to wait for a backport. You can just download the file that you want or copy the functions that you want and include it in your own project (a few do use new features but those are in the minority)
