### ISSUE TITLE
[BUG] __PYX_STD_MOVE_IF_SUPPORTED doesn't work well with MSVC

### ISSUE THREAD

**Issue by Zabolekar** [cython/cython#3789]
Windows 10, Python 3.8.3, Cython 3.0a5, Visual Studio 2017 version 15.9.20.

Let's consider the following example:

a.h:

```cpp
#pragma once
#include <memory>

std::unique_ptr<int> f() {
    return std::make_unique<int>(123456);
}
```

b.pyx:

```cython
from libcpp.memory cimport unique_ptr

cdef extern from "a.h":
    unique_ptr[int] f() except +

def g():
    cdef unique_ptr[int] p = f()
```

setup.py:
```python
from setuptools import setup, Extension
from Cython.Build import cythonize

extensions = [Extension(
    "b",
    ["b.pyx"],
    language='c++'
)]
setup(ext_modules=cythonize(extensions, compiler_directives={"language_level" : "3"}))
```

**Expected behavior**
 `python setup.py build` builds a `.pyd`-file.

**Observed behavior**
`python setup.py build` produces a message referencing error C2280, doesn't build a `.pyd`-file.

**Workaround**
Adding `extra_compile_args=["/Zc:__cplusplus"]` to the arguments of `Extension` fixes the problem.

**Likely reason**
MSVC defines `__cplusplus` as `199711L` by default ([details](https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/))

Cython defines `__PYX_STD_MOVE_IF_SUPPORTED` like this:

([source](https://github.com/cython/cython/blob/master/Cython/Utility/CppSupport.cpp))
```cpp
#if __cplusplus >= 201103L
  #include <utility>
  #define __PYX_STD_MOVE_IF_SUPPORTED(x) std::move(x)
#else
  #define __PYX_STD_MOVE_IF_SUPPORTED(x) x
#endif
```

The generated `.cpp` file tries to copy a `unique_ptr`, and thus doesn't compile.

**Comment by da-woods** [comment]
Does MSVC provide a way to detect C++11 support? Or is it the case that MSVC > "some version" always supports `std::move` whatever command line arguments it's called with? Because if not then we're kind of stuck.

You're currently no worse off now than with for Cython <3, since earlier versions would also have tried to copy the `unique_ptr`. We do want to default to supporting c++98 (so we can't just replace `__PYX_STD_MOVE_IF_SUPPORTED` with `std::move`).

Unless we can reliably detect support then your workaround sounds like the correct solution.

**Comment by Zabolekar** [comment]
I _think_ if both `__cplusplus` and `_MSVC_LANG` are defined, whatever their value, then `std::move` should work. The documentation says:

> _MSVC_LANG Defined as an integer literal that specifies the C++ language standard targeted by the compiler. It's set only in code compiled as C++. The macro is the integer literal value 201402L by default, or when the /std:c++14 compiler option is specified. The macro is set to 201703L if the /std:c++17 compiler option is specified. It's set to a higher, unspecified value when the /std:c++latest option is specified. Otherwise, the macro is undefined. The _MSVC_LANG macro and /std (Specify Language Standard Version) compiler options are available beginning in Visual Studio 2015 Update 3.

As for earlier versions, I, sadly, don't know.

**Comment by da-woods** [comment]
I'm getting the impression that it `std::move` should probably work on at least Visual Studio 2015 onwards (with no obvious way to turn it off). I don't have a huge amount of enthusiasm to download every version of Visual Studio to prove that this is true.

I guess the thing to do would be to turn it on in a PR and see if anything breaks in the Windows tests. The compiler version on Windows is largely dictated by Python anyway, so there aren't a huge variety of options.

**Comment by dgrunwald** [comment]
AFAIK `std::move` was already available in VS2010.
Microsoft only started adding language version switches for their experimental C++17 support; everything up to C++14 is always enabled and cannot be turned off.

Unless you are dealing with older VS versions or legacy code where this is causing compatibility problems, you should be compiling with [/Zc:__cplusplus](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus).

**Comment by da-woods** [comment]
I think this was closed in https://github.com/cython/cython/commit/00e34553343606b7452a515a0ff8b4b7df311423
