### ISSUE TITLE
[BUG] cpdef enum creates PEP 434 wrapper that does not match behavior of PEP 434 enums used in f-strings

### ISSUE THREAD

**Issue by dzimmanck** [cython/cython#3791]
**Describe the bug**
When using a cpdef enum, a PEP 435 style wrapper is generated which allows using the enum in Python code without having to re-define it.  While the resulting enum object has a __str__() method which mirrors a true PEP 435 enum, when an instance of the enum is printed from within an f-string, the integer is printed rather then the enum name.  I suspect there is an inconsistency in the way the``` .__format__()``` method is generated related to PEP 435.

**To Reproduce**
To reproduce, create a cpdef enum
```
cpdef enum CyColors:
    red = 1
    blue = 2
```

In Python, create the same enum using PEP 435
```
from enum import Enum
class PyColors(Enum):
    red = 1
    blue = 2
```

Create instances of both the Python and Cython version and print using an f-string
```
import PyColors
import CyColors

cy_color = CyColors.blue
py_color = PyColors.blue

print(f'{cy_color} is a different string then {py_color}')
```

**Expected behavior**
cy_color should have the same string representation as py_color when used in an f-string

**Environment (please complete the following information):**
 - OS: Windows
 - Python version: 3.7.0
 - Cython version: 3.0a6

**Comment by da-woods** [comment]
As you say it looks like the Cython enum is missing `__format__`. It should probably be added to https://github.com/cython/cython/blob/master/Cython/Utility/CpdefEnums.pyx#L23 (in `__Pyx_EnumBase`).

I think it's PEP 43**5** though.

**Comment by dzimmanck** [comment]
@da-woods 
Yes, I meant PEP 435.  I will edit my original post.

**Comment by da-woods** [comment]
Actually, I'm less convinced that this is a bug. See https://docs.python.org/3/library/enum.html#others :

> Formatted string literals, `str.format()`, and `format()` will use the mixed-in type’s `__format__()`. If the Enum class’s `str()` or `repr()` is desired, use the !s or !r format codes.

Cython's matching the behaviour of `IntEnum` (its enum type is also derived from `int`) so I think the behaviour you see is correct and consistent with the standard library.

**Comment by da-woods** [comment]
I'm closing this because I think Cython's behaviour does make sense for the reasons listed about, and I haven't seen any arguments to the contrary.

**Comment by dzimmanck** [comment]
OK, I think I get it

**Comment by dzimmanck** [comment]
I agree with closing this bug as "works as designed", but if anyone else runs into an issue with their Cython Enums being IntEnums I have a good solution.

The background on my issue was that I was using Cython generated Enums as column names in Pandas dataframes, which uses __format__ for printing so I was getting the integer values when printing the dataframes, which sorta defeats the purpose of using IntEnums rather then Ints.

My solution was to MonkeyPatch the .__format__ method of the Cython enum after importing like so:


`
    import CyColors

    # monkey patch the __format__ method so it displays the name rather then the integer in f-strings
    def format(self, _):
        return self.__str__()
    CyColors.__format__ = format

    cy_color = CyColors.blue

    print(f'{cy_color} is a color')
`

**Comment by scoder** [comment]
@dzimmanck, good idea. This might work as a simpler work-around:
```cython
CyColors.__format__ = CyColors.__str__
```

**Comment by dzimmanck** [comment]
@scoder,

Yes, that was actually the first thing I tried, but `__format__()` expects both self and a format passed as arguments, whereas `__str__()` ony expects self, so I needed to create a new monkey patch function which accepts but ignores the format argument.

**Comment by scoder** [comment]
Right, I missed that part. I changed my proposal above, but you may find a separate function to be easier to read.
