### ISSUE TITLE
[BUG] self documenting expressions in f-strings

### ISSUE THREAD

**Issue by cdrx** [cython/cython#3796]
**Describe the bug**

Python 3.8 added support for the `=` specifier in f-strings to provide self documenting expressions. Using this feature makes a file fail to compile.

**To Reproduce**

test.py:
```test.py
x = 1
print(f"{x=}")
```

then run:

```
$ python test.py
x=1

$ cython -3 test.py

Error compiling Cython file:
------------------------------------------------------------
...
x = 1
print(f"{x=}")
            ^
------------------------------------------------------------

test.py:2:13: Expected ')', found '='
```

**Expected behavior**
No error compiling the file

**Environment (please complete the following information):**
 - OS: macOS
 - Python version 3.8.3
 - Cython version 0.29.21

**Additional context**

https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging

**Comment by StefanD986** [comment]
I can confirm this also in Cython==3.0a6 on windows.

**Comment by scoder** [comment]
Probably easy to implement in `Parsing.py`. PR welcome.
