### ISSUE TITLE
[ENH] Builtin type support for `memoryview`

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#3798]
**Is your feature request related to a problem? Please describe.**

It would be useful to have support for a generic builtin `memoryview`. This can come in handy when the type and dimensionality of the `memoryview` are unknown. In these cases it's tricky to use the Cython `memoryview` as we don't have enough information to type it correctly (or maybe there are tricks I don't know?). The benefit being (much like other builtin types) Cython can translate operations on the `memoryview` into more efficient Python C API calls.

**Describe the solution you'd like**

Here's some sample code showing how this might be used.

```cython
def nbytes(memoryview m):
    cdef Py_ssize_t i, n = m.itemsize
    for i in range(m.ndim):
        n *= m.shape[i]
    return n
```

**Describe alternatives you've considered**

If one knows the type and dimensionality, a Cython `memoryview` can be used. However this doesn't cover the case discussed above (unless I'm missing something). Another alternative is to use the Python C API directly (though this may be less pleasant for other readers and could be buggy if not carefully used).

**Additional context**

NA

**Comment by da-woods** [comment]
What C API functions are you hoping that Cython will generate? There don't look to be a huge number and they're mostly about creating memoryviews: https://docs.python.org/3/c-api/memoryview.html. Similarly [the semi-public struct](https://github.com/python/cpython/blob/8784d3300ec4ffc58bc0e9ab3cff9a24187dbe4c/Include/memoryobject.h#L57) doesn't actually expose a lot of information - all the useful shape/strides/suboffset info is hidden an opaque array at the end

**Comment by jakirkham** [comment]
Yeah I’m hoping things like `memoryview(a)` are translated into `PyMemoryView_FromObject(a)`, `isinstance(mv, memoryview)` gets translated into an appropriate low-level type check, it may also be valuable to have a method to call `PyMemoryView_GetContiguous`, etc..

As to the underlying `Py_buffer`, I think we should be able to get access to it pretty easily as `PyMemoryView_GET_BUFFER` is a macro that does just that. Though agree queries around the buffer can routed through this mechanism.

**Comment by da-woods** [comment]
If you wanted to have a go at writing it then https://github.com/cython/cython/blob/be43235ba3f4fca32dceda46424b36afb3cb00c9/Cython/Compiler/Builtin.py#L252 is where all the types and their member functions are declared (a few are also in Optimize.py, but I think memoryviews would make most sense in Builtin.py. I think getting something basic working is likely to be fairly easy (these type declarations are pretty simple and repetitive).

I suspect the hardest part will be providing fallback versions for PyPy, but that's something we can give suggestions on once it's clear what's needed.

**Comment by jakirkham** [comment]
Thanks for the pointer. That seems like a good place to start.

Do you think we could add [C inline properties]( https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#c-inline-properties ) for the various properties on `memoryview` as well? If so, would they ago in `Builtin.py` or would they go elsewhere? How does Cython handle this kind of thing usually?

**Comment by da-woods** [comment]
> Do you think we could add C inline properties for the various properties on memoryview as well?

It doesn't look like we currently have any examples of handling this kind of thing for the core types. It'd probably need to go in `Builtin.py` with a new class (`BuiltinProperty`) alongside `BuiltinMethod` and `BuiltinAttribute` but that's easier said than done.

**Comment by scoder** [comment]
> How does Cython handle this kind of thing usually?

There is no "usually" here because most of the code in `Builtin.py` predates C inline properties by years, if not a decade or more. ;-)

But yes, inline properties seem right for this. I remember seeing a somewhat recent PR (this year?) that included an unrelated refactoring of `Builtin.py` to use a class for the extension type declarations. Can't find it right now, but it might be worth basing the changes on that.
