### ISSUE TITLE
Add glossary to the documentation

### ISSUE THREAD

**Issue by scoder** [cython/cython#3802]
Something that could help the documentation would be a [glossary](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary-directive) that certain terms could link to. A `pointer` would be a good candidate, or C data structures (struct/union) in general. Also `extension type`, terms like `extern` or `inline`, etc. It wouldn't have to replicate a complete specification or so, just explain shortly what is meant and link to a good place for further reading, be it an internal page or some external resource like the CPython C-API docs or a C/C++ reference.

**Comment by tashachin** [comment]
Hello! I'd like to give this doc issue a shot.

Does this project use an SSG or would establishing a glossary be as simple as editing directly on Github?

**Comment by scoder** [comment]
Hi @tashachin, with "SSG", do you mean some kind of style guide? We don't have one, definitely not for the docs.
You can just edit the Sphinx .rst files and `conf.py` to add a glossary.

**Comment by tashachin** [comment]
Apologies for not clarifying, @scoder ! SSG as in static-site generator (like Sphinx).

Where would you want the glossary to live in the docs? I could add it to the main index.rst (landing page) but that seems like it'd become unwieldy very quickly. 

My solution was to have a link to the glossary be at the same level as Getting Started and Tutorials (and be between them), which then links to a separate page where all the terms can be read.

What are your thoughts on that structure?

**Comment by scoder** [comment]
There is an "indices and tables" section in the user guide. Just add a new page there for the glossary.

**Comment by scoder** [comment]
Closing this ticket since the glossary is there now. We can keep adding to it without the need for a ticket.
