### ISSUE TITLE
[BUG] sys.argv do not show content as string when compiled in Windows

### ISSUE THREAD

**Issue by AlexCstt** [cython/cython#3824]
**Describe the bug**
sys.argv do not show content as string when compiled to .exe in Windows

**To Reproduce**

1. Create a file 'main.pyx' with the following code
```
import sys
print(sys.argv)
```
2. Compile it to C with Cython
3. Compile C to .exe with Gcc
4. Run from Cmd (Terminal) the .exe like this
`app.exe ABC DEF`
5. Sometimes it returns this:
`['?\u2e70?e????\x02', '?CÄQ?????Q?Q?Q', '?FÄQ???']`
6. Sometimes it returns this:
`['?\u2e70?e\uf28f???\x02', '?CÄ"\uf2c9????"?"?"', '?FÄ"\uf2c5??']`

**Expected behavior**

6. It should always return this:
`['app.exe', 'ABC', 'DEF']`

**Environment**
 - OS: Windows Xp, Windows 7, Windows 8, Windows 10
 - Python version: <= 3.8.4
 - Cython version:  0.29.18

**Additional context**

- When when we use the input() function, it returns the string as expected.
- The problem appears only in Windows. In Linux works as expected.
- An obervation, by typing this:
`app.exe A B C`
I get this:
```
['?\u2e70?e????\x02', 'A8Ä8???', 'B8Ä8???\u0e00.8Ä8???\u0e00C8Ä8?????8?8?8?8',
C8Ä8?????8?8?8?8']
```
You can notice that the **first** character of the string is right:
**A** 8Ä8???
**B** 8Ä8???\u0e00.8Ä8???\u0e00C8Ä8?????8?8?8?8
**C** 8Ä8?????8?8?8?8

**Comment by scoder** [comment]
Thanks for the report. Could you provide the commands that you use for Cython and gcc to build the executable?

**Comment by a-costantino** [comment]
I am from another account.

This is my `main.pyx` file
```
import sys
print(sys.argv)
```
This is my `complile.bat` file:
```
cython main.pyx --embed -o main.c
python winFix.py main.c
set PYTHON_DIR=C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python38-32
set WORKING_DIR=%cd%
cd C:\MinGW\bin
gcc %WORKING_DIR%\main.c -I %PYTHON_DIR%\include -lpython38 -lm -L %PYTHON_DIR%\libs -o %WORKING_DIR%\app.exe
cd %WORKING_DIR%
```
And this is my `winFix.py` file:
```
import sys
print('Fixing: '+sys.argv[1])
with open(sys.argv[1],'r')as file :
	filedata=file.read()
filedata=filedata.replace('int wmain(', 'int main(')
with open(sys.argv[1],'w')as file:
	file.write(filedata)
```

**Comment by TeamSpen210** [comment]
Why are you patching the `.c` file like that? Cython uses `wmain` for a reason, it's a Windows-specific alternate entry point which is given a UTF-16 `argv`. That way it can properly handle non-ASCII characters. But if you switch it to `main`, Cython's code is going to try to access the 1-byte array as a 2-byte array. So it's reading the `A\x00` bytes as one character, then trampling into unset memory until it happens to hit `\x00\x00`.

**Comment by a-costantino** [comment]
Because otherwise i get this error: **undefined reference to `WinMain@16'**
Everything except argv works perfectly.

**Comment by da-woods** [comment]
From a quick google search (https://stackoverflow.com/questions/24219012/building-standalone-application-with-cython-mingw, https://stackoverflow.com/questions/34936859/creating-an-executable-from-cython-code), I think you need to pass `-municode` to gcc?

I'm pretty sure this is a problem that's caused by your workaround, rather than a problem with Cython.
