### ISSUE TITLE
ValueError: More than one filename match found for utility code Capsule

### ISSUE THREAD

**Issue by antoineChammas** [cython/cython#3842]
**Describe the bug**
I am trying to compile my python code into cython and am getting this error, I'm on Windows.

**To Reproduce**
Code to reproduce the behaviour:
from distutils.core import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext

ext_modules = [
    Extension("test",  ["test.py"]),
]

setup(
    name = 'test',
    cmdclass = {'build_ext': build_ext},
    ext_modules = ext_modules
)

python compile.py build_ext --inplace  

**Expected behavior**
I expected my code to be compiled

**Environment (please complete the following information):**
 - OS: Windows
 - Python version 3.6.5
 - Cython version 0.29.21

**Additional context**

**Comment by da-woods** [comment]
Does this happen on every file or does it depend on the contents of test.py? If it depends on the contents of test.py then this should be included in your example.

**Comment by antoineChammas** [comment]
It happens on every file, I've even tried practically empty ones (containing mostly comments and no imports) and it still gave that error.

**Comment by da-woods** [comment]
That seems odd - Cython is tested under Windows and is known to work. I'd think the most likely reason is that your install is somehow faulty. I'd try removing it completely (and manually checking that all the files are gone) and reinstalling it.

I really don't know though

**Comment by antoineChammas** [comment]
I already did that and the error is still there.. I am currently downloading it through pip, should I try using conda or download an earlier version of Cython?

**Comment by da-woods** [comment]
My uninformed guess is that you already have multiple versions installed and that this is what's causing your problems. So I would not add more versions into that mix. If you have conda it might be worth trying _in a completely fresh_ conda environment.

It'd also be useful to have the full traceback here rather than just the exception. It isn't obvious where that exception could even come from.

I really don't have much idea though so may not be able to help.

**Comment by antoineChammas** [comment]
It worked after downloading it with conda, thanks
