### ISSUE TITLE
[BUG] compiler crash when mixing class and function pointer

### ISSUE THREAD

**Issue by Mike-HubGit** [cython/cython#3843]
**Describe the bug**
The Cython compiler crashes when I try to compile the following
**To Reproduce**
Code to reproduce the behaviour:
```cython
%%cython --annotate
#cython: language_level=3,boundscheck = False

import cython

cimport numpy as np
import numpy as np
ctypedef  void (*func_ptr)(const double[::1] Y,const double t,double[::1] out_dY)

cdef void dY_lowPass(const double[::1] Y,const double t,\
                         double[::1] out_dY):
    out_dY[0]=-Y[0]/1e-3
    
    
cdef func_ptr thePtr = dY_lowPass

cdef class functor:
    cdef func_ptr myFunc

    cdef setFunc(self,func_ptr inFunc):
        self.myFunc = inFunc
        
    cdef runFunc(self,const double[::1] Y,const double t,\
                         double[::1] out_dY):
        self.myFunc(Y,t,out_dY)
        
    
cdef a = functor()
a.setFunc(dY_lowPass)
```

**Expected behavior**
should allow me to change the class internal pointer to the given one.

**Environment (please complete the following information):**
 - OS: macOS
 - Python version 3.7.9
 - Cython version  0.29.21

**Additional context**

**Comment by da-woods** [comment]
The compiler crash is a bug. [The advice I gave you on the mailing list was to do](https://groups.google.com/d/msg/cython-users/nkThnvdzjcs/Z6MroCJyBwAJ)

```
cdef functor a = functor()
a.setFunc(dY_lowPass)
```

`cdef a` on it's own just sets `a` to be a generic Python object. To use the `cdef` function `setFunc` `a` needs to be typed as a `functor`.

**Comment by Mike-HubGit** [comment]
Yes but even with the cdef (as shown in the code I posted) the compiler crashes.

**Comment by da-woods** [comment]
Yes but what you posted is not what I suggested:

`cdef a = functor()`    -> `cdef functor a = functor()`

**Comment by Mike-HubGit** [comment]
You're right ! I only focused on the "cdef". Now that works, thanks a lot !
