### ISSUE TITLE
cython 0.29.xx broken for python 3.9rc2

### ISSUE THREAD

**Issue by ThomasWaldmann** [cython/cython#3855]
**Describe the bug**
The previously deprecated tp_print is now finally gone.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.9rc2
 - Cython version 0.29.21

```
  src/llfuse.c:50290:36: error: ‘PyTypeObject {aka struct _typeobject}’ has no member named ‘tp_print’
    __pyx_type_6llfuse_VoidPtrCapsule.tp_print = 0;
```

E.g. there: https://travis-ci.org/github/borgbackup/borg/jobs/731883687

**Comment by da-woods** [comment]
My impression is that this should have been fixed in https://github.com/cython/cython/commit/aa56a6b108de18138dfcf8722610327024b11dd9. Although I could be wrong

**Comment by da-woods** [comment]
It looks to me like llfuse includes a pre-cythonized llfuse.c (presumably made with an earlier version of Cython before this change was made) and by default uses this file rather than rebuilds it.

**Comment by ThomasWaldmann** [comment]
Oh crap, there is a llfuse.c from 2019 in the pypi src package. :-(

**Comment by da-woods** [comment]
I'll close this as being a 3rd party problem. If you decide otherwise as you investigate it then I can re-open this, but I'm pretty sure it's fixed in Cython.

**Comment by ThomasWaldmann** [comment]
Yeah, looks like it is a llfuse issue (and llfuse is not maintained any more).
