### ISSUE TITLE
[BUG] increment value inserted into map

### ISSUE THREAD

**Issue by twoertwein** [cython/cython#3861]
**Describe the bug**
I'm new to cython - might be a user error and not a cython bug.

I want to insert a key-value pair into the C++ `unordered_map`. If the key already exists, I want to increment the value. `insert` should return an iterator that should allow to modify the value. It seems that this doesn't work.

**To Reproduce**
Code to reproduce the behaviour:
```cython
# cython: language_level=3, infer_types=True
# distutils: language = c++

from libcpp.unordered_map cimport unordered_map
from libcpp.pair cimport pair as cpair

cimport cython
from cython.operator cimport dereference, postincrement


def insert_or_increment():
    cdef unordered_map[double, cython.int] mapping
    cdef cython.double key = 0.0

    # insert key
    mapping.insert(cpair[double, int](key, 0))

    # try to insert it a second time, should return a pointer to the existing key-value pair
    pair_iterator_inserted = mapping.insert(cpair[double, int](key, 1))
    iterator = dereference(pair_iterator_inserted.first)
    print(iterator.second, mapping[key])   # 0, 0
    if not pair_iterator_inserted.second:
        # key already exists: increment it
        postincrement(iterator.second)
    print(iterator.second, mapping[key])  # 1, 0

```

**Expected behavior**
`postincrement(iterator.second)` should change the value inside the map.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04.1
 - Python version 3.8.6
 - Cython version 0.29.21

**Comment by da-woods** [comment]
`iterator = dereference(pair_iterator_inserted.first)` - this is not an iterator. What you call `iterator` is actually a pair - a copy of what's in the iterator.

You'd probably be better asking this sort of question on the cython-users mailing list.
