### ISSUE TITLE
Cython Question: How to efficiently create arrays of variable sizes in cython for loop.

### ISSUE THREAD

**Issue by ThamuMnyulwa** [cython/cython#3866]
Say one has an array of variable sizes that stores values from a nested for-loop. How can one perform such an operation in Cython efficiently? All the Cython sources I seem to come across do not create arrays of varying dimensions. My inefficient approach that uses more NumPy is placed below using inline Jupyter notebook. How can I optimize this further using Cython?

```
import cython
# Load cython extension
%load_ext Cython
```

```
%%cython
import numpy as np

def my_function(list my_list, int n, int a ):
    cdef list Estimate_1_list = []
    cdef list Estimate_2_list = []
    cdef int l,i,t,j
    for l in my_list:

        # Resizable matrices (could I use memory view?)
        a_mat = np.zeros((l,n+1),float)
        b_mat = np.zeros((l,n+1),float)

        for i  in range(n):
            t = i*a

            for j in range(l):

                # Fill matrices
                a_mat[j,i+1] = a_mat[j,i+1] + np.random.random()

                b_mat[j,i+1] = a_mat[j,i+1]/(2*t+3)

        # Append values of interest to use at different values of matrix size
        Estimate_1_list.append(np.mean(a_mat[:,n]))
        Estimate_2_list.append(np.std(a_mat[:,n]))  
        
    # Return results 
    results = [Estimate_1_list,Estimate_2_list]
    return results
```
```

# Test
my_function([1,2,3], 10, 0.5 )
```

**Comment by scoder** [comment]
This looks more like a support request to me than a bug or feature request. Those are best directed to the cython-users mailing list.
When you ask there, please try to be clearer about what you want, e.g. by providing an example of something that you tried but that does not currently work (and provide the error that you get when you try it).

**Comment by ThamuMnyulwa** [comment]
Ok, thanks @scoder . I will post this onto the mailing list.
