### ISSUE TITLE
[ENH] CPython 3.9 manylinux wheels

### ISSUE THREAD

**Issue by hroncok** [cython/cython#3868]
Hello! Could you please release CPython 3.9 manylinux wheels on PyPI?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. In my code, I would like to do [...]
```console
$ python3.9 -m pip install cython
```

I'd like this to be super fast.

**Describe the solution you'd like**
A clear and concise description of what you want to happen, including code examples if applicable.

I'd like pip to install Cython wheels with Python 3.9.

**Describe alternatives you've considered**

It is possible to install Cython with `--install-option="--no-cython-compile"`, but that doesn't work in situations where Cython is a dependency.

**Additional context**
Add any other context about the feature request here.

Python 3.9.0 final was released this week: https://www.python.org/downloads/release/python-390/

Thank You.

**Comment by KipCrossing** [comment]
This would great to have

**Comment by scoder** [comment]
Uploaded for 0.29.21. I'll also add them for the next 3.0 release.

**Comment by hroncok** [comment]
Thanks!
