### ISSUE TITLE
Issue with Cython and requirements.txt in installing new library

### ISSUE THREAD

**Issue by mattobny** [cython/cython#3871]
Environment 
 - OS: Windows
 - Python version 3.6.7-1~18.04 (When using bash within Finder)
 - Python version 3.8.2 (When using VSCode) [I am unsure of why there is a difference...]
 - Cython version 0.29.21

Hello, I am trying to install the library pegasuspy (https://pegasus.readthedocs.io/en/stable/installation.html) using pip3. When I run 
`pip3 install pegasuspy`, I get the following error:

`Collecting pegasusio (from pegasuspy==1.0.1.dev5+ged4f175)
  Using cached https://files.pythonhosted.org/packages/2f/18/250ab9e615c05172e5ffaa59fc4f77ad0023dbcaab74ab591c55612cba4a/pegasusio-0.2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Compiling ext_modules/io_funcs.pyx because it depends on /home/mattobrien/.local/lib/python3.6/site-packages/Cython/Includes/libc/math.pxd.
    [1/1] Cythonizing ext_modules/io_funcs.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-74tvpwzn/pegasusio/setup.py", line 48, in <module>
        l.strip() for l in Path("requirements.txt").read_text("utf-8").splitlines()
      File "/usr/lib/python3.6/pathlib.py", line 1196, in read_text
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
      File "/usr/lib/python3.6/pathlib.py", line 1183, in open
        opener=self._opener)
      File "/usr/lib/python3.6/pathlib.py", line 1037, in _opener
        return self._accessor.open(self, flags, mode)
      File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
        return strfunc(str(pathobj), *args)
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-74tvpwzn/pegasusio/`

I do not know how to proceed here, I've tried navigating to my root folder and using:
`find . -regex '.*requirements.txt$'` to find the document, but I get this as a result:
`./.vscode/extensions/ms-python.python-2020.9.114305/requirements.txt
./anaconda3/pkgs/conda-4.8.2-py37_0/info/test/tests/conda_env/support/advanced-pip/another-project-requirements.txt
./anaconda3/pkgs/conda-4.8.2-py37_0/info/test/tests/conda_env/support/requirements.txt
./anaconda3/pkgs/hdf5-1.10.4-h7ebc959_0/info/recipe/yum_requirements.txt
./anaconda3/pkgs/matplotlib-3.1.3-py37_0/info/recipe/parent/yum_requirements.txt
./anaconda3/pkgs/matplotlib-base-3.1.3-py37h64f37c6_0/info/recipe/yum_requirements.txt
./anaconda3/pkgs/networkx-2.4-py_0/share/doc/networkx-2.4/requirements.txt
./anaconda3/pkgs/pyqt-5.9.2-py37h6538335_2/info/recipe/yum_requirements.txt
./anaconda3/pkgs/python-3.7.6-h60c2a47_2/info/recipe/yum_requirements.txt
./anaconda3/pkgs/qt-5.9.7-vc14h73c81de_0/info/recipe/yum_requirements.txt
./anaconda3/pkgs/qtawesome-0.6.1-py_0/info/recipe/yum_requirements.txt
./anaconda3/pkgs/qtconsole-4.6.0-py_1/info/recipe/yum_requirements.txt
./anaconda3/pkgs/qtpy-1.9.0-py_0/info/recipe/yum_requirements.txt
./anaconda3/pkgs/scipy-1.4.1-py37h9439919_0/info/recipe/yum_requirements.txt
./anaconda3/share/doc/networkx-2.4/requirements.txt
find: ‘./AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs’: Permission denied
find: ‘./AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/temp/{46f1875d-9f74-4aaa-ac16-f73cb63a38c4}’: Permission denied
find: ‘./AppData/Local/Packages/Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe/SystemAppData/Helium/Cache’: Permission denied
find: ‘./AppData/Local/Packages/Microsoft.Office.Desktop_8wekyb3d8bbwe/SystemAppData/Helium/Cache’: Permission denied
./Documents/Research/compGenW/pegasus/docs/requirements.txt
./Documents/Research/compGenW/pegasus/requirements.txt`
 
I know this is messy, and I'd appreciate any suggestions on how to clean up and/or optimize all of this. Thank you!

**Comment by da-woods** [comment]
To me this looks like this has got past the Cython stage of running setup.py and is hitting problems a few lines later: https://github.com/klarman-cell-observatory/pegasusio/blob/654b8438a0804cddf3356ddbdc114620a12339ee/setup.py#L47-L49.

For some reason it's not finding or doesn't have the requirements.txt file that should be bundled with pegasusio.

Closing because I'm pretty convinced it's not a problem with Cython. I suggest asking on Pegasusio's support channel.
