### ISSUE TITLE
[BUG] Parsing issue with nested templates and const 

### ISSUE THREAD

**Issue by brandon-b-miller** [cython/cython#3885]
**Describe the bug**
Certain situations where nested template types are declared seem not to parse/compile correctly. This is best illustrated through the repro. 

**To Reproduce**
Code to reproduce the behaviour:

This compiles and works:

```cython

# distutils: language = c++

from libcpp.vector cimport vector

cdef void func():
    cdef vector[vector[int]] a_vector

```

This also compiles and works:
```cython
# distutils: language = c++

from libcpp.vector cimport vector

cdef void func():
    cdef vector[const int] a_vector
```

But _this_ doesn't work and gives me a syntax error:

```cython
# distutils: language = c++

from libcpp.vector cimport vector

cdef void func():
    cdef vector[vector[const int]] a_vector
```

```
Error compiling Cython file:
------------------------------------------------------------
...
# distutils: language = c++

from libcpp.vector cimport vector

cdef void func():
    cdef vector[vector[const int]] a_vector
                            ^
------------------------------------------------------------

example.pyx:6:29: Expected ']', found 'int'
```

**Expected behavior**
This should compile to a function that works with the signature something like:

```
void func() {
    std::vector<std::vector<const int>> a_vector;
}
```

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.7.8
 - Cython version: 0.29.21

**Additional context**
N/A

**Comment by scoder** [comment]
The obvious work-around is a `ctypedef`, but this might be easy to fix. Could just be a difference in `Parsing.py` when it hits a nested type versus a top-level type. PR welcome.

**Comment by scoder** [comment]
This has already been reported in #1355.
