### ISSUE TITLE
Template cppclass can't assign values 

### ISSUE THREAD

**Issue by TNonet** [cython/cython#3890]
Hi Everyone,

I am trying to expose a C++ templated class, which I believe should be supported by Cython. However, I am having some difficulties. I believe I have followed the documentation found at [Cython Docs](https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html#templates) and read most of the StackOverflow posts on this subject (There aren't many). However, templating even the simplest class seems to fail.

 ### MWE
Can also be found at (https://github.com/TNonet/CythonTemplateBug)

 File Structure
├─ cy_test.pxd
├─ cy_test.pyx
├─ test.cpp
├─ test.h
├─ setup.py

====== cy_test.pxd =======
```cython
cimport cython

cdef extern from "test.h":

    cdef cppclass TestClass[T]:
        TestClass()
        TestClass(T ptr)
        T ptr;
```

====== cy_test.pyx =======
```cython
from cy_test cimport TestClass

cdef build_TestClass(x):
    cdef double[:] x_memview = x

    cdef TestClass arr_item = TestClass(x_memview[0])
```

====== setup.py =========
```python
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize


examples_extension = Extension(
    name="test",
    sources=["cy_test.pyx", "test.cpp"],
    include_dirs=[],
    language="c++",
    extra_compile_args=["-std=c++11"],
    extra_link_args=["-std=c++11"]
)
setup(
    name="test",
    ext_modules=cythonize([examples_extension], language_level=3)
)

```

====== test.cpp ======
```c++
#include "test.h"
```

====== test.h ========
```c++
#ifndef test
#define test

template <class T1>
class TestClass{
    public:
        T1 ptr;

    TestClass(T1 ptr) {
        this->ptr = ptr;
    }

    TestClass() {}
    ~TestClass();
};

#endif
```

**To Reproduce**
```bash
>>>python setup.py build_ext --inplace
```
``` bash
Compiling cy_test.pyx because it changed.
[1/1] Cythonizing cy_test.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from cy_test cimport TestClass

cdef build_TestClass(x):
    cdef double[:] x_memview = x

    cdef TestClass arr_item = TestClass(x_memview[0])
                                                ^
------------------------------------------------------------

cy_test.pyx:6:49: Cannot assign type 'double' to 'T'
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    ext_modules=cythonize([examples_extension], language_level=3)
  File "/Users/_/opt/anaconda3/envs/py37/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/Users/_/opt/anaconda3/envs/py37/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cy_test.pyx
```

This error suggests that Cython is failing to recognize "T" as a templating type to be inferred and instead thinks of T as a type itself. To add support to this claim, when I replace "T" in cy_test.pxd  with "double" the code compiles.

As the class variable 'ptr' in "test.h" might suggest. I am actually trying to assign pointers, but the issue seems to exist regardless.

Environment: 
 - OS: macOS
 - Python version: 3.7.7
 - Cython version: 0.29.21

**Comment by da-woods** [comment]
Hi - support questions are better directed to the Cython-users list.

I think in this case you need to tell Cython which version of the type you're trying to define

```
cdef TestClass[double] arr_item ...
```

**Comment by TNonet** [comment]
Hi @da-woods,

I apologize for making this seem like a support question. What I really want to accomplish as a result of this Issue is: either

- to personally update the Cython documentation to more explicitly state how (if) Cython can wrap C++ template classes. I have modest experience with C++ and Python so I think it would be a great learning opportunity and provide value for future Cython uses.
- (and/or) to highlight a bug in the Cython C++ class templating functionality.

Responding to your other point, when I implement your changes to cy_test.pyx


====== cy_test.pyx =======
```cython
# distutils: language = c++
# distutils: sources = test.cpp

from cy_test cimport TestClass

cdef build_TestClass(x):
    cdef double[:] x_memview = x

    cdef TestClass[double] arr_item = TestClass(x_memview[0])

```



The compilation still fails in a very similar fashion:
```bash

Compiling cy_test.pyx because it changed.
[1/1] Cythonizing cy_test.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from cy_test cimport TestClass

cdef build_TestClass(x):
    cdef double[:] x_memview = x

    cdef TestClass[double] arr_item = TestClass(x_memview[0])
                                                        ^
------------------------------------------------------------

cy_test.pyx:9:57: Cannot assign type 'double' to 'T'

Error compiling Cython file:
------------------------------------------------------------
...
from cy_test cimport TestClass

cdef build_TestClass(x):
    cdef double[:] x_memview = x

    cdef TestClass[double] arr_item = TestClass(x_memview[0])
                                              ^
------------------------------------------------------------

cy_test.pyx:9:47: Cannot assign type 'TestClass[T]' to 'TestClass[double]'
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    ext_modules=cythonize([test_extension], language_level=3)
  File "/Users/_/opt/anaconda3/envs/py37/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/Users/_/opt/anaconda3/envs/py37/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cy_test.pyx
```

**Comment by da-woods** [comment]
Improvements to the documentation are always welcome of course. Your basic issue is that `TestClass` on its own isn't something you can create an instance of - it has to be `TestClass[int]` or `TestClass[double]`. You need to change it in both places in your usage (I should probably have made that clearer in my initial reply):

```
cdef TestClass[double] arr_item = TestClass[double](x_memview[0])
```

I think this behaviour matches what C++ does - it won't figure out what template specialization to use based on arguments to a class constructor. Therefore I don't think it's a Cython bug. The error message could definitely be clearer though.

The example in the documentation looks to show this usage correctly:

```
cdef vector[int] *v = new vector[int]()
```

but if you have suggestions for how to make it clearer then please do make them!

**Comment by TNonet** [comment]
Hi @da-woods,

I appreciate the extremely prompt response. That change seems to have fixed the issue. Now that I am aware of this difference, it seems obvious.

I think directly stating this difference between C++ and Cython template type inference in the documentation would have been enough (hopefully) to prevent this oversight on my part. Therefore, I was thinking of either:

-  adding a quick mention  about this in the documentation 
- (or) placing this example (or something similar) in the templating section as an example a bit easier to parse than the C++ standard vector.

If either of these options sound reasonable, which branch would the PR go towards?

**Comment by da-woods** [comment]
I'd think a quick mention would be better than changing the example - the nice thing about using `std::vector` is that you don't have to show any C++ files as part of the example and vector is hopefully familiar to most people.

If you want to make a PR then it should go towards master.
