### ISSUE TITLE
[BUG] Dict subclasses can not be passed to functions that expect dict

### ISSUE THREAD

**Issue by velovix** [cython/cython#3903]
**Describe the bug**
If I define a pure Python function and type hint its argument using `dict`, I am no longer able to pass subclasses of `dict` to that function. If I turn off annotation_typing, the problem unsurprisingly goes away.

**To Reproduce**
Code to reproduce the behaviour:
```python
class MyDict(dict):
    pass


def print_dict(d: dict):
    for key, val in d.items():
        print(f"{key}: {val}")


def demonstrate():
    print_dict(MyDict())
```

If you Cythonize and compile the above code, then run `demonstrate`, a `TypeError` occurs:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "demonstrate_bug.py", line 11, in demonstrate_bug.demonstrate
    print_dict(MyDict())
TypeError: Argument 'd' has incorrect type (expected dict, got MyDict)
```

**Expected behavior**
I would have expected to be able to pass a value of type `MyDict` to `print_dict`, since it's a subclass of the expected type.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.8.5
 - Cython version: 3.0a6

**Additional context**
I found this bug when using the standard library's `collections.Counter` class.

**Comment by scoder** [comment]
Works as documented: https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#types
