### ISSUE TITLE
[BUG] python file use exec to define a function , use eval to call the function ,it works,but convert to pyd return function is not defined

### ISSUE THREAD

**Issue by 945226956** [cython/cython#3912]
**Describe the bug**
in the python file my code :

`def testpdyexe():
    f_str='''def  testxxx(x,y):
        print(x,y)
    '''
    exec(f_str)
    p={'x':1,'y':2}
    return eval('testxxx')(**p)
testpdyexe()`

it works return 1,2.but when I convert the python file to pyd file. it return error：
---------------------------------------------------------------------------
NameError                                 
Traceback (most recent call last)
<ipython-input-4-09e2de819d47> in <module>
NameError: name 'testxxx' is not defined

how can I sovle the problem?

**Comment by da-woods** [comment]
That's because you are modifying `locals` by adding `testxxx` to it. Read the [documentation for `exec`](https://docs.python.org/3/library/functions.html#exec) including the notes telling you not to do this.

If it seems to work on uncompiled Python it's pure luck.

**Comment by 945226956** [comment]
def testpdyexe():
    f_str='''def testxxx(x,y):
        print(x,y)
        return 1+1,str(111)
    '''
    p={'x':1,'y':2}

    from types import FunctionType

    foo_code = compile(f_str, "<string>", "exec")
    foo_func = FunctionType(foo_code.co_consts[0], globals(), "foo")
    return foo_func(**p)
it works
