### ISSUE TITLE
Move away from travis-ci

### ISSUE THREAD

**Issue by scoder** [cython/cython#3913]
Sadly, the current situation with travis-ci has become unbearable. Investigate Linux/macOS (and Windows) options on
- circle-ci
- azure
- potentially also Github Actions, but that seems more work for less benefit currently (no Windows support, very different setup).

We currently use [multibuild](https://github.com/matthew-brett/multibuild/) in the [cython-wheels](https://github.com/MacPython/cython-wheels) project, but should also consider [cibuildwheel](https://pypi.org/project/cibuildwheel/).

**Comment by AleksaC** [comment]
Hi, I should be able to help with this. Also I wouldn't rule out Github Actions. They actually have Windows support and their setup isn't all that different from other providers.

**Comment by davfsa** [comment]
If needed, I could help set up Github Actions as it is currently quite fresh after having to move one of our projects out of travis :sweat_smile:. Also, compared to other providers, its free for open source (the 2,000 minutes is only for private projects) and its quite fast after the first run

**Comment by mattip** [comment]
cibuildwheel is a nice option. matplotlib has [moved to using it](https://github.com/matplotlib/matplotlib/blob/master/.github/workflows/cibuildwheel.yml). One nice thing about the wheel building model in cibuildwheel is that the different python jobs can be run consecutively in the same build step, one after another. 

With github actions, admins can trigger the build action from the "Actions" tab on the repo without leaving github.

For arm64, one option is [shippable](https://www.shippable.com/pricing.html) which is what NumPy uses for testing. The machines are less powerful than the travis graviton machines: the builds are about 2x longer than on x86.
