### ISSUE TITLE
Create Stub File for Type Annotation

### ISSUE THREAD

**Issue by diegostammer** [cython/cython#3915]
Using VSCode with pylance plugin in strict mode generate a lot of errors about missing type annotation.
The request is to create a stub file (*.pyi) to document every type of constants, methods, functions, etc.

https://www.python.org/dev/peps/pep-0484/
https://www.python.org/dev/peps/pep-0561/

**Comment by da-woods** [comment]
Related: https://github.com/cython/cython/pull/3818 and https://github.com/cython/cython/issues/3150

**Comment by da-woods** [comment]
So there is one for Shadow.py (which is what you end up importing in when using pure Python mode) https://github.com/cython/cython/blob/master/Cython/Shadow.pyi.

I'm closing this because it isn't clear what you're actually missing here.

**Comment by TeamSpen210** [comment]
PEP 561 introduced the [requirement](https://www.python.org/dev/peps/pep-0561/#id18) that packages providing type hints should include an empty marker `py.typed` file in the package folder, so type checkers know type hints are intentionally present. That might be what's required.

**Comment by alexreg** [comment]
Could we reopen this please? This approach seems to be favoured by the pylance team. See [this comment](https://github.com/microsoft/pylance-release/issues/674#issuecomment-1104545520) by @erictraut.

> I think the right answer here is for Cython toolchain to add support for generating stub files with docstrings. Those stubs can then be distributed along with the library. Any other approach I can think of (including scraping based on runtime reflection) will produce results that leave significant gaps in terms of completeness and correctness. The maintainers of Cython are in a much better place to do this work than the Pylance team. We are happy to work with the Cython community in an advisory manner.

**Comment by TeamSpen210** [comment]
This issue isn't exactly the same thing. This is discussing adding a type stub for `cython` itself, for use when writing pure-Python modules that are then compiled. Having Cython autogenerate stubs for compiled modules is something different, you'd want a new issue.

**Comment by alexreg** [comment]
@TeamSpen210 Ah, I misread, Will do, thanks.
