### ISSUE TITLE
[BUG] __Pyx_PyObject_CallOneArg() doesn't support Python 3.9 METH_METHOD flags

### ISSUE THREAD

**Issue by vstinner** [cython/cython#3917]
The PEP 573 was accepted and implemented in Python 3.9. It adds a new METH_METHOD flag which pass the "defining class".

For example, the zlib.Decompress.decompress() function gets this flag by using the new ``defining_class`` parameter type in its Argument Clinic definition in Python 3.10:

```
/*[clinic input]
zlib.Decompress.decompress

    cls: defining_class
    data: Py_buffer
        The binary data to decompress.
    /
    max_length: Py_ssize_t = 0
        The maximum allowable length of the decompressed data.
        Unconsumed input data will be stored in
        the unconsumed_tail attribute.

(...)
[clinic start generated code]*/
```

It generates the following calling convention:

```

#define ZLIB_DECOMPRESS_DECOMPRESS_METHODDEF    \
    {"decompress", (PyCFunction)(void(*)(void))zlib_Decompress_decompress, METH_METHOD|METH_FASTCALL|METH_KEYWORDS, zlib_Decompress_decompress__doc__},

static PyObject *
zlib_Decompress_decompress(compobject *self, PyTypeObject *cls, PyObject *const *args, Py_ssize_t nargs, PyObject *kwnames)
{
    (...)
}
```

Notice the second parameter: `PyTypeObject *cls`.

It seems like __Pyx_PyObject_CallOneArg() doesn't support this new calling convention and simply treat the function as the "fastcall" calling convention. It does not pass the defining type.

As a consequence, zlib_Decompress_decompress() does crash when parsing its arguments.

See https://bugzilla.redhat.com/show_bug.cgi?id=1898157 for a concrete example in scipy.

I tested Cython 0.29.21 (python3-Cython-0.29.21-4.1.fc34.x86_64) on Fedora Rawhide with Python 3.10.

**Comment by vstinner** [comment]
> The PEP 573 was accepted and implemented in Python 3.9.

FYI it was implemented in https://bugs.python.org/issue38787

cc @encukou

**Comment by hroncok** [comment]
> I tested Cython 0.29.21 (python3-Cython-0.29.21-4.1.fc34.x86_64) on Fedora Rawhide with Python 3.10.

Note that our Cython is patched with https://github.com/cython/cython/pull/3877 -- that should not make a difference.

**Comment by scoder** [comment]
I think the best fix for 0.29.x is to switch to using `PyCFunction_CheckExact()` here.

**Comment by scoder** [comment]
Ah, it's actually *only* an issue in Cython 0.29.x. Cython 3 has a different implementation alltogether here.

**Comment by vstinner** [comment]
Fedora is still using the Cython 0.29 branch.

**Comment by scoder** [comment]
6ba0345d98ee9ed0fcdc662be4fc81a7754d5080 should fix it.

**Comment by hroncok** [comment]
Testing it.

**Comment by vstinner** [comment]
> 6ba0345 should fix it.

Oh wow, that was quick, thanks @scoder!

**Comment by hroncok** [comment]
> Testing it.

It works.
