### ISSUE TITLE
[BUG] Missing return in __Pyx_UnicodeContainsUCS4 with PEP393

### ISSUE THREAD

**Issue by jmd-dk** [cython/cython#3925]
**Describe the bug**
In `Cython/Utility/StringTools.c`, the function `__Pyx_UnicodeContainsUCS4()` is missing a return value in the case of `CYTHON_PEP393_ENABLED` (Python 3.9) and `kind == PyUnicode_WCHAR_KIND`.

When compiling the C code, i get the warning

> myfile.c: In function ‘__Pyx_UnicodeContainsUCS4’:
myfile.c:104840:1: warning: control reaches end of non-void function [-Wreturn-type]
104840 | }
       | ^

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.9.0
 - Cython version: 0.29.21 (but also master)

**Fix**
Below is the [current](https://github.com/cython/cython/blob/master/Cython/Utility/StringTools.c) function with a single line added, constituting a fix. I suppose returning `1` is the correct thing to do in this seemingly overlooked case.
```C
static CYTHON_INLINE int __Pyx_UnicodeContainsUCS4(PyObject* unicode, Py_UCS4 character) {
#if CYTHON_PEP393_ENABLED
    const int kind = PyUnicode_KIND(unicode);
    if (likely(kind != PyUnicode_WCHAR_KIND)) {
        Py_ssize_t i;
        const void* udata = PyUnicode_DATA(unicode);
        const Py_ssize_t length = PyUnicode_GET_LENGTH(unicode);
        for (i=0; i < length; i++) {
            if (unlikely(character == PyUnicode_READ(kind, udata, i))) return 1;
        }
        return 0;
    }
    return 1;  // <-- NEW
#elif PY_VERSION_HEX >= 0x03090000
    #error Cannot use "UChar in Unicode" in Python 3.9 without PEP-393 unicode strings.
#endif
#if PY_VERSION_HEX < 0x03090000
#if Py_UNICODE_SIZE == 2
    if (unlikely(character > 65535)) {
        return __Pyx_PyUnicodeBufferContainsUCS4_SP(
            PyUnicode_AS_UNICODE(unicode),
            PyUnicode_GET_SIZE(unicode),
            character);
    } else
#endif
    {
        return __Pyx_PyUnicodeBufferContainsUCS4_BMP(
            PyUnicode_AS_UNICODE(unicode),
            PyUnicode_GET_SIZE(unicode),
            character);

    }
#endif
}
```

**Comment by da-woods** [comment]
I'd think it should be `return 0` (or possibly `return -1` + an error - I'm not sure right now what exceptions specification that has)  rather than `return 1` that you add.

I don't think "string is a confusing type" translates to "found the character"

**Comment by jmd-dk** [comment]
> I don't think "string is a confusing type" translates to "found the character"

Ah right, `1` is the "success" value. I meant `return 0` then, though a third value for error handling would of course be ideal.

**Comment by jmd-dk** [comment]
On further thought, the `return` should probably be placed as the very last line in `__Pyx_UnicodeContainsUCS4()`, outside all macros, as the problem is not exclusive to `#if CYTHON_PEP393_ENABLED`.

**Comment by robertwb** [comment]
Yes, it would be better to return an error in this case, possibly falling back to the code in the lower half of the function which will raise the right error, or, if this is not appropriate for Python 3.9, a call to the appropriate Python C API function.
