### ISSUE TITLE
Can cython change cpp compiler?

### ISSUE THREAD

**Issue by GoodManWEN** [cython/cython#3927]
Fresher to cython here ,when I was runing demo codes (the specific situation is that I was testing if cpp stl could run properly on cython) there gots some wrong answer. Since there seems no problem in code , I guess it may cause by I've installed both 32/64bit compiler and 64bit python in my os , and by defalut cython called 32bit compiler during compile. 

Is there any way I could swith to 64 bit gcc compiler? Didn't find instructions in documentation , needs help thanks.

Test codes here:
demo.pyx
```
# distutils: language=c++
import cython
from libcpp.vector cimport vector

def main():
    cdef vector[int] vect
    cdef int i
    cdef long s = 0
    for i in range(1000000):
        vect.push_back(i)
    for i in range(1000000):
        s += vect[i]
    return s
```

setup.py
```
from distutils.core import setup
from Cython.Build import cythonize

setup(
    ext_modules = cythonize(
        "demo.pyx",
    )
)
```

These codes got result 1783293664

**Comment by da-woods** [comment]
Please ask support questions on the Cython-users mailing list: https://groups.google.com/forum/m/#!forum/cython-users. In this case the choice of compiler is made by distutils. You won't be able to import a 32 bit module from 64 bit Python so I'd suggest the compiler isn't your problem.
