### ISSUE TITLE
[BUG] Multiple starred expressions in a list

### ISSUE THREAD

**Issue by theogal-pro** [cython/cython#3938]
Hi !
I think Cython is not able to compile when I unpack multiple expressions separated by commas, in one list.

**Describe the bug**
When I want to compile my python file containing a condition like 
```python
if arr['name'] not in [*foo.bar.keys(), *foo.bar2.keys()]:
```

I get two error messages
```
Error compiling Cython file:
------------------------------------------------------------

if arr['name'] not in [*foo.bar.keys(), *foo.bar2.keys()]:
                            ^
------------------------------------------------------------

src/package/foo/bar.py:964:83: starred expression is not allowed here

Error compiling Cython file:
------------------------------------------------------------

if arr['name'] not in [*foo.bar.keys(), *foo.bar2.keys()]:
                                             ^
------------------------------------------------------------

src/package/foo/bar.py:964:83: starred expression is not allowed here
````

I know it is a very particular method and I could do 
```python
if arr['name'] not in [*foo.bar.keys()] + [*foo.bar2.keys()]:
```
But maybe it's possible to add this feature to Cython ?

I found this [issue](https://github.com/cython/cython/issues/2939) which looks like my problem, but setting different language_level doesn't change anything.

**To Reproduce**
To reproduce behaviour, try to compile 
```python
if arr['name'] not in [*foo.bar.keys(), *foo.bar2.keys()]:
```

**Expected behavior**
Errors should appear

**Environment (please complete the following information):**
 - OS: Linux & Windows
 - Python version 3.7.9
 - All Cython versions tested, even master branch

**Additional context**

**Comment by scoder** [comment]
Probably an issue with the optimised `in` tests. If there is a starred expression in the `in` list, then it should not get optimised.

See the `FlattenInListTransform` in `Optimize.py`. 
Test should go into `tests/run/pep448_extended_unpacking.py`

**Comment by scoder** [comment]
Suitable for a backport to 0.29.x.

**Comment by Arvin6** [comment]
I'd like to give this a shot

**Comment by Arvin6** [comment]
Could not reproduce the issue when I test with
```
a = {1: 'a', 2: 'b'}
b = {3: 'c', 4: 'd'}
print(2 in [*a.keys(), *b.keys()])
-----
O/P: True
```

**Comment by da-woods** [comment]
Still looks broken to me - it doesn't look like you tried to compile it with Cython.

**Comment by Arvin6** [comment]
Sorry, my bad. Can replicate the issue. 
```
cython3 --embed -o test.c test.py
/usr/lib/python3/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/arvind/test.py
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
a = {1: 'a', 2: 'b'}
b = {3: 'c', 4: 'd'}
print(2 in [*a.keys()])
           ^
------------------------------------------------------------

test.py:3:12: starred expression is not allowed here

```

**Comment by Arvin6** [comment]
@da-woods @scoder The PR is ready.
