### ISSUE TITLE
windows 10 visual studio support 

### ISSUE THREAD

**Issue by josephfarahat** [cython/cython#3945]
Hello, I am currently using python 3.9 and visual studio 2019. I tried to run the following examples : https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html. My problem is that when the .c file is generated from cython I cant compile or test it on the visual studio where it always says that the Python.h does not exist. I tried to download it  yet all the libraries it includes are also not existing in the visual studio 2019. Any suggestions ?

**Comment by da-woods** [comment]
Please don't use the bug-tracker for support questions. You might try the Cython-users mailing list instead. When you ask it elsewhere you should add more detail about how exactly you're trying to compile it
