### ISSUE TITLE
[BUG] Missing attributes with multiple inheritance in pure Python

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#3948]
**Describe the bug**

In trying to create a Python class that subclasses an extension type and a pure Python class in pure Python, am running into issues with attributes missing from one of the base classes. Whichever base class is listed later in the subclass, appears to have its attributes missing. Not sure if I'm just missing something or if this is a bug.

**To Reproduce**

Code to reproduce the behaviour:

```cython
from cython import cclass, double


@cclass
class A:
    _x: double

    def __init__(self, x: double = 0, **kwargs):
        self._x = x

    @property
    def x(self):
        return self._x


class B:
    def __init__(self, y=2, **kwargs):
        self.y = y


class C(A, B):  # swapping the order to `B, A` results in `x` being missing
    def __init__(self, x=0, y=2):
        super().__init__(x=x, y=y)
        print((self.x, self.y))  # <--- AttributeError: 'C' object has no attribute 'y'


c = C(3, 4)
```

**Expected behavior**

Would like both attributes to remain visible/usable in the subclass `C`.

**Environment (please complete the following information):**
 - OS: macOS
 - Python version: 3.8.6
 - Cython version: 0.29.21

**Additional context**

NA

**Comment by da-woods** [comment]
This is definitely not a bug. Try it in Python!

1. The rules for inheriting extension types are somewhat fiddly, but generally`cdef` classes can only be the first class in the inheritance list (so `(B`, A)` shouldn't work).
2. `super` calls the _next_ constructor in the chain but nothing calls `B.__init__`. Generally you'd either call `super().__init__` in the base classes or call `B.__init__` directly from `C.__init__.`

**Comment by jakirkham** [comment]
Yep you’re right. Thanks for the direction. Adding `super` calls in the base classes fixes this issue 🙂
