### ISSUE TITLE
[BUG] Cython failed to build with new distutils

### ISSUE THREAD

**Issue by xkszltl** [cython/cython#3955]
**Describe the bug**

This is filed to https://github.com/pypa/distutils/issues/13 originally.
Re-filing in cython to bridge the conversation and look for help.
It's likely to be their bug, but seems they don't have enough expertise to fix, so maybe cython side can help or work around.

With distutils 50.0.3, we hit an LTO issue when building cython.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/5203025/92013795-d4cca680-ed80-11ea-82ee-2b0e8e8715d8.png">
```
    /usr/bin/gcc-8 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -I/usr/include/python3.6m -c /tmp/pip-req-build-ybinyobt/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-3.6/tmp/pip-req-build-ybinyobt/Cython/Plex/Scanners.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-3.6/tmp/pip-req-build-ybinyobt/Cython/Plex/Scanners.o -L/usr/lib -o build/lib.linux-x86_64-3.6/Cython/Plex/Scanners.cpython-36m-x86_64-linux-gnu.so
    lto1: fatal error: bytecode stream in file 'build/temp.linux-x86_64-3.6/tmp/pip-req-build-ybinyobt/Cython/Plex/Scanners.o' generated with LTO version 7.3 instead of the expected 6.2
    compilation terminated.
    lto-wrapper: fatal error: /usr/bin/x86_64-linux-gnu-gcc returned 1 exit status
    compilation terminated.
    /usr/bin/ld: error: lto-wrapper failed
    collect2: error: ld returned 1 exit status
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

**To Reproduce**

This is a dockerfile showing the behavior change and breakage of distutils.
```
FROM ubuntu:18.04
SHELL ["/bin/bash", "-c"]
RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y gcc{,-{7,8}} python3{,-pip} git
RUN gcc --version && gcc-7 --version && gcc-8 --version
RUN python3 --version
RUN python3 -m pip --version
RUN python3 -m pip install -Uv pip setuptools==50.0.3
RUN python3 -m pip --version
RUN set -e; \
    export CC=gcc-8 CXX=g++-8; \
    SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pip install -Uv git+https://github.com/cython/cython@0.29.21;
RUN set -e; \
    export CC=gcc-8 CXX=g++-8; \
    SETUPTOOLS_USE_DISTUTILS=local python3 -m pip install -Uv git+https://github.com/cython/cython@0.29.21;
```

Note the difference in `SETUPTOOLS_USE_DISTUTILS`. distutils is moving to local as default, and the second build is broken.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 (default gcc is 7.5, gcc-8 installed as well)
 - Python version: stock version (3.6)
 - Cython version: 0.29.21 (probably not version-specific)

**Comment by da-woods** [comment]
At the risk of stating the obvious, it looks like it's using the GCC 7 linker, but the GCC 8 compiler.

Unless you have evidence otherwise, I doubt this is specifically a Cython bug - Cython only really deals with generating the C files and leave the compilation up to setuptools or distutils. I'd suspect you see this error when compiling any C extension module.

If you just want to get Cython installed then you could try the `--no-cython-compile` command line argument - it'll run marginally slower but otherwise be exactly the same. You'll probably hit the same issue if you try to compile any cython-generated modules though.

**Comment by xkszltl** [comment]
That's my impression as well: `x86_64-linux-gnu-gcc` is wrongly used as linker instead of `gcc-8`.

**Comment by scoder** [comment]
Probably outdated. Please comment if this is still an issue.

**Comment by xkszltl** [comment]
It was a distutil bug for using the wrong linker:
- https://github.com/pypa/distutils/pull/53

**Comment by scoder** [comment]
Thanks for reporting back.
