### ISSUE TITLE
[Question] Is the license notice required by Cyton output?

### ISSUE THREAD

**Issue by MKdays** [cython/cython#3965]
https://github.com/cython/cython/pull/306

I want to clarify the above document.
Is there a license notice obligation for the *.pyd file obtained through Cython from my Python Project?

**Comment by TeamSpen210** [comment]
There isn't for the `*.c`/`*.cpp` file, and so neither is there for the `*.pyd` file.

**Comment by MKdays** [comment]
Okay. Then I understand that the license notice for Output is unnecessary.

**Comment by robertwb** [comment]
Correct. (Note that there may be licensing restrictions on the input pyx files that would, of course, carry over to derived outputs, but the use of the Cython compiler does not encumber the outputs with additional restrictions.)
