### ISSUE TITLE
How cython memoryview accept input of various dimensions

### ISSUE THREAD

**Issue by QINQINKONG** [cython/cython#3970]
Hi everyone. I'm using cython to speed up my code, and use memoryview to let functions defined in cython accept array input. Eventually, I would like my function to be able to accept 3-D, 2-D, 1-D and even scalar input. However, it seems that I have to specify the dimension when I typed the memoryview of the arguments. Then how can I enable both 3-D, 2-D and 1-D input? One way I can imagine is define several functions doing the same thing but accepting input of different dimensions, and then write another caller function with a check of the input dimension to call specific processing function. But, is there any other more elegant way of doing this?

Thanks!

**Comment by da-woods** [comment]
Please ask support questions on the [Cython-users mailing list](https://groups.google.com/forum/#!forum/cython-users), not the bug tracker.

The purpose of memoryviews is pretty much to enable fast indexing, so a memoryview with an unknown number of indexes isn't really a meaningful concept.
