### ISSUE TITLE
[ENH] Fixed arrays that support tuples

### ISSUE THREAD

**Issue by mrakgr** [cython/cython#3991]
Cython's current [array](https://cython.readthedocs.io/en/latest/src/tutorial/array.html) offerings are too sparse at the moment.

```
open arraym
inl main() =
    inl x : array (i32 * i32) = arraym.create 10 
    arraym.set x 0 (1,2)
```
```
cdef class Tuple0:
    cdef readonly signed long v0
    cdef readonly signed long v1
    def __init__(self, signed long v0, signed long v1): self.v0 = v0; self.v1 = v1
cpdef void main():
    cdef list v0
    v0 = [None] * 10
    v0[0] = Tuple0(1, 2)
```

The way I am currently compiling Spiral arrays to Python lists is the least efficient possible way that I can imagine of doing it.

At a later point, I could compile primitive types to Python's efficient [array](https://docs.python.org/3/library/array.html)s. But those don't work for objects, and will not work for [tuples](https://github.com/cython/cython/issues/3985). Cython would be better as a compilation target if it had a clean way of compiling arrays.

For Spiral, I'd put this as being of roughly equal importance to discriminated stack unions, but I'd guess the array feature would be easier to implement.

**Comment by da-woods** [comment]
A couple of thoughts:

1. Numpy arrays do support `dtype=object` and I think you can then view them with an `object[:]` Cython memoryview.
2. When you think about how you'd implemented such an array in Cython, it ends up looking remarkably like a Python list or a tuple. Provided that you tell Cython that `v0` is a `list` then indexing it is really quite efficient and the custom type would probably struggle to do better.

**Comment by mrakgr** [comment]
> Provided that you tell Cython that v0 is a list then indexing it is really quite efficient and the custom type would probably struggle to do better.

It is good to know that indexing into them is efficient, but `list` can only hold heap allocated `object`s. Any tuples stored into them would have to be heap allocated. Typed heterogenous arrays would allow for arbitrarily sized elements rather than the 8 bytes it would take to store a object.

Memory views are close to this, but I've only seen them derived from `array` types which are limited in their selection. Numpy arrays would likely have the same problem of not having tuples.

> [None] * 10

As an aside, I really do need a better way of creating an empty array that this. I looked for a solution for how to create an empty list of fixed size, but this is what I found in a SO post. I just know that Python will start this at 1 element and then do a loop to append the `None`s. This is just nasty; who knows how many resizes will this involve. Do you have advice how I could improve this?

I really should fix this, but I do not want to import Numpy just to get primitive object array functionality.

**Comment by da-woods** [comment]
Ah - I may have misunderstood. It sounds like you want something more like a [Numpy structured array](https://numpy.org/doc/stable/user/basics.rec.html#module-numpy.doc.structured_arrays) - which you can then access as a memoryview of packed structs. It's not well-documented but see https://stackoverflow.com/questions/48320410/correct-usage-of-numpy-recarrays-as-c-structarrays-in-cython for example. Improvements to documentation are always welcome: https://github.com/cython/cython/issues/855. For memoryview access they do have to be purely C-types though.

**Comment by mrakgr** [comment]
> Typed heterogenous arrays 

I mean to write homogenous here.

> For memoryview access they do have to be purely C-types though.

Not good enough, I want the all the types to be first class. Right now neither tuples nor structs can be composed with Python objects.

```
open arraym
inl main() =
    inl x : array (i32 * i32) = arraym.create 10 
    arraym.set x 0 (1,2)
```
```fs
let v0 : (struct (int32 * int32) []) = Array.zeroCreate<struct (int32 * int32)> 10
v0.[0] <- struct (1, 2)
```

Here is the same example as before on the F# backend. What I want is just the same as a regular .NET array that can hold arbitrary types, not just primitive ones. In fact, plain C arrays are the most similar to these, but they lack the memory management capability. .NET has them as a primitive for exactly that reason, so that the GC knows what they are.

---

Actually, I have an idea. Your links jogged my mind. For some reason it did not occur to me previously, but this is an ideal situation to use Spiral's [inverse arrays](https://github.com/mrakgr/The-Spiral-Language#real-nominals).

Instead of having an `array (i32 * f32 * object)`, I can compile those as `array i32 * array f32 * array object`. That will separate out the primitives from the objects. I should have thought of this right away, but when I saw that Python's `array` module did not have `object` arrays I just stopped thinking about it. I think I am going to reimplement Spiral's Cython arrays in terms of Numpy arrays and use the struct-of-arrays form to get the required efficiency.

**Comment by mrakgr** [comment]
https://cython.readthedocs.io/en/latest/src/tutorial/numpy.html#efficient-indexing

```
cdef np.ndarray[DTYPE_t, ndim=2] h = ...
```

I had no idea it was possible to specify the type of a Numpy array at compile-time like this. I made a mistake to use lists. Numpy arrays are what the primitive Spiral arrays should compile to. I'll fix this tomorrow.

**Comment by mrakgr** [comment]
```fs
open arraym
inl main() =
    inl x : array (i32 * i32) = arraym.create 10 
    arraym.set x 0 (1,2)
```
```
import numpy
cimport numpy
cdef class Tuple0:
    cdef readonly signed long v0
    cdef readonly signed long v1
    def __init__(self, signed long v0, signed long v1): self.v0 = v0; self.v1 = v1
cpdef void main():
    cdef numpy.ndarray[object,ndim=1] v0
    v0 = numpy.empty(10,dtype=object)
    v0[0] = Tuple0(1, 2)
```
```
open arraym
inl main() =
    inl x : array f32 = arraym.create 10 
    arraym.set x 0 3
```
```
import numpy
cimport numpy
cpdef void main():
    cdef numpy.ndarray[float,ndim=1] v0
    v0 = numpy.empty(10,dtype=numpy.float32)
    v0[0] = 3.000000
```

This is definitely an improvement on what I had before. Numpy arrays can be typed at compile time, though they only support objects, structs and primitives. Too bad I could not set its type as `Tuple0` in that first example. I'll put in inverse arrays into the core library at a later date.

At any rate, this request still stands. I did run into [trouble](https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory) trying to import Numpy, which would not have happened if Cython had its own primitive arrays. This demonstrates the danger of using outside libraries for key primitives.

**Comment by da-woods** [comment]
Cython does actually have it's own array type: https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#view-cython-arrays (although it's full capabilities aren't documented in that much detail). It supports primitive types, structs (try `format='dd` or similar) and objects (`format=O`).

If you want to use specific cdef classes then you can use an array with dtype object and view it with a memoryview of type `Tuple0`. You're responsible for making sure that it's only filled with the type that you say it is though.

I'm going to close this because I think we do actually have most of what you want already (now that i understand what you want).
Questions of *how* you use this feature are better directed to the cython-users mailing list rather than the bug-tracker.

**Comment by mrakgr** [comment]
Yeah, that does seem what I want. I'll mark this as solved.
