### ISSUE TITLE
[BUG]  `sizeof(uint32_t)` not considered contant

### ISSUE THREAD

**Issue by dvarrazzo** [cython/cython#3997]
**Describe the bug**

Code generated using `sizeof(uint32_t)` behaves like the value could change at runtime

**To Reproduce**
Code to reproduce the behaviour:
```cython
from libc.stdint cimport uint32_t

cdef extern from *:
    """
/* padding to align pointers to 4-bounds */
static const int int32_pad[] = {0, 3, 2, 1};
    """
    const int[4] int32_pad

cdef object test(Py_ssize_t pos):
    pos += int32_pad[pos % sizeof(uint32_t)]  # would you like some padding?
    return pos
```

**Result**
The above generated the following code for the calculation:
```c
  __pyx_t_1 = (sizeof(uint32_t));
  if (unlikely(__pyx_t_1 == 0)) {
    PyErr_SetString(PyExc_ZeroDivisionError, "integer division or modulo by zero");
    __PYX_ERR(0, 314, __pyx_L1_error)
  }
  __pyx_v_pos = (__pyx_v_pos + (int32_pad[(__pyx_v_pos % __pyx_t_1)]));
```
It is... more than unlikely that t_1 will be 0 :smile: 

**Expected behavior**
I would expect the same code generated for `[pos % 4]`, i.e.
```c
__pyx_v_pos = (__pyx_v_pos + (int32_pad[__Pyx_mod_Py_ssize_t(__pyx_v_pos, 4)]));
```
(well, actually I would have expected `pos % sizeof()`... but I guess you have reasons to use that macro instead of the `%` operator).

**Environment:**
 - OS: Linux
 - Python version 3.8.5
 - Cython version 3.0a6

**Comment by da-woods** [comment]
If it's causing you problems then it can be turned off by putting it in a `with cython.division(False):` block (similarly for the macro too). https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives

I don't think there's a good mechanism within Cython for marking an integer as "Cython doesn't know what value this has but it's definitely not 0". Which practically makes it quite hard to fix. Hopefully the C compiler is smart enough not to bother with this branch.

**Comment by robertwb** [comment]
I agree that we could optimize this away (though not sure how easy it would be). However the code above is still correct and should be optimized away by any decent optimizing C compiler.

**Comment by scoder** [comment]
We've always had a policy to let the C compiler do what it does well, and not bother Cython with it. I think this is such a case.
