### ISSUE TITLE
[BUG] Caught exception not defined within a closure

### ISSUE THREAD

**Issue by schiroo-wiw** [cython/cython#3998]
**Describe the bug**
A caught exception referenced within a closure is not defined within the closure after the `except` block.

**To Reproduce**
Code to reproduce the behaviour:
```cython
try:
    raise ValueError("I'm an error")
except ValueError as err:
    def print_err():
        print(err)
print_err()
# Traceback (most recent call last):
#   File "bar.py", line 6, in <module>
#     print_err()
#   File "bar.py", line 5, in print_err
#     print(err)
# NameError: name 'err' is not defined
```

**Expected behavior**
The error should be defined within the closure.
```cython
try:
    raise ValueError("I'm an error")
except ValueError as err:
    def print_err():
        print(err)
print_err()
# I'm an error
```

**Environment (please complete the following information):**
 - OS: macOS
 - Python version: 3.8.3
 - Cython version: 0.29.21

**Additional context**
If the closure is called before exiting the `except` block the error will be defined, but once called outside of the `except` block it will again be undefined.

**Comment by da-woods** [comment]
I get `NameError: name 'err' is not defined` when running in Python 3.8.6 (no Cython). That suggests that the Cython behaviour is right to me.

**Comment by da-woods** [comment]
It's worth pointing out that your example at the global scope won't actually create a closure at all - it just tries to look up a global variable.

If I run it in a function scope (again in pure Python):

```
def f():
...   try:
...     raise ValueError("I'm an error")
...   except ValueError as err:
...     def print_err():
...       print(err)
...   return print_err
... 
>>> f()()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in print_err
NameError: free variable 'err' referenced before assignment in enclosing scope
```

I get the same behaviour in Cython again.

**Comment by schiroo-wiw** [comment]
@da-woods Thank you for the clarification!  I'd expected the function to capture the error, but if this is the defined behavior then my expectations are just wrong. Is there a reference you could point me towards so I can clarify the expected behavior of the language before taking up any contributor time?

**Comment by da-woods** [comment]
https://docs.python.org/3/reference/compound_stmts.html#the-try-statement. Read the bit starting "When an exception has been assigned using `as target`...". It isn't absolutely clear just from reading that what you'd except to happen to captured variables.

For this type of bug report it's generally a good idea to check what Python does.

**Comment by schiroo-wiw** [comment]
Thanks for that information! Sorry, I realize now that I'd confused `cpython` and `cython` and had thought that `cython` was the reference implementation of `python`. Sorry for taking up your time, but I really appreciate your help!
