### ISSUE TITLE
[BUG] usage of argument clinic with docstrings not working properly

### ISSUE THREAD

**Issue by maxbachmann** [cython/cython#4011]
**Describe the bug**
In normal python a function definition with a docstring would look the following way:
```python
def example(arg):
    """
    long description
    """
    pass
```
using a similar function in Cython
```
```cython
def example(arg):
    """
    long description
    """
    pass
```
results in a docstring without information about the arguments. It is possible to add this description using the format of argument clinic. However it appears like cython includes all preceding whitespaces in this multiline comment into the resulting docstring. So the definition would look like this:
```cython
def example(arg):
    """example($module, arg)
--

long description
"""
    pass
```
This works fine, but looks very weird

**To Reproduce**
Code to reproduce the behaviour:
```cython
def example(arg):
    """
    example($module, arg)
    --

    long description
    """
    pass
```
results in the docstring
```
"\n    example($module, arg)\n    --\n\n    long description\n    "
```

**Expected behavior**
It would be expected, that for multiline strings the common preceding whitespaces are ignored. It would probably make sense to ignore the first newline as well, when there is no text on the first line. The output would then look the following way:
```
"example($module, arg)\n--\n\nlong description\n"
```

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.9.1
 - Cython version: 0.29.21

**Comment by da-woods** [comment]
As far as I can tell it does exactly the same thing as Python - https://www.python.org/dev/peps/pep-0257/#handling-docstring-indentation the description is that _docstring processing tools_ strip the whitespace; Python itself doesn't.

It's possible I'm missing something here, but certainly your example behaves identically in Python and Cython.

**Comment by da-woods** [comment]
You may also find the `cython: binding` directive useful - it improves the introspectibility of function arguments, and hence they don't need to go in the docstring.

**Comment by maxbachmann** [comment]
Ah I was not aware the binding directive existed. That's a lot better than manually using argument clinic
