### ISSUE TITLE
SILENT GCC

### ISSUE THREAD

**Issue by matejmicek** [cython/cython#4026]
Honestly, I have spent countless hours trying to figure this out.

Basically, I am developing a serialization framework that uses Cython to compile code. I wanted to compose a demo console app that would benchmark it against other frameworks.

Since my app compiles the code on-demand at runtime, it prints all the GCC warning to the console. 

e.g.
```
/Users/matejmicek/Library/Caches/cython/inline/_cython_inline_699ae8778e7c6b1e514d6416245faebf.c:3737:13: warning: unused variable
      '__pyx_doc_4read_16read_fixed' [-Wunused-variable]
static char __pyx_doc_4read_16read_fixed[] = "Fixed instances are encoded using the number of bytes declared in the\n\tschema.";
```

Also, it is technically really difficult to get rid of the causes of these warnings. Meaning I have support files that sometimes contain unnecessary stuff for one schema but necessary for another.

My question is: How do I get rid of these?

When trying to get rid of these warning I tried:
- googling: didn't help
- passing compiler directives to Cython: I set all the 'warn' ones to False but this did not change anything.
- redirecting `stdout` and `stderr` to `/dev/null`: this surprisingly didn't help either. This I honestly can't understand. The problem with these warnings is that they apparently dont print to either `stdout` or `stderr`, which from my understanding of Unix is not possible, but apparently I am wrong in this case.
- looking through the code of Cython and trying to silence it there, but it all comes down to the compiler I think.

What I want: I want a real cythonice `silent` option that blocks ALL the logs/prints out of the stream. 

Maybe it is already possible and if so, please let me know how.

Thanks a lot to everyone!

Matej

**Comment by da-woods** [comment]
I don't know the full solution but the error message is from C rather than Cython. If you can get a `-w` flag to gcc I think it should silence all warnings.

**Comment by matejmicek** [comment]
@da-woods Thanks a lot. You're the real MVP. It was enough to pass `['-w']` to the `extra_compile_args` argument of `distutils.core.Extension` in `cython._inline`. One again, thank you!
