### ISSUE TITLE
[ENH]  Decimal module C API

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4027]
**Describe the solution you'd like**
Python 3.10 will add a [C API for the decimal module](https://docs.python.org/3.10/c-api/decimal.html). Cython should include this in its C API wrapping.

**Describe alternatives you've considered**
Cython could ignore this new API and not wrap it

------------

The only complication is the advanced API that includes `mpdecimal` headers. There should probably be separate .pxd files so that the regular API will work without those headers.

**Comment by mattip** [comment]
It seem that a better course of action would be to ignore it, at least until it is officially released and has solidified across a few releases of CPython.

**Comment by da-woods** [comment]
@mattip I've removed the "help wanted" tag since you're probably right that it's worth waiting until it's fixed.

**Comment by da-woods** [comment]
Mattip's advice to ignore it turned out to be good advice.

**Comment by Kai-Striega** [comment]
I'm currently investigating whether it is possible to Cythonize a library that supports Decimal types and have a couple of questions:

> The only complication is the advanced API that includes mpdecimal headers. There should probably be separate .pxd files so that the regular API will work without those headers.

I couldn't find any reference to mpdecimal in Cython. Is this in Cython or CPython?

> Is there any support for decimal in Cython, if not would there be any way to add it from a user perspective?

**Comment by da-woods** [comment]
> I couldn't find any reference to mpdecimal in Cython. Is this in Cython or CPython?

Mpdecimal is used internally in cpython to implement decimals.

> Is there any support for decimal in Cython, if not would there be any way to add it from a user perspective?

No there isn't, and no I don't believe it would be possible to add it from a user perspective. Unfortunately they didn't end up adding any C API to access it so there's really no way to get into the decimal types.

You could always wrap a c/c++ library that does the same thing and use that from Cython, but that doesn't get you a nice interaction with the standard library decimal types.

**Comment by Kai-Striega** [comment]
> You could always wrap a c/c++ library that does the same thing and use that from Cython, but that doesn't get you a nice interaction with the standard library decimal types.

At the moment, I've got a Cython fast path and a pure python slow implementation for Decimal types. I don't like having the code duplicated like this. If been looking at this and might give it a try, I'm not sure if it's the best way to go. Just a couple of questions:

* This would add a significant performance overhead, as we have to convert from Python's Decimal type to my own Decimal type, right?
* Is it possible to tell Cython: “this is a decimal, convert it to my own Decimal”?

**Comment by da-woods** [comment]
> *    This would add a significant performance overhead, as we have to convert from Python's Decimal type to my own Decimal type, right?

Probably; depends how much work there is after the conversion

> *   Is it possible to tell Cython: “this is a decimal, convert it to my own Decimal”?

No.

Can you direct any further questions to the [Cython-user's mailing list](https://groups.google.com/g/cython-users) (or possibly the [python discussion board](https://discuss.python.org/), if you phrase it as C API rather than Cython) instead; not sure I have anything hugely incite to add though.
