### ISSUE TITLE
[ENH] How to compile multiple Python modules to generate a PYD file?

### ISSUE THREAD

**Issue by botao1995** [cython/cython#4048]
I have a project, and now I need to compile multiple modules in the project into a PYD

**Comment by da-woods** [comment]
Support questions are better asked on the [Cython-users mailing list](https://groups.google.com/forum/#!forum/cython-users).

Doing this automatically isn't a feature that's currently part of Cython. I believe a few people have made tools to automate this (e.g. https://github.com/smok-serwis/snakehouse), but again, ask elsewhere for a complete list of for support using these tools
