### ISSUE TITLE
[BUG] unused variable warnings on MSVC

### ISSUE THREAD

**Issue by maxbachmann** [cython/cython#4057]
In the codebase there are a lot of places, where an argument for a function is not used. On most compilers this warning is suppressed using the `CYTHON_UNUSED` macro. However since MSVC does not have a similar feature to `__attribute__((unused))`, this causes warnings on MSVC. I think the most straightforward way to fix this would a macro like:
```cpp
#define  CYTHON_UNUSED_ARG(identifier) /*Empty*/
```
I was not sure, whether there was a specific reason, why we would like to keep the identifier in there and just suppress it using `__attribute__((unused))`. In case there is a reason to keep the identifier, it could use
```
#define  CYTHON_UNUSED_ARG(identifier) CYTHON_UNUSED identifier
```
in those cases. However I do not really see a reason, why it would be helpful to keep it.
I am willing to implement this change, but looking for feedback, before I actually change it.

**Comment by mattip** [comment]
A more complete cross-compiler fix is in [this stackoverflow](https://stackoverflow.com/questions/7090998/portable-unused-parameter-macro-used-on-function-signature-for-c-and-c) question, with the added `#define UNUSED(x) __pragma(warning(suppress:4100)) x` for msvc and C.

**Comment by mattip** [comment]
#4162 was merged, I think this can be closed.

**Comment by maxbachmann** [comment]
As far as I remember this should have caught most occurrences.

**Comment by scoder** [comment]
What about #4149? Is that still a thing?

**Comment by mattip** [comment]
Maybe we should leave this open until we run CI on windows. xref #4324

**Comment by maxbachmann** [comment]
> What about https://github.com/cython/cython/pull/4149? Is that still a thing?

Yes totally forgot about this. Revived in #4693

**Comment by maxbachmann** [comment]
Warnings are now mostly fixed. There are still some remaining when using msvc and a C++ standard lower than C++17. However fixing them is pretty ugly, since we need to support C89.
