### ISSUE TITLE
[BUG] @cython.cfunc is applied to inner functions too

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4092]
**Describe the bug**

The `cython.cfunc` decorator is applied not just to the function that is decorates, but to all enclosed functions. This causes a compiler crash.

I suspect that there's other decorators that this applied to as well (e.g. `cython.returns`, `cython.cclass`, etc). I haven't made a thorough check of these yet though.

**To Reproduce**

Code to reproduce the behaviour:
```cython
import cython

@cython.cfunc
def f():
    def inner():  # should not be a cfunc
        pass
    return inner
```

The error message ends with 
```
Cython/Compiler/ParseTreeTransforms.py", line 2783, in create_class_from_scope
    if not node.py_cfunc_node:
AttributeError: 'CFuncDefNode' object has no attribute 'py_cfunc_node'
```
(but I don't think this is actually hugely useful to the bug)

**Expected behavior**
`f` should be a `cdef` function, `inner` should be a regular function.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.8.8
 - Cython version: current master branch

**Comment by scoder** [comment]
IIRC, we previously ignored this issue because cdef functions cannot have closures anyway.
It definitely shouldn't crash, though. Does it also happen with `cdef` syntax?

**Comment by da-woods** [comment]
> Does it also happen with `cdef` syntax?

Works and runs fine:
```
cdef f():
    def inner():  # should not be a cfunc
        pass
    return inner
```

Fails correctly with "C function definition not allowed here"
```
cdef f():
    cdef inner():  # should not be a cfunc
        pass
    return inner
```

------------------------------------------

I can confirm `@cython.cclass` also has a very similar bug.
