### ISSUE TITLE
[BUG] Using CFLAGS for compiler defines

### ISSUE THREAD

**Issue by vorfol** [cython/cython#4096]
runtests.py:
We should not use compiler flags for compiler defines. The different compilers have different command line syntaxes. There is a special parameter for this - compiler definitions (distutils.Extension(..., define_macros=...). 

**To Reproduce**
execute runtests.py on OpenVMS

**Expected behavior**
all tests must be done without errors

**Environment (please complete the following information):**
 - OS: OpenVMS
 - Python version 3.8.2
 - Cython version 0.29.22

**Comment by da-woods** [comment]
It looks like we've tried to do this right at least once:

https://github.com/cython/cython/blob/217a93e7b139ab49815ea9ca34142b3e2a116a08/runtests.py#L1143

so it's probably a useful change to apply it to the other defines in runtest.py if possible.

I don't know how easy it is to eliminate _all_ custom compiler arguments from runtests.py though

**Comment by scoder** [comment]
The main difference is that these defines are currently set globally and would then need to be set at a per-module level, i.e. for each test. Probably means passing down the options, but shouldn't be too difficult. PR welcome.
