### ISSUE TITLE
[BUG] List comprehension overwrites already defined local variable

### ISSUE THREAD

**Issue by Unvorhandener-Winzling** [cython/cython#4105]
**Describe the bug**
An already defined variable gets overwritten if the same name is used as a placeholder in list comprehension, while in original python code this does not happen.
Possibly the same problem as #1159, but I thought it might be worth it to create a new issue for this specific case because the error is hard to notice since there is no indication this happened.

**To Reproduce**

code of cython_test.pyx file
```
variable = 'variable'
unrelated_list = ['listentry1', 'listentry2', 'listentry3']
filtered_list = [variable.upper() for variable in unrelated_list]
print('variable is:' + variable)
```
setup.py:
```
import distutils.core
import Cython.Build
distutils.core.setup(
    ext_modules = Cython.Build.cythonize("cython_test.pyx"))
```
finaly python code analog to .pyx file:
```
print('Now cython code is imported, variable will be printed:')
import cython_test

print('Now python code is run exactly as in pyx file:')
# from here on the code is exactly the same as in the .pyx file
variable = 'variable'
unrelated_list = ['listentry1', 'listentry2', 'listentry3']
filtered_list = [variable.upper() for variable in unrelated_list]
print('variable is:' + variable)
```
Produces:
```
Now cython code is imported, variable will be printed:
variable is:listentry3
Now python code is run exactly as in pyx file:
variable is:variable
```

**Expected behavior**
Behavoir of cython compiled code to match python code behavoir. Otherwise give warning while compilation.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.9.3
 - Cython version: 0.29.22

**Additional context**
Sorry if this is an already known bug, I am 90% sure I made a mistake somewhere

**Comment by da-woods** [comment]
This is expected behaviour in Python 2. Note that Python 0.29.22 follows Python 2 behaviour by default with compiling pyx files (even when running in Python 3). You can change this with Cython's `language_level` parameter.

```
#cython: language_level=3
```
(or `3str`).
