### ISSUE TITLE
[BUG] CYTHON_LIMITED_API and CHANGES.rst

### ISSUE THREAD

**Issue by andrewvaughanj** [cython/cython#4113]
Currently, CHANGES.rst states this:

```
* Preliminary support for the CPython's ``Py_LIMITED_API`` (stable ABI) is
  available by setting the  ``CYTHON_LIMITED_API`` C macro.  Note that the
  support is currently in an early stage and many features do not yet work.
  Patches by Eddie Elizondo and David Woods.  (Github issues :issue:`3223`,
  :issue:`3311`, :issue:`3501`)
```

Despite the above, it seems that this functionality was "hard disabled" in 0c01ea5d8e (April 10th, 2020; interestingly, this change was made *before* CHANGES.rst was updated):

```
#if defined(CYTHON_LIMITED_API) && 0  /* disabled: enabling Py_LIMITED_API needs more work */
```

That is, there's no way to get this to work from the outside, because of the `&& 0`.

However, it isn't documented (e.g., in CHANGES.rst) that this **really** doesn't work.

Would it be reasonable to open-up a PR documenting (e.g., in CHANGES.rst) that `CYTHON_LIMITED_API` isn't ready for prime-time? What's in CHANGES.rst currently is more optimistic about the status of this feature than the actuality :)

**Comment by scoder** [comment]
I don't think the comment is wrong. For me, "preliminary support" does not mean that "Py_LIMITED_API" is automatically enabled to enforce usage of the limited API. It just means that Cython tries to adhere to it where possible if you set the `CYTHON_LIMITED_API` macro. Note the `#ifndef Py_LIMITED_API` that follows the line you quoted. You can define that macro yourself if you want.

**Comment by andrewvaughanj** [comment]
This is my point: if you set `CYTHON_LIMITED_API` (from the outside), it has no effect because of the `&& 0` at the end of the directive.

People may think "oh, I can try setting `CYTHON_LIMITED_API` to get me closer to `Py_LIMITED_API`", but actually it doesn't do that at all (in its current form).

**Comment by andrewvaughanj** [comment]
Just to be clearer, here's my issue:

1. Someone reads CHANGES.rst and finds out about `CYTHON_LIMITED_API`
2. They read about the benefits of `Py_LIMITED_API` and think "oh, this would be great, I should turn on `CYTHON_LIMITED_API`!"
3. They try running Cython and compiling with `-DCYTHON_LIMITED_API=1`
4. Their code builds and run, and so they think "ah, excellent, my code works with `Py_LIMITED_API`!"

However, this has only worked because `CYTHON_LIMITED_API` doesn't actually enable `Py_LIMITED_API`, despite what is currently in CHANGES.rst.

I just think that the current content is misleading to the current status of things: "many features do not yet work" suggests that Cython or the compilation is likely to fall-over if you try running with it (therefore it is "obvious" if your code doesn't work with `Py_LIMITED_API`) -- however, actually, enabling `CYTHON_LIMITED_API` doesn't actually enable `Py_LIMITED_API`, so you don't know if your code works with the limited API or not.

(I should say: I'm not a user of this functionality, I just came across this while trying to resolve #4111, and thought it was worth writing up that it feels misleading -- apologies if it seems I've been "overly negative" about `CYTHON_LIMITED_API`)

**Comment by scoder** [comment]
> it has no effect

It has no effect on setting `Py_LIMITED_API`. However, it has an effect on tons of code in the module, including several optimisations and helper functions, to make them adhere (as far as currently possible) to the limited API.

**Comment by andrewvaughanj** [comment]
I think this problem "goes away" if the paragraph in CHANGES ended with:

```
... currently in an early stage and many features do not yet work (and,
furthermore, enabling `CYTHON_LIMITED_API` does not yet currently enable
`Py_LIMITED_API`)
```

**Comment by andrewvaughanj** [comment]
6ba500e looks great! :D
