### ISSUE TITLE
[BUG] Wrapping function pointers generate duplicated definitions

### ISSUE THREAD

**Issue by emcastillo** [cython/cython#4120]
**Describe the bug**

Declaring external C-function prototypes with the arguments being of the same type but different names, causes Cython to generate duplicated wrap functions. These wrap functions are generated when we manipulate the function pointers from python, as they are wrapped into PyObjects.

The workaround is to have all the parameters with the same name.

**To Reproduce**
Code to reproduce the behaviour (by @kmaehashi):

```cython
# cython: language_level=3
from libc.stdint cimport intptr_t
cdef extern from "Python.h" nogil:
    void PyMem_Free(intptr_t p)
    void PyMem_Del(intptr_t q)
cpdef test():
    call_it(PyMem_Free)
    call_it(PyMem_Del)
cdef call_it(func):
    func(0)
```

This causes errors like the following
```
cyt.c:1540:13: error: redefinition of ‘__pyx_doc_11cfunc_dot_to_py_44__Pyx_CFunc_void____intptr__t____nogil_to_py_wrap’
 static char __pyx_doc_11cfunc_dot_to_py_44__Pyx_CFunc_void____intptr__t____nogil_to_py_wrap[] = "wrap(q: 'intptr_t') -> 'void'";

cyt.c:1390:13: note: previous definition of ‘__pyx_doc_11cfunc_dot_to_py_44__Pyx_CFunc_void____intptr__t____nogil_to_py_wrap’ was here
 static char __pyx_doc_11cfunc_dot_to_py_44__Pyx_CFunc_void____intptr__t____nogil_to_py_wrap[] = "wrap(p: 'intptr_t') -> 'void'";

```
**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.7.3
 - Cython version 0.29.23

**Comment by da-woods** [comment]
I'd think this is a duplicate of https://github.com/cython/cython/issues/3716. If so, it was fixed on the current master branch. I don't immediately know if it's possible to back-port the fix to 0.29.x or not though.

**Comment by emcastillo** [comment]
Indeed, seems its a duplicated one :).
since it's fixed already I will close this now, thanks!

**Comment by da-woods** [comment]
Doesn't look like it backports cleanly I'm afraid. I suggest either using the Cython 3 alpha release, or using [`cpdef` declarations for your extern functions instead](http://docs.cython.org/en/latest/src/tutorial/external.html#external-declarations).
