### ISSUE TITLE
[ENH] Test GraalPython

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4123]
[GraalPython](https://github.com/oracle/graalpython) is an alternative Python implementation. If I understand it correctly it's an implementation of Python that works/compiles to a Java virtual machine, and supports C extensions by executing LLVM bytecode. (My understanding is sketchy though...).

It claims to support some of Numpy and Pandas, which suggests that it can run some Cython extensions. Therefore it might be an idea to test/support it on a similar basis to PyPy.

**Describe alternatives you've considered**

* Do nothing (the status quo),
* Gently prod the maintainers of GraalPython into running the Cython tests instead.

**Additional context**

1. I don't know if anyone is actually using it (i.e. is it worth anyone's effort to support)
2. It probably shouldn't be considered until the Travis->Github actions migration is finished/understood
3. I know nothing about this personally (even how to install GraalPython locally to try it), and wasn't planning on doing it myself, so have created the issue in case it was of interest to someone else.

**Comment by da-woods** [comment]
Quick report on this: running the test suite is pretty slow and also seems pretty resource intensive (looked to be using 5GB of RAM on my PC) so I think we're going to struggle to add it to the test-suite.

Anything using multiprocessing (i.e. a lot of end to end tests with `-j` arguments) seems to be getting stuck in infinite loops.

There's a good deal of failures with "bad internal call" that right now I don't know how to debug (thus definitely don't know how to fix) but some stuff seems to work

**Comment by da-woods** [comment]
Part of the problem is they define `PYPY_VERSION` (https://github.com/oracle/graalpython/blob/39e26642d7c4a9f490c19db9270753a657b97f30/graalpython/com.oracle.graal.python.cext/include/Python.h#L51) and thus Cython detects it as PyPy. This causes everything with a cdef class to fail because of `tp_pypy_flags`

**Comment by scoder** [comment]
> Part of the problem is they define `PYPY_VERSION` (https://github.com/oracle/graalpython/blob/39e26642d7c4a9f490c19db9270753a657b97f30/graalpython/com.oracle.graal.python.cext/include/Python.h#L51) and thus Cython detects it as PyPy. This causes everything with a cdef class to fail because of `tp_pypy_flags`

We can fix that by checking for `GRAALVM_PYTHON` first, and giving them their own config section.

**Comment by da-woods** [comment]
> We can fix that by checking for GRAALVM_PYTHON first, and giving them their own config section.

I'm submitting a PR to do that shortly...

**Comment by da-woods** [comment]
>Part of the problem is they define PYPY_VERSION (https://github.com/oracle/graalpython/blob/39e26642d7c4a9f490c19db9270753a657b97f30/graalpython/com.oracle.graal.python.cext/include/Python.h#L51) and thus Cython detects it as PyPy. This causes everything with a cdef class to fail because of tp_pypy_flags

Probably fixed https://github.com/oracle/graalpython/commit/421dd8b08e0c329924705b5567c50771984c7774

**Comment by fangerer** [comment]
Yes, I confirm that we removed definition of `PYPY_VERSION` in the meantime. However, I would appreciate if we could have a check for `GRAALVM_PYTHON` since we currently override some Cython defines (where possible).
I've already seen the PR related to this issue. I'll add some comments.

**Comment by da-woods** [comment]
> Yes, I confirm that we removed definition of `PYPY_VERSION` in the meantime. However, I would appreciate if we could have a check for `GRAALVM_PYTHON` since we currently override some Cython defines (where possible).
> I've already seen the PR related to this issue. I'll add some comments.

Thanks. I'll give it another go next time there's a proper release. I also saw an update for multiprocessing which I think was breaking a lot of tests at the compilation stage so hopefully that'll help too.

**Comment by scoder** [comment]
We're now testing GraalPython as part of the regular CI runs.
