### ISSUE TITLE
zsh: bus error when running cython module

### ISSUE THREAD

**Issue by noonchen** [cython/cython#4132]
Hi, I'm trying to rewrite a c function in cython, which is used for byte-swaping:

```
from libc.stddef cimport size_t
from libc.string cimport strlen

cdef void SwapBytes(void* pv, size_t n):
    # https://stackoverflow.com/a/2182581
    cdef char *p = <char*>pv
    cdef size_t lo = 0, hi = n-1
    cdef char tmp

    while hi > lo:
        tmp = p[lo]
        p[lo] = p[hi]
        p[hi] = tmp
        lo += 1
        hi -= 1

cdef char* a = b'\x01\x02\x03\x04'

print("before swap", a)
SwapBytes(a, strlen(a))
print("after swap", a)
```

I used `pyximport` to test the code above and I'm expecting:
```
before swap b'\x01\x02\x03\x04'
after swap b'\x04\x03\x02\x01'
```
but instead, I get a `zsh: bus error  /usr/local/opt/python@3.8/bin/python3`.

I am new to Cython and C world, please pardon me if I made any silly mistakes.

**Comment by noonchen** [comment]
In the code above, I also notice something quite confusing.
`cdef char* a = b'\x01\x02\x03\x04'`
In python, `a` is bytes with the length of 4, but in Cython, `sizeof(a)` returns 8 and `strlen(a)` returns 4, I think they both indicate the length of char*, I just cannot figure out what happened here... 😂

**Comment by da-woods** [comment]
`cdef char* a = b'\x01\x02\x03\x04'`

C string literals are not stored in modifiable memory I believe.

`sizeof(a)` represents the size needed to store the pointer.

Support questions should be asked on the [Cython users mailing list](https://groups.google.com/forum/#!forum/cython-users) rather than the bug tracker.
