### ISSUE TITLE
[BUG] `inspect.iscoroutinefunction` call on `async` method is `False`

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#4138]
**Describe the bug**

When Cythonizing a `class` that contains an `async` method, it appears `inspect.iscoroutinefunction` returns `False`. If the same `class` were not Cythonized, passing the `async` method to `inspect.iscoroutinefunction` returns `True`.

**To Reproduce**
Code to reproduce the behaviour:

```cython
import inspect


class C:
    async def m(self):
        pass


assert inspect.iscoroutinefunction(C.m)  # <--- Fails when Cythonized. Passes in pure Python
```

**Expected behavior**

`inspect.iscoroutinefunction` having the same result whether the `class` is Cythonized or not.

**Environment (please complete the following information):**
 - OS: macOS
 - Python version: 3.8.8
 - Cython version: 0.29.23

**Additional context**

NA

**Comment by da-woods** [comment]
I don't think `inspect.iscoroutinefunction` will ever work. On the current master `asyncio.iscoroutinefunction` does work though: see https://github.com/cython/cython/issues/2273 and https://github.com/cython/cython/issues/2092

**Comment by jakirkham** [comment]
Ah sorry for the dup. Had searched, but didn’t find those issues somehow 😞

Thanks for the advice 🙂 Will see if we can switch to asyncio for the check
