### ISSUE TITLE
Can't catch ValueError from float() calls

### ISSUE THREAD

**Issue by brownan** [cython/cython#4143]
In latest master branch, it seems this pattern fails when given a string that can't be converted to a float:

```
def foo(val):
    try:
        a = float(val)
    except ValueError:
        a = val

    return a
```

Compiling and running this gets this error:
```
$ python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cython_trycatch
>>> cython_trycatch.foo("foo")
ValueError: could not convert string to float: 'foo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <cyfunction foo at 0x7f86475a0930> returned a result with an error set
>>> 
```

This problem isn't present on the latest release 0.29.23. I bisected the cython repo and found the commit 337bf7f3b6611126c86cc55de9112eafa2e34034 introduced this problem.

Unfortunately I don't quite know enough about cython internals to fix this myself. Hope this helps, and thanks for the great project!

**Comment by da-woods** [comment]
That has some of the signs of being my fault.

I think it'll be one of the lines

```
return PyFloat_FromDouble(__Pyx_PyUnicode_AsDouble(obj));
return PyFloat_FromDouble(__Pyx_PyByteArray_AsDouble(obj));
```

which make the assumption that `__Pyx_PyUnicode_AsDouble`/`__Pyx_PyUnicode_AsDouble` return error free.

Thanks for the detailed report.

**Comment by brownan** [comment]
I dug into this a bit more and found the same place. What do you think about changing `__Pyx_PyNumber_Float()` to something like this?

```
static CYTHON_INLINE PyObject* __Pyx_PyNumber_Float(PyObject* obj) {
    double val;
    if (PyFloat_CheckExact(obj)) {
        return __Pyx_NewRef(obj);
    } else if (PyUnicode_CheckExact(obj)) {
        val = __Pyx_PyUnicode_AsDouble(obj); 
        return val == -1 && PyErr_Occurred() ? NULL : PyFloat_FromDouble(val);
    } else if (PyBytes_CheckExact(obj)) {
        val = __Pyx_PyBytes_AsDouble(obj);
        return val == -1 && PyErr_Occurred() ? NULL : PyFloat_FromDouble(val);
    } else if (PyByteArray_CheckExact(obj)) {
        val = __Pyx_PyByteArray_AsDouble(obj); 
        return val == -1 && PyErr_Occurred() ? NULL : PyFloat_FromDouble(val);
    } else {
        return PyNumber_Float(obj);
    }
}
```

**Comment by da-woods** [comment]
I was just in the process of making a very similar change... but yes, that's basically the solution.

**Comment by brownan** [comment]
okay cool, thanks! I'll submit a PR today or tomorrow as soon as I can get a test written
