### ISSUE TITLE
[BUG] Can't write a cython module with a function that returns std::string

### ISSUE THREAD

**Issue by enjoysmath** [cython/cython#4145]
The original problem I had was wanting to convert an integer to a base-10 std::string of that value.  So I thought, hmm, no solution on the net so let me just use some modular arithmetic.  So I wrote `cdef string int_to_string(int x)` like so:

```
# distutils: language = c++

cimport cython
from libcpp.string cimport string
from libc.math cimport fmod
   
   
cdef string int_to_string(int x):
   cdef string s = b''
   cdef string sgn = '-'
   cdef int mod
   
   if x == 0:
      return b'0'
   
   if x > 0:
      sgn = ''
   else:     # The below algorithm only works with positive values by definition of modulo
      x = -x
   
   while x != 0:
      mod = x % 10
      
      if mod == 0:
         s += b'0'
      elif mod == 1:
         s += b'1'
      elif mod == 2:
         s += b'2'
      elif mod == 3:
         s += b'3'
      elif mod == 4:
         s += b'4'
      elif mod == 5:
         s += b'5'
      elif mod == 6:
         s += b'6'
      elif mod == 7:
         s += b'7'
      elif mod == 8:
         s += b'8'
      elif mod == 9:
         s += b'9'
      
      x //= 10
            
   return sgn + s
```

![image](https://user-images.githubusercontent.com/1606391/117428627-1945ae80-aedb-11eb-9960-0a9f97bfc43b.png)

In `tools.pyx` and I do have the prototype for it in the `pxd` file as you can see.  The cython build process says nothing, but when I run code that calls `int_to_string` I get:

```
File "C:\Users\FruitfulApproach\Desktop\FiancialCode\financial_framework\main.py", line 1, in <module>
  from string_rep import StringRep
File "C:\Users\FruitfulApproach\Desktop\FiancialCode\financial_framework\string_rep.pyx", line 1, in init string_rep
  # distutils: language = c++

builtins.ImportError: tools does not export expected C function int_to_string
```

Any idea how to either convert a int to a std::string without going through Python (as this is time-critical code), or how to fix the above weird error?  All my files have the C++ comment tag at the beginning.  The code works fine without this addition, and I am able to use std::map, std::vector just fine.  Now this...

**Comment by enjoysmath** [comment]
Okay, my solution for now is hackish, but I took out the function from the second module and just put it into the module that uses it, and I had to modify it since you can't add byte objects to std::strings, like so, if anyone also needs that function:

```
cdef string int_to_string(int x):
   cdef string s = b''
   cdef string sgn = b'-'
   cdef int mod
   
   if x == 0:
      return b'0'
   
   if x > 0:
      sgn = b''
   else:     # The below algorithm only works with positive values by definition of modulo
      x = -x
   
   while x != 0:
      mod = x % 10
      
      if mod == 0:
         s = string(b'0') + s
      elif mod == 1:
         s = string(b'1') + s
      elif mod == 2:
         s = string(b'2') + s
      elif mod == 3:
         s = string(b'3') + s
      elif mod == 4:
         s = string(b'4') + s
      elif mod == 5:
         s = string(b'5') + s
      elif mod == 6:
         s = string(b'6') + s
      elif mod == 7:
         s = string(b'7') + s
      elif mod == 8:
         s = string(b'8') + s
      elif mod == 9:
         s = string(b'9') + s
      
      x /= 10
      
   return sgn + s   
```

I would like the ability in cython to return std::strings from an cimported function, but I guess you can't.  O___O

**Comment by scoder** [comment]
Might be a bug, especially since you wrote that it works with `std::vector` and others (which, BTW, would be quite indicative).

Regarding your specific problem, you probably just want to use the [`to_string()`](https://www.cplusplus.com/reference/string/to_string/) function.

**Comment by enjoysmath** [comment]
> Might be a bug, especially since you wrote that it works with `std::vector` and others (which, BTW, would be quite indicative).
> 
> Regarding your specific problem, you probably just want to use the [`to_string()`](https://www.cplusplus.com/reference/string/to_string/) function.

I thought that might not be available.  Are you saying I should do:

from libcpp import string
s = to_string(1111)

?

**Comment by enjoysmath** [comment]
> Might be a bug, especially since you wrote that it works with `std::vector` and others (which, BTW, would be quite indicative).
> 
> Regarding your specific problem, you probably just want to use the [`to_string()`](https://www.cplusplus.com/reference/string/to_string/) function.

`string_rep.pyx:66:31: 'to_string' is not a constant, variable or function identifier`

**Comment by enjoysmath** [comment]
This is not good:

![image](https://user-images.githubusercontent.com/1606391/117445976-46e92280-aef0-11eb-8486-3d09073bd36b.png)

I can't even zero an ndarray with a utility function.  Are you telling me everything must go into the same module?

**Comment by scoder** [comment]
> `'to_string' is not a constant, variable or function identifier`

Looks like `to_string` wasn't declared in `string.pxd` yet. I added it in bc3dd1a2ece6e72d80e2796af3737a1cb65b6142. You can always declare it yourself, though.

**Comment by scoder** [comment]
The following works for me, indicating that you're doing something differently that you're not showing.
`a.pyx`:
```cython
# distutils: language=c++

from libcpp.string cimport string

cdef string get_string(int x):
    s = f"{x}".encode('ascii')
    return string(<char*>s)
```

`a.pxd`:
```cython
from libcpp.string cimport string

cdef string get_string(int x)
```

`b.pyx`:
```cython
# distutils: language=c++

from a cimport get_string

print(get_string(123))
```

`cythonize -i a.pyx b.pyx`
`python3 -c 'import b'`
outputs: `b'123'`

**Comment by scoder** [comment]
Closing as "works for me".

**Comment by enjoysmath** [comment]
Thanks @scoder, your example gave me the idea to include both module names in the setup file.
