### ISSUE TITLE
[BUG] TypeError: Shared Cython type generator has the wrong size

### ISSUE THREAD

**Issue by cgohlke** [cython/cython#4152]
**Describe the bug**
I compiled the [imagecodecs](https://github.com/cgohlke/imagecodecs) package for testing purposes with Cython 0.29.x (commit 019aebdf5a345087cf4051d3c63d43f6984d7503) on python-3.8.10-amd64 and get the following error when importing any Cython extension. E.g.:

```
> py -c"from imagecodecs import _imcd"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "imagecodecs\_imcd.pyx", line 1, in init imagecodecs._imcd
    # imagecodecs/_imcd.pyx
TypeError: Shared Cython type generator has the wrong size, try recompiling
```

I traced this to commit cb53a50cf30aa75cbc98c31292a5e5a914c3f4a4: **Implement "gen.gi_frame" and "coro.cr_frame" attributes on generators and coroutines that return an inspectable (although otherwise dead) frame object.**

Cython extensions built with this version fail to import. Cython extensions built with earlier versions import without error.

**Environment (please complete the following information):**
```
 - Microsoft Windows [Version 10.0.19042.964]
 - Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
 - numpy 1.20.3 compiled with Cython 0.29.23
 - Cython version 0.29.x 019aebdf5a345087cf4051d3c63d43f6984d7503

**Comment by da-woods** [comment]
I suspect that this is the same issue as https://github.com/cython/cython/issues/4069 was: Cython tries to share common objects such as CyFunction and its generator type. It uses the version string as a disambiguation. You've made some change that's made the generators incompatible with the ones in 0.29.3, but not changed the version string.

 Try changing the version number in https://github.com/cython/cython/blob/019aebdf5a345087cf4051d3c63d43f6984d7503/Cython/Shadow.py#L4

Given that this has come up a couple of times recently it makes me wonder if there's a better solution (but I don't quite know what the solution is...)

**Comment by cgohlke** [comment]
> Try changing the version number

That worked. Thank you!
