### ISSUE TITLE
cl : Command line warning D9002 : ignoring unknown option '-fopenmp'

### ISSUE THREAD

**Issue by Noraboke** [cython/cython#4170]
Hi, 

I'm trying to experiment with OpenMP in Cython, however I am getting this error when I try to compile the code:

`cl : Command line warning D9002 : ignoring unknown option '-fopenmp'`

How would I approach fixing this?

My code and setup is very simple:

_test.pyx_

```
from cython.parallel import prange

def cake(int n):
    cdef int i
    cdef int sum = 0
    for i in prange(n, nogil=True):
        sum += i

    print(sum)
```

_setup.py_
```
from setuptools import Extension, setup
from Cython.Build import cythonize

ext_modules = [
    Extension(
        "test",
        ["test.pyx"],
        extra_compile_args=['-fopenmp'],
        extra_link_args=['-fopenmp'],
    )
]

setup(
    name='hello-parallel-world',
    ext_modules=cythonize(
        ext_modules,
    ),
)

```

**Comment by scoder** [comment]
You're probably using MSVC, which uses `/` instead of `-` as an option prefix.

**Comment by scoder** [comment]
https://cython.readthedocs.io/en/latest/src/userguide/parallelism.html#compiling

**Comment by Noraboke** [comment]
That did the trick. Thank you! 

Changed `'-fopenmp'` to `'/openmp'`
