### ISSUE TITLE
[ENH] Warn /error when overwriting files

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4177]
**Is your feature request related to a problem? Please describe.**

Quoting from the cython-user's mailing list:

>It's a common gotcha with Cython that new users give their C/C++ code file
> the same name as their .pyx file, and then Cython overwrites the .cpp file
> when it translates the .pyx file. 

**Describe the solution you'd like**

Is this something we can treat as an error: all Cython generated files have "Cython" in their first line (either as `#error` or to say they're Cython generated). We could refuse to overwrite any file that doesn't meet these criteria.

**Describe alternatives you've considered**

Potentially it could be a warning instead? Maybe the `--force` option should cause it to be ignored?

**Comment by scoder** [comment]
Already working in it.
