### ISSUE TITLE
"Key Error" when asyncio.iscouroutinefunction( ) is called more than a fixed number of times on distinct coroutine functions

### ISSUE THREAD

**Issue by HVP1621** [cython/cython#4182]
Hi, I was testing out this patch [here](https://github.com/cython/cython/pull/3427) for some application. I am using the Master branch code. While testing I was faced with "Key Error" after a fixed number of asyncio.iscoroutinefunction() calls on distinct coroutine functions. The following minimal code example can be used to reproduce the above issue:
```python
import asyncio 

async def cb1(msg):
   print("cb1") 
async def cb2(msg):
   print("cb2") 
async def cb3(msg):
   print("cb3") 
async def cb4(msg):
   print("cb4") 
async def cb5(msg):
   print("cb5") 
async def cb6(msg):
   print("cb6") 
async def cb7(msg):
   print("cb7") 
async def cb8(msg):
   print("cb8") 
async def cb9(msg):
   print("cb9") 
async def cb10(msg):
   print("cb10") 
async def cb11(msg):
   print("cb11") 
async def cb12(msg):
   print("cb12") 
async def cb13(msg):
   print("cb13")
async def cb14(msg):
   print("cb14")


def main():
    #asyncio.iscoroutinefunction(cb1)
    #asyncio.iscoroutinefunction(cb1)
    #asyncio.iscoroutinefunction(cb1)
    #asyncio.iscoroutinefunction(cb1)
    asyncio.iscoroutinefunction(cb1)
    asyncio.iscoroutinefunction(cb2)
    asyncio.iscoroutinefunction(cb3)
    asyncio.iscoroutinefunction(cb4)
    asyncio.iscoroutinefunction(cb5)
    asyncio.iscoroutinefunction(cb6)
    asyncio.iscoroutinefunction(cb7)
    asyncio.iscoroutinefunction(cb8)
    asyncio.iscoroutinefunction(cb9)
    asyncio.iscoroutinefunction(cb10)
    asyncio.iscoroutinefunction(cb11)
    asyncio.iscoroutinefunction(cb12)

    asyncio.iscoroutinefunction(cb13)


if __name__ == '__main__':
    main()
```
The compilation was done as follows on Debian Buster with Python 3.7 and gcc (Debian 8.3.0-6) 8.3.0:
```bash
cython -3 cython_bug.py --embed && gcc -ggdb -Os -I /usr/include/python3.7m/ -o cython_bug.o cython_bug.c -lpython3.7m -lpthread -lm -lutil -ldl && ./cython_bug.o
```
The number of checks performed on distinct coroutine functions is 13 which causes the crash. If the last line ```asyncio.iscoroutinefunction(cb13)``` is commented out, there is no error.

Further, if the last line is commented out and the first few commented checks are uncommented, I'm faced with Seg faults sometimes.

Please review the same and suggest what could have gone wrong.

**Comment by da-woods** [comment]
That suggests a reference counting error to me...

**Comment by da-woods** [comment]
I think there should be an incref on marker:

https://github.com/cython/cython/blob/940d80dcd5cbc8d55a0f9348d1a2472e9b8b7121/Cython/Utility/CythonFunction.c#L387-L389

**Comment by HVP1621** [comment]
> I think there should be an incref on marker:
> 
> https://github.com/cython/cython/blob/940d80dcd5cbc8d55a0f9348d1a2472e9b8b7121/Cython/Utility/CythonFunction.c#L387-L389

Hi, I tested the patch for my application and it works perfectly well! Thanks!
