### ISSUE TITLE
[ENH] add support for cross-compiling cython modules using setuptools

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [cython/cython#4184]
Hi,
Is it possible to add support for cross-compiling cython modules using setuptools?

**Comment by da-woods** [comment]
I think you'd be better off making the request to setuptools. Cython just generates .c code (which should be pretty much platform-agnostic) and then defers the compilation entirely to setuptools/distutils. If setuptools can do it then it'll work with cython modules too.
