### ISSUE TITLE
[BUG] Even after importing pdx file struct cdef throws 'is not a type identifier'

### ISSUE THREAD

**Issue by Fhoughton** [cython/cython#4188]
**Describe the bug**
I have created a pdx file and imported it into my program so that I can use cdefs with structs since reading online that seemed to be the solution to cdef with structs as a type throwing 'is not a type identifier' but even after creating and cimporting the file it fails. This seems to be the canonical solution based off http://docs.cython.org/en/latest/src/userguide/sharing_declarations.html#the-cimport-statement

**To Reproduce**
main.py (reduced example):
```cython
import raylib
cimport raylib_structs
cdef raylib_structs.Texture2D texture = LoadTexture("resources/textures/texture.png")
```

raylib_structs.pdx:
```cython
cdef extern from "raylib.h":
	cdef struct Texture:
		unsigned int id        

	ctypedef Texture Texture2D
```

which results in (as well as if extern is removed):
```cython
main.pyx:3:5: 'Texture2D' is not a type identifier
```
**Expected behavior**
Code compiles, texture variable is typed as raylib_structs.Texture2D or if using the original swig bindings without the pdx typed as raylib.Texture

**Environment (please complete the following information):**
 - OS: XUbuntu 64-bit
 - Python version 3.8.6
 - Cython version 0.29.23

**Additional context**
I am using bindings generated by SWIG, using the types directly from the SWIG bindings created the initial error of 'is not a type identifier' as well.

**Comment by scoder** [comment]
>raylib_structs.pdx:
>
>which results in (as well as if extern is removed):
>```cython
>main.pyx:3:5: 'Texture2D' is not a type identifier
>```

Is this the only error you get or are there others?
Is pdx above a typo? It should be pxd.

**Comment by da-woods** [comment]
Also "main.py" won't accept Cython-specific syntax (because it's a .py rather than .pyx)

**Comment by Fhoughton** [comment]
@scoder You're right that it should've been pxd, changing it to such does make the def work (there's a lesson about late night programming here). I'm almost ready to close the issue but the structs still don't seem to operate quite right in that they aren't interopable with those from the SWIG bindings from what I can tell as I get the error:
```cython
Traceback (most recent call last):
  File "main.pyx", line 44, in init main
    cdef raylib_structs.Texture2D texture = LoadTexture("resources/textures/texture.png")
  File "stringsource", line 14, in FromPyStructUtility.__pyx_convert__from_py_struct__Texture
TypeError: Expected a mapping, got Texture
happy@happy-pc:~/Documents/python/Raylib/Kusanag
```
Unless I'm mistaken this is cython throwing the issue but I can't quite get what it means by expecting a mapping (I assume something to do with treating the struct as a python object based on https://github.com/cython/cython/blob/master/tests/run/struct_conversion.pyx#L128 )

@da-woods It should've been pyx that was a type on my part.

**Comment by da-woods** [comment]
LoadTexture is being treated as an arbitrary Python function returning an arbitrary Python object. Cython can convert a `dict`-like Python object (i.e. a mapping) to a struct. But it looks like that isn't what `LoadTexture` returns.

I'm fairly convinced this isn't a Cython bug so I'm going to close the issue. I don't know what swig functions return I'm afraid, but I doubt if Cython knows how to get into those objects by default. The [cython-users mailing list](https://groups.google.com/forum/#!forum/cython-users) might be a good place to try to find someone who does.
