### ISSUE TITLE
[BUG] Heap types created by type specs don't handle GC

### ISSUE THREAD

**Issue by scoder** [cython/cython#4193]
As noted in https://github.com/cython/cython/pull/3611#discussion_r616883983, heap types need to implement the GC protocol, `tp_traverse` and `tp_clear`. When the `CYTHON_USE_TYPE_SPECS` option is set, this applies to all extension types.

See https://bugs.python.org/issue42972

**Comment by da-woods** [comment]
I'm going to do this once https://github.com/cython/cython/pull/5846 is merged. It's slightly simpler than I was giving it credit for - only `tp_traverse` needs to handle `type(self)` (not `tp_clean`) and I think Python does the right thing for classes that *only* need to handle `type(self)`. The only complication is that it's version dependent.
