### ISSUE TITLE
[BUG] Types are being enforced on non-cdef classes

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4196]
**Describe the bug +To Reproduce**

From the users mailing list (https://groups.google.com/g/cython-users/c/R4YQzdIOPSQ):

```
class BaseModel:
    pass

class Field:
    def __init__(self, *args, **kwds):
        pass

class ServiceRow(BaseModel):
    """An individual record."""

    service_id: int = Field(..., description="The ID for the service.", alias="id")
    name: str = Field(..., description="Displayable Name for the service.")
```

Fails at runtime with
```
name: str = Field(..., description="Displayable Name for the service.")
TypeError: Expected str, got Field
```

Generated C code includes
```
if (!(likely(PyString_CheckExact(__pyx_t_2))||((__pyx_t_2) == Py_None) || __Pyx_RaiseUnexpectedTypeError("str", __pyx_t_2))) __PYX_ERR(0, 12, __pyx_L1_error)
```

**Expected behavior**

It's just regular Python code - it shouldn't enforce the types

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.8.9
 - Cython version: 3.0a7

**Additional context**

Bisect suggests b2b81c9c5b87645c3f2a71322ead2ab8c9b7b567 (slightly unsurprisingly).

**Comment by stevenj** [comment]
I can also add that
```
# cython: annotation_typing=False
```
added to the top of the file does not seem to work around the issue either.
