### ISSUE TITLE
[BUG] Not compatible with gcc 11

### ISSUE THREAD

**Issue by cvanelteren** [cython/cython#4218]
**Describe the bug**
After recent update to gcc I am getting missing symbols when trying to load the .so generated by cython. In particular I am getting `throw_bad_array_new_lengthv`. After downgrading to gcc 10.2.0 the error disappears. 

**To Reproduce**
- install gcc 11.1.0
- compile any cython code
- ??
- error

**Expected behavior**
No missing symbols, in particular `throw_bad_array_new_lengthv`

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.9.4
 - Cython version 3.07a

**Comment by scoder** [comment]
Works for me:
https://github.com/cython/cython/runs/2783184152?check_suite_focus=true

Maybe there's something wrong with your local installation?

**Comment by cvanelteren** [comment]
I am confused is this for 0.29 branch? I am running the 3.07a branch atm. 

`gcc (GCC) 11.1.0` 

My setup file contains these flags:

```
compiler = "g++"
optFlag = "-Ofast"
cppv = "20"
flags = (
    f"{optFlag} -march=native -std=c++{cppv} -flto "
    "-frename-registers -funroll-loops -fno-wrapv "
    "-fopenmp-simd -fopenmp -unused-variable -Wno-unused "
    "-D_GLIBCXX_USE_CXX11_ABI=0 "
)```

**Comment by cvanelteren** [comment]
Running a unittest on the package generates

```
ImportError: /home/casper/miniconda3/lib/python3.9/site-packages/plexsim-2.0-py3.9-linux-x86_64.egg/plexsim/models/potts.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```

**Comment by scoder** [comment]
It works with the master/3.0 branch. Haven't tried 0.29.x.

**Comment by cvanelteren** [comment]
There is a similar issue happening on julia
https://github.com/JuliaLang/julia/issues/40703

**Comment by scoder** [comment]
Did you try it without the `-D_GLIBCXX_USE_CXX11_ABI` option?

**Comment by cvanelteren** [comment]
Yes, I have also tried setting the compiler version with `os.environ` but no cigar so far.

**Comment by cvanelteren** [comment]
temporary work-around found!
Setting
```
os.environ["CC"] = "g++-10"
os.environ["CXX"] = "g++-10"
```
and the modules work as expected. I think it is probably a gcc issue judging from the variety of dist having the issue.

**Comment by cvanelteren** [comment]
Not sure if CXX does anything as it didn't work with just that flag.

**Comment by scoder** [comment]
No idea why it works in our CI setup then. Here's the output of the C++ tests run:

https://github.com/cython/cython/runs/2783184194?check_suite_focus=true

You can search the "Run CI" part of the logs for "buildenv" to see our system setup. And it definitely installs and uses gcc 11.1 further up.

**Comment by cvanelteren** [comment]
Yeah could be that the ubuntu version is more stable(?) not sure why they would differ either. I updated last night and just now this issue appeared.

**Comment by da-woods** [comment]
Could this comment be the answer https://github.com/stan-dev/pystan/issues/294#issuecomment-843634871 ?

**Comment by cvanelteren** [comment]
Thanks @da-woods I saw this post too yesterday. I wasn't actually aware that conda packages compilers. The output of my extensions do not include any conda references however. I am looking into whether I can temporarily remove the compiler conda uses.

**Comment by cvanelteren** [comment]
I believe this can be closed as it seems like a conda packed compiler issue - not a cython issue. For other peoples facing this issue look at the work-around above.

**Comment by joshua-cogliati-inl** [comment]
This is a real bug (as pystan's problem also demonstrates), but it is for conda.  Despite reading https://anaconda.org/contact/report I am still not sure where to file it.

**Comment by cvanelteren** [comment]
Another workaround

Setting
`export CPPFLAGS="-D_GLIBCXX_USECXX11_ABI=0"` 
I get it to compile with gcc11 (it uses the old ABI).

**Comment by jjerphan** [comment]
@joshua-cogliati-inl proposed [a work around](https://github.com/stan-dev/pystan/issues/294#issuecomment-870711100) for this problem which works for me.

**Comment by jjerphan** [comment]
@joshua-cogliati-inl proposed [a work around to use the system's shared object instead](https://github.com/stan-dev/pystan/issues/294#issuecomment-870711100).

**Comment by cvanelteren** [comment]
Wouldn't recommend making a symlink for this. Unless you really need the features of gcc11 I would just stick with 10 for now until conda updates its compiler.

**Comment by scoder** [comment]
Closing since it's not something that Cython can (or should) handle.
