### ISSUE TITLE
[BUG] casting PyObject * is broken in pure python mode

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#4243]
**Describe the bug**
For some cases casting `PyObject *` is failing during compilation with error: `Cannot convert 'PyObject *' to Python object`

**To Reproduce**
Following code is compiling with no error:

```cython
from cpython.ref cimport PyObject


foo = {"abc": 123}

cdef PyObject *bar = <PyObject *> foo
```
But in pure python version is failing:
```python
import cython
from cython.cimports.cpython.ref import PyObject

foo = {"abc": 123}

bar: cython.pointer(PyObject) = cython.cast(cython.pointer(PyObject), foo)
```

**Expected behavior**

Pure python mode  should reflect cython language.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.9.2
 - Cython version: master branch

**Comment by scoder** [comment]
This is intended. There is already a ticket where this was discussed. It only applies to module globals, which are Python objects unless explicitly declare()-d as something else.

If you try the same thing inside of a function, it will probably work. I think it's ok to use a function in the documentation.

**Comment by matusvalo** [comment]
Hmm, yes it seems working. I did mistake when I was generelizing bug but it seems that following code snippet fails:
```python
import cython
from cython.cimports.cpython.ref import PyObject

@cython.cfunc
def foo(obj: cython.pointer(PyObject)):
    pass

def main():
    python_dict = {"abc": 123}
    foo(cython.cast(cython.pointer(PyObject), python_dict))
```

compiling fails with following error:
```
$ cython -3a test.py

Error compiling Cython file:
------------------------------------------------------------
...
def foo(obj: cython.pointer(PyObject)):
    pass

def main():
    python_dict = {"abc": 123}
    foo(cython.cast(cython.pointer(PyObject), python_dict))
             ^
------------------------------------------------------------

test.py:12:14: Cannot convert 'PyObject *' to Python object
```

**Comment by matusvalo** [comment]
@scoder can you confirm the case? If yes I will close this issue and create new one with new snippet.

**Comment by da-woods** [comment]
The module globals issue is: https://github.com/cython/cython/issues/3944 (the issue that the the annotations on globals are ignored).

Your function-based version looks like a genuine bug (I think). I don't think it's necessary to create a new issue for it though

**Comment by matusvalo** [comment]
Ok closing this big. Thank you @da-woods !
