### ISSUE TITLE
[BUG] Process finished with exit code -1073740940 (0xC0000374)

### ISSUE THREAD

**Issue by 1138886114** [cython/cython#4246]
**Environment (please complete the following information):**
 - OS: Windows10 20H2 19042.1052 Home
 - Python version = 3.7.0
 - Cython version = 0.28.5
 
D:\git_file_OCR_NLP\cython_test>python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

cython
Requirement already satisfied: cython in e:\anaconda\lib\site-packages (0.28.5)

clusters_segmentImage.pyx code：
```cython
#%%cython --annotate
import numpy as np
cimport cython
cimport numpy as np
from libc.math cimport pow
from libc.math cimport sqrt


cdef struct edges:
    int h
    int w
    double l
    double a
    double b


@cython.boundscheck(False)
@cython.wraparound(False)
def segmentImage(np.ndarray[np.float64_t, ndim=3] lab_image, int K=500, int M=40):
    cdef:
        int height = lab_image.shape[0]
        int width  = lab_image.shape[1]
        int clu_no=0
        int area = height*width
        int S = <int>sqrt(area / K)
        int half_S = <int>(S/2)
        int h=half_S
        int w=half_S
        int height_if = <int>((height-half_S)/S + 0.5)
        int width_if = <int>((width-half_S)/S + 0.5)
        int len_clusters = height_if * width_if


        np.ndarray clusters = np.ndarray((len_clusters,),dtype=[('h', 'i4'),('w', 'i4'),('l', 'f8'),('a', 'f8'),('b', 'f8')])
        edges [:] clu_view = clusters
        double [:,:,::1] lab_view = lab_image.copy()
    with nogil:
        while h < height:
            while w < width:
                clu_view[clu_no].h = h
                clu_view[clu_no].w = w
                clu_view[clu_no].l = lab_view[h,w,0]
                clu_view[clu_no].a = lab_view[h,w,1]
                clu_view[clu_no].b = lab_view[h,w,2]
                clu_no+=1
                w += S
            w = half_S
            h += S
    return clusters 
```
Perform compilation
```
python setup.py build_ext --inplace
```
Test code:
```py
import numpy as np
from skimage import io,color
from clusters_segmentImage import segmentImage


if __name__ == '__main__':
    filename = "../Test_Data/1.jpg"
    rgb = io.imread(filename)
    lab_arr = color.rgb2lab(rgb)
    clusters = segmentImage(lab_arr)
    print("========================================")
    print("clusters",clusters.shape[0]) # output shape = 494
	
```
**Describe the bug**
Error in running test program:
Process finished with exit code -1073740940 (0xC0000374)

The same function of Python code：
print("clusters",clusters.shape[0]) # output shape = 540

I encountered the above problem and found that the output of the code is only half of the Python code with the same function. I don't know how to solve it. Please tell me if there is something wrong with my code. If there is something wrong with my code, please indicate the wrong place. I can improve it. Thank you very much

**Comment by da-woods** [comment]
This looks to me like a bug in your code rather than a Cython bug. Please use the [cython-users mailing list](https://groups.google.com/forum/#!forum/cython-users) for support requests instead of the bug tracker.

A couple of possible hints:

```
cdef struct edges:
```

Possibly wants to be a `packed` struct.

```
@cython.boundscheck(False)
```

This line stops Cython from protecting you from indexing beyond the end of an array. If you remove it then you will likely get an `IndexError` rather than a crash. Make sure you understand the implications of putting this kind of line in - don't just copy-paste it without understanding.
