### ISSUE TITLE
[BUG] Something seems off with Cython.Debugger.Tests.TestLibCython and CythonCompileTestCase

### ISSUE THREAD

**Issue by mattip** [cython/cython#4249]
**Describe the bug**

The instaniation of the `CythonCompileTestCase` here
https://github.com/cython/cython/blob/c74e08a0e4a92ac6bbe3d3b9284eefa685e5c409/Cython/Debugger/Tests/TestLibCython.py#L106-L111

does not seem to match the class's `__init__`
https://github.com/cython/cython/blob/c74e08a0e4a92ac6bbe3d3b9284eefa685e5c409/runtests.py#L917-L923

causing the tests to fail. Or am I missing something simple?

**To Reproduce**
Code to reproduce the behaviour:
```cython
$ python runtests.py -vv --no-capture --failfast
==========================================
ERROR: test_all (Cython.Debugger.Tests.TestLibCython.TestAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matti/oss/cython/Cython/Debugger/Tests/TestLibCython.py", line 173, in setUp
    super(GdbDebuggerTestCase, self).setUp()
  File "/home/matti/oss/cython/Cython/Debugger/Tests/TestLibCython.py", line 106, in setUp
    cython_compile_testcase = runtests.CythonCompileTestCase(
TypeError: __init__() missing 1 required positional argument: 'module_path'

----------------------------------------------------------------------
Ran 224 tests in 4.758s

```

**Expected behavior**

I would expect all the tests on master to pass

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version 3.8.4
 - Cython version HEAD

**Additional context**

I am confused since this seems too simple.

**Comment by mattip** [comment]
The `CythonCompileTestCase` signature goes back to 2014, and the debugger tests to 2011.

**Comment by scoder** [comment]
Thanks for noticing. The class signature is more recent. I broke it myself in 3bd321f17474aafde1bd497163b3e7ba089ee2cc.

**Comment by scoder** [comment]
Fixed in https://github.com/cython/cython/commit/506cd5aab31ae2ed5bda431f5ff63077f8acd074

**Comment by scoder** [comment]
Note that this does not repair the debugger tests per se. It just resolves this (recent) issue.
See https://github.com/cython/cython/issues/1717

**Comment by mattip** [comment]
Right, but a first step to a fix is to get the failure back
