### ISSUE TITLE
[BUG] Cython adds _PyGen_Send on CPython 3.10

### ISSUE THREAD

**Issue by skirpichev** [cython/cython#4250]
E.g. see [this](https://github.com/diofant/diofant/runs/2928888111?check_suite_focus=true) build log:
```

    def test_jn_zeros():
>       assert eq(jn_zeros(0, 4, method='scipy'),
                  [3.141592, 6.283185, 9.424777, 12.566370])

diofant/tests/external/test_scipy.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
diofant/functions/special/bessel.py:697: in jn_zeros
    from scipy.optimize import newton
/opt/hostedtoolcache/Python/3.10.0-beta.3/x64/lib/python3.10/site-packages/scipy/optimize/__init__.py:421: in <module>
    from ._shgo import shgo
/opt/hostedtoolcache/Python/3.10.0-beta.3/x64/lib/python3.10/site-packages/scipy/optimize/_shgo.py:9: in <module>
    from scipy import spatial
/opt/hostedtoolcache/Python/3.10.0-beta.3/x64/lib/python3.10/site-packages/scipy/spatial/__init__.py:107: in <module>
    from . import distance, transform
...
>   from .rotation import Rotation, Slerp
E   ImportError: /opt/hostedtoolcache/Python/3.10.0-beta.3/x64/lib/python3.10/site-packages/scipy/spatial/transform/rotation.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send

/opt/hostedtoolcache/Python/3.10.0-beta.3/x64/lib/python3.10/site-packages/scipy/spatial/transform/__init__.py:19: ImportError
```
This is for CPython 3.10.0-beta.3 and Cython from the git repo.

I though that this was fixed by https://github.com/cython/cython/issues/3876, but, apparently, it's not.

**Comment by scoder** [comment]
Could you confirm that your C file was regenerated when trying the latest master? You can see it from the first line of the file.

**Comment by skirpichev** [comment]
Well, there is no wheels for scipy on CPython 3.10 and no C-files in the git tree (scipy/spatial/transform/) or on PyPI (source).  That's why I expect it was regenerated.  I'll do local tests, however.

**Comment by scoder** [comment]
Ah, sorry – I blatantly misread the "beta 3" as referring to Cython, not CPython, and thought you had tested with two versions.
Still, it seems worth testing that the right Cython version was used also by the SciPy build, and not e.g. one that pip installed just for the build.

**Comment by skirpichev** [comment]
You were right, the "pip install" got the scipy v1.6.1 (instead of the most recent release), which indeed has generated (by Cython 0.29.21) rotation.c.  The git version of scipy seems to be working.

Sorry for noise.
