### ISSUE TITLE
Has anyone compiled PYD in unreal4.26? Can you give a document to explain it[ENH] 

### ISSUE THREAD

**Issue by skyeKing** [cython/cython#4255]
I tried to compile to PYD in unreal, and two things happened.
1.  compile in local 3.7.7, call in unreal, unreal will crash directly. There is no problem using py or PyC files directly
2.  The program will be stuck in the compilation phase if it is directly compiled into PYD by using the built-in python of unreal.
<p>
"""
running build_ext
building 'python file' extension
"""
</p>

**Comment by scoder** [comment]
This seems more a support request than something to discuss on the bug and feature tracker.
Please use the cython-users mailing list instead.
