### ISSUE TITLE
Please backport Python 3.9/3.10 compatibility fixes to the stable branch

### ISSUE THREAD

**Issue by geofft** [cython/cython#4260]
We've found that we need
* afffee895b14c7a736e55f28db8b8a94f865782c for Python 3.9 with `-Wall`
* 6ba0345d98ee9ed0fcdc662be4fc81a7754d5080 for Python 3.10 beta

I'm guessing from #4046 that the intent is for the 0.29.x stable branch to support even 3.10. Can you please backport these to the stable branch?

Happy to get you a pull request if that's helpful, but they're quick - the first one needs a very tiny fix (since it's two `#if`s instead of one on stable) and the second one applies cleanly.

**Comment by scoder** [comment]
Sure. I'll pick the first over, but 6ba0345 is already included in 0.29.22.

**Comment by scoder** [comment]
https://github.com/cython/cython/commit/dba5f6bb9922df044951f64bc889cd0592a3e483
