### ISSUE TITLE
compilation warning

### ISSUE THREAD

**Issue by xuliang-st** [cython/cython#4261]
In function ‘__Pyx__PyBytes_AsDouble_Copy’:
warning: unused variable ‘digit’ [-Wunused-variable]
     char *digit = buffer;

**Comment by da-woods** [comment]
I can't see that in `digit` in the most recent version of that function. What version of Cython are you using?

**Comment by xuliang-st** [comment]
> 我`digit`在该功能的最新版本中看不到这一点。您使用的是哪个版本的 Cython？（即它很可能已经被修复）
Generated by Cython 3.0a6

**Comment by xuliang-st** [comment]
> I can't see that in `digit` in the most recent version of that function. What version of Cython are you using? (I.e. it might well have already been fixed)

Cython 3.0a6

**Comment by scoder** [comment]
If I'm not mistaken, that function was only added in the following release, 3.0a7. It didn't exist before.
Please try the latest release.

**Comment by xuliang-yyds** [comment]
> 如果我没记错的话，该功能仅在以下版本 3.0a7 中添加。它以前不存在。
> 请尝试最新版本。

OK,Thanks~
