### ISSUE TITLE
[BUG] std::string::npos not correctly mapped

### ISSUE THREAD

**Issue by phoerious** [cython/cython#4268]
**Describe the bug**
`libcpp.string.npos` maps to `std::npos`, which doesn't exist and causes a compilation error:
```
error: ‘npos’ is not a member of ‘std’; did you mean ‘fpos’?
```
It should map to `std::string::npos` instead.

Sources:
- https://github.com/cython/cython/blob/master/Cython/Includes/libcpp/string.pxd#L8
- https://www.cplusplus.com/reference/string/string/npos/

Wrong:
```cython
cdef extern from "<string>" namespace "std" nogil:
    size_t npos = -1
```

Correct:
```cython
cdef extern from "<string>" namespace "std::string" nogil:
    const size_t npos
```

**Comment by 0dminnimda** [comment]
This one was [added](https://github.com/cython/cython/commit/a6d44949dba6f873c7257a784033eb926eb38ce5) 10 years ago, perhaps the author did not know about the presence of this in the standard library, or maybe they decided not to hope for an implementation in the standard library and make this constant explicitly -1.

It's just that if the implementation of the standard library uses a different value, the ported code, in theory, may not work.
On the other hand, if someone directly compared npos to -1 (why?), Then the change could break existing code.

Anyway, PR is welcome

**Comment by phoerious** [comment]
Done.
