### ISSUE TITLE
[ENH] C functions should propagate exceptions by default

### ISSUE THREAD

**Issue by scoder** [cython/cython#4280]
**Is your feature request related to a problem? Please describe.**
C functions that do not return Python objects cannot currently propagate exceptions by default but require an explicit `except` clause. In Python code, declared return types default to safe exception propagation instead. Both should behave the same.
```cython
cdef int func():
    raise TypeError  # is not propagated

@cython.cfunc
def pyfunc() -> cython.int:
    raise TypeError  # is propagated

cdef int no_exc_func():
    return 0  # no exception raised

cdef extern from *:
    int no_exc_cfunc()  # no exception expected
```

**Describe the solution you'd like**
C functions should also propagate their exceptions by default.
```cython
cdef int func():
    raise TypeError  # CHANGE: should get propagated as with `except? -1`, the default exception value.

@cython.exceptval(check=False)
cdef int func():
    raise TypeError  # is not propagated

cdef int no_exc_func():
    return 0  # CHANGE: no exception raised, but tested by caller

cdef int explicit_no_exc_func() noexcept:    # <- CHANGE
    return 0  # no exception raised, and not tested by caller

cdef extern from *:
    int no_exc_cfunc()  # unclear - should exceptions also be expected for `extern` functions?
```

Questions:
* non-extern `cdef` functions declared in `.pxd` files should probably be affected, too, since they should match the implementation in the corresponding `.pyx` / `.py` file.
* C functions defined in `cdef extern` blocks are unlikely to benefit from this change. Can we live with keeping them different?

Also see
https://github.com/cython/cython/issues/3580
https://github.com/cython/cython/issues/933

**Comment by da-woods** [comment]
> ```cython
>     raise TypeError  # CHANGE: should get propagated as with `except -1`, the default exception value.
> ```

Presumably `except?-1` (i.e -1 may not be the exception value)

**Comment by scoder** [comment]
This will rarely be used. We could add, say, `except -`, but you don't need syntax as long as there is a way to do it.

**Comment by Chronial** [comment]
> Either we turn the switch and add syntax, or we don't turn the switch for Cython 3.0. I'll update the ticket description.

I would like to point out that despite me nagging I am a strong supporter of this general change and 3.0 definitely seems the right time to this, since it is a non-trivial backwards-compatibility-breaking change.

But I have one more question about the plan: What about the return types (i.e. void and structs) that don't support exception marker values. They would keep their old behavior, or would they default to `except *`?

**Comment by h-vetinari** [comment]
> 
> 
> This will rarely be used. We could add, say, `except -`, but you don't need syntax as long as there is a way to do it.

I have to say I like the `noexcept` suggestion for this much better (and not just because it matches C++). I find `except -` quite cryptic and it relies on a single character that's visually sparse and easy to overlook.

**Comment by shwina** [comment]
Hi @scoder - is this being actively worked on? Otherwise, I'm happy to give it a stab.

**Comment by matusvalo** [comment]
Hi @shwina . I am not aware about anyone working on this. Feel free to pick it. PRs are welcome.

**Comment by scoder** [comment]
Yes, I think the intended behaviour is pretty clear. Let's get some code to discuss, also to see if the behaviour for `extern` declarations feels ok.

I changed the Cython syntax modifier to `noexcept`. It's a context specific thing in the parser and thus won't introduce new keywords.

**Comment by matusvalo** [comment]
Note: Default propagating exception should also help with handling `None` values in `cdef` functions - see discussion [1]: After fixing this issue we should be able check `None` value in cdef functions and support `not None` in cdef functions (except functions with `noexcept` modifier.


[1] https://github.com/cython/cython/pull/4516#discussion_r806116949

**Comment by scoder** [comment]
> Default propagating exception should also help with handling `None` values in `cdef` functions

Hmm, no, this seems unrelated. The `noexcept` modifer has an effect on the return value checking but not on arguments.

**Comment by matusvalo** [comment]
> Hmm, no, this seems unrelated. The noexcept modifer has an effect on the return value checking but not on arguments.

I am sorry, I should be more clear. Currently in Cython we have following limitation (example taken from https://github.com/cython/cython/pull/4516#discussion_r806116949):
1. We are not checking `None` value in cdef classes in pure python mode (In regular python functions `None` value is checked).
```python
@cython.cfunc
def foo(bar: Bar) -> cython.int:
     # here we are not checking if bar is None and hence passing None value here is allowed.
```
2. `not None` keyword is not allowed in cdef functions.
```cython
cdef int foo(Bar bar not None):
    # not None construct is not supported in cdef functions
```
I suppose that both examples are caused because cdef function cannot propagate `TypeError` which is raised during the check of the value. My point is that when this issue is closed, we should be able to support both cases mentioned above since exception will be propagated by default by -1 value.

Both of cases won't be supported after fixing this PR in case of `noexcept` modifier because this modifier is not enabling exception propagation from cdef function.

Does it make sense what I wrote? I hope so. :-)

**Comment by scoder** [comment]
> I suppose that both examples are caused because cdef function cannot propagate `TypeError` which is raised during the check of the value.

No, that's not the reason. For `cdef` functions, it's the caller's responsibility to pass the correct input values in the expected types and all. The function only accepts what it gets. Thus, the caller would have to know that `None` is not allowed here and check for it itself. The function does not have to raise exceptions in this case, because it never validates the input.

Thus: unrelated.

**Comment by matusvalo** [comment]
> No, that's not the reason. For cdef functions, it's the caller's responsibility to pass the correct input values in the expected types and all. The function only accepts what it gets. 

To be honest I still don't understand fully rationale of this and why we cant implement raising `TypeError` similar to regular python functions. But I don't want to clutter this issue with this discussion. My apologies for this off topic discussion. I did not expect that my note will trigger such discussion.

**Comment by scoder** [comment]
[copying this here from [the PR](https://github.com/cython/cython/pull/4670#issuecomment-1072977391), since it belongs into the ticket discussion]

Function pointers seem the biggest open question. As soon as we make a distinction between extern and non-extern functions, we end up with the problem that function pointers need to be able to refer to both. And they seem equally likely to refer to either kind of function, maybe even with a slightly higher chance of pointing to Cython implemented (i.e. non-extern) functions, even though they are a totally C-ish thing.

So you'd end up with code like this:
```cython
cdef extern from "someheader.h":
    int cfunc(int x)

cdef int cdeffunc(int x) noexcept:
    return x + 1

cdef int (*func)(int x) noexcept

func = cfunc
func = cdeffunc
```
and
```cython
cdef extern from "someheader.h":
    int cfunc(int x) except? -1

cdef int cdeffunc(int x):
    return x + 1

cdef int (*func)(int x)

func = cfunc
func = cdeffunc
```
OTOH, if we make both behave the same, then we break pretty much all .pxd files out there, but end up with something more consistent:
```cython
cdef extern from "someheader.h" noexcept:
    int cfunc(int x)

cdef int cdeffunc(int x) noexcept:
    return x + 1

cdef int (*func)(int x) noexcept

func = cfunc
func = cdeffunc
```
It feels like the decision is between "easy to use (in most cases)" and "easy to explain".

(And yes, if we make all variants behave the same, then we must backport the `noexcept` modifier to 0.29.x so that users can write declarations now that still work in 3.0.)

**Comment by da-woods** [comment]
I'm generally in favour of consistency I think. And consistency only adds unnecessary checks - it shouldn't break much. I think the other option is too many unintuitive rules.

One note: an `except *` function pointer should be able to store a `noexcept` function. I'm not sure if it is currently, but it could be made compatible. That suggests that most code should continue to work, even if function others are assumed to need an exception check by default.

**Comment by da-woods** [comment]
One other point: for a Cython-implemented function returning an `int` we can implicitly add `except -1?` (because Cython controls the error code). However for an `extern` function it probably has to be `except *` (because it could use anything as an error code).

So it's dificult to be completely consistent

**Comment by scoder** [comment]
> However for an `extern` function it probably has to be `except *` (because it could use anything as an error code).

I don't think so. The large bulk of `extern` functions will be plain C functions that do not raise exceptions [*]. Those that raise exceptions are probably declared CPython API functions, almost all of which adhere to the `except -1` pattern if they return an `int`. Those few remaining functions out there that raise Python exceptions, that return an `int` and do *not* report the exception case with `-1` should ALWAYS be marked with `except XYZ` explicitly by the users who declare them.

[*] that's also the main reason why `extern` functions may seem special enough to break the rules to make them easier to use. For them, it feels the other way round. If we assign them exception propagation features by default, many users may end up with inefficient code without knowing. In the same way that it's easy to forget to declare exception propagation on `cdef` functions, it's easy to forget to declare *no* exception propagation on blocks of `extern` functions.

**Comment by shwina** [comment]
> It feels like the decision is between "easy to use (in most cases)" and "easy to explain".

Just my 2c: I'm inclined to the latter. Especially given:

> Special cases aren't special enough to break the rules.

**Comment by h-vetinari** [comment]
> [*] that's also the main reason why `extern` functions may seem special enough to break the rules to make them easier to use. For them, it feels the other way round. If we assign them exception propagation features by default, many users may end up with inefficient code without knowing. In the same way that it's easy to forget to declare exception propagation on `cdef` functions, it's easy to forget to declare _no_ exception propagation on blocks of `extern` functions.

I was tempted to agree, but looking closer at the example above, I think the consistency should win out, and that the inefficiency of forgetting the `noexcept` should be solved with announcements, documentation (perhaps even warnings that always show up during a transition period, unless suppressed by a flag) etc.

These functions are still being imported into cython after all, where the project "sets the rules". It's IMO a legitimate desire for cython to to require `noexcept`, and it's equally legitimate to add that requirement in 3.0. Not that it'll be _fun_, but looking at the example, it's IMO abundantly clear what the healthier longterm choice would be.

**Comment by da-woods** [comment]
FWIW I think I'm currently leaning towards "treat extern functions differently (and assume they don't throw)". On the basis that:
* I don't think most people think of a Cython-defined `cdef` function and an extern function as the same thing, so I don't think it'll actually catch too many people out.
* The vast majority of extern functions don't throw (except for the Python C API, and most people use Cython's wrapping of that anyway).
* The people using extern functions that do throw should hopefully mostly know what they're doing and be thinking about this stuff actively ("hopefully" is doing a lot of work in this sentence though)
* It's very, very rare to access a Cython-defined `cdef` function with `cdef extern...` - almost everyone uses `cimport` so that's one less cause for confusion.

I'm not sure that opinion brings us any closer to agreement though.

**Comment by shwina** [comment]
I can only add that if we choose consistency (`extern` function also are assumed to throw by default), it will need a bit of work to explicitly mark a _ton_ of extern functions in the Cython codebase `noexcept` by default. I don't mind doing that, but would like for us to reach a consensus before I try.

For now, I'm treating extern functions as "special" in the PR and attempting to pass tests. I'm close...

**Comment by h-vetinari** [comment]
> FWIW I think I'm currently leaning towards "treat extern functions differently (and assume they don't throw)".
> [...]
> I'm not sure that opinion brings us any closer to agreement though.

Happy to retract my preference; it could well be that I'm falling into the trap of "a foolish consistency".

**Comment by mattip** [comment]
Since we can have cython3 specific pxd files (x.pxd for cython2 and x.cython-3.0.pxd) I think it is OK to make a breaking change.

**Comment by scoder** [comment]
> Since we can have cython3 specific pxd files (x.pxd for cython2 and x.cython-3.0.pxd) I think it is OK to make a breaking change.

So – are you voting for also changing `extern` functions?

I take your argument, although asking everyone to start splitting their .pxd files still seems a bit pushy to me. I'd rather add the `noexcept` marker as a no-op to 0.29.x. And I'd still rather try to avoid it where possible and require it only where necessary.

**Comment by mattip** [comment]
> So – are you voting for also changing extern functions?

I don't think so. @da-woods' arguments are persuasive.

**Comment by scoder** [comment]
I agree with these arguments. And we're still in alpha, so let's use that to gather feedback before the final release.

**Decision:**
- We change to "always propagate with the default exception value" for cdef/cpdef functions implemented in Cython 3.0, unless there is an explicit `except` or `noexcept` clause.
- We keep `noexcept` semantics for `cdef extern` blocks of function declarations (unless they return object types or have an explicit `except` clause).
- We add `noexcept` as a no-op for Cython 0.29.x, so that users can start adding it to their function implementations, if they need it and want their code to be compatible with Cython 3.0.

We also need to update the documentation to reflect this, and to explain the difference for `extern` blocks. Note that `extern` functions that are declared as returning an object type always propagate exceptions anyway, so this needs to be part of the explanation as well. The semantic change only applies to functions returning C types, where it is unclear whether exceptions will be raised or not, but where not propagating them from a Cython implemented function is a common mistake.

**Comment by scoder** [comment]
> Function pointers seem the biggest open question. As soon as we make a distinction between extern and non-extern functions, we end up with the problem that function pointers need to be able to refer to both. And they seem equally likely to refer to either kind of function, maybe even with a slightly higher chance of pointing to Cython implemented (i.e. non-extern) functions, even though they are a totally C-ish thing.

Coming back to this part. I think there are two directions for arguments here:
1) Function pointers are somewhat more likely to refer to Cython implemented functions, and should therefore follow their semantics.
2) Function pointers are declarations and should therefore follow the common behaviour of (`extern`) declarations.

For pragmatic reasons, I'm leaning towards argument 1). Users seem more likely to implement a function and then need a pointer to it, than to point to `extern` functions. I think that should guide the semantics. The remaining cases can be handled with better error messages on assignments that point to the right fix.

Also in the (probably not so common) cases where function pointers need to point to different functions that do and do not propagate exceptions, the now implicit `except?` or `except *` on the pointer type would lead to correct behaviour since it adds a call to `PyErr_Occurred()`. If the pointer is not going to refer to a raising function, then calling through it would now be a little slower, which can be resolved by adding the `noexcept` marker (which, again, we should also allow in Cython 0.29.x). And that would be visible from `cython -a`.

If there are no objections to this, then the decision is to make function pointers behave like Cython implemented functions.

**Comment by da-woods** [comment]
> If the pointer is not going to refer to a raising function, then calling through it would now be a little slower, which can be resolved by adding the `noexcept` marker (which, again, we should also allow in Cython 0.29.x). And that would be visible from `cython -a`.

Yes, although this should be combined with https://github.com/cython/cython/issues/4689 so that we can point to non-raising functions with a raising function pointer.

> For pragmatic reasons, I'm leaning towards argument 1). Users seem more likely to implement a function and then need a pointer to it, than to point to extern functions. I think that should guide the semantics. The remaining cases can be handled with better error messages on assignments that point to the right fix.

I think what is quite common is to implement a Cython function (which'll now raise) and pass it to a C function (which may not be expecting an exception). Therefore...

> If there are no objections to this, then the decision is to make function pointers behave like Cython implemented functions.

No objections, but I think we should add a strongly worded warning for function pointers passed to extern functions that don't have an exception specification. That's potentially somewhere where it has the potential to go wrong and where users should be thinking "what happens to my exception". (I don't think we should warn about the a lack of exception specification anywhere else)

**Comment by aleasto** [comment]
> * We add `noexcept` as a no-op for Cython 0.29.x, so that users can start adding it to their function implementations, if they need it and want their code to be compatible with Cython 3.0.

Debian bullseye, Ubuntu focal and jammy are still not EOL but ship a version of Cython 0.29 that does not understand `noexcept`. As a maintainer of a Cython module how do I make the module compile on all versions?

**Comment by da-woods** [comment]
> Debian bullseye, Ubuntu focal and jammy are still not EOL but ship a version of Cython 0.29 that does not understand `noexcept`. As a maintainer of a Cython module how do I make the module compile on all versions?

Are you concerned about just being able to build the module or users being able to interact with your module via public pxd files?

If it's just building the module the something like setuptools `install_requires` would probably be the right thing to do. With build isolation there's really no reason to build using the platform version of Cython.

If you want users to be able to use pxd files with their platform Cython then you might be able to use versioned pxd files. From the changelog:

> .pxd files can now be [versioned](https://cython.readthedocs.io/en/latest/src/userguide/sharing_declarations.html#versioning) by adding an extension like “.cython-30.pxd” to prevent older Cython versions (than 3.0 in this case) from picking them up

The unversioned pxd file would be used by Cython 0.29.x, while the versioned one would be used by Cython 3. I haven't looked into them specifically for this problem but I think they should be suitable.
