### ISSUE TITLE
[ENH] Allow raising C++ exceptions in pure python 

### ISSUE THREAD

**Issue by 0dminnimda** [cython/cython#4282]
**Is your feature request related to a problem? Please describe.**
Pure python version of
```cython
cdef int spam() except +
```

**Describe the solution you'd like**
Some ideas:
Add `cppcheck` kwarg to `cython.exceptval`, if it's `True`, then this will translate to adding `+` to `except` and if the first argument of `cython.exceptval` is callable then `cppcheck` will be set to `True`(debatable).
Examples:
```python
@cython.cfunc
@cython.exceptval(cppcheck=True)
def spam() -> cython.int
```
->
```cython
cdef int spam() except +
```
---
```python
@cython.cfunc
@cython.exceptval(check=True, cppcheck=True)
def spam() -> cython.int
```
->
```cython
cdef int spam() except +*
```

---

```python
@cython.cfunc
@cython.exceptval(MemoryError)
def spam() -> cython.int
```
->
```cython
cdef int spam() except +MemoryError
```

---

```python
@cython.cfunc
@cython.exceptval(MemoryError, cppcheck=True)
def spam() -> cython.int
```
->
```cython
cdef int spam() except +MemoryError
```

---

And this probably should fail

```python
@cython.cfunc
@cython.exceptval(MemoryError, check=True)
def spam() -> cython.int
```
As this code does

```cython
cdef int spam() except +MemoryError*
```

**Comment by scoder** [comment]
C++ exception handling is only needed in (`extern`) declarations, which should best occur only in .pxd files. I don't think we need this.
