### ISSUE TITLE
[ENH] Allow compile-time definitions in pure python

### ISSUE THREAD

**Issue by 0dminnimda** [cython/cython#4286]
**Is your feature request related to a problem? Please describe.**
Pure python version of 
```cython
DEF replace = "spam"
```

**Describe the solution you'd like**
Suggestions:
#### 1) `cython.declare`-like
```python
cython.def(replace="spam")
```

#### 2) variable annotations
```python
replace: cython.DEF = "spam"
```

**Comment by scoder** [comment]
Similar to #4287, I'd like to postpone this until we find a good reason to do it.

**Comment by 0dminnimda** [comment]
it could actually serve as constant variable

**Comment by 0dminnimda** [comment]
> Similar to #4287

not use a lot?

**Comment by scoder** [comment]
Closing for the same reason as https://github.com/cython/cython/issues/4287#issuecomment-887201623

While this has slightly more use cases than conditional compilation, I don't consider it useful enough to add a Python syntax variant for it.

**Comment by scoder** [comment]
I created https://github.com/cython/cython/issues/4310 to discuss whether this feature can be deprecated and removed completely.

**Comment by 0dminnimda** [comment]
> I don't consider it useful enough to add a Python syntax variant for it.

And also const variables (not in cdef extern)?

**Comment by 0dminnimda** [comment]
@scoder How then can we get similar behavior in pure python?

```cython
DEF F = 112

def main():
    cdef int a[F]
    a[35] = 81321
```

**Comment by 0dminnimda** [comment]
> I don't consider it useful enough to add a Python syntax variant for it.

Can you explain your criteria for "usefulness", please?

I just see it this way: we may not have explicit `IF`s, but if the condition can be met at compile time, this should happen (all variables in the condition must be` DEF`s). If we don't have a way to make a variable a compile-time constant, we also lose all the benefits of compile-time conditions, as well as the ability to set a constant, because, as far as I know, using `DEF` is almost the only way to make compile-time variables.
