### ISSUE TITLE
[ENH][BUG] Allow compile-time conditionals inside `ctypedef` blocks

### ISSUE THREAD

**Issue by leofang** [cython/cython#4291]
I am actually not sure if this counts as a feature request or a bug report...

**Is your feature request related to a problem? Please describe.**
We've had to write ugly codes to handle version-dependent struct changes from external libraries like this (a mini example showing a new struct member) 
```cython
cdef extern from '...' nogil:
    IF CUDA_VERSION > 0:
        ctypedef struct _PointerAttributes 'cudaPointerAttributes':
            int type
            int device
            void* devicePointer
            void* hostPointer
    ELSE:
        ctypedef struct _PointerAttributes 'cudaPointerAttributes':
            int device
            void* devicePointer
            void* hostPointer
```
whereas a far cleaner solution that mimics C `#if ... #endif` macros would simply be
```cython
cdef extern from '...' nogil:
    ctypedef struct _PointerAttributes 'cudaPointerAttributes':
        IF CUDA_VERSION > 0:
            int type
        int device
        void* devicePointer
        void* hostPointer
```
which currently would raise an error (`Expected an identifier, found 'IF'`), so in reality every time the struct layout changes, we have to duplicate the entire `ctypedef` block...

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
I can't think of other alternatives that can be as intuitive as the proposed one...

**Additional context**

**Comment by scoder** [comment]
Note that you don't have to do this at all. Just define the field. As long as you don't use it, Cython won't generate any code for it, and the C compiler will see the actual header file definition in the end.

(Automatic struct-to-dict conversion counts as usage, though, in case you need that.)

**Comment by leofang** [comment]
Thanks, @scoder. What if it's a name change (say `type`with ver < X.Y.Z -> `memType` with ver >= X.Y.Z in my example)? Do I list them both, and access the members in a version-dependent fashion?

The struct-to-dict conversion is interesting, thanks for the tip. Can struct members like `char name[8]` or `int shape[3]` be converted automatically? (I can try it myself later.)

Generally, though, some of these annoying structs are needed to be exposed to the Python land, so I'd say they are used...But if the auto-conversion is powerful enough, maybe we could just dump them through Cython's converter without worrying about the exact members in the struct at all?

**Comment by scoder** [comment]
> Thanks, @scoder. What if it's a name change (say `type`with ver < X.Y.Z -> `memType` with ver >= X.Y.Z in my example)? Do I list them both, and access the members in a version-dependent fashion?

You can do that. In the worst case, you'd have to define a C macro for the access to make sure that the C compiler only gets to see them if they truly exist. But that's trivial given that you can insert verbatim C code in the `cdef extern` block.

Also look at explicit cname overrides (`cdef int type "real_type_c_name"`). They might help in some cases (though probably not in the case above).


> The struct-to-dict conversion is interesting, thanks for the tip. Can struct members like `char name[8]` or `int shape[3]` be converted automatically? (I can try it myself later.)

I think so. If not, that's a bug.


> Generally, though, some of these annoying structs are needed to be exposed to the Python land, so I'd say they are used...But if the auto-conversion is powerful enough, maybe we could just dump them through Cython's converter without worrying about the exact members in the struct at all?

struct-to-dict-to-struct conversion copies all members, necessarily. If a Cython declared member doesn't exist in C, you'll get invalid C code. So that won't help you. If you don't need the conflicting members, or can live with copying them yourself, then you might still get away with declaring a struct without these names (or declaring the struct twice, once with, once without, under different Cython names), and then using the automatic conversion only with the reduced struct.

Looks like this is neither a bug nor a ticket request. If you need more help, please contact the cython-users mailing list.

**Comment by leofang** [comment]
Thanks, @scoder! I've been exploring along the lines of your reply and so far I feel our old way (duplicating `ctypedef` blocks) is still the best workaround. For example,
> If you don't need the conflicting members, or can live with copying them yourself, 

We already copy them in a version-dependent fashion
```cython
cpdef getPtrAttrs(intptr ptr):
    cdef _PointerAttributes attrs
    cdef dict out = {}
    status = cudaPointerGetAttributes(&attrs, <void*>ptr)
    IF VERSION > 123:
        out['type'] = attrs.type
    ELSE:
        out['memType'] = attrs.memType
    # copy all the rest common fields to out, ex:
    # out['device'] = attrs.device
    return out
```
given this usage pattern, I still wonder if it's possible to support my proposed solution to enable a uniform style in both importing and accessing:
```cython
cdef extern from '...' nogil:
    ctypedef struct _PointerAttributes 'cudaPointerAttributes':
        IF VERSION > 123:
            int type
        ELSE:
            int memType
        int device
        void* devicePointer
        void* hostPointer
```
Is there a particular challenge so that this is currently unsupported?

> or declaring the struct twice, once with, once without, under different Cython names

This is functionally no different from the above pattern, though together with auto-conversion it does reduce the code duplication in accessing I think:
```cython
cpdef getPtrAttrs(intptr ptr):
    IF VERSION > 123:
        cdef _PointerAttributes_123 attrs
    ELSE:
        cdef _PointerAttributes_old attrs
    status = cudaPointerGetAttributes(&attrs, <void*>ptr)
    return attrs  # <-- auto-convert!
```
But with my proposal it can be as clean as
```cython
cpdef getPtrAttrs(intptr ptr):
    cdef _PointerAttributes attrs
    status = cudaPointerGetAttributes(&attrs, <void*>ptr)
    return attrs  # <-- auto-convert!
```
which would be something very nice!

**Comment by scoder** [comment]
Could we move this discussion to the cython-users mailing list? There may be others listening who have solved similar issues. A ticket system tends to have a very limited audience.

**Comment by leofang** [comment]
@scoder Can we please reopen this issue for the time being? I think my question
> Is there a particular challenge so that this is currently unsupported?

is still a valid feature request. I will send an email to Cython mailing list to open a discussion later this week, but just in case I dropped the ball. Thanks!

**Comment by da-woods** [comment]
(Just for cross-referencing purposes) this would have been a duplicate of https://github.com/cython/cython/issues/573
