### ISSUE TITLE
[ENH] Add `typeof` in cython's built-ins

### ISSUE THREAD

**Issue by 0dminnimda** [cython/cython#4300]
**Is your feature request related to a problem? Please describe.**
It's weird to have `sizeof` accessible as it, but for `typeof` there's need to use cimports, those are roughly equal in terms of
- use cases 
- amount of use 
- kind

**Describe the solution you'd like**
I would like to have `typeof` to be as accessible as `sizeof`, i.e. no need to use `from cython cimport typeof`

**Comment by robertwb** [comment]
Sizeof is used quite frequently, but typeof is pretty much only for testing. (It is also not a C builtin one would expect to have available in the top-level namespace, and could conflict with the GCC C++ typeof.)

**Comment by 0dminnimda** [comment]
> could conflict with the GCC C++ typeof

Can you please explain it in more detail? I don't get the point

**Comment by robertwb** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Typeof.html (which is distinct from Cython's that returns a string).

**Comment by 0dminnimda** [comment]
> https://gcc.gnu.org/onlinedocs/gcc/Typeof.html (which is distinct from Cython's that returns a string).

Sure, in this implementation it's ambiguous, i myself think of typeof as returning type and not string. (But then maybe we should use this behaviour for typeof? It'll be pretty, i think)

.. well ok, not for type of, i think, such change could break back compatibility, but still, in sone other way

**Comment by robertwb** [comment]
Maybe someday we could implement `typeof` that returns an actual type (e.g. that could be used in a type declaration), but it probably couldn't be the same one (especially if it delegates to an actual typeof call in the C code).

**Comment by 0dminnimda** [comment]
> it probably couldn't be the same one (especially if it delegates to an actual typeof call in the C code)

`ctypeof`? :)

**Comment by robertwb** [comment]
:). 

In any case, I don't think Cython's string-returning `typeof` has either the utility (outside of testing) or general familiarity that C/C++'s builtin `sizeof` operator has, nor merits being promoted to the global namespace. Unless some solid arguments can be made to the contrary, I'm going to go ahead and close this request.

**Comment by 0dminnimda** [comment]
Well, i opened this issue because of my ignorance, i thought `typeof` returns type, so my arguments are not as suitable now.
Unless there's some function that will return type from its string representation there's not a lot of cases for `typeof` to be used in some real code

**Comment by 0dminnimda** [comment]
Tho it's an indication of lack of documentation

**Comment by da-woods** [comment]
I think `typeof` is mainly aimed at Cython testing itself - it's useful when writing test-cases but not really to regular users

**Comment by 0dminnimda** [comment]
> Tho it's an indication of lack of documentation

partial fix #4301
