### ISSUE TITLE
[BUG] Test failure with 0.29.24

### ISSUE THREAD

**Issue by swt2c** [cython/cython#4305]
**Describe the bug**
I'm seeing a test failure with 0.29.24 (perhaps related to 8dee7f9?):
```
======================================================================
ERROR: runTest (__main__.CythonRunTestCase)
compiling (cpp) and running cpp_stl_conversion
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/cython-0.29.24/runtests.py", line 1257, in run
    ext_so_path = self.runCompileTest()
  File "/builddir/build/BUILD/cython-0.29.24/runtests.py", line 931, in runCompileTest
    return self.compile(
  File "/builddir/build/BUILD/cython-0.29.24/runtests.py", line 1178, in compile
    self._match_output(expected_errors, errors, tostderr)
  File "/builddir/build/BUILD/cython-0.29.24/runtests.py", line 1227, in _match_output
    self.assertEqual(None, unexpected)
AssertionError: None != "18:5: Unraisable exception in function 'cpp_stl_conversion.add_strings'."

```

**To Reproduce**
Run test suite.

**Expected behavior**
Tests pass.  :-)

**Environment (please complete the following information):**
 - OS: Linux (Fedora 34 & Rawhide)
 - Python version 3.9.6 & 3.10.0b4
 - Cython version 0.29.24

**Additional context**

**Comment by da-woods** [comment]
I think it just needs https://github.com/cython/cython/commit/9bc0abecb3a08ea13313200a51f1ee26a65e5be3 backporting to the 0.29 branch

**Comment by scoder** [comment]
> I think it just needs [9bc0abe](https://github.com/cython/cython/commit/9bc0abecb3a08ea13313200a51f1ee26a65e5be3) backporting to the 0.29 branch

Done.

I don't think this is worth a critical bug-fix release. It's really just a broken test.
