### ISSUE TITLE
[ENH] Autopopulating richcompare

### ISSUE THREAD

**Issue by 0dminnimda** [cython/cython#4306]
**Is your feature request related to a problem? Please describe.**
We can create directive (off by default) that will automatically populate richcompare if there's way to so this i.e.:
if we have `__eq__` method and `__gt__` then we, first of all, can extrapolate them so we will have `__ne__` as `not __eq__`, and we can push even further, and create `__ge__` as combination of `__eq__ and __gt__`,  `__le__` from from `not __gt__`, and `__lt__` from `not __ge__`

So in the end we can write only 2 methods to get full richcompare

**Describe the solution you'd like**
So if there will be such directive, or maybe better - decorator for class, user can choose to extrapolate full richcompare from several basic methods

**Describe alternatives you've considered**
Obviously, we can manually write each of the 6 methods

**Comment by 0dminnimda** [comment]
and actually there's part that already implemented - `__ne__` from `__eq__`, and vice versa, I think

**Comment by da-woods** [comment]
Something very close to this was implemented recently: https://github.com/cython/cython/commit/f902c26b5516d44e6f41deb815cbfc5f4aa7aaf3

**Comment by 0dminnimda** [comment]
> Something very close to this was implemented recently: [f902c26](https://github.com/cython/cython/commit/f902c26b5516d44e6f41deb815cbfc5f4aa7aaf3)

oh, great
