### ISSUE TITLE
[ENH] Help type checkers find Shadow.pyi

### ISSUE THREAD

**Issue by Bluenix2** [cython/cython#4327]
**Is your feature request related to a problem? Please describe.**
Many static type checkers have issues finding Cython's stubs.
Here is from running mypy on my current project:
```
error: Skipping analyzing "cython": found module but no type hints or library stubs
```
The same issue can be seen when using `import Cython as cython`:
```
error: Skipping analyzing "Cython": found module but no type hints or library stubs
```

**Describe the solution you'd like**
Being able to take advantage of static type checkers when developing.

**Additional context**
Inspecting my installation of Cython, it doesn't appear that Shadow.pyi is included:
![image](https://user-images.githubusercontent.com/38372706/128610271-81d9f237-65fd-4dda-8973-162c5046b559.png)
This could have to do with the issues experienced.

**Comment by scoder** [comment]
Are you using Cython 3.0?

**Comment by 0dminnimda** [comment]
> Are you using Cython 3.0?

If the problem persists after this comment, we could probably add `.pyi's to the typeshed repo .. but it seems to be better to limit the solution to this repo. (moreover, we very likely can)

**Comment by TeamSpen210** [comment]
Cython needs to also include a blank `py.typed` file in the package root, to mark it as directly supplying type hints (see [PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)). Otherwise type checkers will assume the package doesn't support hinting and look for a seperate stubs package or in typeshed.

**Comment by Bluenix2** [comment]
> Are you using Cython 3.0?

Yes, this is from my venv's Shadow.py file:
```py
# cython.* namespace for pure mode.
from __future__ import absolute_import

__version__ = "3.0.0a9"

try:
    from __builtin__ import basestring
except ImportError:
    basestring = str
```

**Comment by Bluenix2** [comment]
> Cython needs to also include a blank `py.typed` file in the package root, to mark it as directly supplying type hints (see [PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)). Otherwise type checkers will assume the package doesn't support hinting and look for a seperate stubs package or in typeshed.

Adding this to my venv I get a lot of errors, mainly about `cython.cclass`, `cython.declare` and `cython.cfunc` as these are not defined in Shadow.pyi that I copied into my venv.

**Comment by 0dminnimda** [comment]
> > Cython needs to also include a blank `py.typed` file in the package root, to mark it as directly supplying type hints (see [PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)). Otherwise type checkers will assume the package doesn't support hinting and look for a seperate stubs package or in typeshed.
> 
> Adding this to my venv I get a lot of errors, mainly about `cython.cclass`, `cython.declare` and `cython.cfunc` as these are not defined in Shadow.pyi that I copied into my venv.

If you define it:
```python
class _EmptyDecoratorAndManager(object):
    def __call__(self, x: _T) -> _T: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

cclass = ccall = cfunc = _EmptyDecoratorAndManager()

def declare(t: Optional[Callable[..., _T]] = ..., value: Any = ..., **kwds: Any) -> Optional[_T]: ...
```
Will this solve your errors?

**Comment by 0dminnimda** [comment]
Keep in mind that this typing is only for the python version, there is no promise from me that the same typing will be relevant for the compiled version.

**Comment by scoder** [comment]
This seems a perfect "first issue" to me. PR welcome that adds the missing type declarations from `Shadow.py` to `Shadow.pyi`.

**Comment by tomaszjezak** [comment]
I'd love to work on this, if it's still relevant.

**Comment by da-woods** [comment]
> if it's still relevant.

Not completely sure - I think we should definitely merge #4335 but I'm not sure how much there is to do beyond that.

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/7ad534376c4d562046a3ae58aa0edd1fa68925c0

**Comment by da-woods** [comment]
@tomaszjezak I think the core issue should be solved now. I definitely don't think Shadow.py is complete - there's been new directives added since the PR was originally written, and and some have become more flexible.
