### ISSUE TITLE
Stackless Python 3.8 uses an unmodified PyFrameObject

### ISSUE THREAD

**Issue by akruis** [cython/cython#4329]
Hi,

Stackless used to have a modified PyFrameObject structure. Recently I was able to refactor the code a bit and now (version 3.8 and up) Stackless uses the same structure as C-Python. Therefore it is no longer necessary to compute the offset of field `f_localsplus` at runtime.

https://github.com/cython/cython/blob/3a0ca192ed497f81c7bee60f13f635c9ac265e72/Cython/Utility/ObjectHandling.c#L2449-L2458

Of course this code still works and is still required for Stackless versions prior to 3.8.

Kind regards
  Anselm

**Comment by da-woods** [comment]
Thanks. This seems like something we can't get rid of until we're ready to drop Stackless <3.8. I'll provisionally tag this as "Cython 3.1" because I think that's when the next round of dropping older versions is scheduled for.

**Comment by scoder** [comment]
I don't think this needs to wait for 3.1. If we make the code conditional on `PY_VERSION_HEX < 3.8`, and start using `offsetof()` again in newer versions, I think that should work. You can't compile a Cython module on 3.8 and expect it to work on 3.7 or earlier, so this seems safe to me.
