### ISSUE TITLE
[ENH] Support for tri-bool types

### ISSUE THREAD

**Issue by Bluenix2** [cython/cython#4334]
**Is your feature request related to a problem? Please describe.**
I would like to store a tri-bool in my class. That is, a type of `bint` that has 3 states: True, False or None.

**Describe the solution you'd like**
Cython could introduce a new `tribint` type (name open for suggestions), that would similarly to `bint` be stored as a C integer but be conveniently converted to True, False or now None.

In Pure Python Mode this could be typed as `Optional[cython.bint]` or the Shadow.py shortcut `cython.tribint`.

Looking at the following example code:
```cython
cdef class Test:
    cdef readonly bint value

    def __init__(self, bint val):
        self.value = val
```
The generated C code has the following struct, meaning that Cython could easily fit this in without enlarging the amount of bits used.
```c
struct __pyx_obj_54_cython_magic_873facacc7630598f8ce75554d0cdb8a3ab7d7b9_Test {
  PyObject_HEAD
  int value;
};
```
I do not know what arrangement would be best, None meaning missing matches nicely with `-1`. But the issue then becomes that `-1` is a common exception value, so `2` may be better fit.

**Describe alternatives you've considered**
I could keep using `bint` where None becomes False, this is acceptable but I would like to keep the information of whether it was determined to be False or simply missing.

**Additional context**
This would be a breaking change, as some may be dependent on None becoming False, therefor I am proposing a new type.

**Comment by da-woods** [comment]
This feels like something that could be solved using an enum (either `cdef` or `cpdef`).

I think the feature falls a little outside of Cython's core focus: it isn't really a faster version of an existing Python feature, and it isn't really a way to wrap an existing C/C++ feature.

It might be nice if it were possible to define custom to/from Python conversion functions though, so you could get the conversion to/from `None` to be automatic.
