### ISSUE TITLE
[BUG] cpp_locals generates broken code for thread local temp variables

### ISSUE THREAD

**Issue by maxbachmann** [cython/cython#4354]
**Describe the bug**
When using cpp_locals(True) in combination with  exception handling inside of a prange, an incorrect assignment is generated. The following code:
```cython
cimport cython
from cython.parallel import prange

cdef extern from *:
    """
    class Test {
    };
    """
    cdef cppclass Test:
        Test() nogil except +

@cython.cpp_locals(True)
cdef test():
    cdef int i
    for i in prange(10, nogil=True):
        var = Test()
```
uses std::optional<Test> to store the variable, while it uses Test to store the thread local variable. This results in an invalid assignment:
```
CYTHON_UNUSED __Pyx_Optional_Type<Test> __pyx_v_var;
__Pyx_Optional_Type<Test> __pyx_t_3;
...
Test __pyx_parallel_temp1;
...
__pyx_t_3 = Test();
__pyx_v_var = std::move((*__pyx_t_3));
...
__pyx_parallel_temp1 = __pyx_v_var;
```
here the last assignment to `__pyx_parallel_temp1` is invalid.

**Expected behavior**
The temporary variable `__pyx_parallel_temp1` should use the type `__Pyx_Optional_Type<Test>` as well.

**Comment by da-woods** [comment]
I'd obviously missed that pranges have their own type of temp. I also wonder if the assignment to parallel_temp should use `std::move` too (although that would need a close look at the context it's used in)

**Comment by maxbachmann** [comment]
> I also wonder if the assignment to parallel_temp should use std::move too (although that would need a close look at the context it's used in)

I wondered this too, since it would help me with my problem from https://github.com/cython/cython/issues/4352.

**Comment by da-woods** [comment]
> > I also wonder if the assignment to parallel_temp should use std::move too (although that would need a close look at the context it's used in)

> I wondered this too, since it would help me with my problem from #4352.

At least on gcc, `lastprivate` implies copy constructable, so I don't think this necessarily helps you. I think the move is still worth generating for efficiency, but it doesn't let you couldn't already do

**Comment by maxbachmann** [comment]
> If you don't use it after the loop (so Cython's lastprivate clause is unnecessary) then it'd probably work to wrap the loop body in a cdef function and call the cdef function in the loop

Yes that's what I do now.
