### ISSUE TITLE
[BUG] Auto-generation of "import_array" not working on recent Numpy

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4396]
**Describe the bug**

In https://github.com/cython/cython/pull/3524 I added auto-generation of `np.import_array` to help users out who'd forgotten to include it themselves. In that I relied on the `NPY_NDARRAYOBJECT_H` header include guard to identify "real" Numpy. In https://github.com/numpy/numpy/commit/6dff0c2f22b58b1d5d397fd8c4ab768a30d10499 they renamed their header include guard, thus breaking the fix.

See https://github.com/scipy/scipy/issues/14732 and related issue https://github.com/cython/cython/issues/4394

**Additional context**

I'll submit a fix (and a more robust set of tests...) fairly shortly

**Comment by seberg** [comment]
Just to be sure, this does not affect any released versions of cython?  Because if it does, I still think we should just modify NumPy back.  Otherwise, there is probably indeed no point.

The SciPy issue uses newer features, but the important part seems only whether this automatic addition calling of `import_array()` is new.

**Comment by da-woods** [comment]
This affects the 3.0 pre-releases only (I don't know if you consider those "real" releases?).

In those we switched the Numpy .pxd files to use the Numpy API rather than looking directly into the `PyArrayObject`. It became obvious that was going to break a lot of user code so we added to automatic call of `import_array` in 3.0 alpha 2. The feature is not in the main 0.29.x releases

**Comment by seberg** [comment]
Ok, so the two features just happened to go hand-in-hand.  Then I think we can indeed ignore this in NumPy: It is OK if alpha releases are broken :).

**Comment by charris** [comment]
>  It became obvious that was going to break a lot of user code

@seberg That might be a consideration. The guard check could be used to warn downstream users to fix things up, then at some point we could remove the NumPy fix.
