### ISSUE TITLE
Best practice variable size array in "pure c/cython"

### ISSUE THREAD

**Issue by apbard** [cython/cython#4404]
Sorry if this is more like a support request than a real issue, but I haven't been able to find the best practice in the documentation. What is the best way to allocate a variable size array in "pure c/cython"?
I have found in the documentation the possibility to use e.g., `np.empty`. But in my case, the function is used in a tight loop and the overhead seems quite high. 
 
Here the sample: A simple function that takes a memory view of a 2D numpy array and returns the `k-th` diagonal.

```cython
# cython: language_level=3
# cython: infer_types=True
# cython: profile=True

import numpy as np
import cython

DTYPE_INT = np.intc

@cython.boundscheck(False)
@cython.wraparound(False)
@cython.nonecheck(False)
cdef int[:] npdiag(int[:,:] arr, int k=0):
    rows = arr.shape[0]
    cols = arr.shape[1]
    if k < 0:
        rows = rows + k
    if k > 0:
        cols = cols - k
    cdef int n = max(min(rows, cols), 0)
    cdef int[:] ret = np.empty(n, dtype=DTYPE_INT)  # slow and "dark yellow" in the annotated html
    if k >= 0:
        for i in range(n):
            ret[i] = arr[i, k + i]
    else:
        for i in range(n):
            ret[i] = arr[i - k, i]
    return ret
```

thanks

**Comment by 0dminnimda** [comment]
1. Yeah, we have cython-users mailing list. It have bigger audience and it's the place for support requests.  So the next time please consider that over GitHub issues.
2. `malloc`?
You probably need to take a look at [Memory Allocation](https://cython.readthedocs.io/en/latest/src/tutorial/memory_allocation.html)

**Comment by 0dminnimda** [comment]
If you want to use c arrays then [primes](https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html?highlight=Array#primes) is a good example

**Comment by apbard** [comment]
> 
> 
>     1. Yeah, we have cython-users mailing list. It have bigger audience and it's the place for support requests.  So the next time please consider that over GitHub issues.
> 
ok, thanks

>     2. `malloc`?
>        You probably need to take a look at [Memory Allocation](https://cython.readthedocs.io/en/latest/src/tutorial/memory_allocation.html)

the "issue" with malloc is that you have to take care of deallocate memory elsewhere. 
the "issue" with plain c arrays is that they can't be dynamic. I have seen that in the example you cited a buffer of a fixed size is used that may not applicable in a general case. 

I'll look at cpp `vector` then!
