### ISSUE TITLE
[BUG] segfault on pandas with 3.0a9

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#4409]
Building pandas master (which works with cython 0.29.x) with the 3.0a9 I'm getting a segfault in https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/hashtable_func_helper.pxi.in#L110

lldb is pointing me towards a `__Pyx_INCREF` call:

```
frame #1: 0x000000011da6ef72 hashtable.cpython-39-darwin.so`__pyx_pw_6pandas_5_libs_9hashtable_73__pyx_fuse_12duplicated [inlined] __pyx_f_6pandas_5_libs_9hashtable_duplicated_object(__pyx_v_values=0x0000000000000000, __pyx_optional_args=<unavailable>) at hashtable.c:101383 [opt]
   101380	 *         raise ValueError('keep must be either "first", "last" or False')
   101381	 * 
   101382	 */
-> 101383	  __Pyx_INCREF(__pyx_v_keep);
   101384	  __pyx_t_2 = __pyx_v_keep;
   101385	  __pyx_t_9 = (__Pyx_PyUnicode_Equals(__pyx_t_2, __pyx_n_u_last, Py_NE)); if (unlikely((__pyx_t_9 < 0))) __PYX_ERR(3, 1504, __pyx_L1_error)
   101386	  if (__pyx_t_9) {
```

Not sure if this means anything, but sublimetext's syntax highlighting seems to stop about 60k lines before this

**Comment by jbrockmendel** [comment]
`pytest pandas/tests/libs/`

**Comment by jbrockmendel** [comment]
Awesome, looking forward to trying it out again.

**Comment by jbrockmendel** [comment]
> I did have a go at trying to run through the Pandas test-suite with this fix but unfortunately "hypothesis" outsmarted me (so nothing useful to report...)

i just tried running the tests using cython master and am getting the same segfaults from https://github.com/cython/cython/issues/4409#issuecomment-944387175

**Comment by da-woods** [comment]
For me latest Cython master+latest Pandas master and the code in the comment https://github.com/cython/cython/issues/4409#issuecomment-944387175 seems to work fine.

I can't get the pandas tests to run at all - running `pytest pandas/tests/libs` just gives me:

```
ImportError while loading conftest '<path>/pandas/conftest.py'.
pandas/conftest.py:489: in <module>
    "datetime": tm.makeDateIndex(100),
pandas/_testing/__init__.py:364: in makeDateIndex
    dr = bdate_range(dt, periods=k, freq=freq, name=name)
pandas/core/indexes/datetimes.py:1172: in bdate_range
    return date_range(
pandas/core/indexes/datetimes.py:1061: in date_range
    dtarr = DatetimeArray._generate_range(
pandas/core/arrays/datetimes.py:448: in _generate_range
    values = np.array([x.value for x in xdr], dtype=np.int64)
pandas/core/arrays/datetimes.py:448: in <listcomp>
    values = np.array([x.value for x in xdr], dtype=np.int64)
pandas/core/arrays/datetimes.py:2548: in generate_range
    start = offset.rollforward(start)
pandas/_libs/tslibs/offsets.pyx:639: in pandas._libs.tslibs.offsets.BaseOffset.rollforward
    dt = dt + type(self)(1, normalize=self.normalize, **self.kwds)
E   TypeError: unsupported operand type(s) for +: 'Timestamp' and 'pandas._libs.tslibs.offsets.BusinessDay'
```

so I don't think I can investigate this myself.

**Comment by jbrockmendel** [comment]
Good point, the branch I've been using to try out cython3 implements `__radd__`, `__rsub__`, and `__rmul__`: https://github.com/jbrockmendel/pandas/tree/cy3

**Comment by da-woods** [comment]
So running `pytest pandas/tests/libs` on your cy3 branch I get:

```
============================================= test session starts ==============================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: <path>/pandas, configfile: pyproject.toml
plugins: cython-0.1.1.post0, instafail-0.4.2, xdist-2.4.0, hypothesis-6.27.2, forked-1.3.0, asyncio-0.16.0, cov-3.0.0
collected 461 items                                                                                            

pandas/tests/libs/test_hashtable.py ..................................................................................................................................................................................................................................................................................................................................................................................................................................................
pandas/tests/libs/test_join.py .................
pandas/tests/libs/test_lib.py ..........

------------------ generated xml file: <path>/pandas/test-data.xml -------------------
============================================= slowest 30 durations =============================================
0.01s call     pandas/tests/libs/test_hashtable.py::TestHashTable::test_unique[True-Int32HashTable-int32]
0.01s teardown pandas/tests/libs/test_lib.py::test_no_default_pickle
0.01s call     pandas/tests/libs/test_hashtable.py::TestHashTable::test_unique[True-Int8HashTable-int8]

(27 durations < 0.005s hidden.  Use -vv to show these durations.)
============================================= 461 passed in 1.06s ==============================================
```

i.e. it looks fine. Are you sure that all the .pyx files have been rebuilt with the new version of Cython? It only looks at the file modification time and not the Cython version when deciding whether to rebuild, so if Cython's changed and the file hasn't then it won't recythonize.

**Comment by jbrockmendel** [comment]
> Are you sure that all the .pyx files have been rebuilt with the new version of Cython?

Did `python setup.py clean` before re-building.  In a fresh virtualenv, with cython installed from source.  `cython --version` shows "3.0.0a9"; is it possible I somehow installed the released version and not actually master?

**Comment by da-woods** [comment]
My best suggestion would be to find out where Cython's installed (with `import cython; print(cython.__file__)`) and then go look and see if you can find the changes in https://github.com/cython/cython/pull/4413/files. But I don't know. I'm personally fairly convinced it is fixed, but that doesn't help you too much...

**Comment by jbrockmendel** [comment]
Looks like I've got the right version, so it's a mystery.  I'll try on a different platform next week.
