### ISSUE TITLE
[BUG] npy_clongdouble element access inconsistent with other complex types.

### ISSUE THREAD

**Issue by matthew-brett** [cython/cython#4438]
When a complex array has type `npy_complex256` (on 64-bit) or `npy_clongdouble`, indexing for an element returns a dict with keys `real` and `imag`.  All other complex types generate the complex value itself, and not a dict.

Consider the following Cython file:

```
import numpy as np
cimport numpy as cnp


def one_long_double():
    cdef:
        cnp.ndarray[cnp.npy_longdouble] output

    output = np.array([1], dtype=np.longdouble)
    print(output[0])


def one_c128():
    cdef:
        cnp.ndarray[cnp.complex128_t] output

    output = np.array([1 + 1j], dtype=np.complex128)
    print(output[0])


def one_c256():
    cdef:
        cnp.ndarray[cnp.npy_complex256] output

    output = np.array([1 + 1j], dtype=np.complex256)
    print(output[0])


def one_clong_double():
    cdef:
        cnp.ndarray[cnp.clongdouble_t] output

    output = np.array([1 + 1j], dtype=np.clongdouble)
    print(output[0])


def one_long_double_complex():
    cdef:
        cnp.ndarray[long double complex] output

    output = np.array([1 + 1j], dtype=np.clongdouble)
    print(output[0])


print('long double')
one_long_double()
print('c128')
one_c128()
print('c256')
one_c256()
print('clongdouble')
one_clong_double()
print('long double complex')
one_long_double_complex()
```

Code at: https://github.com/matthew-brett/cyext

This gives output:

```
long double
1.0
c128
(1+1j)
c256
{'real': 1.0, 'imag': 1.0}
clongdouble
{'real': 1.0, 'imag': 1.0}
long double complex
(1+1j)
```

I think this shows that internally, Cython interprets the elements in `complex256` and (equivalently) `clongdouble` as dicts, whereas this not true for other complex data types, nor for the cdef of the same thing, using `long double complex`.

This seems confusing to me - and specifically, it will require some odd workarounds in Scipy code when using the `np.clongdouble` type.  Is it intended?   Is there an easy workaround to get the complex value by indexing, rather than the dict?

**Comment by matthew-brett** [comment]
I notice too that Cython also returns a dict with:

```
def one_np_c128():
    cdef:
        cnp.ndarray[cnp.npy_complex128] output

    output = np.array([1 + 1j], dtype=np.complex128)
    print(output[0])
```

That is - it seems to treat the `npy_complex*` form of the data type as containing dicts, and the `complex*_t` types as containing complex values, except for `clongdouble_t`, which it always treats as containing dicts.

**Comment by da-woods** [comment]
The definitions are at https://github.com/numpy/numpy/blob/main/numpy/__init__.cython-30.pxd (Cython no longer maintains the Numpy pxd files itself)

Without the `_t` the definitions are like:
```
ctypedef struct npy_complex128:
        double real
        double imag
```

While with the `_t`:
```
ctypedef double complex complex128_t
```

So I'd say this is probably working as intended (although I don't know the Numpy complex types enough to know why that is)

**Comment by matthew-brett** [comment]
Aha - yes - thanks for investigating.  I'll post over at Numpy ...
