### ISSUE TITLE
[bug] __qualname__ unavailable at class scope

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4447]
I'm here because support for `__qualname__` is missing in Cython when used with Python 3 (3.8.9, for sure), while running the code natively works properly.  E.g.:

```
#!/usr/bin/env python3
#cython: language_level=3

class foo():
  print("    __name__ =", __name__)
  print("__qualname__ =", __qualname__)

class bar():
  print("    __name__ =", __name__)
  print("__qualname__ =", __qualname__)

```
yields this compilation error:
```
debugCython2.pyx:7:28: undeclared name not builtin: __qualname__
```
instead of:
```
    __name__ = __main__
__qualname__ = foo
    __name__ = __main__
__qualname__ = bar
```

_Originally posted by @RichardFoo in https://github.com/cython/cython/issues/2773#issuecomment-960363677_

Version
----------

Python 3.8.12
Current Cython master

Notes
--------

`foo.__qualname__` is set correctly, but unqualified `__qualname__` is not looked up right when evaluating the class body

**Comment by RichardFoo** [comment]
Thanks for the clarification / bug report and quick response.

Apparently, I'm very alone in this usage of `__qualname__` since it hasn't been reported before now, but I find it extremely handy (e.g., classes self-registering for callbacks automatically when their module is included).  Here's to hoping the fix is easy and finds its way into the next release cycle.

**Comment by da-woods** [comment]
It's probably just a case of declaring `__qualname__` in the class scope in the same way that `__name__` etc are declared in the module scope - https://github.com/cython/cython/blob/b5f81f5e900922356ee7aeedf78a54fa96f85c71/Cython/Compiler/Symtab.py#L1272-L1274

**Comment by RichardFoo** [comment]
I've poked around the Symtab.py file, and while this may be simple for a project maintainer it's much less obvious to an outsider where this fix needs to be applied.  There seems to be a base ClassScope object, plus derivatives for Python, C, and C++.  None of them have a structure similar to the referenced ModuleScope that might be an obvious place to tweak.

Are you suggesting that in, say PyClassScope, an init() should be created with the command self.declare_var(EncodedString('__qualname__'), py_object_type, None)

What would it take to get this "quick fix" some attention?  I'm not above bribery.  ;-)

**Comment by da-woods** [comment]
I had a go at the quick fix near the time this was reported and couldn't easily make it work so it's probably a little more complicated than I originally thought. I doubt it's impossible of course, but at the time the difficulty seemed higher than my level of interest in it.
