### ISSUE TITLE
[ENH] Setting __doc__ attribute of properties

### ISSUE THREAD

**Issue by gentlegiantJGC** [cython/cython#4466]
**Is your feature request related to a problem? Please describe.**
I am trying to dynamically set method/property docstrings to pull the methods from another class.
I have so far managed normal methods and static methods (which need setting via `__func__.__doc__`)

The issue I currently have is properties where apparently the `__doc__` attribute is read only.
I don't know if this is fixable on your end or if this is a python issue you are constrained by.

This code gives the compile error `'test' is not a constant, variable or function identifier`. I think for some reason it just isn't defined at this point. This might be a mechanic of the property decorator that I don't understand
```cython
cdef class Cls:
    @property
    def test(self):
        return "val"
    test.__doc__ = "docstring"
```

Taking the doc into the module scope gives a runtime error.
`AttributeError: attribute '__doc__' of 'getset_descriptor' objects is not writable`
```cython
cdef class Cls:
    @property
    def test(self):
        return "val"
Cls.test.__doc__ = "docstring"
```

Ideally there would be some mechanism of setting the doc attribute like can be done in normal python.

**Comment by da-woods** [comment]
I suspect this is a Python limitation and so is unfixable - `cdef class` properties are implemented in an optimized direct way that imposes more restrictions that a regular Python property.

My best suggestion would be to force a call to the Python property function instead:

```
totally_not_property = property

cdef class C:
    @totally_not_property
    def something(self):
        ...

    # or
    something_else = property(some_func)
```

I can't remember right now if either of these are expected to work on `cdef class`es but it's something to try anyway.

**Comment by scoder** [comment]
> I suspect this is a Python limitation and so is unfixable

"unfixable" by us, not by the CPython project. I can't see a semantic reason why such a docstring should not be changed.

Note, though, that the docstring is tied to the property. If you're reusing descriptor objects, changing the docstring would change it everywhere that same object is used.

**Comment by gentlegiantJGC** [comment]
Okay. The equivalent can be done in standard python but I assume that uses a different thing.

**Comment by da-woods** [comment]
>  I assume that uses a different thing.

No - properties of `cdef class` are implemented using the [`tp_getset` structure](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_getset) in the Python C API so the limitation is with that.
