### ISSUE TITLE
[BUG] Typing an attribute to float in an __init__ makes slearn "clone" method fail on compiled version.

### ISSUE THREAD

**Issue by ElVynz** [cython/cython#4469]
Hello Everyone,

I hope i'm the right place for this bug,  as I have very little experience with cython.
While trying to apply cython on my code, I encountered a problem with sklearn "clone" method. This seems to be due to some variable "disapearing" in the `__init__` method when a variable is typed as float. I haven't found any similar bug reported elsewhere, so I made a minimal code example so that everyone can reproduce the bug.

**To Reproduce**

I used the basic tutorial from https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html to generate an example that reproduces the bug.

The following compilation produces unexpected results at runtime on 0.29.24 :

helloworld.pyx
```cython

from sklearn.base import clone, BaseEstimator, TransformerMixin
import numpy as np


class MyTransform(BaseEstimator, TransformerMixin):
    def __init__(self, var_float: float = 0.01):
        self.var_float = var_float

    def transform(self, X: np.ndarray):
        return X

    def fit(self, X):
        return self

    def _more_tags(self):
        return {"no_validation": True, "stateless": True}

    def __sklearn_is_fitted__(self):
        """Return True since Functors are stateless."""
        return True


X = np.random.randn(100, 10)
my_transform = MyTransform()
cloned_transform = clone(my_transform)
new_X = my_transform.fit_transform(X)

print("Hello World")
```

setup.py (unchanged)
```
from setuptools import setup
from Cython.Build import cythonize

setup(ext_modules=cythonize("helloworld.pyx"))
```

**Expected behavior**
Like in the basic tutorial, this should print "Hello World" when calling `import helloworld`

Instead, i get `RuntimeError: Cannot clone object MyTransform(), as the constructor either does not set or modifies parameter var_float`

The python code works fine when not compiled through cython

**Important Additional information !**

If var_float is no longer typed as float, then the resulting compiled code works just fine

**Environment :**
 - OS: Windows, Linux
 - Python version : 3.8.11
 - Cython version : 0.29.24

**Comment by da-woods** [comment]
It's a bug in sklearn - https://github.com/scikit-learn/scikit-learn/blob/74016abcdffe67cdc58fc326c58fb5033371d96b/sklearn/base.py#L91 - they do an "is not" check. Since typing the variable as float involves unboxing the Python value to a C float this check can never pass.

If you don't intend for Cython to use your annotations then turn the annotation_typing directive off.
