### ISSUE TITLE
[BUG] inspect.Parameter's property annotation error

### ISSUE THREAD

**Issue by luolingchun** [cython/cython#4491]
**Describe the bug**
I'm using `inspect.Parameter`'s property `annotation `, A `string` was returned, but a `function` was expected

**To Reproduce**
compile `test.py` to `test.cp38-win_amd64.pyd`
test.py:
```cython
from pydantic import BaseModel, Field


class A(BaseModel):
    a: int = Field(..., description="aaa")


def test2(a, b):
    print('test2', a, b)


def test3(func: test2, a: A):
    print(func, a)
```

endpoint function, main.py:
```python
import inspect
from test import test3

signature = inspect.signature(test3)
parameters = signature.parameters
print(parameters)
func = parameters.get('func').annotation # test2
func(1, 2)
```
output in python:
```python
OrderedDict([('func', <Parameter "func: <function test2 at 0x00000225280F7EE0>">), ('a', <Parameter "a: test.A">)])
test2 1 2
```
output in cython, i got an wrong type ("func: 'test2'" and "a: 'A'") :
```python
OrderedDict([('func', <Parameter "func: 'test2'">), ('a', <Parameter "a: 'A'">)])
Traceback (most recent call last):
  File "D:/workspace/test/test_cython/build/lib.win-amd64-3.8/main.py", line 11, in <module>
    func(1, 2)
TypeError: 'str' object is not callable
```

**Expected behavior**

I want `function` or `class` but not a `string`.
```python
OrderedDict([('func', <Parameter "func: <function test2 at 0x00000225280F7EE0>">), ('a', <Parameter "a: test.A">)])
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.5
 - Cython version: cython==3.0.0a9

**Comment by da-woods** [comment]
We're currently using PEP563 style annotations (i.e. what you get with `from __future__ import annotations`) so this is expected.
