### ISSUE TITLE
warning: division by zero [-Wdiv-by-zero],error: enumerator value for '__pyx_check_sizeof_voidp' is not an integer constant

### ISSUE THREAD

**Issue by tiredfriut** [cython/cython#4492]
I'm trying to use Cython to convert. py files into. c files and make. c files compile and run independently.
The contents of the. py file is:
`print("hello")`
I used 
`cython hello.py --embed`
to get the .c file.

Then,
`gcc hello.c -I C:......\Python\Python310\include -L C:......\Python\Python310\libs\python310.lib -fPIC -DMS_WIN64`
to complie, but I got:

```
hello.c:203:41: warning: division by zero [-Wdiv-by-zero]
     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
                                         ^
hello.c:203:12: error: enumerator value for '__pyx_check_sizeof_voidp' is not an integer constant
     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
```

In fact, I have looked at several similar problems and tried their solutions,#2670,#3405, which are not valid for me. Maybe I missed something. Can someone remind me?

**Comment by da-woods** [comment]
Please ask support questions on the Cython-users mailing list, not the bug tracker. This is not a bug - it's a check that your environment is correctly set up working correctly.

**Comment by scoder** [comment]
Duplicate of https://github.com/cython/cython/issues/3405
