### ISSUE TITLE
problem with jupyter notebook

### ISSUE THREAD

**Issue by dentistfrankchen** [cython/cython#4502]
Hi guys,
Now i am using the %%cython magic command to compile my cython package.

I found that automatically the pyd file goes to the .ipython\cython folder, how can i set it to another folder?

What arguments should I pass to the magic command?

**Comment by da-woods** [comment]
please use the Cython-users mailing list for support questions rather than the bug tracker

**Comment by dentistfrankchen** [comment]
@scoder I am a beginner with cython. Now I am working with my team in China(Due to the covid-19 pandemic, I can not go back to US), so there's some limit for me using the google website. Can you add a channel on github for feedback?
