### ISSUE TITLE
[BUG] Pure Python mode does not support memoryviews.

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#4505]
**Describe the bug**
Pure python mode does not support memoryviews.

**To Reproduce**
Consider following code snippets:

* cython
```cython
from cpython.array cimport array
cdef array a = array('i', [1, 2, 3])
cdef int[:] ca = a

print(ca[0])
```

* pure python
```python
import cython
from cython.cimports.cpython.array import array
a: array = array('i', [1, 2, 3])
ca: int[:] = a

print(ca[0])
```

The snippets generates following C code:

* cython
```
+4: cdef int[:] ca = a
  __pyx_t_4 = __Pyx_PyObject_to_MemoryviewSlice_ds_int(((PyObject *)__pyx_v_10safe_usage_a), PyBUF_WRITABLE); if (unlikely(!__pyx_t_4.memview)) __PYX_ERR(0, 4, __pyx_L1_error)
  __PYX_XCLEAR_MEMVIEW(&__pyx_v_10safe_usage_ca, 1);
  __pyx_v_10safe_usage_ca = __pyx_t_4;
  __pyx_t_4.memview = NULL;
  __pyx_t_4.data = NULL;
```

* pure python

```
+4: ca: int[:] = a
  __Pyx_GetModuleGlobalName(__pyx_t_2, __pyx_n_s_a); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 4, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_2);
  if (PyDict_SetItem(__pyx_d, __pyx_n_s_ca, __pyx_t_2) < 0) __PYX_ERR(0, 4, __pyx_L1_error)
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
```

Cython version correctly uses memoryview, but pure python just create assignment. 

**Expected behavior**

Pure python mode should create memoryview as Cython language.

**Environment (please complete the following information):**
 - OS: macOS
 - Python version: Python 3.9.7
 - Cython version: Master

**Comment by da-woods** [comment]
I think this is a duplicate of: https://github.com/cython/cython/issues/3944 - we don't use annotations at global scope, mainly because they change the visibility of the variables from outside Cython. I think if you try it as a function argument it'll recognise memoryviews

**Comment by matusvalo** [comment]
> I think this is a duplicate of #3944 - we don't use annotations at global scope

I confirm :-/. I forgot about this limitation of pure mode :-/. Closing this issue.
