### ISSUE TITLE
[BUG] Function pointer assignment doesn't work

### ISSUE THREAD

**Issue by pitrou** [cython/cython#4513]
I have the following definitions:
```cython

cdef cppclass CCSVInvalidRow" arrow::csv::InvalidRow":
    int32_t expected_columns
    int32_t actual_columns
    int64_t number
    c_string text

ctypedef enum CInvalidRowResult" arrow::csv::InvalidRowResult":
    CInvalidRowResult_Error" arrow::csv::InvalidRowResult::Error"
    CInvalidRowResult_Skip" arrow::csv::InvalidRowResult::Skip"

ctypedef CInvalidRowResult PyInvalidRowCallback(object,
                                                const CCSVInvalidRow&)
```

Then:
```cython

cdef CInvalidRowResult _handle_invalid_row(
        handler, const CCSVInvalidRow& c_row) except CInvalidRowResult_Error:
    ...
```

And finally:
```cython
        cdef CInvalidRowResult (*cb)(object, const CCSVInvalidRow&)
        cb = _handle_invalid_row
```

... which fails compiling with this message:
```
Error compiling Cython file:
------------------------------------------------------------
...
        self._invalid_row_handler = value

        cdef CInvalidRowResult (*cb)(object, const CCSVInvalidRow&)
        cb = _handle_invalid_row
            ^
------------------------------------------------------------

pyarrow/_csv.pyx:430:13: Cannot assign type 'CInvalidRowResult (object, const CCSVInvalidRow &) except  arrow::csv::InvalidRowResult::Error' to 'CInvalidRowResult (*)(object, const CCSVInvalidRow &)'
```

I tried other possibilities (using `&_handle_invalid_row`, passing the result value as a pointer...) and did not manage to get it to work.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version 3.9.7
 - Cython version 0.29.26

**Comment by scoder** [comment]
> ```cython
> ctypedef enum CInvalidRowResult" arrow::csv::InvalidRowResult":
>     CInvalidRowResult_Error" arrow::csv::InvalidRowResult::Error"
>     CInvalidRowResult_Skip" arrow::csv::InvalidRowResult::Skip"

These are integers?

The following two signatures are actually incompatible due to the `except` return value:

> ```cython
> cdef CInvalidRowResult _handle_invalid_row(
>         handler, const CCSVInvalidRow& c_row) except CInvalidRowResult_Error:
> ```
> ```cython
>         cdef CInvalidRowResult (*cb)(object, const CCSVInvalidRow&)
>         cb = _handle_invalid_row
> ```

Here, you are trying to assign a function that returns an exception value to a function pointer that does not declare one. That means that if you call the function through the function pointer, then the caller will not know about the exception value and cannot propagate exceptions. This is a dangerous bug in your code and Cython refuses to let it pass. You need to declare the except value also on the function pointer type, or make use Cython's type inference to avoid the declaration all together.

**Comment by pitrou** [comment]
This is weird as in another part of the code it compiles fine with a similar pattern (mismatching `except`):
```cython

ctypedef c_bool CallbackEquals(object, const CFileSystem&)

cdef cppclass CPyFileSystemVtable "arrow::py::fs::PyFileSystemVtable":
    function[CallbackEquals] equals

cdef c_bool _cb_equals(handler, const CFileSystem& c_other) except False:
    ...
```

and then:
```cython
        cdef:
            CPyFileSystemVtable vtable

        vtable.equals = _cb_equals
```

**Comment by scoder** [comment]
> ```cython
> ctypedef c_bool CallbackEquals(object, const CFileSystem&)
> 
> cdef cppclass CPyFileSystemVtable "arrow::py::fs::PyFileSystemVtable":
>     function[CallbackEquals] equals
> ```

But this isn't declaring `equals` with type `CallbackEquals`, it declares it with type `function[CallbackEquals]`, which, from the point of view of Cython, is this C++ type:
https://github.com/cython/cython/blob/008bc53c45d1131d0eedf5c1fe276f5808911681/Cython/Includes/libcpp/functional.pxd#L3-L15
Note the wide range of supported assignment types. There's basically no type checking at all going on here. Anything that qualifies as a pointer type will be accepted.

I'm not saying that that's a good thing. My guess is rather that the original contributor wanted to get the `function` type working with not too many restrictions, because tightening the type checks in Cython always risks rejecting some kind of valid C++ construct. And most incorrect usage will later be rejected by the C++ compiler anyway.

In this case, the unfortunate effect is that we allow something that only Cython can (and should) reject, not C++.

**Comment by pitrou** [comment]
Hmm, I see. Well, I've switched to `function[...]` to fix the assignment issue :-)
