### ISSUE TITLE
[BUG] postincrement in C++ handled incorrectly

### ISSUE THREAD

**Issue by maxbachmann** [cython/cython#4535]
**Describe the bug**
In Cython both `cython.operator.preincrement` and `cython.operator.postincrement` are handled as `preincrement`.  However in C++ these have two different operators (see https://en.cppreference.com/w/cpp/language/operators):

|Expression | As member function |
|----------------|----------------------------|
| `@a`            | (a).operator@()        |
| `a@`            | (a).operator@(0)      |

**To Reproduce**
Since both operators are treated as `@a` the following code does not compile
```cython
cimport cython

cdef extern from "*":
    cdef cppclass example:
        example operator++(int)

def test():
    cdef example a
    cython.operator.postincrement(a)
```
while the following incorrectly does compile:
```cython
cimport cython

cdef extern from "*":
    cdef cppclass example:
        example operator++()

def test():
    cdef example a
    cython.operator.postincrement(a)
```

**Expected behavior**
The operator behavior should match the behavior used in C++. So `postincrement` should only work when the corresponding operator exists.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.9
 - Cython version 3.0.0a9

**Comment by da-woods** [comment]
If I understand this correctly, the issue is in Cython identifying whether the operator is available? Looking at https://github.com/cython/cython/blob/b6a4215211839afaa850538cdbb065e3513e0dd0/Cython/Compiler/ExprNodes.py#L10494-L10498 I think the correct C++ is generated?

**Comment by maxbachmann** [comment]
Yes the correct C++ is generated. https://github.com/cython/cython/pull/4536 should fix the problem with the operator lookup.
