### ISSUE TITLE
[BUG] Namespace is not inserted if a cppclass is renamed

### ISSUE THREAD

**Issue by oKatanaaa** [cython/cython#4547]
**Describe the bug**
When renaming a `cppclass` (`cdef cppclass CppObject "Object"`), namespace is not inserted into the compiled code. 
Though everythins is okay if namespace is already provided in the 'renaming string', like `cdef cppclass CppObject "nspace::Object"`.
I am not sure if it is a bug, but this moment is not explained in the documentation.

**To Reproduce**
Code to reproduce the behaviour:
**test.pyx**:
```cython
# distutils: language = c++
# distutils: sources = cpp_lib.cpp

cdef extern from "cpp_lib.h" namespace "test":
        # it works with cdef cppclass CppTest "test::Test"
	cdef cppclass CppTest "Test":
		CppTest()


cdef class Test:
	cdef CppTest test
```
**cpp_lib.h**:
```C++
namespace test {
	class Test {
	public:
		Test();
	};
}
```
**cpp_lib.cpp**:
``` C++
#include "cpp_lib.h"

namespace test {
	Test::Test() {};
}
```

**Expected behavior**
I expected Cython to insert the namespace automatically since it is already provided after `namespace` keyword, but for some reason I have to write it explicitely for every cppclass (if I want to rename it). I think the easiest way is to explain class renaming in the documentation to avoid possible confusion.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro, Version 10.0.19.044 Build 19044
 - Python version: 3.7.9
 - Cython version: 

**Additional context**
The error message:
```
test.cpp
test.cpp(935): error C3646: 'test': unknown override specifier
test.cpp(935): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
test.cpp(1340): error C2882: 'test': illegal use of namespace identifier in expression
test.cpp(1340): error C2061: syntax error: identifier 'Test'
test.cpp(1351): error C2882: 'test': illegal use of namespace identifier in expression
test.cpp(1351): error C2672: '__Pyx_call_destructor': no matching overloaded function found
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

**Comment by scoder** [comment]
The documentation [says](https://docs.cython.org/en/latest/src/userguide/external_C_code.html#resolving-naming-conflicts-c-name-specifications):
> Note that Cython will not do any validation or name mangling on the string you provide. It will inject the bare text into the C code unmodified, so you are entirely on your own with this feature. If you want to declare a name xyz and have Cython inject the text “make the C compiler fail here” into the C file for it, you can do this using a C name declaration. Consider this an advanced feature, only for the rare cases where everything else fails.

I admit that this does not refer specifically to C++, but I find it rather explicit overall.

Feel free to send a PR if you feel there's something to improve here.
