### ISSUE TITLE
[BUG] Can't allocate object on stack if class has const members (despite having cpp_locals=True)

### ISSUE THREAD

**Issue by jf2718** [cython/cython#4558]
**Describe the bug**
Allocating a class with const members on the stack produces a .cpp file that can't be compiled because an instance of the class would be assigned to a an optional.

**To Reproduce**
Code to reproduce the behaviour:
- myclass.h:  
  ```cpp
  class MyClass {
  public:
      const int a;
      MyClass(int a) : a(a) {};
  };
  ```
- my_module.pxd
  ```pxd 
  cdef extern from "myclass.h":
      cdef cppclass MyClass:
          MyClass(int a) except +
  ```
- test.pyx
     ```cython
    # cython: language_level=3
    # distutils: language = c++
    # cython: cpp_locals=True
    
    from .my_module cimport MyClass
    
    cdef a_function():
         cdef MyClass instance = MyClass(1);
    ```
Compile using:
```
cython test.pyx --cplus
gcc -c test.cpp -I<python include directory> -std=c++17
```
Error message:
```
test.cpp: In function ‘PyObject* __pyx_f_7package_4test_a_function(int)’:
test.cpp:1849:26: error: use of deleted function ‘std::optional<MyClass>& std::optional<MyClass>::operator=(std::optional<MyClass>&&)’
 1849 |     __pyx_t_1 = MyClass(1);
      |                          ^
In file included from test.cpp:1185:
/usr/include/c++/10/optional:659:11: note: ‘std::optional<MyClass>& std::optional<MyClass>::operator=(std::optional<MyClass>&&)’ is implicitly deleted because the default definition would be ill-formed:
  659 |     class optional
      |           ^~~~~~~~
...
```

**Expected behavior**
The code to be generated correctly. My naive approach would be to replace the assignment with `std::optional::emplace(...)`, but I'm not sure if this would break other things.

**Environment (please complete the following information):**
 - OS: Debian 11
 - Python version: 3.9.7
 - Cython version: 3.0.0a10

**Comment by da-woods** [comment]
Yes, `emplace` probably is the solution. It's a bit of a guess whether

```
cdef MyClass instance = MyClass(1);
```

should be translated into `emplace` or an assignment operator and I could imagine different users would expect different things. `emplace` seems reasonable on the basis that it's "more like Python behaviour".

I'll have a look at some point and see if this can be changed. `cpp_locals` is still an alpha-feature I think so I think we're free to tweak this kind of stuff

**Comment by da-woods** [comment]
Thinking about it more: the issue with `emplace` is if the constructor throws we end up with an empty optional (which contradicts Python behaviour a bit). We could do `instance.emplace(MyClass(1))` (i.e. `emplace` calls a move constructor). That's safe against `MyClass(int)` throwing, but not against the move constructor throwing. The move constructor throwing is probably less likely though.

There's a general issue here:

```
cdef some_cppclass A = A(1)
try:
    A = A(2)
except pass:
    pass
# Cython assumes that A is definitely set, and safe to use without checks here, but actually it isn't true, pretty much however you implement it.
```

**Comment by da-woods** [comment]
I'm kind of wondering if the solution is to use double the stack space in exchange for more accurate, Python-like behaviour. So we have something like

```
template <typename T>
class __Pyx_Optional {
    private:
       // only one of "a" or "b" holds a value at a time
       std::optional<T> a;
       std::optional<T> b;
   public:
       template <typename ...Args>
      void emplace(Args...&& args) {
          if (a) {
             b.emplace(...args);
             a.reset();
          } else {
             a.emplace(...args);
             b.reset();
          }
      }
};
```

It's obviously a trade-off, but given that the objective was to make stack-allocated classes behave more like Python objects it might be worthwhile.
