### ISSUE TITLE
[ENH] Allow runtime conditional GIL releasing/acquiring?  

### ISSUE THREAD

**Issue by leofang** [cython/cython#4569]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. In my code, I would like to do [...]

Currently `with nogil(condition)` accepts a compile-time condition ([link](https://cython.readthedocs.io/en/latest/src/userguide/fusedtypes.html#conditional-gil-acquiring-releasing)). But how about a runtime condition? Is it possible?
```cython
def increment(double x, is_ok):
    # is_ok is a Python object, x is a C double
    with nogil(is_ok):
        x = x + 1
    return x
```

**Describe the solution you'd like**
A clear and concise description of what you want to happen, including code examples if applicable.

As title. 

**Describe alternatives you've considered**

N/A

**Additional context**
Add any other context about the feature request here.

Not sure if that this was not allowed is because of any technical difficulty, or just because no one asked for it, thus I'm raising a discussion. Thanks!

**Comment by da-woods** [comment]
What's the purpose of this?

The contents of the block would have to be able to run GIL (because it's a runtime check).

Keeping the GIL isn't useful as a locking mechanism (because all kinds of code can release the GIL, for example any object destructor, or any Python function can).

So I'm not quite sure what you could use this feature for.

**Comment by leofang** [comment]
We have a design discussion involving several internal & external projects. Part of the design involves allowing users to pass a Python object to an external C library (which could potentially be wrapped via Cython and exposed to Python users). The design aims to provide flexibility for users. So, for example, this is the *class* of use cases that we are evaluating: 
```python
cdef extern from *:
    # an external library API
    int my_func(void* ptr, double x)

cpdef my_func_wrapper(my_obj, double x, is_ok):
    # Note: my_obj may not be actually a Python object; is_ok conveys this information
    cdef void* ptr = <void*>my_obj
    with nogil(is_ok):
        # internally, there is a mechanism to allow my_func to access the Python object,
        # but to do so the GIL must be held
        status = my_func(ptr, x)
    if status != 0:
        raise MyError(...)
```
which is currently not possible. I imaginee the proposed usage of `with nogil(is_ok): status = my_func(ptr, x)` can be expressed in the following fashion:
```python
    if is_ok:
        with nogil:
            status = my_func(ptr, x)
    else:
        # hold the Gil
        status = my_func(ptr, x)
```
so to me it's merely a shortcut of the above expansion. Am I missing any technical issues?

**Comment by da-woods** [comment]
I don't think you're missing any technical issues.

My personal reluctance with this is that I think it'd be confusing (the feature would be more limited than people would expect and that people already find the gil confusing), and that what you want is doable via the expansion you show.

It's not like I have any veto power though - just that I don't think it's worthwhile enough to work on myself.

Based on your example, would a fused type for `my_obj` work (and that should let it be a compile time condition)?

**Comment by scoder** [comment]
I also wonder what the benefit is. Releasing the GIL isn't all that expensive. If it's worth doing in one case, is it really worth _not_ doing in the other? If it's executing exactly the same code, then just release the GIL, always. You code has to be able to deal with that case anyway. And if it's not executing exactly the same code, then your explicit expansion seems better, more natural, and probably also easier to code.

**Comment by leofang** [comment]
Closing this issue, as I realized a way better solution that has existed in Cython: we just need to wrap the user's Python callback with `with gil`: https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#acquiring-the-gil. This way we no longer need to track if GIL can be released or not, so even if I have time to contribute this is moot 🙂 Thanks again to you both for replies!
