### ISSUE TITLE
Implement PEP 614: more general expressions for decorators

### ISSUE THREAD

**Issue by 0dminnimda** [cython/cython#4570]
**Describe the bug**
When compiling this code
```cython
@(functools).wraps(foo)
def bar(): pass
```
Cython fails with such output
```
@(functools).wraps(foo)
^
------------------------------------------------------------

...\test.pyx:6:1: Expected an identifier
```

I know that
```cython
(object).__name__
```
is supported, therefore that behavior with decorators seems weird

**Expected behavior**
To just interpret that as
```python
@functools.wraps(foo)
```
like python does and don't show any errors :)

**Environment (please complete the following information):**
 - OS: Windows
 - Python version 3.9.0
 - Cython version 3.0.0a8

**Comment by scoder** [comment]
https://www.python.org/dev/peps/pep-0614/
