### ISSUE TITLE
[ENH] Allow OpenMP compatibility warning to be suppressed

### ISSUE THREAD

**Issue by orlitzky** [cython/cython#4574]
As far as I can tell, this warning is enabled unconditionally:

> warning: example.pyx:N:M: Unsigned index type not allowed before OpenMP 3.0

Given that OpenMP 3.0 is now a teenager and support for it is widespread... can that warning be made optional?

**Comment by scoder** [comment]
We can probably just remove it. The now legacy [manylinux1](https://www.python.org/dev/peps/pep-0513/) standard used GCC 4.2, and only GCC 4.4 added support for OpenMP 3.0. But [manylinux2010](https://www.python.org/dev/peps/pep-0571/) (also EOL) and [manylinux2014](https://www.python.org/dev/peps/pep-0599/) already use GCC 4.5 (OMP 3.0) and 4.8 (OMP 3.1). And then there are already the even [more recent](https://www.python.org/dev/peps/pep-0600/) Docker images and platform tags.

So, if people still use the `manylinux1` Docker images for their wheel builds, then that's an issue. But in that case, they should rather move away from it by now.

**Comment by scoder** [comment]
Thanks for bringing this up.

**Comment by orlitzky** [comment]
Sounds good to me, thank you!
