### ISSUE TITLE
C/C++ parser for .pxd files to include all definitions from C/C++ header files

### ISSUE THREAD

**Issue by datdinhquoc** [cython/cython#4579]
**Is your feature request related to a problem? Please describe.**
I have a class defined in C/C++ header file, with tons of properties. 
The problem is when I need that class in .pxd files, I have to re-define those
properties in .pxd files, and, there's not only 1 or 2 .pxd files, I have kinda 
10 .pxd files thus there are too much duplicated code in .pxd files.

This creates incomplete type:
```cython
cdef extern from "myclass.hh":
    cppclass MyClass
```

This creates a `dict` instead of a type with all properties
(this works to include implementation file code .cc, .cpp but not headers):
```cython
cdef extern from "myclass.hh:
    cppclass MyClass:
        pass
```

**Describe the solution you'd like**
I wish that Cython as C/C++ parser and parse the C/C++ header files by itself
so my .pxd files won't contain duplicated code again and again in different files.
Also when the C/C++ header file is changed, it is needed to change all those
.pxd files that `cdef extern` from it.

With a C/C++ parser, and a new keyword for example `grab`, the whole
header file can be included into Cython with all things defined in that header file:
```cython
cdef extern from "myclass.hh":
    cppclass MyClass:
        grab
```

**Describe alternatives you've considered**
I don't have any alternatives or work-arounds right now,
accepting the duplicated code in .pxd files.

**Additional context**
None.

**Comment by scoder** [comment]
I'm not sure I understand what you want here. Can't you define the class once in a .pxd file and then cimport it from there in other .pxd files?

**Comment by scoder** [comment]
Also see https://github.com/cython/cython/wiki/AutoPxd

**Comment by datdinhquoc** [comment]
Tks, I found out that single .pxd file to go in pair with .hh file works when there are no circular structures.
