### ISSUE TITLE
[BUG] Cython uses uninitialized variables

### ISSUE THREAD

**Issue by website-reader** [cython/cython#4594]
Please be nice, as I am just starting out - 

Operating System:
openSUSE Leap 15.2
Kernel: 5.3.18-lp152.106-default
64 bit
-------------------------------------------
owner@localhost:~> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=hsa:nvptx-none
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,ada,go --enable-offload-targets=hsa,nvptx-none, --without-cuda-driver --enable-checking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/7 --enable-ssp --disable-libssp --disable-libvtv --disable-libcc1 --disable-plugin --with-bugurl=https://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --with-system-zlib --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-7 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 7.5.0 (SUSE Linux) 
------------------------------------
owner@localhost:~> python --version
Python 2.7.18
owner@localhost:~> 
------------------------------------
owner@localhost:~> cython -V
Cython version 3.0.0a10
owner@localhost:~>
====================================
hello.pyx module
----------------
print("Hello World")
=========================================
uninited.pyx module
-------------------
from __future__ import print_function

def a():
  cdef int n
  print("n=",n)
  print()
=========================================
logged python run
-----------------
owner@localhost:~/sage.corrected> python
Python 2.7.18 (default, Mar 11 2021, 19:28:42) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyximport; pyximport.install()
(None, <pyximport.pyximport.PyxImporter object at 0x7fcde54a25d0>)
>>> import hello
Hello World
[THIS IS WHAT WE EXPECT TO SEE - NORMAL EXECUTION OF MODULE]
>>> import uninited
/usr/local/lib64/python2.7/site-packages/Cython/Compiler/Main.py:346: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/owner/sage.corrected/uninited.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: uninited.pyx:5:13: local variable 'n' referenced before assignment
/home/owner/.pyxbld/temp.linux-x86_64-2.7/home/owner/sage.corrected/uninited.c: In function ‘__pyx_pf_8uninited_a’:
/home/owner/.pyxbld/temp.linux-x86_64-2.7/home/owner/sage.corrected/uninited.c:1873:13: warning: ‘__pyx_v_n’ is used uninitialized in this function [-Wuninitialized]
   __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_v_n); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 5, __pyx_L1_error)
   ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>> 
-----------------------------------------------------------------------------------
We get the error of using an uninitialized variable, see uninited.pyx module above
-----------------------------------------------------------------------------------
I also am UNABLE to get the example on the tutorial page to run

https://cython.readthedocs.io/en/latest/src/quickstart/build.html?highlight=setuptools#building-a-cython-module-using-setuptools

in the section of

Building a Cython module using setuptools

Imagine a simple “hello world” script in a file hello.pyx:

def say_hello_to(name):
    print("Hello %s!" % name)

The following could be a corresponding setup.py script:

from setuptools import setup
from Cython.Build import cythonize

setup(
    name='Hello world app',
    ext_modules=cythonize("hello.pyx"),
    zip_safe=False,
)

To build, run python setup.py build_ext --inplace. Then simply start a Python session and do from hello import say_hello_to and use the imported function as you see fit.

One caveat: the default action when running python setup.py install is to create a zipped egg file which will not work with cimport for pxd files when you try to use them from a dependent package. To prevent this, include zip_safe=False in the arguments to setup().
--------------------------------------------
When I try to run this example, exactly as it is written down, I get an error message

owner@localhost:~/sage.corrected> python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools
owner@localhost:~/sage.corrected> 

So I am unable to actually even run the tutorial examples.
--------------------------------------------------------------------------------------
I am familiar with C and C++ and we followed the practice of always initializing a variable upon first declaration.

**Comment by da-woods** [comment]
This all seems expected to me. It doesn't force you to initialise C variables (like C) but does warn you that you haven't initialized them

**Comment by da-woods** [comment]
Your `ImportError: No module named setuptools` should be easily resolved by installing setuptools (`pip install setuptools`) but you're much better asking that kind of question on the cython-users mailing list

**Comment by scoder** [comment]
> ```cython
> def a():
>     cdef int n
>     print("n=",n)
> ```
Here, you are not initialising `n` before you use it.

> ```
> warning: uninited.pyx:5:13: local variable 'n' referenced before assignment
> ```
This is the warning that Cython gives you about it.

> ```
> /home/owner/.pyxbld/temp.linux-x86_64-2.7/home/owner/sage.corrected/uninited.c: In function ‘__pyx_pf_8uninited_a’:
> /home/owner/.pyxbld/temp.linux-x86_64-2.7/home/owner/sage.corrected/uninited.c:1873:13: warning: ‘__pyx_v_n’ is used uninitialized in this function [-Wuninitialized]
> ```
And this is the warning that the C compiler gives you about it.

> I am familiar with C and C++ and we followed the practice of always initializing a variable upon first declaration.

Not in your example.

**Comment by scoder** [comment]
Also, you should probably be using Python 3 instead of Python 2, but I understand that Sage might still be hindered here.
In Python 2, you have to install setuptools yourself, or use a virtualenv. Or use distutils instead, which should also still work.

Much of the documentation targets Python 3 these days, simply because new users often don't even know any more that there is still a Python 2 and what the differences are.

**Comment by mattip** [comment]
The documentation may not be explicit enough that `cdef int x = 0` is needed to initialize `x`, The example code all does do this, for instance on the [quickstart page](https://cython.readthedocs.io/en/latest/src/quickstart/build.html#using-the-jupyter-notebook), under the Cython form of the first mention of cdef. I would think a PR to [cdef documentation](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#c-variable-and-type-definitions) to enhance the concept that `cdef` follows the rules of C initialization would be nice: 
> Like C, `cdef` declarations do not initialize the variable. Use of uninitialized values will cause a warning when cython compiles the code to C: "local variable ... referenced before assignment". To avoid this initialize values with `cdef int x = 0`.

**Comment by scoder** [comment]
I pushed a documentation update in https://github.com/cython/cython/commit/cf88658ebb9a19716b2bd68fd8e2f52381ebbe0a.

**Comment by mattip** [comment]
Thanks! Hopefully including the warning string will allow google searches for that warning message to find the well-written documentation.
