### ISSUE TITLE
[BUG] Const cast of pointer type overridden

### ISSUE THREAD

**Issue by website-reader** [cython/cython#4597]
System:
openSUSE Leap 15.2 linux 64-bit
Linux localhost.localdomain 5.3.18-lp152.106-default #1 SMP Mon Nov 22 08:38:17 UTC 2021 (52078fe) x86_64 x86_64 x86_64 GNU/Linux
gcc version 7.5.0
Python 2.7.18
Cython version 3.0.0a10

The const qualifier is overriden for a pointer
```
63216:[sagelib-9.4] build/cythonized/sage/calculus/integration.c:6546:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
```

Object code:
```c
    /* "sage/calculus/integration.pyx":645
 *         # Initialize the random number generator
 *         gsl_rng_env_setup()
 *         type_rng = gsl_rng_default             # <<<<<<<<<<<<<<
 *         _rng = gsl_rng_alloc(type_rng)
 * 
 */
    __pyx_v_type_rng = (gsl_rng_type *) gsl_rng_default;
```
Apparently the `gsl_rng_type *` has a `const` qualifier, but the assignment statement is discarding this qualifier.

Question:

Do we simply turn off the warning flag and ignore this warning?
-Wdiscarded-qualifiers is the compiler flag.

**Comment by scoder** [comment]
How is `gsl_rng_type` declared in Sage?  Does Cython know that it has a `const` qualifier?

**Comment by da-woods** [comment]
https://github.com/sagemath/sage/blob/a89f81d7783df2d4e4a187bf209e94d128301f83/src/sage/libs/gsl/rng.pxd#L70

`  cdef gsl_rng_type *gsl_rng_default`

I'm not sure why Cython is inserting the cast here. But it looks like Cython doesn't know about the const qualifier

**Comment by scoder** [comment]
Apparently, the declaration is a dummy:
https://github.com/sagemath/sage/blob/a89f81d7783df2d4e4a187bf209e94d128301f83/src/sage/libs/gsl/types.pxd#L125-L12
```cython
cdef extern from "gsl/gsl_rng.h":
    ctypedef struct gsl_rng_type
    ctypedef struct gsl_rng
```
Cython would probably generate better code if the declaration was closer to what the C compiler sees.

**Comment by scoder** [comment]
This isn't necessarily Sage's fault, since this used to be a common way to hide implementation details from Cython. But it needs fixing in Sage.
