### ISSUE TITLE
[QUESTION] How to get Cython to switch a compiler?

### ISSUE THREAD

**Issue by TheSiker** [cython/cython#4600]

**Comment by TheSiker** [comment]
So basically, I want Cython to use GCC/G++, but it says that I must download Visual Studio 14.0, which is useless,
making it a bloatware. So how do I force Cython to use GCC/G++?

**Comment by da-woods** [comment]
1. Please ask support questions on the Cython-users mailing list, not the bug tracker.
2. The C compiler is handled by distutils and setuptools, not by Cython
3. MSVC is the only supported compiler to use with Python on Windows
4. It is just about possible to get mingw to work (https://stackoverflow.com/questions/70654722/how-to-create-c-extension-embed-python-with-mingw-w64-on-windows) but it is unsupported so if you run into bugs then you may not get any help
