### ISSUE TITLE
RELEASE: schedule for a 0.29.27 release?

### ISSUE THREAD

**Issue by mattip** [cython/cython#4601]
Cython 0.29.26 exposed a PyPy bug, which was worked around in #4509 and #4517. This leaves a situation where using 0.29.26 to build on PyPy will fail. PyPy is getting close to a new release, which means packagers who are brave enough to build PyPy3.8+ wheels with Cython for the new release and use "latest" will run into this problem.

Sorry to ask have to ask for this, but is there a plan to release 0.29.27 with the fixes soonish?

**Comment by scoder** [comment]
It's still unclear what to do about #4500. But since that doesn't look like it will go into 0.29.x soon, and isn't critical ATM, I'll see if I can get 0.29.27 released as it is.

**Comment by mattip** [comment]
Thanks!

**Comment by scoder** [comment]
Released yesterday.

**Comment by mattip** [comment]
:+1:
