### ISSUE TITLE
CI integration fails on a timeout. Seems the fix doesn't break any tests.

### ISSUE THREAD

**Issue by Aung658** [cython/cython#4602]
CI integration fails on a timeout. Seems the fix doesn't break any tests.

_Originally posted by @rhpvorderman in https://github.com/cython/cython/issues/3831#issuecomment-694033092_

**Comment by da-woods** [comment]
This doesn't look like a useful issue. It looks like you accidentally clicked on a comment and converted it to an issue. But I don't understand what you've re-opened it.

Please leave it closed.
