### ISSUE TITLE
[ENH] Improve documentation of installing custom C++ exception handlers

### ISSUE THREAD

**Issue by vyasr** [cython/cython#4613]
**Is your feature request related to a problem? Please describe.**
I would like to be able to install custom exception handlers in my code to automate the translation of additional C++ exceptions into Python exceptions, similar to the automatic translation described [here](http://docs.cython.org/en/latest/src/userguide/wrapping_CPlusPlus.html#exceptions) and implemented [here](https://github.com/cython/cython/blob/db19667d81066aa20cf13ab3ea9cba8d5ab9c948/Cython/Utility/CppSupport.cpp#L9). It appears that such a handler is already possible to implement according to [this StackOverflow post](https://stackoverflow.com/questions/10684983/handling-custom-c-exceptions-in-cython). However, I don't find this behavior documented anywhere.

**Describe the solution you'd like**
It would be helpful to add an example to the documentation showing how such a handler could be installed. I am happy to contribute it, but I don't know enough to know if the approach recommended in the post linked above is a good one or if it would need to be changed. I can certainly do it with some pointers.

**Describe alternatives you've considered**
I stumbled upon this while investigating whether it would be possible to add a Cython feature to directly modify the existing exception handler by defining a mapping between custom Python and C++ exceptions in a Cython file. While that seemed like an interesting idea, if it is already possible to accomplish this with a little C++ boilerplate as shown above I don't think there's much reason to add that complexity to Cython.

**Additional context**
None.

**Comment by scoder** [comment]
The default implementation in [`__Pyx_CppExn2PyErr()`](https://github.com/cython/cython/blob/db19667d81066aa20cf13ab3ea9cba8d5ab9c948/Cython/Utility/CppSupport.cpp#L9) that you already linked to is probably the best example there is. I don't think a custom handler would look much different.

I agree that it would be good to add at least an example to the docs, and maybe also link to `__Pyx_CppExn2PyErr()`. The SO posts pretty much fill in all the details.

OTOH, if you want to share the handler across modules, then it might be worth implementing it in a `.pxd` file as [verbatim C++ code](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#including-verbatim-c-code). It should usually be a simple function, so this shouldn't feel excessive, but would leave the code easily visible from your Cython code editor.

PR welcome.

**Comment by vyasr** [comment]
My question was less about what the handler itself would like like, and how I would go about using that handler in place of the the default implementation. Is what's in that post basically what you would want to see in the documentation of that process? If so, I am happy to make that docs PR.

**Comment by scoder** [comment]
I'd say the SO answers seem to have all the information in them, but need summing up somehow. Would be great to have a PR for that.

**Comment by vyasr** [comment]
@scoder well, it's only been almost a year since I made this request :smile: but I finally put together a suitable example [in this gist](https://gist.github.com/vyasr/4eddbff25bb197e056eab3ac1dda6f40). I think this would fit well in [the exceptions section of the C++ docs](https://docs.cython.org/en/latest/src/userguide/wrapping_CPlusPlus.html#exceptions), which already shows the possibility of a custom `raise_py_error`. The goal of my example is to show exactly what `raise_py_error` would look like, particularly if you wanted to define a mapping between any currently unhandled C++ exception and a (possibly user-defined) Python exception. Any thoughts on how best to adapt my gist into the docs? Also two questions about the contents:
1. Do you think including my entire example is too verbose, and if so what could I strip out? Maybe not including all of the possible exceptions that Cython handles, and showing a handler that just handles one specific exception and raises a `RuntimeError` for everything else?
2. Is my approach for creating a new Python exception the best way to handle this in Cython? I figured there was no need to add a separate `PyInit_*` function for a new module if I could just call the C function inside the Cython module.
