### ISSUE TITLE
[BUG] lxml fails to build in Python-3.11.0a5

### ISSUE THREAD

**Issue by MrBitBucket** [cython/cython#4636]
**Describe the bug**
I'm testing reportlab with latest python alpha 5; I use lxml. This built fine in 3.11.0a3, but fails in 3.11.0a5.

**To Reproduce**
Code to reproduce the behaviour:
. bin/activate
pip install cython #this works fine
pip install lxml fails

**Expected behavior**
I expected it to build as in the previous alpha 3; there was an alpha 4, but it was withdrawn so far as I can tell. If I build a wheel with 3.11.0a3 it will install in 3.11.0a5, but I think that is unsafe.

**Environment :**
 - OS:arch linux amd64
 - Python version 3.11.0a5
 - Cython version 0.29.27

[lxml-311a5-install-failure.log](https://github.com/cython/cython/files/8054589/lxml-311a5-install-failure.log)
[lxml-311a3-install-success.log](https://github.com/cython/cython/files/8054591/lxml-311a3-install-success.log)

**Comment by scoder** [comment]
The error shown in the logs is a duplicate of https://github.com/cython/cython/issues/4581
