### ISSUE TITLE
does cython support inheritance only from python class？ Even more， multiple inheritance only from python classes? [ENH] 

### ISSUE THREAD

**Issue by yujianpeng66** [cython/cython#4645]
example for inheritance only from python class:
Like: `cdef class mydict(OrderedDict):`

example for multiple inheritance only from python classes:
Like: `cdef class myReader(Readable, Seekable):`

**Comment by da-woods** [comment]
No. Cython doesn't support this.

Please ask support questions to the Cython-users group and not the bug tracker
