### ISSUE TITLE
Bring back to .c extension

### ISSUE THREAD

**Issue by ADF-UNIX** [cython/cython#4647]
Hi,
I have android Termux. I have cython file and my file name is ```main.so```. I want to bring back the ```.c```file. I do not have the source code and I have to retrieve the ```.c``` file. Let me know the method by which I can bring back the ```.c``` extension.
Thanks!

**Comment by da-woods** [comment]
1. Please ask support questions on the cython-users mailing list (https://groups.google.com/forum/#!forum/cython-users)
2. In general this is not possible. If you don't have the .c file and you don't have the .pyx file then you can't really get back the C file (and it certainly isn't a feature that Cython provides). If the .so file was compiled with debug symbols you may be able to retrieve some .c source with effort.
3. If you have the .pyx file then you just need to run cython on it.

**Comment by ADF-UNIX** [comment]
> 1. Please ask support questions on the cython-users mailing list (https://groups.google.com/forum/#!forum/cython-users)
> 2. In general this is not possible. If you don't have the .c file and you don't have the .pyx file then you can't really get back the C file (and it certainly isn't a feature that Cython provides). If the .so file was compiled with debug symbols you may be able to retrieve some .c source with effort.
> 3. If you have the .pyx file then you just need to run cython on it.

Hmmm,
This means that we cannot reverse cython ```.so``` file.
