### ISSUE TITLE
Extract cython .so to .c graph!

### ISSUE THREAD

**Issue by Termux-user-0x0** [cython/cython#4654]
Hi,
I have cython ```main.so``` file. But I want to ```.so``` extract to ```.c``` and can we decode cython ```.so``` file. It's possible?

**Comment by da-woods** [comment]
https://github.com/cython/cython/issues/4647

**Comment by scoder** [comment]
@Termux-user-0x0 please stop asking this question on the bug tracker. Please use the Cython users mailing list, and please read the answers that you get. If you continue to open new tickets, we may have to block your account to avoid having to keep closing your tickets over and over.
