### ISSUE TITLE
Attempts to use PEP 572 with PyPI releases fail - issues closed without fixing release

### ISSUE THREAD

**Issue by AstroFloof** [cython/cython#4659]
**Describe the bug**
Cython's parser chokes on walrus operators within a parenthesis, which is legal python. The parser expects a closing parenthesis but finds a colon instead.
```
Cython.Compiler.Errors.CompileError: 
Error compiling Cython file:
------------------------------------------------------------
myvar = int(env_val) if (env_val := os.getenv("MYVAR")) else 0
                                 ^
------------------------------------------------------------
(tree fragment):1:33: Expected ')', found ':'
```
**To Reproduce**
```py
cython.inline('myvar = int(env_val) if (env_val := os.getenv("MYVAR")) else 0')
```

**Expected behavior**
Compilation as normal. According to #2636 and #3691 this should be implemented already, so I don't understand why it dies.

**Environment (please complete the following information):**
 - Linux Mint Una 20.3 (Based on Ubuntu, Kernel 5.4.0)
 - Python version 3.10.2
 - Cython version 0.29.28

**Additional context**
Noob to Cython. Attempted to use Cython on pure python without any modified type-hinting yet. Eventually I will make pxd headers and/or a way to generate them if there isn't already.

**Comment by AstroFloof** [comment]
Found another
```py
if (val := myclass.anotherclass.value) or not self.function():
```
Seems to be the parentheses screwing things up

**Comment by AstroFloof** [comment]
Also occurs in 3.0.0a10

**Comment by AstroFloof** [comment]
Ok what the heck
```py
            elif match := await regex_with_timeout(patterns[0], line):
```
also dies on both versions

**Comment by AstroFloof** [comment]
Alright, I just installed from the master branch.
It seems like that fixed it, so I suppose this issue should be closed. However, why was #2636 closed before a solution was released? I'll keep this open for now unless one of yall closes it.
Now I have to wait on #4029

**Comment by scoder** [comment]
> Now I have to wait on #4029

Sure, waiting is something you can do. However, something that usually feels much more productive to people than waiting is helping out. You may give that a try.

**Comment by AstroFloof** [comment]
> > Now I have to wait on #4029
> 
> Sure, waiting is something you can do. However, something that usually feels much more productive to people than waiting is helping out. You may give that a try.

Sorry, I already have a bunch on my plate, and I don't know the first thing about Cython internals or parsing/transpilation. I wish I did, so I could help.
Good luck with future development!
