### ISSUE TITLE
[BUG] pickled classes have different checksums on Cython 3.0 Vs 0.29

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4680]
**Describe the bug**

It looks like classes pickled in a module compiled in Cython 0.29.x cannot be reloaded when the module is recompiled in Cython 3.0 because the checksum has changed. See https://github.com/pandas-dev/pandas/pull/46029#issuecomment-1066294846

I'm putting https://github.com/cython/cython/commit/f00af64bcc2cef4c3fb1433ed670ab5f9970e2cd as the most likely cause, but I haven't properly bisected it yet.

**To Reproduce**
I don't have a tested minimal example myself yet, but I imagine

```
cdef class C:
   pass
```

would be sufficient.

**Expected behavior**
I'm not sure how far we should guarantee the long-term stability of our pickle output. 3.0 seems a reasonable time to break if, if we're going to. I wonder if we should have some way of ignoring the checksum though, just to help people preserve their old data.

**Environment (please complete the following information):**
 - Cython version 0.29.28 and 3.0 master (plus some in-progress patches)

**Comment by scoder** [comment]
Added a test fix here: https://github.com/cython/cython/commit/685f7a7e4b4578f4c74f88185b99f5ede97bd42c
