### ISSUE TITLE
Could pyx file be debugged line by line?

### ISSUE THREAD

**Issue by ardeal** [cython/cython#4686]
Hi,

Is there any IDE or tools to debug pyx file with break-point and line by line?
we could debug python code in VSCode or pycharm easily, for cython, is there any similar IDE or tools that could make me debug cython code?

Thanks

**Comment by scoder** [comment]
I think PyCharm had this at some point.

Not sure if there is something that Cython can do better or differently here. Seems more something that debuggers should handle. So I'll close this ticket, unless there is something that Cython actually *could* do better.
