### ISSUE TITLE
A crash with unknown cause[BUG] 

### ISSUE THREAD

**Issue by dentistfrankchen** [cython/cython#4688]
I designed a data type to simulate the collections library.
[test1.zip](https://github.com/cython/cython/files/8305272/test1.zip)

Inside the file:
I wrote a cdef class named parrot. I also wrote a append function which allows me to attach new data to the c data structure inside the parrot class. As for the running platform, I choose vscode+cython 0.29.15.
This works well when I just append a small amount of data, for example 30000 integers.(appending this integers to the linked list)HOWEVER, when I try to append a relatively large amount of data such as 50000 integers, the jupyter kernel "dies".
In comparison, if I use collections.deque to do this, there will be no crashes.

The following is the error code I got:
Error 22:28:04: Raw kernel process exited code: 3221225477
Info 22:28:04: Cancel all remaining cells due to dead kernel
Info 22:28:04: Cancel pending cells
Info 22:28:04: Cell 6 executed with state Success
Info 22:44:46: Execute Cells request 6
Info 22:44:46: Execute Cell 6 c:\Users\dentistfrankchen\Desktop\art_intel\exp_copy\linked_nodes_exp_malloc_block\test1.ipynb
Info 22:44:48: Cell 6 executed with state Error due to kernel state.

**Comment by da-woods** [comment]
I only had a very quick look at it, but this looks dodgy:

```
      free(self.queue)
      free_mem(&(self.queue))
```

You're trying to use a pointer after you've deallocated it. There may well be (and probably are) other issues.

With that in mind, I'm pretty confident that this is an issue with your code rather than Cython. Please ask support questions on the cython-users mailing list rather than the bug tracker.

**Comment by dentistfrankchen** [comment]
Problem solved. Thank you a lot. Frank Chen ***@***.*** 签名由 网易邮箱大师 定制 On 03/19/2022 03:26, da-woods wrote: I only had a very quick look at it, but this looks dodgy:       free(self.queue)
      free_mem(&(self.queue))
 You're trying to use a pointer after you've deallocated it. There may well be (and probably are) other issues. With that in mind, I'm pretty confident that this is an issue with your code rather than Cython. Please ask support questions on the cython-users mailing list rather than the bug tracker. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
