### ISSUE TITLE
Jacobus van't Hoff

### ISSUE THREAD

**Issue by samalbee** [cython/cython#4696]
<p><strong>Jacobus van't Hoff</strong></p>
<p>J. H. van't Hoff was a Dutch physicist and chemist. He taught chemistry, mineralogy and geology as a professor in Amsterdam.&nbsp;Van't Hoff was one of the co-founders of physical chemistry. He founded stereochemistry - <a href="https://domyhomework.club/php-homework/">https://domyhomework.club/php-homework/</a>&nbsp;. However, van't Hoff became best known for his descriptions of chemical equilibria and the development of the law of mass action. The well-known RGT rule (reaction rate-temperature rule) originates from him. van't Hoff was awarded the Nobel Prize in Chemistry in 1901 for his discovery of the laws of reaction kinetics and of osmotic pressure in solutions. He was thus the first person to receive the Nobel Prize in Chemistry.</p>
<p><strong>The time in which he lived</strong></p>
<p>The 19th century in which Jacobus Henricus van't HoffJ lived was characterised by many scientific discoveries - <a href="https://domyhomework.club/chemistry-problem-solver/">chemistry homework solver</a>&nbsp;. Chemistry had developed from alchemy into a science to be taken seriously.</p>
<p>Milestones in this development were, for example, the decomposition of alkaline earths and alkaline compounds by electric current -&nbsp;<a href="https://domyhomework.club/">do my homework services</a>&nbsp;(Davy 1807/08), the discovery and isolation of the elements iodine (Courtois 1811), bromine (Balard 1826) and aluminium (1811 to 1827; Wohler 1827) and the formulation of Avogadro's law (1811). In addition, J. L. Meyer And Mendeleev established the periodic table of the elements. For scientists, the 19th century was a fruitful century. Technology and industry created the conditions for many groundbreaking discoveries.</p>
<p><strong>More information:</strong></p>
<p><a href="https://www.textarea.com/samalbee/triangle-construction-52286/">Triangle construction</a></p>
<p><a href="https://community.gtarcade.com/thread/forum.php?mod=viewthread&amp;tid=1362658">Proof of the inequality of a triangle</a></p>
<p><a href="http://teamworkmatters.ocbmedia.com/members/samalbee/profile/">Biography Leonhard Euler</a></p>
<p><a href="https://www.traumagroup.org/profile/albees046/profile">Cause-effect relationship and atomic theory</a></p>
<p><a href="https://www.fixationonhistology.com/profile/albees046/profile">Intellectual sources of the "Utopia"</a></p>

**Comment by da-woods** [comment]
Spam

**Comment by da-woods** [comment]
@scoder could you edit out the spam content from the post above (or just deleting the issue entirely)? I'd rather not keep spam links up, and I don't think I can remove it myself
