### ISSUE TITLE
[BUG] Use of ob_shash is deprecated on 3.11

### ISSUE THREAD

**Issue by mattip** [cython/cython#4721]
**Describe the bug**

Using `PyStringObject->ob_shash` is deprecated in Python 3.11 and emits a warning. NumPy fails the builds on warnings.

**To Reproduce**
We are seeing this in NumPy when [building for Python 3.11](https://github.com/numpy/numpy/pull/21308#issuecomment-1091193532).
**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Linux, Windows, macOS]
 - Python version [e.g. 3.8.4]
 - Cython version [e.g. 0.29.18]

All OSs, Python 3.11alpha, Cython HEAD and 0.29.28

**Additional context**

Cython could decide to tell downstream projects to ignore the deprecation warning, which would allow the problem to be pushed off for 2 years.

Another alternative is to avoid the fast path that uses internals. Would it be a significant slowdown to skip this for Python>=3.11? https://github.com/cython/cython/blob/c79ae55a7440459dae7667699284a72b09e89185/Cython/Utility/StringTools.c#L369-L379

**Comment by felixxm** [comment]
`cpython` usages should be straightforward to fix by using `PyObject_Hash()`:
```
             hash1 = PyObject_Hash(s1); 
             hash2 = PyObject_Hash(s2); 
```

**Comment by felixxm** [comment]
See https://bugs.python.org/issue46864.

**Comment by da-woods** [comment]
> Using `PyStringObject->ob_shash` is deprecated in Python 3.11 and emits a warning.

I think it's only `PyBytesObject` isn't it?

> cpython usages should be straightforward to fix by using PyObject_Hash():

That's possibly a pessimization once it's actually removed and no longer cached

**Comment by scoder** [comment]
Given the `CYTHON_USE_UNICODE_INTERNALS` guard, this is probably a relict of Py2 times, when Py2 `str` was more important than it is today. I'd just mark the fast path as Py<3.11 only and phase it out that way. It shouldn't make that much of a difference, except for longer byte strings (with long identical prefixes).

**Comment by felixxm** [comment]
Thanks :rocket:
