### ISSUE TITLE
[ENH] Switch to cibuildwheel

### ISSUE THREAD

**Issue by lithomas1** [cython/cython#4736]
**Is your feature request related to a problem? Please describe.**
The wheel building process in Cython is currently clunky and is missing/not building wheels(other than the universal wheel, which I don't think is compiled) for any platforms other than Linux. Migrating to cibuildwheel will provide better release automation and build isolation and make building wheels easier(it's pretty easy to add new platforms using cibuildwheel as long as tests pass). 

It also saves end users time, as although Cython still works, they still need to compile it upon install (which takes a fair bit of time).

**Describe the solution you'd like**

I would like to see Cython migrate to cibuildwheel for release 3.1(but the infra for cibuildwheel can be put in much earlier than that). Unfortunately, cibuildwheel seems to be pretty stringent about dropping Python versions, and they tend to drop them on the dot when they become EOL. This may be a problem for Cython, if they wish to support any Python minor version past EOL. Pinning cibuildwheel to an old version doesn't work, as cibuildwheel as the list of platforms/Python versions it supports is baked into a particular version, meaning that Cython will not be able to support any new platforms/Python versions that cibuildwheel adds support for if they pin.

My recommendation to solve this is to first do the work adding the infrastructure to build in cibuildwheel, but leave it dormant and continue using the current system to build wheels. After 3.0, which deprecates Python 2.7, there probably should be little reason to support EOL python versions. When Cython 3.1 releases, which drops 2.7 support, we can then activate the cibuildwheel infra.

**Describe alternatives you've considered**
multibuild, but cibuildwheel is better as it has better support for building wheels for pre-release Pythons, and doesn't need to be vendored as a submodule.

**Additional context**

I am willing to put up a PR for this if this is welcome.

cc @scoder @da-woods

**Comment by da-woods** [comment]
> It also saves end users time, as although Cython still works, they still need to compile it upon install (which takes a fair bit of time)

Just a quick comment that's pretty tangential to your issue - you don't *have* to build Cython (the current argument to skip it is `pip install Cython --install-option="--no-cython-compile"`). And for an isolated build where Cython's it probably makes sense not to.

-----------------------------------

I have to admit, I know almost nothing about the pros and cons of different build systems so I'm reluctant to comment too much. In an ideal world I guess Cython would work well with all of the major options and try not to force the user to use one in particular (obviously they may need one in particular to build Cython, but in an ideal world that wouldn't force them into a choice for their own project).

But given my ignorance I'm not sure I have much to add!

**Comment by scoder** [comment]
This change is absolutely welcome. For older Python versions, we can leave the current build setup in place, and just discard it completely in Cython 3.1. That doesn't mean that we can't start building wheels with `cibuildwheel` right away, for the supported Python versions (and variants).

If they are really strict about EOLs, and we can't support, say Py3.6 and Py3.15 at the same time any more, then it should still be possible to use an older cibuildwheel version for older Pythons. In the worst case, we can duplicate parts of the CI build script for that. Duplication is good here, because it makes phasing out old versions easy by just removing the older duplicate again.

**Comment by scoder** [comment]
> you don't _have_ to build Cython (the current argument to skip it is `pip install Cython --install-option="--no-cython-compile"`).

We also provide pure Python wheels for environments for which we don't have binary wheels on PyPI. Those install quickly and run only somewhat slower than the binary wheels. You probably won't notice any difference for smaller packages on a CI server, especially not on virtual build instances that suffer from high build time variation anyway.

**Comment by maxbachmann** [comment]
> If they are really strict about EOLs, and we can't support, say Py3.6 and Py3.15 at the same time any more, then it should still be possible to use an older cibuildwheel version for older Pythons.

They drop things as soon as they are dropped by manylinux. However as you noted at this point it is still possible to keep using the old version as long as you need to support the platform. I am personally using cibuildwheels on my projects for a while now and I am super happy with it so far.
