### ISSUE TITLE
[BUG] unicode.split does not allow to pass None for sep

### ISSUE THREAD

**Issue by navytux** [cython/cython#4737]
**Describe the bug**
I'm hitting the difference in behaviour in between CPython and Cython for `unicode.split` - with Cython passing `sep=None` explicitly raises TypeError. Please find details below:

**To Reproduce**
Code to reproduce the behaviour:

---- 8< ---- usplit.pyx
```cython
# cython: language_level=3

def mysplit(q):
    return unicode.split(q, None)

print(mysplit("hello world"))
```

**Expected behavior**

I expect it to behave the same as in Python - i.e. print ['hello', 'world']:

---- 8< ---- usplit_py.py
```py
def mysplit(q):
    return str.split(q, None)

print(mysplit("hello world"))
```

```console
$ python usplit_py.py 
['hello', 'world']
```

However what I get instead is the following exception that None could not be used for `sep`:

```console
$ cythonize -i usplit.pyx 
Compiling /home/kirr/usplit.pyx because it changed.
[1/1] Cythonizing /home/kirr/usplit.pyx
running build_ext
building 'usplit' extension
creating /home/kirr/tmp3kckc5wa/home
creating /home/kirr/tmp3kckc5wa/home/kirr
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/kirr/src/wendelin/venv/py3.venv/include -I/usr/include/python3.9 -c /home/kirr/usplit.c -o /home/kirr/tmp3kckc5wa/home/kirr/usplit.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /home/kirr/tmp3kckc5wa/home/kirr/usplit.o -o /home/kirr/usplit.cpython-39-x86_64-linux-gnu.so
```
```console
$ python -c 'import usplit'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "usplit.pyx", line 6, in init usplit
    print(mysplit("hello world"))
  File "usplit.pyx", line 4, in usplit.mysplit
    return unicode.split(q, None)
TypeError: must be str, not NoneType
```

**Environment (please complete the following information):**
 - OS: [Debian GNU/Linux 11]
 - Python version [e.g. 3.9.2]
 - Cython version [e.g. 0.29.27]

Thanks beforehand,
Kirill

**Comment by da-woods** [comment]
So it looks like we translate `unicode.split` to `PyUnicode_split` https://github.com/cython/cython/blob/d2d2ea33a21e1915a52790ef64fdd1f28867854c/Cython/Compiler/Optimize.py#L3614-L3635

The documentation for that (https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_Split) implies that it treats `sep==NULL` as "split on whitespace". So we probably just want a tiny wrapper function to translate `None` to `NULL` and maybe also to special-case it when a `None` constant is passed.

**Comment by navytux** [comment]
Yes, @da-woods, thanks. I'm already doing my workarounds for other unicode methods - `count`, `endswith`, `find` etc for `start` and `stop`, e.g. as follows:

```cython
    def count(self, sub, start=None, end=None):                                                            
        # cython optimizes unicode.count to directly call PyUnicode_Count - cannot use None for sub        
        if start is None: start = 0                                                                        
        if end   is None: end   = PY_SSIZE_T_MAX                                                           
        return unicode.count(self, pyu(sub), start, end)                                                   
```

but for `unicode.split` I could not find a clean way to pass `sep` as NULL myself.

**Comment by da-woods** [comment]
If you have a list of the unicode methods that you know of that have similar bugs then that'd be very useful?

**Comment by navytux** [comment]
Sure, here is my current list:

- count
- endswith
- find
- index
- rfind
- rindex
- split        (this one)
- startswith

**Comment by da-woods** [comment]
Your best workaround in the short-term would be to stop Cython from knowing that the object is unicode. So

```
def call_split(u: unicode):
   return (<object>u).split(None)
```

should at least prevent Cython from doing its optimization

**Comment by navytux** [comment]
@da-woods, thanks for the hint. For the reference I already worked it around as follows:

```cython
    def split(self, sep=None, maxsplit=-1):
        # cython optimizes unicode.split to directly call PyUnicode_Split - cannot use None for sep
        # and cannot also use object=NULL https://github.com/cython/cython/issues/4737
        if sep is None:
            v = unicode.split(self, maxsplit=maxsplit)
        else:
            v = unicode.split(self, pyu(sep), maxsplit)
        return list([pyu(_) for _ in v])
```

**Comment by scoder** [comment]
Agreed that Cython should handle this internally. Thanks for bringing it up.

**Comment by navytux** [comment]
You are welcome, @scoder. Thanks for feedback.

**Comment by scoder** [comment]
I looked into this. @navytux, apart from `split()`, the other methods you mentioned do not seem to accept `None` as argument except for the index range. That's what you meant, right? Supporting that is a bit tricky, because it involves two different coercions: 1) `None` -> `0` / `PY_SSIZE_T_MAX` and 2) `object` -> `Py_ssize_t`. I'll see what I can do.

**Comment by navytux** [comment]
@scoder, thanks for looking into it. Yes, for everything besides `split` I was talking about `start`/`end` parameters that specify interested index range.

**Comment by scoder** [comment]
I submitted a PR in https://github.com/cython/cython/pull/4740

@navytux, since there are a bunch of methods that are affected, maybe you could help us by writing up the tests for them? I added a few and it looks good, but most methods are still missing, and I think it'd be good to also test the None arguments separately and not just together as two Nones.

**Comment by scoder** [comment]
You are looking at the doctest part, which is executed by Python (not compiled by Cython). We use this to a) run our compiled test function and validate the result, and sometimes also to b) do the same operation in Python to make sure it produces the same (expected) result, and it stays that way across Python versions. What you remove above is the Python comparison test part.

**Comment by navytux** [comment]
Now I see, thanks for clarifying. Then since we are adding many cases, would the following be ok with you:

```diff
--- a/tests/run/unicodemethods.pyx
+++ b/tests/run/unicodemethods.pyx
@@ -357,44 +357,33 @@ def startswith(unicode s, sub):
     "//PythonCapiCallNode")
 def startswith_start_end(unicode s, sub, start, end):
     """
-    >>> text.startswith('b ', 1, 5)
+    >>> def _(sub, start, end):
+    ...     py = text.startswith(sub, start, end)
+    ...     cy = startswith_start_end(text, sub, start, end)
+    ...     assert py == cy, (py, cy)
+    ...     return cy
+    >>> _('b ', 1, 5)
     True
-    >>> startswith_start_end(text, 'b ', 1, 5)
-    'MATCH'
-    >>> text.startswith('ab ', -1000, 5000)
+    >>> _('ab ', -1000, 5000)
     True
-    >>> startswith_start_end(text, 'ab ', -1000, 5000)
-    'MATCH'
-    >>> text.startswith('b X', 1, 5)
+    >>> _('b X', 1, 5)
     False
-    >>> startswith_start_end(text, 'b X', 1, 5)
-    'NO MATCH'
 
-    >>> text.startswith('ab ', None, None)
+    >>> _('ab ', None, None)
     True
-    >>> startswith_start_end(text, 'ab ', None, None)
-    'MATCH'
-    >>> text.startswith('ab ', 1, None)
+    >>> _('ab ', 1, None)
     False
-    >>> startswith_start_end(text, 'ab ', 1, None)
-    'NO MATCH'
-    >>> text.startswith('b ', 1, None)
+    >>> _('b ',  1, None)
     True
-    >>> startswith_start_end(text, 'b ', 1, None)
-    'MATCH'
-    >>> text.startswith('ab ', None, 3)
+    >>> _('ab ', None, 3)
     True
-    >>> startswith_start_end(text, 'ab ', None, 3)
-    'MATCH'
-    >>> text.startswith('ab ', None, 2)
+    >>> _('ab ', None, 2)
     False
-    >>> startswith_start_end(text, 'ab ', None, 2)
-    'NO MATCH'
     """
     if s.startswith(sub, start, end):
-        return 'MATCH'
+        return True
     else:
-        return 'NO MATCH'
+        return False
```

i.e. do the check of what Python produced wrt what Cython produced automatically, and have only one case for each test entry. So reworked test looks e.g. like the following:

```cython
@cython.test_fail_if_path_exists(
    "//CoerceToPyTypeNode",
    "//CastNode", "//TypecastNode")
@cython.test_assert_path_exists(
    "//CoerceFromPyTypeNode",
    "//PythonCapiCallNode")
def startswith_start_end(unicode s, sub, start, end):
    """
    >>> def _(sub, start, end):
    ...     py = text.startswith(sub, start, end)
    ...     cy = startswith_start_end(text, sub, start, end)
    ...     assert py == cy, (py, cy)
    ...     return cy
    >>> _('b ', 1, 5)
    True
    >>> _('ab ', -1000, 5000)
    True
    >>> _('b X', 1, 5)
    False

    >>> _('ab ', None, None)
    True
    >>> _('ab ', 1, None)
    False
    >>> _('b ',  1, None)
    True
    >>> _('ab ', None, 3)
    True
    >>> _('ab ', None, 2)
    False
    """
    if s.startswith(sub, start, end):
        return True
    else:
        return False
```

and personally I find it easier to understand because the signal/noise ratio becomes higher. (I would rework it even further to just do `return s.startswith(...)` but then it starts to fails detecting `CoerceToPyTypeNode`.

Would such style be ok with you?

**Comment by scoder** [comment]
> Would such style be ok with you?

Good idea. But please use a descriptive name (like "test_endswith") instead of "_" to make the output of different tests easier to distinguish on failures.

**Comment by navytux** [comment]
Thanks, @scoder. So I've tried to do those tests for unicode methods the way we discussed. Please find the patches at https://github.com/cython/cython/pull/4743. More specifically the patches are:

- https://github.com/navytux/cython/commit/5786479ec026a23b6f867b6ab3cb804b0651bbae
- https://github.com/navytux/cython/commit/b2d6691377bf438e2bc802b6bc033e84650ab257
- https://github.com/navytux/cython/commit/f5f124ad943fc889a7810ddf7cf194caa500631c

Hope it is ok,
Kirill
