### ISSUE TITLE
[BUG] Looking up object.__getstate__ seems to have broken PyPy

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4738]
**Describe the bug**
The CI on PyPy is reporting a lot of `xxx has not attribute __getstate__`.

**Environment (please complete the following information):**
 - Python version PyPy
 - Cython version 0.29.x and 3.0

**Additional context**
Almost certainly introduced in https://github.com/cython/cython/commit/ae4ade8daeae206db68583f2f4b9c1cbce9cba75. PyPy probably doesn't use CYTHON_USE_PYTYPE_LOOKUP so will go through a slightly different code path

**Comment by scoder** [comment]
Fixed in https://github.com/cython/cython/commit/60ca7eb7497bd5be93e616666e3ce04ae0f27fd2
