### ISSUE TITLE
[ENH] Auto-generation of ufuncs

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4758]
**Is your feature request related to a problem? Please describe.**

The Numpy C API defines a way to generate ["ufuncs" from a C function pointer](https://numpy.org/doc/stable/reference/c-api/ufunc.html). The C API takes a C callable and converts it into a Python callable that works on arrays of varying dimensions (broadcasting), and also handles reductions and broadcasting I think.

**Describe the solution you'd like**

The Numpy C API for this is accessible in Cython (via the pxd files) but is not hugely intuitive. It is also based around `void*`s to access the data, rather than the nicer Cython types like typed memoryviews). Therefore it might be nice to have a decorator to convert Cython cdef functions into Numpy ufuncs to allow them to work well with array broadcasting (people sometimes try to solve this problem with fused types of `double[:]`, `double[:,:]`, double[:,:,:]` etc., which is OK, but a bit ugly).

Example code:

```
cimport cython

@cython.numpy_ufunc
cdef double add(double x, double y):
    return x+y  # obviously a trivial example which is in Numpy already
```

**Additional context**

Numba provides a similar feature https://numba.pydata.org/numba-doc/dev/user/vectorize.html, so there's precedent (and people would probably understand it)

The Numpy C API also provides "generalised ufuncs". These would also be nice, but probably not part of an initial implementation.

This'd introduce a runtime+compile-time dependency on Numpy. Cython typically tries to be fairly dependency-free by default. I've proposed the decorator name `numpy_ufunc` to try to make that dependency as clear as possible. There's also a question: is there a way to do this without tying it to Numpy.

In the more distant future this might be a good place to introduce other backends (e.g. gpu, parallelization?). But definitely not for the initial version.

I have no immediate plans to implement this for the moment - posted mainly to get a bit of feedback about whether it's likely to be useful

**Comment by tillahoffmann** [comment]
This would be great to have! I played around with a `ufunc`-`cython` integration a bit [here](https://github.com/tillahoffmann/cyfunc) because I needed to evaluate the likelihood of a distribution repeatedly. But the interface in the linked repo is still pretty clunky. See [here](https://github.com/tillahoffmann/shedding/blob/master/shedding/_util.pyx) for the application.

**Comment by gwerbin** [comment]
Just throwing my 2 cents in as a happy Cython user, this would be a great feature for developers of other libraries who want to use Cython either to implement their own functions or to wrap external libraries, and who want to expose their work as ufuncs.

See for example https://github.com/uber/h3-py/issues/141 and https://github.com/uber/h3-py/issues/205, where the authors of H3-Py implemented only a bare minimal subset of ufunc behavior because it wasn't obvious or easy how to use Numpy to do it.

**Comment by da-woods** [comment]
@gwerbin A few comments:
1. you can always test the preliminary implementation now (https://github.com/cython/cython/pull/4803),
2. it doesn't actually do anything that you can't do yourself (I think...) - it does a bit of auto-generation of Cython code but it's all code that a user could write. The main reason to do it in Cython that the Numpy interface is pretty confusing and that we can hide that from you

**Comment by gwerbin** [comment]
@da-woods Do you have an example of the generated Cython code? It would be very helpful to at least have an equivalent of this page https://numpy.org/doc/stable/user/c-info.ufunc-tutorial.html#example-numpy-ufunc-with-multiple-arguments-return-values in Cython.

I tried to browse your PR diff but the codebase is too unfamiliar to me and it would take me a very long time to work through it. I'm not much of a "Cython hacker" nor am I deeply familiar with C. My use cases tend to be pretty low on the complexity scale and my knowledge is correspondingly beginner-level.

**Comment by da-woods** [comment]
@gwerbin Check out my PR, go to this line (https://github.com/cython/cython/blob/c7ba0c83d7fa7c0db60742b117b9e0207493013f/Cython/Compiler/UFuncs.py#L156) and add `print(code.impl)` and that should show the generated utility code I hope.

Note that the one thing that doesn't work in multiple return types where one of the types is a PyObject. That's really a consequence of the syntax I've used than a fundamental block.

There's also a small amount of C utility code. Think that all could be written in Cython but isn't (mainly for convenience). I think you'd add `print(TempitaUtilityCode.load("UFuncConsts", "UFuncs_C.c", context=context).impl)` (near https://github.com/cython/cython/blob/c7ba0c83d7fa7c0db60742b117b9e0207493013f/Cython/Compiler/UFuncs.py#L230) to see that.

**Comment by jan-david-fischbach** [comment]
Hey All,
Is there an elegant way to use the `@cython.ufunc` decorator such that the original "C" functions remains existent, such that 
``` cython
# Test a ufunc calling another ufunc
@cython.ufunc
cdef (cnp.int64_t, cnp.int64_t) add_one_add_two(cnp.int64_t x) nogil:
    return x + 1, x + 2

@cython.ufunc
cdef cnp.int64_t add_one_add_two_and_multiply(cnp.int64_t x) nogil:
    cdef cnp.int64_t a1
    cdef cnp.int64_t a2 
    a1, a2 = add_one_add_two(x)
    return a1 * a2

def test_nested_ufunc():
    """
    >>> out = add_one_add_two_and_multiply(np.array([1, 2, 3], dtype=np.int64))
    >>> out
    array([ 6,   12, 20])
    """
```
would work? Best Regards JD

**Comment by da-woods** [comment]
There isn't a good solution for the "get to the underlying C function" except for the obvious workaround of writing it under another name:

```
cdef (cnp.int64_t, cnp.int64_t) add_one_add_two_impl(cnp.int64_t x) nogil:
    return x + 1, x + 2

@cython.ufunc
cdef (cnp.int64_t cnp.int64_t) add_one_add_two(cnp.int64 x) nogil:
    return add_one_add_two_impl(n)

@cython.ufunc
cdef cnp.int64_t add_one_add_two_and_multiply(cnp.int64_t x) nogil:
    cdef cnp.int64_t a1
    cdef cnp.int64_t a2 
    a1, a2 = add_one_add_two_impl(x)
    return a1 * a2
```

Practically the C compiler should inline it so there shouldn't be a runtime cost. But it's not as nice as it could be.
