### ISSUE TITLE
[BUG] prange has num_threads dependent results

### ISSUE THREAD

**Issue by lorentzenchr** [cython/cython#4761]
**Describe the bug**
The use of `prange` with `num_threads` set to different values produces different results.

**To Reproduce**
Code to reproduce the behaviour:
```cython
%%cython --compile-args=-Xpreprocessor --compile-args=-fopenmp --compile-args=-I/usr/local/opt/libomp/include --link-args=-Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION

import cython
from cython cimport floating
from cython.parallel import prange, parallel
import numpy as np

cimport numpy as np
np.import_array()

def gram_numpy(X):
    return X.T @ X

def gram_cython_parallel(floating[:, :] X, int n_threads=1):
    cdef:
        int n_samples = X.shape[0]
        int n_features = X.shape[1]
        int i, ii  # Cython does not like the same name for different loops => use i and ii
        int j, jj
        int k
        floating[:, ::1] out = np.zeros_like(X, shape=(n_features, n_features))  # C-contiguous

    with nogil, parallel(num_threads=n_threads):
        for k in prange(n_samples, schedule='static'):
            for i in range(n_features):
                for j in range(i, n_features):
                    out[i, j] += X[k, i] * X[k, j]  # THIS is the main computation, order should not matter.

    for ii in range(1, n_features):
        for jj in range(0, ii):
            out[ii, jj] = out[jj, ii]
        
    return np.asarray(out)
```
The following passes:
```python
rng = np.random.default_rng(0)
X = rng.standard_normal((5, 3), dtype=np.float64)

np.testing.assert_allclose(gram_cython_parallel(X, 1), gram_numpy(X))
```
This statements errors on my machine:
```python
np.testing.assert_allclose(gram_cython_parallel(X, 2), gram_numpy(X))
```

**Expected behavior**
Both statements should give the same result, i.e. `n_threads` should not have an influence on the result.

**Environment (please complete the following information):**
 - OS: macOS 12.3
 - Python version: 3.9.12 (via homebrew)
 - Cython version: 0.29.24
 - OpenMP: libomp 14.0.0

**Additional context**
None.

**Comment by scoder** [comment]
Your code uses `k` threads that all write to the same index positions `out[i, j]`. Depending on which thread comes first, you end up with one value or another in there, pretty unpredictable. The number of threads only changes the chances which thread wins.

**Comment by lorentzenchr** [comment]
The order does not (should not!) matter. In fact, this code works when you change the loop order (as long as `i` is before `j`, otherwise a minor modification is needed). On top, it gives correct results with a normal `range` replacing the `prange`. Maybe, I do not see the wood for the trees.

**Comment by 0dminnimda** [comment]
`out[i, j] +=` isn't just wrining to one memory address, but still it's affected by the race condition (while you're calculating the sum and writing the result to `out[i, j]` another thread has potentially already finished, so your starting `out[i, j]` isn't correct)

**Comment by lorentzenchr** [comment]
Thanks for clarifying. No, I feel a little stupid.
