### ISSUE TITLE
[BUG]  float data type problem in power funcion

### ISSUE THREAD

**Issue by xuezhicang** [cython/cython#4765]
**Describe the bug**
I am wondering whether the float data type inCython has a problem when we use the power function.

**To Reproduce**
Code to reproduce the behaviour:
```cython

import numpy as np
cimport numpy as np
cimport cython

from libc.math cimport pow as powerC

cdef extern from "math.h":
    float powerC(float x,float y) nogil

cdef float cal_val(int[:,:] test_mveiw):
    cdef Py_ssize_t SIZE_Y = test_mveiw.shape[0]
    cdef Py_ssize_t SIZE_X = test_mveiw.shape[1] 
    cdef float res = 0
    for i in range(SIZE_Y):
        for j in range(SIZE_X):
                res = res + powerC(test_mveiw[i,j],0.5)
    return res 

cdef float test(int[:,:] test_mveiw,float res):
    cdef Py_ssize_t SIZE_Y = test_mveiw.shape[0]
    cdef Py_ssize_t SIZE_X = test_mveiw.shape[1] 

    for i in range(SIZE_Y):
        for j in range(SIZE_X):
                res = res - powerC(test_mveiw[i,j],0.5)
    for i in range(SIZE_Y):
        for j in range(SIZE_X):
                res = res + powerC(test_mveiw[i,j],0.5
    return res
 


cdef int[:,:] test_mveiw = np.zeros((1419,1442),dtype=np.int32)
cdef float val=0
cdef float val_1=0
cdef Py_ssize_t SIZE_Y = test_mveiw.shape[0]
cdef Py_ssize_t SIZE_X = test_mveiw.shape[1]  
print("size",SIZE_Y,SIZE_X)
for i in range(SIZE_Y):
    for j in range(SIZE_X):
        test_mveiw[i,j] = 1000*j+i

val = cal_val(test_mveiw)
print(val)

val_1 = cal_val(test_mveiw)    
for qq in range(20):
    val_1 = test(test_mveiw,val)
print("difference",val-val_1)

val_2 = cal_val(test_mveiw)    
for qq in range(1):
    val_2 = test(test_mveiw,val)
print("difference",val-val_2)
```
The output is:
size 1419 1442
1475766386688.0
difference 3840.0
difference 3840.0

**Expected behavior**
The difference between the val and val_1 is very large. I am wondering whether the difference is not just caused by the data type precise.  My expect result is:

size 1419 1442
1475766386688.0
difference 0
difference 0

**Environment (please complete the following information):**
 - OS: [Windows]
 - Python version [3.8.8]
 - Cython version [0.29.23]

**Additional context**

If I use the double data type,  the results are correct. Since my data amount is large, the double data type make my program slow, so I still want to use the float data type.

Also, if the problem is caused by the precise of data type. Why the first result and second results are the same? I think the first one is updated more times, so the first result should have a larger error. 

Thank you for your time and help in advance.

**Comment by da-woods** [comment]
Please ask support questions on the Cython-users mailing list (https://groups.google.com/g/cython-users). This doesn't look like a Cython bug to me. It also doesn't look like code that will actually compile to demonstrate the issue.

**Comment by xuezhicang** [comment]
If the values are the same in the memory view, the results are correct. So I am wondering whether the problem is not caused by the data type precise but caused by other reasons.

'''cython
cdef int[:,:] test_mveiw = np.zeros((200,200),dtype=np.int32)#np.zeros((1419,1442),dtype=np.int32)
cdef float val=0
cdef float val_1=0
cdef Py_ssize_t SIZE_Y = test_mveiw.shape[0]
cdef Py_ssize_t SIZE_X = test_mveiw.shape[1]  
print("size",SIZE_Y,SIZE_X)
for i in range(SIZE_Y):
    for j in range(SIZE_X):
        test_mveiw[i,j] = 9527

val = cal_val(test_mveiw)

print(val)
val_1 = cal_val(test_mveiw)    
for qq in range(2):
    val_1 = test(test_mveiw,val)
print("difference",val-val_1)

val_2 = cal_val(test_mveiw)    
for qq in range(1):
    val_2 = test(test_mveiw,val)
print("difference",val-val_2)
'''

The output is:
size 1419 1442
1475766386688.0
difference 0
difference 0

**Comment by xuezhicang** [comment]
@da-woods Thank you for your help.

If the values in the memory view are the same (see my new comment), the results are correct. For this reason,  I am wondering if the problem is not caused by the precision of the float data type, but caused by a bug in the memory view.

**Comment by da-woods** [comment]
Reading values from a memoryview is pretty well-tested so I'd be surprised if there was a bug there. Why not try a version of the code that avoids the memoryview and just calculates the values as it goes.

I'm almost certain this is just float rounding errors.

**Comment by xuezhicang** [comment]
@da-woods Thank you for your help.

I am wondering why you are certain this is float rounding errors.

I construct a memory view. All the value is 9527 except one is 1234. 


```cython

cdef int[:,:] test_mveiw = np.zeros((200,200),dtype=np.int32)#np.zeros((1419,1442),dtype=np.int32)
cdef float val=0
cdef float val_1=0
cdef Py_ssize_t SIZE_Y = test_mveiw.shape[0]
cdef Py_ssize_t SIZE_X = test_mveiw.shape[1]  
print("size",SIZE_Y,SIZE_X)
for i in range(SIZE_Y):
    for j in range(SIZE_X):
            test_mveiw[i,j] = 9527 

test_mveiw[10,20] = 1234


val = cal_val(test_mveiw)

print(val)
val_1 = cal_val(test_mveiw)    
for qq in range(2):
    val_1 = test(test_mveiw,val)
print("difference",val-val_1)

val_2 = cal_val(test_mveiw)    
for qq in range(1):
    val_2 = test(test_mveiw,val)
print("difference",val-val_2)

```

The output is:
difference 0.25
difference 0.25


If we compare the difference in python:
```python
import numpy as np
print(np.float32(np.power(np.float32(1234),np.float32(0.5))) - np.float64(np.power(np.float64(1234),np.float64(0.5))))
```
the result is 1.7196068284874855e-06, which is about 145382 times smaller than the difference in my cython script. For this reason, I am wondering why you are certain this is just float rounding errors.
