### ISSUE TITLE
[BUG] Includes/libcpp/algorithm.pxd for latest tag 0.29.28 does not correspond to latest master

### ISSUE THREAD

**Issue by diptansu** [cython/cython#4766]
**Describe the bug**
`Includes/libcpp/algorithm.pxd` for latest tag 0.29.28 does not correspond to latest [master](https://github.com/cython/cython/blob/master/Cython/Includes/libcpp/algorithm.pxd). The master contains numerous algorithms, e.g. [transform](https://github.com/cython/cython/blob/master/Cython/Includes/libcpp/algorithm.pxd#L89-L100), etc. which are not present in the current latest version. I checked this by both installing the latest version and checking the `algorithm.pxd` file and also downloading the tag and checking the file included.

**To Reproduce**
Code to reproduce the behaviour:
Run this in a jupyter notebook:
```cython
%%cython -a -+ -3

from libcpp.string cimport string, npos
from libcpp.algorithm cimport transform
```

**Expected behavior**
No errors

Instead we get:
```

Error compiling Cython file:
------------------------------------------------------------
...

from libcpp.string cimport string, npos
from libcpp.algorithm cimport transform
^
------------------------------------------------------------
/home/ddas/.cache/ipython/cython/_cython_magic_d4345cddad97905427cc9a6732292667.pyx:3:0: 'libcpp/algorithm/transform.pxd' not found
```

**Environment (please complete the following information):**
 - OS: Windows. Jupyter running under wsl. I have also verified this on linux.
 - Python version [e.g. 3.9.12]
 - Cython version [e.g. 0.29.28]

**Comment by da-woods** [comment]
I think this is to be expected. At this stage new features are mostly going into the master branch and the 0.29.x branch is bug fixes only.

The .pxd files distributed with Cython don't do anything you can't do yourself so you can probably just copy the definitions you need from the master branch.

**Comment by da-woods** [comment]
With that said - those that use `&&` references won't work on Cython 0.29.x since it's a feature that's only in master
