### ISSUE TITLE
[BUG] binding=True causes a mysterious import error 

### ISSUE THREAD

**Issue by kwankyu** [cython/cython#4775]
This issue arose while we tried to turn on `binding=True` cython compiler option in SageMath 9.6.rc3:

https://trac.sagemath.org/ticket/26254#comment:64

The function `call_registered_function()` is defined in the file `src/sage/symbolic/pynac_function_impl.pxi`, which is included into `src/sage/symbolic/expression.pyx` by `include "pynac_function_impl.pxi"`.

Then the statement `from .expression import call_registered_function` **in the global scope** of `src/sage/symbolic/function.pyx` throws the exception

`ImportError: cannot import name call_registered_function`

This may be a bug on cython since we don't have this exception with the default `binding=False`. 

SageMath 9.6.rc3 uses python-3.10.3 and cython-0.29.28.

**Comment by da-woods** [comment]
To me this looks like a circular import issue possible? From the issue:

```
File "sage/symbolic/expression.pyx", line 1, in init sage.symbolic.expression
    # -*- coding: utf-8 -*-
  File "sage/symbolic/function.pyx", line 144, in init sage.symbolic.function
    from .expression import (
```

`expression` import `function` which imports `expression` (some of these imports may be generated by `cimport` though - I'm not sure).

With `binding=False` functions are defined in `PyModuleDef`. I think that means they exist very early in the module import process before the main module init function has run, and therefore you may get away with it. With `binding=True` they're generated in the module init function.

Therefore I provisionally don't think it's a Cython bug - it looks a lot like code that wouldn't work in Python either

**Comment by da-woods** [comment]
I think if you remove the line

```
from sage.symbolic.function cimport SymbolicFunction
```

it'll work. You don't look to actually use the cimport so you're losing nothing by removing it.

However I can't work out how the code is working at all with or without binding. At least on a simplified test locally it makes no difference if it's enabled for not.

**Comment by kwankyu** [comment]
> To me this looks like a circular import issue possible? 

Right. There was a circular import. We could fix the problem by changing the global imports to local imports. Your explanation below confirms that we did the right thing. 

> With `binding=False` functions are defined in `PyModuleDef`. I think that means they exist very early in the module import process before the main module init function has run, and therefore you may get away with it. With `binding=True` they're generated in the module init function.

So `binding=True` simply revealed the existing  circular import. Thank you for the explanation!

**Comment by da-woods** [comment]
> So `binding=True` simply revealed the existing circular import. Thank you for the explanation!

Possibly... I tried to make a cut-down example to replicate it myself and couldn't make it work with either version!

Anyway - hopefully you have enough information to fix it... I'll close this issue I think
