### ISSUE TITLE
[BUG] binding=True causes IndexError instead of TypeError in some situation

### ISSUE THREAD

**Issue by kwankyu** [cython/cython#4779]
This is another issue that arose while we tried to turn on binding=True cython compiler option in SageMath 9.6.rc3:

https://trac.sagemath.org/ticket/26254#comment:69

Note that with `binding=False`:
```
class NewClass:
    def parent(self):
        return 1

NewClass.parent()
...
TypeError: parent() missing 1 required positional argument: 'self'
```
```
%%cython
cdef class NewClass:
    def parent(self):
        return 1

NewClass.parent()
...
TypeError: unbound method NewClass.parent() needs an argument
```

With `binding=True`:
```
%%cython
cimport cython
@cython.binding(True)
cdef class NewClass:
    def parent(self):
        return 1

NewClass.parent()
...
IndexError: tuple index out of range
```

I think this is a bug of cython. It should raise `TypeError` if it should follow Python behavior. 

SageMath 9.6.rc3 uses python-3.10.3 and cython-0.29.28.

**Comment by da-woods** [comment]
It's fixed in the current master branch. The commit that fixed it was 54211e322a55b419ba5bf237d2d3ebba32c70d0d. That looks like a fairly substantial change and unlikely to be backported, but possibly the place where the error message comes from can be identified

**Comment by da-woods** [comment]
Probably in `__Pyx_CyFunction_CallAsMethod`

https://github.com/cython/cython/blob/74073417c4f7e616af0a139a55f790f1ec7fe728/Cython/Utility/CythonFunction.c#L655-L664.

It looks like it'd actually be a bug in the master branch on versions of Python that predate vectorcall - the same code exists in the master branch. On that basis is probably is worth fixing.

**Comment by kwankyu** [comment]
> It looks like it'd actually be a bug in the master branch on versions of Python that predate vectorcall - the same code exists in the master branch. On that basis is probably is worth fixing.

Thanks for fixing it. We will wait for a release of Cython free of this bug.
