### ISSUE TITLE
[BUG] Can't initialize dataclasses with keyword arguments

### ISSUE THREAD

**Issue by rnestler** [cython/cython#4787]
**Describe the bug**

Initializing dataclasses with keyword arguments leads to a `TypeError` exception.

**To Reproduce**
Code to reproduce the behaviour:
```cython
from dataclasses import dataclass

@dataclass
class Foo:
    name: str


NAMES = [
    Foo(name="bar")
]
```

After compilation with `cythonize -i -3 test.py` running this code will give a `TypeError: Foo.__init__() got an unexpected keyword argument 'name'`

**Expected behavior**
Code should work and not raise exception.

**Environment (please complete the following information):**
 - OS: Linux (ArchLinux)
 - Python version 3.10.4
 - Cython version 0.29.28

**Additional context**
https://github.com/rnestler/minimal-cython-example

**Comment by da-woods** [comment]
duplicate https://github.com/cython/cython/issues/2552 (there's some useful workarounds in that issue, but using the pre-release version is definitely your best option)
