### ISSUE TITLE
[BUG] Is swap meant to be in libcpp?

### ISSUE THREAD

**Issue by adam2392** [cython/cython#4791]
**Describe the bug**
I am trying to use c++'s `swap` function to swap two elements in a vector efficiently. However, I keep getting an error when building the file. For example, I see in this [online file](https://rd.yyrcd.com/2021-06-11-Accelerating%20Python%20on%20GPUs%20with%20nvc%2B%2B%20and%20Cython%20%7C%20NVIDIA%20Developer%20Blog.pdf) that `libcpp.algorithm cimport swap` should work. Is this an issue w/ this particular version?

I think(?) this is a bug, so wasn't sure if it was appropriate for the mailing list. Lmk if you need more information though.

**To Reproduce**
Code to reproduce the behaviour:
```cython
from libcpp.algorithm cimport swap

cdef void do_something():
        # construct an array to sample from mTry x n_features set of indices
        cdef vector[SIZE_t] indices_to_sample = vector[SIZE_t](max_features * n_non_zeros)
        cdef SIZE_t n = indices_to_sample.size()
        for i in range(0, n):
            indices_to_sample.push_back(i)

        cdef SIZE_t j
        cdef int* T1
        cdef int* T2  
        for i in range(0, n):
            j = rand_int(0, n - i, random_state)
            swap(&indices_to_sample[i], &indices_to_sample[j]) 
```

I build it and I get the following error:

```
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  from libc.stdlib cimport free
  from libc.stdlib cimport qsort
  from libc.string cimport memcpy
  from libc.string cimport memset
  from libcpp.vector cimport vector
  from libcpp.algorithm cimport Swap
  ^
  ------------------------------------------------------------

  sklearn/tree/_oblique_splitter.pyx:20:0: 'libcpp/algorithm/Swap.pxd' not found
```

**Expected behavior**
I would've thought it is in Cython...

**Environment (please complete the following information):**
 - OS: macOS
 - Python version 3.8.12
 - Cython version 0.29.28

```
(sklearn-dev) adam2392@adams-mbp scikit-learn % cython --version
Cython version 0.29.28
```
**Additional context**

**Comment by da-woods** [comment]
It seems to have been added in https://github.com/cython/cython/commit/008bc53c45d1131d0eedf5c1fe276f5808911681 (i.e. master branch only)

As ever, the pxd files in Cython don't do anything that you can't do yourself in a cdef extern, so just copy that one line if you need it
