### ISSUE TITLE
[ENH] Python class inherit from multiple cdef classes

### ISSUE THREAD

**Issue by mlguruz** [cython/cython#4795]
This feature is basically not functioning right now, even though it says that it is supported in the official documentation.

A minimal example like below will give error: `TypeError: multiple bases have instance lay-out conflict
`

Example:
```
cdef class A:

    cpdef void test1(self):
        pass
    

cdef class B:

    cpdef void test2(self):
        pass

class C(A, B):
    pass
``` 

It would be *very* helpful if this feature is supported.

**Comment by scoder** [comment]
Could you link to where the documentation says that? Maybe we can improve the wording there.

This is a general CPython limitation. You cannot have different extension types as super classes unless they have the same memory layout. Try, for example:
```python
>>> class X(list, dict): pass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: multiple bases have instance lay-out conflict
```

**Comment by mlguruz** [comment]
> Could you link to where the documentation says that? Maybe we can improve the wording there.
> 
> This is a general CPython limitation. You cannot have different extension types as super classes unless they have the same memory layout. Try, for example:
> 
> ```python
> >>> class X(list, dict): pass
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: multiple bases have instance lay-out conflict
> ```

I see... 

The doc I'm referring to is here: https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#subclassing

I says "...A Python class can inherit from multiple extension types provided that the usual Python rules for multiple inheritance are followed (i.e. **the C layouts of all the base classes must be compatible**)..." 

"*compatible*" seems a bit generic to me. Maybe an example will help?

**Comment by da-woods** [comment]
Compatible turns out to be very restrictive. For C extensions types it pretty much means that one of the bases has to be empty (def functions are allowed, but not cdef functions, since they generate a vtab pointer). (It isn't quite that simple, but it isn't far off...)

**Comment by mlguruz** [comment]
> 

Ok got it. and thanks for the clear explanation. Seems like this is not cython related but more of a cpython ENH .... 

Will close now.
