### ISSUE TITLE
[BUG] np.ndarray attributes won't compile with NPY_NO_DEPRECATED_API set

### ISSUE THREAD

**Issue by cmccully** [cython/cython#4805]
**Describe the bug**
Compilation error when accessing the shape of a numpy array and using define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION.

**To Reproduce**
Code to reproduce the behaviour:
```cython
# cython: boundscheck=False, nonecheck=False, wraparound=False, language_level=3, cdivision=True
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
import numpy as np
cimport numpy as np

np.import_array()

def medfilt3(np.ndarray[np.float32_t, ndim=2, mode='c', cast=True] d3):
    cdef int ny = d3.shape[0]
    return ny

```
This fails with 
```helloworld.c:1793:29: error: no member named 'dimensions' in 'struct tagPyArrayObject'
  __pyx_v_ny = (__pyx_v_d3->dimensions[0]);
```

**Expected behavior**
Successful compile.

**Environment (please complete the following information):**
 - OS: macOSX
 - Python version 3.9.12
 - Cython version 0.29.30

**Additional context**

**Comment by mattip** [comment]
If you use the cython3 alpha releases you can use that macro. With 0.29 this is expected behaviour.

**Comment by da-woods** [comment]
Closing - what Mattip says is correct. (We've also handed over maintenance of the Numpy pxd files to the Numpy project)

**Comment by cmccully** [comment]
Thanks for checking.
