### ISSUE TITLE
[DOCS] Projects using Cython

### ISSUE THREAD

**Issue by guzmanojero** [cython/cython#4806]
About: https://github.com/cython/cython/wiki/projects

The list of projects using Cython could be updated.
Both Pandas and Numpy use Cython.

**Pandas.**
https://github.com/pandas-dev/pandas
Cython 5.6%
https://github.com/pandas-dev/pandas/search?l=cython

**Numpy.**
https://github.com/numpy/numpy
Cython 0.9%
https://github.com/numpy/numpy/search?l=cython

**Scikit-Learn**
https://github.com/scikit-learn/scikit-learn
Cython 6.9%
https://github.com/scikit-learn/scikit-learn/search?l=cython

It's a good endorsement.

**Comment by da-woods** [comment]
That page is on a wiki - feel free to edit it :)

**Comment by guzmanojero** [comment]
Thanks!
