### ISSUE TITLE
[BUG] conditional compilation does not work for cimport

### ISSUE THREAD

**Issue by shakfu** [cython/cython#4832]
On cython version 0.29.30, while trying to conditionally include headers as per the recommended way in issue #4310, I have discovered that `cimport` doesn't respond to condition statements.

For example, in the following case, `cimport numpy as np` and ` np.import_array()` are activated even though `INCLUDE_NUMPY` is clearly False (as per the assert) and is defined as 0 in the prior `cdef extern`.

```cython

cdef extern from *:
    """
    #ifndef INCLUDE_NUMPY
    #define INCLUDE_NUMPY 0
    #endif
    """
    cdef bint INCLUDE_NUMPY


if INCLUDE_NUMPY:
    import numpy as np
    cimport numpy as np # <-- this still works somehow!
    np.import_array()   # <-- this still works somehow!

assert INCLUDE_NUMPY == 0
```

It seems that the only way to stop cimport from working is to use the deprecated `DEF` / `IF` combo as follows:

```cython

DEF INCLUDE_NUMPY = 0

IF INCLUDE_NUMPY:
    import numpy as np  
    cimport numpy as np # <-- now deactivated!
    np.import_array()   # <-- now deactivated!
```

Now, I'm confused. Why are `DEF` and `IF` being deprecated as per issue #4310 if the recommended alternative does not work?

**Comment by da-woods** [comment]
I'm relatively convinced `    np.import_array()   # <-- this still works somehow!` isn't actually called. That definitely looks to be in an `if` block in the generated C file.

You're hitting an awkward mix of runtime and compile-time behaviour:
*  `cimport`s have both compile-time and runtime behaviour so aren't simple to resolve with a runtime variable. It would be dangerous to disable the runtime behaviour when the compile-time behaviour still happens.
* Cython can't see into the `cdef extern from *` literal code block so it can't work out anything about its value at compile-time.

> Now, I'm confused. Why are `DEF` and `IF` being deprecated as per issue https://github.com/cython/cython/issues/4310 if the recommended alternative does not work?

`DEF` and `IF` aren't going anywhere particularly soon, and especially not until suitable alternatives exist and are easy to access so feel free to use them for now. We'd probably recommend https://github.com/cython/cython/issues/2596 as the more general approach to this, although it needs some work to be integrated so that it's convenient to use.

**Comment by shakfu** [comment]
@da-woods thanks for your feedback.

My particular use-case is that I'd like to programmatically include or exclude NUMPY headers and numpy related code depending on the availability of numpy on the user's system.

I can do this at compilation time, by checking if `import numpy; numpy.get_include()` returns a value, and I was trying to do it in the case above by setting a compile time definition such as `INCLUDE_NUMPY=1` to override `INCLUDE_NUMPY=0` and enable the inclusion of numpy related `import`, `cimport`, and conditional code.

Perhaps I'm wrong, but even if I use `DEF`, it doesn't seem to be possible to address the above use-case for some reason.

For example:

```cython
DEF INCLUDE_NUMPY = 0

IF INCLUDE_NUMPY:
    import numpy as np
    cimport numpy as np
    np.import_array()

IF INCLUDE_NUMPY:
    # some numpy-related code
    def check():
        return 1
```

Initially I thought I could override `INCLUDE_NUMPY` by setting some option at the `cythonize` level. `cythonize` gives three types of options:

```text
-X NAME=VALUE,..., --directive=NAME=VALUE,...
                        set a compiler directive
-E NAME=VALUE,..., --compile-time-env=NAME=VALUE,...
                        set a compile time environment variable
-s NAME=VALUE, --option=NAME=VALUE
```

But none of them allow an `INCLUDE_NUMPY=1` to work.  It looks like overriding a DEF compile time constant is not possible, which seems, at least to me, to be counterintuitive. 

I'm not sure how using a templating language would address this use case.

Why not just translate a DEF VARIABLE to:
```c
#ifndef VARIABLE
#define VARIABLE
#endif
```

or at least facilitate the idiom I used in my first post?

**Comment by da-woods** [comment]
> But none of them allow an INCLUDE_NUMPY=1 to work. It looks like overriding a DEF compile time constant is not possible, which seems, at least to me, to be counterintuitive.

I'm surprised at that. I'd think it's the `-E` option that should work. Possibly it doesn't *override* any value you provide in your code.

> I'm not sure how using a templating language would address this use case.

It'd be fairly similar e.g.

```
{{if some_compile_time_value}}
import numpy
cimport numpy
np.import_array()
{{endif}}
```

(with convenient ways to set `some_compile_time_value` in setup.py)

> Why not just translate ... [to `#define VARIABLE`]

If you didn't have Numpy installed when you built it the `cimport numpy` would have already failed when it doesn't find the pxd file. So whatever you did, Cython needs to know to ignore the code itself

**Comment by shakfu** [comment]
Thanks for your reply

> I'm surprised at that. I'd think it's the -E option that should work. Possibly it doesn't override any value you provide in your code.

I can't believe I missed that. You are absolutely right 😊 

If I dropped the `DEF` and only kept the `IF`, it works provided I set the `cython -E` option appropriately.

Well that resolves it then. Thanks very much for your help and guidance and for fighting for `IF` and `DEF` to stay around a little longer. 👍

**Comment by pitrou** [comment]
Just a heads up that the `IF` deprecation is [biting us](https://github.com/apache/arrow/pull/34616#issuecomment-1752716116) in Apache Arrow, and any potential workaround seems much more cumbersome and maintenance-heavy that the `IF`-based solution.

Unless it is really a maintenance burden for Cython, it would be nice to deprecate this feature.

**Comment by jorisvandenbossche** [comment]
@pitrou you might want to move that comment to https://github.com/cython/cython/issues/4310

**Comment by pitrou** [comment]
Woops, done.
