### ISSUE TITLE
[BUG] cdef `except -1` silently ignored by cpdef caller and not raised!

### ISSUE THREAD

**Issue by mlguruz** [cython/cython#4833]
**Describe the bug**
`cpdef` function calling `cdef` function that raises in case of a return value of -1 would silently ignore the exception and simply skip executing the chunk of code starting from the `cdef` function.

This IMO is a *very* bad behavior/feature/bug, b/c it makes debugging very hard and confusing.

**To Reproduce**
Code to reproduce the behaviour:
```
cdef class Dummy:

    cdef int test(self) nogil except -1:
        return -1   # should raise


cpdef void test() except *:
    cdef Dummy d = Dummy()

    print("before d.test")
    d.test()
    print("called d.test")
```

**Expected behavior**
I would expect `d.test()` to raise and that exception gets propagated to the caller `test` as well.

Instead, if you run the above, anything after line `d.test()` (inclusive) is simply ignored w/o any error/warning msgs!

**Environment (please complete the following information):**
 - OS: Linux (Centos)
 - Python version 3.8
 - Cython version 3.0a10

**Additional context**

**Comment by da-woods** [comment]
No. You're misunderstanding how it works.

```
cdef int test(self) nogil except -1:
    return -1   # should raise
```

What this says is: if Cython raises an error, then it'll use a value of -1 to indicate it to the caller.
It does not say that a value of -1 is converted into an exception. All `return -1` will do is confuse the caller (because it expects an exception to be set).

What you want is something like:
```
cdef int test(self) nogil except -1:
    raise ValueError
```

**Comment by mlguruz** [comment]
> No. You're misunderstanding how it works.
> 
> ```
> cdef int test(self) nogil except -1:
>     return -1   # should raise
> ```
> 
> What this says is: if Cython raises an error, then it'll use a value of -1 to indicate it to the caller. It does not say that a value of -1 is converted into an exception. All `return -1` will do is confuse the caller (because it expects an exception to be set).
> 
> What you want is something like:
> 
> ```
> cdef int test(self) nogil except -1:
>     raise ValueError
> ```

So `except -1` is just a way for caller to realize that it needs to propagate the exception raised inside the `cdef` function. 

If there's no exception detected, it behaves like a normal `cdef` function (i.e. just returns -1 and that's it)? 

But then why `print("called d.test")` part of the example above was skipped since there's no exception raised.

**Comment by da-woods** [comment]
> So except -1 is just a way for caller to realize that it needs to propagate the exception raised inside the cdef function.

Yes.

> If there's no exception detected, it behaves like a normal cdef function (i.e. just returns -1 and that's it)?

This really isn't well-defined. It expects there to be an exception if you return -1. It may or may not check. You shouldn't rely on it.

If `-1` is a legitimate value to return then you should use `except ?-1` instead (which says "a value of -1 might be an exception")

**Comment by mlguruz** [comment]
> except ?-1

I see... so let me summarize to make sure:

First of all, picking `except -1` over `except *` (c only. no c++) is largely due the function return type (i.e. `int`) here, so faster (i.e. only check one value), and it's *only a signal* to the caller for checking and propagating exception(s). 

If, for example, we wanna to *raise* if an index is -1, re-using the example above, we should just `raise` inside the `cdef` function to be safe, instead of `return -1` and counting on the caller to *treat* it as an exception (which it won't).  

Finally, the reason why I saw the weird behavior (to me) above that the function runs but everything after `d.test()` is ignored, is b/c I was basically doing something **undefined**, i.e. telling the caller that there's an exception, but there's not, which is undefined.

**Comment by da-woods** [comment]
Yes, it looks like you understand it correctly now.

**Comment by mlguruz** [comment]
> Yes, it looks like you understand it correctly now.

Thank you very much! Really appreciate the great help!
