### ISSUE TITLE
[BUG] Compile error when parameter in property setter has same name as the property (regression 3.0a9 -> 3.0a10)

### ISSUE THREAD

**Issue by danrauch** [cython/cython#4836]
**Describe the bug**

When a class property setter parameter has the same name as the property itself, compiling normal Python code fails with 

`cdef variable 'value' declared after it is used`

Does not happen with Cython 3.0a9 or earlier.

**To Reproduce**

Trying to compile

```cython
class TestCythonProperty:

    def __init__(self) -> None:
        self._value = 0

    @property
    def value(self) -> int:
        return self._value

    @value.setter
    def value(self, value: int):
        self._value = value
```

with Cython 3.0a10 results in

```bash
Cython version 3.0.0a10

Error compiling Cython file:
------------------------------------------------------------
...
    @property
    def value(self) -> int:
        return self._value

    @value.setter
    def value(self, value: int):
                   ^
------------------------------------------------------------

test_cython.py:13:20: cdef variable 'value' declared after it is used
```

**Expected behavior**

Code is compiling

**Environment:**

 - OS: Linux, Windows
 - Python version: tried with 3.8 and 3.10
 - Cython version: since 3.0a10

**Comment by da-woods** [comment]
Looks like it's 8c7b0f3fb745aa7bd0afedfbeb862eecc5fdff0c that broke it
