### ISSUE TITLE
[BUG] Wrong generation of wrapped c function signature

### ISSUE THREAD

**Issue by flotang-gtt** [cython/cython#4839]
**Describe the bug**
Wrapping a fortran/C dll on windows does not give expected results. Inspecting the Cython generated code, it looks suspicious.

**To Reproduce**
Since it deals with a proprietary dll I am not allowed to share, I'll try to summarize. Feel free to ask for more details. All the code I give here is actual copy-paste from my codebase - I may mangle names to not violate the proprietary character

The F77 based dll (not that is matters, I guess) exposes the following interface
```interface.h: 	int tqifct(int param1, const char* characterarray,  int* param2, int* param3, int* param4);

interface.c: 	void __stdcall FUNCTION(int param1, const char * characterarray, size_t characterarray_len, int* param2, int* param3, int* param4);
```
this is absolutely fine to being called from a c program and works.

However, the cythonized module does not behave as expected. Since the call-by-reference nature of the fortran code requires it, the 'wrapping' cython code is as follows (for namespace clashing reasons, the signatures are rewritten in a interface.pxd and imported. This works absolutely fine for the 100s of other routines in the same dll):

```    cdef int param4
    cdef int param3
    cdef int param2
    cdef char characterarray[80] 

    FUNCTION(param1+1, characterarray, &param2, &param3, &param4)
```

**Expected behavior**
The call-by-reference set values param2, param3 and param4 are written completely correctly. However, the characterarray is always an empty string.

Since there are plenty of routines with very similar signatures that are all working, I looked at the cython-generated .c file, which looks as follows:

```  /* "file.pyx":2713
 * 
 * 
 * def function(int param1):             # <<<<<<<<<<<<<<
 */
  __pyx_tuple__180 = PyTuple_Pack(6, __pyx_n_s_param1, __pyx_n_s_param1, __pyx_n_s_param4, __pyx_n_s_param3, __pyx_n_s_param2, __pyx_n_s_characterarray); if (unlikely(!__pyx_tuple__180)) __PYX_ERR(0, 2713, __pyx_L1_error)
```

does this only look wrong to me? Looking at other routines (again, with very similar signatures), the order of the parameters of the c file and of the pyx file are not in that order.

**Environment:**
 - OS: Windows
 - Python version 3.9.12
 - Cython version 0.29.30

**Comment by da-woods** [comment]
```
__pyx_tuple__180 = PyTuple_Pack(6, __pyx_n_s_param1, __pyx_n_s_param1, __pyx_n_s_param4, __pyx_n_s_param3, __pyx_n_s_param2, __pyx_n_s_characterarray); if (unlikely(!__pyx_tuple__180)) __PYX_ERR(0, 2713, __pyx_L1_error)
```

This is setting up some tuple that's used in making the function introspectable. It didn't affect whether the code is called correctly. I don't have enough context to know if it's right or wrong. It might just be a list of variable names in no real order.

The one thing I do notice is that you seem to have left out the character array length from your call. I'll close it on the basis that this looks very likely to be your problem. I can reopen if that isn't the issue and we believe it's a genuine Cython bug.
