### ISSUE TITLE
[BUG] Fused type not subscriptable in uncompiled pure python

### ISSUE THREAD

**Issue by pfebrer** [cython/cython#4840]
**Describe the bug**
Fused type can't be subscribed in pure python syntax when `cython.compiled == False`

**To Reproduce**
Code to reproduce the behaviour:
```python
import cython

int_or_float = cython.fused_type(cython.int, cython.float)

def func(num: int_or_float[:]):
    ...
```

Gives error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [302], in <module>
      1 import cython
      3 int_or_float = cython.fused_type(cython.int, cython.float)
----> 5 def func(num: int_or_float[:]):
      6     ...

TypeError: '_FusedType' object is not subscriptable
```

**Expected behavior**
`Cython.Shadow` should implement this so that it doesn't raise an error (?).

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: '3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) \n[GCC 9.4.0]'
 - Cython version: 3.0.0a10

**Comment by da-woods** [comment]
PR welcome

**Comment by da-woods** [comment]
0.29.x backport is https://github.com/cython/cython/commit/a7d98eeafac9aaaa8825fd471be38172ee0b259c
