### ISSUE TITLE
[BUG] Broken tuple multiplication behavior

### ISSUE THREAD

**Issue by vovaf709** [cython/cython#4861]
**Describe the bug**
Tuple multiplication doesn't work correctly while it is unpacked into list. It produces list with only one copy of initial tuple and also doesn't throw exception when multiplier is of float type.

**To Reproduce**
Code to reproduce the behaviour:
```cython
[*(1,) * 1]  # [1,]
[*(1,) * 2]  # [1,]
[*(1,) * 3]  # [1,]
[*(1,) * 1.5]  # [1,]
```

**Expected behavior**
It is expected to work identically to multiplication of lists which works fine in cython:
```cython
[*[1,] * 1]  # [1,]
[*[1,] * 2]  # [1, 1]
[*[1,] * 3]  # [1, 1, 1]
[*[1,] * 1.5]  # TypeError: can't multiply sequence by non-int of type 'float'
```

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 20.04.3 LTS
 - Python version 3.9.5
 - Cython version 0.29.30

**Comment by da-woods** [comment]
This was closed in https://github.com/cython/cython/commit/5c900c59d03f23f7329d6e68e114e4a277112916
