### ISSUE TITLE
[BUG] Inaccuracy in "sharing declarations" docs

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4862]
> Note

> When a module exports a C function in this way, an object appears in the module dictionary under the function’s name. However, you can’t make use of this object from Python, nor can you use it from Cython using a normal import statement; you have to use cimport

This doesn't seem to be true. Taking the "volume" example from the documentation and running `dir(volume)` gives

```
['__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__pyx_capi__', '__spec__', '__test__']
```

**Comment by scoder** [comment]
Right. We use __pyx_capi__ for this instead of single per name entries.

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/530e370ff3d4d43e1969dcc821f65bf33a99f252
