### ISSUE TITLE
Update various bits of the Cython FAQ for Cython 3

### ISSUE THREAD

**Issue by scoder** [cython/cython#4867]
The Cython FAQ has been slowly bit rotting for years, but is now getting a huge blow by the developments for Cython 3.0.

https://github.com/cython/cython/wiki/FAQ

There are various bits of information sprinkled in there that are no longer true or for which better solutions exist now. This can be done iteratively, question by question, and whenever someone looks into it, but some effort needs to be put into it to make it more helpful again.

**Comment by da-woods** [comment]
It's probably time to remove most of the comparisons to Pyrex. It's obviously worth acknowledging as the foundation of Cython, but I don't think anyone is trying to decide whether to use Cython or Pyrex at the moment

**Comment by Bluenix2** [comment]
Instead, most people will probably wonder how it is different to MypyC.

**Comment by da-woods** [comment]
There's a bit of comparison to mypyc (and other tools) in the readme file I believe (i.e. information spread in loads of different places)

**Comment by h-vetinari** [comment]
Now that #5374 is merged, should we delete https://github.com/cython/cython/wiki/FAQ from the wiki?

**Comment by da-woods** [comment]
> Now that #5374 is merged, should we delete https://github.com/cython/cython/wiki/FAQ from the wiki?

Just done that (deleted the text and replaced it with a link)

**Comment by scoder** [comment]
I think this is done, mostly, so let's close the ticket.
