### ISSUE TITLE
[BUG] 'cython' is not a package (docs)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [cython/cython#4870]
[Pure Python](https://docs.cython.org/en/latest/src/tutorial/array.html#safe-usage-with-memory-views)

```python
from cython.cimports.cpython import array
import array
```

But `cython` is `cython.py`, also no clue why two `array` imports. Doesn't compile via `setup.py` either (from `.pyx`). Couldn't find an explanation in the basic tutorial. Outdated docs?

cython 0.29.24, Python 3.8.12, Windows 10, `conda install -c conda-forge cython`.

**Comment by da-woods** [comment]
> Outdated docs?

No. The opposite. What you're trying only works in the Cython 3 alpha releases, not the 0.29.x branch.

There's a link to the docs for that at the top of the page https://docs.cython.org/en/stable/src/tutorial/array.html

**Comment by da-woods** [comment]
On 0.29.x you have to use `from cpython cimport array` which isn't isn't 100% "pure Python" compatible
