### ISSUE TITLE
Symbol Undefined...

### ISSUE THREAD

**Issue by bitmodeler** [cython/cython#4874]
I have read multiple examples for generating an so library using cython's pure python interface, and then later calling a function in it. THE FUNCTION IS NOT GETTING DEFINED IN THE SO!

- The pure python code:
```
#cython: language_level=3

import cython

@cython.cfunc
@cython.returns(cython.int)
@cython.locals(a=cython.int)
def blah(a):
    return 42
```
- The cython command:
`cython3 test.py`
- The gcc step:
```gcc -fpic `python3-config --cflags` -o test.o -c test.c```
- generate an so from the compilation output:
```gcc -shared -o test.so test.o `python3-config --libs` ```
- List the entrypoints in the so:
```
nm -D test.so|less
# (I'm not seeing the function "blah" there!)
```
- Try accessing the so:
```
python3
from ctypes import CDLL
so=CDLL('./test.so')
dir(so)
['_FuncPtr', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_func_flags_', '_func_restype_', '_handle', '_name'] 
# NO "blah" function!
```

All the pure python examples take it as a given that it will show up.

cython version:  0.29.30
python version: 3.9.2
gcc version: 10.2.1
ctypes version: 1.1.0
OS: Debian 11

**Comment by 0dminnimda** [comment]
Cython is compiling your code into python callable modules, it does not include any symbols for c calls.
You can use compiled code like this
```python
from blah_file import blah
blah(5)
```
And my suggestion is to use setuptools if you want to compile python collable module.
Only need to use c compiler directly is if you are compiling with the `--embed` option.

**Comment by 0dminnimda** [comment]
What are trying to achieve with that?

**Comment by bitmodeler** [comment]
Make a shared library of compiled functions derived from a python module that will be fastER than doing python (the code there of course being a trivial example; the blah function might be tons of iterative code at some point...)

**Comment by 0dminnimda** [comment]
> library of compiled functions derived from a python module that will be fastER than doing python

Cython does exactly that and if you don't need to call it from c than just import compiled cython module and that's it.

Try to follow this page https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html
It explains everything in great details.

**Comment by bitmodeler** [comment]
So to generate an so, I guess I want to do the setup.py with the cythonize call.

They are doing it with a pyx for input; can I pass a pure-python py file?

[I found 2 online examples doing it the gcc way I listed above; I figured once you have the c file generated by cython, the function call representing the call to the python function should be exposed thanks to those decorators I used above and found online...]

And: thanks so far...

**Comment by 0dminnimda** [comment]
> can I pass a pure-python py file?

Yes, you can

> [I found 2 online examples doing it the gcc way I listed above; I figured once you have the c file generated by cython, the function call representing the call to the python function should be exposed thanks to those decorators I used above and found online...]

It's always a good idea to first try to read the official documentation ^-^

**Comment by bitmodeler** [comment]
ACK+thanks

**Comment by bitmodeler** [comment]
After doing it the cythonize way, I found your advice to just to do an import of the so worked. So the issue was not the way I was building the so; that was being done alright. It was the CTYPES invocation that was not working. When I try a CDLL with the cythonize built one, that also doesn't see the blah function in the so.

I appreciate that the import of an so works; but given that those ctypes/CDLL examples for so's were online, is there a way to invoke the function in an so using ctypes? Just curious. If you don't know, I can dig...

**Comment by 0dminnimda** [comment]
> is there a way to invoke the function in an so using ctypes?

Cython was never supposed to support this. And even if it were supported, you would not get anything from it. Rather your code will become messier and more difficult to understand. Therefore,  I would recommend to adhere to imports if you want to use Cython.

**Comment by bitmodeler** [comment]
will do...

**Comment by bitmodeler** [comment]
I checked and didn't see a mangled blah entrypoint, nothing with blah; but you're right: cython probably used to expose the functions in a simple manner such that ctypes could be used to call them. Now, it's a lot more complicated; so you have to rely on an import which has the more complicated loading baked in and done for you.

Computers: the illusion of simplicity...

**Comment by da-woods** [comment]
Hi. The bug tracker is really for bug and feature requests to support the development of Cython. The preferred user support forum is the Cython users mailing list (https://groups.google.com/g/cython-users).

**Comment by scoder** [comment]
There's a "public" modifier to expose symbols. Not sure if that's available in Python code or limited to Cython syntax, though.
