### ISSUE TITLE
[BUG] Doc ambiguity

### ISSUE THREAD

**Issue by gentlegiantJGC** [cython/cython#4875]
**Describe the bug**
I think there might be a typo in the documentation on error return values.
https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values

This might also be me misunderstanding something but it seems to contradict itself.

`While this is always the case for C functions, functions defined as C functions or cpdef/@ccall functions can return arbitrary C types, which do not have such a well-defined error return value.`

If it is correct it could do with some clarification because it is a bit confusing.

**Comment by da-woods** [comment]
I think you're right. I think it should start

> While this is always the case for Python functions, [...]

It used to read

> While this is always the case for `def` functions, [...]

and I think was mixed up during the "pure Pythonizing" of that bit of documentation.
