### ISSUE TITLE
[BUG] pxd file ignored when compiled using pip/setuptools

### ISSUE THREAD

**Issue by mCodingLLC** [cython/cython#4880]
I have a project layout like this
```
src
    cymod
        cymod.py
        cymod.pxd
pyproject.toml
setup.cfg
setup.py
```

If I use `cython -3 -a src/cymod/cymod.py` cython correctly finds the `.pxd` file and in the annotation report I can see that a normal `def` function in `cymod.py` that is marked as `cdef` in the `.pxd` has no Python interaction, and trying to use the function from python results in an error (as expected).

However, if I use `python setup.py build_ext` or `pip install .` the report shows that the same function is marked as having Python interaction, and the function is accessible from python, indicating that the `.pxd` file was ignored.

I've tested this in Cython 0.29.30 as well as 3.0.0a10, and it also does not make a difference whether I use a `.py` file or a `.pyx` file, I just happen to be using a `.py` file. My best guess is that the `cythonize` function is the culprit.

Edit: when using a `.pyx` file the `cython` command produces an error because the `.pyx` does not match the `.pyd`, so the setup or pip command should fail as well, but they do not because the `.pyd` is ignored.

**Important edit**: If the string `"src/cymod/cymod.py"` is passed directly to `cythonize` rather than the list of `Extension` objects, then it works as expected.

Relevant files:

setup.py
```python3
from Cython.Build import cythonize
from setuptools import setup, Extension, find_packages

sources = ['src/cymod/cymod.py']

extension = Extension(
    "cymod",
    sources=sources,
)

setup(
    ext_modules=cythonize(
        [extension],
        language_level=3,
        force=True,
        annotate=True,
    ),
    packages=find_packages()
)
```

setup.cfg
```
[metadata]
name = cymod
version = 0.0.1

[options]
package_dir =
    =src
python_requires = >=3.7
zip_safe = no
```

pyproject.toml
```
[build-system]
requires = ["setuptools>=62.0", "wheel", "Cython"]
build-backend = "setuptools.build_meta"
```

cymod.py
```python3
def myfunction(x, y=2):
    a = x - y
    return a + x * y


def _helper(a):
    return a + 1


class A:
    def __init__(self, b=0):
        self.a = 3
        self.b = b

    def foo(self, x):
        print(x + _helper(1.0))

```

cymod.pxd
```cython
cpdef int myfunction(int x, int y= *)
cdef double _helper(double a)

cdef class A:
    cdef public int a, b
    cpdef foo(self, double x)

```

**Expected behavior**
The compiled cython module, whether compiled with `cython` or `setup.py build_ext` or `pip install` should behave the same in all cases and find the `.pxd` sitting next to the `.py` file

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version 3.10
 - Cython version 0.29.30

**Comment by mCodingLLC** [comment]
Found two fixes:
delete the `__init__.py` that I forgot to mention in `src/cymod`, or
leave the `__init__.py` and change the name of the extension to `cymod.cymod`.

Not entirely sure but since presence of init file makes a difference this might be intended behavior. Closing as this seems like a me issue, though I hope this proves useful for others.

**Comment by 0dminnimda** [comment]
This seems like a bug, presence of `__init__.py` should not make cython ignore the `.pxd`

**Comment by scoder** [comment]
Not sure if Cython 3.0 still behaves the same here (it seems reasonable to look for a .pxd file next to the .py/.pyx file), but the project layout was wrong either way. If you have a module in the package, it should get compiled as module in that package. The lookup of related files is not the only impact of that, there are a few places in the module where we use the fully qualified module name. Fixing the project layout is the correct way to resolve this.

**Comment by vbargsten** [comment]
> This seems like a bug, presence of `__init__.py` should not make cython ignore the `.pxd`

@scoder @0dminnimda 

I have a very similar issue. After many trials and long time wondering why my definitions in the `.pxd` file are unknown, the  `__init__.py` -- maybe related with my directory structure -- is the problem. I'm trying to make a native namespace package (the namespace module does not have an `__init__.py`).

This does **not** work with `Cython version 0.29.28`, the definitions of the `.pxd` are unknown in the `.pyx`.
```
namespace_pkg
└── model
    ├── cymodel.pxd
    ├── cymodel.pyx
    └── __init__.py

```

Renaming `__init__.py` to `__init__.py.bak` works and gives:
```
namespace_pkg
└── model
    ├── cymodel.c
    ├── cymodel.cpython-310-x86_64-linux-gnu.so
    ├── cymodel.pxd
    ├── cymodel.pyx
    └── __init__.py.bak

```

However, the `__init__.py` is needed here. I renamed the extension module already from model to cymodel to avoid potential problems.

**Comment by scoder** [comment]
> `Cython version 0.29.28`

That version is really old an outdated. Please try with the latest 0.29.x and 3.0beta releases.
