### ISSUE TITLE
Should `cython.declare`, `cython.pointer` and so on be strictly considered not `in_c_type_context`?

### ISSUE THREAD

**Issue by scoder** [cython/cython#4882]
Should `cython.declare`, `cython.pointer` and so on be strictly considered not `in_c_type_context`?  At least for .py files?

_Originally posted by @0dminnimda in https://github.com/cython/cython/issues/4606#issuecomment-1179806535_

**Comment by scoder** [comment]
> Should `cython.declare`, `cython.pointer` and so on be strictly considered not `in_c_type_context`? At least for .py files?

That is a very good question. There shouldn't be a difference between .py and .pyx files here. But I can see that these functions have issues. It seems easy for `cython.pointer()`, which always needs a C type as argument. The same might apply to `cython.typedef()` and maybe other C-ish operations. But what is the meaning of
```python
x = cython.declare(int)
y: int
```
The second definitely refers to a Python `int`, but the first? The difference is that the first declares a static variable (when used globally), whereas the second only declares a regular Python global variable. That difference goes away for local variables, though.

My guess is that it should be rare for users to mix both inside of functions, but there seems to be benefit in using both at the global module level. It doesn't feel wrong to expect C types for a static C variable. But it's probably a gotcha where code doesn't quite do what you might expect when you look at it.

**Comment by da-woods** [comment]
To me the difference is intent. We treat

```
x: int
```
as being a Python variable because (a) a Python int and a C int aren't quite the same, and (b) we don't know that the annotation was intended for Cython - it might just have been someone documenting their code.

```
x = cython.declare(int)
```
seems pretty clearly intended for Cython (like `cdef`) so I'd treat it as a C int.

**Comment by 0dminnimda** [comment]
For me cython.declare, cython.pointer etc seems like a python context (not a special cython syntax)
So if we have `cython.type_x` as an argument, it should be a c type and if we have `type_x` it should be python-to-c type as in annotations.

Here is an example #4298

**Comment by scoder** [comment]
I agree with @da-woods that the main distinction point is currently user intent, and we should leave it at that. ISTM that `cython.declare(int)` now interprets `int` as C int, which is the intended behaviour. I added a test.
https://github.com/cython/cython/commit/6414a07ec88b60d604daf0e51fd850ee974afdcb
