### ISSUE TITLE
[BUG]: `int` function argument annotation does not allow numpy integers on main 

### ISSUE THREAD

**Issue by mroeschke** [cython/cython#4885]
**Describe the bug**

Following https://github.com/cython/cython/commit/31d40c8c62acef9509675155fe5b5bb8e48dba5a, it appears that annotating functions with `int` changes the behavior when passing numpy integer types

**To Reproduce**
Code to reproduce the behaviour:

Before:
```
In [1]: %load_ext Cython

In [2]: %%cython
   ...: def f(x: int):
   ...:     return x
   ...:
ld: warning: -pie being ignored. It is only used when linking a main executable

In [3]: import numpy as np

In [4]: f(np.int64(1))
Out[4]: 1

% conda list cython
# Name                    Version                   Build  Channel
cython                    0.29.30         py310hd4537e4_0    conda-forge
```

After:
```
In [1]: %load_ext Cython

In [3]: %%cython
   ...: def f(x: int):
   ...:     return x
   ...:

In [4]: import numpy as np

In [5]: f(np.int64(1))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 f(np.int64(1))

TypeError: Argument 'x' has incorrect type (expected int, got numpy.int64)


% conda list cython
# Name                    Version                   Build  Channel
cython                    3.0.0a10                 pypi_0    pypi
```

**Expected behavior**

Not sure if this is expected behavior, but prior I would expect annotating arguments with `: int` to also accept numpy types

**Environment (please complete the following information):**
 - OS: macOS
 - Python version: 3.10
 - Cython version: https://github.com/cython/cython/commit/31d40c8c62acef9509675155fe5b5bb8e48dba5a

**Additional context**

**Comment by scoder** [comment]
This behaviour is correct. NumPy's `int64` is not a subtype of `int`.
```python
>>> import numpy
>>> numpy.int64
<class 'numpy.int64'>
>>> numpy.int64.__mro__
(<class 'numpy.int64'>, <class 'numpy.signedinteger'>, <class 'numpy.integer'>, <class 'numpy.number'>, <class 'numpy.generic'>, <class 'object'>)
>>> isinstance(numpy.int64(1), int)
False
```
(NumPy 0.17.4, Python 3.8.10)

The difference is that Cython 0.x did not take type annotations with Python's `int` type into account, at all.

**Comment by mroeschke** [comment]
Okay that is reasonable. So prior to https://github.com/cython/cython/commit/31d40c8c62acef9509675155fe5b5bb8e48dba5a `: int` was incorrectly accepting/ignoring(?) numpy types?

**Comment by scoder** [comment]
> Okay that is reasonable. So prior to [31d40c8](https://github.com/cython/cython/commit/31d40c8c62acef9509675155fe5b5bb8e48dba5a) `: int` was incorrectly accepting/ignoring(?) numpy types?

Can't say if that's the change ID, but you probably tried it. Yes, it was ignored before (in Cython 0.x) and not rejected.

I don't know right now if rejecting is the correct thing to do (depends on whether it still accepts subtypes), but in any case, it's your code that need fixing here. Thanks for bringing this up, though. It's worth testing on our side whether the new behaviour is correct as it is now.

**Comment by da-woods** [comment]
Kind of related to this: would it make sense to be able to disable annotation typing on a per-function or per-class basis? I can't see any good reason why it shouldn't be possible, and it lets people turn it off locally if/when they disagree on Cython's interpretation of the rules?

**Comment by scoder** [comment]
> disable annotation typing on a per-function or per-class basis

 Yes, let's allow that.
