### ISSUE TITLE
[BUG] Cannot inspect cythonized generator functions as such (`co_flags` don't have `CO_GENERATOR`)

### ISSUE THREAD

**Issue by tlambert03** [cython/cython#4888]
**Describe the bug**
Generator  functions lose inspection after compiling

**To Reproduce**
Code to reproduce the behaviour:

```python
def func():
    yield 1
```

when uncompiled:

```python
In [1]: import inspect

In [2]: inspect.isgenerator(func())
Out[2]: True

In [3]: inspect.isgeneratorfunction(func)
Out[3]: True

In [4]: func.__code__.co_flags
Out[4]: 16777315
```

after being cythonized
```python
In [3]: inspect.isgenerator(func())
Out[3]: True

In [4]: inspect.isgeneratorfunction(func)
Out[4]: False

In [5]: func.__code__.co_flags
Out[5]: 67

In [6]: type(func())
Out[6]: <class '_cython_3_0_0a10.generator'>

```

**Expected behavior**
Im not sure if this type of inspection is possible with `cython_function_or_method`, but I was hoping to be able to tell if a given function is a generatorfunction or not 

**Environment (please complete the following information):**
 - OS: tested on mac and linux
 - Python version tested on 3.9 and 3.10
 - Cython version [e.g. 3_0_0a10]

**Additional context**

**Comment by da-woods** [comment]
This isn't identical but I suspect it's related https://github.com/cython/cython/issues/2273

Some of the same arguments may apply, that CPython may try to use the code object based on these flags

**Comment by tlambert03** [comment]
yep thanks. it's exactly the same issue, but applied to `CO_GENERATOR` instead of `CO_COROUTINE`.  I'll have a look around that issue and linked issues and see what can be done/make a PR

**Comment by scoder** [comment]
I looked through the usages of `CO_COROUTINE` in CPython (main) and they look safe, except for this one, which I don't quite understand yet:

https://github.com/python/cpython/blob/50b9a7762f06335277d9962edc8d39498601a4e4/Objects/frameobject.c#L208-L211

All other usages only occur for Python generator and coroutine objects, not for other objects that look like coroutines.

**Comment by TeamSpen210** [comment]
That code's for checking if it's legal to set the frame)s `f_lineno`. While tracing you can do that to jump execution around, but you can't do it into/out of loops, exception blocks and some other things. Since Cython always has a blank `co_code`, I think it'll always fail [here in the setter](https://github.com/python/cpython/blob/50b9a7762f06335277d9962edc8d39498601a4e4/Objects/frameobject.c#L618) so it's not a problem. Maybe there should be a test for this though.

**Comment by scoder** [comment]
> That code's for checking if it's legal to set the frame)s `f_lineno`. While tracing you can do that to jump execution around, but you can't do it into/out of loops, exception blocks and some other things.

Thanks for looking through that.

> Since Cython always has a blank `co_code`, I think it'll always fail [here in the setter](https://github.com/python/cpython/blob/50b9a7762f06335277d9962edc8d39498601a4e4/Objects/frameobject.c#L618) so it's not a problem. Maybe there should be a test for this though.

I wouldn't rely on that. Cython's code objects aren't as blank as they may seem, we emulate quite a bit of Python functionality in them for introspection. A test seems needed, as you wrote.

**Comment by da-woods** [comment]
I think this was closed by https://github.com/cython/cython/pull/4902
