### ISSUE TITLE
[BUG] Cython not creating bound method

### ISSUE THREAD

**Issue by jonashaag** [cython/cython#4890]
I'm sorry if this has been reported before. It feels like a very basic issue but I couldn't find any documentation or other bug reports related to it.

**Describe the bug**

Cython does not seem to create a bound method if you do `f = instance.method`.

**To Reproduce**
Code to reproduce the behaviour:
```cython
cdef class X:
    cdef foo(self):
        print(self)


f = X().foo
f()
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "t.pyx", line 8, in init t
    f()
TypeError: wrap() takes exactly one argument (0 given)
```

**Expected behavior**
Prints `self`.

**Environment (please complete the following information):**
Cython version 0.29.30

**Comment by da-woods** [comment]
There isn't really such a thing as a "bound C function". A function pointer doesn't have any space to store anything except the function itself.

Cython should probably report an error though, since it isn't obvious that you can't do it.

**Comment by da-woods** [comment]
Although in this case it's creating a Python wrapper object... which removes the benefit of having a cdef function, but means a bound method should possibly work...

I still think the solution is probably an error message though.

**Comment by jonashaag** [comment]
Relatedly, I want to be able to write code such as

```cython
cdef int const_1 = 1
cdef int const_2 = 2
x = X()
n = some_int
{const_1: x.foo, const_2: x.bar}[n]()
```

And have Cython optimize it to a `switch`. Not sure if that's something that's ever going to be implemented, but it is a case where the Python wrapper could be optimized away and so the "making a Python wrapper of a cdef function is stupid" is a weaker argument.
