### ISSUE TITLE
[BUG] Annotating Memoryviews of Extension Types in the Pure Python Mode With `mem_view: extension_type[:]` Fails

### ISSUE THREAD

**Issue by Acmion** [cython/cython#4907]
**Describe the bug**
Annotating memoryviews of extension types in the pure Python mode with `mem_view: extension_type[:]` fails. However, annotating Cython primitives memoryviews (e.g. `mem_view: cython.int[:]`) works just fine. The cdef syntax does not have this problem. 

**To Reproduce**
Consider the following cdef syntax:

```cython
# cython: initializedcheck = False, boundscheck = False, wraparound = False

cdef class container:
    cdef int item

cdef int calc_containers(container[::1] containers):
    cdef int s = 0
    cdef int c = containers.shape[0]
    for i in range(c):
        s += containers[i].item
    return s

cdef int calc_ints(int[::1] ints):
    cdef int s = 0
    cdef int c = ints.shape[0]
    for i in range(c):
        s += ints[i]
    return s
```

This will compile into:

```c
static int __pyx_f_12memview_cdef_calc_containers(__Pyx_memviewslice __pyx_v_containers) { ... }
static int __pyx_f_12memview_cdef_calc_ints(__Pyx_memviewslice __pyx_v_ints) { ... }
```

Consider the following pure Python code:

```python
# cython: initializedcheck = False, boundscheck = False, wraparound = False

import cython

@cython.cclass
class container:
    item: cython.int

@cython.cfunc
def calc_containers(containers: container[::1]) -> cython.int:
    s: cython.int = 0
    c: cython.int = containers.shape[0]
    for i in range(c):
        s += containers[i].item
    return s

@cython.cfunc
def calc_ints(ints: cython.int[::1]) -> cython.int:
    s: cython.int = 0
    c: cython.int = ints.shape[0]
    for i in range(c):
        s += ints[i]
    return s
```

This will compile into:
```c
static int __pyx_f_12memview_pure_calc_containers(PyObject *__pyx_v_containers) { ... }
static int __pyx_f_12memview_pure_calc_ints(__Pyx_memviewslice __pyx_v_ints) { ... }
```

In the cdef case all arguments are of type `__Pyx_memviewslice`, while in the pure Python case the extension type memoryviews are of type `PyObject` and the primitives of type `__Pyx_memviewslice`. The implication is that the pure Python code will not perform as well (and in some cases will not run at all), even if, in principle, the same syntax was used in all places.

**Expected behavior**
Annotating memoryviews of extension types in the pure Python mode should work in the same fashion as annotating memoryviews of Cython primitives. For example:

```python
@cython.cfunc
def calc0(data: extension_type[:]) -> cython.double: ...

@cython.cfunc
def calc1(data: cython.double[:]) -> cython.double: ...
```

Both should be efficiently compiled. Currently, only the function `calc1` is efficiently compiled. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.10.5
 - Cython version: 3.0.0a10

**Additional context**
I could not find anything about this in the documentation.

**Comment by da-woods** [comment]
You could probably use the `locals` decorator instead. But I don't see why it shouldn't work.

**Comment by Acmion** [comment]
I can not get the `locals` decorator to work for extension type memoryviews. See the code below:

```python
@cython.cfunc
@cython.locals(ints = cython.int[::1])
def calc_ints_alt(ints) -> cython.int:
    s: cython.int = 0
    c: cython.int = ints.shape[0]
    for i in range(c):
        s += ints[i]
    return s
```

Compiles to:

```c
static int __pyx_f_12memview_pure_calc_ints_alt(__Pyx_memviewslice __pyx_v_ints) { ... }
```

Consider the following code with an extension type:

```python
@cython.cfunc
@cython.locals(containers = container[::1])
def calc_containers_alt(containers) -> cython.int:
    s: cython.int = 0
    c: cython.int = containers.shape[0]
    for i in range(c):
        s += containers[i].item
    return s
```

The compiler will fail with the following error:

```
@cython.cfunc
@cython.locals(containers = container[:])
                                    ^
------------------------------------------------------------

path\memview_pure.pyx:26:37: Not a type
```

In other words, I can not get memoryviews of extension types to work. I am also unable to find an alternative way to annotate memoryviews in the pure Python mode.

**Comment by da-woods** [comment]
Again, that does look like it should work, so is a bug.

Practically you'll find a memoryview of `container` is equivalent to a memoryview of `object` with an unchecked cast to `container` (there's no validation of types for example, and the internal structure is exactly the same). So you might be able to use

```
@cython.cfunc
def calc_containers_alt(containers: object[:]) -> cython.int:
   ...
        s += cython.cast(container, containers[i], typecheck=False).item
```

and it should generate almost the same C code as a memoryview of `container`. However, I haven't actually tested that it works, and it's a workaround that you shouldn't have to do

**Comment by Acmion** [comment]
Your code works, but the memoryview is again considered as a `PyObject` and thus performance suffers once again. Consider the following code:

```python
@cython.cfunc
def calc_objs(containers: object[:]) -> cython.int:
    s: cython.int = 0
    c: cython.int = containers.shape[0]
    for i in range(c):
        cnt: container = cython.cast(container, containers[i], typecheck=False)
        s += cnt.item
    return s
```

It translates into this:

```c
static int __pyx_f_12memview_pure_calc_objs(PyObject *__pyx_v_objs) { ... }
```

This time the code does work, but it performs about 20x worse than `cdef int calc_containers(container[::1] containers)` (defined in the first post), because of the incorrect type. This means that Cython has to interface with Python for, for example, the indexation. I also tried `cython.locals(containers = object[:])` and got the same error as previously: `Not a type`.

**Comment by da-woods** [comment]
Yeah - my suggestion would only have been worthwhile if it typed it as a memoryview. I hoped it might, but obviously not...
