### ISSUE TITLE
FIPS mode check with hashlib.md5 is not handled correctly

### ISSUE THREAD

**Issue by mvpel** [cython/cython#4909]
https://github.com/cython/cython/blob/87329f1f9747a5a7e483cf4827d40457f6354c7c/Cython/Compiler/ParseTreeTransforms.py#L2044-L2047

When a machine has FIPS mode enabled, via a fips=1 option on the kernel command line, the MD5 algorithm, among others, is blocked within the kernel. The AttributeError exception shown above is intended to catch situations where this is the case and omit md5 from the list of algorithms, However, simply appending the hashlib.md5 function to the checksum_algos list does not invoke the function, and thus does not raise an exception of any kind if the function is available but blocked. The exception occurs later, when the function is used in "for mkchecksum" to try to create an MD5 checksum, throwing a ValueError exception when it's blocked by the kernel:

https://github.com/cython/cython/blob/87329f1f9747a5a7e483cf4827d40457f6354c7c/Cython/Compiler/ParseTreeTransforms.py#L2050-L2053

A fix would be to make a dummy call to hashlib.md5 in the try block immediately before appending it to the array, and catching and passing that ValueError exception, demonstrated here:

```
>>> import hashlib
>>> hashlib.md5(b'')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: unknown reasons
>>>

sh-4.2# fipscheck
usage: fipscheck [-s <hmac-suffix>] <paths-to-files>
fips mode is on
sh-4.2#
```

You would want to look for both the ValueError and AttributeError exceptions so as to catch both FIPS mode blockage as well as a missing md5 function.

This is the root cause of https://github.com/PySlurm/pyslurm/issues/236. Based on information there, downgrading to Cython 0.25.2 works around the issue in PySlurm.

**Comment by scoder** [comment]
Thanks for the detailed report. Could you verify that https://github.com/cython/cython/commit/3a373e2ccdddc79202d9ed13edc85d4b95616b26 works for you?

**Comment by mvpel** [comment]
> There also looks to be the usedforsecurity argument on Python 3.9+, which we might want to use to get access to md5

When FIPS mode is enabled, the setting of usedforsecurity wouldn't matter; the MD5 algorithm is blocked in the kernel, not by Python. The WerkZeug project, for example, switched from md5 to sha1 for their integrity checks in their 2.0 release for this reason. It seems to me that MD5 should be considered extinct, to be avoided in nearly all cases.

**Comment by mvpel** [comment]
> Thanks for the detailed report. Could you verify that [3a373e2](https://github.com/cython/cython/commit/3a373e2ccdddc79202d9ed13edc85d4b95616b26) works for you?

That did the trick, yes! Thanks! I like the implementation; it handles all the algorithms in the same way.
