### ISSUE TITLE
[ENH] Support "nogil" Python

### ISSUE THREAD

**Issue by colesbury** [cython/cython#4912]
It would be great if Cython could support the ["nogil" Python fork](https://github.com/colesbury/nogil). (A fork of CPython 3.9 that runs without the global interpreter lock.) I'm currently maintaining patches to Cython for compatibility. If the Cython maintainers are OK with it, I'll submit PRs for compatibility.

There are two pieces, both pretty small:
- The configuration in `Cython/Utility/ModuleSetupCode.c`
- Making `MemoryView` reference counting thread-safe without the GIL

Making Cython compatible with "nogil" Python will make it easier to install Python packages that depend on Cython. In particular, because source distributions (sdist) often include pre-Cythonized files.

**Comment by da-woods** [comment]
I suspect that's something we could add.

We'd probably want the memoryview changes to be conditionally compiled (so it doesn't cost anything on other Python versions), but I suspect you've done that anyway.

I'm not sure if we'd want to add it to the CI testing at this stage.

**Comment by scoder** [comment]
Great, thanks for doing this. And for putting so much work into the nogil fork of CPython, that's an impressive achievement.

I [asked](https://github.com/cython/cython/pull/4915#issuecomment-1192173282) over in the atomics PR why you think this can go into the "stable as in boring" 0.29.x branch. I'd rather see 3.0 as a target for such a new feature.

**Comment by da-woods** [comment]
I'd guess the desire to have it in 0.29.x is

> In particular, because source distributions (sdist) often include pre-Cythonized files.

(i.e. you only really benefit from this if you put it in the branch everyone uses)

Not disagreeing with the "changing memoryview locking seems high risk" though

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/f1748bb86bf7edb731728ac366e129c1be9bcb61 and https://github.com/cython/cython/commit/f1748bb86bf7edb731728ac366e129c1be9bcb61.

**Comment by 0dminnimda** [comment]
@da-woods you probaby wanted to mention  66b27de36ec09e1181e8b7eb83cf78d3c5221c2c the second time

**Comment by da-woods** [comment]
Yes thanks I did
