### ISSUE TITLE
[BUG] future feature annotations is not defined

### ISSUE THREAD

**Issue by tinmarr** [cython/cython#4937]
**Describe the bug**
I'm getting exactly the same problem as the others in this thread (#2950). Not exactly sure what's up.

This bug only occurs when I try to build my project completely using `python -m build` without having built the project beforehand. Building the project with `python setup.py build_ext --inplace` before running `python -m build` seems to fix the problem.

Any ideas on what's up?

**To Reproduce**
Code to reproduce the behaviour:
explained above.

**Expected behavior**
I expect the build to succeed

**Environment (please complete the following information):**
 - OS: Windows
 - Python version: 3.10.5
 - Cython version: 3.0.0a10

**Additional context**
Here is the project code:
https://github.com/rubatopy/rubato/tree/cython
Here are the relevant stacktraces
![image](https://user-images.githubusercontent.com/35586618/181880350-ca09ccfb-4eeb-4bbe-8dbf-9cd270f10068.png)
![image](https://user-images.githubusercontent.com/35586618/181880370-437a1387-d952-4a6a-b051-9eb398c54476.png)

**Comment by da-woods** [comment]
Can you double-check the version of Cython you're using. It works for me on 3.0.0a10 (as I'd expect). It doesn't work on any of the 0.29.x releases (but I wouldn't expect it to)

**Comment by tinmarr** [comment]
Yes I'm using 3.0.0a10 (just double checked). Does it work for you when doing `pip install -e .` ?

**Comment by da-woods** [comment]
So by "it works for me" what I mean is "a small file containing `from __future__ import annotations` works for me when I compile it with `cython` from the command line". I definitely haven't tried building that full project. Sorry - I skim read it an missed the bit about `build` vs `build_ext` which is probably the core of the issue.

I suspect that some combination of distutils/setuptools/pip is running it was a different version of Cython than you think. But I don't personally know why that'd be, why `build_ext` is different from `build`, or how to fix it.

**Comment by tinmarr** [comment]
Ok I figured it out. You were on the right track.

In the pyproject.toml file under the build-system requirements you need to specify the Cython version like so

```toml
[build-system]
requires = ["setuptools ~= 63.2", "wheel ~= 0.37", "Cython ~= 3.0.0a10"]
build-backend = "setuptools.build_meta"
```
