### ISSUE TITLE
[BUG] HTML generated by cython -3a renders all C code in single line

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#4945]
**Describe the bug**
`cython -3a` command generates C code in html file which is rendered to single line:

**To Reproduce**
Code to reproduce the behaviour:
```cython
cdef int a = 3
cdef int b = 5

print(a * b)
```
![image](https://user-images.githubusercontent.com/827060/182687499-82a05ced-c51f-49b0-992d-c07a7de03ebc.png)

**Expected behavior**
C code rendered in browser should be splited into several lines

**Environment (please complete the following information):**
 - OS: Any
 - Python version 3.9
 - Cython version master

**Additional context**
Issue was introduced by following commit:
```
commit 0b4370678e5b00a020cd990f922964d3aba59884
Author: Stefan Behnel <stefan_ml@behnel.de>
Date:   Sat Jul 16 22:14:48 2022 +0200

    Reduce overhead in the code writer when writing out simple code without newlines.

 Cython/Compiler/Code.pxd |  1 +
 Cython/Compiler/Code.py  | 19 ++++++++++++-------
```

**Comment by da-woods** [comment]
0b4370678e5b00a020cd990f922964d3aba59884 (just reposting to get a link the commit)
