### ISSUE TITLE
[BUG] Unused parameter warning on CPython 3.11

### ISSUE THREAD

**Issue by godlygeek** [cython/cython#4948]
**Describe the bug**
Running Cython 0.29.32 with CPython 3.11 generates code that produces an "unused parameter" warning from GCC.

**To Reproduce**
Code to reproduce the behaviour:

A Cython file that contains only `pass` is enough to trigger the problem, as long as `CFLAGS` includes `-Wall -Wextra -Werror`. For instance, using the `cythonmagic` IPython magic:

```py
(311venv) $ CFLAGS="-Wall -Wextra -Werror" python -m IPython
Python 3.11.0b5 (main, Jul 26 2022, 12:19:13)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %load_ext cython

In [2]: %%cython
   ...: pass
   ...:
   ...:
/home/mwoznisk/.cache/ipython/cython/_cython_magic_adb847382f59ef636f2f8056fa356181.c: In function ‘__Pyx_CLineForTraceback’:
/home/mwoznisk/.cache/ipython/cython/_cython_magic_adb847382f59ef636f2f8056fa356181.c:1631:69: error: unused parameter ‘tstate’ [-Werror=unused-parameter]
 1631 | static int __Pyx_CLineForTraceback(CYTHON_NCP_UNUSED PyThreadState *tstate, int c_line) {
      |                                                      ~~~~~~~~~~~~~~~^~~~~~
cc1: all warnings being treated as errors
```

**Expected behavior**
No unused parameter warnings 😄

Ideally, the generated code would conditionally add a `__attribute__((unused))` when `CYTHON_FAST_THREAD_STATE` is not set. Or, instead,
```c
#define __Pyx_ErrRestoreInState(tstate, type, value, tb)  PyErr_Restore(type, value, tb)
#define __Pyx_ErrFetchInState(tstate, type, value, tb)  PyErr_Fetch(type, value, tb)
```
could be changed to do:
```c
#define __Pyx_ErrRestoreInState(tstate, type, value, tb)  (void)(tstate); PyErr_Restore(type, value, tb)
#define __Pyx_ErrFetchInState(tstate, type, value, tb)  (void)(tstate); PyErr_Fetch(type, value, tb)
```

**Environment (please complete the following information):**
 - OS: [e.g. Linux, Windows, macOS] Linux (technically WSL)
 - Python version [e.g. 3.8.4] 3.11.0b5
 - Cython version [e.g. 0.29.18] 0.29.32

**Additional context**
It looks like in 3.10 and earlier, this peeked into private fields of the thread state, but in 3.11 where those fields are inaccessible it now just calls `PyErr_Fetch()` and the `tstate` parameter doesn't get used.

**Comment by da-woods** [comment]
I'm fairly sure that `CYTHON_NCP_UNUSED` adds `__attribute__((unused))` so I'm a little puzzled by this.

I suspect this won't end up being fixed on Cython 0.29.x, but we would try to fix it in 3.0 (if it's still an issue)

**Comment by godlygeek** [comment]
> I'm fairly sure that `CYTHON_NCP_UNUSED` adds `__attribute__((unused))` so I'm a little puzzled by this.

It doesn't:

```c
#ifndef CYTHON_NCP_UNUSED
# if CYTHON_COMPILING_IN_CPYTHON
#  define CYTHON_NCP_UNUSED
# else
#  define CYTHON_NCP_UNUSED CYTHON_UNUSED
# endif
#endif
```

Since building for CPython 3.11.0b5 results in `CYTHON_COMPILING_IN_CPYTHON` being true, `CYTHON_NCP_UNUSED` has no effect.

What's the intended difference between the two macros? Does "NCP" mean "not c python"?

**Comment by scoder** [comment]
Yes, `NCP` means "not CPython" here, so it doesn't do anything in CPython (including 3.11). Apparently, Python 3.11 is no longer CPython, at least as we know it. ;-)

The quick-fix is probably just to remove the `NCP` in this case.

**Comment by scoder** [comment]
I think removing the `NCP` is really correct, also in the master branch, because it depends on a user definable flag (and not just on CPython or not) whether the argument is (un)used.
