### ISSUE TITLE
[BUG]  Compiler crash in 3.0.0a11 for Dataclass with Tuple field

### ISSUE THREAD

**Issue by bobbyi** [cython/cython#4951]
```cython
import cython
from typing import Tuple

@cython.dataclasses.dataclass
@cython.cclass
class MyDataClass:
    tuple: Tuple
```

Trying to build this (on 64-bit linux with Python 3.8.11 and Cython 3.0.0 Alpha 11) results in

```
Compiler crash traceback from this point on:
  File "/home/ec2-user/anaconda3/envs/py38/lib/python3.8/site-packages/Cython/Compiler/ExprNodes.py", line 13381, in __init__
    assert dst_type.is_extension_type or dst_type.is_builtin_type, \
AssertionError: PyTypeTest for Python object against non extension type Python object
```

If `Tuple` is changed to `Tuple[str]` , it does not crash

**Comment by da-woods** [comment]
Yes, that should probably work.

You can also use `tuple` (i.e. not imported from `typing`), which is probably clearer if you don't want to subscript it.

**Comment by bobbyi** [comment]
Thanks. I will change my code.

The real issue here isn't that cython doesn't accept my initial code but that the compiler crashes and gives no indication of which line of my file was the problem.

**Comment by da-woods** [comment]
Part of the reason you don't get a good traceback (I think) is that the error comes from generated code. It looks to come from within the `__init__` function that Cython generates from the class, and hence it doesn't *directly* link to a line of your file. That isn't hugely easy to fix I think (although it doesn't mean we shouldn't try...)
