### ISSUE TITLE
[BUG] `__Pyx_FakeReference<__Pyx_memviewslice>` cannot be initialized using default Cython generated values.

### ISSUE THREAD

**Issue by Micky774** [cython/cython#4966]
**Describe the bug**
When attempting to create a vector of memory views and access via `operator[]` or `.at()` into a placeholder variable, Cython compiles with errors:
```traceback
error: could not convert ‘{0, 0, {0}, {0}, {0}}’ from ‘<brace-enclosed initializer list>’ to ‘__Pyx_FakeReference<__Pyx_memviewslice>’
 4183 |   __Pyx_FakeReference<__Pyx_memviewslice> __pyx_t_12 = { 0, 0, { 0 }, { 0 }, { 0 } };
      |                                                                                    ^
      |                                                                                    |
      |                                                                                    <brace-enclosed initializer list>
```

**To Reproduce**
Code to reproduce the behaviour:
```cython
from libcpp.vector cimport vector

vector[int[:]] unique_labels
const int[:, :] labels

...

self.unique_labels = [[1, 2], [3]]
cdef int[:] tmp = self.unique_labels.at(0)

...

```

**Expected behavior**
No compilation errors.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.9.13
 - Cython version 0.29.30

**Additional context**
The generated code could be simply fixed by altering the brace-enclosed initialization to as follows:
```cpp
__Pyx_FakeReference<__Pyx_memviewslice> __pyx_t_12 = __Pyx_memviewslice { 0, 0, { 0 }, { 0 }, { 0 } };
```

Even if I code around this bug such that there are no compilation errors, I end up with segfaults later on when accessing the vector `unique_labels` which is probably directly caused by this.

**Comment by da-woods** [comment]
A vector of memoryviews isn't expected to work. In Cython 3 we've added explicit error messages for it (https://github.com/cython/cython/commit/3226074e9babe86da1b235fcec6905ad1eef12f2) but it was never something that generated valid code. Essentially memoryviews require Cython-generated reference counting code. `std::vector` doesn't know and just treats them as a plain-data struct. Which is wrong.

What you probably want to store a similar data structure (i.e. an resizeable array of memoryviews) is to create a wrapper cdef class for the specific type of memoryviewview you're using:

```
cdef class DoubleMemoryview1D:
    cdef double[:] view
```

and just create a Python list of `DoubleMemoryview1D`. You can cast on index (if you're confident that you control access the the list, so nobody's added any incorrectly typed objects) to get the memoryview efficiently:

```
(<DoubleMemoryview1D>mview_list[0]).view
```
