### ISSUE TITLE
[ENH] misleading error suggestion: missing closing paren vs. assignment

### ISSUE THREAD

**Issue by smurfix** [cython/cython#4998]
```
    dd.setdefault(devs[dev].name, attrdict().setdefault("regs",attrdict()).setdefault(typ,attrdict()).setdefault(phase,attrdict())[ins] = reg
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
```
Wrong. Real reason: I forgot to close a parenthesis.

It'd be nice if the error suggestion mechanism would notice that in preference to the assignment, esp. since it's hard to find in more complex expressions.

**Comment by da-woods** [comment]
This doesn't look like a Cython error message. We don't do `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^` formatting of messages.

I suspect you intended to post to http://github.com/python/cpython/issues
