### ISSUE TITLE
How to cross compile cython code correctly by setup.py?

### ISSUE THREAD

**Issue by atptour2017** [cython/cython#5009]
I have done lots of cross compile works for my arm platform. Usually the codes are open source code in github such as apache beam. There are many cython code in it. I assign $CC to be my arm compiler and then I perform python setup.py build to cross compile it. Usually it's successful. Then its c lib was built out such as stream.cpython-38-x86_64-linux-gnu.so.
But the problem is that it's name was always wrong. The file name always has "x86_64" in it. When I transfer this lib to run in arm server, its name must be changed to "aarch64" inside.
I think this is the problem of cython. When I run setup.py, it generate the folder name with "x86_64" automatically. For example, build/lib.linux-x86_64-cpython-38 is the folder generated in apache-beam-2.27.0 source code. How can I assign the CPU/arch type name for cython compile? Are there any parameter to set that for cython compile?

**Comment by da-woods** [comment]
Support question - please ask on the cython-user's mailing list instead (as instructed).

Note that Cython itself doesn't control the compilation - setuptools/distutils does.
