### ISSUE TITLE
[BUG] dataclass fields type shown as string

### ISSUE THREAD

**Issue by nisalup** [cython/cython#5010]
### Describe the bug

The type value of attributes from `fields` in `dataclasses` shows the `type` as a string representation.

### Code to reproduce the behaviour:

For the following piece of code of a simple dataclass:

```
from dataclasses import dataclass, field, fields

@dataclass
class Test():

    _id: ObjectId = field(init=False)

    def __post_init__(self):
        self._id = ObjectId()

tt = Test()
fields(tt)

```

Running it on python directly would give the following object:

> (Field(name='_id',type=<class 'bson.objectid.ObjectId'>,default=<dataclasses._MISSING_TYPE object at 0x7ff1d30f6760>,default_factory=<dataclasses._MISSING_TYPE object at 0x7ff1d30f6760>,init=False,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD),)

However, if I ran the following code compiled with cython 3.0.0a11, I get:

> (Field(name='_id',type='ObjectId',default=<dataclasses._MISSING_TYPE object at 0x7f80335335b0>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f80335335b0>,init=False,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD),)

Where _id type is a string value, hence no type comparisions can be made.

### Expected behaviour

The field type should contain the real type of the attribute

### Environment

OS: Linux
Python version 3.9
Cython version 3.0.0a11

**Comment by da-woods** [comment]
I do have a draft "mostly working" PR to revert to the old behaviour https://github.com/cython/cython/pull/4463. Currently I don't think we're planning to merge this, but I'm keeping the PR mostly up-to-date in case we do want to change it.

You're welcome to check out that PR and try to use it if it helps solve a particular problem, but obviously it's unsupported.

**Comment by chibai** [comment]
@nisalup 
Do you know How to code compatible with python and cython

```python
from dataclasses import dataclass, field, fields

@dataclass
class Test():

    _id: str = str()


tt = Test()
for dataclass_field in fields(tt):
  if tt is str:
    # This not working in cython
```
