### ISSUE TITLE
Alpha releases should be marked as pre-releases on GitHub

### ISSUE THREAD

**Issue by SpecLad** [cython/cython#5012]
All releases on the [GitHub release page](https://github.com/cython/cython/releases) are currently marked as regular releases. It would be clearer if the 3.0 alpha releases were marked as pre-releases, since (as far as I understand) they _are_.

**Comment by 0dminnimda** [comment]
Yes, they are, but usually people eather use pip or clone the repo
It would be better to mark them as pre-releases, but it's tedious and mostly useless, so may not be done
Also we want people to switch to this alpha, it's pretty stable (enough for most users)

**Comment by da-woods** [comment]
Since they're marked as pre-releases on PyPI it seems consistent to do so here, so I've done so. It's possible that decision may be revised of course
