### ISSUE TITLE
[BUG] multiple compiler_directives in setup.py get ignored

### ISSUE THREAD

**Issue by excubo-jg** [cython/cython#5022]
### Describe the bug

Using diff on the generated html-file I see that setting one compiler_directives does change the generated code but setting multiple directives does not. I am following the guidelines from https://github.com/cython/cython/blob/master/docs/src/userguide/source_files_and_compilation.rst#in-filesetuppy
 set directives using setup.py.

### Code to reproduce the behaviour:

The code generated with one compiler_directives differs from code generated without compiler_directives being set
setup(
    name="My hello app",
    ext_modules=cythonize('hello.pyx', compiler_directives={'boundscheck': False}),
)
This code does produce the same code as when run without compiler_directives being set.
setup(
    name="My hello app",
    ext_modules=cythonize('hello.pyx', compiler_directives={'boundscheck': False, 'wraparound': False, initializedcheck': False, profile': True}),
)

### Expected behaviour

Multiple directives get parsed 

### Environment

OS: [e.g. Linux, Windows, macOS]
Python version [e.g. 3.10.2]
Cython version [e.g. 3.0.0a11]

**Comment by 0dminnimda** [comment]
Your code may not include anytihng those directives target

Also I may not be correct on this one, but if you didn't change the `hello.pyx` than build should not be triggered
You may want to set the `force=True`, to get full recompilation each time

**Comment by excubo-jg** [comment]
Not sure why as I did not change anything but the last execution of the build process did as expected.
