### ISSUE TITLE
[BUG] error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

### ISSUE THREAD

**Issue by oddsmatcheraustralia** [cython/cython#5044]
### Describe the bug

This no longer works on windows 11

Command:

python setup.py build_ext --inplace
running build_ext
building 'helloworld' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
What I have tried:

I am running version 3.10 python, I have tried anaconda 3.7 and 3.9 still no luck. I have install visual studio Build Tools 2022 and Visual Studio Community 2022 all files which is around 200gb as well as added C:\Program Files (x86)\Microsoft Visual Studio 14.0 and C:\Program Files (x86)\Microsoft Visual Studio 14.0/Vc to path. I have tried https://github.com/abbodi1406/vcredist/releases/tag/v0.62.0

### Code to reproduce the behaviour:

```cython
# example code
```

### Environment

OS: [e.g. Linux, Windows, macOS]
Python version [e.g. 3.10.2]
Cython version [e.g. 3.0.0a11]
windows 11
python 3.10.2
cython (most recent)

**Comment by da-woods** [comment]
Cython doesn't handle finding the C compiler itself so this isn't a Cython bug. That's deferred to setuptools on distutils. However we would be interested in documenting it better if we're missing information.

I'm not using Windows 11 so practically I'm not in a position to investigate this.

**Comment by da-woods** [comment]
Practically https://github.com/pypa/setuptools/issues/3329 and https://github.com/pypa/setuptools/issues/3275 (and possibly others) might be related, but I'm not sure if they're hugely useful

**Comment by oddsmatcheraustralia** [comment]
Yeah I just wanted to make an app run in cython but apparently Microsoft has had these issues since 2018 what is going on
