### ISSUE TITLE
[BUG] When using the dictionary fromkeys method in a class, the converted C source code crashes on execution

### ISSUE THREAD

**Issue by maple-leaf-0219** [cython/cython#5051]
### Describe the bug

When using the dictionary fromkeys method in a class, the converted C source code crashes on execution

### Code to reproduce the behaviour:

```cython
# example code
class LsaLsdb(object):
    def __init__(self):
        pass

    def test(self):
        new_node = {}
        new_node['area-id'] = ['0.0.0.0', '0.0.0.0']
        test_dict = {}
        new_node['area-id'] = test_dict.fromkeys(new_node['area-id']).keys()
        print(new_node['area-id'])


lsa = LsaLsdb()

lsa.test()
```
```bash
cython -2  --embed -o test.c test.py
gcc -g -I /usr/include/python2.7 test.c -lpython2.7 -o test

run test, and Segmentation fault
```

### Expected behaviour

['0.0.0.0']

### Environment

OS: Linux
Python version 2.7.17
Cython version 3.0.0a11 and 0.29.32

**Comment by maple-leaf-0219** [comment]
use dict.fromkeys()  or {}.from, not use test_dict.fromkeys can avoid this problem

**Comment by da-woods** [comment]
This appears to be Python 2 only.

The crash is at
https://github.com/cython/cython/blob/169876872f3cb6198971a1db07e5b8a9d12b3dac/Cython/Utility/ObjectHandling.c#L2008
(`d_method` is NULL).

```
(gdb) print(*method)
$4 = {ob_refcnt = 1, ob_type = 0x7ffff7f5a500 <PyCFunction_Type>}
```

That suggests to me that `method` may not actually be a `PyMethodDescrObject` (and the check is Py3 only). But I don't really know what's gone wrong.

**Comment by da-woods** [comment]
I'm assuming the issue is to with with it being a class method. In which case the options are either:
* reverse the `    if (likely(__Pyx_TypeCheck(method, &PyMethodDescr_Type)))` check in Python 2 - check for "not a C function" instead of "is a method descr"
* Disable the optimization for `fromkeys`. As far as I can tell there's no other builtin types with class methods in Python 2 (except for `float` which is essentially impossible to type in Python 2)

**Comment by maple-leaf-0219** [comment]
> 

py3 doesn't crash, but it runs incorrectly

**Comment by da-woods** [comment]
The bug applies to any builtin-type classmethod (although these examples only exist on Py3)

```
def bytesfromhex(bytes b):
    return b.fromhex('2Ef0 F1f2  ')

def bytearrayfromhex(bytearray ba):
    return ba.fromhex('2Ef0 F1f2  ')

def intfrombytes(i: int):  # annotation - py int
    i.from_bytes([255, 0, 0], 'big')
```

```
>>> bytesfromhex(b'a')
...
TypeError: bytes.fromhex() takes exactly one argument (2 given)
>>> bytearrayfromhex(bytearray(b'a'))
...
TypeError: bytearray.fromhex() takes exactly one argument (2 given)
>>> intfrombytes(2)
...
TypeError: from_bytes() takes exactly 2 positional arguments (3 given)
```

Essentially the `__Pyx_CallUnboundCMethod1/2` optimization doesn't work for `classmethods` (crashes in Python 2, mixes up the arguments on Python 3)
