### ISSUE TITLE
[BUG] locals() not return same dict in multiple calls

### ISSUE THREAD

**Issue by fanthos** [cython/cython#5054]
### Describe the bug

CPython `locals()` returns same `dict` for multiple calls, and update dict content when `locals()` called.
Cython creates new `dict` on each `locals()` call.

### Code to reproduce the behaviour:

```cython
def cython_locals_test():
    a = locals()
    b = locals()
    return a, b, a == b
```

### Expected behaviour

Cython returns `({}, {'a': {}}, False)`
`a == b` should be `True`
CPython returns `({'a': {...}}, {'a': {...}}, True)`

### Environment

Windows 11
Python 3.10
Cython 3.0.0a11

**Comment by da-woods** [comment]
Not really a bug: https://docs.python.org/3/library/functions.html#locals You can't usefully modify locals (see the note in the documentation) so it really doesn't matter if it returns the same dict. At best it'd be a minor optimization.

**Comment by fanthos** [comment]
The difference is that CPython updates the dict prevous returned by locals, so `a['a']` exists without assign it again.

**Comment by 0dminnimda** [comment]
You better use your own dict if you generate names
It doesn't mean this is not a valid bug, but it seems to be somewhat a waste of time trying to implement it

**Comment by scoder** [comment]
Python does not update the dict before it assigns variables, as you can see here:
```python
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def cython_locals_test():
...     a = locals()
...     b = locals()
...     return a, b, a == b, a is b
... 
>>> cython_locals_test()
({'a': {...}}, {'a': {...}}, True, True)
>>> def test2():
...     a = dict(locals())
...     b = dict(locals())
...     return a, b, a == b, a is b
... 
>>> test2()
({}, {'a': {}}, False, False)
```
However, it does always return the same dict for `locals()` and updates it when you call `locals()`. That does not mean that an assignment leads to new entries in that dict. In fact, really only calling `locals()` changes the content, as you can see here:
```python
>>> def test3():
...     a = locals()
...     b = locals()
...     c = dict(b)
...     locals()
...     return a, b, c
... 
>>> test3()
({'a': {...}, 'b': {...}, 'c': {'a': {...}}}, {'a': {...}, 'b': {...}, 'c': {'a': {...}}}, {'a': {'a': {...}, 'b': {...}, 'c': {...}}})
```

Cython currently behaves slightly differently in that it creates a new dict on each access. That's ok for most use cases, but obviously differs from Python's behaviour if you explicitly look for the difference, as you do in your example.

I don't see a real difference in practice, though. If you want an up-to-date version of locals(), ask for it.

**Comment by fanthos** [comment]
I used locals() for monitoring variables in function and track variable assignment(declaration) by calling `locals()`, found that the old locals and new locals not the same dict.
I fixed my usage by assign the locals() to my dict cache each time if I need to update values, so it works in my case.

**Comment by TeamSpen210** [comment]
Note that exactly what `locals()` does inside function scopes is currently not well defined by the language spec. [PEP 558](https://peps.python.org/pep-0558/) is currently being proposed to standardise a specific behaviour, which is actually to return a fresh dict each time like Cython does.
