### ISSUE TITLE
[ENH] Optimise bound C methods

### ISSUE THREAD

**Issue by scoder** [cython/cython#5062]
Follow-up to https://github.com/cython/cython/pull/4988 and https://github.com/cython/cython/issues/4890

The current implementation just calls `__import__("functools").partial(cfunc)`. Cython could generate more efficient code. Specifically, it could use a CPython method object, which would also make use of the vectorcall protocol. Assuming that Cython supports that for its generated C function wrapper.

**Comment by da-woods** [comment]
That is significantly simpler than what I did.
