### ISSUE TITLE
[BUG] type of 'self' in __truediv__ method

### ISSUE THREAD

**Issue by Ovizro** [cython/cython#5067]
### Describe the bug

I notice the argument `self` in method `__truediv__` is not regarded as type Self@CClass currectly.

### Code to reproduce the behaviour:

```cython
cdef class TestDiv:
    cdef int x

    def __cinit__(self):
        self.x = 1
    
    def __mul__(self, other):
        return self.x

    def __truediv__(self, other):
        return self.x
```
In method `__mul__`, `self.x` is complited to `__pyx_v_self->x`, while in `__truediv__`, it is complited to `__Pyx_PyObject_GetAttrStr(__pyx_v_self, __pyx_n_s_x)`. And the same situation happens on methods including `__rtruediv__`, `__floordiv__`, `__matmul__`.

### Expected behaviour

`self` in methods above should have the same behavior as `self` in other methods.

### Environment

OS: Windows
Python version 3.8.12
Cython version 3.0.0a10 & 3.0.0a11

**Comment by da-woods** [comment]
I suspect these have just been missed from the `c_api_binops` change. It's probably a relatively simple fix.
