### ISSUE TITLE
[ENH] Use `cython.pointer[...]` instead of `cython.pointer(...)`

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5071]
### Is your feature request related to a problem? Please describe.

Python is using squared brackets for specifying complex types - e.g. `tuple[int]`, `Callable[[int]`, `Union[int, str]`. It would be nice that Cython can follow this for `cython.pointer`:

```python
a: cython.pointer[cython.Py_ssize_t]
```

### Additional context

Old behaviour `cython.pointer(...)` will be deprecated but still maintained for backward compatibility.

**Comment by da-woods** [comment]
This feels reasonable to me given the Python syntax.

The only question would be if it's easy to support both syntaxes (without having tried, I could imagine it might be fiddly).

**Comment by 0dminnimda** [comment]
From what i know it shouldn't be hard, we just won't have any single defs anymore, but rather only classes
