### ISSUE TITLE
[BUG] Uncompilable .c code with fused types and cimport_from_pyx=True

### ISSUE THREAD

**Issue by skunkyevil** [cython/cython#5072]
### Describe the bug

Compilation fails on C stage failing with error C2065 (unknown identifier) when ```cimport_from_pyx``` option is on

### Code to reproduce the behaviour:

```cython
ctypedef fused fused_type:
    long
    double

cdef fused_checker(fused_type i):
    if fused_type is long:
        return True
    else:
        return False

def test():
    return fused_checker(0)
```

My setup.py:

```
from distutils.core import Extension, setup

import Cython.Compiler.Options
from Cython.Build import cythonize


Cython.Compiler.Options.cimport_from_pyx = True

setup(
    name='Cython tests',
    ext_modules=cythonize("cython_tests.pyx"),
)
```

### Environment

OS: Windows
Python version 3.9.7
Cython version 3.0.0a11

**Comment by da-woods** [comment]
The issue seems to be two lines

```
if (__Pyx_ExportFunction("__pyx_fuse_0fused_checker", (void (*)(void))__pyx_fuse_0__pyx_f_12cython_tests_fused_checker, "PyObject *(long)") < 0) __PYX_ERR(0, 1, __pyx_L1_error)
  if (__Pyx_ExportFunction("__pyx_fuse_1fused_checker", (void (*)(void))__pyx_fuse_1__pyx_f_12cython_tests_fused_checker, "PyObject *(double)") < 0) __PYX_ERR(0, 1, __pyx_L1_error)
```

I think these are exported so that they can be cimported from elsewhere if needed. However the functions in question are implementation details so shouldn't be exported.

**Comment by da-woods** [comment]
Actually what's happened: only the int version of `fused_checker` is used, so Cython drops the double version. However it still generates export code for the double version. It should treat all functions as "declared in pxd" and not drop them

**Comment by da-woods** [comment]
Hopefully closed in https://github.com/cython/cython/pull/5318 (unless I'm missing something)
