### ISSUE TITLE
Add a generalized mean function which can calculate quadratic means, cubic means, and so on

### ISSUE THREAD

**Issue by JeffOfTheSixPaths** [cython/cython#5091]
### Is your feature request related to a problem? Please describe.

In my code, I would like to do have a function which can calculate quadratic means, cubic means, and so on

### Describe the solution you'd like.

a function within statistics.py which calculates this mean.

### Describe alternatives you've considered.

I've considered making it myself within my code, however it makes my code much messier than needed

**Comment by da-woods** [comment]
I think you meant to post this on https://github.com/python/cpython/issues. Cython is a tool for writing Python extension modules and doesn't provide any statistics library.
