### ISSUE TITLE
[BUG] python code with annotations compile error

### ISSUE THREAD

**Issue by 43501474** [cython/cython#5092]
### Describe the bug

cython compile fail with error: ` 'Dict' is not a constant, variable or function identifier`

### Code to reproduce the behaviour:

```python
import typing as t

a = t.Dict[str, str]
```

### Expected behaviour

compile success

### Environment

OS: Ubuntu 22.04
Python version [3.8.13]
Cython version [3.0.0a11]

### Additional context

the following similar code compiles ok

```python
from typing import Dict

a = Dict[str, str]
```

**Comment by da-woods** [comment]
Thanks. This is fixed in the current master branch so should work in the next release https://github.com/cython/cython/commit/f6edb652db32e12505be8bc4767e64b50790f378
