### ISSUE TITLE
CI started raising warnings that `save-state` command and `set-output` command are deprecated

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5103]
See here:

https://github.com/cython/cython/actions/runs/3351493154/jobs/5552981131#step:4:23

Github Actions documentation says:

> Starting today runner version 2.298.2 will begin to warn you if you use the save-state or set-output commands via stdout. We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by da-woods** [comment]
To me it looks like this is coming from the CCache script(?) that we're using, so it may need to be updated there rather than on our end.

**Comment by da-woods** [comment]
We can probably just pump the version though https://github.com/pat-s/always-upload-cache/releases/tag/v3.0.11

**Comment by da-woods** [comment]
Not cherry-picking to 0.29.x for now - it looks to be on a much older version of the ccache scripts and I'm not completely sure what else has changed here.
