### ISSUE TITLE
[BUG] Unable to pickle cpdef enum values from pure python because of attribute lookup error

### ISSUE THREAD

**Issue by tarasko** [cython/cython#5120]
### Describe the bug

pickle.dumps throws an exception when attempted to serialize enum value
```
>>> pickle.dumps(ValEnum.val1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <enum 'ValEnum'>: attribute lookup ValEnum on importlib._bootstrap failed
```

### Code to reproduce the behaviour:

```cython
cpdef enum ValEnum:
    val1 = 1
    val2 = 2
```

```python
import pickle
pickle.dumps(ValEnum.val1)
```

### Expected behaviour

pickle.dumps should return serialized value instead of throwing an exception

### Environment

OS: Linux 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Python version [e.g. 3.10.6]
Cython version [e.g. 3.0.0a11]

**Comment by da-woods** [comment]
Thanks for the report. I suspect we just need to pass module and/or qualname arguments when we construct the enum.

The workaround probably involves casting it to int and pickling the int I suggest.
