### ISSUE TITLE
[ENH] Please consider maintaining the Emacs-Lisp files in a separate repository

### ISSUE THREAD

**Issue by tarsius** [cython/cython#5122]
### Is your feature request related to a problem? Please describe.

This repository contains one or more Emacs-Lisp libraries, which are distributed on [Melpa](https://melpa.org) for easy installation using Emacs' official package manager (`package.el`) and are also mirrored on the [Emacsmirror](https://github.com/emacsmirror).

This project/repository is about much more than just the elisp libraries.  These libraries are tucked away in some "contrib" or "utilities" directory.  The maintainers of the project as a whole likely care little about these libraries, which makes it a less than optimal place to maintain them.  The maintainers will always have something more important to deal with and potential contributors are likely scared away by the additional processes and conventions that such a large project needs, but which are overkill when looking at the elisp libraries in isolation.

### Describe the solution you'd like.

I would like to propose that the Emacs-Lips libraries are maintained in a separate repository.  Doing that would solve a few issues and have additional benefits:

- Distributing a package that originates in such a large repository puts additional strain on the Melpa server.  Fetching the repository takes longer and they require more space.  We are already trying to deal with the latter, but not very successfully and this leads to special-cases in the tooling, which come with additional maintenance costs.  See https://github.com/melpa/melpa/issues/5361, also for some past discussion.

- I also maintain the Emacsmirror and here the costs are much higher than for Melpa.  The Emacsmirror does not just distribute installable snapshots of a package, as Melpa does.

  Instead it mirrors the upstream repository.  But in cases like this, where the repository contains much more than just the elisp libraries, it filters the history, using tools such as `git filter-repo` and `git subtree`.  Unfortunately these tools are not very reliable and highly inefficient when continuously rewriting large repositories like this one.
  
  Currently this affects just 33 out of 8485 on the Emacsmirror, and the disproportionate amount of work that it takes to maintain the tooling for these special-cases is just not worth it.  So I have decided to phase out support, but not before making an effort to get as many of these Emacs package slit out of the repositories they are currently being maintained in.
  
- For maintainers of this repository any issue about the elisp libraries is likely just more noise.  They have better things to do.

- On the other hand, the original authors of the elisp libraries and people who have contributed to them, likely have notifications for this repository disabled because they only contribute to the elisp parts and there would just be too much noise otherwise.  So issues and pull-requests by users are likely to go unnoticed for a long time.

  The author and contributors likely have to be explicitly summoned, as I am doing now: @gvol @immerrr @williamstein

- Potential contributors are discouraged when their pull-requests are being "ignored" or they might be discouraged by the additional requirements imposed by the project as a whole, and not even try to contribute as a result.

- Users who install elisp packages by manually cloning their repositories and then manually adding the appropriate directories to the `load-path`, are forced to clone a huge repository just to get their hands on a few elisp libraries in some subdirectory.  (Or they can use the filtered repositories on the Emacsmirror, but as I mentioned, those are going away.)

So in summary, I think there are many downsides to maintaining the elisp libraries in this repository.  I am not sure there are any upsides, except that it is the status quo.

Moving the elip libraries out of here is some work, that someone has to do, but most of that work is already done.  You can just clone the respective repository from the Emacsmirror (at https://github.com/emacsmirror/cython-mode) and publish it somewhere else.  (Please check that no recent history is missing and if the mirror repository is not uptodate, then ping me.)

Once you have done that tell me about it here, and I will take care of updating Melpa and the Emacsmirror.

Thanks for considering!
Jonas

### Describe alternatives you've considered.

We can remove `cython-mode` from Melpa and the Emacsmirror, but I would rather not do that.

**Comment by williamstein** [comment]
Hi, I see that I've been explicitly summoned! 

For what it is worth, I don't use emacs anymore, and don't have any vested interest in this emacs-lisp code.  If there is anything where I can help regarding permissions let me know. 

> We can remove cpython-mode from Melpa and the Emacsmirror, but I would rather not do that.

Did you mean to write "cython-mode", but wrote "cpython-mode" as a typo?

**Comment by da-woods** [comment]
I don't think we're particularly set on having this in the main Cython repository - I don't think any of the current Cython maintainers use emacs, so on the rare occasion we do get a PR for it it's hard to know what to do. I'm not sure whether moving them to another repository under github.com/cython solves a huge amount - it'd be the same people (not) maintaining it.

My question would be: is there somewhere useful external that we could hand this off to? (A quick search suggests "not really").

**Comment by tarsius** [comment]
> My question would be: is there somewhere useful external that we could hand this off to?

There is the [Emacsorphanage](https://github.com/emacsorphanage), which I happen to maintain. :grin:

I think that would be a good place to move this too. I am certainly qualified to take care of the Elisp side of things, but I am not a C or Python programmer, so there is a possibility that I would have to summon some experts (you) once in a blue moon.

**Comment by immerrr** [comment]
> There is the [Emacsorphanage](https://github.com/emacsorphanage), which I happen to maintain. grin
>
> I think that would be a good place to move this too. I am certainly qualified to take care of the Elisp side of things, but I am not a C or Python programmer, so there is a possibility that I would have to summon some experts (you) once in a blue moon.

Was going to suggest emacsorphanage :) I haven't touched C or Cython code in ages, but would be happy to help.

**Comment by tarsius** [comment]
@da-woods let me know if you want to proceed like this. I will then setup to repository on the orphanage and change the mirror and Melpa to get it from there. I'll also give @immerrr access, and can also give you or someone else from the `cython` organization access.

**Comment by da-woods** [comment]
@scoder do you have any thoughts on this?

**Comment by dnicolodi** [comment]
I use Cython and I use Emacs. I would be happy to help in taking care of `cython-mode`. I think making it a new repository in the `cython` organization makes sense. Commit rights can be delegated for that repository only. I can spin up `git-filter-repo` and prepare a git repository with `cython-mode` only preserving the commit history.

**Comment by scoder** [comment]
I was always considering the Emacs mode a single file, nothing that really requires a repository checkout to retrieve it. Just download it from the master branch URL and that's it.

That said, moving it to a separate repo seems fine, for exactly the same reason.

What are the trade-offs in moving it to Emacsorphanage vs. our own separate repo?

It definitely lacks a maintainer currently, so any such place will probably be better than its current.

**Comment by dnicolodi** [comment]
Probably the repository would grow some other files to have a minimum documentation and some basic tests. The Emacsorphanage makes it sound like the code is abandoned and maybe superseded by something else. The cython organization is where someone would most likely look for it. The only drawback I can see in having the repo in the cython organization is that someone with admin privileges on the organization will need to delegate the appropriate permissions on the new project for someone else to take care of it. But it is most likely something that will need to be done just once.

**Comment by scoder** [comment]
I extracted the file into its own repo under the cython organisation:

https://github.com/cython/emacs-cython-mode

To keep the history, I used:

* https://stackoverflow.com/a/37037151
* https://stackoverflow.com/a/23606462
* https://stackoverflow.com/a/13389977

If you want to help in maintaining that repo, please contact me. Thanks for the input and for bringing up this topic.

**Comment by dnicolodi** [comment]
Thank you @scoder I normally use `git-filter-repo` https://github.com/newren/git-filter-repo for this kind of things.

**Comment by tarsius** [comment]
For the Emacsmirror I used something like:

```sh
cd /tmp
git clone https://github.com/cython/cython source
git init target
git filter-repo \
    --source source \
    --target target \
    --path Tools/cython-mode.el \
    --path-rename Tools/cython-mode.el:cython-mode.el \
    --prune-empty=always \
    --prune-degenerate=always
```

**Comment by tarsius** [comment]
I've updated Melpa and the Emacsmirror to point to the new repository.

**Comment by matusvalo** [comment]
Closing this issue since the the cython-mode.el was moved to separate repo. Feel free to reopen the issue when still valid.
