### ISSUE TITLE
[ENHWhere is the openMP documentation

### ISSUE THREAD

**Issue by nyck33** [cython/cython#5125]
### Is your feature request related to a problem? Please describe.

I am looking at the last example here: https://docs.cython.org/en/latest/src/userguide/parallelism.html

Here is the documentation linked to: https://www.openmp.org/wp-content/uploads/spec30.pdf

But that is C, C++ documentation and does not actually show the API syntax at all for Cython.

You just give the one example using `with nogil, parallel():` 

The above which I have no idea which openmp c++ api it is using, with my best guess being something like:

```
void a1(int n, float *a, float *b)
{
int i;
#pragma omp parallel for
for (i=1; i<n; i++) /* i is private by default */
b[i] = (a[i] + a[i-1]) / 2.0;
```
from the linked to openmp documentation.

I also want to do reductions but in that case what is the syntax?

Are users supposed to poke around in the dark taking wild guesses at what the api calls would be by looking at C++ documentation?

If you're going to release something, please document it.  We are not all super duper brilliant like you folks.  

### Describe the solution you'd like.

Documentation of Cython OpenMP and way more examples.

Also Jupyter lab or notebook style documentation where I can execute cells, make edits, execute, etc. 

### Describe alternatives you've considered.

I'm in Jupyter lab taking guesses, also trying in a .pyx file, incredibly frustrating to say the least and I'm about to throw it away and just write C or C++ which seems wasteful of your efforts so far.

**Comment by da-woods** [comment]
Just a few quick comments:

> I also want to do reductions but in that case what is the syntax?

There's specifically an example in the documentation of that:

```
from cython.parallel import prange

cdef int i
cdef int n = 30
cdef int sum = 0

for i in prange(n, nogil=True):
    sum += i

print(sum)
```

Essentially Cython infers the reduction for you when you do `+=` or similar.

> Also Jupyter lab or notebook style documentation where I can execute cells, make edits, execute, etc.

I don't think this is realistic - I'm not sure we have the expertise or resources to set up a server where we can let people can safely run arbitrary C code. I agree it sounds nice, but I don't really see how we can do that.

> [...] just write C or C++ [...]

If you want to generate very specific OpenMP/C/C++ code then this is actually a pretty good idea - sometimes it's most appropriate to use Cython as a wrapper around some hand-written C or C++..

----------------------------------------------------------------

There's definitely room for improvement with the documentation - I think probably a "tutorial" style introduction to parallelism might be a good idea. There's a bit of a balance with writing for users that know C, and users that don't know C. You obviously want to know what OpenMP code is generated but this would be confusing to a lot of other people.

Essentially what Cython does with parallelization is `openmp parallel for` (`prange` in Cython), and `openmp parallel` (`parallel` in Cython). It's able to infer reductions for parallel for loops. There isn't a much customization available beyond that though - if you want more control you're probably better hand-writing it.

Convincing yourself that it's generated the right C code is a bit of a challenge and possibly something we should do better on. But I don't have too many good ideas here.

I'll have a go at writing a more tutorially introduction when I have time.
