### ISSUE TITLE
Drop Python 2.7, 3.4 and 3.5 support (raise minimum version to 3.6)

### ISSUE THREAD

**Issue by EwoutH** [cython/cython#5130]
Python 2.7, 3.4 and 3.5 have been [end-of-life](https://endoflife.date/python) for a long time:

- Python 2.7: Security support ended 2 years and 10 months ago (01 Jan 2020)
- Python 3.4: Security support ended 3 years and 8 months ago (18 Mar 2019)
- Python 3.5: Security support ended 2 years ago (13 Sep 2020)

The last time the Python version requirement [was raised](https://github.com/cython/cython/commit/8c490265b8c2b23e8680068c9d18210e5f82c8e7) was 4 years ago, in november 2018. At that moment, Python 2.6 and 3.3 support was removed.

So I'm curious what the thoughts are about raising the minimum version requirement.

**Comment by mattip** [comment]
Duplicate of #2800. They are targeted for removal in Cython 3.1

**Comment by EwoutH** [comment]
Thanks for both your replies! I searched but still missed that issue, thanks for linking to it. I will close this issue and discuss if there further.
