### ISSUE TITLE
[ENH] Allow const return types

### ISSUE THREAD

**Issue by mikegraham** [cython/cython#5131]
### Is your feature request related to a problem? Please describe.

Suppose I try to implement a function like

```cython
cdef const int f():
    return 1
```

Cython will generate code like
```c
static int const __pyx_f_10constrepro_f(void) {
  int const __pyx_r;
  __Pyx_RefNannyDeclarations
  __Pyx_RefNannySetupContext("f", 0);

  __pyx_r = 1;
  goto __pyx_L0;

  /* function exit code */
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}
```

Since the return value was declared like `int const __pyx_r;`, `__pyx_r = 1;` is not valid.

### Describe the solution you'd like.

I would like

```cython
cdef const int f():
    return 1
```

to generate valid code.

I believe this could be accomplished by stripping const qualifiers from the declaration of the return variable, generating code like

```c
static int const __pyx_f_10constrepro_f(void) {
  int __pyx_r; // but the function return type is still `int const`
  ...
  __pyx_r = 1;
  ...
  return __pyx_r;
}
```

**Comment by da-woods** [comment]
There's no reason why you shouldn't be able to do this and the change you propose is probably the right one. I'm not sure I understand the benefit of const return types though (except for returning const references)

**Comment by mikegraham** [comment]
I encountered this behavior while trying to implement an abstract C++ class

```cython
cdef extern from *:
    """
    class Base {
      public:
        virtual const int f() = 0;
    };
    """
    cppclass Base:
        pass

cdef cppclass Child(Base):
    int f():
        return 4
```

If I don't have the `const`, I do not successfully override `f`, but if I do have the `const`, Cython generates invalid code.

**Comment by mikegraham** [comment]
This should also apply to thinks like plain callbacks

E.g., 
```cython
from libcpp.functional cimport function

cdef g(function[const int()] h):
    pass

cdef int f():
    return 4

g(f)
```

This code isn't very realistic, but if `g` were defined externally, this would be difficult. (I think C plays fast and loose enough with function pointers that plain function pointers will not get caught on the const.)
