### ISSUE TITLE
[BUG] Receiving unused parameter warning in Fedora 37 + Cython 0.29.32

### ISSUE THREAD

**Issue by tristan957** [cython/cython#5132]
### Describe the bug

Cython is generating a warning on gcc (at least) on Fedora 37.

```
[469/1105] Compiling C object subprojects/hse-python/hse3/hse.cpython-311-x86_64-linux-gnu.so.p/meson-generated_.._hse.c.o
FAILED: subprojects/hse-python/hse3/hse.cpython-311-x86_64-linux-gnu.so.p/meson-generated_.._hse.c.o 
cc -Isubprojects/hse-python/hse3/hse.cpython-311-x86_64-linux-gnu.so.p -Isubprojects/hse-python/hse3 -I../hse/subprojects/hse-python/hse3 -Iinclude -I../hse/include -I/usr/include/python3.11 -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=gnu11 -O2 -g -fPIC -MD -MQ subprojects/hse-python/hse3/hse.cpython-311-x86_64-linux-gnu.so.p/meson-generated_.._hse.c.o -MF subprojects/hse-python/hse3/hse.cpython-311-x86_64-linux-gnu.so.p/meson-generated_.._hse.c.o.d -o subprojects/hse-python/hse3/hse.cpython-311-x86_64-linux-gnu.so.p/meson-generated_.._hse.c.o -c subprojects/hse-python/hse3/hse.c
subprojects/hse-python/hse3/hse.c: In function '__Pyx_CLineForTraceback':
subprojects/hse-python/hse3/hse.c:38110:69: error: unused parameter 'tstate' [-Werror=unused-parameter]
38110 | static int __Pyx_CLineForTraceback(CYTHON_NCP_UNUSED PyThreadState *tstate, int c_line) {
      |                                                      ~~~~~~~~~~~~~~~^~~~~~
```

I am not super sure if Cython maintainers act on bug reports of this nature.

After reading the file, I find `CYTHON_NCP_UNUSED` is defined as nothing because `CYTHON_COMPILING_IN_CPYTHON` is set to `1`.

My workaround will just be disabling this warning on the Meson side of things, but I did want to report this.

### Code to reproduce the behaviour:

This seems like boilerplate Cython generated C code.

### Expected behaviour

Ideally there is no warning.

### Environment

OS: Fedora 37 (Linux)
Python version: 3.11.0
Cython version: 0.29.32

**Comment by da-woods** [comment]
It looks like this is fixed more robustly on the the master branch (i.e. the Cython 3 alpha releases).

We do typically try to fix this type of warning where possible. Although the 0.29.x branch is a bit lower priority especially where it's diverged. So thanks for the report.

**Comment by da-woods** [comment]
It actually looks like it might be fixed in the next release anyway https://github.com/cython/cython/commit/189f6684474b9d3c5e27696f2ed961657b951204

**Comment by da-woods** [comment]
#4948

**Comment by tristan957** [comment]
Oh nice. I didn't find the ticket number because I searched "unused parameter" instead of "unused argument". Apologies :)
