### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jdavid54** [cython/cython#5136]
### Describe the bug

Try to install the packages from 
https://learnembeddedsystems.co.uk/easy-raspberry-pi-iot-server

error while running ./menu.sh

Running setup.py install for ruamel.yaml.clib did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      sys.argv ['/tmp/pip-install-w42v2zo9/ruamel-yaml-clib_ec2758fc94a7421d8aa3e020cc106826/setup.py', 'install', '--record', '/tmp/pip-record-ou8r8r84/install-record.txt', '--single-version-externally-managed', '--compile', '--install-headers', '/home/pi/Documents/IOTstack/.virtualenv-menu/include/site/python3.11/ruamel.yaml.clib']
      test compiling /tmp/tmp_ruamel_xz5xte8a/test_ruamel_yaml.c -> test_ruamel_yaml OK
      /home/pi/Documents/IOTstack/.virtualenv-menu/lib/python3.11/site-packages/setuptools/dist.py:286: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated, consider using implicit namespaces instead (PEP 420).
        warnings.warn(msg, SetuptoolsDeprecationWarning)
      running install
      /home/pi/Documents/IOTstack/.virtualenv-menu/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-311
      creating build/lib.linux-armv7l-cpython-311/ruamel
      copying .ruamel/__init__.py -> build/lib.linux-armv7l-cpython-311/ruamel
      creating build/lib.linux-armv7l-cpython-311/ruamel/yaml
      copying .ruamel/yaml/__init__.py -> build/lib.linux-armv7l-cpython-311/ruamel/yaml
      creating build/lib.linux-armv7l-cpython-311/ruamel/yaml/clib
      copying ./__init__.py -> build/lib.linux-armv7l-cpython-311/ruamel/yaml/clib
      copying ./LICENSE -> build/lib.linux-armv7l-cpython-311/ruamel/yaml/clib
      running build_ext
      building '_ruamel_yaml' extension
      creating build/temp.linux-armv7l-cpython-311
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/pi/Documents/IOTstack/.virtualenv-menu/include -I/usr/local/include/python3.11 -c _ruamel_yaml.c -o build/temp.linux-armv7l-cpython-311/_ruamel_yaml.o
      _ruamel_yaml.c:198:12: fatal error: longintrepr.h: Aucun fichier ou dossier de ce type
         #include "longintrepr.h"
                  ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

### Code to reproduce the behaviour:

```cython
# example code
```

### Environment

OS: [e.g. Linux, Windows, macOS]
Python version [e.g. 3.10.2]
Cython version [e.g. 3.0.0a11]

**Comment by mattip** [comment]
That might be due to using a really old version of [ruamel.yaml](https://sourceforge.net/p/ruamel-yaml/code/ci/0.11.0/tree/ext/_ruamel_yaml.c) which ships pre-cythonized versions of *.pyx files built for python2 only. I am not sure how to fix this for your use case, you might get further commenting on the tutorial itself.

**Comment by scoder** [comment]
Not an issue in Cython itself but in a third-party tool that *uses* Cython.
