### ISSUE TITLE
[ENH] 

### ISSUE THREAD

**Issue by OmusubiGX7** [cython/cython#5143]
### Is your feature request related to a problem? Please describe.

The following code does not compile.
If '=' is removed, it can compile.

foo = "bar"
print(f"{ foo = }")

foo = 'bar'
print(f'{ foo = }')

### Describe the solution you'd like.

I would like to be able to compile the above code.

**Comment by da-woods** [comment]
Works for me on the Cython 3 alpha releases. I don't think this is in the 0.29.x branch (and it probably won't be).
