### ISSUE TITLE
[BUG] Sage reports performance loss with binding=True

### ISSUE THREAD

**Issue by da-woods** [cython/cython#5144]
### Describe the bug

Sage reports ~25% performance drop when calling functions with bind=True. See https://groups.google.com/g/cython-users/c/1ImgS3mv_kE for a more complete description

### Environment

Cython 3 alpha, unknown Python version or OS.

**Comment by nbruin** [comment]
This was tested on:
```
$ sage --version
SageMath version 9.7.rc2, Release Date: 2022-09-17
$ python --version
Python 3.10.8
$ uname -a
Linux *** 6.0.7-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 3 17:09:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ cat /proc/cpuinfo
...
model name	: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
...
```
Code used to test:
```
%%cython
cimport cython

@cython.binding(False)
cdef class Unbinding(UB):
    def test(self): return 1

@cython.binding(True)
cdef class Binding(UB):
    def test(self): return 1

def fetch_test(a, N=100):
    for i in range(N): _ = a.test

def call_test(a, N=100):
    for i in range(N): _ = a.test()
```
timing results:
```
>>> U=Unbinding()
>>> B=Binding()
>>> %timeit fetch_test(U,100000)
4.41 ms ± 45.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
>>> %timeit fetch_test(B,100000)
4.06 ms ± 30.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
>>> %timeit call_test(U,100000)
5.08 ms ± 41.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
>>> %timeit call_test(B,100000)
7.2 ms ± 148 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
which shows that just fetching a binding method seems a slight bit cheaper, but fetching-and-calling it is considerably more expensive than a non-binding method.

**Comment by da-woods** [comment]
So when I try (Python 3.10.6, Cython master, `Linux *** 5.19.2-1-default #1 SMP PREEMPT_DYNAMIC Thu Aug 18 05:06:49 UTC 2022 (6c252ef) x86_64 x86_64 x86_64 GNU/Linux`, Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz)

```
In [6]: %timeit fetch_test(U, 100000)
5.3 ms ± 42.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: %timeit fetch_test(B, 100000)
4.61 ms ± 59.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [8]: %timeit call_test(U, 100000)
6.31 ms ± 70.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [9]: %timeit call_test(B, 100000)
5.47 ms ± 43.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

That was compiling the file with `cython -if filename.pyx` on the command line (mentioning it because it might give different compiler flags).

So on my PC it looks like binding is faster in both cases (I tried rerunning a few times and it looked reproducible). So I may struggle to investigate.

**Comment by nbruin** [comment]
Cool! those timings suggest that this problem is actually fixed by upgrading to `Cython master`. If that's indeed the case then this will not be a problem for transitioning to cython 3 (provided the required changes in master are already present there, which might be the case)

**Comment by matusvalo** [comment]
@nbruin what version of Cython 3 alpha are you using?

**Comment by nbruin** [comment]
I've now succeeded in getting 3.0.0a11. I can confirm that in the test above, "Binding" performs uniformly better! We can close this, I think. Thanks for helping me check.

**Comment by da-woods** [comment]
One last comment: We ended up disabling fast all/vectorcall in Python 3.10+ on the 0.29.x branch because it was causing problems with tracing (and things had diverged enough that we couldn't backport easily)

https://github.com/cython/cython/pull/4735

You're probably seeing the results of that. But I'm not going to bisect in detail to verify.
