### ISSUE TITLE
`PyUnicode_AsUnicode` is deprecated, slated for removal in 3.12

### ISSUE THREAD

**Issue by mattip** [cython/cython#5149]
A call to `PyUnicode_AsUnicode` exposes the `PyUnicodeObject.wstr` field. This is removed in 3.12. The [documentation](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUnicode) says it is deprecated since 3.3, and it was removed in python/cpython#92537. This will require a workaround for this code https://github.com/cython/cython/blob/849d14785367e8e74faf0ecc579430007cf1c6e6/Cython/Utility/TypeConversion.c#L101

which is used here
https://github.com/cython/cython/blob/0e1d4bc61225bf382abb5d27399e3fe339552f6e/Cython/Compiler/PyrexTypes.py#L2563

I ran up against this in the py_unicode_strings tests when it uses a `unicode` object in a call to a cdef function with this signature `cdef assert_Py_UNICODE_equal(const Py_UNICODE* u1, const Py_UNICODE* u2)` 
https://github.com/cython/cython/blob/e9ffbb8f3e30f8de9ba118d476167e64ca1e36f9/tests/run/py_unicode_strings.pyx#L98. 

The code might be hard to replace 1:1 since there is no longer a safe way to access the underlying PyUnicodeObject internal buffer, the remaining interfaces all need to deal with freeing the buffer when done with it.

**Comment by da-woods** [comment]
I'm not convinced that this is a huge issue. Essentially this conversion function only applies for pointers defined as `Py_UNICODE*`. If any user code uses those then it'll probably become obsolete anyway and it's not our fault.

So really the question is "should we remove the test, change the test, or only run it on supported versions"?

**Comment by da-woods** [comment]
In terms of the type conversion, I think we should just add a warning to Cython when people try to use it saying "type conversion from Python objects to Py_UNICODE* will only work on versions of Python that provide Py_UNICODE APIs. These are scheduled for removal in Python 3.12" or something similar. I don't think Cython is obliged to find workarounds beyond that.

**Comment by scoder** [comment]
> only run it on supported versions

This.

> add a warning to Cython

Sounds good, too, although not visible by default, as we usually do. Now that there is an actual removal, it's good to warn about it, but people who use it probably know what they're doing at some point and don't need the warning any more, even if they keep their code around for supported Python versions.

**Comment by mattip** [comment]
Closing, although I never found a good place to add a warning. Please reopen if that should be part of this issue.
