### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pcarbonn** [cython/cython#5153]
### Describe the bug

I get an error when building a cp310-win32 wheel:

    pyDatalog/pyEngine.c(59079): warning C4013: '_PyGen_Send' undefined; assuming extern returning int
    ...
    pyEngine.obj : error LNK2001: unresolved external symbol __PyGen_Send
    ...
    fatal error LNK1120: 1 unresolved externals

### Code to reproduce the behaviour:

`cython pyDatalog/pyEngine.py` creates a pyEngine.c file that contains `_PyGen_Send`, instead of `PyIter_Send()`.

### Expected behaviour

`pyEngine.obj` should link when creating the wheel.

### Environment

OS: [Windows]
Python version [3.10]
Cython version [0.29.32]

### Additional context

I'll try creating 'pyEngine.c' again with Cython 0.29.22, or Cython 3.0a11 instead.

This was fixed in 0.29.22 (https://github.com/cython/cython/issues/3876), but it seems to reappear.

**Comment by da-woods** [comment]
Can you post the first few lines of pyEngine.c and a few lines around line 59079 (say 5 lines before to 5 lines after)?

My suspicion is that you just haven't regenerated the .c file

**Comment by pcarbonn** [comment]
I did regenerate pyEngine.c, but I thought I had Cython 0.29.32, and it was not the case.  (Python 2 had it, but not Python 3; using pip3 fixed it)
