### ISSUE TITLE
Cython 0.29.33 release with depfile support?

### ISSUE THREAD

**Issue by dnicolodi** [cython/cython#5158]
I know the issue tracker is probably not the best place where to ask this, but I already wrote to the development mailing list and I didn't receive any answer. Therefore I'm trying again here.

I've seen some activity that may hint toward an upcoming Cython 0.29.33 release. This release will include the depfile support. Meson included  native support for compiling Cython code and having support for depfiles would enable it to correclty rebuild the Cython artifacts when any of the dependencies change. SciPy is leading the way in the scientific Python community for a switch from setuptools to Meson as build system. The depfile support would simplify this transition.

Meson is moving toward an 1.0 release at the beginning of December. It would be awesome if this release could come with Cython dependency tracking support. Is there an expected release date for Cython 0.29.33?  Is there anything that can be done to help with getting the release out of the door?

**Comment by matusvalo** [comment]
Cython 0.29.33 should be release before christmas - see following thread: https://groups.google.com/g/cython-users/c/9hrd0qv8Sdw

**Comment by h-vetinari** [comment]
@scoder @da-woods 
Thanks for the release! This issue can be closed now I guess.

Sidenote: the GH release has a lot of artefacts attached already, but nothing seems to have made it to PyPI [yet](https://pypi.org/project/Cython/).
