### ISSUE TITLE
[BUG] Required number of arguments for __pow__ prevents compiled and interpreted pure python code compatability

### ISSUE THREAD

**Issue by jtoledo1974** [cython/cython#5160]
### Describe the bug

Cython mandates three argument for the special method __pow__ . My class makes no use of the third argument, but when compiling the code cython forces me to define one without a default value

That mean that code using the exponteation operator must have two different implementations depending on whether it is running as compiled code or as interpreted code. I believe this defeats the purpose of pure python, which is one of the goals of cython 3.

### Code to reproduce the behaviour:

```cython
@cython.cclass
class Pow:
    def __pow__(self, x):
        return x
```

Fails with 

```
(venv311) C:\Users\Juan\cruji-enaire>python setup.py build_ext --inplace
Compiling src/crujisim/cythontests.py because it changed.
[1/1] Cythonizing src/crujisim/cythontests.py

Error compiling Cython file:
------------------------------------------------------------
...
@cython.cclass
class Pow:
    def __pow__(self, x):
    ^
------------------------------------------------------------

src\crujisim\cythontests.py:514:4: Special method __pow__ has wrong number of arguments (2 declared, 3 expected)
```

When trying to compile with a default argument,

```cython
@cython.cclass
class Pow:
    def __pow__(self, x, m=None):
        return x
```

Now fails because it won't accept a default value

```
(venv311) C:\Users\Juan\cruji-enaire>python setup.py build_ext --inplace
Compiling src/crujisim/cythontests.py because it changed.
[1/1] Cythonizing src/crujisim/cythontests.py

Error compiling Cython file:
------------------------------------------------------------
...
@cython.cclass
class Pow:
    def __pow__(self, x, m=None):
                         ^
------------------------------------------------------------

src\crujisim\cythontests.py:514:25: This argument cannot have a default value
```

Finally, the solution that cython will be happy with:

```cython
@cython.cclass
class Pow:
    def __pow__(self, x, m):
        return x
```

fails in interpreted mode because now the third argument is mandatory

```
In [1]: from crujisim.cythontests import Pow

In [2]: p = Pow()

In [3]: p ** 5
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [3], line 1
----> 1 p ** 5

TypeError: Pow.__pow__() missing 1 required positional argument: 'm'
```

### Expected behaviour

I expect to be able to write a valid python .py file that I can optionally compile with cython to obtain speed advantages, but should work both compiled and interpreted.

I can work around it using `@cython.compiled`, but I believe  this should not be necessary

### Environment

OS: Windows
Python version 3.11
Cython version 3.0.0a11

**Comment by da-woods** [comment]
I think this would likely be tricky but not impossible (so we probably should do it, but I wouldn't expect it to be soon).

The special methods of cclasses map pretty directly onto the C API slots, and in this case the C API slot only defines the 3 argument version.

In terms of implementation there's two things we could do:
1. Special-case it to allow a 3rd default argument of `None` (since this is the value that the Python internals use by default). We wouldn't allow any other default values.
2. Convert the two argument version into a small wrapper function that just checks the third argument is `None`.

**Comment by scoder** [comment]
Python gives a `TypeError` if the 3-argument version is used but not implemented:
```python
>>> class C:
...   def __pow__(self, other): return 5 * other
... 
>>> pow(C(), 3)
15
>>> pow(C(), 3, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __pow__() takes 2 positional arguments but 3 were given
```
I think we need to generate a wrapper slot function here that raises this exception if a third argument is passed. Although, we already *do* generate a wrapper function any way (in `ModuleNode.generate_binop_function()`), so maybe we can fold that special case into it and accept both signatures?

**Comment by scoder** [comment]
BTW, this doesn't seem specific to Python code. It seems helpful to support this also in Cython code. We should generally allow 2 or 3 arguments for  `__pow__` and let users choose which they prefer to implement.
