### ISSUE TITLE
[BUG] Python power operator to negative power as cython integer is not casted to float

### ISSUE THREAD

**Issue by L1nkus** [cython/cython#5162]
### Describe the bug

Python power operator to negative power as cython integer is not casted to float.

### Code to reproduce the behaviour:

```cython
import cython
cython.declare(lotsizes=cython.int) # without this, it's good.
x = 0.011
y = 3
x -= 10 ** -y
# if ^^ were 10.0 instead of 10, it is fine.
print(x) # 0.011 with cython. 0.009999999999999998 in python
```

### Expected behaviour

10 ** -y shouldn't evaluate to 0, but to 0.001

### Environment

OS: Linux
Python version 3.10.7
Cython version 0.29.30

**Comment by da-woods** [comment]
https://github.com/cython/cython/issues/4936
