### ISSUE TITLE
Windows builds failing with C syntax error

### ISSUE THREAD

**Issue by da-woods** [cython/cython#5169]
See for example https://github.com/cython/cython/actions/runs/3669311794/jobs/6203055738

```
D:\a\cython\cython\Cython\Compiler\Parsing.c(5011): error C2059: syntax error: '}'
```

_Originally reported by @yudonglin in https://github.com/cython/cython/issues/4897#issuecomment-1345651917_ but actually universally to the current Windows builds and has nothing to do with the proposed pattern matching changes.

We should probably also turn off "allow-failures" on at least some of the Windows CIs.

**Comment by yudonglin** [comment]
By the way, since I assume you are creating an empty struct here, I change manually change `={}` to `={0}`, and it works just fine.

**Comment by da-woods** [comment]
> By the way, since I assume you are creating an empty struct here, I change manually change `={}` to `={0}`, and it works just fine.

Thanks. Can you check that works in C++ too and submit a PR :)

**Comment by da-woods** [comment]
For reference it's ModuleNode.py line 2790 `module_state.putln('static %s %s_static = {};' % (`

(can submit a the change myself though if you don't want to)

**Comment by yudonglin** [comment]
sure
