### ISSUE TITLE
How to return Optional[object] in cpdef functions?

### ISSUE THREAD

**Issue by ahsand97** [cython/cython#5174]
Is there any way to specify the return type having Optional in cpdef functions?

```cython

def my_function(a: str) -> Optional[str]:   # <-- This works
    if a == some_condition:
        return "yes"
    return None

cpdef my_function(str a): # <-- This also works, leaving the return type empty
    if a == some_condition:
        return "yes"
    return None

cpdef Optional[str] my_function(str a): # <-- This doesn't work, error 'Optional' is not a type identifier
    if a == some_condition:
        return "yes"
    return None
```

Is there any way to specify an optional return parameter? having no return type in the function signature it allows to return anything and I'd like to be able to specify that either None or an object is returned

**Comment by da-woods** [comment]
You have something that works so use that.

However, please ask support questions on the Cython-users mailing list in future, not GitHub

**Comment by matusvalo** [comment]
Yes posting to cython-users is the best place. But in any case if I am not wrong `Optional[str]` as returning type is not supported by cython currently:

```python
import cython

@cython.ccall
def my_function(a: str) -> Optional[str]:
    if a is None:
        return "yes"
    return None
```

```
$ cython -3a test.py

Error compiling Cython file:
------------------------------------------------------------
...
import cython

@cython.ccall
def my_function(a: str) -> Optional[str]:
                           ^
------------------------------------------------------------

test.py:4:27: Not a type

Error compiling Cython file:
------------------------------------------------------------
...
import cython

@cython.ccall
def my_function(a: str) -> Optional[str]:
    if a is None:
        return "yes"
               ^
------------------------------------------------------------

test.py:6:15: Unicode literals do not support coercion to C types other than Py_UNICODE/Py_UCS4 (for characters) or Py_UNICODE* (for strings).
```

**Comment by ahsand97** [comment]
> But in any case if I am not wrong `Optional[str]` as returning type is not supported by cython currently:

It works in pure cython mode for **def** functions, but not for **cpdef** functions

**Comment by matusvalo** [comment]
For **def** functions it works because cython is not evaluating returning type for them since it is standard python function. When you define **cpdef** function cython is creating fast C function for which it evaluates parameter and returning types (see [1] for details). But you can emulate **cpdef** function as follows (it is also rough equivalent what cython generates for **cpdef** function):

```python
import cython

@cython.cfunc
def my_cfunction(a: str) -> str:       # Here we are returning str because you cannot use `Optional[str]` in cdef function
    if a is None:
        return "yes"
    return None

def my_function(a: str) -> Optional[str]: 
    return my_cfunction(a)
```


[1] https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#python-functions-vs-c-functions
