### ISSUE TITLE
[BUG] [Python 3.12] py35_asyncio_async_def raises RuntimeError: There is no current event loop in thread 'MainThread'.

### ISSUE THREAD

**Issue by hroncok** [cython/cython#5183]
### Describe the bug

We have this test failure in Fedora with Python 3.12.0a3:

```
Traceback (most recent call last):
  File "/builddir/build/BUILD/cython-0.29.32/TEST_TMP/0/run/py35_asyncio_async_def/main.py", line 9, in <module>
    with closing(asyncio.get_event_loop()) as loop:
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/events.py", line 676, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

This is from 0.29.32 but I see the same code in the master branch:

https://github.com/cython/cython/blob/b2cad768499cf5763251fe757491e9fc24a1f583/tests/run/py35_asyncio_async_def.srctree#L28

### Code to reproduce the behaviour:

Run tests with Python 3.12.0a3.

### Expected behaviour

Tests pass.

### Environment

OS: Fedora Linux
Python version: 3.12.0a3
Cython version: 0.29.32 or master branch

### Additional context

https://docs.python.org/3.12/whatsnew/3.12.html#changes-in-the-python-api

> [`asyncio.get_event_loop()`](https://docs.python.org/3.12/library/asyncio-eventloop.html#asyncio.get_event_loop "asyncio.get_event_loop") and many other [`asyncio`](https://docs.python.org/3.12/library/asyncio.html#module-asyncio "asyncio: Asynchronous I/O.") functions like [`ensure_future()`](https://docs.python.org/3.12/library/asyncio-future.html#asyncio.ensure_future "asyncio.ensure_future"), [`shield()`](https://docs.python.org/3.12/library/asyncio-task.html#asyncio.shield "asyncio.shield") or [`gather()`](https://docs.python.org/3.12/library/asyncio-task.html#asyncio.gather "asyncio.gather"), and also the `get_event_loop()` method of `BaseDefaultEventLoopPolicy` now raise a [`RuntimeError`](https://docs.python.org/3.12/library/exceptions.html#RuntimeError "RuntimeError") if called when there is no running event loop and the current event loop was not set. Previously they implicitly created and set a new current event loop. [`DeprecationWarning`](https://docs.python.org/3.12/library/exceptions.html#DeprecationWarning "DeprecationWarning") is no longer emitted if there is no running event loop but the current event loop is set in the policy. (Contributed by Serhiy Storchaka in [gh-93453](https://github.com/python/cpython/issues/93453).)

**Comment by scoder** [comment]
Closed in https://github.com/cython/cython/pull/5188
