### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AndreiKeino** [cython/cython#5191]
### Describe the bug

after trying to run cythonized project I've get:

File "/usr/lib/python3.8/dataclasses.py", line 1019, in dataclass
    return wrap(cls)
  File "/usr/lib/python3.8/dataclasses.py", line 1011, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/lib/python3.8/dataclasses.py", line 885, in _process_class
    raise TypeError(f'{name!r} is a field but has no type annotation')
TypeError: 'df_fname_list' is a field but has no type annotation

$ python -V
Python 3.8.10

pip freeze | grep -i cython
Cython==3.0a1

@dataclass
class PathNameInfo:
    df_path: Optional[str]
    df_col_name: Optional[str]
    df_fname_list: List[str] = field(default_factory=lambda: [])
    index: int = 0

As I know this is an old bug and it was reported as a fixed one `a` couple of years ago. See https://github.com/cython/cython/issues/2552

### Expected behaviour

Should work as is.

### Environment

ubuntu 20.4

$ python -V
Python 3.8.10

pip freeze | grep -i cython
Cython==3.0a1

**Comment by da-woods** [comment]
> pip freeze | grep -i cython
> Cython==3.0a1

> As I know this is an old bug and it was reported as a fixed one a couple of years ago. See #2552

It was fixed in Cython 3.0a7 and you're using Cython 3.0a1.

**Comment by AndreiKeino** [comment]
Thanks.

**Comment by AndreiKeino** [comment]
You are incorrect. It not working neither with cython 3.0a7, nor with cython 3.0.0a11. Also it shows incorrect cython version. See https://github.com/cython/cython/issues/5192
