### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AndreiKeino** [cython/cython#5192]
##### https://github.com/cython/cython/issues/5191 is not solved - TypeError(f'{name!r} is a field but has no type annotation'**

sudo pip install cython==3.0.0a11
Collecting cython==3.0.0a11
  Using cached Cython-3.0.0a11-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.4 MB)
Installing collected packages: cython
Successfully installed cython-3.0.0a11

pip freeze | grep -i cython
Cython==3.0a1
```
$ python
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cython
>>> cython.__version__
'3.0a1'
```

File "/usr/lib/python3.8/dataclasses.py", line 1019, in dataclass
return wrap(cls)
File "/usr/lib/python3.8/dataclasses.py", line 1011, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
File "/usr/lib/python3.8/dataclasses.py", line 885, in _process_class
raise TypeError(f'{name!r} is a field but has no type annotation')
TypeError: 'df_fname_list' is a field but has no type annotation
### Code to reproduce the behaviour:

```
@dataclass
class PathNameInfo:
df_path: Optional[str]
df_col_name: Optional[str]
df_fname_list: List[str] = field(default_factory=lambda: [])
index: int = 0

```

### Expected behaviour

- should show the correct version - 3.0.0a11
- should run the code as is but it reproduces https://github.com/cython/cython/issues/5191

### Environment

sb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 20.04.5 LTS
Release: 20.04
Codename: focal

$ python -V
Python 3.8.10

**Comment by da-woods** [comment]
Your code compiles fine for me on 3.0.0a11.

I think you have 3.0a1 installed somewhere where it gets found before 3.0.0a11 (maybe user account vs super-user account?). However, this pip support question rather than a Cython bug. The Cython bug tracker is not intended for be a support forum so we will not be able to help you sort out your Python environment here.

The [Cython-users mailing list](https://groups.google.com/g/cython-users) is out "official" support forum.

**Comment by AndreiKeino** [comment]
**Your code compiles fine for me on 3.0.0a11.**

OK, I'll look to it.

**Comment by da-woods** [comment]
Sorry I didn't try executing it.

I have now and I can confirm that the code executes fine for me on 3.0.0a11

**Comment by AndreiKeino** [comment]
Thank you finally)
