### ISSUE TITLE
[BUG] sdist is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [cython/cython#5193]
### Describe the bug

The sdist package at PyPI (see https://pypi.org/project/Cython/#files) does not contain the `tox.ini` file.  Please add the file to sdist to make the downstream testing easier.  Thank you.

### Environment

Cython version: 0.29.32

**Comment by scoder** [comment]
Thanks, I've included the file for the next release.

However, the most likely reason why it was missing from the sdist is that we aren't using it. Even the list of test envs was entirely outdated. We might end up removing the file rather than keeping it up to date.

**Comment by mtelka** [comment]
Thank you for adding the file.

The list of envs is not very important to be up to date.  The most important part is the `[testenv]` section.  With the proper `[testenv]` I could simply run (the usual) `tox --current-env --no-provision --recreate -e py39`, instead of trying to find what is the proper way to run tests.  In case of Cython it is apparently `make test` which is extremely rare.  Even direct `pytest` run (which is another typical way to run tests without the `tox.init` file) does not work here.
