### ISSUE TITLE
[BUG] module 'cython' has no attribute 'annotation_typing'

### ISSUE THREAD

**Issue by hank0137** [cython/cython#5194]
### Describe the bug

Hello, I asked this question on StackOverflow and I was referred here as it may be a bug.  I can provide additional information but I think my [SO post](https://stackoverflow.com/questions/75004800/module-cython-has-no-attribute-annotation-typing) covers it succinctly.  

I just recently updated Cython from 0.29.24 to 3.0.0a11 and I was getting compilation errors due to functions that were using Dict type hints. With the previous versions, I never had any issues of this type (no pun intended). I compile my entire python project by building Extensions using cythonize in a setup.py file. I am using Python 3.9.13.

After doing some reading I attempted to solve the issues I was having by using the [compiler directive](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#disabling-annotations) as follows:

### Code to reproduce the behaviour:

```cython
import cython

@cython.annotation_typing(False)
def my_function_with_type_hints(this_object: Dict) -> Dict:
   pass
```

### Expected behaviour

Compilation succeeded although I have not tested my compiled code yet. I returned to development to test some new code and now I am unable to run code in interpeter mode because Cython is complaining "module 'cython' has no attribute 'annotation_typing'". I confirmed (via pip freeze) that Cython==3.0.0a11 is installed in my environment and that my environment is activated (in vscode).

My questions:

Did I fix the typing issue correctly using the compiler directive or am I not understanding the problem fully?
How should I be using compiler directives in interpreter mode? Do I need another decorator that conditionally includes the cython directive?

### Environment

Python version 3.9.13
Cython version 3.0.0a11

**Comment by 0dminnimda** [comment]
Huh, I wonder how it was not discovered earlier...
It is a legitimate bug, `annotation_typing()` is not defined in the shadow.py

As a temporary solution, you can have `cython.annotation_typing = lambada x: x` in the main file
Also, you should try to look into the [compiler directive](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives) `annotation_typing`, which applies to all of the compiled functions

**Comment by hank0137** [comment]
Thank @0dminnimda, I'm glad that it was not something obvious that I was ignoring.  When you say, "in the main file" do you mean in my main file (entrypoint) or cython's?

**Comment by 0dminnimda** [comment]
Yes, your main file, as it's not the best practice to change code in the installed libraries
Also as @da-woods suggests it's probably better to do this when using a python interpreter and account for `with` statements: `if not cython.compiled: cython.annotation_typing = cython.returns` (`cython.returns == cython.boundscheck`, just shorter)
But I would still discourage you from using it
