### ISSUE TITLE
[BUG] test_int_pow fails

### ISSUE THREAD

**Issue by mtelka** [cython/cython#5198]
### Describe the bug

Some `test_int_pow` tests fails:

| | c | cpp |
|-|---|---|
| complex_numbers_T305 | ok | FAIL |
| complex_numbers_c89_T398 | ok | ok |
| complex_numbers_c99_T398 | FAIL | FAIL |
| complex_numbers_cxx_T398 | ok | FAIL |

All four failures are like this:
```
FAIL: test_int_pow (complex_numbers_cxx_T398)
Doctest: complex_numbers_cxx_T398.test_int_pow
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/doctest.py", line 2205, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for complex_numbers_cxx_T398.test_int_pow
  File "$(BUILD_DIR)/TEST_TMP/run/cpp/complex_numbers_cxx_T398/complex_numbers_cxx_T398.cpython-39.so", line unknown line number, in test_int_pow

----------------------------------------------------------------------
File "$(BUILD_DIR)/TEST_TMP/run/cpp/complex_numbers_cxx_T398/complex_numbers_cxx_T398.cpython-39.so", line ?, in complex_numbers_cxx_T398.test_int_pow
Failed example:
    [test_int_pow(complex(0, 2), k, 1e-15) for k in range(-4, 5)]
Expected:
    [True, True, True, True, True, True, True, True, True]
Got:
    [False, False, False, False, True, True, False, False, False]
```

### Code to reproduce the behaviour:

```
tox --current-env --no-provision --recreate -e py39
```

### Environment

OS: OpenIndiana
Python version: 3.9.16
Cython version: 0.29.32
GCC version: 10.4.0

### Additional context

I'm packaging Cython for OpenIndiana and I'd like to make sure Cython is built and packaged properly.  Thanks.

**Comment by mtelka** [comment]
To workaround the issue I applied the following patch:
```
--- Cython-0.29.32/tests/run/complex_numbers_T305.pyx.orig
+++ Cython-0.29.32/tests/run/complex_numbers_T305.pyx
@@ -91,8 +91,6 @@
     """
     >>> [test_int_pow(complex(0, 1), k, 1e-15) for k in range(-4, 5)]
     [True, True, True, True, True, True, True, True, True]
-    >>> [test_int_pow(complex(0, 2), k, 1e-15) for k in range(-4, 5)]
-    [True, True, True, True, True, True, True, True, True]
     >>> [test_int_pow(complex(2, 0.5), k, 1e-14) for k in range(0, 10)]
     [True, True, True, True, True, True, True, True, True, True]
     >>> test_int_pow(-0.5, 5, tol=1e-15)
```
Now all `test_int_pow` tests pass.

**Comment by da-woods** [comment]
It's probably just a small floating point rounding difference, so may not matter.

But if you want more useful diagnostics I'd try:

```
[test_int_pow(complex(0, 2), k, None) for k in range(-4, 5)]
```

That'll just return the raw numbers from the calculation without comparison to a tolerance, so we can see how much they're off by.

**Comment by da-woods** [comment]
It looks to me (based on what tests are failing) like Cython's own implementation is passing but that the versions where it falls back to the C and C++ standard libraries may be failing.

If that's the case it's kind of out of our hand and needs fixing in the platform standard libraries.

To confirm that can you try compiling and running the following c++ program:

```
#include <complex>
#include <cstdio>

int main() {
    for (int k=-4; k<5; ++k) {
        std::complex<double> res = std::pow(std::complex<double>(0, 2), std::complex<double>(k, 0));
        std::printf("%d (%g %g)\n", k, res.real(), res.imag());
    }
    return 0;
}
```

(Can just be compiled with `g++ test_int_pow.cpp -o test_int_pow` assuming your compiler is gcc and run with ./test_int_pow`)

**Comment by da-woods** [comment]
> But I still do not understand why it passed for complex_numbers_c89_T398

C89 doesn't define complex.h. So it'll be using Cython's own complex number implementation (which you can force with the define `CYTHON_CCOMPLEX=0` if you want to work around this issue in real code).

I'll close this issue because it's third party.

**Comment by mtelka** [comment]
Thank you for explanation.  Really appreciated!
