### ISSUE TITLE
[ENH] Allow to package multiple modules in one shared object

### ISSUE THREAD

**Issue by rjungbeck** [cython/cython#5227]
### Is your feature request related to a problem? Please describe.

In my code, I would like to compile multiple modules into a single shared object (.so or .pyd).

### Describe the solution you'd like.

The functionality could be like cython_freeze but instead of creating a main function it would create a PyInit_mypackage that calls the PyInit_module functions of all the modules  and register the modules as buildin.

**Comment by TeamSpen210** [comment]
This would be a quite handy feature for writing accelerator modules. Currently I have a bunch for various parts of my package, meaning they all get built separately, have duplicate copies of utility code, constants and imports, etc. Each only has a few visible names for the public API. It'd be nice if there was a way to merge several, having Cython mangle names to avoid conflicts for the internals, reuse constants/utility code/imports. Then verify there's not overlaps on the Python-exposed API, and bundle all those into the same namespace for Python code to import from.

No idea if the structure of Cython would allow for this to be done without major rearchitecturing.

**Comment by da-woods** [comment]
I think the deduplication of utility code should be treated as a separate issue (last time I looked at it I decided that it might be worthwhile for the memoryview code but really not for everything else).

Bundling modules into one .so file becomes a simpler problem if you compile each module to separate C files, use internal linkage for everything (which we basically do) and then the only name clashes that you need to worry about are the module init functions.

There's at least a couple of third-party tools that do this for Cython modules:
* https://github.com/smok-serwis/snakehouse
* https://github.com/dave-msk/merak

**Comment by rjungbeck** [comment]
I was not able to use any of these solutions directly (because I wanted to convert .py files into a web assembly file for pyodide).

But I was able to use the main idea behind snakehouse (ie use templates to create a .bootstrap pyx  and .h file, extend sys.meta_path) to get my problem solved.
