### ISSUE TITLE
[BUG] Compilation crashes when using `const`-qualified customly fused-typed memoryview parameters for `def` function

### ISSUE THREAD

**Issue by jjerphan** [cython/cython#5230]
### Describe the bug

As of Cython 0.29.33, compilation crashes:
 - when defining a `def` function with a memoryview as a parameter
 - when a custom fused type is defined using NumPy types 
 - when using `const`-qualification on a memoryview typed with this custom fused type

### Code to reproduce the behaviour:

This crashes:
```cython
cimport numpy as cnp

ctypedef fused fused_t:
    cnp.float32_t
    cnp.float64_t
    cnp.int32_t
    cnp.int64_t

def _func(
    const fused_t[:] data,
):    
    return
```

with this trace:

```
Error compiling Cython file:
------------------------------------------------------------
...
    cdef __Pyx_memviewslice memslice
    cdef Py_ssize_t itemsize
    cdef bint dtype_signed
    cdef char kind
    itemsize = -1
    cdef bint ___pyx_const int32_t_is_signed
                          ^
------------------------------------------------------------

(tree fragment):16:27: Syntax error in C variable declaration
```

<details>
<summary>Alternatives that compiles</summary>

The following snippets compiles:

```cython
ctypedef fused fused_t:
    float
    double
    int
    long

def _func(
    const fused_t[:] data,
):    
    return
```

```cython
from cython cimport numeric

def _func(
    const numeric[:] data,
):    
    return
```

```cython
cimport numpy as cnp

ctypedef fused fused_t:
    cnp.float32_t
    cnp.float64_t
    cnp.int32_t
    cnp.int64_t

cdef void _func(
    const fused_t[:] data,
):    
    return
```

</details>

### Expected behaviour

This must compile and work.

### Environment

OS: Linux
Python version 3.11.0
Cython version 0.29.33

### Additional context

First observed in https://github.com/scikit-learn/scikit-learn/pull/25041/files#r1087947278 as of https://github.com/scikit-learn/scikit-learn/pull/25041/commits/563fd00a8a729519b3d9be9a433b8df60a0f5ef0.

**Comment by da-woods** [comment]
It's broken on master too. It looks fairly obvious to fix though so I'll do it at the weekend if no-one gets there first.
