### ISSUE TITLE
[Doc] Softdeprecate C style array declaration

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5245]
### Is your feature request related to a problem? Please describe.

Cython currently supports two ways how to declare an array:
```cython
cdef int arr1[4]   # C style array declaration
cdef int[4] arr1   # Java style array declaration
```

it seems that both of them generate same C code but the Java style (cdef int[4] arr1) is more consistent because:

1. Memoryviews are defined in the same way: `cdef int [:, :, :] narr_view = narr` [1]
2. As mentioned in the bug report Cython currently supports `cdef int[4] arr2 = [1, 2, 3, 4]` but not `cdef int arr[4] = [1, 2, 3, 4]` #5179
3. Defining fused types uses syntax of `TYPE[n]` [2]:
    ```cython
    ctypedef fused my_fused_type:
        int[3]
        float[2]
   ```

[1] https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html

### Describe the solution you'd like.

Soft-deprecate C style definition - use only Java style array definition (`cdef int[4] arr1`) in Cython Documentation in all places but still support the C style (to keep backward compatibility).

### Additional context

See https://github.com/cython/cython/issues/5179#issuecomment-1409259055

**Comment by scoder** [comment]
Seems right to me, we should migrate the documentation to Java style.

**Comment by jrenaud90** [comment]
This syntax change does not appear to apply to pointers, correct? For example, the following code works fine.
```python
cdef char[4] char_array
```

But this does not work (produces "Syntax error in C variable declaration"),
```python
cdef char*[4] char_ptr_array
```

Changing it to the c-declaration style does work.
```python
cdef char* char_ptr_array[4]
```

The documentation states that "C-style array declarations (`cdef int a[4]`) are now (silently) deprecated in favour of the Java-style `cdef int[4] a` form. Will `cdef char*[4] char_ptr_array` be allowed in the future. More importantly, will a hard deprecation block `cdef char* char_ptr_array[4]` soon?

Running Cython 3.0.4

**Comment by da-woods** [comment]
@jrenaud90 I don't think the plan here is to do more than update the documentation to use the java style. So don't worry about using the other style for pointer arrays.

**Comment by matusvalo** [comment]
> This syntax change does not appear to apply to pointers, correct?

No it does supports it:

* `cdef char[4] *char_ptr_array` is equivalent to `cdef char (*char_ptr_array)[4]` and translates to C `char (*__pyx_v_6delete_char_ptr_array)[4]`
* `cdef (char *)[4] char_ptr_array` is equivalent to `cdef char *char_ptr_array[4]` and translates to C `char *__pyx_v_6delete_char_ptr_array[4]`

For difference between them see https://www.geeksforgeeks.org/difference-between-pointer-to-an-array-and-array-of-pointers/
