### ISSUE TITLE
[BUG] compiler directive "annotation_typing=False" ignored

### ISSUE THREAD

**Issue by kannes** [cython/cython#5246]
### Describe the bug

I am struggling with setting the compiler directive `annotation_typing` to `False` successfully and by now it feels like a bug. Unfortunately the mailing list requires a Google account otherwise I would have asked there first.

As we introduced type hints recently but not perfectly we want to disable Cython's `annotation_typing` compiler directive. And since we have quite a few Python files, I would like to do so on a global level, not with a header line in each file.

Our `setup()` call looked like this:

    from distutils.core import setup
    ...
    from Cython.Distutils import build_ext, Extension
    ...
    setup(
      name="foo",
      cmdclass={"build_ext": build_ext},
      ext_modules=[list_of_Extension_objects],
    )

I have a type hint like `def foo(x: list)` and a call with `foo(tuple(...))` which leads to a `TypeError: Argument 'x' has incorrect type (expected list, got tuple` if I run the cythonized code (as it should, if we wanted this strictness).

To disable this I discovered the `annotation_typing` compiler directive on https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html . (While this is not documented in the docs of the stable version, the changelog suggests it does exist in 0.29.33 as well. I also did not encounter any errors about the directive being unknown during my tests.)

But everything I tried did not end up actually properly fixing the `TypeError` being raised:

a) Amending our `Extension` instantiations with it: `Extension(ext, [file_path], cython_directives={"annotation_typing": False})`

b) Changing our `setup(..., ext_modules=...)` to `ext_modules=cythonize(list_of_Extension_objects, compiler_directives={"annotation_typing": False})`

c) Setting it on the `Extension` objects *after* instantiation via `extension.cython_directives = {"annotation_typing": False}`

d) Combinations of the above. Also tried with conflicting True and False settings to see if I could trigger any warning about a mismatch -> Nothing.

e) It probably didn't do anything at all but I got desperate and even tried this... :} ->
```
from Cython.Compiler import Options
Options._directive_defaults["annotation_typing"] = False
```

None of these made the `TypeError` disappear. I did delete the target directory, the build directory each time and also used `setup.py build_ext --force ...`.

Disabling the feature _does_ work if I add a `# cython: annotation_typing=False` header to the Python file(s) but we would really like to avoid this.

### Code to reproduce the behaviour:

See variations above.

### Expected behaviour

No `TypeError` when having conflicts between type hint and passed objects.

### Environment

OS: Ubuntu 22.04
Python version 3.9.5
Cython version 0.29.33

### Additional context

The exception is apparently not raised if using `3.0.0a11` so I could not test if the directive setting got applied in that version.

I am really sorry if this is not a bug. ❤️ I did sent it to cython-users@googlegroups.com but the mail got rejected as I am not registered with a Google account there.

**Comment by 0dminnimda** [comment]
What's interesting is that all of the ways discribed in [source_files_and_compilation](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html?highlight=setup) are outdated as it seems

The way compiler directives are supposed to be set is
```python
from setuptools import Extension, setup
from Cython.Build import cythonize


ext_modules = [
    Extension(...),
]

setup(
    name="...",
    ext_modules=cythonize(
        ext_modules,
        language_level=3,
        annotation_typing=False,
    ),
)
```

**Comment by da-woods** [comment]
Not commenting on the main issue but

> Disabling the feature does work if I add a `# cython: annotation_typing=False` header to the Python file(s) but we would really like to avoid this.

The header has the big advantage that it links the behaviour to the source that requires it. In contrast directives given in a setup.py file are far away from the source code and so not obvious to readers

**Comment by kannes** [comment]
> ```python
> setup(
>     name="...",
>     ext_modules=cythonize(
>         ext_modules,
>         language_level=3,
>         annotation_typing=False,
>     ),
> )
> ```

I will try it tomorrow but is there a canonical source for that? If I read it correctly for the current master https://github.com/cython/cython/blob/1c3a212084744ab52c3e928857a636c312c8f20e/Cython/Build/Dependencies.py#L890 the docstrings says one should pass a "compiler_directives" dict (with the parameters list in the function definition putting that into `**options`).

@da-woods: Thanks! That is a very valid consideration but for our tiny and internal 5 developer team the global setting is more convenient :)

**Comment by da-woods** [comment]
The internal tests all look to do `cythonize(..., compiler_directives=dict(...))` so this is what's tested. See for example:

https://github.com/cython/cython/blob/efdf996dced075682d86b7e53a12b56b5ebfea38/tests/run/language_level.srctree#L13

The following minimal example works for me:

```
# setup.py
from setuptools import setup

from Cython.Distutils import build_ext, Extension
from Cython.Build.Dependencies import cythonize

setup(
  name="foo",
  cmdclass={"build_ext": build_ext},
    ext_modules=cythonize("at.py", compiler_directives={"annotation_typing": False})
    )
```

```
# at.py
def f(x: list):
    return x
```

The only issue I had: when importing `setup` from `distutils` it didn't seem to reliably recompile. Importing it from setuptools works better. So it's possible that you were ending up not actually applying your changes because of this

**Comment by kannes** [comment]
> The only issue I had: when importing `setup` from `distutils` it didn't seem to reliably recompile. Importing it from setuptools works better. So it's possible that you were ending up not actually applying your changes because of this

Wow, this was it. Thank you! I always removed all build artifacts so it's not about re-compilation I think.

Any idea if using `setuptools`' vs `distutils`' `setup` function is documented somewhere? I might have glanced over it in examples but don't recall a warning or similar note.

**Comment by GalaxySnail** [comment]
> Any idea if using `setuptools`' vs `distutils`' `setup` function is documented somewhere? I might have glanced over it in examples but don't recall a warning or similar note.

distutils has been deprecated and will be removed in Python 3.12, it is recommended to use setuptools instead of distutils. Although distutils is included in setuptools, it is considered as an implementation detial.

**Comment by da-woods** [comment]
> Any idea if using `setuptools`' vs `distutils`' `setup` function is documented somewhere? I might have glanced over it in examples but don't recall a warning or similar note.

Apart from the general deprecation, not really. I think we should have updated all the documentation examples to use `setuptools` though. If that isn't the case then let us know (or propose a PR to fix it).

I'll close this issue since I think it's resolved.

**Comment by kannes** [comment]
I checked the docs yesterday and the examples I found all used `setuptools` so I think you are right. Anyone lost will hopefully find this issue via their search engine.

Thank again and sorry if it wasn't an actual bug, your response was super nice and helpful!
