### ISSUE TITLE
[ENH] removing `except -1` syntax for exception propagation 

### ISSUE THREAD

**Issue by mlguruz** [cython/cython#5247]
### Is your feature request related to a problem? Please describe.

First of all, I use Cython for a very large-scale project. Because the project was built over time, initially I was writing lot of functions like 
```
cdef int foo() nogil except -1:
    return something_can_be_minus_1
```
...to propagate exceptions in case function `foo` returns -1.

However, if this `foo` function is wrapped in some other functions, like this:
```
cpdef void bar() except *:
    foo()
    print('here')
```
The behavior seems undefined (?), as no exception will be raised. The program will silently stop at line `foo()` (i.e. won't print anything, and more importantly, the program won't fail either). 

This makes debugging hard and very confusing, especially for people who haven't used Cython for long. 

### Describe the solution you'd like.

I wonder if we could disable this syntax, or make it fail in case `foo` returns -1, or anything that makes it clear instead of a gray area.

**Comment by da-woods** [comment]
No. You're misunderstanding it.

```
cdef int foo() nogil except -1:
    return something_can_be_minus_1
```

You should **never** return `-1` from this function. `-1` is used *by Cython* to indicate that an exception has occurred. If `-1` is also a valid return value then use `except? -1`.

```
cpdef void bar() except *:
    foo()
    print('here')
```

Cython will internally check the return value of `foo` and propagate the exception if it's `-1`. Thus the code will work as intended.

Feel free to suggest improvements to the documentation if you don't feel it explains it well enough.
