### ISSUE TITLE
[BUG] NameError with cpdef enum

### ISSUE THREAD

**Issue by thrasibule** [cython/cython#5269]
### Describe the bug

cpdef enums defined in a pxd file don't work if used as a default value for a class method.

### Code to reproduce the behaviour:

I create a myenum package with the following the below three files:

In enum.pyx:

```cython
cdef class A:
    def __init__(self, MyEnum e=MyEnum.bla):
        if e == MyEnum.bla:
            print("bla")

    # def cmp(self, MyEnum e=MyEnum.bla):
        # if e == MyEnum.bla:
            # print("bla")
```

In enum.pxd:

```cython
# distutils: language = c++
cdef extern from 'enum.hpp':
    cpdef enum class MyEnum:
        bla
        blabla
```

and in enum.hpp:
```cpp
enum class MyEnum {bla, blabla};
```

### Expected behaviour

Code compile and executes fine with the cmp method commented out. But with the cmp method, I get the following error when trying to import A:

```
Cell In[1], line 1
----> 1 from myenum.enum import A

File enum.pyx:6, in init myenum.enum()

File <stringsource>:137, in EnumTypeToPy.__Pyx_Enum_MyEnum_to_py()

NameError: name 'MyEnum' is not defined
```
The issue is the default value in cmp. If e doesn't have a default value then it works as well.

### Environment

OS: Linux
Python version: 3.10.2
Cython version: 3.0.0b1

**Comment by thrasibule** [comment]
Forgot to mention, this was working fine with cython3 alpha11.

**Comment by da-woods** [comment]
There's a specific problem with your example as presented where your module `enum` overrides the standard library `enum` module. I kind of think we should try to fix that too (but not sure how easy that'd be).

I've got a fix for your real issue though (hopefully)

**Comment by thrasibule** [comment]
Thank you! I've tried the patch and I can confirm it fixes the issue.
I also noticed the issue when a cython enum module clashes with the standard library enum, but clearly that's asking for trouble, so didn't bother me at all.
