### ISSUE TITLE
3.0.0b1 generates misnamed `PyMemoryview_Check` function call

### ISSUE THREAD

**Issue by totaam** [cython/cython#5270]
### Describe the bug

Compilation error:
```
error: implicit declaration of function ‘PyMemoryview_Check’; did you mean ‘PyMemoryView_Check’? [-Werror=implicit-function-declaration]
32216 |   __pyx_t_1 = PyMemoryview_Check(__pyx_v_pixels);
      |               ^~~~~~~~~~~~~~~~~~
      |               PyMemoryView_Check
```
As `gcc` suggests, the correct function spelling is `PyMemoryView_Check` with an uppercase `V`.
Manually editing the `.c` file allows the compilation to succeed.

### Code to reproduce the behaviour:

```
  /* "xpra/codecs/nvidia/nvenc/encoder.pyx":2436
 *         if isinstance(pixels, (bytearray, bytes)):
 *             pixels = memoryview(pixels)
 *         if isinstance(pixels, memoryview):             # <<<<<<<<<<<<<<
 *             #copy memoryview to inputBuffer directly:
 *             buf = self.inputBuffer
 */
  __pyx_t_1 = PyMemoryview_Check(__pyx_v_pixels); 
  if (__pyx_t_1) {
```

### Expected behaviour

Compilation should succeed, it did with 3.0.0a11 so this is a recent regression.

### Environment

Reproducible on many different Linux distros.

**Comment by da-woods** [comment]
Thanks. Memory**V**iews are now a "known" builtin type in Cython so they're handled slightly differently.

Just working on fixing this (and another memoryview issue). Should be pretty easy
