### ISSUE TITLE
[BUG] TypeError: C function has wrong signature - 3.0.0b1 regression

### ISSUE THREAD

**Issue by totaam** [cython/cython#5284]
### Describe the bug

Why does it now think that this function's signature has `PY_LONG_LONG` in it instead of `uint64_t`?
```python
from xpra.server.window.motion import ScrollData
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "xpra/server/window/motion.pyx", line 1, in init xpra.server.window.motion
TypeError: C function xpra.buffers.xxh.xxh3 has wrong signature (expected unsigned PY_LONG_LONG (void const *, size_t), got uint64_t (void const *, size_t))
```

### Code to reproduce the behaviour:

A tiny [XXH3 wrapper](https://github.com/Xpra-org/xpra/blob/master/xpra/buffers/xxh.pyx) is `cimport`ed from another module using `from xpra.buffers.xxh cimport xxh3`:
https://github.com/Xpra-org/xpra/blob/e735e6a3bdf17c3299f78948a10fd45f2d8f4c77/xpra/server/window/motion.pyx#L16

### Expected behaviour

This used to work just fine with previous versions, the function can be imported and used without problems.

### Environment

OS: reproduced on Linux, not tested others
Python version 3.10.10
Cython version 3.0.0b1

**Comment by totaam** [comment]
FYI: still an issue with `3.0.0b2`

**Comment by scoder** [comment]
I cannot find any reference to `uint64_t` in your code, so this smells funny. `unsigned PY_LONG_LONG` is reasonable since you've declared the return type as `unsigned long long`. Both are the same.

A wild guess is that this might be related to the exception passing changes. Could you add `noexcept` markers to your exported function and its pxd declaration? Might not resolve the issue, but it seems the right thing to do here in any case.

**Comment by totaam** [comment]
> Could you add noexcept markers to your exported function and its pxd declaration?

That did it!

I'm happy that I have a workaround - but is this the correct behaviour for Cython?
(feel free to close this ticket if it is)

What makes this more of a pain is that I now have to add a patch for older distributions because older versions of Cython now error (including the CI):
```
cdef uint64_t xxh3(const void* input, size_t length) nogil noexcept:
                                                          ^
------------------------------------------------------------

xpra/buffers/xxh.pyx:16:59: Syntax error in C variable declaration
```

> I cannot find any reference to `uint64_t` in your code, so this smells funny.

FWIW: `xxhash` does: `typedef uint64_t XXH64_hash_t;` here:
https://github.com/Xpra-org/xpra/blob/3803f14183e44d0cec197560c86357e234de48ca/xpra/buffers/xxhash.h#L762
And we use it as `uint64_t` here:
https://github.com/Xpra-org/xpra/blob/c2d84256ad3e57a0e73f1f84078ad7bff65f1379/xpra/server/window/motion.pyx#L114-L126

**Comment by scoder** [comment]
> older versions of Cython now error

The `noexcept` declaration was added in Cython 0.29.31/32, released in June 2022. If you make 0.29.32 your minimum version, then it should work also with Cython 0.29. You'll probably need a somewhat recent Cython version anyway in order to support CPython releases like 3.10/3.11.

**Comment by scoder** [comment]
> And we use it as `uint64_t` here:

Then I wonder why your Cython pxd declarations do not reflect that as well.

**Comment by totaam** [comment]
> Then I wonder why your Cython pxd declarations do not reflect that as well.

Well, this is embarrassing.
The pxd didn't match the pyx... all my fault. Sorry!
