### ISSUE TITLE
[ENH] use `@dataclasses.dataclass` to cdef dataclasses (instead of `@cython.dataclasses.dataclass`)

### ISSUE THREAD

**Issue by da-woods** [cython/cython#5292]
### Is your feature request related to a problem? Please describe.

One confusing feature of Cython dataclasses is that you have to cimport `cython.dataclasses.dataclass` and `cython.dataclasses.field` to use them, but all other dataclass-related imports (e.g. `dataclasses.ClassVar` and any runtime dataclass functions you want to access) come from the standard library `dataclasses` module.

There were good reasons for this at the time, but I think it's just a source of confusion to people. Therefore we should probably just take a `@dataclasses.dataclass` decorator on a `cdef` class to mean "Cython dataclass".

(We should also do the same for `total_ordering` while we're at it)

### Describe alternatives you've considered.

I'm slightly uncomfortable with co-opting someone else's module for our own behaviour. This'd especially be a concern if we ever allowed arbitrary decorators on `cdef classes` (in which case people might legitimately want to use the standard library module directly). However that's probably unlikely.

### Additional context

This was discussed before in a comment somewhere which I now can't find...

**Comment by scoder** [comment]
I agree, both for `@dataclasses.dataclass` and `@functools.total_ordering`, when used on a `cdef ` class (and `@cython.cclass`, obviously).

I additionally suggest that putting `@cython.dataclasses.dataclass` on a  Python class should mean both `@cython.cclass` and `@dataclasses.dataclass`, without the need for an additional `@cython.cclass` decorator.
