### ISSUE TITLE
Cython 3.0: is type inference broken for the pow operator ?

### ISSUE THREAD

**Issue by neutrinoceros** [cython/cython#5299]
Trying again to compile yt with Cython 3.0, I'm encountering a handful  of errors similar to this one, rather self-contained, example
```
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      @cython.boundscheck(False)
      @cython.wraparound(False)
      cdef np.int64_t lrot(np.int64_t x, np.int64_t i, np.int64_t width):
          i = i%width
          x = (x<<i) | (x>>width-i)
          return x&(2**width-1)
                  ^
      ------------------------------------------------------------
      
      yt/utilities/lib/geometry_utils.pyx:109:12: Invalid operand types for '&' (int64_t; double)
```

The common denominator between many of these errors seems to be that the inferred type for `2**whatever` always ends up being `double`, no matter the context.
Is this a regression ? If it's intended it's not actually much of a burden to add explicit type casting to our code base (about 15 lines are affected).

**Comment by 0dminnimda** [comment]
As stated in the [Migration guide](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#power-operator)

> Cython 3 has changed the behaviour of the power operator to be more like Python. The consequences are that
> - `a**b` of two ints may return a floating point type,
> - `a**b` of one or more non-complex floating point numbers may return a complex number.

Cython cannot decide here, as `width` can be positive or negative, one returns a whole number while the other returns a floating type
```python
>>> 5**-3
0.008
>>> 5**3
125
```

You can set `width` to `np.uint64_t` to help cython resolve this to a whole number type or revert to old behaviour:

> The old behaviour can be restored by setting the cpow [compiler directive](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives) to True.

**Comment by da-woods** [comment]
Was just too slow to answer, but @0dminnimda is right - this is a deliberate change. Look up `cpow` under the "compiler directive" link for full details.

**Comment by neutrinoceros** [comment]
Oh I missed it in the guide, thank you both !

**Comment by da-woods** [comment]
There's a few places where we make exceptions if people haven't given an explicit `cpow` directive and use the old behaviour (e.g. if you'd done `cdef int xxx = 2**(width-1)` it would have assumed you almost certainly wanted the old behaviour and not gone through an `double`). These are mostly undocumented because I didn't want people to rely on them, but they're just to reduce friction a little.

I'm wondering whether to add "bitwise operators" to that list of exceptions. It's still better to specify the directive of course, but the intent is pretty clear that you want an `int`.

**Comment by 0dminnimda** [comment]
> I'm wondering whether to add "bitwise operators" to that list of exceptions. It's still better to specify the directive of course, but the intent is pretty clear that you want an `int`.

I'd say that `Explicit is better than implicit.`
And if casting the result to whole type will make it use cpow, than no other exceptions are needed
As you know `Special cases aren't special enough to break the rules.`
😉

**Comment by 0dminnimda** [comment]
What I'm trying to say is that I would be surprised to see `3&(5**-3)` return a result and not an error

**Comment by da-woods** [comment]
For the other special-cases for this rule we do emit a warning. So it shouldn't be a huge surprise. But I take your point. I'll have a think about it more.

**Comment by neutrinoceros** [comment]
> Or even better - @cython.cpow(True) decorator

@0dminnimda I just noticed that `cython.cpow` is *new in Cython 3.0*, but it still compiles fine on Cython 0.29, so is this decorator just ignored in older versions of Cython, and is that intended ?

**Comment by da-woods** [comment]
It was added for backwards compatibility. You can only select `cpow(True)` which is just the existing behaviour on 0.29 so doesn't actually do anything.

But it lets the same code compile on 0.29 and 3.0 and run in the same way

**Comment by neutrinoceros** [comment]
awesome, thank you !
