### ISSUE TITLE
[BUG] C++ Constructors do not support type parameters

### ISSUE THREAD

**Issue by rickmark** [cython/cython#5303]
### Describe the bug

Type parameters cannot be specified for C++ class constructor definitions

### Code to reproduce the behaviour:

```cython
cdef cppclass reverse_iterator[Iter]:
    reverse_iterator[U](const U& other)
```

### Expected behaviour

Can define and use template constructors

**Comment by da-woods** [comment]
Duplicate #3198

**Comment by rickmark** [comment]
I think I'll add a documentation note in a PR for this.

The work around is fine, but I think the bug should be left open as it's a parser bug that you have to use the member function style instead of constructor (no return value) style.

**Comment by da-woods** [comment]
I'm just closing it as a duplicate, not claiming it's fixed! I agree it's a bug.

**Comment by rickmark** [comment]
> I'm just closing it as a duplicate, not claiming it's fixed! I agree it's a bug.

So sorry - i thought it was closed as a duplicate of a closed - read it on mobile and missed, I'll work on the doc PR and more context
