### ISSUE TITLE
[BUG] cpdef enum not defined (cython 3.0.0b1)

### ISSUE THREAD

**Issue by mlguruz** [cython/cython#5315]
### Describe the bug

After upgraded to cython 3.0.0b1, several modules using `cdpef enum` broke. 
It compiles, but I cannot import the enum in python **when there's an extension class using that enum in the same file**. 
Please see example below for clear explanation.

### Code to reproduce the behaviour:

Below is an example that fully replicates the problem:

test_cython_enum_bug.pxd:
```
cpdef enum MyEnum:
    A


cdef class MyExtClass:

    cpdef double foo(self, MyEnum ctype = *) except *
```

test_cython_enum_bug.pyx
```
cdef class MyExtClass:

    cpdef double foo(self, MyEnum ctype = MyEnum.A) except *:
        return 1.0
```

Now, after complied, try import either `MyEnum` or `MyExtClass`, you will get Error:

`NameError: name 'MyEnum' is not defined`

### Expected behaviour

This works fine for all previous versions.

### OS

Linux

### Python version

3.8.10

### Cython version

3.0.0b1

### Additional context

This broke part of my production code, so please help...

**Comment by da-woods** [comment]
Duplicate https://github.com/cython/cython/issues/5269

It's a bug so you most likely want to pin to the previous working Cython version
