### ISSUE TITLE
[BUG] Cython 3.0.0b1 not handling -std=c++03

### ISSUE THREAD

**Issue by neutrinoceros** [cython/cython#5316]
### Describe the bug

Making progress on porting yt to Cython 3.0, but I'm still encountering one compilation error where what _seems_ to be happening is that Cython produces C++11-only code despite an explicit directive
`# distutils: extra_compile_args = ['-std=c++03']`

The following errors are outputted
```
yt/utilities/lib/cykdtree/kdtree.cpp:573:81: error: default template arguments may not be used in function templates without ‘-std=c++11’ or ‘-std=gnu++11’
  573 |     template<typename U=T> bool operator==(const __Pyx_FakeReference<U>& other) const { return *ptr == *other.ptr; }
      |                                                                                 ^~~~~
yt/utilities/lib/cykdtree/kdtree.cpp:574:81: error: default template arguments may not be used in function templates without ‘-std=c++11’ or ‘-std=gnu++11’
  574 |     template<typename U=T> bool operator!=(const __Pyx_FakeReference<U>& other) const { return *ptr != *other.ptr; }
```

I have not been able to reproduce this locally, so all I have to show is a failed build on GHA, see
- [context](https://github.com/yt-project/yt/pull/4374#issuecomment-1468208388)
- [failed build](https://github.com/yt-project/yt/actions/runs/4416612698/jobs/7741148482)

This could result from an intentional change (support for C++ older than 11 dropped ...), however I haven't been able to find any mention of it in the migration guide or elsewhere. If the failure is intended, maybe the error message could make it clearer too.

### OS

Linux

### Python version

3.11.2

### Cython version

3.0.0b1

**Comment by scoder** [comment]
> Cython produces C++11-only code despite an explicit directive
> `# distutils: extra_compile_args = ['-std=c++03']`

Note that Cython will generate code for the C++ functionality that you use. The directive above only instructs distutils/setuptools to pass the `-std=c++03` option to the C compiler afterwards. If your code uses C++11 functionality, then the C++ code that you get from Cython will require C++11 and the C++ compiler option will make the C++ compilation fail. That's what seems to be happening here. Maybe you need to pass the option `-std=c++11` instead?

**Comment by neutrinoceros** [comment]
> That said, this looks like something that Cython generates internally. Requiring C++11 unconditionally is definitely unintended and would be a bug on our side.

This was my hunch. The code has been mostly unchanged and compiling fine for 6 years with the `-std=c++03` directive on Cython 0.29.x

We require c++14 for other modules so I can probably get away with requiring C++11 for now.

**Comment by neutrinoceros** [comment]
(FWIW I confirm that the same code builds fine if I use `-std=c++11`)
