### ISSUE TITLE
Using step in range() result in poor performance

### ISSUE THREAD

**Issue by almarklein** [cython/cython#532]
I've noticed that using `range(start, stop, step)` performs much more poorly then `range(start, stop)`, even with `step=1`. This surprised us, since it seems that `range()` should map just fine to a C for-loop, even with a `step` parameter.

cc @JDWarner

**Comment by almarklein** [comment]
> I guess you're referring to this change here: scikit-image/scikit-image@645140c

Yes, moving from duplicating the loop and switching based on whether the step is 1, to an approach based on while loops. I dislike both approaches :)

> So it needs to generate code that determines the step at runtime and allows the loop to run in both directions,

Right. That makes sense. Thanks for the explanation.

Would it be possible to somehow annotate the step as being `>0`? Or to mark the `range` as increasing/decreasing?

**Comment by scoder** [comment]
Consider typing your loop variable as unsigned, and maybe also the step.

**Comment by almarklein** [comment]
Just tried. Unfortunately, it does not help. Would be nice if it did though ;)

**Comment by jakirkham** [comment]
Any ideas where Cython could be improved to handle this better?

**Comment by tscrim** [comment]
I ran across this while working on the downstream SageMath ticket https://trac.sagemath.org/ticket/25633. My workaround was to use the old-style `for` syntax to generate the simple C code.

For the `step` that cannot be determined at compile time (such as an unsigned `int`), perhaps doing `for i in range(start, stop, step)` mapping to
```c
for(i=start, (step > 0 && i < stop) || (step < 0 && i > stop), i+=step)
```
While it is not optimal, the extra comparison tests should be quick (if the C compiler does not optimize them away).

**Comment by jakirkham** [comment]
Yeah, that's more or less the conclusion we came to in issue ( https://github.com/cython/cython/issues/2519 ). I think it's a matter of someone submitting a PR at this point.

**Comment by scoder** [comment]
#1106 has more information by now, so I'm closing this one as a duplicate.
