### ISSUE TITLE
Fatal Python error: PyEval_SaveThread when creating ufunc with nogil [BUG] 

### ISSUE THREAD

**Issue by hiyominato** [cython/cython#5328]
### Describe the bug

I'm generating ufuncs for my fortran library by the new version 3.0.0b1 of cython, using the @cython.ufunc function decorator.
I declare the function as nogil. and call it in python script. It works fine when the input array length is less than 500. When the input array length is greater than 500, it stops and throws a thread error.
```
Fatal Python error: PyEval_SaveThread: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized
```
I'm using the mingw-w64 compiler provided by msys2 on windows, but that doesn't seem to be the cause of the error. I transferred the program to an ubuntu machine and found the same error.

### Code to reproduce the behaviour:

```cython
# test_ufunc.pyx
cimport cython

@cython.ufunc
cdef double add_one(double x) nogil:
    return x+1
```

```python
import test_ufunc
import numpy as np

x=np.linspace(-1,1,501)
x_add=test_ufunc.add_one(x)
print(x_add)
```

### Expected behaviour

No errors, result returns successfully.

### OS

Ubuntu and Windows

### Python version

3.10.6 (Ubuntu), 3.11.2 (Windows)

### Cython version

3.0.0b1

**Comment by da-woods** [comment]
So it looks like I misunderstood ufuncs and the GIL. I'd assumed that it was up to the user to release the GIL in a ufunc (on the basis that they'd documented macros to do so https://numpy.org/doc/stable/reference/c-api/ufunc.html#macros). But it looks like Numpy releases it automatically. It only becomes an issue for large arrays though.

It also looks like I wasn't the only one to find this confusing https://github.com/numpy/numpy/issues/2067.

Should be fairly easy to fix I think.
