### ISSUE TITLE
[BUG] "pure_cdef_class_dataclass" test fails in Py3.12

### ISSUE THREAD

**Issue by scoder** [cython/cython#5346]
### Describe the bug

The `_DataclassParams` class apparently changed its constructor.
```
======================================================================
ERROR: runTest (__main__.CythonRunTestCase.runTest)
[2] compiling (c/cy2) and running pure_cdef_class_dataclass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/run/pure_cdef_class_dataclass.py", line 10, in init pure_cdef_class_dataclass (pure_cdef_class_dataclass.c:8809)
    class MyDataclass:
TypeError: _DataclassParams.__init__() missing 4 required positional arguments: 'match_args', 'kw_only', 'slots', and 'weakref_slot'
```

### Python version

Py3.12a6

### Cython version

3.0.0b2

**Comment by da-woods** [comment]
I think this is (indirectly) my fault - I suggested that they add a bunch of fields that were missing from `_DataclassParams`.

**Comment by da-woods** [comment]
FWIW I have a branch where this is fixed. I hadn't made a PR for it because it was on-top of [another pending PR](https://github.com/cython/cython/pull/4989). But I'll see if I can quickly pick it out.
