### ISSUE TITLE
[BUG] reference leak in for-loop with else:break

### ISSUE THREAD

**Issue by scoder** [cython/cython#5347]
### Describe the bug

If a for-loop's `else:` branch executes a `break` for an outer loop, then we leak the iterable list reference that we create in the optimised list iteration case. Since this is a reference to the iterable, this can leak an arbitrarily large amount of data.

### Code to reproduce the behaviour:

```cython
def for_in_break2(data, avoid):
    """
    >>> for_in_break2([1,2,3,None], avoid=[1,2,3])
    3
    >>> for_in_break2([1,2,3,None], avoid=[1])
    1
    """
    data_iter = iter(data)
    value = None
    while 1:
        match = next(data_iter)
        if match is None:
            break
        for value in avoid:
            if match == value:
                break
        else:
            break  # <--- refleak here

    return value
```

### Cython version

0.29.33 and 3.0.0b2

**Comment by da-woods** [comment]
Is there a reason not to clear these references up at the *start* of the `else` block? I don't think you can actually use the iterable inside the `else` block. That might reduce the number of clean-up paths that needs handling?

**Comment by scoder** [comment]
> Is there a reason not to clear these references up at the _start_ of the `else` block?

Good question. I think, the original reasoning might be that the `else` path is a "normal" exit path and we only intercept on the special (break/continue) paths. The `else` path runs back into the normal loop exit path that does this cleanup in the end.

But you're probably right, we could rearrange the label jumps to do the cleanup first. It seems safe to me, too.

**Comment by scoder** [comment]
The reason why it's not trivial is a `return` in the `else` clause, which cleans up temps itself, independently of the iterator specific cleanup. However, restructuring the code actually makes it both shorter and cleaner (IMHO), especially given the new `label_interceptor`. I'll push another update for 3.0.
