### ISSUE TITLE
[BUG] bytes data corruption when passed to def function

### ISSUE THREAD

**Issue by williamhCode** [cython/cython#5351]
### Describe the bug

When I passed a very large bytes data into a function, the data became corrupted. The data is also corrupted differently everytime. Sometimes due to the way the bytes is corrupted, my programs throws a bus error.

This only happens when I pass the data into a `def` function, not a `cdef` function. I isolated the error making sure it has nothing to do with OpenGL. It also has nothing to do with data conversion between `bytes` and `unsigned char *`. This is because if i simply change `cdef update_data` to `def update_data`, the code breaks.

Context:
```python
# python file

texture_1 = texture.load("imgs/test3.png")
# then I draw the texture
...
```
```cython
# cython file

def load(str filepath, bint resize_nearest=False):
    stbi_set_flip_vertically_on_load(1)

    cdef int width, height, n
    cdef unsigned char *data = stbi_load(filepath.encode(), &width, &height, &n, 4) # load data from image

    # p_data = list(data[200000 * 4:200010 * 4])
    # print(p_data)

    if data == NULL:
        texture = None
        raise RuntimeError(f"Failed to load texture at {filepath}")
    else:
        texture = Texture(width, height, data, resize_nearest, filepath)  # error is here
        # texture.update_data(data)  # uncomment to upload correct data
        stbi_image_free(data)

    return texture


cdef class Texture:

    def __init__(
        self, int width, int height, bytes py_data=None, bint resize_nearest=False
        , str path=None
    ):
        # by this point py_data is already corrupted
...
        cdef unsigned char *data
        if py_data is None:
            data = NULL
        else:
            data = py_data

        # p_data = list(data[200000 * 4:200010 * 4])
        # print(p_data)
...
        glTexImage2D(
            GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, data
        )  # pass data into graphics memory, which is corrupted
...

    cdef update_data(self, unsigned char *data):
        glBindTexture(GL_TEXTURE_2D, self.texture_id)
        glTexSubImage2D(
            GL_TEXTURE_2D, 0, 0, 0, self.width, self.height, GL_RGBA, GL_UNSIGNED_BYTE, data
        )  # update the data, is corrupted depending if this function is cdef or def
...
```
If I don't call `update_data`, or call it and change `cdef update_data` to `def update_data`, my texture draws out like this:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/83525937/229330587-39ce4fe9-7ead-4af2-81cd-493ffc62a6f4.png">

If I call `update_data`, the texture draws properly:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/83525937/229330618-910b2ad5-346c-49a1-b0fd-0f640382912a.png">

I did some further investigation by printing the data, before and after the function, and I can confirm there is a corruption.
This is a result of the print statements if I uncomment them:
```
[255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255, 255, 0, 0, 255]
[108, 101, 0, 95, 95, 108, 111, 111, 112, 48, 95, 49, 55, 55, 95, 114, 117, 108, 101, 0, 95, 95, 103, 97, 116, 104, 101, 114, 95, 49, 55, 56, 95, 114, 117, 108, 101, 0, 95, 95]
```

### Code to reproduce the behaviour:

I honestly do not know the specific circumstances that make this happen, but I'll lay it out so it matches my code.
```cython
# a.pyx

def foo():
    data: bytes = # very large
    Bar(data)

cdef class Bar:
    def __init__(self, bytes data):
        pass
```
```python
import a

a.foo()
```

`data` gets corrupted when passed in the init function

### Expected behaviour

Data shouldn't be corrupted when passed into another function.

### OS

macOS

### Python version

3.11.2

### Cython version

3.0.0b2

### Additional context

This is part of a 2D graphics library I'm working on, so the program can be run if needed in `examples/main.py` [here](https://github.com/williamhCode/cyclone/tree/110bf2421111d5a7a1c0118242439cfa37b696e7).  
Uncomment line 19 in `cyclone/texture.pyx` to get make the bug happen.  
Note: I've only built the project on macOS so I don't know if it works on windows/linux.

**Comment by da-woods** [comment]
The conversion from `unsigned char` to `bytes` assumes a zero-terminated array, which is fine for text strings but almost certainly nonsense for image data.

I think if you do `cdef bytes as_bytes = data[:width*height*4]` this'll copy it into a `bytes` object of correct size, and it'll work.

**Comment by williamhCode** [comment]
@da-woods it works thanks! sorry for all the trouble i really thought i was tripping for this weird bug
