### ISSUE TITLE
[BUG] Error at compilation with `overflowcheck(True)`.

### ISSUE THREAD

**Issue by Ericgig** [cython/cython#5356]
### Describe the bug

I get an error at compilation when using `overflowcheck(True)` with 3.0.0b2.
Prior version worked well.

### Code to reproduce the behaviour:

```cython
%%cython --cplus

cimport cython

@cython.overflowcheck(True)
cdef size_t _mul_checked(size_t a, size_t b) except? -1:
    return a * b

def f(size_t[:] a, size_t[:] b):
    return _mul_checked(a.shape[0], b.shape[0])
```
Output:
```
Content of stderr:
/home/eric/.cache/ipython/cython/_cython_magic_7ec89a75959ed7157c2554d3336a3feedfc6cd9d.cpp:2382:8: error: redefinition of ‘struct __PYX_IS_UNSIGNED_IMPL<T>’
 2382 | struct __PYX_IS_UNSIGNED_IMPL {static const bool value = T(0) < T(-1);};
      |        ^~~~~~~~~~~~~~~~~~~~~~
/home/eric/.cache/ipython/cython/_cython_magic_7ec89a75959ed7157c2554d3336a3feedfc6cd9d.cpp:1329:8: note: previous definition of ‘struct __PYX_IS_UNSIGNED_IMPL<T>’
 1329 | struct __PYX_IS_UNSIGNED_IMPL {static const bool value = T(0) < T(-1);};
      |        ^~~~~~~~~~~~~~~~~~~~~~
```

### OS

Linux

### Python version

3.10.0

### Cython version

3.0.0b2

**Comment by 0dminnimda** [comment]
It seems to be unintational that cython includes util twice
but the easy fix of moving `__PYX_IS_UNSIGNED_IMPL ` into cython module util will help

**Comment by 0dminnimda** [comment]
It seems that msvc does not care about those declarations, probably because they are just duplicates

**Comment by 0dminnimda** [comment]
It seems that msvc does not care about those declarations, probably because they are just duplicates
