### ISSUE TITLE
[BUG] Function pointers in extern structure are not noexcept by default 

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5359]
### Describe the bug

Numpy declares following structure [1]:
```
cdef extern from "numpy/random/bitgen.h":
    struct bitgen:
        void *state
        uint64_t (*next_uint64)(void *st) nogil
        uint32_t (*next_uint32)(void *st) nogil
        double (*next_double)(void *st) nogil
        uint64_t (*next_raw)(void *st) nogil


    ctypedef bitgen bitgen_t
```

All function pointers are declared as `except *` in Cython3.

[1] https://github.com/numpy/numpy/blob/bba99dbd606d173a12c7de1867e2337de17c60e9/numpy/random/__init__.pxd#L4-L12

### Code to reproduce the behaviour:

```cython
from numpy.random cimport bitgen
from libc.stdint cimport uint64_t

cdef uint64_t cb(void *st) nogil:
    return 5

cdef bitgen bg = bitgen(NULL, &cb, NULL, NULL, NULL)

bg.next_uint64(NULL)
```

### Expected behaviour

All function pointers in structure are `noexcept` by default when placed in extern block.

### OS

MacOS

### Python version

3.9.16

### Cython version

master

### Additional context

There is possible performance degradation caused by this bug due following excerpt from documentation:
> There’s a known performance pitfall when combining nogil and except * @cython.exceptval(check=True). In this case Cython must always briefly re-acquire the GIL after a function call to check if an exception has been raised.

> **Note** This bug is affecting migration of scipy to cython3 - see: https://github.com/scipy/scipy/pull/18242/files#r1156507014

### Example 1:
```cython
cdef uint64_t cb(void *st) noexcept nogil:
    return 5

cdef bitgen bg = bitgen(NULL, &cb, NULL, NULL, NULL)

bg.next_uint64(NULL)
```
* Cython 0.29.X - compilation success, code: `(void)(__pyx_v_2np_bg.next_uint64(NULL));`
* master - compilation success, code: `__pyx_v_2np_bg.next_uint64(NULL); if (unlikely(PyErr_Occurred())) __PYX_ERR(1, 9, __pyx_L1_error)`
> **Warning** it seems that cython3 here ignores `noexcept` and generates code as for `except *`

### Example 2:
```cython
cdef uint64_t cb(void *st) nogil:
    return 5

cdef bitgen bg = bitgen(NULL, &cb, NULL, NULL, NULL)

bg.next_uint64(NULL)
```
* Cython 0.29.X - compilation success, code: `(void)(__pyx_v_2np_bg.next_uint64(NULL));`
* master - compilation success, code: `__pyx_v_2np_bg.next_uint64(NULL); if (unlikely(PyErr_Occurred())) __PYX_ERR(1, 9, __pyx_L1_error)`

### Example 3:
```cython
cdef uint64_t cb(void *st) except * nogil:
    return 5

cdef bitgen bg = bitgen(NULL, &cb, NULL, NULL, NULL)

bg.next_uint64(NULL)
```
* Cython 0.29.X - compilation error
* master - compilation success, code: `__pyx_v_2np_bg.next_uint64(NULL); if (unlikely(PyErr_Occurred())) __PYX_ERR(1, 9, __pyx_L1_error)`

**Comment by matusvalo** [comment]
CC @mattip @rgommers @tacaswell

**Comment by scoder** [comment]
Agreed that this contradicts the decision in https://github.com/cython/cython/issues/4280#issuecomment-1100588580
