### ISSUE TITLE
0.29.34 changelog missing from stable documentation

### ISSUE THREAD

**Issue by adang1345** [cython/cython#5364]
### Describe your issue

The documentation page for the stable version of Cython (https://cython.readthedocs.io/en/stable/src/changes.html) is missing the changelog entry for 0.29.34. The most recent changelog entry on this page is 0.29.33. The changelog entry for 0.29.34 can be found  on the documentation page for only the latest version of Cython at https://cython.readthedocs.io/en/latest/src/changes.html.

**Comment by da-woods** [comment]
It looks like the stable documentation is currently failing to build - https://readthedocs.org/projects/cython/builds/19986954/ - we probably just need to disable pdf output (like with did for the master branch)

**Comment by scoder** [comment]
@robertwb, I think you fixed this last time? AFAIK, it needs to be changed in the readthedocs config, not in a repo based config file?

**Comment by scoder** [comment]
Ok, I found the config option myself and disabled it in the readthedocs project. I think we should add a config file to the repo, though, to keep the configuration under VCS.

**Comment by da-woods** [comment]
I think @0dminnimda might have added https://github.com/cython/cython/blob/master/.readthedocs.yaml on the master branch, but not sure that applies to the 0.29.x branch.

I'm staying well clear since it didn't go well last time I tried to fix a problem with the docs ;)

**Comment by 0dminnimda** [comment]
`.readthedocs.yaml` works on a per-branch basis, so for `.readthedocs.yaml` to be applied to 0.29.x, it needs to be backported
