### ISSUE TITLE
[Docs] Document Macros that can be declared by user

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5367]
### Describe your issue

C file generated by Cython contains a lot of defined macros. Some of them are expected to be used by users to finetune compilation process - e.g. `__PYX_EXTERN_C` - https://github.com/cython/cython/pull/5040#discussion_r980296238

I have created a PR for mentioning this macro in documentation #5366. But we are missing separate section in Source Files and Compilation documentation providing list of macros with explanation.

There are two motivation for doing this:
1. to improve documentation (of course)
2. to explicitly define public "API" otherwise we will loose control which macro should be used and which is "internal" (and can be changed anytime)

**Comment by matusvalo** [comment]
Note: I can create a documentation, but I am not 100% sure which macros can be changed/used by users...

**Comment by da-woods** [comment]
Most of the `CYTHON_USE_*` macros can be. Mostly you don't need to (they're set right already) but useful for extra compatibility

`CYTHON_LIMITED_API` can I think.

**Comment by da-woods** [comment]
Probably worth emphasising, most of these really are "advanced options" - the normal use shouldn't have to worry about them (but that doesn't mean they shouldn't be documented, just that we should make it clear most users shouldn't worry)
