### ISSUE TITLE
[BUG] Wrong type inference when variable is shadowed as another type

### ISSUE THREAD

**Issue by metab0t** [cython/cython#5376]
### Describe the bug

When a variable is shadowed by another variable with the same name and different type, the compiler still refers to the old variable.

### Code to reproduce the behaviour:

```cython
import numpy as np
def g(double[:] x):
    x = np.asarray(x, dtype = np.intc)
    cdef int[:] y
    y = x
```
It complains that `Different base types for memoryviews (double, int)`

But the following code compiles.
```cython
import numpy as np
def g(double[:] x):
    z = np.asarray(x, dtype = np.intc)
    cdef int[:] y
    y = z
```

### Expected behaviour

Expect the compiler recognizes the shadowed variable correctly.

### OS

Windows

### Python version

3.10.10

### Cython version

3.0.0.b2

**Comment by scoder** [comment]
In your failing example, you are statically declaring the type of the variable `x` as `double[:]` and then try to assign it to a variable with the static type `int[:]`. This is not valid. In fact, the assignment of the NumPy array to `x` will already fail because it has the wrong dtype for the target variable `x`.

The bug is in your code, not in Cython.

**Comment by da-woods** [comment]
We don't support the concept of "shadowing" a variable

**Comment by scoder** [comment]
It's not so much that "we don't support the concept". Rather, it would run against user expectations if a variable is statically typed and suddenly starts accepting arbitrary other types instead. It rightfully is a compile time error if users accidentally do that. A variable either has a statically defined type or not. Declaring such a static type explicitly opts out of Python's dynamic typing semantics. You can't have both.
