### ISSUE TITLE
getattr(sys, 'frozen', False) not working 

### ISSUE THREAD

**Issue by gaamaaresosa** [cython/cython#5391]
### Describe the bug

I write by code in **Python 3.7.3** and use **Cython > GCC** to compile a binary.
I am using some conditional coding between 
**Development (IDE) mode** or **Executable binary mode.**

For that I use below line of python code.
``` getattr(sys, 'frozen', False) ```

But after building with Cython I see **always it show False as if from IDE mode**.

### Code to reproduce the behaviour:

```cython
if getattr(sys, 'frozen', False):
    # executable
    **print('I AM FROM EXECUTABLE BINARY')**
else:
    # code
    **print('I AM FROM IDE')**
```

### Expected behaviour

When every I run as binary I should see
print('I AM FROM EXECUTABLE BINARY')

### OS

Linux in Raspberry Pi 4 32bit Buster OS

### Python version

Python 3.7.3

### Cython version

Cython version 0.29.34

### Additional context

When ever the binary running I should get
**print('I AM FROM EXECUTABLE BINARY')**

**Comment by scoder** [comment]
You're probably looking for [`cython.compiled`](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#compiled-switch) (but apparently were not looking into the documentation).

**Comment by gaamaaresosa** [comment]
> You're probably looking for [`cython.compiled`](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#compiled-switch) (but apparently were not looking into the documentation).

Yes you are right !
Thank you so much.

```if cython.compiled:
    print("Yep, I'm compiled.")
else:
    print("Just a lowly interpreted script.")```

**Comment by gaamaaresosa** [comment]
> `sys.frozen` is something that PyInstaller

Yes it could be.
Thanks

**Comment by gaamaaresosa** [comment]
> You're probably looking for [`cython.compiled`](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#compiled-switch) (but apparently were not looking into the documentation).



> As far as I can tell `sys.frozen` is something that PyInstaller and maybe cx_freeze do. It doesn't seem to be something that's required, or something that Cython has ever documented that it does.
> 
> Therefore I'm inclined to close as "not a bug".


Please have a look at this site and see PyInstaller setting sys.frozen = True
(PyInstaller/loader/pyiboot01_bootstrap.py:    sys.frozen = True)
To let the developer know its running in binary mode.

What cython is setting to let the user know its running is bunary mode ?
 
'cython.compiled' needs Imprort cython
Which is not easy and additional effor.

 
https://stackoverflow.com/questions/59238237/why-use-getattr-instead-of-hasattr-for-sys-frozen

**Comment by gaamaaresosa** [comment]
@da-woods Thank you so much for your detailed explanation.

>>I definitely don't think it's a bug that it isn't set.

Me too agree its not a bug, may be the developer would have give better solution for this but its not exposed to me yet.

Btw, if you are familar with cython compilation, can you please help me how to add my own import *.py files inside a single cyton compiled exe ?

Some one said Nuitka compiler is as similar as cython, but fully atomatic.
I tried today. Yes fully automatic.
But very huge exe size (7MB) even for 100 lines of single file code.
And I don't think the output file is native machine code exe (Not 100% sure yet).
I got upset still that is using unsafe/unsecure CPython byte code (Not 100% sure yet).

Same code I tried in Cython and the size is just 200K
And the output exe is 100% native machine code.
Secured and safe from reverse engineering (Binary to Source code not possible)

So I plan to make my own python script for Cython compiler.
I don't know how to bundle my own import modules *.py file.
I learned making *.so files from cython. But all are separate .so files.
I need all in one executable binary.

**My python project:**

MainExecutable.py
      | import GeneralFunctions (.py)
      | import Encrypt (.py)
      | import Decrypt (.py)
      | import Settings (.py)
      
I need only single binary **MainExecutable**


Please help me...

**Comment by da-woods** [comment]
Nuitka has put a lot of effort into being able to bundle multiple compiled files and all their dependencies. I believe it is fully compiled, but you'd have to ask them to confirm.
This is not something that Cython supports. It's generally quite a difficult problem and not one that we're interesting in solving.

We also aren't really interested in making a tool to obfuscate people's source code. We're aware that people use it for that (and this is fine... it's open source so use it for what you like). But it isn't a use case that we care about.

Github issues are for feature suggestions and bugs. Please direct ask further support questions on the Cython-user's mailing list https://groups.google.com/g/cython-users - it's possible that some people there may have solutions for some of your problems.

**Comment by gaamaaresosa** [comment]
> it's possible that some people there may have solutions for some of your problems.

Ok thanks again da-woods.
