### ISSUE TITLE
[BUG] ctuple types with object items are not rejected in annotations

### ISSUE THREAD

**Issue by scoder** [cython/cython#5397]
### Describe the bug

Cython allows `x: (int, int)` in annotations but crashes during type analysis.

Also, it seems that ctuple types in annotations do not correctly add the necessary ctuple declaration and utility code to the generated C code. It's not even clear that we want to allow the simple `(t1, t2)` syntax for them in annotations. It's not what Python's typing expects.

### Code to reproduce the behaviour:

Found while testing this:
```cython
def mul((int, int) t, int c):
    x: (int, int, int, int) = t * c
```
In the second line, `int` refers to Python `int`, and this crashes Cython when trying to coerce the Python object item to a Python object type (which shouldn't be tried in the first place). The type of `x` here is the (currently invalid) ctuple type `(Python object, Python object, Python object, Python object)`. We should not allow this type to be created at all, but the check seems to be missing when analysing types in annotations.

### Cython version

3.0.0b2

**Comment by da-woods** [comment]
Semi-related note: in the `tuple[int, int, int, int]` annotation I made it fall back to a plain tuple as soon as it saw a Python type. I suspect that doesn't apply here though

**Comment by scoder** [comment]
I guess I'd be fine with disallowing (or rather warning about) plain tuples in type annotations all together. Given that tuple[...] exists, we don't need to allow them in Python code.
