### ISSUE TITLE
[BUG]  cpdef Enum does not support enums with the same value

### ISSUE THREAD

**Issue by mikelui** [cython/cython#5400]
### Describe the bug

When a cpdef enum is used and has duplicate values, Cython fails to compile the *.pyx file.

For example:

```
cdef enum SomeType:
    BYTE = 1
    UINT8 = 1
    UINT16 = 2
    UINT32 = 3
```

I belive this is because a switch is being used during optimization (maybe here? https://github.com/cython/cython/blob/master/Cython/Utility/CpdefEnums.pyx#L154)

Perhaps a bug with enums here: https://github.com/cython/cython/blob/master/Cython/Compiler/Optimize.py#L1246

### Code to reproduce the behaviour:

```diff
diff --git a/tests/run/switch.pyx b/tests/run/switch.pyx
index dfd734f..a88e679 100644
--- a/tests/run/switch.pyx
+++ b/tests/run/switch.pyx
@@ -333,7 +333,7 @@ def compile_time_tuple_constant(int x):
 
 cdef enum X:
     a = 1
-    b
+    b = 1
     c
     d
     e = 10
```

```
$  python3 runtests.py -vv switch

Compiler output:
switch.cpp:5165:10: error: duplicate case value: '__pyx_e_6switch_a' and '__pyx_e_6switch_b' both equal '1'
    case __pyx_e_6switch_b:
         ^
switch.cpp:5163:10: note: previous case defined here
    case __pyx_e_6switch_a:
         ^
switch.cpp:5356:10: error: duplicate case value: '__pyx_e_6switch_a' and '__pyx_e_6switch_b' both equal '1'
    case __pyx_e_6switch_b:
         ^
switch.cpp:5354:10: note: previous case defined here
    case __pyx_e_6switch_a:
         ^
switch.cpp:5601:10: error: duplicate case value: '__pyx_e_6switch_a' and '__pyx_e_6switch_b' both equal '1'
    case __pyx_e_6switch_b:
         ^
switch.cpp:5599:10: note: previous case defined here
    case __pyx_e_6switch_a:
         ^
3 errors generated.

```

### Expected behaviour

Should be valid and compile. Nothing prevents C or C++ enums from having duplicate values. This breaks existing code during upgrade.

### OS

Linux and macos

### Python version

tested 3.8 and 3.11

### Cython version

3.0.0b2

**Comment by mikelui** [comment]
I'm guessing somewhere in `NameNode` there should be an extra analysis to set a `self.constant_result`

**Comment by da-woods** [comment]
> I'm guessing somewhere in `NameNode` there should be an extra analysis to set a `self.constant_result`

I don't necessarily think that solves it - I don't think Cython knows the values of all enums (specifically extern ones can be opaque to Cython).

I suspect the switch optimization just needs to be more cautious and fail for anything that it doesn't know a constant result for.  It's clearly a general issue, but one that's pretty likely to happen with enums
