### ISSUE TITLE
[BUG] Fused memoryviews returns `ValueError` instead of `TypeError`.

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5401]
### Describe the bug

Fused memoryviews returns `ValueError` instead of `TypeError`.

### Code to reproduce the behaviour:

```cython
cimport numpy as cnp
import cython

ctypedef fused np_numeric_t:
    cnp.int8_t
    cnp.int16_t
    cnp.int32_t
    cnp.int64_t
    cnp.uint8_t
    cnp.uint16_t
    cnp.uint32_t
    cnp.uint64_t
    cnp.float32_t
    cnp.float64_t
    cnp.longdouble_t
    cnp.complex64_t
    cnp.complex128_t

@cython.initializedcheck(False)
def bandwidth_c(np_numeric_t[:, ::1]A):
    return
```

## Cython 3
```python
>>> import numpy as np
>>> zz = np.zeros([5, 5], dtype='M')
>>> import fused
>>> fused.bandwidth_c(zz)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fused.pyx", line 31, in fused.__pyx_fused_cpdef
    @cython.initializedcheck(False)
ValueError: cannot include dtype 'M' in a buffer
```
## Cython 0.29.X:

```python
>>> import numpy as np
>>> zz = np.zeros([5, 5], dtype='M')
>>> import fused
>>> fused.bandwidth_c(zz)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fused.pyx", line 32, in fused.__pyx_fused_cpdef
    def bandwidth_c(np_numeric_t[:, ::1]A):
TypeError: No matching signature found
```

### OS

MacOS

### Python version

3.9.16

### Cython version

master

### Additional context

See discussion in mailing list: https://mail.python.org/pipermail/cython-devel/2023-April/005423.html

**Comment by scoder** [comment]
> As mentioned, the issue can be easily fixed by adding `ValueError` to following

Can it? Does it actually work to catch the exception and continue? Or does it then just fail later?

To me, it looks like NumPy really doesn't support `datetime` (M) or `timedelta` (m) in buffers.

**Comment by scoder** [comment]
To me, the `ValueError` seems a leak of implementation details. A `TypeError` saying that there is no matching signature seems much more appropriate and helpful. I would add the `ValueError` to the list of exceptions that we catch, and make sure that we raise the expected `TypeError` in this case.

**Comment by da-woods** [comment]
> > As mentioned, the issue can be easily fixed by adding `ValueError` to following
> 
> Can it? Does it actually work to catch the exception and continue? Or does it then just fail later?

I think the correct behaviour is to fail later, once it's checked all the different possible fused types. So I think the right thing to do is to catch the `ValueError`, and then proceed to test the next fused type (and raise the `TypeError` at the end if nothing matches).

The Cython fix is worth making whatever you decide to do with Numpy
