### ISSUE TITLE
Strings and Function names shown on Cythonized binary

### ISSUE THREAD

**Issue by gaamaaresosa** [cython/cython#5405]
### Is your feature request related to a problem? Please describe.

I need secured binary wanted to escape from reversing source code.
Found Cython and I love the schema of native binary output.
Really hard to reverse to source code.

But it exposes too much improtant strings on the output binary with 
Detect It Easy or any other tool.
I feel its is more details text than other compilers.
Eg: 
IsRegistered()
License Key
Password
API Keys are easily seen from the built exe.

I know it is possibe to hide the strings on out binary.
Many commercial packers to it like Themida.

Can you please help me how to hide those string ?

Which is the better complier for Cythonized binary ?
GCC or G++ ?

![image](https://user-images.githubusercontent.com/21296884/234323787-8dbdebba-005e-4208-b6bd-db47c20d486f.png)

One can easily patch the binary by going to the address with JE/JNE/JMP/NOPE etc.

https://www.linuxquestions.org/questions/programming-9/gcc-and-why-is-there-strings-in-the-binary-927240/

I expect something like thih should hide the strings.
I tried chr() encoding but compiling and executable becoming slower.

```
compiler:
-Wall -fno-rtti -Os -fdata-sections -ffunction-sections
and
linker:
-Wl,-O,-s,--gc-sections
```

**Comment by da-woods** [comment]
1. Please ask support questions on the [cython-users mailing list](https://groups.google.com/g/cython-users), not on the bug tracker.
2. I don't think we're particularly interesting in building obfuscation of strings into Cython, so you're going to have to do it as a post-processing step on top of the cython-generated C file.
