### ISSUE TITLE
[BUG] Compilation error in cpp mode with python 3.12 caused by `class` C++ keyword in cpython header

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5409]
### Describe your issue

It seems that new function parameter was named as `class` C++ keyword - see https://github.com/python/cpython/pull/103809

This is causing compilation error when used in C++ mode - see the discussion here: https://github.com/scipy/scipy/pull/18242#issuecomment-1526674172

**Comment by encukou** [comment]
The `Include/internal/pycore_code.h` header should only be included in CPython itself, and CPython should be compiled as C.
How is SciPy using it? Is there some function in this internal header that should be made public?

**Comment by tacaswell** [comment]
https://github.com/python/cpython/issues/103978 <- this was fixed upstream.  It may still be a good idea for CYthon to not import private headers, but the compilation errors are resolved.
