### ISSUE TITLE
[BUG] `CythonCImports` shadowing functionality can confuse pickle

### ISSUE THREAD

**Issue by seberg** [cython/cython#5411]
### Describe the bug

Moving over from NumPy https://github.com/numpy/numpy/issues/20167.  On Cython, the `CythonCImports` shadowing module tries to import things that are below it using `__import__` in its `__getattr__`:
```python
    def __getattr__(self, item):
        if item.startswith('__') and item.endswith('__'):
            raise AttributeError(item)
        return __import__(item)
```

### Code to reproduce the behaviour:

```cython
import pickle
import numpy as np

# This adds e.g
# sys.modules['cython.cimports'] = CythonCImports('cython.cimports')
from Cython import Shadow

# This will cause the following to fail:
pickle.dumps(np.add)

# The reason is convoluted, but basically, sometimes pickle will search
# all modules for the attribute.  But this raises a ModuleNotFoundError
getattr(sys.modules["cython.cimports"], "add")
```

### Expected behaviour

Cython should ensure an AttributeError is given.  I suspect the simple fix is to do:
```
    try:
        __import__(item)
    except ModuleNotFoundError:
        raise AttributeError(item) from None
```
or something similar.  I am not quite sure what this code does, so there is probably a much better solution.  But since I suspect this usage is somewhat niche, the above would probably do.

### Cython version

3

### Additional context

I will admit that NumPy is not being nice about not providing `__module__` on the ufunc object and that is an issue, but in the grand scheme of things, I also suspect that others will run into similar issues.

**Comment by mattip** [comment]
I hit this again when trying to use 3.0.0b3 with NumPy.

**Comment by mattip** [comment]
If I put a `pdb.set_trace()` just before the `__import__(name)`, I see it is tripped for the `run/pure_py3` test. It is called as `hasattr(module, x)` (where `x == 'math'`) in  [`importlib/_bootstrap.py::_handle_from_list`](https://github.com/python/cpython/blob/f3909b8bc83675b7ab093dbc558e677558d8e718/Lib/importlib/_bootstrap.py#L1231), which would strengthen the argument that a failure to import should raise an `AttributeError`, not a `ModuleNotFoundError`.
