### ISSUE TITLE
[BUG] Clang15 - constant-logical-operand warning on Cython/C++ wrapper code.

### ISSUE THREAD

**Issue by matttyson** [cython/cython#5418]
### Describe the bug

When compiling my C++/Cython wrapper code with Cython 3, I get the following warning from Clang 15:

`warning: use of logical '&&' with constant operand [-Wconstant-logical-operand]`
`  if (maybe_self_is_right && 0 && !(1)) {`

Clang doesn't like the usage of non boolean constants in if statements.

The below C++ code, compiled on Clang demonstrates the warning

### Code to reproduce the behaviour:

```
int main(int, char *[])
{
   int maybe_foo = 1;
   int maybe_bar = 0;

   if (maybe_foo && 0) {
      return 1;
   }

   if (maybe_foo && maybe_bar) {
      return 1;
   }
   return 0;
}
```

### Expected behaviour

Ideally I'd expect Cython to generate code that compiles without warning.

I don't know enough about Cython to know if

- This type of generated C++ code is expected
- The desired way to fix the warning

If all that is needed is a clang-specific warning suppression I can attempt to write a patch.
If there's another way the warning should be addressed I can attempt to write a patch if the Cython team can provide guidance on the best way to fix it.

### OS

FreeBSD

### Python version

3.9

### Cython version

3.0.0.b2

**Comment by da-woods** [comment]
It probably just needs the `0` put in brackets like the `(1)` is.

Clang likes to complain about everything though, so while we try to reduce the number of warnings, some are pretty much unwinnable

**Comment by matttyson** [comment]
Yeah, it's not hard to make clang upset.

Putting the zero in brackets doesn't help.  The code generator would need to emit `true` or `false` or have the warning suppressed entirely.

**Comment by scoder** [comment]
It might actually be enough to avoid generating dead code here. See https://github.com/cython/cython/pull/5420

**Comment by matttyson** [comment]
Oh cool.  I'll give that patch a try in the next day or so!

**Comment by matttyson** [comment]
Hi,

I've taken a stab at fixing this another way.  I've just replaced the integer types with boolean types. Personally I'm not too concerned about emitting dead code.  The optimizer should clean that up.

Let me know what you think.

**Comment by matttyson** [comment]
Ok, that didn't work. I didn't realize it could also be compiled as C code. I'm using it in C++

**Comment by matttyson** [comment]
Ok, patch updated.  Let me know how you feel about this approach.
