### ISSUE TITLE
[BUG] disallow `except +nogil`

### ISSUE THREAD

**Issue by scoder** [cython/cython#5430]
### Describe the bug

We currently allow `except +nogil` and parse it as `except + nogil` (with space). However, that is different from `except +handlerfunc`. We should require it to be spelled `except + nogil`.

We should also consider rejecting `except +nogil` all together and not parse it as exception handler function. It's an easy source of typos.

### Code to reproduce the behaviour:

```cython
cdef func() except +nogil:
    pass
```

### Cython version

0.29.x and master

**Comment by h-vetinari** [comment]
It's quite unfortunate that the ordering of except vs. nogil now makes the white-space after `except +` semantically relevant. If only to mitigate that, I fully agree that `+nogil` should be forbidden.

I tried chasing down the decision for the ordering, and AFAICT, it was [made](https://github.com/cython/cython/pull/4670#discussion_r854489596) directly in the PR. So, for completeness, a comparison of all possible combinations:

### Current status: first `except` qualifier, then `gil` qualifier
```
noexcept nogil:
noexcept with gil:
except <val> nogil:
except <val> with gil:
except? <val> nogil:
except? <val> with gil:
except * nogil:
except * with gil:
except + nogil:                # only separated from `except +<handler>` (without gil-qualifier) by a single space
except + with gil:
except +* nogil:
except +* with gil:
except +<PyError> nogil:
except +<PyError> with gil:
except +<handler> nogil:
except +<handler> with gil:
```

### Parallel world: first `gil` qualifier, then `except` qualifier

```
nogil noexcept:
nogil except <val>:
nogil except? <val>:
nogil except *:
nogil except +:
nogil except +*:
nogil except +<PyError>:
nogil except +<handler>:
with gil noexcept:
with gil except <val>:
with gil except? <val>:
with gil except *:
with gil except +:
with gil except +*:
with gil except +<PyError>:
with gil except +<handler>:
```

Personally I think the second set looks better, aside from the fact that it does not suffer from any ambiguity or semantically relevant whitespace. But I also guess it's too late to change it now that we're in the beta phase already and projects have started responding to the warnings about the ordering.

**Comment by h-vetinari** [comment]
@scoder @da-woods 
Seeing that this is currently one of the main blockers for 3.0 (cannot deprecate something that 0.29.x cannot even do correctly yet), can we decide how to handle this?

I'm not sure if it's worth the churn to change the order of the gil & except qualifiers to avoid the ambiguities in the first place, but if so 3.0 is the only time to do it (and I guess we could say we're not in rc phase yet). If so (and it's a big if), it should IMO be part of the next beta.

**Comment by da-woods** [comment]
> I'm not sure if it's worth the churn to change the order of the gil & except qualifiers [...]

I'd probably say no. Although with hindsight I might have argued against fixing down the order.

I guess the long-term options are:
* Change `except +nogil` to mean "use an exception handler called nogil".
* Ban `except +nogil` (with a message that says recommends `except + nogil` or a different exception handler name).
* Leave it as is, and maybe issue a stronger warning if we detect a situation where it's genuinely ambiguous (i.e. a C function called `nogil` actually exists). Or just always issue a warning recommending the space.

And in principle the first two of those could be done with a deprecation period for the existing behaviour.

I don't think we should do the first option - too much chance of confusion. I think we should either warn about it or ban it for Cython 3. Don't have a strong opinion which.

**Comment by scoder** [comment]
I've also backported the error to 0.29.35.

**Comment by bjodah** [comment]
Sorry to ping in an old issue. But what is the most robust way to write these declarations?
I've changed the syntax back and forth to please different releases of cython lingering in some various environments, it looks like the most robust way to spell this across multiple version of cython is:

- `nogil except +`

but this seem to trigger a warning?:
 > `The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.`
