### ISSUE TITLE
When a Chinese appears in a .py file, an error is reported for unrecognized characters

### ISSUE THREAD

**Issue by 15286590842** [cython/cython#5439]
### Describe the bug

当.py文件出现中文字符时，py转pyd时会报错无法识别的字符（main.py:10:20: Unrecognized character）

### Code to reproduce the behaviour:

```cython
# example code
```

### OS

win20

### Python version

3.10

**Comment by da-woods** [comment]
This should work on the Cython 3 pre-release (let us know if it doesn't). It won't work on the 0.29.x releases

**Comment by da-woods** [comment]
Duplicate https://github.com/cython/cython/issues/2601

**Comment by 15286590842** [comment]
> 这应该适用于 Cython 3 预发布版（如果不支持，请告诉我们）。它不适用于 0.29.x 版本
Where to download the pre-release version of Cython 3

**Comment by scoder** [comment]
> Where to download the pre-release version of Cython 3

pip install --pre "Cython>=3"
