### ISSUE TITLE
[BUG] Cython uses deprecated cgi module

### ISSUE THREAD

**Issue by JelleZijlstra** [cython/cython#5449]
### Describe the bug

Cython uses the deprecated `cgi` module, which is removed in Python 3.13. (See PEP 594 and python/cpython#104775). However, Cython still uses it in the 0.29.x branch: https://github.com/cython/cython/blob/6ff8a7e7c2730b03a81b7b0932fba17c19dc0c3a/Cython/Tempita/_tempita.py#L36.

This makes Cython unusable on the current CPython main.

### Python version

3.13.0a0

### Cython version

0.29.35

**Comment by da-woods** [comment]
https://github.com/cython/cython/issues/3309 - We already removed this from the master branch (https://github.com/cython/cython/pull/5128).

Practically I think this is just unused vestigial code in Cython (so we can just cherry-pick back the commit that removed it from master). There's a slight concern that this changes the features that Tempita offers on the stable branch of Cython and maybe we should guard it by an `if... except ImportError` block.

I'd just be inclined to remove it though.

**Comment by JelleZijlstra** [comment]
Since this code has already been broken since 3.8 and apparently nobody noticed, removing it is probably safe.

**Comment by scoder** [comment]
Picked into 0.29.x here: https://github.com/cython/cython/commit/54b92e3d4f75225c55609076afd2d901be8326d2

We already had the same discussion in https://github.com/cython/cython/issues/3309, let's just remove that code.

BTW, I rather hope that 0.29.x won't survive the Py3.13 development cycle. Even Cython 3.1 should be on its way by then, and I don't want to maintain three entirely different branches.
