### ISSUE TITLE
[BUG] Tutorial for Numpy uses deprecated (possibly removed?) `np.int`

### ISSUE THREAD

**Issue by da-woods** [cython/cython#5457]
### Describe the bug

https://cython.readthedocs.io/en/latest/src/tutorial/numpy.html - some of the examples use `np.int`. This has been deprecated or removed in Numpy (I'm not quite sure which). Either way we should update it to match the current recommendations.

### Cython version

Both stable and latest documentation

**Comment by da-woods** [comment]
I also wonder if we should `cimport numpy as cnp` to make it clear which bits are coming from the imports and which bits are coming from the pxd. I know it's fine to use the same name for both, but I wonder if it might be less confusing

**Comment by scoder** [comment]
Not sure how easy it'll be to tear both (cimport/import) apart, but it feels better to do that.

I can't say if that makes it more or less confusing for users, though. It might be easier to just always write `np.something` and let Cython see for itself whether that `something` C stuff or Python stuff. But it's definitely not obvious if you do care.
