### ISSUE TITLE
Python 3.12 wheels for Cython 3.0 beta (on PyPI)

### ISSUE THREAD

**Issue by EwoutH** [cython/cython#5467]
### Describe your issue

Currently there are no Python 3.12 (`cp312`) wheels released either on [GitHub](https://github.com/cython/cython/releases) or [PyPI](https://pypi.org/project/Cython/). It would be very useful for these wheels to be build and published, to start early testing for many of the root dependencies in the Python package ecosystem. This could either be done for the existing [3.0.0b3](https://github.com/cython/cython/releases/tag/3.0.0b3) release, or the next one. Especially projects like NumPy could benefit a lot from early Python 3.12 wheels (see also https://github.com/numpy/numpy/pull/23824).

**Comment by scoder** [comment]
These wheels are not needed. All environments that don't have a dedicated wheel use the pure Python wheel instead. We will eventually provide wheels. Currently, they'd only crash due to https://github.com/python/cpython/issues/104614

**Comment by EwoutH** [comment]
Thanks for getting back!

The linked PR was just an example, probably a bad one though. I can remember Cython Python 3.11 wheels being published almost directly after CPython 3.11 hit its beta release. Especially for CI setups it can be quite beneficial to not have to build wheels from scratch.

**Comment by scoder** [comment]
We only provide binary wheels to speed up the Cython *runs* on user side (especially CI setups on Linux). The pip installation always uses a wheel, binary or generic Python, so it's always fast and never builds a wheel locally.

**Comment by scoder** [comment]
Just to be clear: Cython itself does not have to be compiled in order to compile user code with it. It runs just fine as plain Python code, just a little slower. Usually, the user side build times are dominated by the C compiler runs, not by Cython's execution (or installation).

**Comment by EwoutH** [comment]
Thanks for the clarification, I learned something!

Could we keep this issue open until Python 3.12 wheels are released?
