### ISSUE TITLE
[BUG] Broken Links

### ISSUE THREAD

**Issue by BruceEckel** [cython/cython#5473]
### Describe the bug

https://github.com/cython/cython/blob/master/docs/src/userguide/faq.rst (and generated FAQ page) most or all of the links take you to 404 pages.

### Code to reproduce the behaviour:

For example, this link Answer: See [the documentation](https://cython.readthedocs.io/en/latest/src/userguide/auto_pickle). 

Takes you to a 404 page.

### Expected behaviour

A non 404 page

**Comment by da-woods** [comment]
Thanks for pointing it out. Hopefully should be largely fixed now
