### ISSUE TITLE
Cannot assign type 'sighandler_t' to 'void (*)(int) noexcept'

### ISSUE THREAD

**Issue by jwilk** [cython/cython#5498]
Since dee8906fe77cb27ce35b835f1b2dc0093ad92cb3 ("Keep 'extern' visibility in context of struct/union to properly infer 'noexcept' for function pointer fields (GH-5386)"), this code no longer builds:

```cython
#cython: language_level=3

from libc.signal cimport SIG_DFL
from posix.signal cimport sigaction_t

cdef sigaction_t sa
sa.sa_handler = SIG_DFL
```

The error is:
```
sa.pyx:7:16: Cannot assign type 'sighandler_t' to 'void (*)(int) noexcept'
```

Originally reported by @fuzz2ret at <https://github.com/jwilk/python-afl/issues/29>.
Cc: @matusvalo

**Comment by da-woods** [comment]
Thanks - I've just pushed a commit that should fix this
