### ISSUE TITLE
libc.math.isnan seems to be almost useless

### ISSUE THREAD

**Issue by frol** [cython/cython#550]
```cython
from libc.math cimport isnan

cdef extern from "numpy/npy_math.h":
    bint npy_isnan(double x)

import cmath
import numpy

def test_nans():
    cdef float f_nan = numpy.nan
    cdef double d_nan = numpy.nan

    print(isnan(numpy.nan), isnan(f_nan), isnan(d_nan))
    print(npy_isnan(numpy.nan), npy_isnan(f_nan), npy_isnan(d_nan))
    print(numpy.isnan(numpy.nan), numpy.isnan(f_nan), numpy.isnan(d_nan))
    print(cmath.isnan(numpy.nan), cmath.isnan(f_nan), cmath.isnan(d_nan))
```

I expect to see the following output:

```
(True, True, True)
(True, True, True)
(True, True, True)
(True, True, True)
```

, but I get the following:

```
(False, False, False)
(False, False, False)
(True, True, True)
(True, True, True)
```

Am I doing something wrong?

The only way to see `libc.math.isnan` outputs `True` is to pass `libc.math.NAN` into it.

BTW, `cmath.isnan` is ~7 times faster than `numpy.isnan` on a scalar input, and `libc.math.isnan` is even faster especially when I work with raw `float`/`double` data:

```
In []: a = numpy.nan
In []: numpy_isnan = numpy.isnan
In []: cmath_isnan = cmath.isnan
In []: %timeit numpy_isnan(a)
The slowest run took 18.52 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 844 ns per loop
In []: %timeit cmath_isnan(a)
The slowest run took 20.88 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 124 ns per loop
```

I use x86-64 Arch Linux with Python 3.5.2 and Cython 0.24.1.

**Comment by robertwb** [comment]
On Sat, Aug 6, 2016 at 2:17 PM, Vlad Frolov <notifications@github.com> wrote:
>
> from libc.math cimport isnan
>
> cdef extern from "numpy/npy_math.h":
>     bint npy_isnan(double x)
>
> import cmath
> import numpy
>
> def test_nans():
>     cdef float f_nan = numpy.nan
>     cdef double d_nan = numpy.nan
>
>     print(isnan(numpy.nan), isnan(f_nan), isnan(d_nan))
>     print(npy_isnan(numpy.nan), npy_isnan(f_nan), npy_isnan(d_nan))
>     print(numpy.isnan(numpy.nan), numpy.isnan(f_nan), numpy.isnan(d_nan))
>     print(cmath.isnan(numpy.nan), cmath.isnan(f_nan), cmath.isnan(d_nan))
>
> I expect to see the following output:
>
> (True, True, True)
> (True, True, True)
> (True, True, True)
> (True, True, True)
>
> , but I get the following:
>
> (False, False, False)
> (False, False, False)
> (True, True, True)
> (True, True, True)
>
> Am I doing something wrong?

Very strange.  I get all Trues on both OS X and Ubuntu, as expected.
(Cython 0.23 through 0.24.1, both Python 2).

What do you get for

  from libc.math cimport NAN

  import struct, numpy as np
  print struct.pack('d', np.nan).encode('hex')
  print struct.pack('d', float('nan')).encode('hex')
  print struct.pack('d', NAN).encode('hex')

I see '000000000000f87f' for all.

> The only way to see libc.math.isnan outputs True is to pass libc.math.NAN into it.
>
> BTW, cmath.isnan is ~7 times faster than numpy.isnan on a scalar input, and libc.math.isnan is even faster especially when I work with raw float/double data:
>
> In []: a = numpy.nan
> In []: numpy_isnan = numpy.isnan
> In []: cmath_isnan = cmath.isnan
> In []: %timeit numpy_isnan(a)
> The slowest run took 18.52 times longer than the fastest. This could mean that an intermediate result is being cached.
> 1000000 loops, best of 3: 844 ns per loop
> In []: %timeit cmath_isnan(a)
> The slowest run took 20.88 times longer than the fastest. This could mean that an intermediate result is being cached.
> 10000000 loops, best of 3: 124 ns per loop

Using timeit for something so small is grossly distorted due to the
overhead of the timeit loop.

See https://gist.github.com/robertwb/806c3c942fd4825a1272c61bfdc3b470

I'm getting

isnan from math.h: 0.4 ns/call
np_isnan from npy_math.h: 0.5 ns/call
isnan from math (python): 50 ns/call  # overhead is Python function call
isnan from cmath (python): 170 ns/call  # likely converts the input to a complex
isnan from numpy (python): 2000+ ns/call  # dispatch or conversion to array?

**Comment by frol** [comment]
```cython
from libc.math cimport NAN, isnan

import cmath, binascii, struct, numpy as np

cdef extern from "numpy/npy_math.h":
    bint npy_isnan(double x)


def test_nans():
    cdef float f_nan = np.nan
    cdef double d_nan = np.nan

    print(binascii.hexlify(struct.pack('d', np.nan)))
    print(binascii.hexlify(struct.pack('d', float('nan'))))
    print(binascii.hexlify(struct.pack('d', NAN)))

    print(isnan(np.nan), isnan(f_nan), isnan(d_nan))
    print(npy_isnan(np.nan), npy_isnan(f_nan), npy_isnan(d_nan))
    print(np.isnan(np.nan), np.isnan(f_nan), np.isnan(d_nan))
    print(cmath.isnan(np.nan), cmath.isnan(f_nan), cmath.isnan(d_nan))

test_nans()
```

Output:

```
b'000000000000f87f'
b'000000000000f87f'
b'000000000000f87f'
(False, False, False)
(False, False, False)
(True, True, True)
(True, True, True)
```

I have the same output using the following setup:

1. Arch Linux, x86-64, Python 2.7.12 (compiled with GCC 6.1.1), Cython 0.24.1, GCC 6.1.1, Numpy 1.11.1
2. Arch Linux, x86-64, Python 3.5.2 (compiled with GCC 6.1.1), Cython 0.24.1, GCC 6.1.1, Numpy 1.11.1
3. Arch Linux, x86-64, Anaconda Python 3.5.2 (compiled with GCC 4.8.2), Cython 0.24.1, GCC 6.1.1, Numpy 1.11.1

However, running the code on Ubuntu 14.04 with Python 2.7.9 (compiled with GCC 4.9.2) and GCC 4.9.2 indeed produced the expected output! This is weird! Any ideas?

**Comment by robertwb** [comment]
On Thu, Aug 11, 2016 at 12:00 PM, Vlad Frolov <notifications@github.com> wrote:
>
> from libc.math cimport NAN, isnan
>
> import cmath, binascii, struct, numpy as np
>
> cdef extern from "numpy/npy_math.h":
>     bint npy_isnan(double x)
>
>
> def test_nans():
>     cdef float f_nan = np.nan
>     cdef double d_nan = np.nan
>
>     print(binascii.hexlify(struct.pack('d', np.nan)))
>     print(binascii.hexlify(struct.pack('d', float('nan'))))
>     print(binascii.hexlify(struct.pack('d', NAN)))
>
>     print(isnan(np.nan), isnan(f_nan), isnan(d_nan))
>     print(npy_isnan(np.nan), npy_isnan(f_nan), npy_isnan(d_nan))
>     print(np.isnan(np.nan), np.isnan(f_nan), np.isnan(d_nan))
>     print(cmath.isnan(np.nan), cmath.isnan(f_nan), cmath.isnan(d_nan))
>
> test_nans()
>
> Output:
>
> b'000000000000f87f'
> b'000000000000f87f'
> b'000000000000f87f'
> (False, False, False)
> (False, False, False)
> (True, True, True)
> (True, True, True)
>
> I have the same output using the following setup:
>
> Arch Linux, x86-64, Python 2.7.12 (compiled with GCC 6.1.1), Cython 0.24.1, GCC 6.1.1, Numpy 1.11.1
> Arch Linux, x86-64, Python 3.5.2 (compiled with GCC 6.1.1), Cython 0.24.1, GCC 6.1.1, Numpy 1.11.1
> Arch Linux, x86-64, Anaconda Python 3.5.2 (compiled with GCC 4.8.2), Cython 0.24.1, GCC 6.1.1, Numpy 1.11.1
>
> However, running the code on Ubuntu 14.04 with Python 2.7.9 (compiled with GCC 4.9.2) and GCC 4.9.2 indeed produced the expected output! This is weird! Any ideas?

What does a straight C program give using isnan from math.h?

**Comment by frol** [comment]
Oh my, I have just shot myself in the foot by using `-ffast-math` while compiling my Cythonized module. `-ffast-math` disables nan and inf checks: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25975

I'm sorry for this noise.
