### ISSUE TITLE
[BUG] `cython` command prints stdout-type information to stderr

### ISSUE THREAD

**Issue by scoder** [cython/cython#5504]
### Describe the bug

As reported on the mailing list, the `cython` command prints things to stderr that should go to stdout.

### Code to reproduce the behaviour:

```python
>>> from subprocess import run
>>> res = run("cython --version", capture_output=True, shell=True)
>>> err = res.stderr.splitlines()
>>> print(err)
[b'Cython version 0.29.35']
>>> out = res.stdout.splitlines()
>>> print(out)
>>> []
```

### Cython version

0.29.35, probably also master

**Comment by scoder** [comment]
ISTM that 3.0 would be the right time to fix this. Not sure if it's a) important enough to b) still change it at this point.

**Comment by mattip** [comment]
It turns out fixing this broke meson, see scipy/scipy#18865. Two thoughts
- I wonder if CMake will be hit by this as well. 
- cython should add a minimal meson/CMake build project to its CI. I am currently updating the NumPy test to build a c-extension using Cython and the `numpy.random.*.pxd` files, so something along the lines of [this](https://github.com/numpy/numpy/pull/24153/files#diff-e03423ccf31fb23b1233c397aab020881f64d58c3fa5b246dc2f3a612bb0e0e4R63) could also work for cython

**Comment by mattip** [comment]
cc @eli-schwartz, I think meson is going to make a quick-fix release to deal with this.

**Comment by scoder** [comment]
That would be great. But as you also noted in the scipy ticket, it's probably not the only tool that wants to read the version.

**Comment by scoder** [comment]
I pushed a change that writes the version to stderr as well, unless that's a TTY. That way, we won't print it twice, at least, but would still make it available to tools that read from Cython's stderr.

**Comment by da-woods** [comment]
Are we worried that this blocks too many people from testing the release candidate? (i.e. does this justify needing a second release candidate?) Or has Meson successfully worked round it too?

**Comment by eli-schwartz** [comment]
> cc @eli-schwartz, I think meson is going to make a quick-fix release to deal with this.

To clarify, meson is currently running its own release candidate 3 and the final release is expected on Sunday if all goes well.

> Are we worried that this blocks too many people from testing the release candidate? (i.e. does this justify needing a second release candidate?) Or has Meson successfully worked round it too?

When is cython hoping to release the final release?
