### ISSUE TITLE
Bound cpdef method with default argument causes "Cannot assign type"

### ISSUE THREAD

**Issue by jwilk** [cython/cython#551]
For this code:

``` cython
cdef class A:

    cpdef foo(self, str s, float f=0):
        pass

    def bar(self):
        foo = self.foo
        foo('foo', 3.14)
```

I get:

```
Error compiling Cython file:
------------------------------------------------------------
...
    cpdef foo(self, str s, float f=0):
        pass

    def bar(self):
        foo = self.foo
        foo('foo', 3.14)
           ^
------------------------------------------------------------

test.pyx:8:12: Cannot assign type 'str object' to 'A'
```

The problem goes away if I remove `=0`...

Tested with Cython 0.24.1

**Comment by jwilk** [comment]
I bisected this; first bad commit is 767fce81073e7f96c6e9dc95906d96795e61cc32.

**Comment by tobihan** [comment]
Hi! Could someone have a look at this please? In Debian we have the annoying situation that this is a release critical bug, so it prevents new versions of Cython to enter what will be the next Debian release. And we need to update Cython for Sagemath...

**Comment by robertwb** [comment]
Thanks for the bisect. This was certainly an unintended side-effect of that patch. Looking into it.
