### ISSUE TITLE
Mystery casts to `char *`

### ISSUE THREAD

**Issue by da-woods** [cython/cython#5514]
### Describe your issue

We've got a whole load of mystery casts to `(char *)`. For example:

https://github.com/cython/cython/blob/0d0cc9987f1c7e4d757d974be681e0288f0640e9/Cython/Utility/Printing.c#L23

https://github.com/cython/cython/blob/0d0cc9987f1c7e4d757d974be681e0288f0640e9/Cython/Utility/ImportExport.c#L347

(but also loads of other similar places).

I don't really understand these - in most cases the argument type is `const char*` so the cast seems unnecessary, and just serves to generate warnings about casting away a constant. I'd like to remove them, but they've presumably been put there for a reason.

**Comment by scoder** [comment]
My guess is that these C-API functions had no "const" in their argument declaration at some point and thus required non-const arguments - so we cast away the warning. The declaration might have changed at some point, and now we get a warning for casting to non-const on our side.

**Comment by da-woods** [comment]
That sounds plausible. I can find a commit adding `const` to a bunch of them from 2007: https://github.com/python/cpython/commit/f308132cc29eea9b7fe899deb575d29d607a48f4

I'll have a cleanup of these then.
