### ISSUE TITLE
Docs: latest/stable both point to the v3.0.0 docs.

### ISSUE THREAD

**Issue by da-woods** [cython/cython#5535]
Q: Would it still be possible to access the docs for v0.29.x? It seems right now both version toggles (latest/stable) point to the v3.0.0 docs.

_Originally posted by @leofang in https://github.com/cython/cython/issues/4022#issuecomment-1638519660_

**Comment by leofang** [comment]
Thanks, David. To clarify, there's no problem in both latest/stable pointing to v3.0.0, it's correct. What's missing from the version selector is the old docs. We should have at least the last v0.29.x available, because a lot of projects still depend on it.

**Comment by da-woods** [comment]
@scoder is this something you can fix?

**Comment by scoder** [comment]
I set up a link to 0.29.x and removed the "stable" link (because I couldn't find a way to point it somewhere else).

**Comment by leofang** [comment]
Thanks, @scoder @da-woods!
