### ISSUE TITLE
[BUG] NameError: name 'Dict' is not defined

### ISSUE THREAD

**Issue by brettlangdon** [cython/cython#5536]
### Describe the bug

When import `typing` and accessing `typing.Dict` a `NameError` is raised.

This does not occur with `Cython<3`.

### Code to reproduce the behaviour:

```cython
import typing
typing.Dict
```

### Expected behaviour

An exception is not raised.

### OS

macOS, Linux

### Python version

3.10.8

### Cython version

3.0.0

**Comment by da-woods** [comment]
Hmm. I'm fairly sure we test more complicated versions of that so I wonder what's going wrong with the simple version. Thanks for the report

**Comment by brettlangdon** [comment]
The bug occurs for us in a "more complex" scenario, but I was able to reproduce with this simple example.

If it helps to have our actual source of the issue for context: https://github.com/DataDog/dd-trace-py/blob/7f73c55c66fc8201dda021fe2fec2d812feb3d06/ddtrace/profiling/_threading.pyx#L103

**Comment by brettlangdon** [comment]
Definitely seems like it is there, so curious why attribute access doesn't work 🤷🏻‍♂️ 

--- 

```cython
import typing
print(dir(typing))
```

```
[..., 'Dict', ...]
```
---

```cython
import typing
print(getattr(typing, "Dict"))
```

```
typing.Dict
```

**Comment by eli-schwartz** [comment]
I had the same issue with various classes that were defined as `class Foobar(GenericFoo[typing.List[str]])` or similar. Solution seems to mostly work
