### ISSUE TITLE
[BUG] Cython 0.29.30 failing build with pymssql

### ISSUE THREAD

**Issue by GustafFig** [cython/cython#5541]
### Describe the bug

I am trying to build a alpine python 3.7 container with pymssql==2.1.5 and Cython==0.29.30. I have already build this image many times with success, but today (18 july 2023) it start to failed in many machines. I saw equal error in Cython==3.0.0 and even updating cython version the error persist. Someone knows why this older version crash? Have someone passed through this and knows how to solve this problem?

Collecting pymssql                                                                                    
  Downloading pymssql-2.2.7.tar.gz (170 kB)                                                           
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.0/171.0 KB 7.0 MB/s eta 0:00:00                      
  Installing build dependencies: started                                                              
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: pymssql
  Building wheel for pymssql (pyproject.toml): started
  Building wheel for pymssql (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for pymssql (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [119 lines of output]
      setup.py: platform.system() => Linux
      setup.py: platform.architecture() => ('64bit', '')
      setup.py: platform.libc_ver() => ('', '')
      setup.py: include_dirs => []
      setup.py: library_dirs => []
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/pymssql
      copying src/pymssql/__init__.py -> build/lib.linux-x86_64-cpython-37/pymssql
      running build_ext
      warning: src/pymssql/_mssql.pyx:27:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:28:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:29:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:30:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:31:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:32:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:35:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:36:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:38:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:82:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:230:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:264:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:333:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:831:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:919:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:1005:12: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:1379:16: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:1713:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      cdef void init_mssql():
          if dbinit() == FAIL:
              raise MSSQLDriverException("dbinit() failed")
      
          dberrhandle(err_handler)
                      ^
      ------------------------------------------------------------
      
      src/pymssql/_mssql.pyx:2173:16: Cannot assign type 'int (DBPROCESS *, int, int, int, char *, char *) except? -1 nogil' to 'EHANDLEFUNC'
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef void init_mssql():
          if dbinit() == FAIL:
              raise MSSQLDriverException("dbinit() failed")
      
          dberrhandle(err_handler)
          dbmsghandle(msg_handler)
                      ^
      ------------------------------------------------------------
      
      src/pymssql/_mssql.pyx:2174:16: Cannot assign type 'int (DBPROCESS *, DBINT, int, int, char *, char *, char *, LINE_T) except? -1 nogil' to 'MHANDLEFUNC'
      Compiling src/pymssql/_mssql.pyx because it changed.
      [1/1] Cythonizing src/pymssql/_mssql.pyx
      Traceback (most recent call last):
        File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
          metadata_directory)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 417, in build_wheel
          wheel_directory, config_settings)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 340, in <module>
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 181, in build_extensions
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/Cython/Distutils/build_ext.py", line 123, in build_extension
          ext,force=self.force, quiet=self.verbose == 0, **options
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-1e60ghn3/overlay/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/pymssql/_mssql.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymssql
Failed to build pymssql
ERROR: Could not build wheels for pymssql, which is required to install pyproject.toml-based projects
WARNING: You are using pip version 22.0.4; however, version 23.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
failed to solve: process "/bin/sh -c pip install pymssql" did not complete successfully: exit code: 1

### OS

Linux 18.04; Docker alpine3.16

### Python version

3.7.15

### Cython version

0.29.30

**Comment by GustafFig** [comment]
I created this issue because I have only seen the problem to Cython==3.0.0, but resemble it happens on older versions too

**Comment by da-woods** [comment]
This definitely looks like you're actually using Cython 3.0 even if you think you're using 0.29.x. Would it be possible to add a print for the version in setup.py to check?

**Comment by da-woods** [comment]
> Do you say it is Cython 3 because something in the log, or only because the error??

Because of the error.

**Comment by blink1073** [comment]
Relevant post in discourse: https://discuss.python.org/t/no-way-to-pin-build-dependencies/29833/14

**Comment by marcwimmer** [comment]
Wanted to mention, that this happens inside docker of my M1 machine also. 
Not on docker containers on intel machines as it seems.

**Comment by marcwimmer** [comment]
perhaps the with gil / no gil is the problem here - i try a bit 
![Screenshot by Dropbox Capture](https://github.com/cython/cython/assets/10896358/eb162fd7-8b42-4a36-bc16-296265b97453)

**Comment by capkz** [comment]
Just wanted to bump this by saying that I am facing the same issue currently, it is happening to me on Azure Pipelines as well as locally.

**Comment by marcwimmer** [comment]
This also affects intel machines;

What i saw right now:
- pip freeze shows i am using cython 0.29.35

when i install pymssql i just saw that it is downloading the latest cython 3.0.0 version when pip installing the pymssql.

Seems if i can avoid downloading the cython 3.0.0 at install it will work again:
![Screenshot by Dropbox Capture](https://github.com/cython/cython/assets/10896358/24b4c51b-218c-42e5-bf6d-78f649596830)

**Comment by marcwimmer** [comment]
ok by this it works again:
![Screenshot by Dropbox Capture](https://github.com/cython/cython/assets/10896358/a25db79e-b56d-42ee-8f64-278697248450)
Setting pyproject.toml and forcing not to use latest Cython by setting it to the latest best 0.29.35 cython version.

I make a pull request and a branch.

Installing could then work with
pip3 install git+https://github.com/....@branch

When compiling the libs must be present:
![Screenshot by Dropbox Capture](https://github.com/cython/cython/assets/10896358/f4b2ee78-dcc8-4c82-a724-314bfdcb247d)
I will check out installing them on ubuntu based image and see if it also works.

**Comment by marcwimmer** [comment]
In order to compile fully those libs are required on ubuntu:
```
apt-get install libcurl4-openssl-dev zlib1g-dev libkrb5-dev libssl-dev
```

I will now make a pull request to restrict the cython to 0.29.35. I hope the maintainer is merging that very soon, that this is available on pypi.

**Comment by marcwimmer** [comment]
i branched away from 2.2.7 version - now doing pull request. please help me reach the maintainers.

**Comment by capkz** [comment]
I really need this pull request to go through as I depend on the package a lot currently, hopefully it won't take long

**Comment by capkz** [comment]
Thanks a lot @marcwimmer, unfortunately on my way of working I can not install packages like that for security reasons, but I will be on lookout for the pull request to go through!

**Comment by marcwimmer** [comment]
https://github.com/pymssql/pymssql/pull/827
Pull request done - lets call the maintainers somehow :) which timezone are they?

**Comment by capkz** [comment]
A temporary solution until @marcwimmer's solution goes live:
```
echo "Cython==0.29.35" >> constraints.txt
export PIP_CONSTRAINT="$(pwd)/constraints.txt"
```

Thanks @blink1073 for providing that link!

**Comment by GustafFig** [comment]
The conclusion for futher readers,
This is right, the problem is that pymssql take another cython to compile and that version is simply bigger than 0.29.x, so it takes the new release of cython 3.0.0 (@da-woods you were right) and breaks on build. The solution is take the pymssql repo and change the build configuration fixing cython.
I need to do this on an older version of pymssql, so I did a fork and I created a new branch from the tag. But the next version of pymssql would probably be fixed with the @marcwimmer's PR or some other.
Thanks everyone that helped.

**Comment by JarekParal** [comment]
> A temporary solution until @marcwimmer's solution goes live:
> 
> ```
> echo "Cython==0.29.35" >> constraints.txt
> export PIP_CONSTRAINT="$(pwd)/constraints.txt"
> ```
> 
> Thanks @blink1073 for providing that link!

You can also add a link to `constraints.txt` to your `requirements.txt`:
```
--constraint constraints.txt
anyio==3.6.1
...
```

Good thing is that the constraint is applied for dependent packages of packages used in `requirements.txt`
