### ISSUE TITLE
Incompatibility for PyLBFGS 

### ISSUE THREAD

**Issue by iamMohamed** [cython/cython#5551]
### Describe the bug

We are using AWS ECR for our code build it's was worked fine last week but two days before when I tried I faced issue in pip-sync.

Environment : python:3.9.13-alpine3.15

## Error Message

#11 39.93 Collecting pylbfgs==0.2.0.13 (from -r /tmp/tmp0fgk2vts (line 149))
--
706 | #11 39.93   Downloading PyLBFGS-0.2.0.13.tar.gz (105 kB)
707 | #11 39.94      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.2/105.2 kB 32.0 MB/s eta 0:00:00
708 | #11 39.96   Installing build dependencies: started
709 | #11 45.26   Installing build dependencies: finished with status 'done'
710 | #11 45.26   Getting requirements to build wheel: started
711 | #11 46.09   Getting requirements to build wheel: finished with status 'error'
712 | #11 46.10   error: subprocess-exited-with-error
713 | #11 46.10
714 | #11 46.10   × Getting requirements to build wheel did not run successfully.
715 | #11 46.10   │ exit code: 1
716 | #11 46.10   ╰─> [53 lines of output]
717 | #11 46.10       Compiling lbfgs/_lowlevel.pyx because it changed.
718 | #11 46.10       [1/1] Cythonizing lbfgs/_lowlevel.pyx
719 | #11 46.10       /tmp/pip-build-env-as4hcwtd/overlay/lib/python3.9/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-f27krqt1/pylbfgs_148318638f24499e8b809dc14cc168c9/lbfgs/_lowlevel.pyx
720 | #11 46.10         tree = Parsing.p_module(s, pxd, full_module_name)
721 | #11 46.10
722 | #11 46.10       Error compiling Cython file:
723 | #11 46.10       ------------------------------------------------------------
724 | #11 46.10       ...
725 | #11 46.10
726 | #11 46.10               x_a = aligned_copy(x0.ravel())
727 | #11 46.10
728 | #11 46.10               try:
729 | #11 46.10                   callback_data = (f, progress, x0.shape, args)
730 | #11 46.10                   r = lbfgs(n, x_a, fx_final, call_eval,
731 | #11 46.10                                               ^
732 | #11 46.10       ------------------------------------------------------------
733 | #11 46.10
734 | #11 46.10       lbfgs/_lowlevel.pyx:395:40: Cannot assign type 'lbfgsfloatval_t (void *, lbfgsconst_p, lbfgsfloatval_t *, int, lbfgsfloatval_t) except? -1' to 'lbfgs_evaluate_t'
735 | #11 46.10
736 | #11 46.10       Error compiling Cython file:
737 | #11 46.10       ------------------------------------------------------------
738 | #11 46.10       ...
739 | #11 46.10               x_a = aligned_copy(x0.ravel())
740 | #11 46.10
741 | #11 46.10               try:
742 | #11 46.10                   callback_data = (f, progress, x0.shape, args)
743 | #11 46.10                   r = lbfgs(n, x_a, fx_final, call_eval,
744 | #11 46.10                             call_progress, <void *>callback_data, &self.params)
745 | #11 46.10                             ^
746 | #11 46.10       ------------------------------------------------------------
747 | #11 46.10
748 | #11 46.10       lbfgs/_lowlevel.pyx:396:22: Cannot assign type 'int (void *, lbfgsconst_p, lbfgsconst_p, lbfgsfloatval_t, lbfgsfloatval_t, lbfgsfloatval_t, lbfgsfloatval_t, int, int, int) except? -1' to 'lbfgs_progress_t'
749 | #11 46.10       Traceback (most recent call last):
750 | #11 46.10         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
751 | #11 46.10           main()
752 | #11 46.10         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
753 | #11 46.10           json_out['return_val'] = hook(**hook_input['kwargs'])
754 | #11 46.10         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
755 | #11 46.10           return hook(config_settings)
756 | #11 46.10         File "/tmp/pip-build-env-as4hcwtd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
757 | #11 46.10           return self._get_build_requires(config_settings, requirements=['wheel'])
758 | #11 46.10         File "/tmp/pip-build-env-as4hcwtd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
759 | #11 46.10           self.run_setup()
760 | #11 46.10         File "/tmp/pip-build-env-as4hcwtd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
761 | #11 46.10           super(_BuildMetaLegacyBackend,
762 | #11 46.10         File "/tmp/pip-build-env-as4hcwtd/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
763 | #11 46.10           exec(code, locals())
764 | #11 46.10         File "<string>", line 27, in <module>
765 | #11 46.10         File "/tmp/pip-build-env-as4hcwtd/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
766 | #11 46.10           cythonize_one(*args)
767 | #11 46.10         File "/tmp/pip-build-env-as4hcwtd/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
768 | #11 46.10           raise CompileError(None, pyx_file)
769 | #11 46.10       Cython.Compiler.Errors.CompileError: lbfgs/_lowlevel.pyx
770 | #11 46.10       [end of output]
771 | #11 46.10
772 | #11 46.10   note: This error originates from a subprocess, and is likely not a problem with pip.
773 | #11 46.10 error: subprocess-exited-with-error
774 | #11 46.10
775 | #11 46.10 × Getting requirements to build wheel did not run successfully.
776 | #11 46.10 │ exit code: 1
777 | #11 46.10 ╰─> See above for output.
778 | #11 46.10
779 | #11 46.10 note: This error originates from a subprocess, and is likely not a problem with pip.
780 | #11 46.78 Traceback (most recent call last):
781 | #11 46.78   File "/usr/local/bin/pip-sync", line 8, in <module>
782 | #11 46.78     sys.exit(cli())
783 | #11 46.78   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
784 | #11 46.78     return self.main(*args, **kwargs)
785 | #11 46.78   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
786 | #11 46.78     rv = self.invoke(ctx)
787 | #11 46.78   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
788 | #11 46.78     return ctx.invoke(self.callback, **ctx.params)
789 | #11 46.78   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
790 | #11 46.78     return __callback(*args, **kwargs)
791 | #11 46.78   File "/usr/local/lib/python3.9/site-packages/piptools/scripts/sync.py", line 203, in cli
792 | #11 46.78     sync.sync(
793 | #11 46.78   File "/usr/local/lib/python3.9/site-packages/piptools/sync.py", line 263, in sync
794 | #11 46.78     run(  # nosec
795 | #11 46.78   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
796 | #11 46.78     raise CalledProcessError(retcode, process.args,
797 | #11 46.78 subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pip', 'install', '-r', '/tmp/tmp0fgk2vts']' returned non-zero exit status 1.

### OS

image: python:3.9.13-alpine3.15

**Comment by mattip** [comment]
That formatting is horrible, what happened to the indents? In any case the issue is being dealt with in the upstream package, see dedupeio/pylbfgs#38. They will release a hotfix to pin `cython<3.0`, so I think this can be closed here.

**Comment by iamMohamed** [comment]
Hello @mattip 

Thanks for your guidance, My doubt is why Cython 3.0 is not compatible with pylbfgs?

**Comment by da-woods** [comment]
Cython 3.0 isn't compatible because we've changed the default behaviour of cdef functions to be able to propagate exceptions. This means that you can't assign them to a function point where the function pointer expects a function that won't propagate exceptions.

This is by design. We're going to improve the error message a little in the next release I think to give a bit more guidance.

The solution is likely to add `noexcept` to functions that are used as pointers.

I'll post this in the PyLBFGS issue.
