### ISSUE TITLE
[BUG] Cython generates code with double parenthesis tripping -Wparentheses-equality with clang++

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [cython/cython#5584]
### Describe the bug

Cython generates C++ source code that clang++ (and Intel's C++ compiler) emit  `-Wparentheses-equality` warnings.

### Code to reproduce the behaviour:

```cython
# distutils: language = c++
# cython: language_level=3

def foo(char *c_mode):
   cdef str mode = "fortran" if c_mode[0] == b'f' else "c"
   return mode
```

To reproduce:

```
$ cythonize example.pyx
$ icpx $(python3-config --includes) -Wall -Wextra -c parens.cpp
parens.cpp:2110:28: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
  if (((__pyx_v_c_mode[0]) == 'f')) {
       ~~~~~~~~~~~~~~~~~~~~^~~~~~
parens.cpp:2110:28: note: remove extraneous parentheses around the comparison to silence this warning
  if (((__pyx_v_c_mode[0]) == 'f')) {
      ~                    ^     ~
parens.cpp:2110:28: note: use '=' to turn this equality comparison into an assignment
  if (((__pyx_v_c_mode[0]) == 'f')) {
                           ^~
                           =
1 warning generated.
```

This example is distilled from View.MemoryView as shown in comments generated by Cython for my extension
```
  /* "View.MemoryView":270
 * cdef array array_cwrapper(tuple shape, Py_ssize_t itemsize, char *format, char *c_mode, char *buf):
 *     cdef array result
 *     cdef str mode = "fortran" if c_mode[0] == b'f' else "c"  # this often comes from a constant C string.             # <<<<<<<<<<<<<<
 *
 *     if buf is NULL:
 */
  if (((__pyx_v_c_mode[0]) == 'f')) {
    __Pyx_INCREF(__pyx_n_s_fortran);
    __pyx_t_1 = __pyx_n_s_fortran;
  } else {
    __Pyx_INCREF(__pyx_n_s_c);
    __pyx_t_1 = __pyx_n_s_c;
  }
  __pyx_v_mode = ((PyObject*)__pyx_t_1);
  __pyx_t_1 = 0;
```

### Expected behaviour

Ideally, I would like for these double parenthesis to not be thread.

### OS

Linux

### Python version

3.9.12

### Cython version

3.0.0

**Comment by da-woods** [comment]
Duplicate https://github.com/cython/cython/issues/5555

**Comment by da-woods** [comment]
Thanks. I think we would like to fix it if possible, but there's probably some higher priority bugs first. Any PR that addressed it would be welcome of course

**Comment by oleksandr-pavlyk** [comment]
>Any PR that addressed it would be welcome of course.

I am happy to try to work out a fix, but being new to Cython code base, how do I begin to identify the relevant portion of the code to change? Could you please refer me to a document onboarding new developers, I could not find one.

**Comment by da-woods** [comment]
@oleksandr-pavlyk 

The way I'd start is to put a conditional breakpoint in `CCodeWriter.write` in Code.py to match the line of C that you want to change. This is much easier if you don't compile Cython. The fix is likely a few levels up the stack, but that should probably get you pretty close.
