### ISSUE TITLE
[BUG] Integer string conversion limit

### ISSUE THREAD

**Issue by wanfuse123** [cython/cython#5596]
### Describe the bug

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    ext_modules=cythonize("dp.pyx", compiler_directives=compiler_directives),
  File "Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "Cython/Build/Dependencies.py", line 1280, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
  File "Cython/Compiler/Main.py", line 615, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "Cython/Compiler/Main.py", line 539, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "Cython/Compiler/Pipeline.py", line 398, in run_pipeline
    data = run(phase, data)
  File "Cython/Compiler/Pipeline.py", line 375, in run
    return phase(data)
  File "Cython/Compiler/Visitor.py", line 294, in Cython.Compiler.Visitor.VisitorTransform.__call__
  File "Cython/Compiler/Visitor.py", line 190, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "Cython/Compiler/Visitor.py", line 141, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error
  File "Cython/Compiler/Visitor.py", line 109, in Cython.Compiler.Visitor.TreeVisitor.dump_node
ValueError: Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

### Code to reproduce the behaviour:

```cython
# example code
```
cdef large_integer = 10**4301
print(large_integer)

### Expected behaviour

should allow one to overide the python3 new security settings
or provide some work around
working with 
Python 3.10.12
cython (latest from github)
gmpy2

### OS

Linux

### Python version

3.10.12

### Cython version

cython --version Cython version 3.0.0

### Additional context

same issue in a slightly older version of cython

**Comment by da-woods** [comment]
> should allow one to overide the python3 new security settings

That's arguably something that you should be doing (e.g. the `PYTHONINTMAXSTRDIGITS` environmental variable) and we shouldn't be taking the decision for you.

I suspect in a lot of cases we could just write a hex value instead though.

**Comment by scoder** [comment]
Hex values (in strings) are generally a good idea, because they are very efficient to convert to integer digits. Much faster than decimal numbers.

However, this integer value is so large that we cannot store it in any other way in C than a string. We could avoid folding such large calculated values into integers and generate code for the original calculation instead, but I'm not sure if that's so much better. There could still be limits that users may have reduced on their side, so it's still not safe (and always arbitrary) to draw a line.

**Comment by da-woods** [comment]
CPython doesn't limit the length of hex numbers (or anything else with base 2) so hex does solve the problem

**Comment by wanfuse123** [comment]
some applications in pure mathematics requires much larger numbers, is there a way around the issue? gmpy2 easily supports such numbers, and I have worked with even much larger numbers with it.

**Comment by mattip** [comment]
Maybe I don't understand the problem. Python provides [ways around this](https://docs.python.org/3/library/stdtypes.html#int-max-str-digits) via `sys.set_int_max_str_digits()` or the equivalent [`PYTHONINTMAXSTRDIGITS`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONINTMAXSTRDIGITS). Why can't this work for you?
```
export PYTHONINTMAXSTRDIGITS=0
python ...
```

**Comment by wanfuse123** [comment]
I am trying to create a demo— without writing patches for python and still
get reasonable speed.


It will take me six more months to write custom patches, what is wrong with
the override feature? It worked for like, FOREVER…

Gmpy2 allows for arbitrary precision , I am not sure if it can provide a
work around for this issue in a way Cython supports, suggestions are
welcome.

I realize I am pushing the limit of what is doable, but this was within the
limits like a year ago.

Breaking the number up introduces a lot of complexity that I am trying to
avoid, until really top notch programmers can address these difficult task.

That is the whole point of python and Cython, it puts complex coding into
the reach of normal every day programmers for demo’s and prototyping.


Thanks!

**Comment by wanfuse123** [comment]
> Maybe I don't understand the problem. Python provides [ways around this](https://docs.python.org/3/library/stdtypes.html#int-max-str-digits) via `sys.set_int_max_str_digits()` or the equivalent [`PYTHONINTMAXSTRDIGITS`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONINTMAXSTRDIGITS). Why can't this work for you?
> 
> ```
> export PYTHONINTMAXSTRDIGITS=0
> python ...
> ```

yes this is the fix, thank you 
this does not work inside the program
sys.set_int_max_str_digits(5000)

**Comment by wanfuse123** [comment]
is there a way to set it to a certain number of digits rather than just any digits, I assume there is more of a speed issue if it can be any length verses a fixed (large ) number, maybe?

**Comment by wanfuse123** [comment]
Thank you very much for the help!

My program works just need to find a way to speed out up 100x to 1000x.
Parallelization is a huge help but only like 15x to 30x .

I started profiling to find optimizations, but they only will get me
another 3x or so :-(


Regards,


Steven

**Comment by RubTalha** [comment]
https://stackoverflow.com/a/75162528/13086128
