### ISSUE TITLE
[BUG] Unable to run `Cythonize.py`

### ISSUE THREAD

**Issue by aueam** [cython/cython#5646]
### Describe the bug

I tried to run `Cythonize.py` but it failed because of relative imports in file:
```
Traceback (most recent call last):
  File "/tmp/cython/Cython/Build/Cythonize.py", line 10, in <module>
    from .Dependencies import cythonize, extended_iglob
ImportError: attempted relative import with no known parent package
```

### Code to reproduce the behaviour:

```bash
# download repo
cd /tmp/
git clone https://github.com/cython/cython.git

# make file runable
cd /tmp/cython/Cython/Build/
chmod +x Cythonize.py

# run file
./Cythonize.py
```

### Expected behaviour

`Cythonize.py` has the shebang so I expected it to be executable.

### OS

Linux

### Python version

3.10.12

### Cython version

main branch from git

**Comment by scoder** [comment]
Ah, right, thanks. It can probably still be run, but as `python3 -m Cython.Build.Cythonize`. Not sure if that's actually helpful, given that there's the `cythonize` frontend command, but why remove it if it works…
