### ISSUE TITLE
TESTING: what should happen with limited API tests and PyPy?

### ISSUE THREAD

**Issue by mattip** [cython/cython#5659]
### Describe your issue

What should be the approach to limited API testing and PyPy? It does not support the limited API, so any tests that use `-DCYTHON_LIMITED_API=1` (like `tests/run/isolated_limited_api_tests.srctree`) will not work. A few choices:
- add the specific limited-API tests to the `tests/pypy_bugs.txt`. What will happen as more and more tests are converted to use the limited-API?
- undefine `CYTHON_LIMITED_API` for PyPy, then PyPy will run the test as if it does not limit the API
- skip the limited-API-specific tests in the [runtests.py lambda](https://github.com/cython/cython/blob/1cde6233a58538c146a16adcb38496c8e81b0b78/runtests.py#L509) for PyPy.

**Comment by scoder** [comment]
We should add a tag "limitedapi" to the tests specific to that API and exclude all tests with that tag on PyPy (and other Pythons that don't support it).

**Comment by scoder** [comment]
Note also that we're not intending to add a lot of special tests for the Limited API. The one(s?) that we have are rather because we need to test *something* and most things still don't work, so including specific tests is still easier than excluding all but some.

**Comment by da-woods** [comment]
The eventual plan is that the "limited API" test runs should run with `Py_LIMITED_API` defined, and should run as much of the test-suite as possible. And at that point "isolated_limited_api_tests" should go away since it'll be redundant.

There may end up being a few specific limited api tests (for example, the run-time version is no longer the same as the compile-time version which is not necessarily the same as the `Py_LIMITED_API` macro definition, so there's exciting combinations of bugs to be found there)

**Comment by mattip** [comment]
Thanks for the clarifications.

> the "limited API" test runs should run with Py_LIMITED_API defined, and should run as much of the test-suite as possible

Make sense, since the limited-api mode should JustWork. I assume that test run would only be run using CPython.

> There may end up being a few specific limited api tests

Right, and these can continue to use `tag: limited-api`, which would skip them where appropriate.

**Comment by da-woods** [comment]
> I assume that test run would only be run using CPython.

That'd the the plan (unless something else comes along that claims to support it).

The main reason that limited API will end up affecting PyPy is that both tend to use the slow fallback code paths in Cython. So it possibly generates a little bit of churn it those paths. But hopefully the PyPy tests should spot most of those
