### ISSUE TITLE
[BUG] list set item doesn't use PyList_SetItem when wraparound/boundscheck False

### ISSUE THREAD

**Issue by jonathanhogg** [cython/cython#5662]
### Describe the bug

If I disable `boundscheck` and `wraparound`, list gets switch from `__Pyx_GetItemInt_List` to `PyList_GET_ITEM` but list sets stay as `__Pyx_SetItemInt`.

### Code to reproduce the behaviour:

```cython
# cython: language_level=3

import cython

def foo1(list bar not None):
    bar[1] = bar[2]

@cython.wraparound(False)
@cython.boundscheck(False)
def foo2(list bar not None):
    bar[1] = bar[2]
```

### Expected behaviour

The `bar[1] = bar[2]` line in the first function compiles to:

```c
  __pyx_t_1 = __Pyx_GetItemInt_List(__pyx_v_bar, 2, long, 1, __Pyx_PyInt_From_long, 1, 0, 1); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 6, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  if (unlikely((__Pyx_SetItemInt(__pyx_v_bar, 1, __pyx_t_1, long, 1, __Pyx_PyInt_From_long, 1, 0, 1) < 0))) __PYX_ERR(0, 6, __pyx_L1_error)
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
```

and in the second:

```c
  __pyx_t_1 = PyList_GET_ITEM(__pyx_v_bar, 2);
  __Pyx_INCREF(__pyx_t_1);
  if (unlikely((__Pyx_SetItemInt(__pyx_v_bar, 1, __pyx_t_1, long, 1, __Pyx_PyInt_From_long, 1, 0, 0) < 0))) __PYX_ERR(0, 11, __pyx_L1_error)
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
```

I had hoped for something more like:

```c
  __pyx_t_1 = PyList_GET_ITEM(__pyx_v_bar, 2);
  __Pyx_INCREF(__pyx_t_1);

  __Pyx_INCREF(__pyx_t_1);
  __Pyx_GIVEREF(__pyx_t_1);
  PyList_SET_ITEM(__pyx_v_bar, 1, __pyx_t_1);

  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
```

(I may have messed up the reference counting in this – I'm assuming that the code generator would need to add in the INCREF/GIVEREF to make `PyList_SET_ITEM` work.)

### OS

macOS

### Python version

3.11.4

### Cython version

3.0.2

**Comment by jonathanhogg** [comment]
Ah, no, wait.

Having attempted a low-level experiment and actually consulted the API docs, I see that this would have to be `PyList_SetItem` not `PyList_SET_ITEM` or the existing item in the list will not get DECREFed and will leak.

I can explicitly do this:

```cython
# cython: language_level=3

import cython
from cpython cimport PyList_SetItem, Py_INCREF

def foo1(list bar not None):
    bar[1] = bar[2]

@cython.wraparound(False)
@cython.boundscheck(False)
def foo2(list bar not None):
    cdef object tmp = bar[2]
    Py_INCREF(tmp)
    PyList_SetItem(bar, 1, tmp)
```

and the code works as I expected, but feels an order of magnitude more hacky…

**Comment by da-woods** [comment]
I'm not convinced this is a bug.

If we look at the definition `__pyx_SetItemInt`

https://github.com/cython/cython/blob/4df7e67000575b42183735fabbbec5a5bdc01465/Cython/Utility/ObjectHandling.c#L477-L481

It takes `is_list`, `wraparound` and `boundcheck` parameters, so it's designed to account for these settings.

The intention for a lot of these functions in that they're largely inlined in place (so the `wraparound`/`boundscheck` parameters will just allow the C compiler to drop code as needed). With that said `__pyx_SetItemInt_Fast` isn't declared as inline.

I think the idea is that it's easier to hide the things behind macros/functions that have a single interface rather than change the code generation substantially for the different compiler settings.

**Comment by scoder** [comment]
> With that said `__pyx_SetItemInt_Fast` isn't declared as inline.

Yes, it is, exactly to optimise the fast path for lists, and then gradually fall back to less and less efficient code for other data types.

I'm closing this ticket since the resulting binary code will be virtually the same for lists.

**Comment by jonathanhogg** [comment]
Thanks for this. Having just spent the last 15 minutes staring at the assembler output and running microbenchmarks, I can confirm 🙄. I was thrown by the fact that the get is optimised differently.

Gonna go hunt elsewhere for speed-ups…
