### ISSUE TITLE
[BUG] Unreachable code generated for function definitions

### ISSUE THREAD

**Issue by simonbowly** [cython/cython#5681]
### Describe the bug

Cython 3.0.2 generates unreachable code for every function definition.

```
> python setup.py build_ext
Compiling test.pyx because it changed.
[1/1] Cythonizing test.pyx
running build_ext
building 'test' extension
clang -Wsign-compare -Wunreachable-code ...
test.c:2172:3: warning: code will never be executed [-Wunreachable-code]
  goto __pyx_L3_error;
  ^~~~~~~~~~~~~~~~~~~
1 warning generated.
```

### Code to reproduce the behaviour:

Run `python setup.py build_ext` with the following files:

test.pyx:

```cython
# cython: language_level=3
# cython: binding=True

def myfunction(arg):
    return arg
```

setup.py:

```
from setuptools import setup, Extension
from Cython.Build import cythonize

ext_modules = cythonize([
    Extension("test", ["test.pyx"])
])

setup(ext_modules=ext_modules)
```

### Expected behaviour

Expected no compiler warnings. Cython generates the following code:

```
2170   __pyx_L5_argtuple_error:;
2171   __Pyx_RaiseArgtupleInvalid("myfunction", 1, 1, 1, __pyx_nargs); __PYX_ERR(0, 4, __pyx_L3_error)
2172   goto __pyx_L3_error;
2173   __pyx_L3_error:;
```

Line 2172 does seem to be unreachable since `__PYX_ERR` expands an identical `goto` statement.

### OS

macOS

### Python version

3.11.4

### Cython version

3.0.1, 3.0.2

### Additional context

The issue is still there on master. A bisect pointed me to e1d9c5a03af7a7c, and it looks like this is where the unreachable goto is generated:

https://github.com/cython/cython/blob/8d20040844dbff3e8113fe2d7fb96312fd72cb9e/Cython/Compiler/Nodes.py#L3922-L3925

**Comment by da-woods** [comment]
That's a pain. The goto is to shut up another compiler warning. So unless someone can do something clever, you just have a choice of which warning you want to see.

**Comment by scoder** [comment]
I'll try if I can do something.

**Comment by simonbowly** [comment]
Ah I see, the `unused-label` warning that this fixes doesn't come up on that small example, but I see it does occur on a larger codebase if I remove the above goto.
