### ISSUE TITLE
[BUG] Use PyFloat_Pack8 instead of _PyFloat_Pack8 for Python 3.11

### ISSUE THREAD

**Issue by boisgera** [cython/cython#5683]
### Describe the bug

The context: https://github.com/python/cpython/issues/91062 (API change in CPython)

As a consequence, when trying to build [bitstream](https://pypi.org/project/bitstream/) from sources with Cython 3.0.2 and Python 3.11, I get the following warning:

```
src/bitstream.c: In function ‘__pyx_f_9bitstream__write_float64’:
src/bitstream.c:28007:19: warning: implicit declaration of function ‘_PyFloat_Pack8’; did you mean ‘PyFloat_Pack8’? [-Wimplicit-function-declaration]
28007 |       __pyx_t_3 = _PyFloat_Pack8(__pyx_v__float, __pyx_v_pointer, 0); if (unlikely(__pyx_t_3 == ((int)-1))) __PYX_ERR(0, 1586, __pyx_L1_error)
```

which translates into an error at runtime

```
$ python
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitstream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/boisgera/miniconda3/envs/test/lib/python3.11/site-packages/bitstream-3.0-py3.11-linux-x86_64.egg/bitstream.cpython-311-x86_64-linux-gnu.so: undefined symbol: _PyFloat_Pack8
```

### Code to reproduce the behaviour:

With Python 3.11 and Numpy installed

```
$ pip install bitstream
Collecting bitstream
  Using cached bitstream-3.0-cp311-cp311-linux_x86_64.whl
Installing collected packages: bitstream
Successfully installed bitstream-3.0
```

```
$ python
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitstream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/boisgera/miniconda3/envs/test3/lib/python3.11/site-packages/bitstream.cpython-311-x86_64-linux-gnu.so: undefined symbol: _PyFloat_Pack8
```

### Expected behaviour

No `PyFloat_Pack8`-related warning when cythonizing `bitstream`, no runtime error at import time.

### OS

Linux

### Python version

3.11

### Cython version

3.0.2

**Comment by da-woods** [comment]
`_PyFloat_Pack8` doesn't appear in the Cython source code.

I think this might be on you:

https://github.com/boisgera/bitstream/blob/4260cc1298e963c77526df02f849792716667afa/src/bitstream.pyx#L40-L41

https://github.com/boisgera/bitstream/blob/4260cc1298e963c77526df02f849792716667afa/src/bitstream.pyx#L1586

https://github.com/boisgera/bitstream/blob/4260cc1298e963c77526df02f849792716667afa/src/bitstream.pyx#L1591

**Comment by boisgera** [comment]
You're obviously right 😓

Thanks for the quick feedback !
