### ISSUE TITLE
An error occurred when the dll generated by the python code was called with C++.

### ISSUE THREAD

**Issue by huanfzx** [cython/cython#5684]
### Describe your issue

The third-party library opencv-python is used in the python program. First use cython to convert python code to .c code, then use vs2017 to generate dll. an error occurs when C++ calls the dll.  

![5](https://github.com/cython/cython/assets/83294919/8f3dc3c5-c739-4880-8b26-2eedc857600f)

The version of the library and code are shown below.

![0](https://github.com/cython/cython/assets/83294919/288f76e0-3317-4af9-9e92-de645536a913)
![1](https://github.com/cython/cython/assets/83294919/16937af9-1a91-4592-a493-92761a531161)
![2](https://github.com/cython/cython/assets/83294919/641b1137-57ed-4dcc-8ea5-4ce636fb0669)

**Comment by da-woods** [comment]
You need to follow https://cython.readthedocs.io/en/latest/src/tutorial/embedding.html

**Comment by huanfzx** [comment]
I first run the cython .pyx command to get the .h and .c files corresponding to python, and then use VS to package the c file into a dll. At the same time, use the pyinstaller .py command to find out the dependencies required to run the dll. But calling the dll still fails. Am I doing something wrong when rewriting the .pyx file. My own code can run successfully according to the https method, but after being encapsulated into a dll, .py is still required to successfully call the dll, and the .py is exposed to the outside, and the encapsulation seems meaningless. 
I call pyc and dll directly. solved my problem.

**Comment by huanfzx** [comment]
I first run the cython .pyx command to get the .h and .c files corresponding to python, and then use VS to package the c file into a dll. At the same time, use the pyinstaller .py command to find out the dependencies required to run the dll. But calling the dll still fails. Am I doing something wrong when rewriting the .pyx file. My own code can run successfully according to the link(https://cython.readthedocs.io/en/latest/src/tutorial/embedding.html) method, but after being encapsulated into a dll, .py is still required to successfully call the dll, and the .py is exposed to the outside, and the encapsulation seems meaningless.
I call pyc and dll directly. solved my problem.
