### ISSUE TITLE
[BUG] positional only parameter compile error

### ISSUE THREAD

**Issue by hidan98** [cython/cython#5702]
### Describe the bug

When compiling a method that takes positional only parameters using the '/' syntax I get an error " Expected an identifier, found '/'".  I thought this issue was identified in  [#2915](https://github.com/cython/cython/issues/2915#issue-430107277) and fixed in [#2927](https://github.com/cython/cython/pull/2927).

### Code to reproduce the behaviour:

```cython
# example code
def testFunc(a, b, c, /):
    return
```

### Cython version

3.0.2

**Comment by scoder** [comment]
Are you sure that you used Cython 3.0.x to test this? Your example definitely works for me.

**Comment by hidan98** [comment]
Yes I downloaded the source code version 3.0.2, 3.0.1 and 3.0.0 and ran bin/cython myfile.py and got the same result.

**Comment by hidan98** [comment]
> Are you sure that you used Cython 3.0.x to test this? Your example definitely works for me.

Yes I downloaded the source code version 3.0.2, 3.0.1 and 3.0.0 and ran bin/cython myfile.py and got the same result.

**Comment by scoder** [comment]
What does `bin/cython -V` give you?

**Comment by da-woods** [comment]
I also tried this and failed to reproduce the error.

**Comment by hidan98** [comment]
Ah you were correct, I was picking the wrong version up.
