### ISSUE TITLE
[ENH] Have @cython.overflow skip arithmetic on overflow

### ISSUE THREAD

**Issue by WillAyd** [cython/cython#5705]
### Is your feature request related to a problem? Please describe.

When using @cython.overflowcheck with tools like UBSAN you end up with failures because the arithmetic still is performed, giving you undefined results until the OverflowError gets raised

### Describe the solution you'd like.

As far as I can tell Cython generates this code for multiplication overflow checking:

```c
static CYTHON_INLINE int __Pyx_mul_const_int_checking_overflow(int a, int b, int *overflow) {
    if (b > 1) {
        *overflow |= a > __PYX_MAX(int) / b;
        *overflow |= a < __PYX_MIN(int) / b;
    } else if (b == -1) {
        *overflow |= a == __PYX_MIN(int);
    } else if (b < -1) {
        *overflow |= a > __PYX_MIN(int) / b;
        *overflow |= a < __PYX_MAX(int) / b;
    }
    return a * b;
}
```

Since the results of the multiplication are undefined I am guessing we could return almost anything here? Alternately we could give users a `@cython.overflowcheck.return_value()` decorator that specifies what value they would like back in such instances, or maybe even a new `@cython.overflowcheck.fail_fast()` decorator where the user can still choose to continue with the multiplication or not

### Describe alternatives you've considered.

When using UBSAN you could also work with a suppression file, but I think that is harder for users to set up and properly maintain

**Comment by da-woods** [comment]
I definitely don't think it's worth adding additional compilation options. The skipping the check part sounds reasonable to me

**Comment by WillAyd** [comment]
When you say skipping the check do you mean skipping the arithmetic?

**Comment by da-woods** [comment]
> When you say skipping the check do you mean skipping the arithmetic?

Yes - that's what I mean. Sorry for being a bit vague.

**Comment by WillAyd** [comment]
Actually I think this _does_ already work this way, at least on platforms that have the overflow builtins looks like it is leveraging those. So probably nothing else for Cython to do - just have to wait for more compilers to support those
