### ISSUE TITLE
[BUG] Relative cimport from package without `__init__.pxd` fails

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5715]
### Describe the bug

Relative cimport from package without `__init__.pxd` fails - see example below (adding `b/__init__.pxd` will fix the compilation issue):

```
$ cython -3 a.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from .b cimport aa
^
------------------------------------------------------------

a.pyx:1:0: 't/b.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from .b cimport aa

cdef aa.ulong a = 5
     ^
------------------------------------------------------------

a.pyx:3:5: 'aa' is not declared
```

### Code to reproduce the behaviour:

```
######## __init__.py ########

######## a.pyx ########
from .b cimport aa
cdef aa.ulong a = 5

######## b/__init__.py ########

######## b/aa.pxd ########
ctypedef long int ulong
```

### Expected behaviour

The example is compiled successfuly even without `b/__init__.pxd`

### OS

any

### Python version

any

### Cython version

3.0.1, 3.0.2, master

### Additional context

Affecting: https://github.com/MagicStack/uvloop/pull/534
Possible introduced by: #5538

**Comment by scoder** [comment]
Oh, yes, that seems a serious regression. Targeting for 3.0.3 to make sure we keep it in sight.

**Comment by matusvalo** [comment]
Yes it is caused by following lines introduced in #5538:
https://github.com/cython/cython/blob/9827c6085e2141db71c55ae231a4a09a878dd524/Cython/Compiler/Main.py#L222-L224

Feel free to revert #5538 if needed.
