### ISSUE TITLE
[BUG] Traceback reference leak in CPython 3.12.0a6 and above

### ISSUE THREAD

**Issue by yut23** [cython/cython#5724]
### Describe the bug

In CPython 3.12.0a6 and newer with `CYTHON_FAST_THREAD_STATE=1`, traceback objects for Python code called from Cython have their refcounts incremented but never decremented. This is triggered when Cython code calls into a Python function that then raises an exception. The source of the leak is `__Pyx_ErrRestoreInState()`, which never calls `Py_XDECREF` on `tb`: https://github.com/cython/cython/blob/9827c6085e2141db71c55ae231a4a09a878dd524/Cython/Utility/Exceptions.c#L178-L193

### Code to reproduce the behaviour:

lib.pyx:
```cython
def get_spam(data):
    # this will raise a KeyError in the Python code for UserDict.__getitem__()
    return data["spam"]
```
repro.py:
```python
from collections import UserDict
from lib import get_spam

def main():
    d = UserDict()
    d["lots of data"] = bytearray(1024**2)
    try:
        get_spam(d)
    except KeyError:
        pass

for i in range(10):
    main()
```
I've uploaded a full reproducer to https://github.com/yut23/cython_3.12_traceback_leak, along with some code I used to track down the leaks.

### OS

Linux, macOS

### Python version

3.12.0a6+

### Cython version

3.0.0+

### Additional context

We first encountered this when running yt's test suite on Python 3.12, and reported it to CPython in https://github.com/python/cpython/issues/109602. Thanks to @neutrinoceros, @Xarthisius, and @mdboom for their work in simplifying the reproducer!

I'll make a PR with a proposed fix shortly.

**Comment by ThomasWaldmann** [comment]
@scoder Does this issue also apply to Cython 0.29.x and if so, was a fix already released (could not find it in changelog)?

**Comment by scoder** [comment]
The issue milestone says 3.0.3, so the fix was (probably) not backported. Looks more like a 3.0.x issue to me. There were a lot of changes in the exception handling code since 0.29.x. It doesn't look like 0.29.x has any special casing code for Py3.12 here.
