### ISSUE TITLE
[BUG] Incorrect return type from np.sum in Cython 3

### ISSUE THREAD

**Issue by matthew-brett** [cython/cython#5727]
### Describe the bug

We have Cython code equivalent to the following:

```cython
def summer():
    cdef:
        cnp.npy_intp c = 0

    mask = np.zeros(3, dtype=np.uint8)
    c += mask.sum()
    return c
```

When run, the generated file gives:

```
sum_uint8.pyx:9: in sum_uint8.summer
    c += mask.sum()
E   TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

The return type from the sum operation in Python is:

```
[ins] In [3]: type(np.zeros(3, dtype=np.uint8).sum())
Out[3]: numpy.uint64
```

I only get this error for current `main` and Cython 3, not Cython < 3.

I do not get the error when the type of `c` is `np_uint64` or `np_int`.

### Code to reproduce the behaviour:

```
git clone https://github.com/matthew-brett/mincy
cd mincy
pip install -r requirements.txt
make
```

### Expected behaviour

No error, as output type from sum operation should be interpretable as an integer.

### OS

macOS

### Python version

3.11.5

### Cython version

Commit 2f3236d49

**Comment by da-woods** [comment]
Cython's behaviour hasn't actually changed between 3.0 and 0.29.x. What's changed is the definition of `npy_intp`.

In 0.29.x:

```
cdef extern from "Python.h":
    ctypedef int Py_intptr_t

cdef extern from "numpy/arrayobject.h":
    ctypedef Py_intptr_t npy_intp
```

and in master

```
cdef extern from "Python.h":
    ctypedef Py_ssize_t Py_intptr_t

cdef extern from "numpy/arrayobject.h":
    ctypedef Py_intptr_t npy_intp
```

Note that in master the Numpy pxd file will end up coming from Numpy itself, not us. Cython no longer maintains it.

Running the code in Python:

```
>>> a = no.zeros(3, dtype=no.uint8)
>>> x = 0
>>> x += a.sum()
>>> x
0.0
```

Note that it returns a floating point number. Again, not a Cython decision.

Internally Cython converts `c` to a Python `int`, adds that to `a.sum()` and then converts back and assigns it to `c`.

The difference is in the conversion back. The difference between `Py_ssize_t` and a C `int` from Cython's point of view is that Cython uses a stricter conversion for `Py_ssize_t` and only accepts values where `PyNumber_Index` is valid (which evidently doesn't include floating point numbers). In contrast, with a C `int` Cython calls `PyNumber_Long` which is less strict and will convert `0.0`.

I suspect the special-casing of `Py_ssize_t` to be a strict index is something we don't want to change at this stage. And `ctypedef` of `np_intp` is now outside our control.

**Comment by matthew-brett** [comment]
Thanks - sorry - was travelling - and only got back to think about this now.

So, to check I understand, in Cython 2, `npy_intp` resolves to `int`, but in Cython 3, it resolves to `Py_ssize_t`.   This results in stricter conversion checks, hence the error.  The change in resolution to give `Py_ssize_t` was intended.

I did check return return type of `a.sum()` in Numpy before posting, and now I check again, I still get:

```python
[ins] In [1]: import numpy as np

[ins] In [2]: a = np.zeros(3, dtype=np.uint8)

[ins] In [3]: a.sum()
Out[3]: 0
```

Am I running a different Numpy from you?   I tried on 1.25.2 and 1.26.0.

**Comment by da-woods** [comment]
> I did check return return type of a.sum() in Numpy before posting, and now I check again, I still get: [...]

Sorry - don't think I was completely clear with that part. For the result of `a.sum()` I get `np.uint64` (like you do).

When I add a Python `int` that that `np.uint64` I get `np.float64`. It's this `float64` that fails to convert back to `Py_ssize_t`.

> So, to check I understand, in Cython 2, npy_intp resolves to int, but in Cython 3, it resolves to Py_ssize_t. This results in stricter conversion checks, hence the error. The change in resolution to give Py_ssize_t was intended.

Yes - with one complication: Numpy now provides the files that are used with `cimport cython`. It actually provides two version (one for [Cython 0.29.x](https://github.com/numpy/numpy/blob/main/numpy/__init__.pxd) and one for [Cython 3](https://github.com/numpy/numpy/blob/main/numpy/__init__.cython-30.pxd)) - these have slightly different definitions. To further complicate things we haven't yet deleted this file from Cython. At least for Cython 3 the version provided by Numpy should be preferred but I'm not sure what happens for older version of Cython. It doesn't matter in terms of this issue though

**Comment by matthew-brett** [comment]
Ah - thank you - that's a very helpful clarification - sorry for missing your well-placed `x +=` before.
