### ISSUE TITLE
[ENH] Support `const` and `volatile` in Pure Python Mode

### ISSUE THREAD

**Issue by scoder** [cython/cython#5728]
### Is your feature request related to a problem? Please describe.

In my Python code, I would like to do the equivalent of
```cython
cdef const int x = 0
cdef const int[:] mv
```

### Describe the solution you'd like.

```cython
x: cython.const(cython.int) = 0
x: cython.volatile(cython.int) = 0
mv: cython.const(cython.int)[:]
```

However, this is invalid annotation syntax since [calls are not allowed](https://typing.readthedocs.io/en/latest/spec/annotations.html#type-and-annotation-expressions) there.

### Describe alternatives you've considered.

```cython
x: cython.const[cython.int] = 0  # possibly a bit too overloaded by now
mv: cython.const[int[:]]  # probably difficult to remember if it's that or cython.const[int][:]
x: cython.int[cython.const] = 0  # difficult to distinguish from (and to mix with) memory views
x: cython.int(cython.const) = 0  # we don't have anything like this yet

with cython.const:  # doesn't work for function arguments
    x: cython.int = 0
```

The [`Annotate[]` typing syntax](https://typing.readthedocs.io/en/latest/spec/qualifiers.html#annotated) is fairly verbose and only available in Python 3.9 and later:

```cython
from typing import Annotated
x: Annotated[cython.int, cython.const] = 0
y: Annotated[cython.int, cython.volatile] = 1
z: Annotated[cython.int[:], cython.const] = 1
```
For memory views, it's not obvious whether `Annotated[cython.int[:], cython.const]` really means the commonly used `(const int)[:]` or `const (int[:])` (as it's written). In general, `Annotated[]` is less suitable for any annotations e.g. on struct fields or any other structured usage.

### Additional context

There's the general problem with memory views that we'll add two levels of declarations, `const()` and `[:]`, which should better be used in a specific order. It's a difference whether you write `cython.const(cython.int)[:]` or `cython.const(cython.int[:])` (in the latter case, the variable cannot be modified, in the first, it's only the items of the memory view).

We could argue that `const (int[:])` isn't very useful in comparison to `(const int)[:]` and live without a Python expression for the first. In fact, Cython already transforms `const int[:]` into `(const int)[:]` internally, for this very reason.

However, transforming the "obvious" expression `const[int[:]]` into `const[int][:]` automatically means that we cannot support `const (int[:])` in the future any more.

**Comment by matusvalo** [comment]
> Describe alternatives you've considered.

I propose to use approach from python stdlib `typing` module [1]:

```python
x: Annotated[cython.int, cython.const] = 0
y: Annotated[cython.int, cython.volatile] = 1
```

It is used for instance in popular fastapi framework [2].

[1] https://docs.python.org/3/library/typing.html#typing.Annotated
[2] https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#add-query-to-annotated-in-the-q-parameter

**Comment by jpe** [comment]
I've run into this when trying to use type hints instead of cython.locals() / cython.declare() -- I want to declare a variable as const char * but there doesn't seem to be any way to using type hints. I'm reverting back to cython.locals() / cython.declare() for now.

**Comment by scoder** [comment]
> ```python
> x: Annotated[cython.int, cython.const] = 0
> ```

I'm not so sure. This is even more verbose and feels less easy to integrate with typedefs. It's also not clear how to reproduce the difference between `(const int)[:]` and `const (int[:])` with this syntax.

**Comment by scoder** [comment]
It turns out that [call syntax is not allowed](https://typing.readthedocs.io/en/latest/spec/annotations.html#type-and-annotation-expressions) inside of type annotations. This makes `cython.const(cython.int)` invalid syntax.

**Comment by scoder** [comment]
I think the best of the bad solutions here is `const[]` as in `const[int]`.

The drawbacks of `cython.int[const]` seem worse, requiring us to open up something as simple as `cython.int` for further nested bracket annotations. Even if we restricted that to only Cython types (e.g. not allow it for Python `int` etc.), it still seems a large opportunity for invalid syntax usage. Is it `int[const][:]` or `int[const, :]` or `int[:][const]` or what else?

Regarding memory views, `const[int][:]` seems ok-ish, though not great. We should consider explicitly disallowing `const[int[:]]` for now, as that's usually not what users want but would obstruct future semantics.

**Comment by da-woods** [comment]
Can we make a definition of `cython.const`  such that mypy (and similar) are happy for code like

```
a: cython.const[cython.int] = 1
```

since I think what a lot of people want is to write type annotations that Cython can use but which also pass their static type checkers.

(We've already missed here with our typed memoryview syntax though, but maybe it'd be good to make sure future additions meet this.)

I'm definitely not an expert in the Python-typing ecosystem though, and I remain generally suspicious of it. So I really can't make an informed comment on whether either `const[int]` or `int[const]` meets that criteria. I suspect `Annotated[int, const]` does, but I agree with all the other criticism of it.

**Comment by da-woods** [comment]
> Looks like it can be done with Annotated without too much verbosity -- see the bottom of https://typing.readthedocs.io/en/latest/spec/qualifiers.html

That's potentially useful. I'm not sure the type alias syntax is something that would be easy for Cython to support, but it'd work as definition of `cython.const` for external users

**Comment by scoder** [comment]
> type alias

[`TypeAlias`](https://docs.python.org/3/library/typing.html#typing.TypeAlias) was only added in Python 3.10, and is already deprecated in Python 3.12 in favour of a new statement, called `type`. So I guess we can only use it in `Shadow.pyi` and not in `Shadow.py`. It's an alias, so probably needs a different name from the `Annotated[]` argument, which is annoying.

I'll try something out.

**Comment by scoder** [comment]
What do you think of https://github.com/cython/cython/pull/6398 ?

**Comment by TeamSpen210** [comment]
Where it can be used, it might be good to support `typing.Final` as a `const` alias. It just specifies that the variable or attribute cannot be re-assigned, so it would be equivalent in the cases where it's usable. Then type checkers would complain if you reassign those variables. One snag is that you're allowed to do `x: Final = 3`, where the checker is then going to infer the appropriate type. Not sure if Cython should use `object` there, or try to pick some more optimal type?

**Comment by da-woods** [comment]
>  One snag is that you're allowed to do `x: Final = 3`, where the checker is then going to infer the appropriate type

I don't think that'd work in most places unfortunately, just because cython would typically try to generate the C code

```
const type x;
// ...
x = 3
```

It really only works for function arguments.

That suggests to me we shouldn't do it for now, because it'd break a bunch of valid Python code.
