### ISSUE TITLE
IF clauses inside definitions

### ISSUE THREAD

**Issue by robertwb** [cython/cython#573]
Normally, IF only works in the global scope. 
Defining conditional members of a struct necessitates redefining the whole structure:

```
IF UNAME_SYSNAME == "Windows":
      ctypedef struct ohmygod:
            int common
            int greece
ELSE:
      ctypedef struct ohmygod:
            int common
            float pelvis
```

This would be more convenient, especially for big structures:

```
ctypedef struct ohmygod:
     int common
     IF UNAME_SYSNAME == "Windows":
                 int greece
     ELSE:
                 float pelvis
```

Migrated from http://trac.cython.org/ticket/16

**Comment by maxbachmann** [comment]
@scoder given the deprecation in #4310 this can probably be closed

**Comment by da-woods** [comment]
Yeah I think we're agreed that we aren't planning to do this thanks
