### ISSUE TITLE
[BUG] Intermediate bool value cast as PyObject * and DECREFed

### ISSUE THREAD

**Issue by LinAGKar** [cython/cython#5731]
### Describe the bug

In the result of the example code given below, I get:

```C
  /* "test.pyx":10
 * 
 * def f2(x):
 * 	f1(False if x is None else x)             # <<<<<<<<<<<<<<
 * 
 * f2(None)
 */
  __pyx_t_2 = (__pyx_v_x == Py_None);
  if (__pyx_t_2) {
    __pyx_t_1 = ((PyObject *)0);
  } else {
    __pyx_t_3 = __Pyx_PyInt_As_bool(__pyx_v_x); if (unlikely((__pyx_t_3 == ((bool)-1)) && PyErr_Occurred())) __PYX_ERR(0, 10, __pyx_L1_error)
    __pyx_t_1 = ((PyObject *)__pyx_t_3);
  }
  __pyx_t_4 = __pyx_f_4test_f1(((bool)__pyx_t_1)); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 10, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_4);
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
  __Pyx_DECREF(__pyx_t_4); __pyx_t_4 = 0;
```

So it's taking the bool from the `if` expression (`0` or `__pyx_t_3`, depending on the branch), and casting it to a `PyObject *` (`__pyx_t_1`). Then later it casts the pointer back into a bool to pass it to the function, which works, but afterwards it tries to call `__Pyx_DECREF` on it, causing a segfault.

### Code to reproduce the behaviour:

```cython
# cython: language_level=3

cdef extern from "<stdbool.h>":
	ctypedef int bool

cdef f1(bool x):
	pass

def f2(x):
	f1(False if x is None else x)

f2(None)
```

Built with `cython --embed`

### Expected behaviour

In the C code above, `__pyx_t_1` should be a `bool`.

### OS

Linux

### Python version

3.9.18

### Cython version

3.0.2

**Comment by da-woods** [comment]
It's in 0.29.x too so doesn't appear to be a regression. The `typedef` also isn't relevant - just defining `f1` as `int` works the same.

**Comment by da-woods** [comment]
There's also two issues

```
    __pyx_t_1 = ((PyObject *)__pyx_t_3);
```

is also wrong
