### ISSUE TITLE
[BUG] Cython documentation link is broken

### ISSUE THREAD

**Issue by ECrosland** [cython/cython#5742]
### Describe the bug

The link to the Cython documentation at https://cython.org/#documentation is broken. It currently references `docs.cython.org`, whereas the documentation is evidently available at https://cython.readthedocs.io/en/latest/ instead.

Sorry if it's goofy to report this here. I wasn't sure how else to bring it to folks' attention.

### Expected behaviour

I expect to be taken to the Cython documentation when I click the link for it.

**Comment by matusvalo** [comment]
> It currently references docs.cython.org, whereas the documentation is evidently available at https://cython.readthedocs.io/en/latest/ instead.

The `docs.cython.org` is redirecting to `https://cython.readthedocs.io/en/latest/`. I got no error. I don't see any problem there. Have I missed something?

**Comment by ECrosland** [comment]
Huh. The redirect doesn't work for me on my work laptop, which is what led me to report this. I just tried it on another machine, and it does work there. Perhaps my office VPN is the culprit, I don't know. I works if I visit the `cython.readthedocs.io` site directly.

**Comment by da-woods** [comment]
The redirect works for me too.

**Comment by ECrosland** [comment]
All right. I didn't mean to send you all on a wild goose chase with this.

I confirmed that the problem only manifests for me when I'm on my organization's VPN. In that case, when I try to follow the link to the documentation, I get a message from Chrome saying the connection was reset.

FWIW, it seems it may be happening because the link gives `http://docs.cython.org/` as the href. If I modify that using the browser's dev tools to use an HTTPS URL instead, then it works fine for me on my VPN. Maybe the VPN just isn't happy accepting a redirect from an unsecure source.

**Comment by scoder** [comment]
Thanks. There were a few links still using insecure HTTP needlessly.
