### ISSUE TITLE
[BUG] Unsupport `match...case...` statement when compiling *.py 

### ISSUE THREAD

**Issue by DawnEver** [cython/cython#5755]
### Describe the bug

`match...case...` statement, proposed in [PEP 634: Structural Pattern Matching](https://peps.python.org/pep-0634),provides pattern matching process for users like `switch` statement in C/C++.

However, this statement is not supported in current Cython.

A minimal example is as following to reproduce the issue:

### Code to reproduce the behaviour:

```python
# Minimal example to reproduce the issue
a=1
match a:
    case 1:
        print("1")
    case _:
        print("2")
"""
>>> python .../test.py
1

>>> cython .../test.py
Error compiling Cython file:
------------------------------------------------------------
...
# minimal example to reproduce the issue
a=1
match a:
      ^
------------------------------------------------------------

.../test.py:3:6: Syntax error in simple statement list
"""
```

### Expected behaviour

Any solutions or suggestions?

If it is a bug, I am trying to fix this bug if possible.

### OS

macOS

### Python version

3.10.12

### Cython version

3.0.2 and 3.0.3

## My Analysis
So I trace back to the function `def p_simple_statement_list(s, ctx, first_statement = 0)` in `./Cython/Compiler/Parsing.py`,which raise the syntax error. The only call appears in the function `def p_statement(s, ctx, first_statement = 0)` in the same file.

```python
...
elif s.sy == 'include':
    if ctx.level not in ('module', 'module_pxd'):
        s.error("include statement not allowed here")
...
elif s.sy == 'for':
    return p_for_statement(s)
elif s.sy == 'with':
    return p_with_statement(s)
...
```
This function deals with different statements according to prefixs. I think `p_match_statement` and `p_case_statement` are needed to resolve this statement.

Also, I searched `'match'` globally in the project, but found nothing. It seems that match statement is not considered in current cython.

I am trying to fix this bug now if possible.

**Comment by da-woods** [comment]
Duplicate https://github.com/cython/cython/issues/4029.

It just isn't implemented yet in any Cython release. In that ticket you'll find links to a branch where it is implemented in full, but this hasn't yet been reviewed and merged.
