### ISSUE TITLE
[BUG] Undesirable performance warnings

### ISSUE THREAD

**Issue by pitrou** [cython/cython#5757]
### Describe the bug

The upgrade to Cython 3.0.3 on the Apache Arrow CI suddenly produces a lot of similar warnings when compiling our Cython files. Example:
```
  [1/129] Compiling Cython CXX source for _compute...
  performance hint: pyarrow/_compute.pyx:380:39: Exception check will always require the GIL to be acquired. Possible solutions:
        1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
```
https://github.com/apache/arrow/actions/runs/6452131883/job/17513702248#step:6:3712

The warning is legitimate in itself (that is, the analysis is right), it's just that it produces no actual value for us, and we get hundreds of instances of this warning simply because it flags a very common and convenient construct in the Arrow Cython source code (that construct unpacks a C++ result-or-error type and raises a Python exception on error).

Several complaints here:

1. I skimmed through the docs and I haven't found how to disable the warning (in particular, it does not seem mentioned [here](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html?highlight=warning#warnings)). It should be possible to disable warnings selectively, because they otherwise can obscure other more important pieces of information.

2. I also find weird that the warning message seems to introduce several "Possible solutions" but only one is displayed. Is the message truncated?

### Cython version

3.0.3

**Comment by pitrou** [comment]
cc @AlenkaF

**Comment by AlenkaF** [comment]
cc @danepitkin

**Comment by matusvalo** [comment]
There is compiler options for that:

https://github.com/cython/cython/blob/459f7c6236b7507b664703e6a20aafafe22f8a21/Cython/Compiler/Options.py#L153C8-L153C8

The reasy why it is not present in documentation is that currently there is only documentation of Cython 3.0.2 not sure why.

**Comment by pitrou** [comment]
> There is compiler options for that:

Is there a corresponding command-line option?

**Comment by scoder** [comment]
> currently there is only documentation of Cython 3.0.2 not sure why.

Build failure in readthedocs due to API changes on their side. I'll try to fix it.

**Comment by da-woods** [comment]
> 2\. I also find weird that the warning message seems to introduce several "Possible solutions" but only one is displayed. Is the message truncated?

No. It's a template that can output different numbers of options depending on the context, and you're (correctly) only getting one. I suspect it's worth tweaking the grammar a bit in that case though.

--------------------------------

It's obvious a bit tricky - we want the message to be visible (because otherwise nobody will benefit from it, and it is a slightly unintuitive performance change) but don't want it to be disruptive. I'd deliberately made it "not a warning" so it wouldn't trip with `-Werrors`. But maybe it could be a bit easier to turn off.

The other thing we could might be able to change is to only show it on implicitly `except *` functions, and to assume that people who've manually added `except *` know what they're doing and don't need to see it.

**Comment by pitrou** [comment]
> The other thing we could might be able to change is to only show it on implicitly `except *` functions, and to assume that people who've manually added `except *` know what they're doing and don't need to see it.

Hmm, this is in a `with nogil` block, so I don't see where we would add a `except *` block.

**Comment by da-woods** [comment]
> Hmm, this is in a with nogil block, so I don't see where we would add a except * annotation.

On the function.

```
cdef Something func1() nogil except *:
   ...

# later
with nogil:
  func1()
```

and explicitly putting it on the function definition would turn it off. (To be clear, this is something we could do - I don't think it's something we've done)

**Comment by da-woods** [comment]
I wasn't really saying anything about inner functions. Your declaration of `GetResultValue` looks to be https://github.com/apache/arrow/blob/ad26f3ff2348292be8d723be64f443553c3703f3/python/pyarrow/includes/common.pxd#L167.

I was suggesting that the explicit `extern *` on that declaration would tell Cython that you know about the exception behaviour and be enough to turn off the warnings for the calls.

**Comment by pitrou** [comment]
> I was suggesting that the explicit `extern *` on that declaration would tell Cython that you know about the exception behaviour and be enough to turn off the warnings/hints for the calls.

Ah, thank you for the clarification. Yes, that would work for us.

**Comment by da-woods** [comment]
... doesn't mean you shouldn't have a command-line option or similar to turn it off too. Just thinking about ways that it could be made a little more targeted to only the people who need it.

**Comment by pitrou** [comment]
By the way, I can't seem to be able to pass the relevant option on the command line:
```console
$ python -m cython --version
Cython version 3.0.3
$ python -m cython -X show_performance_hints=0
Traceback (most recent call last):
  [...]
ValueError: Unknown option: "show_performance_hints"
$ python -m cython -X show-performance-hints=0
Traceback (most recent call last):
  [...]
ValueError: Unknown option: "show-performance-hints"
```

**Comment by matusvalo** [comment]
It seems that documentation even after update still missing `show-performance-hints` option. I created PR fixing it.

> By the way, I can't seem to be able to pass the relevant option on the command line:

I am afraid that currently it is not possible. If I am not wrong the only way how to turn it off is by setting it programatically as showed in example: https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-options

**Comment by pitrou** [comment]
> I am afraid that currently it is not possible. If I am not wrong the only way how to turn it off is by setting it programatically as showed in example

Ouch...

**Comment by matusvalo** [comment]
There is discussion to expose it as directive see #5759
