### ISSUE TITLE
[ENH] Release branches?

### ISSUE THREAD

**Issue by haampie** [cython/cython#5763]
### Is your feature request related to a problem? Please describe.

It looks like `3.0.x` tags are made on the `master` branch, so that patch releases now get new features and potentially breaking changes

Is that intentional?

### Describe the solution you'd like.

Tags on a branch `releases/3.0` which only receives bugfix backports from the `master` branch

**Comment by scoder** [comment]
>Is that intentional?

It didn't really receive any new features yet. We're mostly still cleaning up the initial release, smoothing rough corners, and helping users to migrate more easily.

Once we're through with that, I'd like to branch it out and prepare the Py3-only release 3.1.

**Comment by haampie** [comment]
Ok 👌 feel free to close. I was mostly looking for an obvious place for Python 3.12 related fixes, but I guess I'll just have to check the master branch for now

**Comment by da-woods** [comment]
I think any significant Python 3.12 fixes would probably end up in the next possible 3.0.x release at this stage anyway.

Is there anything specific that's broken with Python 3.12? As far as I'm aware the sole remaining issue is profiling and everything else has been working for a while.
