### ISSUE TITLE
[BUG] In Shadow.py, is it always_allows_keywords or always_allow_keywords?

### ISSUE THREAD

**Issue by lk-1984** [cython/cython#5772]
### Describe the bug

The pylint is complaining:

```
Module 'cython' has no 'always_allow_keywords' member; maybe 'always_allows_keywords'?
```

when I have

```
@cython.always_allow_keywords(True)
```

And there indeed exists `always_allows_keywords` in the Cychon repository:

https://github.com/cython/cython/blob/master/Cython/Shadow.py#L113

I have to disable the "no-member" in the pylint due this for those decoration calls. The build obviously fails when I use `always_allows_keywords` and succeeds, when I use `always_allow_keywords`.

### OS

WSL2 Ubuntu 22.04

### Python version

Python 3.9.16

### Cython version

3.0.4

**Comment by da-woods** [comment]
That looks like a typo in `Shadow.py` - it should be `always_allow_keywords`. PR welcome.

**Comment by lk-1984** [comment]
> That looks like a typo in `Shadow.py` - it should be `always_allow_keywords`. PR welcome.

https://github.com/cython/cython/pull/5774

Hopefully that is in order.

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/3780a03c18195eeb277a2b7605c33f9c8c18dcf9
