### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HamadPhy** [cython/cython#5775]
### Describe the bug

I want to install a specific version of cython using 

pip install Cython==0.29.36
 but i am getting error 
 "ERROR: Could not find a version that satisfies the requirement Cython==0.29.36 (from versions: none)
ERROR: No matching distribution found for Cython==0.29.36"
![image](https://github.com/cython/cython/assets/125566140/dc2f66b4-d508-4d79-b74b-18d814bc449a)

### Code to reproduce the behaviour:

```cython
# example code
```

### OS

Windows

### Python version

3.10.9

### Cython version

0.29.36

### Additional context

I want to install a specific version of cython using 

pip install Cython==0.29.36
 but i am getting error 
 "ERROR: Could not find a version that satisfies the requirement Cython==0.29.36 (from versions: none)
ERROR: No matching distribution found for Cython==0.29.36"

![image](https://github.com/cython/cython/assets/125566140/f8a0b4ea-49ca-42ce-ad2d-f725d0bdc60c)
![image](https://github.com/cython/cython/assets/125566140/745e45e0-a022-4667-ae85-56102c3a67af)

**Comment by da-woods** [comment]
That looks very much like you have a network connection issue so pip isn't able to connect.

**Comment by HamadPhy** [comment]
Thank you for your feedback I will try again. 


On Saturday, October 21, 2023, 6:05 PM, da-woods ***@***.***> wrote:




That looks very much like you have a network connection issue so pip isn't able to connect.
