### ISSUE TITLE
[BUG] Indexing self fails under PyPy with "%T index out of range"

### ISSUE THREAD

**Issue by oscarbenjamin** [cython/cython#5776]
### Describe the bug

I have a cdef class that has a `leading_coefficient` method:
```python
# polymod.pyx

cdef class poly:

    def __len__(self):
        return 0

    cpdef long degree(self):
        return -1

    def __getitem__(self, key):
        if key < 0:
            return 0

    def leading_coefficient(self):
        return self[self.degree()]
```
The `self.degree()` method can return `-1` but `__getitem__` can handle that case. The code runs fine under CPython but fails under PyPy with:
```python
>>>> p.leading_coefficient()
Traceback (most recent call last):
  File "/home/oscar/current/active/python-flint/tmp/cytest/stuff.py", line 7, in <module>
    print(p.leading_coefficient())
  File "polymod.pyx", line 14, in polymod.poly.leading_coefficient
    return self[self.degree()]
IndexError: %T index out of range
```
Calling `p[p.degree()]` with an instance of the class works fine but calling the `p.leading_coefficient()` method whose body is just `return self[self.degree()]` fails.

The bug is not seen if the `long` type declaration is removed or if the `degree` method is made `def`. The bug is still seen when degree is either `cpdef` or `cdef`. If the `__len__` method is removed then a different error is seen:
```python
Traceback (most recent call last):
  File "/home/oscar/current/active/python-flint/tmp/cytest/stuff.py", line 7, in <module>
    print(p.leading_coefficient())
  File "polymod.pyx", line 11, in polymod.poly.leading_coefficient
    return self[self.degree()]
TypeError: 'polymod.poly' has no length
```
Somehow the C code generated for `self[self.degree()]` is assuming that it can treat `self` as a sequence rather than using the `__getitem__` method that is defined. The code is basically:
```c
  /* "polymod.pyx":11
 * 
 *     def leading_coefficient(self):
 *         return self[self.degree()]             # <<<<<<<<<<<<<<
 */
...
 __pyx_t_2 = __Pyx_GetItemInt(((PyObject *)__pyx_v_self), __pyx_t_1, long, 1, __Pyx_PyInt_From_long, 0, 1, 1);
...
```
In turn this is defined as
```c
#define __Pyx_GetItemInt(o, i, type, is_signed, to_py_func, is_list, wraparound, boundscheck)\
    (__Pyx_fits_Py_ssize_t(i, type, is_signed) ?\
    __Pyx_GetItemInt_Fast(o, (Py_ssize_t)i, is_list, wraparound, boundscheck) :\
    (is_list ? (PyErr_SetString(PyExc_IndexError, "list index out of range"), (PyObject*)NULL) :\
               __Pyx_GetItemInt_Generic(o, to_py_func(i))))
```
I'm not sure exactly which code paths are taken here.

I have tested with Cython 3.0.4 and also current Cython master under both CPython and PyPy and always this works under CPython and fails under PyPy.

### Code to reproduce the behaviour:

```cython
# polymod.pyx

cdef class poly:

    def __len__(self):
        return 0

    cpdef long degree(self):
        return -1

    def __getitem__(self, key):
        if key < 0:
            return 0

    def leading_coefficient(self):
        return self[self.degree()]
```
A script to test:
```python
# stuff.py

import polymod

p = polymod.poly()
print(p.degree())
print(p[-1])
print(p[p.degree()])
print(p.leading_coefficient())
```

### Expected behaviour

The `leading_coefficient` method should always return `0` and should not fail with an exception.

### OS

Linux

### Python version

PyPy 3.9-7.3.12

### Cython version

3.0.4 or current master

### Additional context

This comes from a python-flint issue:
https://github.com/flintlib/python-flint/issues/74#issuecomment-1773827740

**Comment by da-woods** [comment]
On PyPy `__Pyx_GetItemInt_Fast` ends up as (there's a big `ifdef` block which is dropped in PyPy)

```
static CYTHON_INLINE PyObject *__Pyx_GetItemInt_Fast(PyObject *o, Py_ssize_t i, int is_list,
                                                     CYTHON_NCP_UNUSED int wraparound,
                                                     CYTHON_NCP_UNUSED int boundscheck) {
    if (is_list || PySequence_Check(o)) {
        return PySequence_GetItem(o, i);
    }
    return __Pyx_GetItemInt_Generic(o, PyInt_FromSsize_t(i));
}
```

and `__Pyx_GetItemInt_Generic` is just

```
static PyObject *__Pyx_GetItemInt_Generic(PyObject *o, PyObject* j) {
    PyObject *r;
    if (unlikely(!j)) return NULL;
    r = PyObject_GetItem(o, j);
    Py_DECREF(j);
    return r;
}
```

I think `PySequence_Check` should pass and it'll call `PySequence_GetItem`. When you write `__getitem__` Cython defines both `sq_item` and `mp_subscript` which both point at the `__getitem__` method. Therefore, `PySequence_GetItem` calls your `__getitem__` method via `sq_item`.

Even if `PySequence_Check` fails, it'll go through `PyObject_GetItem` (which also calls your `__getitem__` method, this time through `mp_subscript` I think).

(As an aside, there's room for improvement in Cython's here since it does some unnecessary conversions to Python integers in some cases, although not yours).

The upshot of all of this is that I'm relatively sure the logic is OK and that this is a PyPy bug.
So it's probably best reported there. @mattip - any thoughts?

Cython is probably missing a test here however.

**Comment by da-woods** [comment]
In PyPy: https://foss.heptapod.net/pypy/pypy/-/blob/ee9b959e818bb95b3d92861dd3fd15ef41a3f0e4/pypy/module/cpyext/sequence.py#L174

```
@cpython_api([PyObject, Py_ssize_t], PyObject, result_is_ll=True)
def PySequence_GetItem(space, w_obj, i):
    """Return the ith element of o, or NULL on failure. This is the equivalent of
    the Python expression o[i]."""
    if i < 0:
        l = PySequence_Length(space, w_obj)
        i += l
        if i < 0:
            # Prevent things like 'abc'[-4] from turning into 'abc'[-1]
            # since this can end up calling space.getitem()
            raise oefmt(space.w_IndexError,
                "%T index out of range")
    return PySequence_ITEM(space, w_obj, i)
```

So if manually calculate the negative index itself before passing it to `PySequence_ITEM`, and the call to `sq_item` is in `PySequence_ITEM`. In contrast CPython goes straight to calling `sq_item` (https://github.com/python/cpython/blob/5e7727b05232b43589d177c15263d7f4f8c584a0/Objects/abstract.c#L1932)

(There's also a second bug there when it forgets to pass the type to be formatted in the error message, but that's minor)

**Comment by da-woods** [comment]
Hmmmmm.... actually.... changed my mind. CPython does basically the same thing with `__len__` (although it does check that it's defined first).

To me this suggests that Cython shouldn't put `__getitem__` in `sq_item` because that stops the user from handling negative numbers as they would like.

**Comment by da-woods** [comment]
Or possibly also that indexing anything unknown with a negative C `int` in Cython shouldn't go through `PySequence_GetItem` because it potentially behaves differently to indexing in Python.

**Comment by da-woods** [comment]
Final comment for now: the "fast path" CPython code checks `mp_subscript` before `sq_item` while the slow path tries sequence first. So they aren't equivalent.

**Comment by mattip** [comment]
Thanks for digging in, and exposing some unrelated shortcomings with PyPy. If I understand correctly, there are other cases where this condition could be False
https://github.com/cython/cython/blob/a272c6261a07b3b6b5ecf84dc79129453267aca9/Cython/Utility/ObjectHandling.c#L425

so if @oscarbenjamin defined, say, `CYTHON_AVOID_BORROWED_REFS`, the code would fail similarly?

**Comment by da-woods** [comment]
> Thanks for digging in, and exposing some unrelated shortcomings with PyPy. 

Just so we're clear, my current view is that the only actual bug in PyPy here is a bit of exception string formatting.


> If I understand correctly, there are other cases where this condition could be False
> 
> https://github.com/cython/cython/blob/a272c6261a07b3b6b5ecf84dc79129453267aca9/Cython/Utility/ObjectHandling.c#L425
> 
> so if @oscarbenjamin defined, say, `CYTHON_AVOID_BORROWED_REFS`, the code would fail similarly?

Yes - practically the limited API is the most important other case where it'd fail similarly.

**Comment by oscarbenjamin** [comment]
The poly object shown is a mapping rather than sequence and does not conform to the sequence protocol.

I don't think that `PySequence_GetItem` should be used in place of `PyObject_GetItem` for this type.

**Comment by da-woods** [comment]
> The poly object shown is a mapping rather than sequence and does not conform to the sequence protocol.
> 
> I don't think that `PySequence_GetItem` should be used in place of `PyObject_GetItem` for this type.

Yes I agree - that's the conclusion I came to too.

**Comment by da-woods** [comment]
@mattip I tried to create an PyPy bug report for the `%T` formatting issue. But unfortunately heptapod says "Your issue has been recognized as spam and has been discarded.". So I'm afraid I can't report it there... sorry!

**Comment by mattip** [comment]
Thanks. I [fixed that](https://foss.heptapod.net/pypy/pypy/-/commit/8a88f1224e9867ce86756c50020562d58de470a3) without adding the extra check for `__len__`.

**Comment by oscarbenjamin** [comment]
Thanks all!
