### ISSUE TITLE
[BUG] Operations with variable annotated with `int` avoids optimisations

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#5783]
### Describe the bug

When variable has type `int` in pure python mode, Cython is using generic `PyObject_RichCompare` instead of optimised `__Pyx_PyInt_EqObjC` which is used when no annotation is used.

### Code to reproduce the behaviour:

```python
def bar(a: int):
    print(a == 5)

bar()
```

Generated C code:

```c
  /* "deleteme.py":23
 * 
 * def bar(a: int):
 *     print(a == 5)             # <<<<<<<<<<<<<<
 * 
 * bar()
 */
  __pyx_t_1 = PyObject_RichCompare(__pyx_v_a, __pyx_int_5, Py_EQ); __Pyx_XGOTREF(__pyx_t_1); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 23, __pyx_L1_error)
```

### Expected behaviour

```python
def bar(a):
    print(a == 5)

bar()
```

Generated C code:
```c
  /* "deleteme.py":23
 * 
 * def bar(a):
 *     print(a == 5)             # <<<<<<<<<<<<<<
 * 
 * bar()
 */
  __pyx_t_1 = __Pyx_PyInt_EqObjC(__pyx_v_a, __pyx_int_5, 5, 0); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 23, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
```

### OS

MacOS

### Python version

3.9

### Cython version

master

**Comment by da-woods** [comment]
I suspect what's happened is that the check is probably based on `is py_object_type` and we assume anything typed with something else *isn't* an int.

We could probably do better though if we really wanted:
`__Pyx_PyInt_EqObjC` is written with the assumption that `a` is probably an `int` but doesn't have to be. So we could generate a more specific function for this.

**Comment by matusvalo** [comment]
> I suspect what's happened is that the check is probably based on is py_object_type and we assume anything typed with something else isn't an int.

Yes there are two places:
1. New method needs to be added for `int` type - `_handle_simple_method_int___eq__`:
 https://github.com/cython/cython/blob/edaea23cc5a7909e84d3bd01b0a8ab2206af8e95/Cython/Compiler/Optimize.py#L3425
2. `int` type needs to be added to this line:
 https://github.com/cython/cython/blob/edaea23cc5a7909e84d3bd01b0a8ab2206af8e95/Cython/Compiler/Optimize.py#L4210
https://github.com/cython/cython/blob/edaea23cc5a7909e84d3bd01b0a8ab2206af8e95/Cython/Compiler/Optimize.py#L4215

**Comment by da-woods** [comment]
> 1. New method needs to be added for `int` type - `_handle_simple_method_int___eq__`:

I'm sure you've spotted it, but this issue (and fix) applies to most other binops too (i.e. add, sub, etc)
