### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by rnarkk** [cython/cython#5786]
### Describe your issue

Hi, I want to suggest to enable Discussions feature on GitHub. Mailing lists are too old and inconvenient for technical discussions where you often want to share styled code snippets or embed span of the source code inline. GitHub Discusses is relatively more accessible and easy to use for many of us. Please consider it.

Discourse would also be very appreciated.

Thank you.

**Comment by scoder** [comment]
I'll close this issue since it's the wrong place to discuss such a change. Please ask on the current cython-users mailing list to see if you find enough support there. If users generally agree that they would prefer moving away from email, then we can make the switch.
