### ISSUE TITLE
[BUG] Segmentation fault from trying to print std::string as %d

### ISSUE THREAD

**Issue by Source61** [cython/cython#5787]
### Describe the bug

Doesn't happen on its own, but with 2 preceding arguments it segfaults.
Haven't tested anything else, like how many arguments are required to cause segfault, etc.

### Code to reproduce the behaviour:

```cython
from libcpp.string cimport string

cdef:
        string s = b"abc"

print("addCost %f -> this.cost: %f (this.ip: %d)" % (7, 77, s))
```

### OS

Linux (Ubuntu 22.04.3 LTS WSL)

### Python version

3.10.12

### Cython version

3.0.4

**Comment by matusvalo** [comment]
Issue is caused because string `s` is formatted as integer using `%d`. Changing line to:
```python
print("addCost %f -> this.cost: %f (this.ip: %s)" % (7, 77, s))
```

Fixes the issue. But still we should error out in better way than segfault...

**Comment by matusvalo** [comment]
OK this is minimal reproducer:
```python
s= 'asdf'
"%d" % (s,)
```
Compiling it and importing will cause segfault. 

When brackets are not used:
```python
s= 'asdf'
"%d" % s
```
the compiling and running an example will end up with an exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nogil.pyx", line 2, in init nogil
    "%d" % s
TypeError: %d format: a number is required, not str
```

**Comment by scoder** [comment]
Thanks for investigating. There was a missing failure check which made it continue the formatting with a NULL pointer.
