### ISSUE TITLE
[BUG] classes with `__weakref__` don't compile using the limited api

### ISSUE THREAD

**Issue by ap--** [cython/cython#5793]
### Describe the bug

Hello everyone,

I was trying to compile a class with a `cdef object __weakref__` attribute in the limited api and it crashes with:

```
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -DCYTHON_LIMITED_API=1 -DPy_LIMITED_API=0x030B0000 -I/private/var/folders/l4/gpyzwv455hzbmbv78x05555h0000gn/T/build-env-x8r7d7re/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c limited_weakref.cpp -o build/temp.macosx-14-arm64-cpython-311/limited_weakref.o
limited_weakref.cpp:3707:38: error: member access into incomplete type 'PyTypeObject' (aka '_typeobject')
  if (__pyx_ptype_15limited_weakref_A->tp_weaklistoffset == 0) __pyx_ptype_15limited_weakref_A->tp_weaklistoffset = offsetof(struct __pyx_obj_15limited_weakref_A, __weakref__);
                                     ^
/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:20:16: note: forward declaration of '_typeobject'
typedef struct _typeobject PyTypeObject;
               ^
limited_weakref.cpp:3707:95: error: member access into incomplete type 'PyTypeObject' (aka '_typeobject')
  if (__pyx_ptype_15limited_weakref_A->tp_weaklistoffset == 0) __pyx_ptype_15limited_weakref_A->tp_weaklistoffset = offsetof(struct __pyx_obj_15limited_weakref_A, __weakref__);
                                                                                              ^
/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:20:16: note: forward declaration of '_typeobject'
typedef struct _typeobject PyTypeObject;
               ^
2 errors generated.
error: command '/usr/bin/clang' failed with exit code 1
```

-Andreas

### Code to reproduce the behaviour:

```cython
# limited_weakref.pyx

cdef class A:
    cdef object __weakref__
```

### Expected behaviour

It should compile.

### Additional context

The relevant compiler code seems to be here: https://github.com/cython/cython/blob/bc32b7ec3f15f532c0ae59b930544c23172e8c50/Cython/Compiler/Nodes.py#L5817-L5831

**Comment by da-woods** [comment]
I think the solution here would be to add `__weakref__` to `Py_tp_members` (or possibly to use `[Py_TPFLAGS_MANAGED_WEAKREF](https://docs.python.org/3/c-api/typeobj.html#c.Py_TPFLAGS_MANAGED_WEAKREF)` if the version of Python is high enough).

> If it is not possible to switch to a MANAGED flag (for example, for vectorcall or to support Python older than 3.12), specify the offset in [Py_tp_members](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_members).

(https://docs.python.org/3/c-api/type.html#c.PyType_Slot.slot)

Unfortunately that doesn't do the "already set" check that our current code does so it isn't identical, but that's an edge case that I don't think we can cover with the limited API.

-----------------------------------------------

It's probably worth using the MANAGED flags (for both `__dict__` and `__weakref__` in the regular API too on suitable Python versions and in the common case where we aren't inheriting from an extern class or builtin. In this case we know that we don't need the "already set" check. And I think Python is hoping that this'll be the optimized structure in future.
