### ISSUE TITLE
[BUG] Odd warning in generated .c file related to fused type usage

### ISSUE THREAD

**Issue by skunkyevil** [cython/cython#5794]
### Describe the bug

There's an odd warning present when I check for fused type in `if` clause.
```Warning C4244 '=': conversion from 'long' to 'char', possible loss of data```

I found mention of the same bug in Internet dated 2015:
https://www.mail-archive.com/cython-devel@python.org/msg04553.html

I minimized the example code

### Code to reproduce the behaviour:

```cython
ctypedef fused floating:
    float
    double

cpdef add_one(floating [:] array):
    if floating is float:
        pass
        
```

Copilled with:
```python
from setuptools import setup
from Cython.Build import cythonize

setup(
    name='Hello world app',
    ext_modules=cythonize("bug.pyx"),
)
```

### Expected behaviour

There should be no warning

### OS

Windows 10

### Python version

3.9

### Cython version

3.0.5

**Comment by scoder** [comment]
What warning message do you get?

**Comment by skunkyevil** [comment]
Sorry, it was ```Warning C4244 '=': conversion from 'long' to 'char', possible loss of data```. Updated above

**Comment by da-woods** [comment]
Probably from

https://github.com/cython/cython/blob/bc32b7ec3f15f532c0ae59b930544c23172e8c50/Cython/Compiler/FusedNode.py#L467

(where `kind` is a `char` and `ord` returns a `long`). PR welcome to fix - I think this could hide a real bug in principle

**Comment by scoder** [comment]
Ah, thanks. So this is from generated code on our side. I replaced the `char` type with `Py_UCS4` in https://github.com/cython/cython/commit/e584c46beb0ca96da647e30cca55ccfbe77b35de. It comes from a Unicode string, there's no reason why we should cut this down to a `char`.
