### ISSUE TITLE
[ENH] inline_defnode_calls more?

### ISSUE THREAD

**Issue by da-woods** [cython/cython#5806]
### Is your feature request related to a problem? Please describe.

We've got an (undocumented) compiler directive `optimize.inline_defnode_calls` which I think directly calls functions in closures without going through the python wrapper.

Is there any value to having a similar option for global functions? We already have `error_on_unknown_names` which assumes no external monkey-patching so the assumption here would be similar.

I suspect it should be off by default, but a lot of them mechanism is already there.

**Comment by da-woods** [comment]
Arguably this might be a little pointless because it's equivalent to just using `cpdef` functions (while it's a little more useful for inner functions where `cpdef` isn't possible)

**Comment by scoder** [comment]
I think this is mostly covered by the `auto_cpdef` directive.

**Comment by da-woods** [comment]
Yeah that was my conclusion after thinking about it more. I'll close this
