### ISSUE TITLE
Anaconda3 problem reading *.pyd created by cythonize

### ISSUE THREAD

**Issue by BijanSeif** [cython/cython#5807]
### Describe your issue

Hi,

I have converted my *.py files to *.pyd using cythonize command. In Pyhon enironment everything is fine and there is no problem and the improted package is working correctly. 

BUT when we call the package from anaconda jupyter notebook, or other anaconda edotors we encounter with the following problem:

ImportError: DLL load failed while importing code: The specified module could not be found.

Would you guide me what if the problem and what should I do?

I test it with the following simple code (Just wanna show you that there is no specific library or ...):

def mmntest():
    print('this is a test')

How do I call pyd? I change the name of created pyd files to what are them originally and then inside init call them. (I'm emphasizing that it is working in python environment BUT only in anaconda enivronment I have above problem)

**Comment by scoder** [comment]
Probably a problem with the Python module search path. Not sure what you mean by "call pyd" – you don't call extension modules, you import them.

In any case, this is almost certainly not a bug in Cython. For general support questions, please use the cython-users mailing list.
