### ISSUE TITLE
cython  prange

### ISSUE THREAD

**Issue by KnSun99** [cython/cython#5814]
### Describe the bug

I need to compute a big matrix. I want to use prange in cython to speed up the for loop.

The raw data is a numpy object consisting of an irregular array. (Array of object type, np.ndarray[object, ndim=1])
The raw data is shown below:
![image](https://github.com/cython/cython/assets/123467428/25ea67b1-6373-4606-8eba-954d6ec96ca0)
Each row is an array. Each data has a different number of rows but the same number of columns. such as 10×36, 5×36, 19×36, 105×36……

At compile time, the following error occurs:
![image](https://github.com/cython/cython/assets/123467428/6a63b492-4a45-451d-9d8a-b578753d223f)

### Code to reproduce the behaviour:

```cython
# example code
```
for m in range(nSeg):
    for n in prange(m, nSeg, nogil=True, schedule='static'):
        distmat[m, n] = calculate_distance_C(SegParas[m], SegParas[n], sigma)

### Expected behaviour

I wanted to speed up the calculations with prange.

### OS

Windows，Linux

### Python version

3.10.12 / 3.11.5

### Cython version

3.0.0

**Comment by da-woods** [comment]
1. The bug tracker is for bug reports or feature requests - please ask support questions on the [cython-users mailing list](https://groups.google.com/g/cython-users)
2. It is not possible to operate on Python objects in a nogil block so this won't work. You might consider using c++ (via Cython) and `vector[vector[double]]` for an irregular array instead.
