### ISSUE TITLE
Unclear documentation about types

### ISSUE THREAD

**Issue by sls1005** [cython/cython#5848]
### Describe your issue

From <https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#types> :

>It provides all the standard C types, namely `char`, `short`, `int`, `long`, `long long` as well as their `unsigned` versions

This gives the impression that only `char`, `short`, `int`, `long`, `long long` and their unsigned versions are standard C types, and that the other C types are not supported. I know that _namely_ doesn't necessarily mean that, but it's just misleading. Also, `float` and `double` aren't mentioned there, which might cause the reader to think that they aren't supported.

`float` appeared later in a grey box saying it replaces the Python `float`, while `double` appeared at the end of section and was described as may be wanted by someone, but not explicitly as supported.

And now I still don't know if `size_t` is supported.

**Comment by matusvalo** [comment]
There is open PR providing table of types supported by Cython: https://github.com/cython/cython/pull/4980

But it can be incomplete and needs review and expanding.

**Comment by scoder** [comment]
I agree that `float` and `double` are missing, and that `Py_ssize_t` and `size_t` should be explained.
