### ISSUE TITLE
[BUG] The PySide6 code cannot be encrypted, and an error message is reported

### ISSUE THREAD

**Issue by fggzs** [cython/cython#5872]
### Describe the bug

Compiling jianlou_ui.py because it changed.
[1/1] Cythonizing jianlou_ui.py
D:\Python\Python311\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: D:\MYpython\jianlou_ui.py
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
        self.proxies_checkBox.setGeometry(QRect(170, 160, 61, 21))
        self.token_textEdit = QTextEdit(self.centralwidget)
        self.token_textEdit.setObjectName(u"token_textEdit")
        self.token_textEdit.setGeometry(QRect(230, 350, 259, 219))
        self.token_textEdit.setStyleSheet(u"border-left: 1px solid rgb(0, 118, 177);\n"
"border-right: 1px solid  rgb(0, 118, 177);\n"
^

jianlou_ui.py:733:0: Cannot mix string literals of different types, expected u'', got ''

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Python\Python311\Scripts\easycython.exe\__main__.py", line 7, in <module>
  File "D:\Python\Python311\Lib\site-packages\begin\main.py", line 52, in start
    cmdline.apply_options(self.__wrapped__, opts,
  File "D:\Python\Python311\Lib\site-packages\begin\cmdline.py", line 253, in apply_options
    return_value = call_function(func, signature(ext), opts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\begin\cmdline.py", line 236, in call_function
    return func(*pargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\easycython\easycython.py", line 77, in main
    ext_modules = cythonize(ext_modules),
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "D:\Python\Python311\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: jianlou_ui.py

### Code to reproduce the behaviour:

# -*- coding: utf-8 -*-

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1243, 932)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(1080, 90, 101, 71))
        self.graphicsView_2 = QGraphicsView(self.centralwidget)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(0, 330, 471, 281))
        self.graphicsView_3 = QGraphicsView(self.centralwidget)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(0, 620, 471, 281))
        self.graphicsView_4 = QGraphicsView(self.centralwidget)
        self.graphicsView_4.setObjectName(u"graphicsView_4")
        self.graphicsView_4.setGeometry(QRect(480, 40, 476, 281))
        self.graphicsView_5 = QGraphicsView(self.centralwidget)
        self.graphicsView_5.setObjectName(u"graphicsView_5")
        self.graphicsView_5.setGeometry(QRect(480, 330, 471, 281))
        self.graphicsView_6 = QGraphicsView(self.centralwidget)
        self.graphicsView_6.setObjectName(u"graphicsView_6")
        self.graphicsView_6.setGeometry(QRect(480, 620, 471, 281))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(1080, 330, 101, 71))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(1080, 610, 101, 71))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(0, 0, 951, 41))
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.shangchuan1 = QPushButton(self.centralwidget)
        self.shangchuan1.setObjectName(u"shangchuan1")
        self.shangchuan1.setGeometry(QRect(980, 90, 101, 71))
        self.shangchuan2 = QPushButton(self.centralwidget)
        self.shangchuan2.setObjectName(u"shangchuan2")
        self.shangchuan2.setGeometry(QRect(980, 330, 101, 71))
        self.shangchuan3 = QPushButton(self.centralwidget)
        self.shangchuan3.setObjectName(u"shangchuan3")
        self.shangchuan3.setGeometry(QRect(980, 610, 101, 71))
        self.label_1 = QLabel(self.centralwidget)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(0, 40, 471, 281))
        self.label_1.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(480, 40, 471, 281))
        self.label_2.setScaledContents(True)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 330, 471, 281))
        self.label_3.setScaledContents(True)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 620, 471, 281))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(480, 620, 471, 281))
        self.label_6.setScaledContents(True)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(480, 330, 471, 281))
        self.label_4.setScaledContents(True)
        self.graphicsView_1 = QGraphicsView(self.centralwidget)
        self.graphicsView_1.setObjectName(u"graphicsView_1")
        self.graphicsView_1.setGeometry(QRect(0, 40, 476, 281))
        MainWindow.setCentralWidget(self.centralwidget)
        self.graphicsView_1.raise_()
        self.pushButton.raise_()
        self.graphicsView_2.raise_()
        self.graphicsView_3.raise_()
        self.graphicsView_4.raise_()
        self.graphicsView_5.raise_()
        self.graphicsView_6.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.lineEdit.raise_()
        self.shangchuan1.raise_()
        self.shangchuan2.raise_()
        self.shangchuan3.raise_()
        self.label_1.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_2.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u5b66\u751f\u8bfe\u5802\u8bc6\u522b", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u5b66\u751f\u5206\u5272", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u72b6\u6001\u8bc6\u522b", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u4eba\u8138\u8bc6\u522b", None))
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"                    \u4e0a\u4f20\u56fe\u7247                                    \u7ed3\u679c", None))
        self.shangchuan1.setText(QCoreApplication.translate("MainWindow", u"\u4e0a\u4f20", None))
        self.shangchuan2.setText(QCoreApplication.translate("MainWindow", u"\u4e0a\u4f20", None))
        self.shangchuan3.setText(QCoreApplication.translate("MainWindow", u"\u4e0a\u4f20", None))
        self.label_1.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.label_4.setText("")
    # retranslateUi

### Expected behaviour

The PySide6 code cannot be encrypted, and an error message is reported，And the code that encrypts the same as the Chinese function reports an error

### OS

windows

### Python version

3.11.3

**Comment by da-woods** [comment]
1. Cython isn't an encryption tool and has no interest in being an encryption tool.
2. You just need to put a `u` before the string starting ` "border-right: 1px solid rgb(0, 118, 177);\n"`
3. This probably is a minor Python incompatibility. I don't think it's high priority to fix though

**Comment by fggzs** [comment]
This is the code generated by qt library PySide 6. Can you support this transformation of pyd without manual processing

**Comment by da-woods** [comment]
The directive `language_level=3` fixes it. You can override the default directives in your setup file. This'll also work by default in Cython 3.1 where `language_level=3` is the only option.

Compiling auto-generated PySide code is unlike to be worthwhile though.
