### ISSUE TITLE
Getting ValueError: source code string cannot contain null bytes while using cython

### ISSUE THREAD

**Issue by shrinath136** [cython/cython#5876]
### Describe your issue

Hi Team

I tried running cython compile time optimization on FastAPI serving layer in python during ML Model inferencing.
Instead of loading plain python module for ML Model , I tried loading cython compile ML Module in FastAPI Server.

I am getting below error while loading ML Model while running on Mac OS Monterey ( Version 12.5)

ValueError: source code string cannot contain null bytes while using cython
Entire error trace

```
   spec.loader.exec_module(your_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes
```

Code used to load shared object file (.so extension file) generate via setup.py

```
loader = SourceFileLoader("IMHitEnterQueryFastText", "../pipelines/IMHitEnterQueryFastText/[IMHitEnterQueryFastText.cpython-310-darwin.so](http://imhitenterqueryfasttext.cpython-310-darwin.so/)")
spec = importlib.util.spec_from_file_location("IMHitEnterQueryFastText",location="../pipelines/IMHitEnterQueryFastText/[IMHitEnterQueryFastText.cpython-310-darwin.so](http://imhitenterqueryfasttext.cpython-310-darwin.so/)",loader=loader)
your_module = importlib.util.module_from_spec(spec)
sys.modules["IMHitEnterQueryFastText"] = your_module
spec.loader.exec_module(your_module)
```
Any help would be appreciated here.

**Comment by da-woods** [comment]
I would not expect to be able to load a `.so` with `SourceFileLoader` because it isn't a source file - it's an extension module. `ExtensionFileLoader` might be more the right thing (but I haven't tried it)?

This doesn't look like a Cython bug; please ask support questions on the [cython-users mailing list](https://groups.google.com/g/cython-users)
