### ISSUE TITLE
Not able to Load .so file Shared Object File generated from Cython

### ISSUE THREAD

**Issue by shrinath136** [cython/cython#5881]
### Describe your issue

I tried running cython compile time optimization on FastAPI serving layer in python during ML Model inferencing.

Instead of loading plain python module for ML Model , I tried loading cython compile ML Module in FastAPI Server.

I am using below code to load generated .so file dynamically in python run time.

// load module functionality
```
loader = ExtensionFileLoader("EnterQueryFastText", "../pipelines/EnterQueryFastText/EnterQueryFastText.cpython-310-darwin.so")
spec = importlib.util.spec_from_file_location("EnterQueryFastText",location="../pipelines/EnterQueryFastText/EnterQueryFastText.cpython-310-darwin.so",loader=loader)
your_module = importlib.util.module_from_spec(spec)
sys.modules["EnterQueryFastText"] = your_module
spec.loader.exec_module(your_module)
```

// calling method ( pre_process,transform, post_process) in loaded module

```
input = {"query":"achi"}
pre_proc_output:Any = your_module.pre_process(input)
transform_output:Any = your_module.transform(pre_proc_output)
post_proc_output:Any = your_module.post_process(transform_output)
print(post_proc_output)
```
Error :

`EnterQueryFastText' has no attribute 'pre_process'`
Any idea what is going wrong here ?

FYI - adding cython class structure for reference

```
cdef class EnterQueryFastText:

  cpdef transform(self, payload):
    cdef embedding = self._get_sentence_vector(payload)
    return embedding

  cpdef pre_process(self, input: dict):
    cdef pre_processed_input = cleanText(input['query'])
    return pre_processed_input
```

Tried googling other options available for loading cython (.so file) module but could not find any better mechanism

**Comment by da-woods** [comment]
Please don't use the bug/feature tracker to ask support questions.
