### ISSUE TITLE
Cython compile errors

### ISSUE THREAD

**Issue by Noob225566** [cython/cython#5884]
### Describe the bug

I can't install h5py because of some cython compile errors 

### Code to reproduce the behaviour:

To reproduce the error type this 
pip install h5py --no-build-isolation

### Expected behaviour

H5py successfully installed

### OS

Linux on termux on android

### Python version

 Python 3

### Cython version

3.0.5

### Additional context

Just ask me and i provide you the error but plz respond me as soon as possible

**Comment by da-woods** [comment]
I believe H5py only supports Cython 0.29.x right now. They're working to fix this, but you have to use an older version of Cython currently.

In future please ask support questions on the [cython-users mailing list](https://groups.google.com/g/cython-users) instead

**Comment by da-woods** [comment]
Also

> Just ask me and i provide you the error but plz respond me as soon as possible

Things like the error message should be *a basic part* of a bug report, not something that you provide later if asked.

**Comment by Noob225566** [comment]
Thanks bro i tried cython 0.29.24 version and when i trype pip install h5py --no-build-isolation it gives ma a different error but something a cython compile error here is the error

Collecting h5py
  Using cached h5py-3.10.0.tar.gz (403 kB)
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.17.3 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from h5py) (1.26.1)
Building wheels for collected packages: h5py
  Building wheel for h5py (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for h5py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [165 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-311
      creating build/lib.linux-armv7l-cpython-311/h5py
      copying h5py/h5py_warnings.py -> build/lib.linux-armv7l-cpython-311/h5py
      copying h5py/__init__.py -> build/lib.linux-armv7l-cpython-311/h5py
      copying h5py/ipy_completer.py -> build/lib.linux-armv7l-cpython-311/h5py
      copying h5py/version.py -> build/lib.linux-armv7l-cpython-311/h5py
      creating build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/attrs.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/__init__.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/vds.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/compat.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/dims.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/dataset.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/files.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/base.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/filters.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/datatype.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/selections.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/group.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      copying h5py/_hl/selections2.py -> build/lib.linux-armv7l-cpython-311/h5py/_hl
      creating build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_h5f.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_h5p.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_base.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/__init__.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_file_image.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_completions.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_attribute_create.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_filters.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_h5pl.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/common.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_attrs.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_file2.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_selections.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_group.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_errors.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_dimension_scales.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_dataset.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_ros3.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_h5t.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_file_alignment.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_h5z.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_dtype.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_h5.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/conftest.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_attrs_data.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_objects.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_datatype.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_slicing.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_file.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_h5o.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      copying h5py/tests/test_big_endian_file.py -> build/lib.linux-armv7l-cpython-311/h5py/tests
      creating build/lib.linux-armv7l-cpython-311/h5py/tests/data_files
      copying h5py/tests/data_files/__init__.py -> build/lib.linux-armv7l-cpython-311/h5py/tests/data_files
      creating build/lib.linux-armv7l-cpython-311/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-armv7l-cpython-311/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-armv7l-cpython-311/h5py/tests/test_vds
      copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-armv7l-cpython-311/h5py/tests/test_vds
      copying h5py/tests/test_vds/__init__.py -> build/lib.linux-armv7l-cpython-311/h5py/tests/test_vds
      copying h5py/tests/data_files/vlen_string_dset_utc.h5 -> build/lib.linux-armv7l-cpython-311/h5py/tests/data_files
      copying h5py/tests/data_files/vlen_string_dset.h5 -> build/lib.linux-armv7l-cpython-311/h5py/tests/data_files
      copying h5py/tests/data_files/vlen_string_s390x.h5 -> build/lib.linux-armv7l-cpython-311/h5py/tests/data_files
      running build_ext

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

      cdef struct err_data_t:
          H5E_error_t err
          int n

      cdef herr_t walk_cb(unsigned int n, const H5E_error_t *desc, void *e) nogil noexcept:
                                                                                 ^
      ------------------------------------------------------------

      h5py/_errors.pyx:97:76: Syntax error in C variable declaration
      Loading library to get build settings and version: /data/data/com.termux/files/usr/lib/libhdf5.so
      ********************************************************************************
                             Summary of the h5py configuration

        HDF5 include dirs: [
        '/data/data/com.termux/files/usr/include'
      ]
        HDF5 library dirs: [
        '/data/data/com.termux/files/usr/lib'
      ]
             HDF5 Version: (1, 14, 2)
              MPI Enabled: False
         ROS3 VFD Enabled: False
       DIRECT VFD Enabled: False
         Rebuild Required: True
           MS-MPI Enabled: False
      MS-MPI include dirs: []
      MS-MPI library dirs: []

      ********************************************************************************
      Executing api_gen rebuild of defs
      Updated /data/data/com.termux/files/usr/tmp/pip-install-jqfx5dq7/h5py_e7b8c6bc091b4b1e9c42dc5fec6a8fc6/h5py/config.pxi
      Executing cythonize()
      [ 1/24] Cythonizing /data/data/com.termux/files/usr/tmp/pip-install-jqfx5dq7/h5py_e7b8c6bc091b4b1e9c42dc5fec6a8fc6/h5py/_conv.pyx
      [ 2/24] Cythonizing /data/data/com.termux/files/usr/tmp/pip-install-jqfx5dq7/h5py_e7b8c6bc091b4b1e9c42dc5fec6a8fc6/h5py/_errors.pyx
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 68, in <module>
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 369, in run
          self.run_command("build")
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-install-jqfx5dq7/h5py_e7b8c6bc091b4b1e9c42dc5fec6a8fc6/setup_build.py", line 178, in run
          self.extensions = cythonize(self._make_extensions(config),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
          cythonize_one(*args)
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: /data/data/com.termux/files/usr/tmp/pip-install-jqfx5dq7/h5py_e7b8c6bc091b4b1e9c42dc5fec6a8fc6/h5py/_errors.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
Failed to build h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects

Well in short words i think your suggestion doesn't work but i am happy that someone response could plz help me to fix this error plz response as soon as possible 😄😄

**Comment by da-woods** [comment]
> In future please ask support questions on the [cython-users mailing list](https://groups.google.com/g/cython-users) instead

**Comment by Noob225566** [comment]
Bro i have a good news and a bad news the good news is that when i got frustrated because everytime I try to install h5py i got errors thats why i install keras-core without h5py using 
pip install keras-core --no-devs 
And it works even when i run pip show keras-core i got these
pName: keras-core
Version: 0.1.7
Summary: Multi-backend Keras.
Home-page: https://github.com/keras-team/keras-core
Author: Keras team
Author-email: keras-users@googlegroups.com
License: Apache License 2.0
Location: /data/data/com.termux/files/usr/lib/python3.11/site-packages
Requires: absl-py, dm-tree, h5py, namex, numpy, rich
Required-by:
And i already have all the required packages except h5py but unfortunately when i try to use keras-core i got error that no module named tensorflow.compat.v2 as tf 
My only goal is to use keras-core without tensorflow because i hear that keras-core support multi backend that's why i thought i can use keras-core even tensorflow is not installed but i try every way to change its backend to pytorch but nothing works plz help me plz respond me as soon as possible  plzzzz
