### ISSUE TITLE
Wheel for macosx_arm64

### ISSUE THREAD

**Issue by oliverweissl** [cython/cython#5904]
### Is your feature request related to a problem? Please describe.

Building a package, that relies on Cython it would be nice to have a pre-built wheel for macosx with the arm64 architecture instead of only x84_64.

I faced the issue when building a Cython module in my CI for multiple systems including macOS with arm64 and x84_64, where the CI cant build properly because it gets the x84_64 wheel for Cython, and therefore builds another wheel for x84_64 of my package. However it should build for arm64.

### Describe the solution you'd like.

My suspicion is that this can be resolved by adding a prebuilt Cython wheel for arm64, since I found similar issues on scipy that were resolved when this wheel was included in the releases.

### Describe alternatives you've considered.

However if you think this issue is not relevant to Cython please feel free to close the issue.

### Additional context
This issue is edited to reflect the problem better.

**Comment by scoder** [comment]
macOS ARM64 CPUs tend to be quite fast. I'm not sure it's worth providing binary wheels for this target.

Note that the installation is currently quicker than from a binary wheel because it uses the smaller Python-only wheels. The binary wheels are much larger and would need longer to download.

Is there a specific reason why you think this "would be nice" ?

**Comment by oliverweissl** [comment]
I faced the issue when building a Cython module in my CI for multiple systems including macOS with arm64 and x84_64, where the CI cant build properly because it gets the x84_64 wheel for Cython, and therefore builds another wheel for x84_64 of my package. However it should build for arm64. 

My suspicion is that this can be resolved by adding a prebuilt Cython wheel for arm64, since I found similar issues on scipy that were resolved when this wheel was included in the releases.

However if you think this issue is not relevant to Cython please feel free to close the issue.

**Comment by anthrotype** [comment]
+1 

All new macs nowadays use arm64 architecture. It's become standard for many python projects to provide "universal2" wheels (that contain both x64_86 and arm64 in the same binary) for macOS. https://cibuildwheel.readthedocs.io/en/stable/ makes it relatively easy to build these wheels among others.

**Comment by mhsmith** [comment]
The fix appears not to have worked, as there are still no macOS ARM64 wheels on PyPI for Cython 3.0.12.

**Comment by scoder** [comment]
Note that this ticket is targeted at Cython 3.1.
