### ISSUE TITLE
[BUG] async grpc  *** was never awaited

### ISSUE THREAD

**Issue by yfismine** [cython/cython#5925]
### Describe the bug

The example comes from the official example of grpc.
``` shell
git clone https://github.com/grpc/grpc.git
cd grpc/examples/python/helloworld
python setup.py build_ext
cd build/lib*
python  asyncio_server.py
python asyncio_client.py
```
![image](https://github.com/cython/cython/assets/53209596/810c9819-46b2-4daf-8e1e-b2e6d32a316c)
![image](https://github.com/cython/cython/assets/53209596/a7515afd-7b8a-4e5d-bcdc-43ef4cc2093f)

### Code to reproduce the behaviour:

```python
# setup.py
from distutils.core import setup
from Cython.Build import cythonize
setup(
    name="pyos",
    ext_modules=cythonize("./*.py"),
)

```
``` python
# async_server.py
import asyncio
from async_greeter_server import serve
asyncio.run(serve())
```
``` python
# async_client.py
from async_greeter_client import run
import asyncio
asyncio.run(run())
```

### OS

Linux

### Python version

3.8

### Cython version

3.0.7

**Comment by da-woods** [comment]
That looks like a grpc bug not a Cython bug. It looks like it tries to serialise something that it doesn't know how to serialise.

**Comment by yfismine** [comment]
> That looks like a grpc bug not a Cython bug. It looks like it tries to serialise something that it doesn't know how to serialise.

It can't be serialized because there is no await after cython compiles, which leads to a future, but I don't use cython to compile, and I don't use the original python example directly.

**Comment by scoder** [comment]
gprc needs to understand how to handle a Cython compiled function. Failures like this are often due to incorrect type checks. Please report the problem over there to make them adapt their code.
