### ISSUE TITLE
Compile of Django admin.py with django-mass-edit package creates error when saving

### ISSUE THREAD

**Issue by scrimpys** [cython/cython#5930]
### Describe the bug

When running .py code the Django-mass-edit package works as expected.  When I compile my .py code ( which includes admin.py) I get the following error: 

save_model() takes exactly 5 positional arguments (3 given)

### Code to reproduce the behaviour:

```cython
# example code
```
simply compile your Django project with Django-mass-edit installed.  Attempt to make a mass edit in the admin portion of the application and press save. The error appears after you press save.

### Expected behaviour

expect Django-mass-edit to work as it does when not compiled.

### OS

linux

### Python version

3.10.12

### Cython version

3.0.2

**Comment by scoder** [comment]
Thanks for the report. Please try the latest Cython release, and please provide a traceback of the failure, as well as any further information that might help diagnose the problem without setting up a Django system/app first. It would also help if you could provide step by step instructions how we can reproduce this.

**Comment by scrimpys** [comment]
Have tested latest version - 3.0.7.  Problem still occurs. 

Not sure how to provide the traceback.  The problem is reported in the GUI/Web page when I attempt to make changes to a field in my application. 

I have attached a sample application to demonstrate the problem.  Use username="sam" and password="Secret_123" to login to the admin screen ( <IP address>/admin ).  You can start the dev server using "python manage.py runserver 0:8000" from the pixel directory.

Further testing shows that the issue arrises when I create a custom save for my model.  It does not occur if I don't have a custom save mode.  The issue also only occurs only when I compile using Cython. 
[django_cython_error.tar.gz](https://github.com/cython/cython/files/13851677/django_cython_error.tar.gz)


The tar archive contains the Django project but you will likely need to install the requirements ( assume you will use a python venv).

The specific part of the code that causes the issue is in admin.py.


`   # sample save_model - note indentation not shown

   def save_model(self, request, obj, form, change):
        obj.save()
        print(change)
        if change:
            print("change", change, obj.id)
            if not os.path.isdir(f'/tmp/{obj.id}'):
                os.mkdir(f'/tmp/{obj.id}')
`

Again - this code only creates the issue when the project is compiled with Cython.  There is a setup.py file in the pixel directory that I used to compile the project with command "python setup.py build_ext --inplace"


Please let me know if there is anything else you need.

**Comment by scoder** [comment]
Looking through Django's code a bit, there seems to be a metaclass involved for this class: `MediaDefiningClass`. It doesn't touch this specific method, but at least, it changes the way the class is instantiated. The method itself seems to be very ordinary and overriding it shouldn't harm. Also, the fact that it says "3 arguments given" instead of 5 seems odd. If anything goes wrong with a method, it's usually off by one due to `self`, not off by two. Difficult to say what's going wrong here.

**Comment by da-woods** [comment]
Not a Cython bug - this is a choice that django-mass-edit has made:

https://github.com/burke-software/django-mass-edit/blob/8f455b1ee05e9d5b7b3e4e5094928b4397fc405b/massadmin/massadmin.py#L125

```
        for (varname, var) in self.get_overrided_properties().items():
            if not varname.startswith('_') and not isinstance(var, types.FunctionType):
                self.__dict__[varname] = var
```

Cython functions don't pass the check `isinstance(var, types.FunctionType)`, which checks for an regular Python function. Therefore your `CustomerAdmin.save_model` gets inappropriately copied over to overwrite `MassAdmin.save_model` and you end up in some sort of mess.

Cython functions are not regular Python functions by necessity. We made them look as much like Python functions as possible, but we can never pass an `isinstance` type check.

**Comment by da-woods** [comment]
If you want a reproducible example that doesn't use Cython then change your `CustomerAdmin` class to be:

```
class CustomerAdmin(...):  # put in the correct base class

    class Callable:
        def __call__(self, request, obj, form, change):
            ... # implementation of save_model goes here
    save_model = Callable()
```

This'll demonstrate the (roughly) same issue you see here.

**Comment by scoder** [comment]
> this is a choice that django-mass-edit has made

They might want to change the check to "callable()". Might be worth sending 
them a bug report if you want to make this work.
