### ISSUE TITLE
Documentation enhancement regarding "pure python mode" in the tutorial flow

### ISSUE THREAD

**Issue by matanster** [cython/cython#5943]
### Describe your issue

I had wondered what does Pure Python v.s. Cython mean in the code snippets of both the [3.1](https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html) and [3.0](https://cython.readthedocs.io/en/stable/src/tutorial/cython_tutorial.html) tutorial versions ― are they just two types of allowed syntax or is the "Pure Python" syntax a more limited subset of what one can do with "cython syntax" ―

Obviously that is well answered in https://cython.readthedocs.io/en/latest/src/tutorial/pure.html but _**may I suggest that the first pages refer to the latter for clarity and avoidance of doubt**_. 

On the same aspect though more specific, the tutorial pages from above refere to (quoting) "The cythonize version", but it remains a little vague (to me) which version of the code on that page this description refers to, or the term cythonize is just too ambiguous to be of help in a tutorial flow, at least for the rest of us limited humans out there. 

Thanks for all the hard work, and hope this helps infinitesimally.

**Comment by rraulf** [comment]
@matanox Thank you! Yes, it is still remains a little vague.

**Comment by scoder** [comment]
> It runs on the standard Python interpreter (CPython) and is generally slower because Python is an interpreted language and not compiled to machine code.

Except that it can be compiled with Cython and then gets the same performance characteristics as the corresponding code in extended Cython syntax. It's really just two different syntax variants for the same thing. Whether your code becomes faster or not does not depend on the syntax variant that you chose.

**Comment by scoder** [comment]
I reworded the text around the first examples to make the page more accessible. Comments welcome.
https://github.com/cython/cython/commit/ded34a59305b7e4753d6db1c4533b384b6800655

**Comment by da-woods** [comment]
> In the context of the code snippets from the Cython tutorial 
> 
> [...]
> 
> In summary, using Cython can significantly enhance the performance of Python code by compiling it into optimized C code, while Pure Python is simpler and more straightforward for general use.

@rraulf - That summary looks like it came from ChatGPT. It's obvious a useful tool, but it does often get things wrong. In this case it doesn't know that "pure Python mode" in Cython is another syntax for Cython (as @scoder points out).

My advice would be: be wary of trusting it too much.

(With that said, if we clarify the wording, maybe it'll do better once it's trained on the updated documentation...)
