### ISSUE TITLE
[BUG] Cython `@contextlib.contextmanager` unexpectedly turns StopIteration into a RuntimeError

### ISSUE THREAD

**Issue by godlygeek** [cython/cython#5953]
### Describe the bug

Given a pure Python context manager like:
```py
@contextlib.contextmanager
def nullcontext():
    yield
```
a `StopIteration` raised inside of the `with` block will propagate out.

If you implement that exact context manager in Cython instead, the `StopIteration` exception will be replaced with a `RuntimeError`.

### Code to reproduce the behaviour:

```shell-session
git clone https://gist.github.com/godlygeek/3b461adb37d99f77ba470d79745a5c2c /tmp/reproducer
cd /tmp/reproducer
python3 -m venv venv
. venv/bin/activate
pip install .
python test.py
```

### Expected behaviour

That reproducer installs a Python package with 2 modules. One is a pure Python module, the other is a Cython-compiled version of that same pure Python source. The `test.py` imports a context manager from each of them, and uses both in the same way. We should get the same output from both, but instead we see:
```text
--------------------------------------------------
testing py_nullcontext
caught StopIteration
--------------------------------------------------
testing cy_nullcontext
Traceback (most recent call last):
  File "/tmp/reproducer/test.py", line 11, in <module>
    raise StopIteration()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/reproducer/test.py", line 10, in <module>
    with func():
  File "/opt/bb/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "pymodule.py", line 5, in nullcontext
    yield
RuntimeError: generator raised StopIteration
```

### OS

Linux

### Python version

3.12.0

### Cython version

3.0.8

### Additional context

This is likely due to https://peps.python.org/pep-0479/ but something must be incorrect with the logic about when to apply it, seeing as how this results in a behavior difference from CPython.

**Comment by da-woods** [comment]
So I think the bit that's failing is https://github.com/python/cpython/blob/cce6ba91b3a0111110d7e1db828bd6311d58a0a7/Lib/contextlib.py#L174

```
            if (
                    isinstance(value, StopIteration)
                    and exc.__cause__ is value
                ):
```

You can reproduce this by compiling the following in Cython

```
def nullcontext():
    yield
```

and then in Python doing:

```
g = nullcontext()
next(g)
si = StopIteration()
try:
    g.throw(StopIteration, si, None)
except RuntimeError as e:
    e2 = e
```

With both Python and Cython versions of `nullcontext` you get your `e2 == RuntimeError("generator raised StopIteration")` but in the CYthon version `e2.__cause__` is set to `None` for reasons I don't really understand.

**Comment by da-woods** [comment]
I think it just needs the cause setting in https://github.com/cython/cython/blob/0e1026cb7c767450a88ab822e8eda2b451dee3c6/Cython/Utility/Coroutine.c#L303 rather than relying on the implicit chaining
