### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by foreso-GitHub** [cython/cython#5969]
### Describe the bug

Hi,

I compiled python code which contains fastapi_jsonrpc.  But when I run the pyd, a error orrurs.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test\\test2.py", line 5, in init test2
  File "C:\Users\aaa\.conda\envs\ks_cta_test\lib\site-packages\fastapi_jsonrpc\__init__.py", line 1236, in __init__
    self.callee_module = inspect.getmodule(inspect.stack()[1][0]).__name__
AttributeError: 'NoneType' object has no attribute '__name__'

### Code to reproduce the behaviour:

```cython
# example code

import uvicorn
import fastapi_jsonrpc as jsonrpc

APP_JSONRPC = jsonrpc.API()
APP_JSONRPC_V1 = jsonrpc.Entrypoint('/api/v1/jsonrpc')
APP_JSONRPC.bind_entrypoint(APP_JSONRPC_V1)
uvicorn.run(APP_JSONRPC,  host='127.0.0.1', port=8900, access_log=False)


```

### Expected behaviour

If I just run above codes in pure python environment, it works.  I hope it can run properly by cython pyd too.

### OS

Windows 10

### Python version

3.8.18

### Cython version

3.0.8

### Additional context

Thanks for help!

**Comment by da-woods** [comment]
https://cython.readthedocs.io/en/latest/src/userguide/limitations.html#stack-frames

This is a documented limitation of Cython that we don't generate stack frames for inspect as we go. This is unlikely to change in the near future I think.

I don't know of an obvious workaround.

**Comment by foreso-GitHub** [comment]
@da-woods Got it, thanks for the information!

**Comment by foreso-GitHub** [comment]
Close the issue.
