### ISSUE TITLE
Unterminated string literal causes cython compiler to go into an infinite loop.

### ISSUE THREAD

**Issue by culler** [cython/cython#5977]
### Describe the bug

Running `cythonize bug.pyx`  on the following file bug.pyx hangs:

```cython
# cython: language_level=3str

class Bug():
    """Cythonizing this creates an infinite loop."""

    something = "hello"
    
    def dumb(self):
        print("Say something: %s'%self.something)
 
# Local Variables:
# mode: Python
# End
```

The traceback produced by hitting Control-C says:
```
Dependencies.py", line 509, in parse_dependencies
    source, literals = strip_string_literals(source)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/culler/Library/Python/3.12/lib/python/site-packages/Cython/Build/Dependencies.py", line 349, in strip_string_literals
    while True:
          ^^^^
```

### Code to reproduce the behaviour:

```bash
cythonize bug.pyx
```

### Expected behaviour

An error message saying that the file contains an unterminated string literal.

### OS

linux and macOS, at least

### Python version

3.10 on linux and 3.12 on macOS

### Cython version

3.0.8

**Comment by scoder** [comment]
Thanks for the report and the reproducer. That function was bound to be reimplemented at some point, so I just did that in https://github.com/cython/cython/pull/5994.

**Comment by culler** [comment]
Thanks!!!
