### ISSUE TITLE
[BUG] Incompatible pointer in inlined method of derived class

### ISSUE THREAD

**Issue by sergiopasra** [cython/cython#6033]
### Describe the bug

cython is generating C code that produces an "incompatible-pointer-types" when compiled with gcc. The problem appears in inlined methods of a derived class.

In the folloing code, the method `Derived.fun1` receives a `Base*` where the method expects a `Derived*`

### Code to reproduce the behaviour:

```cython
# example code
cdef class Base:
    cdef double fun1(self):
        return 100

    cdef double fun2(self):
        return 100


cdef class Derived(Base):
    # If this method is not inlined, the error disappears
    cdef inline double fun1(self):
        return 200

    # Without this method, the error disappears also
    cdef double fun2(self):
        return self.fun1()




```

### Expected behaviour

The code compiles without warnings

### OS

Linux Fedora

### Python version

3.11

### Cython version

3.1.0a0

### Additional context

This warning appears when compiling scikit-learn in Fedora to create rpm packages.

https://bugzilla.redhat.com/show_bug.cgi?id=2261602

This problem affects only the next release in developement (Fedora 40) where `incompatible-pointer-types` are treated as errors (following this https://fedoraproject.org/wiki/Changes/PortingToModernC).

In previous releases, the warning appears but it doesn't prevent scikit-learn from compiling

**Comment by QuLogic** [comment]
Possibly related to #2747 in some way.

**Comment by scoder** [comment]
>Possibly related to #2747 in some way.

Yes, this is a duplicate.
