### ISSUE TITLE
[ENH] Conditional Compilation

### ISSUE THREAD

**Issue by YoSTEALTH** [cython/cython#6058]
### Is your feature request related to a problem? Please describe.

Does Cython have anything like this https://doc.rust-lang.org/rust-by-example/attribute/cfg.html#cfg ? I have lots of function that need to meet Linux kernel version to be compiled.

**Comment by scoder** [comment]
It used to have something like this, but these things are really best done by writing simple C shims for the conditional functionality.

https://docs.cython.org/en/latest/src/userguide/external_C_code.html#including-verbatim-c-code

**Comment by YoSTEALTH** [comment]
Is there any way to add these features to Cython itself? Defining C in Cython while wrapping a library you don't control can only go so far... to do it properly you endup writing more C code than what you are trying to wrap! Main reason I choose Cython was because I didn't want to write C.
