### ISSUE TITLE
[BUG] Regression in cython 3.0.9

### ISSUE THREAD

**Issue by h-vetinari** [cython/cython#6066]
### Describe the bug

While building pyarrow [15.0.0](https://github.com/conda-forge/arrow-cpp-feedstock/pull/1335) resp. [14.0.2](https://github.com/conda-forge/arrow-cpp-feedstock/pull/1336) in conda-forge, we got a regression going from cython 3.0.8 to 3.0.9

```
[5/141] Compiling Cython CXX source for lib...
FAILED: CMakeFiles/lib_pyx $SRC_DIR/python/build/temp.linux-x86_64-cpython-310/CMakeFiles/lib_pyx 
cd $SRC_DIR/python/build/temp.linux-x86_64-cpython-310 && $PREFIX/bin/python -m cython --cplus --warning-errors --directive embedsignature=True --working /home/conda/feedstock_root/build_artifacts/apache-arrow_1709883667824/work/python --output-file $SRC_DIR/python/build/temp.linux-x86_64-cpython-310/lib.cpp $SRC_DIR/python/pyarrow/lib.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    if schema.release != NULL:
        schema.release(schema)

    free(schema)

cdef object alloc_c_schema(ArrowSchema** c_schema) noexcept:
                          ^
------------------------------------------------------------

pyarrow/types.pxi:5248:26: noexcept clause is ignored for function returning Python object

Error compiling Cython file:
------------------------------------------------------------
...
    if array.release != NULL:
        array.release(array)

    free(array)

cdef object alloc_c_array(ArrowArray** c_array) noexcept:
                         ^
------------------------------------------------------------

pyarrow/types.pxi:5267:25: noexcept clause is ignored for function returning Python object

Error compiling Cython file:
------------------------------------------------------------
...
    if stream.release != NULL:
        stream.release(stream)

    free(stream)

cdef object alloc_c_stream(ArrowArrayStream** c_stream) noexcept:
                          ^
------------------------------------------------------------

pyarrow/types.pxi:5286:26: noexcept clause is ignored for function returning Python object
```

This happens across all platforms & arches. Going back to 3.0.8 fixes the build again.

### Code to reproduce the behaviour:

Build [pyarrow](https://github.com/apache/arrow) with cython 3.0.9

### Expected behaviour

Build passes

### OS

Linux, macOS, Windows

### Python version

3.8-3.12

### Cython version

3.0.9

**Comment by scoder** [comment]
This is not a regression. It's a new warning that we added, and I think you treat warnings as errors?

Just remove the noexcept. Function calls returning Python objects *always* check for exceptions, so the noexcept is wrongly used here.

**Comment by h-vetinari** [comment]
OK. I called it a regression because it's the first 3.0.x patch release to break anything. It's definitely a breaking change relative to what passed compilation before, which is unexpected to me in a patch version, so I don't exactly know what to call it if not a regression.

But if this is something to be fixed in arrow, feel free to close this issue. That just means we'll stay on cython 3.0.8 until this has been fixed upstream.

**Comment by h-vetinari** [comment]
> I think you treat warnings as errors?

Yeah, you're right, this uses `--warning-errors`; this comes from upstream, though I agree that breakage due to treating-warnings-as-errors is not a regression. If you cannot change warning behaviour in patch releases, it's really too much of a constraint to move forward. I'll raise this on the arrow side. Sorry for the noise.
