### ISSUE TITLE
Document compilation caching?

### ISSUE THREAD

**Issue by pitrou** [cython/cython#6070]
### Describe your issue

I notice that Cython seems to have a ccache-like feature that is disabled by default and that does not seem documented. 
https://github.com/cython/cython/blob/f3cad15100da00936b3ac31865c28d22eb95c108/Cython/Compiler/Options.py#L671-L672

Unless there is a definite reason for not expose it to end users (though it does seem [tested](https://github.com/cython/cython/blob/master/Cython/Build/Tests/TestCyCache.py)), it would be nice to document it.

**Comment by scoder** [comment]
Hmm, right. That seems worth documenting. I can imagine that it can make a real difference for large projects, as it apparently did for Sagemath at the time (for which it seems to have been implemented).

There are two options: `cache` allows enabling the cache by setting it to either `True` or the path of a cache directory, and `cache_size` allows to change the maintained size of the LRU cache.

**Comment by pitrou** [comment]
By the way, I'm not sure it's related, but I see a subdirectory `.cython/inline` on my machine, and the only file it contains seems to have been generated by 0.28a0. Is it failed experiment?

**Comment by pitrou** [comment]
And if I add `# cython: cache = True` inside a source file, it seems ignored (nothing appears in `.cython`).

**Comment by scoder** [comment]
`cythonize` is a "do it all in one go" kind of tool, whereas `cython` (or `python -m cython`) is a "translate a single file and let me do the rest" tool. Both have their use cases.

And yes, it seems that `cache` is not available from the command line of the `cython` tool. It's a compile option, not a directive that you can set from a source file.

Unknown directives should get rejected, though, and not pass silently.

**Comment by matusvalo** [comment]
> And yes, it seems that cache is not available from the command line of the cython tool. It's a compile option, not a directive that you can set from a source file.

Yes but it is more complicated. Cache is hardwired into cythonize code so it is not just adding new option to `cython`. We need to extract cache code to separate module and integrate it in both `cython` and `cythonize` or more deeper in common compilation code. Cannot tell right now what is better out of blue.

**Comment by scoder** [comment]
> Cache is hardwired into cythonize code so it is not just adding new option to `cython`.

That makes sense, given the different nature and complexity of both tools.

**Comment by matusvalo** [comment]
> It would be nice if some way of enabling cache from the cython command (or a global config file) was available. 

I have created PR adding cache support to cython command - see #6091

**Comment by pitrou** [comment]
Thanks a lot @matusvalo, this is great. I hope we can make good use of it in PyArrow.
