### ISSUE TITLE
[BUG] Bug with limited API support in trivial program involving float literal

### ISSUE THREAD

**Issue by vyasr** [cython/cython#6093]
### Describe the bug

Float literals in equality comparison operators in limited API mode trigger some unsupported code path. Oddly, the compile error comes extremely early, in the include of Python.h itself, which made me slightly suspect a potential error in CPython's own limited API support. However, other operators (e.g. inequality comparisons) do not trigger the error, and neither do integer comparisons, which makes me think that it's more likely that the cause is something Cython itself is doing to generate invalid code that somehow triggers this path. Unfortunately, I can't quite pin down what it is.

I'll note that I also see different failure modes depending on whether I compile the Cython module as C or C++. When compiling in C++, I see this:
```
/home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/coder/.conda/envs/rapids/include -fPIC -O2 -isystem /home/coder/.conda/envs/rapids/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/coder/.conda/envs/rapids/include -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/coder/.conda/envs/rapids/include -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs -fPIC -DPy_LIMITED_API=0x030B0000 -DCYTHON_LIMITED_API -I/home/coder/.conda/envs/rapids/include/python3.11 -c test.cpp -o build/temp.linux-x86_64-cpython-311/test.o
In file included from /home/coder/.conda/envs/rapids/include/python3.11/Python.h:55,
                 from test.cpp:41:
/home/coder/.conda/envs/rapids/include/python3.11/floatobject.h: In function 'PyObject* __Pyx_PyFloat_EqObjC(PyObject*, PyObject*, double, int, int)':
/home/coder/.conda/envs/rapids/include/python3.11/floatobject.h:14:26: error: 'PyFloat_Type' has incomplete type
   14 | PyAPI_DATA(PyTypeObject) PyFloat_Type;
      |                          ^~~~~~~~~~~~
In file included from /home/coder/.conda/envs/rapids/include/python3.11/Python.h:42,
                 from test.cpp:41:
/home/coder/.conda/envs/rapids/include/python3.11/pytypedefs.h:20:16: note: forward declaration of 'PyTypeObject' {aka 'struct _typeobject'}
   20 | typedef struct _typeobject PyTypeObject;
```

When compiling in C, I instead see this:
```
/home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/coder/.conda/envs/rapids/include -fPIC -O2 -isystem /home/coder/.conda/envs/rapids/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/coder/.conda/envs/rapids/include -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/coder/.conda/envs/rapids/include -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs -fPIC -DPy_LIMITED_API=0x030B0000 -DCYTHON_LIMITED_API -I/home/coder/.conda/envs/rapids/include/python3.11 -c test.c -o build/temp.linux-x86_64-cpython-311/test.o
test.c: In function '__Pyx_PyFloat_EqObjC':
test.c:6745:37: error: invalid use of incomplete typedef 'PyTypeObject' {aka 'struct _typeobject'}
 6745 |                         PyFloat_Type.tp_richcompare(op2, op1, Py_EQ));
```

### Code to reproduce the behaviour:

```cython
# test.pyx
x = 1
# x = 1.0  # This is also fine

x == 1.0  # This will raise an error regardless of which line is used above
# x < 1.0  # This will not raise an error
# x == 1  # This will not raise an error

# setup.py
from setuptools import Extension, setup
from Cython.Build import cythonize

extensions = [
    Extension(
        "test", ["test.pyx"],
        define_macros=[("Py_LIMITED_API", "0x030B0000"), ("CYTHON_LIMITED_API", None)],
        language="c++",  # This changes the error
    )
]

setup(
    name='test',
    ext_modules=cythonize(extensions),
)
```

### Expected behaviour

This code should compile

### OS

Linux

### Python version

3.11.8

### Cython version

Merge of #6061 and the limited API branch from #6082

### Additional context

There is also a separate limited API issue with `PyList_GET_ITEM` that I observe in the above MWE, but I've fixed that in #6061.

**Comment by da-woods** [comment]
The upshot is that we can't use `PyFloat_Type` because it's opaque. The C compiler knows that it exists but doesn't know what's in it.

`__Pyx_PyFloat_EqObjC` (and related functions) are largely just optimisations. As a fallback they could just be replaced with the standard PyObject comparison in the limited API.

I suspect in case we could use `__Pyx_PyType_GetSlot` on `PyFloat_Type`. This should end up equivalent to the current code normally, and something slightly less efficient but valid in the limited API.

**Comment by vyasr** [comment]
I figured out the opaque struct bit, what I was having trouble understanding is what code gen cython is doing to produce the invalid code. The error is coming up right after the limited api macros are defined and python.h is included, so almost none of the cython generated code has been hit. How is what cython doing triggering this error from just the include of python.h?

**Comment by da-woods** [comment]
The error is the line

```
PyFloat_Type.tp_richcompare(op2, op1, Py_EQ));
```

All the other messages are just telling you that `PyFloat_Type` is an incomplete type and is defined in "Python.h". They're informational.

**Comment by vyasr** [comment]
Ah right I didn't look at the C traceback nearly closely enough, sorry about that. Any idea why the issue is so obscured in the C++ traceback? I do see the
```
/home/coder/.conda/envs/rapids/include/python3.11/floatobject.h: In function 'PyObject* __Pyx_PyFloat_EqObjC(PyObject*, PyObject*, double, int, int)':
```
which is the function you mentioned as being an optimization, but I don't see the equivalent obvious error line indicating _where_ the incomplete type is being used. Apologies if this is obvious to see, I suspect that I'm having trouble tracing because I'm not accustomed to using macros nearly to the extent used in the Cython/CPython code bases and they make tracebacks harder to follow.

**Comment by da-woods** [comment]
I'm going off the C traceback instead. I think they're expressing the same issue in slightly different ways. I can't actually see the relevant line in the C++ traceback you've posted.
