### ISSUE TITLE
[BUG] cppclass inheritance does not work with overloaded methods

### ISSUE THREAD

**Issue by dgrunwald** [cython/cython#6106]
### Describe the bug

Inheritance in a cppclass inherits only one of the overloads not all of them:

### Code to reproduce the behaviour:

```cython
cdef extern from *:
	"""
	class Base
	{
	public:
		const char *instance_method(int x) { return "Base::instance_method(int)"; }
		const char *instance_method(int x, int y) { return "Base::instance_method(int, int)"; }
	};

	class Derived : public Base
	{
	};
	"""
	cppclass Base:
		const char* instance_method(int x)
		const char* instance_method(int x, int y)

	cppclass Derived(Base):
		pass

def test():
	cdef Derived d
	assert d.instance_method(1) == 'Base::instance_method(int)'
	assert d.instance_method(1, 2) == 'Base::instance_method(int, int)'
```

### Additional context

```
def test():
        cdef Derived d
        assert d.instance_method(1) == 'Base::instance_method(int)'
                         ^
------------------------------------------------------------

cpp_method_inheritance.pyx:46:25: Call with wrong number of arguments (expected 2, got 1)
```

**Comment by dgrunwald** [comment]
I have a patch for this problem and for #5741.
I will create a pull request once I have corporate approval.

**Comment by da-woods** [comment]
This may possibly be fixed by https://github.com/cython/cython/pull/3235 (which I intended to merge and haven't quite got round to).

I'll investigate that and let you know.

**Comment by da-woods** [comment]
Closed in https://github.com/cython/cython/commit/3d41922a23793fef61eba6b51b779d24bac9a1f1. Hopefully you didn't spend too long fixing it yourself. If you have any improvements to the current version then do let us know though.
