### ISSUE TITLE
[ENH] Improve Cython install speed from source

### ISSUE THREAD

**Issue by YoSTEALTH** [cython/cython#6116]
It takes a long time to install Cython from source. I found this helps:
`python3 -m pip install --upgrade --config-setting="--build-option=build_ext -j4" git+https://github.com/cython/cython/`

Maybe this can be added to https://docs.cython.org/en/latest/src/quickstart/install.html

**Comment by scoder** [comment]
Yeah, it's sad that this option isn't automatic in setuptools, and also can't be set via environment variables, pip option, etc.

That said – almost no-one needs to install Cython from sources. There are a few CI setups in third-party projects that do this, but almost everyone should be happy with the binary and Python wheels that we provide for releases.

Is there a reason why you do this often enough to consider it annoying?

**Comment by YoSTEALTH** [comment]
This would only be for developers that want to try out latest Cython that doesn't have pre-built wheel yet. Like people that submit PR or want to test out the new bug fix...

**Comment by scoder** [comment]
Well, for these cases, the fastest way to install Cython is (and probably will always be) as a pure Python package, without compiled modules.

**Comment by YoSTEALTH** [comment]
O, you mean `NO_CYTHON_COMPILE=true python3 -m pip install --upgrade git+https://github.com/cython/cython/` that is interesting. I didn't think you went to such extreme to make pure python version as well. That works as well.
