### ISSUE TITLE
[BUG] C Marco not populating value!

### ISSUE THREAD

**Issue by YoSTEALTH** [cython/cython#6145]
### Describe the bug

After wrapping C Macro, the values are not being populated into Cython/Python side.

### Code to reproduce the behaviour:

``` c
#define io_uring_for_each_cqe(ring, head, cqe)				\
	/*								\
	 * io_uring_smp_load_acquire() enforces the order of tail	\
	 * and CQE reads.						\
	 */								\
	for (head = *(ring)->cq.khead;					\
	     (cqe = (head != io_uring_smp_load_acquire((ring)->cq.ktail) ? \
		&(ring)->cq.cqes[io_uring_cqe_index(ring, head, (ring)->cq.ring_mask)] : NULL)); \
	     head++)							\


```

``` cython

# defined it as so
void __io_uring_for_each_cqe 'io_uring_for_each_cqe'(
        __io_uring* ring,
        unsigned int head,
        __io_uring_cqe* cqe)
```

``` cython
# cpdef function 
cpdef unsigned int io_uring_for_each_cqe(io_uring ring, io_uring_cqe cqe):
    cdef unsigned int    head=0
    __io_uring_for_each_cqe(&ring.ptr, head, cqe.ptr)
    return head

```

``` python
# calling in Python
import liburing


cqe = liburing.io_uring_cqe()
ring = liburing.io_uring()
liburing.io_uring_queue_init(4, ring)
try:
    sqe = liburing.io_uring_get_sqe(ring)
    liburing.io_uring_prep_nop(sqe)
    sqe.user_data = 1

    sqe = liburing.io_uring_get_sqe(ring)
    liburing.io_uring_prep_nop(sqe)
    sqe.user_data = 2

    liburing.io_uring_submit_and_wait_timeout(ring, cqe, 2)

    head = liburing.io_uring_for_each_cqe(ring, cqe)
    print()
    print('head:', head)  # head: 2
    print('cqe:', cqe.res)
    # MemoryError: `cqe.ptr` is NULL
    # or
    # Segfault
finally:
    liburing.io_uring_queue_exit(ring)
```

**Comment by da-woods** [comment]
I'd suggest writing a small inline C function that calls the macro with a signature of

```
void inline_function(
        __io_uring** ring,
        unsigned int* head,
        __io_uring_cqe** cqe)
```

instead

**Comment by YoSTEALTH** [comment]
I am not sure what Cython does internally. All I want is to see results like:
``` python
print(cqe.res) # should return `0`
print(cqe.user_data) # should return either `1` or `2`
```
Which doesn't seem to be happening! As you can see `head` returns `2` so we can tell that function/wrapper itself is working to some extent.

This is now the `io_uring_for_each_cqe` function is used in C side https://github.com/axboe/liburing/blob/master/examples/proxy.c#L1949-L1954

**Comment by scoder** [comment]
The problematic part is the assignment to `head` and `cqe` inside of the macro:
> ```c
> head = *(ring)->cq.khead;					\
> cqe = (head != io_uring_smp_load_acquire((ring)->cq.ktail) ? \
> ```
Here, the macro is assuming that the assignment has an effect in the outside world, which may not be the case, depending on what `head` and `cqe` are. If they are stored in temporary variables, then there will not be a re-assignment back to where their values were originally taken from. It's the kind of macro that should generally be avoided because it has several side-effects and makes implicit assumptions that may or may not apply.

As @da-woods suggested, wrap it in an actual function instead.

**Comment by YoSTEALTH** [comment]
Ended up writing bellow code and its working!!! Thank you so much @da-woods, glad its finally working. I been at it for couple of days now. Though its really frustrating not being able to solves these problems within Cython itself and having to do these monkey patch with C code seem abnormal!

It would be nice if you guys enabled **Discussions** option on GitHub so people can talk about Cython.

``` cython

'''
    static inline void inline_function(struct io_uring* ring,
                                       unsigned int head,
                                       struct io_uring_cqe* cqe)
    {
        io_uring_for_each_cqe(ring, head, cqe);
    }
'''

void inline_function(__io_uring* ring, unsigned int head, __io_uring_cqe* cqe)


cpdef unsigned int io_uring_for_each_cqe(io_uring ring, io_uring_cqe cqe):
    cdef unsigned int   head=0
    inline_function(&ring.ptr, head, cqe.ptr)
    return head

```

**Comment by YoSTEALTH** [comment]
@scoder p.s. `cqe` reference to memory is actually managed be the C library `ring` itself, that's probably why the author is ok with reassigned `cqe = (head ...` as they do.
