### ISSUE TITLE
[BUG] Function pointer casting not working properly

### ISSUE THREAD

**Issue by oddbookworm** [cython/cython#6212]
### Describe the bug

I'm trying to perform a cast because of a portmidi change that broke some of our ancient code, and casting doesn't work when I do it in the cython, but if I generate the cython without the cast then cast in the generated C code, it works fine

### Code to reproduce the behaviour:

snippets from cython
```cython
# typedefs
ctypedef long PmTimestamp
ctypedef PmTimestamp(*PmTimeProcPtr)(void *time_info)

# function declarations
PtTimestamp Pt_Time()
PmError Pm_OpenInput(*unimportant args*, PmTimeProcPtr time_proc, *other unimportant args*)

...

# call that throws the error
err = Pm_OpenInput(..., <PmTimeProcPtr>(&Pt_Time), ...)
```

Cython error:
```
Cannot assign type 'PmTimeProcPtr' (alias of 'PmTimestamp (*)(void *) noexcept') to 'long (*)(void) noexcept')
```

Modified generated C code that does compile
```
__pyx_v_err = Pm_OpenInput((&__py_v_self->midi), __pyx_t_2, NULL, __pyx_t_3, (PmTimeProcPtr)&Pt_Time, NULL);
```
All I did was add the cast of `&Pt_Time` to `PmTimeProcPtr`

### Expected behaviour

Cython is able to perform the cast because C can do it

### OS

Tested on windows and linux

### Python version

3.11, 3.12

### Cython version

3.0.0, 3.0.10

### Additional context

The particular library is pygame-ce, and the particular lines in question are [these lines](https://github.com/pygame-community/pygame-ce/blob/main/src_c/cython/pygame/pypm.pyx#L544-L545)

**Comment by matusvalo** [comment]
Unfortunately, I cannot replicate the issue. I tried to reconstruct the example but it compiled successfully. When I tried to compile module directly from pygame-ce I was able to compile it too (cython 3.0.10):

```bash
wget https://raw.githubusercontent.com/pygame-community/pygame-ce/main/src_c/cython/pygame/pypm.pyx

cython -3 pypm.pyx # this command was successful.
```

**Comment by oddbookworm** [comment]
I need to pay better attention when people respond to me..

Right about the time I opened this issue, we merged our own fix because we needed to keep our builds going. I can create a custom branch in the next couple days that reverts our shim

**Comment by oddbookworm** [comment]
I've created a pull request [here](https://github.com/pygame-community/pygame-ce/pull/2981) that has the fix reverted. Hopefully there will actually be some build failures in our CI, otherwise I'll play around with it more over the next week or so to try to reproduce it again

**Comment by oddbookworm** [comment]
The branch in particular that I created for the revert is https://github.com/oddbookworm/pygame-ce/tree/revert-cython-shim

**Comment by ankith26** [comment]
My hunch is that it is a C compiler bug not a cython bug (which probably affects some gcc versions and not all?)

atleast I couldn't repo the error myself, nor does CI repro the error (but the CI is on an old compiler version)

**Comment by oddbookworm** [comment]
I'm still able to reproduce it using the branch I created now that I'm back on the laptop I originally had. Here's my config:
```
>>> gcc --version
gcc (GCC) 14.1.1 20240522
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>>> cython --version
Cython version 3.0.10

>>> python --version
Python 3.12.4

>>> pip --version
pip 24.0 from /home/andrew/Projects/pygame-ce/venv/lib/python3.12/site-packages/pip (python 3.12)
```

meson build log
[meson-log.txt](https://github.com/user-attachments/files/16137977/meson-log.txt)

**Comment by oddbookworm** [comment]
Oh interestingly, downgrading gcc and gcc libs to sub-14.0 worked

**Comment by oddbookworm** [comment]
Alright, I think this can be closed. I'm not sure cython has anything they can do here, or if this is even a compiler bug, maybe it's an intended change. I dunno, not sure how I can repro it with pure gcc to report it there
