### ISSUE TITLE
Codespell currently failing on CI

### ISSUE THREAD

**Issue by da-woods** [cython/cython#6220]
### Describe your issue

It's started complaining a lot about `assertIn` and similar. Unsurprisingly this has affected other people https://github.com/codespell-project/codespell/issues/3430 so I expect will be fixed pretty quickly. I think it's best to ignore it and wait for it to be fixed elsewhere.

**Comment by scoder** [comment]
I fixed some issues in https://github.com/cython/cython/commit/101d2a2b640250b48cde88073621d2587f3373b8
