### ISSUE TITLE
[BUG] Use of `Py_LIMITED_API` sometimes results in references to nonexistent `PyTuple_SET_ITEM` function

### ISSUE THREAD

**Issue by phlummox** [cython/cython#6244]
### Describe the bug

Use of `Py_LIMITED_API` sometimes results in implicit declaration of `PyTuple_SET_ITEM` function, and consequent `ImportError` when importing.

When the code below is built with  `python3 setup.py build_ext --inplace`, the following warning is emitted:

```
my_module.c: In function ‘__pyx_pf_9my_module_my_function’:
my_module.c:2246:3: warning: implicit declaration of function ‘PyTuple_SET_ITEM’; did you mean ‘PyTuple_SetItem’? [-Wimplicit-function-declaration]
 2246 |   PyTuple_SET_ITEM(__pyx_t_1, 0, __pyx_v_firstword);
      |   ^~~~~~~~~~~~~~~~
      |   PyTuple_SetItem
```

And if an attempt is made to import and use the function from the built .so file, using `python3 -c 'import my_module as mm; print(mm.my_function())'`, the following error is emitted:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/user/cython_bug/my_module.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyTuple_SET_ITEM
```

### Code to reproduce the behaviour:

Cython code (`my_module.pyx`):

```cython
# cython: language_level=3

def my_function():
    firstword = "greetings"
    mesg = f"{firstword} {firstword}"
    return 42
```

`setup.py` script:

```python
from setuptools import setup, Extension
from Cython.Build import cythonize

extensions = [
    Extension(
        name="my_module",
        sources=["my_module.pyx"],
        language="c",
        extra_compile_args=["-DCYTHON_LIMITED_API=1",
                            "-DPy_LIMITED_API=0x030a0000",
                            ],
    )
]

setup(
    name="my_cython_project",
    version="0.1",
    description="A sample Cython project",
    packages=["my_module"],
    ext_modules=cythonize(extensions),
)
```

### Expected behaviour

When `-DCYTHON_LIMITED_API=1` and `-DPy_LIMITED_API=0x030a0000` are passed as compiler options, generated code should't refer to undeclared functions.

It should be possible to build a shared library with `python3 setup.py build_ext --inplace`, and then import and use it with `python3 -c 'import my_module as mm; print(mm.my_function())'`.

(At which point, the result "42" should be printed, in this case.)

### OS

Linux

### Python version

3.10.12 (but also occurs for Python 3.11.9)

### Cython version

3.0.10

### Additional context

The generated code constructs a tuple, and then attempts to set elements of the tuple using code like this:

```c
  PyTuple_SET_ITEM(__pyx_t_1, 0, __pyx_v_firstword);
```

But `PyTuple_SET_ITEM` never gets declared, if the `-DCYTHON_LIMITED_API=1` and
`-DPy_LIMITED_API=0x030a0000` options are passed to the Cython compiler. (The code compiles without error if those options are not passed: but then the built .so file can't be used with other versions of Python.)

The call to `PyTuple_SET_ITEM` is generated due to the following bit of Python code:

```python
  mesg = f"{firstword} {firstword}"
```

If the line is removed, or the f-string changed to just `f"{firstword} "`, that call no longer gets generated.

**Comment by da-woods** [comment]
It's worth trying with the master branch (or the limited-api-preview branch which also contains a few unmerged PRs). The master branch has significant improvements in the limited API (but still isn't perfect).

The 3.0 branch only has absolutely minimal support for the limited API - while there are modules that compile, they don't do a lot.

Improvements to the limited API are going in the master branch rather than the 3.0 release branch so if the limited API is important to you then you'll have to use that for now.

**Comment by da-woods** [comment]
I'll close this because I'm reasonably sure that f-strings are fixed in master. But do let me know if you try it and it isn't true.

**Comment by phlummox** [comment]
I'll give the master branch a go - cheers.

**Comment by phlummox** [comment]
Can confirm that this bug is fixed in master :)

But hopefully this report will be useful to anyone else encountering the same problem. I was just using the latest release, not realizing `master` would be the better option.
