### ISSUE TITLE
[BUG] Issue after upgrading to Cython 3.0.10

### ISSUE THREAD

**Issue by bjmarfito** [cython/cython#6245]
### Describe the bug

When I tried to run the compiled Cython code it outputs this error: `ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/isce/components/contrib/alos2proc_f/alos2proc_f.so, 0x0002): symbol not found in flat namespace '_PyUnstable_Code_NewWithPosOnlyArgs'`

### Code to reproduce the behaviour:

```cython
# example code
```

### OS

macOS

### Python version

3.11.9

### Cython version

3.0.10

**Comment by da-woods** [comment]
`PyUnstable_Code_NewWithPosOnlyArgs` is used in one place in Cython, but only for Python versions 3.12 and above.

https://github.com/cython/cython/blob/7ae85318297ed306b84ecc72d0279e27090b25f3/Cython/Utility/ModuleSetupCode.c#L812-L816

Therefore you should not need it on Python 3.11.

My suspicion is that you're trying to use a module that was compiled for Python 3.12 on Python 3.11. But it's hard to know what you're doing

**Comment by da-woods** [comment]
Normally you'd expect the filename to be something like `alos2proc_f.cpython-311.so` to avoid this kind of version mix-up, but whatever build system is being used is clearly avoiding doing that
