### ISSUE TITLE
[BUG] when multiple .pyx files cimport the same .pxd file, and cythonize these  extensions at the same time, bug occurs

### ISSUE THREAD

**Issue by monchin** [cython/cython#6274]
### Describe the bug

If I have 2 extensions in one `setup.py`, and the 2 extensions cimport the same `.pxd` file, an error `TypeError: '<' not supported between instances of 'dict' and 'dict'` will occurs

### Code to reproduce the behaviour:

Let's say we have a dir
```
test_cython
├── __init__.py
├── __pycache__
├── cpp
│   ├── include
│   │   ├── a.h
│   │   └── b.h
│   └── src
│       ├── a.cpp
│       └── b.cpp
└── cython
    ├── aa.pxd
    ├── aa.pyx
    ├── bb.pxd
    ├── bb.pyx
    ├── share.pxd
    └── share.pyx
```
```cpp
// a.h
class A {
    int a;
public:
    int get_a();
};

// b.h
class B {
    int b;
public:
    int get_b();
};

// a.cpp
#include "a.h"
int A::get_a() {
    return a;
}

// b.cpp
#include "b.h"

int B::get_b() {
    return b;
}
```

```cython
# aa.pxd
cdef extern from "a.h":
    cdef cppclass A:
        A()
        int get_a()

# bb.pxd
cdef extern from "b.h":
    cdef cppclass B:
        B()
        int get_b()

# share.pxd
cdef class Shrubbery:
    cdef int width
    cdef int length

# share.pyx
# distutils: language = c++
cdef class Shrubbery:
    def __init__(self, int w, int l):
        self.width = w
        self.length = l

def standard_shrubbery():
    return Shrubbery(3, 7)

# aa.pyx
# distutils: language = c++

from aa cimport A
from share cimport Shrubbery
import share
cdef class PyA:
    cdef A ca

    def __cinit__(self):
        self.ca = A()

    def test(self):
        self.ca.get_a()
        cdef Shrubbery sh
        sh = share.standard_shrubbery()
        print("Shrubbery size is", sh.width, 'x', sh.length)

# bb.pyx
# distutils: language = c++

from bb cimport B
from share cimport Shrubbery
import share
cdef class PyB:
    cdef B ca

    def __cinit__(self):
        self.cb = B()

    def test(self):
        self.cb.get_b()
        cdef Shrubbery sh
        sh = share.standard_shrubbery()
        print("Shrubbery size is", sh.width, 'x', sh.length)
```
```python
# setup.py
from Cython.Build import cythonize
from pathlib import Path
from setuptools import Extension, setup


PROJ_NAME_A = "aa"
PROJ_NAME_B = "bb"
PRJ_PATH = Path(__file__).absolute().parent  / "test_cython"

srcs_A = [
    str(PRJ_PATH / "cython" / "aa.pyx"),
    str(PRJ_PATH / "cython" / "share.pyx"),
    str(PRJ_PATH / "cpp" / "src" / "a.cpp"),
]


srcs_B = [
    str(PRJ_PATH / "cython" / "bb.pyx"),
    str(PRJ_PATH / "cython" / "share.pyx"),
    str(PRJ_PATH / "cpp" / "src" / "b.cpp"),
]

a_ext = Extension(
    PROJ_NAME_A,
    sources=srcs_A,
    language="c++",
    include_dirs=[str(PRJ_PATH / "cpp" / "include")],
)

b_ext = Extension(
    PROJ_NAME_B,
    sources=srcs_B,
    language="c++",
    include_dirs=[str(PRJ_PATH / "cpp" / "include")],
)

# extenstions = [a_ext]
externsions = [a_ext, b_ext]

setup(
    ext_modules=cythonize(externsions, language_level=3),
)
```
Note that `setup.py` is in the same layer with `test_cython`

If I uncomment `extensions = [a_ext]` and comment `extensions = [a_ext, b_ext]`, and run `python setup.py build_ext`, `.pyd` file will be generated, although it will say `AttributeError: module 'share' has no attribute 'Shrubbery'` when I `from aa import PyA`, but that's Okay, it's not the point I want to focus today.

Now, in `cython` directory, delete all the `.cpp` files (very important to reproduce the bug), and uncomment `extensions = [a_ext, b_ext]`, and run `python setup.py build_ext`, it will say `TypeError: '<' not supported between instances of 'dict' and 'dict'`

### Expected behaviour

I read the source code of cython, and found that in `Build/Dependencies.py#line1121`,  there is a `to_compile.sort()`. If there is no `.cpp` files in `cython` directory,  it will send every `.pyx` files to the list `to_compile`. As both `a_ext` and `b_ext` need `share.pyx`, `share.pyx` is sent twice to `to_compile`. In `to_compile`, every element is a tuple, but one item in tuple is a dict.   Because `share.pyx` is sent twice, there are 2 similar elements in `to_compile`, which before that dict they are all the same. Because `to_compile` need to be sorted, and the items before dict are all the same, the 2 dicts should be compared. But dicts can't be compared, then the error occurs. For testing, I commented `to_compile.sort()`, and everything works well.

I think there are several ways to fix the bug:
- Do we really need to sort `to_compiles`? Finally we will compile all the things in `to_compile` anyway, so delete this phrase would work
- I believe there must be some reasons that `to_compile` need to be sorted, but can we just sort the 1st item `priority` of each element? For example `to_compile.sort(key=lambda x: x[0])` would work
- when sending a `.pyx` file to `to_compile`, check if it has been in `to_compile`, if True, just continue
- jsonfy the dict to a string when sorting

It seems that the 3rd way (checking before sending to `to_compile`) is the most reasonable way, but the 2nd way (just compare `priority`) may also be needed.

### OS

Windows

### Python version

3.10.11

### Cython version

3.0.10

**Comment by monchin** [comment]
Also it will be appreciated if anyone can tell me why `AttributeError: module 'share' has no attribute 'Shrubbery'` would occur, thank you very much!

**Comment by da-woods** [comment]
Compiling multiple Cython files at once should give you a warning:

```
Warning: Multiple cython sources found for extension ...
See https://cython.readthedocs.io/en/latest/src/userguide/sharing_declarations.html for sharing declarations among Cython files.
```

This is telling you that **compiling multiple Cython sources together at once is a bad idea** for reasons that you're seeing.

Instead you should compile `share.pyx` as a separate module.

If you can't do that then it's probably better to use the (old and still a bad idea) `include` mechanism to reuse share. This will do a textual include, which is probably safer than what you're trying to do.

-----

> Also it will be appreciated if anyone can tell me why AttributeError: module 'share' has no attribute 'Shrubbery' would occur, thank you very much!

Don't know. You're not compiling a module `share` at all, so it should probably be a `ModuleNotFoundError`?

**Comment by da-woods** [comment]
I've closed this because there's much better ways to share declarations so I don't think it's worthwhile spending time to sort out all the issues with this really discouraged mechanism.
