### ISSUE TITLE
[BUG] Pandas FutureWarning thrown when getting dataframes from a function

### ISSUE THREAD

**Issue by alex-p-99** [cython/cython#6279]
### Describe the bug

When using pandas dataframes `df["col"] = df["col"].apply(foo)` should pass, regardless of how `df` is created

In the examples below, `test_1` runs as expected, while `test_2` fails with
```
FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
```

Note this warning only occurs after cythonising.

Using Pandas 2.2.2 & Cython 3.0.10

### Code to reproduce the behaviour:

```cython

import pandas as pd

class MyTestClass:

    def __init__(self):
        self.df = pd.DataFrame({"c1": ["a", "b", "c"], "c2": ["d", "e", "f"]})

    def get_df(self):
        return pd.DataFrame({"c1": ["a", "b", "c"], "c2": ["d", "e", "f"]})

    def _foo(self, _):
        return "foo"

    def test_1(self):
        df = self.df
        df["c1"] = df["c1"].apply(self._foo)

    def test_2(self):
        df = self.get_df()
        df["c1"] = df["c1"].apply(self._foo)


# Tests

def test_1():
    df = MyTestClass().test_1()

def test_2():
    df = MyTestClass().test_2()
```

### OS

Windows 10

### Python version

3.11

### Cython version

3.0.10

**Comment by da-woods** [comment]
Duplicate #6013

**Comment by da-woods** [comment]
Thanks for the report. I don't think this is something that Cython can realistically fix. Pandas have chosen a very implementation-dependent way to try to detect this warning that Cython can't (and shouldn't) really emulate.
