### ISSUE TITLE
Cython Compile embedsignature

### ISSUE THREAD

**Issue by pokecheater** [cython/cython#6285]
### Describe your issue

Hello,

I have a short question. When using embedsignature: False, cython should not include any code traces of the origin source code right? But although I am using this Flag with False, my error messages still show the original python stack traces so I guess my code is not obfuscated right?

How to achieve that?

**Comment by da-woods** [comment]
1. Please do not clutter the issue tracker with support questions. Instead ask them on the [cython-user's mailing list](https://groups.google.com/g/cython-users)
2. Obfuscation is a use-case we don't really care about. Any obfuscation you may get is largely accidental. Cython is open source so you're welcome to use it for whatever you like of course.
3. Stack traces are generated by reading from the source file. If the source file isn't present then they'll give less information (but not no information)
