### ISSUE TITLE
[BUG] Empty tuples aren't optimized in conditional statements

### ISSUE THREAD

**Issue by bbb23exposed** [cython/cython#6288]
### Describe the bug

Normally statements such as `x in (1, 2, 3)` are optimized to not use python functions, however `x in ()` will result in the generation of calls to python functions.

### Code to reproduce the behaviour:

```cython
ctypedef enum node_type:
    NODE_NULL,
    NODE_CONSTANT,
    NODE_TRANSMIT,
    NODE_SUM,
    NODE_ACTIVATE,
    NODE_BLEND,
    NODE_MULTIPLY,
    NODE_MODULO,
    NODE_BOOL,
    NODE_INVERSE,
    NODE_SIN,
    NODE_SQRT,
    NODE_LOW_POW,
    NODE_SQUARE,
    NODE_INPUT,
    NODE_OUTPUT

ctypedef enum slot_type:
    SLOT_NULL,
    SLOT_FLOAT,
    SLOT_BOOL

cdef inline slot_type get_node_input_type(node_type node_type, slot_type type_) noexcept:
    if ((node_type) in (NODE_CONSTANT, NODE_TRANSMIT, NODE_BLEND, NODE_INPUT)):
        return type_
    elif ((node_type) in (NODE_SUM, NODE_ACTIVATE, NODE_MULTIPLY, NODE_MODULO, NODE_INVERSE, NODE_SIN, NODE_SQRT, NODE_LOW_POW, NODE_SQUARE, NODE_BOOL)):
        return SLOT_FLOAT
    elif ((node_type) in ()):
        return SLOT_BOOL

    return SLOT_NULL
```

### Expected behaviour

They should be optimized into C switch statements.

### Python version

3.8.3

### Cython version

3.0.10

**Comment by bbb23exposed** [comment]
> Is this `x in ()` something that actually appears in your (generated?) code?

Yes, I use macros.

**Comment by scoder** [comment]
> I use macros.

Could you give a (realistic) example of how you use this? I'd like to understand if this is something worth working on.

**Comment by bbb23exposed** [comment]
I have Nodes that input and output Slots. To reduce code duplication and increase extensibility, I have macros defined that can check commonly used properties about nodes inferred from theirs types. Somes of these macros use tuples of Node types. To increase extensibility, these tuples are defined as separate macros than the checks which they are included in so they can be used in other context (e.g. iterating over a list of types that meet the requirement).

Some of these requirements don't have any nodes that match them or exclude them but may in the future, so they are defined as empty tuples.

**Comment by bbb23exposed** [comment]
> Still not sure what you mean by "macros".

I use the C processor on my code.

> However, I doubt that `variable in ()` takes any serious amount of time. `variable` and `()` are constants that do not need any time to look up, then `whatever in ()` is really just jumping through a few pointers and returning `0` without doing anything worth noting. Arguably, the C compiler cannot optimise that away, so it _is_ doing something at runtime, but that "something" is really, really cheap, especially when executed several times. If you can motivate that this consumes a non-negligible amount of time in your code, we may consider adding special cases for this, but I doubt that you'll find this being a bottleneck.

I don't know how much a performance hit it is. It probably isn't much, but the code is very optimized and the function is called a lot. Plus, the perfectionist in me gets annoyed seeing a yellow line in a sea of white.

Forgive me since I don't know much about Cython's internal architecture, but if the problem is that the lhs could have side-effects, then why don't the non-empty arrays have the same issue? None of my lhs's have side effects, but only the one with the empty tuple causes the issue.
