### ISSUE TITLE
[BUG]  Cython depfile should use relative paths

### ISSUE THREAD

**Issue by lesteve** [cython/cython#6291]
### Describe the bug

A little while ago I created an issue in the Meson repo https://github.com/mesonbuild/meson/issues/13212 since when you update some `pxd` in scikit-learn, you would need to build twice to fully build the project. We have a work-around in scikit-learn but it would be great if the underlying issue was fixed because it is quite a confusing behaviour.

Investigation by @rgommers and @eli-schwartz seemed to indicate that potentially using relative files in depfiles would fix the issue see https://github.com/mesonbuild/meson/issues/13212#issuecomment-2137556487

cc @ev-br since I think he is the one who added depfile support in Cython in https://github.com/cython/cython/pull/4563 IIUC and you may have some insights into this. Thanks a lot for this by the way! The more I worked on using Meson in scikit-learn the more I realized all the issues that had been fixed along the way to make it a workable solution for the Scientific Python ecosystem.

### Code to reproduce the behaviour:

repo to reproduce the behaviour: https://github.com/lesteve/meson-partial-build

A quick summary of the behaviour:
```bash
touch package/utils/utils.pxd
# This does not rebuild package/lib/lib shared library
ninja -C build -d explain -v
# The second time this builds package/lib/lib shared library
ninja -C build -d explain -v
```

A more detailed explanation is available in https://github.com/mesonbuild/meson/issues/13212

### Expected behaviour

Calling `ninja` once fully builds the project, calling `ninja` a second time says "No work to do".

### OS

Linux

### Python version

3.12

### Cython version

3.0.10

**Comment by ev-br** [comment]
I don't have any deep insights, sorry. The decision of `# paths below the base_dir are relative, otherwise absolute` was IIRC  a quick-and-dirty fix to _make it work now and can tweak later if causes problems_. Well, now it does :-).

(and yeah, I was just early test-driving meson/cython combo in smaller side projects and the two-step `custom_target` solution looked clunky)

**Comment by lesteve** [comment]
OK thanks @ev-br, do you happen to remember what were the issues with always using relative paths? I tried to look for some hints in #4563 but could not find any unfortunately.

I quickly tried to modify Cython to always use relative path and both numpy and scikit-learn builds fine. In scikit-learn I tried to modify a few `.pxd` and rebuilding and the dependency needs to be taken correctly into account, same thing with numpy (although I am a lot less familiar with the numpy Cython dependencies)

**Comment by ev-br** [comment]
Don't remember anything specific really. Might be that there aren't any. Would be happy to test scipy if you've a branch of cython.

**Comment by lesteve** [comment]
Thanks, here is a cython branch with the minimal changes I mentioned to always use relative paths for depfile: https://github.com/lesteve/cython/tree/relative-path-for-depfile

**Comment by ev-br** [comment]
Sorry for the delay. I built scipy with cython from the https://github.com/lesteve/cython/tree/relative-path-for-depfile. Seems to work as expected indeed.

**Comment by lesteve** [comment]
Thanks for the feed-back, I have opened #6345. Suggestions more than welcome, on how to add a test for this!

**Comment by ev-br** [comment]
I suppose you'll want to modify some of these:

```
$ grep depfile . -rn
./build/depfile_package_cythonize.srctree:2:CYTHONIZE -i pkg --depfile
./build/depfile_package_cython.srctree:4:CYTHON --depfile pkg/sub/test.pyx -o builddir/pkg/sub/test.c
```
