### ISSUE TITLE
[BUG] Asyncio create_connection -> call extern C++ method inside try except -> call extern void function -> raise Exception -> SystemError raised instead

### ISSUE THREAD

**Issue by Source61** [cython/cython#6316]
### Describe the bug

I found this bug whose flow is described in the title.

Another odd behavior of this code that makes it clearly a bug is that if you added a print statement after the exception is raised then the exception IS caught and there's no SystemError raised like the one described below.

The exception raised, when not adding a print statement after the method that raises an exception, is:

Exception in callback ClientLogin.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle ClientLogin.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "test.pyx", line 7, in test.mystringError
    raise BufferError()
BufferError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
SystemError: <cyfunction ClientLogin.connection_made at 0x7ffac8f057d0> returned a result with an exception set

### Code to reproduce the behaviour:

test.pyx
```cython
import asyncio, signal

cdef:
	extern void mystringError() except *:
		raise BufferError()

	extern from "mytest.cpp":
		cppclass test:
			test()
			void check(unsigned int i)

	cdef class ClientLogin:
		cdef:
			test t
			cpdef connection_made(self, transport):
				print("connection_made")
				try:
					self.t = test()
					self.t.check(7)
					print("hello") # REMEMBER TO DELETE THIS TO GET THE EXCEPTION
				except BufferError:
					print("BufferError")

			cpdef data_received(self, data):
				print("data_received", data)

			cpdef connection_lost(self, exc):
				print("connection_lost", exc)

			cpdef eof_received(self):
				print("eof_received")

async def timer():
	f = loop.create_connection(ClientLogin, "localhost", 7171)
	await asyncio.shield(f)
	await asyncio.sleep(100000000)

loop = asyncio.get_event_loop()

loop.add_signal_handler(signal.SIGINT, loop.stop)

timertask = loop.create_task(timer())

loop.run_forever()
```

mytest.cpp:
```c++
extern void mystringError();

class test {
public:
	void check(unsigned int i) {
		if (i % 2)
			mystringError();
	}
};

```

### OS

Linux

### Python version

3.11.2

### Cython version

3.0.10

**Comment by Source61** [comment]
Follow-up: I just realized/noticed that if you add an "except *" (NOT except +) to the extern from -> cppclass test -> void check method, then the exception is caught. So although I still believe this is a bug, adding an except * seems to be a workaround for now.

**Comment by da-woods** [comment]
> Follow-up: I just realized/noticed that if you add an "except *" (NOT except +) to the extern from -> cppclass test -> void check method, then the exception is caught. So although I still believe this is a bug, adding an except * seems to be a workaround for now.

No. This is the correct fix.

`except *` says "this function may raise a  Python exception". That's correct for `check`.

`except +` says "this function may raise a c++ exception. `check` doesn't do that. 

Without `except *`, Cython doesn't realise that `check` has raised a Python exception and so continues as if it hasn't (which gives the crash)

**Comment by Source61** [comment]
> > Follow-up: I just realized/noticed that if you add an "except *" (NOT except +) to the extern from -> cppclass test -> void check method, then the exception is caught. So although I still believe this is a bug, adding an except * seems to be a workaround for now.
> 
> No. This is the correct fix.
> 
> `except *` says "this function may raise a Python exception". That's correct for `check`.
> 
> `except +` says "this function may raise a c++ exception. `check` doesn't do that.
> 
> Without `except *`, Cython doesn't realise that `check` has raised a Python exception and so continues as if it hasn't (which gives the crash)

Ok, thanks for the clarification.

**Comment by Source61** [comment]
> > Follow-up: I just realized/noticed that if you add an "except *" (NOT except +) to the extern from -> cppclass test -> void check method, then the exception is caught. So although I still believe this is a bug, adding an except * seems to be a workaround for now.
> 
> No. This is the correct fix.
> 
> `except *` says "this function may raise a Python exception". That's correct for `check`.
> 
> `except +` says "this function may raise a c++ exception. `check` doesn't do that.
> 
> Without `except *`, Cython doesn't realise that `check` has raised a Python exception and so continues as if it hasn't (which gives the crash)

Ok, thanks for the clarification.
