### ISSUE TITLE
[BUG] Unable to transform type of function param

### ISSUE THREAD

**Issue by LeoMooreCST** [cython/cython#6319]
### Describe the bug

suppose we have a function param whose type is dict, if there is an operation on the following code, error will occur as "Expected dict, got DataFrame"

### Code to reproduce the behaviour:

```python
def myfunc(features: dict):
      features = pd.DataFrame([features])

### Expected behaviour

can it normally perform type transformation?

### OS

Windows

### Python version

3.8.5

### Cython version

3.0.10

### Additional context

_No response_

**Comment by da-woods** [comment]
That seems right to me. Cython uses type hints for static typing and `pd.DataFrame` isn't a `dict`. The type hint refers to all uses of the variable and not just the function input. (Note that Cython is also stricter than most type checkers and requires an exact `dict` and not a subclass. But that doesn't apply here).

If you want to turn off this behaviour then set the Cython directive `annotation_typing` to `False`.

Obviously pure Python doesn't enforce type hints, but if you ran this code through a type checker like `MyPy` then that would complain to you.
