### ISSUE TITLE
Build and upload Python 3.13 wheels to PyPI

### ISSUE THREAD

**Issue by EwoutH** [cython/cython#6322]
### Describe your issue

Python 3.13.0 release candidate 1 (`3.13.0rc1`) is [released](https://pythoninsider.blogspot.com/2024/08/python-3130-release-candidate-1-released.html)! Wit with release candidate the ABI is frozen which means wheels for Python 3.13 can be build and uploaded to PyPI.

Since cython is a (very) low-level dependency for many downstream projects, it would be beneficial to have Python 3.13 on PyPI as fast as possible, via a 3.0.x release and/or 3.1.0.

cibuildwheel now uses the latest Python `3.13.0rc1` and build Python 3.13 by default (https://github.com/pypa/cibuildwheel/pull/1950). Next cibuildwheel release should be soon, which can help this process.

**Comment by EwoutH** [comment]
First step: https://github.com/cython/cython/pull/6321

**Comment by scoder** [comment]
According to GHA, the last 3.0.x CI run was crashing in 3.13b3 (in the `no_gc` test), which isn't hugely surprising, given the amount of breaking changes in this release. There's probably a fix in the master branch for this that may or may not work as a backport. 
https://github.com/cython/cython/actions?query=branch%3A3.0.x

Upgrading `cibuildwheel` in 3.0.x is probably fine. We haven't served Py2.7 or anything below Py3.6 with a binary wheel in a while. They'll continue to be sufficiently happy with the generic Py2/3 wheel that we ship. I'll try upgrading.

**Comment by da-woods** [comment]
> Since cython is a (very) low-level dependency for many downstream projects, it would be beneficial to have Python 3.13 on PyPI as fast as possible, via a 3.0.x release and/or 3.1.0.

While I agree, it shouldn't be blocking anything.  If you try to install Cython on Python 3.13 it works fine, but just installs the generic pure-Python wheel.  Cython itself runs slightly slower but functions the same.

**Comment by scoder** [comment]
In fact, it might actually be better to *not* upload a Py3.13 binary wheel for Cython as long as Python 3.13 is not finally released (or has had its first bug fix release). If we upload a binary wheel now, we risk getting it broken by new changes in the final release. The Python wheel is unlikely to be affected by this.

**Comment by EwoutH** [comment]
It’s [stated](https://www.python.org/downloads/release/python-3130rc1/) that Python 3.13 won’t have any ABI changes anymore, and it’s recommended (and encouraged) to upload wheels.

> There will be no ABI changes from this point forward in the 3.13 series, and the goal is that there will be as few code changes as possible.
> 
> #### Call to action
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc1 will work with future versions of Python 3.13.

**Comment by scoder** [comment]
> There will be no ABI changes from this point forward in the 3.13 series

They've definitely learned from the past, but incompatible changes in final CPython releases (or even point releases) are not unheard of.

Regardless, as @da-woods mentioned, Cython's own binary wheels are a pure optimisation for execution performance and not required to get a fast wheel install. The Python wheel is much smaller and thus faster to download and install than a binary wheel. For small single module package builds, the generic Python wheel might even be faster overall than using a binary wheel of Cython.

**Comment by andyfaff** [comment]
numpy is currently experiencing build issues with a `cp313t-manylinux_aarch64` (i.e. free threaded) build. We're installing from cython from `scientific-python-nightly-wheels`. The non free-threaded build works ok.

The error message seems to point to something to do with cython. See [here](https://github.com/numpy/numpy/issues/27107#issuecomment-2268111184)

**Comment by scoder** [comment]
I fixed up a few minor issues in the 3.0.x branch and I think 3.0.11 is ready for a release. That's the best thing we can give users of Py3.13 right now, I believe. I'll prepare the release.

**Comment by EwoutH** [comment]
Awesome! Thanks a lot for this. Also thanks for the context on execution performance and install times of the Python wheels vs the binary wheels, I didn't know that yet.

Another great option might be a 3.1.0 [pre-release](https://packaging.python.org/en/latest/specifications/version-specifiers/#pre-releases). Then users can install and test that easily by using `pip install --pre cython`. It's also a great way to communicate a new release is coming soon and to get it tested and feedback on it.

**Comment by scoder** [comment]
3.0.11 is uploaded to PyPI. I'll close this ticket.
We'll see about a 3.1 pre-release when we have some more open PRs merged.
