### ISSUE TITLE
[BUG] Cython uses PyObject_GenericSetAttr() on types in Limited API

### ISSUE THREAD

**Issue by scoder** [cython/cython#6323]
### Describe the bug

This code now hits an assertion in dev-builds of the CPython main branch:
https://github.com/cython/cython/blob/7e8a172d21b0c723be14685e25ae854bbc6cdaec/Cython/Utility/ExtensionTypes.c#L694-L699

https://github.com/python/cpython/blob/e6fad7a0e3d824f4a3c9cd71a48208880606d705/Objects/object.c#L1714
```c
    assert(!PyType_IsSubtype(tp, &PyType_Type));
```

This is used in the auto-reduce setup code to fix up the reduce methods after creating the type. The assertion was added in
https://github.com/python/cpython/pull/118454

Not sure if there's a way to work around this – or whether we should. It seems to be a hack on our side to update the type dict like this (even *after* adding the type to the module dict).

### Python version

3.14

### Cython version

master

**Comment by da-woods** [comment]
> It seems to be a hack on our side to update the type dict like this (even _after_ adding the type to the module dict).

It is a hack - yes :)

I've asked for (and will probably get) a better way of dealing with this in future with https://github.com/python/cpython/issues/121654. But that doesn't help now really.

**Comment by da-woods** [comment]
> This is used in the auto-reduce setup code to fix up the reduce methods after creating the type.

It's also used in adding `CyFunctions` to the class dict, which is probably the more important use.

The easiest option would be not to set the immutable flag on these classes, although I don't really like that.

**Comment by da-woods** [comment]
I think the better solution might be to use a custom metaclass which isn't flagged as immutable, but has a custom `__setattr__` that acts immutable but provides a backdoor to use in construction.

If we do that then it precludes custom metaclasses on `cdef class` as a future feature though.

**Comment by da-woods** [comment]
I think I can see a more robust hack... will try it and make a PR if successful
