### ISSUE TITLE
[ENH] Documentation suggestion: make it clearer what the default values are for compiler directives

### ISSUE THREAD

**Issue by asmeurer** [cython/cython#6340]
### Is your feature request related to a problem? Please describe.

The docs for compiler directives is inconsistent in showing the defaults https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives. Some options list the default at the end, some list it somewhere in the middle of the text, and some don't list it at all. 

See https://github.com/cython/cython/blob/master/docs/src/userguide/source_files_and_compilation.rst#compiler-directives

I would suggest adopting a style where "default is X" is always a single line at the bottom of the description. Additionally, I would suggest bolding the default option in the list after the name of the directive, like

> `annotation_typing` (**True** / False)
> Uses function argument annotations to determine the type of variables...

I'm happy to make a PR for this but someone will need to point me to where the defaults are defined for the options that don't actually specify that.

**Comment by da-woods** [comment]
Defaults are listed here: https://github.com/cython/cython/blob/1d7100d867a8b64b6f661009ec2ed45a4d8d5dba/Cython/Compiler/Options.py#L179

Making things clearer would be good I think
