### ISSUE TITLE
Tag anything that's CPython 3.13 nogil compatible (3.1.0 alpha)?

### ISSUE THREAD

**Issue by h-vetinari** [cython/cython#6368]
### Describe your issue

In conda-forge, we're about to begin migrating for CPython 3.13 (not yet with nogil).

To make this work tractable, it would be much easier if there were a consistent ~version~ tag of Cython that we use across our various packages, even if it's just an alpha version. This could be quite literally any recent commit, with the one caveat that we're relying on no more ABI changes to publish builds in advance (which CPython promises post-rc1). If that's not possible for Cython yet, then we're up a certain creek without a paddle... 😅 

I saw that the 3.0.x branch recently added the 3.13 classifier (https://github.com/cython/cython/commit/5fa0660e3901bc5a6ec573d0ea320588d59effa2), so 3.0.12 would be even better than 3.1.0a1. :)

**Comment by scoder** [comment]
3.0.11 is fine, it's just missing the classifier.

3.1 is probably more interesting, assuming that users of 3.13 won't care much about Py2 and really old Py3 versions any more.

I think we're close to an alpha release there, but I can't promise that there won't be any behavioural changes between now and the final release. Probably nothing big, though.

**Comment by h-vetinari** [comment]
Unfortunately, it seems that Cython 3.0.11 is not enough to successfully build/test numpy 2.1.0 (c.f. https://github.com/numpy/numpy/issues/27314), although it's particular that the issue affects only macOS -- the other targets build fine.

Is there a bound for the macOS deployment target, and if so what is it? There's necessarily a lowest version being tested, if only implicitly by what CI agents offer...

**Comment by h-vetinari** [comment]
The main issue in numpy seems to be that [this](https://github.com/numpy/numpy/blob/v2.1.0/numpy/_core/tests/examples/cython/checks.pyx) test module cannot be imported after being built with cython 3.0.11. Any help there would be appreciated, as we're currently stuck on that.

**Comment by dnicolodi** [comment]
There is a compilation error with Cython 3.0.11 with Python 3.13 on macOS when the compilation uses a C standard older than C11: #6385

**Comment by ngoldbaum** [comment]
Any chance you can trigger the nightly wheels action? The curently nightly is incompatible with 3.13.0rc2 and I think all it needs is a new upload to fix it.

**Comment by scoder** [comment]
> trigger the nightly wheels action

Done.

**Comment by h-vetinari** [comment]
FWIW, the same situation persists now for the free-threading builds. We cannot _really_ start migrating for the free-threading builds in conda-forge until we have a tag (alpha, beta, whatever) of Cython 3.1.0. If it's an alpha, we don't yet need a promise of ABI-stability; we could do things in a way that we rebuild (the relatively small number of currently available packages that are free-threading compatible) for every new Cython alpha/beta until there's a RC or GA version. 

All that to say, even just tagging current `master` as `3.1.0a0` would help (alphas don't have to be feature-complete either, so that wouldn't preclude other big changes to still land).

**Comment by h-vetinari** [comment]
> All that to say, even just tagging current `master` as `3.1.0a0` would help (alphas don't have to be feature-complete either, so that wouldn't preclude other big changes to still land).

Any chance for a 3.1.0a0 in the foreseeable future? @scoder @da-woods

**Comment by da-woods** [comment]
I don't control the release schedule I'm afraid. Although there isn't much more that I'd like to add to 3.1 I think

**Comment by scoder** [comment]
I started going through the list of open PRs to see what can still be merged for a first alpha release, but as the goal seems to be to have "something usable to get started with it", I decided that the current status is safer for a first release. There will be more merges later, but let's get something out already.

**Comment by scoder** [comment]
I released Cython 3.1.0a1 to PyPI. Have fun.

**Comment by h-vetinari** [comment]
Thank you very much! 🙏
