### ISSUE TITLE
Cython doesn't support numba?

### ISSUE THREAD

**Issue by duxuan11** [cython/cython#6372]
I use easycython to convert python script files to pyd files in Windows system.
The script file contains numba, and decorators are used for some functions in dynamics script files.
![image](https://github.com/user-attachments/assets/68a23d61-0a63-4d85-afcf-2ac0230b77ef)
![image](https://github.com/user-attachments/assets/638e1343-0da6-41c0-a394-9576b589cde2)
Therefore, I want to ask if cpython supports Numba's decorator?  When I remove decorators, the code will not report any error.

**Comment by TeamSpen210** [comment]
It wouldn't, and it doesn't really make sense. Cython converts Python code into native code, which is what Numba also does, just at runtime instead of ahead of time. Doing it twice doesn't make any sense, pick one to use.

**Comment by da-woods** [comment]
The only detail to add to what @TeamSpen210 says: Numba works by inspecting the Python bytecode of the functions. Cython does not use Python bytecode. So they really are incompatible for good reason.
