### ISSUE TITLE
[ENH] support isinstance(cyfunction, types.FunctionType) return True

### ISSUE THREAD

**Issue by nokados** [cython/cython#6379]
### Is your feature request related to a problem? Please describe.

In my code, I check if something is a function. When I cythonize the code, it stops working.

### Describe the solution you'd like.

```python
import inspect
from types import FunctionType

import cython


# compile some function
foo = cython.inline("def f(): pass")["f"]

# Both of these conditions must be True
assert isinstance(foo, FunctionType)
assert inspect.isfunction(foo)
```

### Describe alternatives you've considered.

I've considered to add specific conditions - https://github.com/pydantic/pydantic/issues/10282 
However, it seems unreliable

**Comment by da-woods** [comment]
No. This just isn't possible, and it'll cause as many problems as it solves.

If we somehow managed to make it work then people would assume that they could get usable Python bytecode from it (for example).

We can make a Cython function act a lot like a Python function, but it *isn't* a Python function and `isinstance` should reflect that.

**Comment by scoder** [comment]
`types.FunctionType` is the Python function type. This means that `isinstance(function, types.FunctionType)` tests if `function` is exactly a Python function (with byte code and all), not "some callable". It also returns false for builtin functions, methods, and really everything that is not a Python function.

From the pydantic issue that you linked, it seems that pydantic is too restrictive when it needs to exclude (certain) callables from its analysis.

**Comment by nokados** [comment]
Alright. Perhaps we need an explicit method to check if a variable is a Cython function. Checking the `__name__` string or extracting the type from a similar variable, as I suggested in the other issue, are non-obvious and inelegant solutions.

**Comment by nokados** [comment]
So, what do we do next? @da-woods  @scoder 

- Open a new issue "Explicit method to check if a variable is a Cython function"
- Reopen this one
- Nothing, only comment why this feature is not interesting enough

**Comment by da-woods** [comment]
If we assume that this is a good idea - the trouble is that there isn't one type of Cython function in existence but (roughly) one type per Cython version. So there's a cython-3.0.10 function which is different from a cython-3.0.11 function, etc..

To make it work with an `isinstance` check I think we'd need to make a shared abstract base class somewhere (e.g. `cython_runtime` and register each Cython function type with that).

Or do something else like give cython functions an easily recognisable attribute instead of an instance check.

I'm not really convinced of the value of this, but I think it would be possible to do.

**Comment by nokados** [comment]
I am not sure is the issue important. Of course, you understand better whether it matters. My use case is to cythonize all my code, and I would like it to happen seamlessly, but in the case of pydantic, explicit function checking doesn't solve the problem anyway. I don't know if there are any applications of this checking, besides in libraries like pydantic that analyze code structure. As an option, you could put the issue on hold until a sufficient number of people express that they also need it.

Regarding the implementation, you can also define `__instancecheck__` in a metaclass, as mentioned in https://github.com/pydantic/pydantic/issues/6670#issuecomment-1644799636

**Comment by scoder** [comment]
> in the case of pydantic, explicit function checking doesn't solve the problem anyway

It rarely does in Python. If pydantic is interested in functions to analyse, I'd rather suggest looking at the source file path or the code object. The mere fact that a function is compiled doesn't mean it's not interesting, at least in the case of Cython. The source might still be available and decorators/annotations/etc. might have been used just normally.
