### ISSUE TITLE
[BUG] CompileError on method after parenthesis in with statement

### ISSUE THREAD

**Issue by vavanade** [cython/cython#6381]
### Describe the bug

Code below fails with `CompileError` with `Expected ':', found '.'`  pointing to the dot before `open`.

### Workaround
```python
full_path = dir_path / file_name
with full_path.open() as f:
    data = f.read()
```

### Code to reproduce the behaviour:

```python
from pathlib import Path

dir_path = Path("/path/to/dir")
file_name = "file.txt"

with (dir_path / file_name).open() as f:
    data = f.read()
```

### Expected behaviour

the code compiles

### OS

Windows

### Python version

3.10

### Cython version

3.0.0a11

**Comment by da-woods** [comment]
3.0.0a11 is quite old now (it was a pre-release alpha version). 3.0.11 (no "a") is the current release. It's fixed in that.
