### ISSUE TITLE
Don't include `pycore_lock.h` when `CYTHON_COMPILING_IN_CPYTHON_FREETHREADING`

### ISSUE THREAD

**Issue by colesbury** [cython/cython#6391]
### Describe your issue

The [`PyMutex`](https://docs.python.org/3.13/c-api/init.html#c.PyMutex) API is public (in 3.13). I don't think Cython needs to include `pycore_lock.h`, which is intended to be an internal-only header.

https://github.com/cython/cython/blob/7ae676645185e934c6c61b62abdb626ee905049a/Cython/Utility/ModuleSetupCode.c#L2480-L2488

**Comment by da-woods** [comment]
Yes - I think this can go. It was only added to make things work before PyMutex was made public
