### ISSUE TITLE
[BUG] Cython-generated variable name is a C++ keyword 

### ISSUE THREAD

**Issue by tvalentyn** [cython/cython#6400]
### Describe the bug

I noticed the following Cython-translated excerpt from running Cython over fastavro sources.

```

/* "fastavro/_schema.pyx":561
 *
 *
 * cdef _inject_schema(outer_schema, inner_schema, namespace="", is_injected=False):             # <<<<<<<<<<<<<<
 *     # Once injected, we can stop checking to see if we need to inject since it
 *     # should only be done once at most
 */
struct __pyx_opt_args_8fastavro_7_schema__inject_schema {
  int __pyx_n;
  PyObject *namespace;
  PyObject *is_injected;
};
```

Because in C++ `namespace` is a reserved keyword,  the translated code doesn't compile in my environment with default compiler setting, and I have to apply some workarounds (https://github.com/fastavro/fastavro/commit/dd026c6e584b3ed3e731002e815500f49dd554c2).

Per discussion on https://groups.google.com/g/cython-users/c/qIJzaBurOWg, it should be possible to select better variable names here.

**Comment by scoder** [comment]
Fixed in https://github.com/cython/cython/commit/6aeff0e9d76d130b4c300f90863d505f5bea3ef3
