### ISSUE TITLE
Need more documentation about the  PXD files.

### ISSUE THREAD

**Issue by Ruhaan838** [cython/cython#6453]
### Describe your issue

# Recently I have been working on Cython, and I need more docs about the PXD file 
- Is there a way I can declare my ' class ' in the PXD file? that I can further use in other PXD files.
- How can I can declare the __init__, __add__, __sub__, __div__, __mul__ other more methods like that 
- How can I declare the cdef methods that are not part of that class object but some different methods that I declare to help the __add__ methods?

**Comment by da-woods** [comment]
Please direct support questions to the [cython users mailing list](https://groups.google.com/g/cython-users) (as you were asked to when you opened this issue).

I'm sure there's improvements that could be made to the documentation, but this issue doesn't really propose anything concrete.

**Comment by Ruhaan838** [comment]
Ok, thanks :)
