### ISSUE TITLE
[BUG] Unable to install gevent using Cython 3.1.0a1

### ISSUE THREAD

**Issue by e-nomem** [cython/cython#6490]
### Describe the bug

Since `gevent` doesn't have pre-built arm64 wheels we build them at install time in our application image. We started running into errors starting a few hours ago looking like this:
```
Collecting gevent==22.10.2
  Downloading https://[REDACTED]/gevent/22.10.2/gevent-22.10.2.tar.gz (6.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 356.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Compiling src/gevent/resolver/cares.pyx because it changed.
      [1/1] Cythonizing src/gevent/resolver/cares.pyx
      performance hint: src/gevent/libev/corecext.pyx:1339:0: Exception check on '_syserr_cb' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef tuple integer_types
      
      if sys.version_info[0] >= 3:
          integer_types = int,
      else:
          integer_types = (int, long)
                                ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:60:26: undeclared name not builtin: long
      Compiling src/gevent/libev/corecext.pyx because it changed.
      [1/1] Cythonizing src/gevent/libev/corecext.pyx
      Traceback (most recent call last):
        File "/code/venvs/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/code/venvs/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/code/venvs/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-cmtabhyu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-cmtabhyu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-cmtabhyu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
        File "<string>", line 61, in <module>
        File "/tmp/pip-install-3x4wflup/gevent_b05306ac6dd147a990f5c37cc6e4ce76/_setuputils.py", line 237, in cythonize1
          new_ext = cythonize(
        File "/tmp/pip-build-env-cmtabhyu/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1109, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-cmtabhyu/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
pip install failed!
```

The above output is from a Python 3.10 venv so I'm not sure how we're ending up in else case of the branch for `sys.version_info[0] >= 3`, but we pulled the `3.1.0a1` release from our internal pypi mirror and builds started succeeding again. We also observed the same behavior on `gevent==23.7.0`.

### Code to reproduce the behaviour:

```shell
pip install 'gevent==22.10.2'
# or
pip install 'gevent==23.7.0'
```

### Expected behaviour

The wheel builds and I'm able to install `gevent`

### OS

Ubuntu Jammy (arm64)

### Python version

3.10.12

### Cython version

3.1.0a1

**Comment by scoder** [comment]
This is expected. Cython 3.1 removes all Python 2.x cruft and thus doesn't know the Python 2 long type any more. Code using that type probably doesn't need it any more and should be cleaned up.

However, Cython 3.1.0a1 is a pre-release. Pip shouldn't normally install it. Apparently, yours does by default. Might be due to your use of a PyPI mirror, as you noted.

**Comment by da-woods** [comment]
1. It's a bit of a shame that this fails at compile-time, thus forcing everyone to get rid of their Python 2 cruft.  It could probably be left to a runtime "failure" (in the event that it actually does get run)
2. I also get this issue (without using a PyPI mirror). I think gevent is pinned to `"Cython >= 3.0a6"`, so that presumably expresses that they're happy with any pre-release. That's on them rather than us though.

**Comment by scoder** [comment]
> 1. It's a bit of a shame that this fails at compile-time, thus forcing everyone to get rid of their Python 2 cruft.

My expectation is that users of Cython 3.1 will *want* to get rid of the Python 2 zombies in their code, so a compile time failure would rather help in finding left-overs.

I agree that it's annoying if Cython 3.1 comes in unintentionally, thus failing builds as described above. But we've openly communicated for a very long time (for years) that Cython 3.1 will remove Python 2 support, so I really think it's up to users to not blindly specify a broad dependency like "Cython >= 3.0" if they want to continue supporting Python 2 in their code base.

**Comment by scoder** [comment]
I've opened ticket https://github.com/gevent/gevent/issues/2076 for gevent.

**Comment by e-nomem** [comment]
Makes perfect sense, I didn't realize `gevent` had advertised a pre-release version in the build deps but that definitely explains how the pre-release cython 3.1 version snuck in. Thanks for looking into it!
