### ISSUE TITLE
[BUG] cannot build redistributable wheel

### ISSUE THREAD

**Issue by lmaddox** [cython/cython#6498]
### Describe the bug

I need to build a re-usable python package.

I've tried:
- [cibuildwheel](https://github.com/pypa/cibuildwheel/issues/2082)
- [auditwheel](https://github.com/pypa/auditwheel/issues/518)
- [twine](https://github.com/pypa/twine/issues/1176)
- [stackoverflow](https://stackoverflow.com/questions/79187007/github-act-workflow-build-cython-project-and-push-to-pypi)

### Code to reproduce the behaviour:

any trivial example

### Expected behaviour

pushable to pypi

### OS

linux

### Python version

3.12

### Cython version

latest

### Additional context

`pip wheel -w dist/ && twine upload dist/*`

**Comment by scoder** [comment]
It looks like you need to write a pyproject.toml and then use setuptools to build your project. cibuildwheel will then help you build it for different platforms on a CI system.

This is not a but in Cython. Consider contacting the cython-users mailing list for help.
