### ISSUE TITLE
[ENH] typed names for functions using fused types

### ISSUE THREAD

**Issue by Maki4748** [cython/cython#6525]
### Is your feature request related to a problem? Please describe.

Hey,
I used fused types in my code to generate me return functions for arrays from cpp.
The problem I sorta had with this is, that the function names are numbered instead of using the specific type as a name.
Since I at this point couldn't really find a good solution to get cpp to call the correct function based on the type, I hardcoded the whole thing, but this comes with the issue of, if the list is changed, the numbers need to be changed by hand too.
This is totally doable and that's what tests are for, but at the same time, this seems like a shortcoming.

Just quickly as an example:
```cython
ctypedef fused array_types_t:
    double
    long double
    double complex
    long double complex
    float
    float complex
    long
    unsigned long
    long long
    unsigned long long
    int
    unsigned int
    short
    unsigned short
    signed char
    unsigned char


# Array with limit 2D
cdef api np.ndarray[array_types_t, ndim=2] ddarray(const array_types_t *data)
```
generates:
```cython
 if (__Pyx_ImportFunction_0_29_36(module, "__pyx_fuse_0ddarray", (void (**)(void))&__pyx_api_f_7eigency_11conversions___pyx_fuse_0ddarray, "PyArrayObject *(double const *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_36(module, "__pyx_fuse_1ddarray", (void (**)(void))&__pyx_api_f_7eigency_11conversions___pyx_fuse_1ddarray, "PyArrayObject *(long double const *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_36(module, "__pyx_fuse_2ddarray", (void (**)(void))&__pyx_api_f_7eigency_11conversions___pyx_fuse_2ddarray, "PyArrayObject *(__pyx_t_double_complex const *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_36(module, "__pyx_fuse_3ddarray", (void (**)(void))&__pyx_api_f_7eigency_11conversions___pyx_fuse_3ddarray, "PyArrayObject *(__pyx_t_long_double_complex const *)") < 0) goto bad;
  if (__Pyx_ImportFunction_0_29_36(module, "__pyx_fuse_4ddarray", (void (**)(void))&__pyx_api_f_7eigency_11conversions___pyx_fuse_4ddarray, "PyArrayObject *(float const *)") < 0) goto bad;
  .
  .
  .
```

### Describe the solution you'd like.

That instead of `__pyx_fuse_4ddarray` it generates `__pyx_fuse_floatddarray` or something similar.

**Comment by da-woods** [comment]
What might work is to assign them (in Cython) to a C function pointer with a well-defined name. Cython should match up the correct version to the function pointer. It's a bit verbose though.

**Comment by scoder** [comment]
I agree that explicit function pointers (or an array of functions or whatever) seems a good way to do this. Cython avoids generating fused function variants that are unused. I'm not sure how it handles this with respect to `api` functions, but listing the complete set of exported (generated) function variants somewhere seems best in terms of API design. It also allows you to later change the implementation, the collection of type variants, etc., without relying on specific Cython behaviour regarding internal naming or other implementation details.

**Comment by scoder** [comment]
I'm closing this as "won't fix", but feel free to comment if you think that the proposed solutions do not fit your use case.
