### ISSUE TITLE
multiple definitions of method fails in c code, not cython

### ISSUE THREAD

**Issue by robertwb** [cython/cython#715]
In version 1474:7f1b96cad687, defining multiple versions of the same method using def fails in c code, but not cython.  Specifically, the following code fails:

```
cdef class A:
    def a(self): pass
    def a(self): pass
```

It produces this output:

```
running build_ext
cythoning mult_def.pyx to mult_def.c
building 'mult_def' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -O2 -march=i586 -mtune=i686 -fmessage-length=0 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -g -fwrapv -fPIC -I/home/hoytak/sysroot/lib/python2.5/site-packages/numpy/core/include -I/usr/include/python2.5 -c mult_def.c -o build/temp.linux-i686-2.5/mult_def.o
mult_def.c:229: error: redefinition of ‘__pyx_pf_8mult_def_1A_a’
mult_def.c:214: error: previous definition of ‘__pyx_pf_8mult_def_1A_a’ was here
error: command 'gcc' failed with exit status 1
```

instead of failing in cython.  If the def is replaced by cdef or cpdef, cython catches it.

--Hoyt

Migrated from http://trac.cython.org/ticket/157

**Comment by da-woods** [comment]
This now compiles fine. It's slightly ambiguous which definition ends up being used (if seems to differ depending on binding) but it doesn't break anything.
