### ISSUE TITLE
Missing test: Raising exception from module init code

### ISSUE THREAD

**Issue by robertwb** [cython/cython#832]
This takes some effort to test for so not doing it now. http://trac.cython.org/ticket/271 would have been caught earlier with this.

Migrated from http://trac.cython.org/ticket/272

**Comment by da-woods** [comment]
https://github.com/cython/cython/commit/871377b440f7d43fdd8e225f74d18876f5a040e7#diff-73c15f009c0f485e769c2269e2fdb821eb54b0d2d24c44ed4c8e05fd89b5f4f9
