### ISSUE TITLE
Possible race condition w/ nogil exception propagation

### ISSUE THREAD

**Issue by robertwb** [cython/cython#841]
Given this example:

```
cdef int g() except -1 with gil:
    raise ValueError("test")

def f():
    cdef int a
    with nogil:
        g() # (a)
```

Here, the line marked (a) will generate code which writes to `__pyx_filename/lineno/...` in order to record information to put in the exception stack trace.

However, since it is in a nogil section, many threads can access those (global) variables at the same time. So if two exceptions are raised simultaneously in the same Cython module and at least one is in a nogil section then one stack trace could partially spill into the other.

Migrated from http://trac.cython.org/ticket/281

**Comment by scoder** [comment]
Closing. Variables are function-local now.
