### ISSUE TITLE
closures for module scope

### ISSUE THREAD

**Issue by robertwb** [cython/cython#868]
Function closure support has been implemented as of ticket http://trac.cython.org/ticket/82. The same mechanism is required for the module scope to support generator expressions and lambda expressions at the module level, and might be a suitable base to implement PEP 3121 support as of tickets http://trac.cython.org/ticket/173 and http://trac.cython.org/ticket/218.

At 2010-11-27T08:26:08Z @vitek added attachment [lambda-module-scope.patch](https://gist.github.com/ad1b4eefdd95ddd79cc1b32d2ff7a47d)

Migrated from http://trac.cython.org/ticket/308

**Comment by da-woods** [comment]
Generators at the module scope currently seem to work (module scope variables are looked up, rather than captured, but this is right I think)
