### ISSUE TITLE
Test suite for pyximport

### ISSUE THREAD

**Issue by robertwb** [cython/cython#881]
It would be a lot easier to review pyximport-related changes if we had a test suite for pyximport. I suppose it wouldn't be very difficult to do:

1) Have a directory structure with py and pyx and various configuration files in it

2) Have a test script which just copies this whole directory and then runs doctest on test_*.py in the directory (each probably in a new Python instance, to get pyximport and pyx modules loaded/unloaded).

Migrated from http://trac.cython.org/ticket/321

**Comment by scoder** [comment]
We have this now.
