### ISSUE TITLE
conjugate() method on complex numbers

### ISSUE THREAD

**Issue by robertwb** [cython/cython#954]
conjugate() method is not supported

```
cdef complex z = 1 + 1j
z = z.conjugate()
assert z == (1 - 1j)
```

Migrated from http://trac.cython.org/ticket/391

**Comment by vadimw2qcom** [comment]
Is real and imag supported in nogil mode. I can't get real or imag part of the complex number in nogil mode

**Comment by da-woods** [comment]
@vadimw2qcom Please ask support questions on the [cython-users](https://groups.google.com/forum/#!forum/cython-users) mailing list instead of on tangentially related issues. You'll probably get a better answer if you include some example code to show what's failing.
